### ISSUE TITLE
Logging in should revoke existing token if any

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#1]
If we're logging out to log in under a different account, we should revoke the existing token.

**Comment by leo** [comment]
[Here](https://github.com/zeit/now-app/blob/master/src/main/actions/logout.js)'s an example of how we're revoking the token in Now.app.

**Comment by codyzu** [comment]
Looks like Now.app revokes the token by calling:
**DELETE:** `https://zeit.co/api/www/user/tokens/{tokenId}`

What is the api call for now? Will this work?
**DELETE:** `https://api.zeit.co/now/registration/{token}`

@leo can you confirm on the server side what the api call should be?

**Comment by codyzu** [comment]
Looking through old issues... @leo any update on this?

**Comment by leo** [comment]
Yep, that's how it should be done. Not sure if he's talking about deleting the token from `~/.now.json` or about revoking it through the API. Can you test that, @codyzu? If the former is already the case, then the latter needs to follow.

**Comment by codyzu** [comment]
@leo ok I'll try to take a look tomorrow.
