### ISSUE TITLE
Ensure consistent `usage` error style

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#10]
Some commands display an error followed by the help message when using a sub-command wrong, and others just display the error.

We should switch to a hybrid, where we say:

```
> Error! Incorrect number of parameters supplied
> Usage: now alias add <from> <to>
> For further help and examples, run `now help alias`
```

**Comment by Ethan-Arrowood** [comment]
We have resolved this specific issue and made significant improvements to the error consistencies. This will continue to be improved upon in an upcoming feature: https://www.notion.so/vercel/5e74f5ecd5be463da1f6f3f6a7a108af
