### ISSUE TITLE
Now alias with custom domain doesn't recognize Zeit's DNS

### ISSUE THREAD

**Issue by jjant** [vercel/vercel#1005]
I have my custom domain on which I've set the DNS servers to `x.zeit.world` for `x = a..f`. I've done this more than a week ago, and get the following when trying to alias my domain:

```bash
$ now alias  my_app-iqplydjrcz.now.sh mydomain.com

> mydomain.com is a custom domain.
> Verifying the DNS settings for mydomain.com (see https://zeit.world for help)
> Resolved IP: none
> Nameservers: a.zeit.world, b.zeit.world, c.zeit.world, d.zeit.world, e.zeit.world, f.zeit.world
> Error! Please make sure that your nameservers point to zeit.world.
> Examples: (full list at https://zeit.world)
> - california.zeit.world    173.255.215.107
> - newark.zeit.world        173.255.231.87
> - london.zeit.world        178.62.47.76
> - singapore.zeit.world     119.81.97.170
> Alternatively, ensure it resolves to alias.zeit.co via CNAME / ALIAS.
```

I've also tried using the domains listed there (which I suppose are outdated): `california.zeit.world`, etc. but couldn't get it to work. If it changes anything, I got my domain from `namecheap.com`

**Comment by andrerfneves** [comment]
I have been facing the exact same issue. I decided to use the CNAME record route but that has yet to work. I also got my domain from NameCheap. It either it taking much longer to propagate, or there is an issue. I have other NameCheap domains that work fine, but I initially `alias`ed them months ago - not sure if anything has changed since then.

**Comment by codeofsumit** [comment]
same issue for me. I added the zeit nameservers to a `.io` domain. I can add DNS entries via now cli to it, but the verification won't work.
It's NOT a namecheap.com domain though.

**Comment by OlliV** [comment]
Make sure that you are using the latest now client version.

For domain verification issues, use `now domain add -f <yourdomain>`
