### ISSUE TITLE
--follow on the alias fails with "Error! Unexpected error. Please try again later. (undefined)"

### ISSUE THREAD

**Issue by yodertv** [vercel/vercel#1008]
'''
mikes-air:Todos mike$ now logs -d -f reminders.now.sh
> [debug] Socket connected
> [debug] Socket disconnect
> Error! Unexpected error. Please try again later. (undefined)
'''

Works on the instance URL. Thanks, -Mike

**Comment by leo** [comment]
cc @matheuss

**Comment by TooTallNate** [comment]
@yodertv Can you try again please? According to the commit logs, this should have been fixed on December 15, 2017.
