### ISSUE TITLE
Respect bash-coding conventions by providing non-zero exit code when error is happening

### ISSUE THREAD

**Issue by inem** [vercel/vercel#1009]
Otherwise it is impossible to use `now` cli in CI systems. Here the build marked as succeeded even when `now` command has failed:

![image](https://user-images.githubusercontent.com/9665/33230803-5e9ee72a-d1ea-11e7-9402-6f664e55d380.png)

**Comment by brettdh** [comment]
Surprised that an issue this significant has sat untouched for so long. This affects _any_ scripting with `now`, not just CI (though CI is my current pain point as well).
