### ISSUE TITLE
now alias - maximum number of concurrent instances exceeded 

### ISSUE THREAD

**Issue by maticzav** [vercel/vercel#1014]
Hi,

I have noticed that whenever I run `now alias`, which repoints new deployment to my url, it first creates the new scaled version of new instance and only later on downscales the old one. Due to this many attempts to `alias` my webpage fail, as the number of concurrent instances is exceeded. 

Would it be possible to first downscale the old deployment and then upscale the new one?

**Comment by ewolfe** [comment]
You would lose out on "zero downtime" deployments. You could do something like:

```sh
now scale example.now.sh 1
now
now alias
now rm example --safe --yes
```
