### ISSUE TITLE
/_src returning an error

### ISSUE THREAD

**Issue by jacc** [vercel/vercel#1016]
Sorry for this, I didn’t really know where to go to get support for now.sh

Adding /_src to any URL returns ‘An unexpected error occurred’

Even the demo URL: https://zeit.co/IHQQXNOCXXS5uyEmGAfEEBsB/my-app/erkgfjtrna/source

Is this a problem that will be fixed?

**Comment by ghost** [comment]
did you make sure to deploy public so /_src can be accessed by anyone

**Comment by jacc** [comment]
@ThiccCat yes, its not working for any Zeit-deployed app

**Comment by ghost** [comment]
found potentional fix

after [login](https://zeit.co/login) it allows to see source

**Comment by timneutkens** [comment]
Logged as a bug internally, thanks for surfacing @jacc!

**Comment by timneutkens** [comment]
@jacc @ThiccCat the issue is fixed and deployed to production. You'll be able to access the url without being logged in (only for the OSS plan ofcourse). Thanks again!
