### ISSUE TITLE
Allow `export VAR="value"` syntax in dotenv files

### ISSUE THREAD

**Issue by schickling** [vercel/vercel#1017]
It's a quite common use case to use the `export` keyword in `.env` files which enables you to run `source .env` without the need to additionally install any kind of tooling. Currently the `now` CLI doesn't pick up env vars prepended by an `export` statement.

Please support this case as well. 👍

**Comment by pranaygp** [comment]
Seems like the npm `dotenv` maintainers made the decision *not* to support `export` statements within `.env` files (https://github.com/motdotla/dotenv/pull/118)

It also seems as if the suggested course of action is to use this auxiliary package (https://github.com/AndersDJohnson/dotenv-export) on a regular .env file (without the "export" statements)

**Comment by leo** [comment]
Sounds like a good idea if we can just support it without breaking the usual behaviour.

Though it seems like the package that was suggested (dotenv-export) is just a CLI for modifying existing dotenv files that don't yet have the keyword.

What we need is a package that supports parsing both the usual dotenv files and those with the `export` keyword inside.
