### ISSUE TITLE
Unable to enter Name when `now cc add`

### ISSUE THREAD

**Issue by bodadotsh** [vercel/vercel#1018]
Full Name input becomes terminal input again for some reason

![screen shot 2017-12-02 at 21 01 45](https://user-images.githubusercontent.com/6238558/33519704-2b5b670c-d7a4-11e7-958b-4c70bb75e824.png)

**Comment by matheuss** [comment]
I can reproduce 😩 Thanks a lot for reporting – will fix it ASAP!

**Comment by TooTallNate** [comment]
Closing because I can not reproduce using the latest version of Now CLI. Let us know you are still experiencing this.
