### ISSUE TITLE
An Dockerfile without `EXPOSE` line will cause the app crashing

### ISSUE THREAD

**Issue by idealhack** [vercel/vercel#1019]
```
12/04 05:21 PM (10m) docker build
...
12/04 05:22 PM (10m) Storing image
12/04 05:22 PM (9m) Deploying image
12/04 05:22 PM (9m) Container started
12/04 05:24 PM (7m) Deploying image
12/04 05:24 PM (7m) Container started
12/04 05:24 PM (7m) + exec app
12/04 05:24 PM (7m) Deploying image
12/04 05:24 PM (7m) Container started
12/04 05:24 PM (7m) + exec app
12/04 05:25 PM (7m) Deploying image
12/04 05:25 PM (7m) Container started
12/04 05:25 PM (7m) + exec app
12/04 05:25 PM (6m) Deploying image
12/04 05:25 PM (6m) Container started
12/04 05:25 PM (6m) + exec app
12/04 05:26 PM (6m) Deploying image
12/04 05:26 PM (6m) Container started
12/04 05:26 PM (6m) + exec app
12/04 05:27 PM (4m) Deploying image
12/04 05:27 PM (4m) Container started
```

A Dockerfile deployment of Go service seems keep crashing, same code works on my machine.

After read https://github.com/zeit/now-cli/issues/326#issuecomment-297856078 I add the `EXPOSE` line and it's deploying.

P.S. This is an issue I posted on slack - https://zeit-community.slack.com/archives/C1TMPLCKS/p1512380060000075

**Comment by idealhack** [comment]
seems #237 is related

**Comment by timneutkens** [comment]
All services are required to expose a port until #146 is resolved.
Documentation can be found here: https://zeit.co/docs/deployment-types/docker#port-selection

We can catch this mistake early on though. So that you don't have to wait for it to fail catching the port.

**Comment by idealhack** [comment]
I’m closing this because it seems to be inactive for months. If anyone feel this issue still matters, feel free to reopen it.
