### ISSUE TITLE
Bad request: Missing  `name` field

### ISSUE THREAD

**Issue by prakhar1989** [vercel/vercel#102]
Hey Everyone,

I've been trying to deploy a Docker container with now, and I'm constantly getting the following error -

```
$ now --docker
> Deploying ~/Code/jsjs-web
> Error! Bad request. Missing `name` field.
```

Things I tried to fix this (on Now v0.27.0) - 
1. Relogin
2. Deploying static files to now and then retrying.
3. Trying it with another email
4. Asking a couple of friends to create an account and try to deploy other docker files with their logins.

Sadly, none of these worked.  Here's a screenshot if it helps

![dokcer](https://cloud.githubusercontent.com/assets/649249/19822882/bb517542-9d33-11e6-8f12-bc2457edebe2.png)

Any ideas on how to fix this?

**Comment by pqvst** [comment]
Add `LABEL name="app_name"` to your Dockerfile

**Comment by prakhar1989** [comment]
@pqvst Yes! This works - thanks a lot. The funny thing is that the very same `Dockerfile` deployed successfully for matheus. Anyway, I'll close this issue - thanks a ton again!

**Comment by TooTallNate** [comment]
I agree this seems weird. I've never had to have that line in my Dockerfiles before.

**Comment by OlliV** [comment]
Fixed here: https://github.com/zeit/now/commit/f31d1f0804f5583a5cc3b4597adbb1e200447860
