### ISSUE TITLE
Trying to scale a domain with rules throws an error

### ISSUE THREAD

**Issue by mxstbr** [vercel/vercel#1021]
Let's say I have domain `asdf.com`, and I've run the following command where `rules.json` contains some path aliases:

```JS
$ now alias asdf.com -r rules.json
```

It doesn't matter what those are, but now when I try running the scale command the CLI just throws an error:

```JS
$ now scale asdf.com 1
> Error! Unknown error: TypeError: Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
  at run (/snapshot/now-cli/dist/now.js:8125:13)
  at <anonymous>
```

This should probably log a nice warning instead of the TypeError like "Domain points to path alias rules, nothing to scale."

**Comment by timneutkens** [comment]
Thanks for reporting @mxstbr created a PR to fix this 👌
