### ISSUE TITLE
`now alias` throws error on .es domains: WHOIS error

### ISSUE THREAD

**Issue by mattrei** [vercel/vercel#1023]
Hi,

the problem seems to be related to _es_ domains.
I have set on my domain the nameservers to Zeit's however a `now alias` fails gracefully:

```

now alias -d https://out-atuemambeo.now.sh vroodl.es
> [debug] GET /v2/now/deployments: 1037.283ms
> [debug] matched deployment iiecnh8yeLymAds4y5DFBuEX by url out-atuemambeo.now.sh
> vroodl.es is a custom domain.
⠇ Fetching domain info> [debug] #1 GET /domains/status?name=vroodl.es: 637.552ms
> Verifying the DNS settings for vroodl.es (see https://zeit.world for help)
> [debug] #1 GET /domains/price?name=vroodl.es: 767.304ms
> [debug] bailing on get domain due to 404
> [debug] #1 GET /whois-ns: 201.909ms
> [debug] Retrying: Error: Invalid whois response
Error: Invalid whois response
    at module.exports.EventEmitter.getNameservers.Promise.retry (/snapshot/now-cli/dist/now.js:811:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #2 GET /whois-ns-fallback: 2990.622ms
> [debug] Retrying: Error: Whois error (500): An unexpected internal error occurred
Error: Whois error (500): An unexpected internal error occurred
    at module.exports.EventEmitter.getNameservers.Promise.retry (/snapshot/now-cli/dist/now.js:821:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #3 GET /whois-ns-fallback: 2930.091ms
> [debug] Retrying: Error: Whois error (500): An unexpected internal error occurred
Error: Whois error (500): An unexpected internal error occurred
    at module.exports.EventEmitter.getNameservers.Promise.retry (/snapshot/now-cli/dist/now.js:821:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #4 GET /whois-ns-fallback: 2426.949ms
> Error! Unknown error: Error: Whois error (500): An unexpected internal error occurred
Error: Whois error (500): An unexpected internal error occurred
    at module.exports.EventEmitter.getNameservers.Promise.retry (/snapshot/now-cli/dist/now.js:821:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I have already asked help at the zeit slack chat, however it seems to be a bug.

Best

**Comment by OlliV** [comment]
Hi, try adding the domain with `now domain add -f domain.es` and then try aliasing again.

**Comment by mattrei** [comment]
Hi, thanks for your quick answer.

It does not allow me, because I need a premium account for that. 
Is there any chance without the need of having one yet? I am thinking of getting one, however first I have to do more tests with Next.js before myself buying in.

**Comment by OlliV** [comment]
Yes you need at least Premium plan for adding domains. You can contact our support for that request.

**Comment by mattrei** [comment]
ok i have now signed up for a premium account, i get the following error:
```
$ now domains add -d -f -e vroodl.es
> [debug] #1 POST /domains: 1007.362ms
> Error! Not authorized to access domain vroodl.es
```

Please note that the domain is registered with an external provider. The nameservers are set to a.zeit.world, etc.

**Comment by mattrei** [comment]
Are there any updates on this? Why is it not working? I think that it is a bug.

**Comment by OlliV** [comment]
@mattrei in that case `-e` is not needed. Only if the nameservers are not set to a-f.zeit.world. It seems that the domain already exist for a team. Maybe you forgot to `now switch`?

**Comment by mattrei** [comment]
@OlliV  sorry my fault, the error message was confusing for me ;). I got it working now. 
(The nameserver verification does not work though, I have to force it with `-f`). Thx for helping out!

**Comment by timneutkens** [comment]
@mattrei no worries! I've created a pull request to add a clear description to the error you saw (not authorized to access domain) 👍
