### ISSUE TITLE
Confused behavior with: now alias and now rm.

### ISSUE THREAD

**Issue by saeta-eth** [vercel/vercel#1027]
Hi,

I tested your products in the last days. Really good work guys!
I will explain my issue by steps.

1 - I deployed my app and It provided me a new url
2 - I used `now alias` command to connect the deploy with a subdomain (lala.example.com).
3 - I removed my deploy with `now rm` command using the url I had in the step 1.

> -- up to this point, all seems normal --

4 - Opened my browser and my subdomain is running with the deployment removed.

Is there a way to put the subdomain as disabled?
Thanks!

**Comment by leo** [comment]
@slorenzo You can remove the alias using `now alias rm`. You'll find more details when running `now alias -h`. IIRC, it might take some time until deployments are fully gone! 🤔 

cc @matheuss

**Comment by saeta-eth** [comment]
Hi @leo 

How much time is needed to remove a subdomain? I did it 6 days ago.
I followed your comments, but the subdomain is running.

**Comment by OlliV** [comment]
The subdomains are always enabled as there is typically a `CNAME` `*.domain.com => alias.zeit.co`

**Comment by saeta-eth** [comment]
Hello @OlliV.

If I use `now alias rm lala.mydomain.com` when I open this URL, it should be enabled?
I "created" a subdomain using `now alias url-deploy lala.mydomain.com` just for test reason but I can't remove it.

**Comment by OlliV** [comment]
If you want to "disable" the URL you should remove the certificate created for the alias: `now certs rm lala.mydomain.com` in addition to removing the alias.

**Comment by saeta-eth** [comment]
Hi @OlliV,

It doesn't work for me, I did what you said but the url exists and I can open it using my browser.
I removed the both things: certificate and alias.

Another suggestion?
