### ISSUE TITLE
Running with npx causes confusing output

### ISSUE THREAD

**Issue by SteveALee** [vercel/vercel#1035]
With a project local install of now when I run `npx now <cmd>` the first line output is `null`. This does not happen when running `./node_modules/.bin/now.cmd`

I'm on Windows

**Comment by leo** [comment]
This only seems to be the case on Windows!

**Comment by SteveALee** [comment]
Typical!! :)
Do you think is an upstream issue? I do not see it with other commands

**Comment by leo** [comment]
We should definitely fix this!

**Comment by TooTallNate** [comment]
<img width="320" alt="Screen Shot 2019-08-09 at 4 21 02 PM" src="https://user-images.githubusercontent.com/71256/62813870-00b82280-bac2-11e9-9265-4158ea9ab0b6.png">

Closing because I can not reproduce this. Let us know if this is still occurring for you and we will take a closer look.
