### ISSUE TITLE
`now alias` and Cloudflare

### ISSUE THREAD

**Issue by robertoachar** [vercel/vercel#1036]
Hi, I can't get my site up and running even following all the docs available. I'm from Brazil and I guess it's related to it. I received an error saying: **You don't have access to "br"**.

## Whois Information
[http://whois.domaintools.com/cervejamurano.com.br](http://whois.domaintools.com/cervejamurano.com.br)

### Status

![cloudflare-active](https://user-images.githubusercontent.com/7755073/33835729-8e8f669a-de6e-11e7-9d60-c01f18a40b1b.png)

### DNS

![cloudflare-dns](https://user-images.githubusercontent.com/7755073/33835801-c40fd2d2-de6e-11e7-9746-2fccfc54bcaa.png)

### Crypto

![cloudflare-crypto](https://user-images.githubusercontent.com/7755073/33835850-e963aafe-de6e-11e7-8e21-d7589e613213.png)

### Page Rules

![cloudflare-page-rules](https://user-images.githubusercontent.com/7755073/33835920-12921af0-de6f-11e7-94a0-60ac3f56a8d3.png)

### Domains

```bash
$ now domain ls
> 2 domains found under robertoachar [1s]

  domain                dns       verified  created
  cervejamurano.com.br  external  true      43m ago
  ...
```

### Alias

```bash
$ now alias cerveja-murano-cnfynnjodf.now.sh cervejamurano.com.br
> cervejamurano.com.br is a custom domain.
> Verifying the DNS settings for cervejamurano.com.br (see https://zeit.world for help)
> Verification OK!
> Error! Unknown error: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.Now.createAlias.alias.retry (C:\snapshot\now-cli\dist\now.js:3887:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

### Certs

```bash
$ now cert create cervejamurano.com.br
> Error! Unexpected error. Please try again later. (You don't have access to "br")
```

## Website

![website](https://user-images.githubusercontent.com/7755073/33836208-e94e7eee-de6f-11e7-9df2-910d327c506e.png)

**Comment by OlliV** [comment]
Hi,

We identified a bug in our backend related to adding a domain. The bug should be fixed by now. Could you try aliasing again.

**Comment by robertoachar** [comment]
Hi Olli,

I just tried again but I got this error.

```
    $ now alias cerveja-murano-iguvowgcoc.now.sh cervejamurano.com.br
    > cervejamurano.com.br is a custom domain.
    > Verifying the DNS settings for cervejamurano.com.br (see https://zeit.world for help)
    > Verification OK!
    > Provisioning certificate for cervejamurano.com.br
    > Error! Unknown error: Error: Invalid challenge response for cervejamurano.com.br. Make sure the DNS records are correct.
    Error: Invalid challenge response for cervejamurano.com.br. Make sure the DNS records are correct.
        at module.exports.EventEmitter.createCert.domain.retry (C:\snapshot\now-cli\dist\now.js:924:15)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:188:7)
```

So I switch off the "Alway use HTTPS" on Cloudflare and works!

Thank you so much for it. I really appreciate that.

**Comment by TooTallNate** [comment]
@robertoachar So you're all good then it sounds like? If so we can close this issue.

**Comment by robertoachar** [comment]
Thanks guys!

**Comment by morgs32** [comment]
Do we have to leave it off?

**Comment by morgs32** [comment]
@robertoachar

**Comment by aviaryan** [comment]
I also have the same setup but getting the 525 mismatch error.
