### ISSUE TITLE
Update `libvips` version

### ISSUE THREAD

**Issue by elrumordelaluz** [vercel/vercel#1037]
Hi Zeit team,

With the help of @lovell in [this issue](https://github.com/lovell/sharp/issues/1058) and based on #639 seems that the globally-installed version of `libvips` doesn't support `svg`.

Is there a way to use another version? 

Is it possible to compile a greater one with more support?

Thanks in advance,

**Comment by leo** [comment]
@TooTallNate just mentioned that we're using [this](https://pkgs.alpinelinux.org/package/edge/testing/x86/vips). Maybe we need to install an addition plugin?

**Comment by lovell** [comment]
Hello, you'll probably want to modify https://github.com/alpinelinux/aports/blob/master/testing/vips/APKBUILD to include librsvg as a dependency if using `vips` from Alpine's "testing" repo.

**Comment by TooTallNate** [comment]
We'll be deploying a fix for this later today

**Comment by TooTallNate** [comment]
@elrumordelaluz OK please give it a try now. Thank you for your patience.

**Comment by elrumordelaluz** [comment]
thank you @TooTallNate 
here is the working (perfect) example https://elrumordelaluz.github.io/micro-outline-stroke/
