### ISSUE TITLE
Can't upload a project due to file size issues, not told how much I can use

### ISSUE THREAD

**Issue by cfjedimaster** [vercel/vercel#1038]
I'm trying to push up a (I think) relatively small Node project. When I run `now`, I get:

```
> Error! Upload failed
> Error! An unexpected error occurred in deploy: Error: File size limit exceeded
    at responseError (/snapshot/now-cli/dist/now.js:187:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Ok, fair enough, but what *is* the limit? And what can I do to help fix the problem? As I said, it isn't a terribly big project. I assume node_modules is big, but that's not being pushed up I assume.

**Comment by cfjedimaster** [comment]
Using -d I can see it is one particular file, a 3.5 meg video file. Is that really too big?

**Comment by cfjedimaster** [comment]
So I guess to summarize - the CLI should have said, *without* the debug flag, what file was too big. Also, do you document the largest individual file size? Honestly 3.5 megs seems small to be blocked.

**Comment by cfjedimaster** [comment]
Ok, in the pricing plan I see it - 1 meg is the max. That feels.... low, but ok. But really - if the CLI had just said as much (again, w/o using -d), it would have been really helpful.

**Comment by rauchg** [comment]
Agreed that we should make the message more clear! Thanks for the feedback

**Comment by g-a-v-i-n** [comment]
I seem to recall the way this used to work was that files that violated the size limit were gracefully ignored. Has this changed?

**Comment by cfjedimaster** [comment]
I wouldn't do that - I mean in my case they were files I could just delete, and a flag of some sort to ignore would be cool, but it shouldn't be the default imo.

**Comment by rauchg** [comment]
Yep I think it'd be a dangerous default with subtly-hard-to-debug bugs. But, an option is indeed nice @gavinpatkinson

**Comment by sreeramjayan** [comment]
@rauchg @cfjedimaster 
I would like to contribute to now. Is this still an existing issue? I am on the OSS plan and tried deploying a static application and the behavior I see is that as @gavinpatkinson mentioned large files are ignored and deployment continues. Is the desired behavior to provide an option that lets the user know that deployment cannot occur and list the large files?

The odd part is that even though I am on the OSS plan, I am able to upload files > 40MB. Going by https://zeit.co/pricing isn't the max file size for the OSS plan 1MB?

**Comment by OlliV** [comment]
Yes the limit for OSS is 1 MB per file.

**Comment by OlliV** [comment]
We are now printing the plan limit:
```
> Error! Upload failed
> Error! An unexpected error occurred in deploy: Error: File size limit exceeded (1 MB)
    at responseError (/snapshot/now-cli/dist/now.js:199:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by OlliV** [comment]
@sreeramjayan if you'd like to improve the UX, we should probably do something to the `responseError()` function that now hides `error.code` and makes it impossible to show proper error messages in places where it's used.

**Comment by cfjedimaster** [comment]
Any chance you could share the file that was over the limit? Obviously it is my directory of stuff, but imagine I've got a large set of files.

**Comment by sreeramjayan** [comment]
@OlliV  @cfjedimaster  I was able to upload 2 50MB with my OSS plan. 
Here is the link to my deployment:
https://test-nmcmarknvi.now.sh

**Comment by OlliV** [comment]
@sreeramjayan that has been an error on our side, it shouldn't be possible.

**Comment by rauchg** [comment]
@sreeramjayan it should be rectified now. We also improved the `now-cli` error to be more clear.
