### ISSUE TITLE
request processing time - too high

### ISSUE THREAD

**Issue by playerx** [vercel/vercel#1039]
First of all this issue is for now.sh cloud itself, not for cli, but I didn't found any other repository for such an issue, that's why I've created it here, If its not in correct place sorry and please give me some direction where should I create it.

I was comparing request processing time in now.sh vs heroku. I've created simple graphql server with tracing and here are the results:
Now.sh
![now](https://user-images.githubusercontent.com/1698274/33932650-629445b6-dfa8-11e7-844e-7cec3dd9657c.PNG)

Heroku
![heroku](https://user-images.githubusercontent.com/1698274/33932655-6722ac4e-dfa8-11e7-80fe-4572ec77a06d.PNG)

This is the time after request sent successfully and server is processing, based on that region is not necessary here but for information both (now.sh & heroku) servers are in US.

Also I'm using free tier in now.sh and can it be the reason ?

P.S. I do some researches right now, for future infrastructure and I really liked now.sh with its pricing & cli, but that factor is really important and will be happy if you will give me more information about that.

P.P.S. the results are not for first run, first run needs more time, this is results after multiple run same query, in both cases

query that I ran in graphql is simple:
``` gql
type Query {
   hello: String
}
```
``` js
const resolvers = {
    Query: {
        hello: () => null
    },
}
```

**Comment by Qix-** [comment]
Hi - are you using HTTPS when connecting to Heroku? There are a _lot_ of steps in a request and having a better breakdown would be beneficial here. Otherwise, it's a complete guessing game.

**Comment by playerx** [comment]
Yes it's https in both cases, I've created repo: https://github.com/playerx/paas-performance-test

So my questions are:
* If I'll have another kind of subscription (not free one) will I have the same picture?
* Am I doing something wrong, should I meter the performance with another way? 

one more screen, processing time with browser waiting time:
<img width="1327" alt="screen shot 2017-12-13 at 22 30 59" src="https://user-images.githubusercontent.com/1698274/33955600-829c22e0-e055-11e7-88bb-ec9b201b5cac.png">

**Comment by Qix-** [comment]
Could you show ping times to each server?

---

> If I'll have another kind of subscription (not free one) will I have the same picture?

Potentially; the open source plan has lower resources allotted to deployments and lower bandwidth guarantees.

> Am I doing something wrong, should I meter the performance with another way?

The network panel in your last screenshot is a bit more telling than lumping _all_ of the time under `request`. Connection time is a large portion of requests and SSL handshaking can incur some cost, too.

The waiting is a little troublesome - upon trying the Now version I see the reporting isn't very accurate:

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/885648/33957666-1eb2b0ae-dff7-11e7-83f5-4f603bde6723.png">


309ms is not at all close to the 1847ms the tool is reporting.

As well, I'm seeing similar times to Heroku:

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/885648/33956640-0d522428-dff4-11e7-959f-42b0246b34d2.png">

As with the Now example, it appears the tool's timing mechanism is off here, too.

**Comment by playerx** [comment]
```
PING https://paas-performance-test-dfqsnqkmox.now.sh (130.211.93.80): 56 data bytes
64 bytes from 130.211.93.80: icmp_seq=0 ttl=43 time=78.624 ms
64 bytes from 130.211.93.80: icmp_seq=1 ttl=43 time=80.317 ms
64 bytes from 130.211.93.80: icmp_seq=2 ttl=43 time=106.854 ms
64 bytes from 130.211.93.80: icmp_seq=3 ttl=43 time=78.409 ms
64 bytes from 130.211.93.80: icmp_seq=4 ttl=43 time=78.278 ms
```

I'm not in US, but ping is good.

Its strange that tracing doesn't work for you, can you try chrome ? maybe apollo tracing has some issue. Also can you try to run same query multiple times.

Can you show the picture for Now.sh? in both pictures there are heroku in url.

**Comment by Qix-** [comment]
Apologies, not sure how that happened. Updated the screenshot in https://github.com/zeit/now-cli/issues/1039#issuecomment-351486202.

**Comment by Qix-** [comment]
Here it is on Chrome:

![image](https://user-images.githubusercontent.com/885648/33957720-4b704390-dff7-11e7-9822-605b1eb8561c.png)

![image](https://user-images.githubusercontent.com/885648/33957798-81fda74a-dff7-11e7-95a9-2408bd50757c.png)

**Comment by Qix-** [comment]
Heroku seems a bit volatile:

![kapture 2017-12-13 at 11 21 14](https://user-images.githubusercontent.com/885648/33957970-01c0e9ba-dff8-11e7-8e75-cf62a183d30b.gif)

Whereas now is a little more consistent:

![kapture 2017-12-13 at 11 22 33-now](https://user-images.githubusercontent.com/885648/33957982-0e6bbeb0-dff8-11e7-8cbf-242b37fccc3b.gif)

Our TTFB times are going to decrease in the coming months as we make improvements to our internal networking design.

**Comment by playerx** [comment]
Now I really don't understand, same resource, same server and 2 different clients:
1. your request was processed in 183ms
2. my request was processed in 773ms

Do you have any idea?

I'm located in another part of the world, in [Georgia](https://www.google.ge/maps/place/Georgia/@42.3029889,41.1146059,7z/data=!3m1!4b1!4m5!3m4!1s0x40440cd7e64f626b:0x4f907964122d4ac2!8m2!3d42.315407!4d43.356892?hl=en), can it matter? 

P.S. thanks for helping me

**Comment by playerx** [comment]
300-400 ms is okey for me, but for me its 700-1000 every time I try at Now.sh

**Comment by Qix-** [comment]
Yes, it definitely can. Your route to Heroku's datacenters could be drastically different than the route to Now's datacenters, especially since you're quite far away. Route topology makes a huge difference in response times.

Just out of curiosity, what is the difference between https://sfo.now.sh and https://bru.now.sh for you? Our Belgium datacenter is being rolled out and will become generally available in the coming months, which I would imagine will be a much better connection.

**Comment by Qix-** [comment]
It's also worth mentioning I'm connecting from San Francisco, California.

**Comment by playerx** [comment]
https://bru.now.sh - 3225 km   80-100 ms

So this is request processing time by server + routing time. I thought it was just request processing time, thanks.

One more question, is there any way to select server(s) where I want to host, I've found it in now.json configuration but didn't found available values, server list.

**Comment by playerx** [comment]
https://sfo.now.sh - 11105 km  300-340 ms

**Comment by Qix-** [comment]
Yeah those ping times sound about right.

Right now, no - we only have one datacenter location here in San Francisco. In the coming months we'll be rolling out functionality to scale up deployments in our Belgium datacenter, which is probably what you're after. :)

**Comment by playerx** [comment]
Great thank you so much !

**Comment by Qix-** [comment]
No problem :) 👋

**Comment by luisherranz** [comment]
I'm having the same problem here. 

I'm in Spain with a 1000Mb connection. The latency to the new Brussels servers is really good, 34ms: https://bru.now.sh/ 

But a simple hello-world takes always more than 600ms to load: https://tye-billing-utyfruxnox.now.sh/
That's from my personal account (free) but I've tried from my company's account (pro) with the same result.

I've uploaded the same hello-world example to Google Cloud and takes only 50-100ms: https://hello-world-193417.appspot.com/

We'd like to stick with now because we love its simplicity, but this extra 500ms are quite important for what we are building.

Is there something we can do about it? If the ping is so good, why is it taking so long to answer?

> Our TTFB times are going to decrease in the coming months as we make improvements to our internal networking design

Will that help in this case? If so, how much? Is there any ETA for this improvements?

**Comment by luisherranz** [comment]
By the way, I'd like to add that I've tried on different networks (home, mobile) with the same result. 

And as a test I also did a deploy of Kubernetes on Google Cloud with the same hello-world example and the same result: it took only 50-100ms to answer (I've deleted it now).

**Comment by luisherranz** [comment]
@dohomi no, I'm getting 50-100 ms on bru1 now. The exact same performance than in Google Cloud.
