### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by xxczaki** [vercel/vercel#1042]
Hi,
I'm using now to host my website. Is there any way to enable caching with now? .htaccess doesn't work there :(

**Comment by pranaygp** [comment]
Depends on how your site is implemented. I'm assuming you're deploying a static website (if you're using node/express, you'll have to implement it [yourself](https://stackoverflow.com/questions/9470603/node-js-express-caching#9847524))

If you already have a static website that you're able to deploy with `now`, then I believe `now` simply uses [serve](https://github.com/zeit/serve) to serve up your files. Good to know that `serve` has a flag `--cache` to cache files on the browser. A simple setup for your project would be:

1. Go to your project folder
2. `npm init`
3. `npm install --save-dev serve`
4. Add this to the new package.json file in your directory:
```
  ...
  "scripts": {
     "start": "serve . --cache 216000"
  }
  ...
```

Running `now` after that should set it up using a server and enable caching (for 216000ms)

It doesn't give you the same control as .htaccess though

**Comment by sergiodxa** [comment]
You can also create a Dockerfile and run Apache inside it to use `.htaccess`, then deploy the container to Now.

**Comment by timneutkens** [comment]
Lets close this since there's multiple answers. @xxczaki if this didn't solve your issue please let us know and we'll re-open 👍 ❤️
