### ISSUE TITLE
Cloudflare's cf-connecting-ip header is not forwarded

### ISSUE THREAD

**Issue by satyavh** [vercel/vercel#1043]
I'm using Zeit cname config with external domain, Cloudflare in front (dns).
It turns out that Zeit is not forwarding the `cf-connecting-ip` header from Cloudflare. That header contains the original IP the request is coming from.

How can I get access to this header?

**Comment by timneutkens** [comment]
@satyavh can you check if `X-Forwarded-For` contains the user IP address?

**Comment by satyavh** [comment]
x-forwarded-for contains Cloudflare's ip.
But I've noticed `cf-connecting-ip` is now included in the headers. Now sure what has changed :-|
Closing this now. Sorry to bother.

**Comment by timneutkens** [comment]
No worries!
