### ISSUE TITLE
502  An error occured with your deployment.

### ISSUE THREAD

**Issue by lesliedoghouse** [vercel/vercel#1047]
Deploy success but got such error.

7 out of 10 times deploy I'll get weird new error... 

Unreliable service.

**Comment by lesliedoghouse** [comment]
Not to mention an app hosting service that has no way to contact support team. Bravo guys!

**Comment by sergiodxa** [comment]
Hello. 

You can contact us here, on our slack community or via email to support@zeit.co.

Anyway, what error so you see? Did you checked the logs with `now logs` or appending `/_logs` to the URL?

If you don't see anything let me know the deployment URL.

**Comment by rauchg** [comment]
@lesliedoghouse In many cases an error in your codebase yields this. We don't see any errors in our backends that could yield 7/10 failed deployments. Please reach out to support and we'll be happy to take a look at this specific case

**Comment by lesliedoghouse** [comment]
I run my app locally without error

Now you blame my code and close my issue. And you say can contact support at here. But without solving the problem and close my issue instead. Brilliant! Damn it... I have enough with zeit

**Comment by rauchg** [comment]
@lesliedoghouse sometimes your app runs locally perfectly but experiences issues in production. Since we don't see a log of failing deployments, that's one possibility.

I'm closing the issue because it doesn't belong in the CLI repository. Feel free to reach out to support@zeit.co and we'll happily discuss it there!

**Comment by Alexintosh** [comment]
Same problem here, logs are fine:

```
04/04 03:59 PM (5m)
npm install
04/04 03:59 PM (5m)
✓ Using "yarn.lock"
04/04 03:59 PM (5m)
⧗ Installing 3 main dependencies…
04/04 03:59 PM (5m)
yarn
04/04 03:59 PM (5m)
yarn install v1.5.1
04/04 03:59 PM (5m)
warning package.json: No license field
04/04 03:59 PM (5m)
warning rewebrtc-server@0.0.1: No license field
04/04 03:59 PM (5m)
[1/4] Resolving packages...
04/04 03:59 PM (4m)
[2/4] Fetching packages...
04/04 03:59 PM (4m)
[3/4] Linking dependencies...
04/04 03:59 PM (4m)
[4/4] Building fresh packages...
04/04 03:59 PM (4m)
Snapshotting deployment
04/04 03:59 PM (4m)
Saving deployment image (3.1M)
04/04 04:00 PM (4m)
npm start
04/04 04:00 PM (4m)

> rewebrtc-server@0.0.1 start /home/nowuser/src
> node app.js
04/04 04:00 PM (4m)

Rewebrtc-server is up and running at 80 port
```

**Comment by pantharshit00** [comment]
Receiving same error after 11.x update
