### ISSUE TITLE
Use now to deploy on my own server

### ISSUE THREAD

**Issue by HarshOB** [vercel/vercel#1050]
Is there any documentation that will guide me to deploy my site on my own server using now and also I can use my DNS.

**Comment by thebaconnaut** [comment]
There's [Up.](https://github.com/apex/up)

**Comment by rauchg** [comment]
@HarshOB we are working on [Universal Now](https://zeit.co/blog/universal-now) and other exciting new additions to the Now product lineup in 2018 to address on-premise and beyond. Stay tuned!
