### ISSUE TITLE
Provisioning certificate issue

### ISSUE THREAD

**Issue by dimroth** [vercel/vercel#1053]
Hey Now team ! Thanks for your wonderful work.

I've changed my website registrar few weeks ago and switched hosting to Now. I have been trying, since DNS were changed to `zeit.world` on Namecheap, to deploy a static file to the main domain and a NPM package to a `blog` subdomain.

Unfortunately, it has been at least a week I get this error for both actions : 
```
➜ now alias file-xxxxx.now.sh mydomain.co
> mydomain.co is a custom domain.
> Verifying the DNS settings for mydomain.co (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for mydomain.co
> Error! The certificate issuer failed to verify ownership of the domain. This likely has to do with DNS propagation and caching issues. Please retry later!
```

Does it really have something to do with DNS propagation ? Can I help SSL certificate to finally issue correctly with Let's Encrypt acme challenge subfolder ? Do I just have to wait ?

Thanks in advance for your much appreciated help ! I am really stuck here.

**Comment by timneutkens** [comment]
Hey @dimroth, could you email the domain that's failing to alias to support@zeit.co if you don't want to share it in public. Thanks in advance!

**Comment by dimroth** [comment]
In case a solution can be found faster with your help @timneutkens, domain name is **aircampus.co**. Thanks a lot !

**Comment by OlliV** [comment]
Hi @dimroth,
The reason seems to be that Let's Encrypt can't find the A records for your domain. To me it seems that the nameserver used by Let's Encrypt is caching records for longer than TTL, since it's not the first time I'm seeing such an issue. These issues usually resolves without human intervention. Let's check again tomorrow.

**Comment by dimroth** [comment]
Hi @OlliV,
Thanks for your answer. I still get the same error. If it is the case you describe, then Let's Encrypt nameservers are caching records for more than a week because `dig +short A aircampus.co` has been giving good A records since then 😢

**Comment by OlliV** [comment]
You have `DNSSEC: signedDelegation` configured for the domain. I  think this may cause the issue because zeit.world doesn't currently support DNSSEC.

**Comment by dimroth** [comment]
<img width="988" alt="dnssec can t be configured" src="https://user-images.githubusercontent.com/19348229/34478528-a38c4150-efa1-11e7-9269-9c75e5cb28b9.png">
Ok, getting closer ! Namecheap, my current registrar, doesn't allow DNSSEC to be configured for the domain. I think DNSKEY and DS records might have persisted from my previous registrar, I'll check with them.

**Comment by dimroth** [comment]
@OlliV thank you for your help ! It was indeed a DNSSEC issue !
