### ISSUE TITLE
Access deployed url

### ISSUE THREAD

**Issue by ericmasiello** [vercel/vercel#1054]
Hi, is it possible to access to the url (host and port) that’s created when deploying an app to now somehow within the app such as through `process.env`?

**Comment by timneutkens** [comment]
The url is provided as `process.env.NOW_URL`
Alternatively if you want to get the alias you can read it from the `HOST` header.
https://zeit.co/docs/features/env-and-secrets#default-variables

**Comment by cryptiklemur** [comment]
Is this in V2 at all? I can't find any reference too it, and it doesn't seem to be in the env vars

**Comment by juliangruber** [comment]
@aequasi you're right that this isn't in V2. Can you make a case for adding it?

**Comment by cryptiklemur** [comment]
One of my apps has an OAuth flow to it. The callbackUrl is hard-coded to my production alias.

Would love for this to support my staging aliases, and possibly multiple aliases per deploy. 
I'm sure I could get it set up to use the URL from the request some how, but it'd be a lot easier to just have an env var for it

**Comment by styfle** [comment]
You can use one of these to find the requested URL

- Serverless Function: `req.headers.host`
- Browser: `window.location.hostname`

In your case (OAuth), I would suggested reading the `host` header for the callbackUrl.

**Comment by JJAshcraft** [comment]
I was able to get mine by using (example)
 let URL = req.headers['x-now-deployment-url']
*note: this does not give you a full url, you still need to prepend the https://*

**Comment by juliangruber** [comment]
This is documented here: https://zeit.co/docs/v2/platform/upgrade-to-2-0#environment-variables

**Comment by borekb** [comment]
> This is documented here: https://zeit.co/docs/v2/platform/upgrade-to-2-0#environment-variables

Up-to-date URL: https://zeit.co/docs/v2/advanced/platform/changes-in-now-2-0#environment-variables

(@juliangruber Feel free to delete this comment if you want to update your link.)

**Comment by compex-africa** [comment]
> > This is documented here: https://zeit.co/docs/v2/platform/upgrade-to-2-0#environment-variables
> 
> Up-to-date URL: https://zeit.co/docs/v2/advanced/platform/changes-in-now-2-0#environment-variables
> 
> (@juliangruber Feel free to delete this comment if you want to update your link.)

Url is now out of date

**Comment by dcastil** [comment]
Is there a way to get the deploy URL during build time at the moment?

If I want to enable a [twitter card](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/summary-card-with-large-image) with an image for a website, I need to add a meta tag in the head with a full image URL.

```html
<meta name="twitter:image" content="https://mysite.com/image.jpg">
```

Not having a deploy URL at hand makes it pretty hard to test this functionality in a deploy preview. On Netlify I can access the deploy URL via `process.env.DEPLOY_PRIME_URL` and I'm searching for a way to replicate this on now.

**Comment by hacknug** [comment]
I was also looking for this. The way I had it set up in Gridsome + Netlify was: `siteUrl: process.env.BRANCH === 'master' ? process.env.URL : process.env.DEPLOY_URL,` and it was quite useful to test and debug changes on branch and PR deploys. Would love to see something similar available on Now.

**Comment by alondahari** [comment]
I'm also looking for this. We are using jenkins for our CI and deploying to now to run end to end tests against it. Would love it if the url could be accessed from stdout.

**Comment by lucleray** [comment]
You can get the URL both in Build/Runtime and in your CI/CD:
- In Build or Runtime, use the `VERCEL_URL` [System Environment Variable](https://vercel.com/docs/platform/environment-variables#system-environment-variables) in your project and it will be available in your code (for example, in Node.js, `process.env.VERCEL_URL`).
- In a CI/CD environment, when running `vercel`, stdout contains the deployment URL. For example, try `vercel --confirm > my_url.txt` and the URL will be written to a file.
- Lastly, we also add a [`host` header](https://vercel.com/docs/v2/edge-network/headers#inlinecode) to the request when it is routed to your deployment. You can read it to know what url (domain or deployment url) is accessed by the visitor of your website.

**Comment by revskill10** [comment]
@lucleray In my case, `process.env.VERCEL_URL` is `hpu-4tvpnc2z7.vercel.app` while the production domain is at `hpu.vercel.app`. Do you know how to get the production url ?

**Comment by gunar** [comment]
If you're going to use [system environment variables such as `VERCEL_URL`](https://vercel.com/docs/platform/environment-variables#system-environment-variables), you'll need to enable `Automatically expose System Environment Variables` in your Project Settings.

![image](https://user-images.githubusercontent.com/7684574/99887939-6a6d2900-2c40-11eb-9fc9-b744aa55342c.png)

**Comment by ChocolateLoverRaj** [comment]
`VERCEL_URL` is less reliable than `host` because `VERCEL_URL` is the 'inspect' url, which is wrong when you are on 'preview' url.
