### ISSUE TITLE
Error message when adding existing secret

### ISSUE THREAD

**Issue by tobybear** [vercel/vercel#1058]
Using the NOW CLI, on Windows when adding a secret with a name that already exists, it gives the message "Error! Unexpected error. Please try again later."
Removing the secret first and then adding it under the same name with a new text works however.

Example output (the "-d/--debug" flag does not seem to be working or am I doing something wrong using it?):

```
C:\nowtest>now --public
> Deploying C:\nowtest under ###
> Using Node.js 8.9.3 (default)
> Ready! https://nowtest-glwxvsetdp.now.sh [7s]
> Synced 1 file (359B) [0ms]
> Initializing.
```

```
C:\nowtest>now secrets ls
> 6 secrets found under ### [220ms]

  name            created
  consumerkey     2d ago
  consumersecret  2d ago
  accesstoken     2d ago
  accesssecret    2d ago
  querysecret     2d ago
  queryt          22h ago
```

```
C:\nowtest>now secrets add test "abc"
> Success! Secret test added (###) [400ms]
```
```
C:\nowtest>now secrets ls
> 7 secrets found under ###[260ms]

  name            created
  consumerkey     2d ago
  consumersecret  2d ago
  accesstoken     2d ago
  accesssecret    2d ago
  querysecret     2d ago
  queryt          22h ago
  test            6s ago
```
```
C:\nowtest>now secrets add test "def"
> Error! Unexpected error. Please try again later. (An unexpected internal error
 occurred)
```
```
C:\nowtest>now -d secrets add test "def"
> Error! The specified directory "secrets" doesn't exist.
```
```
C:\nowtest>now --debug secrets add test "def"
> Error! The specified directory "secrets" doesn't exist.
```
```
C:\nowtest>now secrets rm test
> The following secret will be removed permanently
  test      1m ago
> Are you sure? [y/N] y
> Success! Secret test removed [3s]
```
```
C:\nowtest>now -d secrets add test "def"
> Error! The specified directory "secrets" doesn't exist.
```
```
C:\nowtest>now secrets add test "def"
> Success! Secret test added (###) [420ms]
```

**Comment by sreeramjayan** [comment]
@tobybear 
I tried recreating this issue on a Windows machine but wasn't able to. I am using version 9.2.5 of Now. Also the debug flag works in conjunction with secrets if appended at the end of the command. For example:  `now secrets add test3 "def" --debug` has an output of:
> [debug] #1 POST /secrets: 330.008ms
> Success! Secret test3 added  [344ms]
> [debug] closing agent

**Comment by tobybear** [comment]
Strange, it is still happening here. I did in the meantime I upgraded to the latestd CLI version (9.2.6), but still the same behaviour.
Here is the debug output:
`C:\nowtest>now secrets add test "def
> [debug] #1 POST /secrets: 242.593ms
> [debug] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.Now.add.value.retry (C:\snapshot\now-cli\dist\now.js:12060:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #2 POST /secrets: 85.175ms
> [debug] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.Now.add.value.retry (C:\snapshot\now-cli\dist\now.js:12060:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #3 POST /secrets: 79.473ms
> [debug] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.Now.add.value.retry (C:\snapshot\now-cli\dist\now.js:12060:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] #4 POST /secrets: 74.327ms 
> Error! Unexpected error. Please try again later. (An unexpected internal error
 occurred)`

**Comment by TooTallNate** [comment]
Closing since this is what is shown today:

```
$ now secrets add test "abc"
> Success! Secret test added (tootallnate) [145ms]

$ now secrets add test "abc"
> Error! The secret name "test" already exists for this user
```
