### ISSUE TITLE
`--npm` should overwrite `now.json` config

### ISSUE THREAD

**Issue by littleStudent** [vercel/vercel#1064]
I would assume that using CLI options overwrite the `now.json` config. 
It looks like even though i use `--npm` it is still deploying via `docker`

now.json
```Javascript
{
    "type": "docker"
}
```

running command
```
now --npm
```

**Comment by sreeramjayan** [comment]
@leo @matheuss I submitted a PR to fix this issue https://github.com/zeit/now-cli/pull/1086 Please review it when you get time.

**Comment by littleStudent** [comment]
thx for the fix @sreeramjayan
