### ISSUE TITLE
now alias throws error when current alias has multiple instances

### ISSUE THREAD

**Issue by satyavh** [vercel/vercel#1065]
So I have a deploy that I scaled up to 3 instances.
Now I do:

`now && now alias`
Which deploys a new single instance, and then alias it and (should) scale it up to 3 instances. 
It gives this result:

```
➜ git:(master) ✗ now alias
> Assigning alias www.pstsp.kr to deployment...
> Assigning pstsp.kr to deployment...
> Alias pstsp.kr points to pstspkr-lfvajqlfba.now.sh (3 instances)
> Scaling pstspkr-nggeyzhofl.now.sh to 3 instances atomically
> Alias www.pstsp.kr points to pstspkr-lfvajqlfba.now.sh (3 instances)
> Scaling pstspkr-nggeyzhofl.now.sh to 3 instances atomically
> Error! An unexpected error occurred
```

But it actually did scale up to 3 instances (sometimes), but it didn't alias them (most of the time)
I know that because when I do `now rm pstspkr --save` it removes the latest deploy that isn't aliased.

But the strange thing is, (very!) sometimes is does work, but still throws error!
```
> Assigning alias www.pstsp.kr to deployment...
> Assigning alias pstsp.kr to deployment...
> Alias www.pstsp.kr points to pstspkr-nggeyzhofl.now.sh (3 instances)
> Scaling pstspkr-czntyeauwa.now.sh to 3 instances atomically
> Alias pstsp.kr points to pstspkr-nggeyzhofl.now.sh (3 instances)
> Scaling pstspkr-czntyeauwa.now.sh to 3 instances atomically
> Scaled to 3 instances: [5s]
- pstspkr-czntyeauwa-fa563758b3fbb5b53900c726.now.sh
- pstspkr-czntyeauwa-04ef6c2415e004e5a5130160.now.sh
> Scaled to 3 instances: [4s]
- pstspkr-czntyeauwa-fa563758b3fbb5b53900c726.now.sh
- pstspkr-czntyeauwa-04ef6c2415e004e5a5130160.now.sh
- pstspkr-czntyeauwa-8941f05db7e3dc4b0f7c4335.now.sh
> www.pstsp.kr is a custom domain.
⠋ Fetching domain info> pstsp.kr is a custom domain.
> Verifying the DNS settings for www.pstsp.kr (see https://zeit.world for help)
> Verifying the DNS settings for pstsp.kr (see https://zeit.world for help)
> Verification OK!
> Verification OK!
> Success! www.pstsp.kr now points to pstspkr-czntyeauwa.now.sh! [3s]
> Success! pstsp.kr now points to pstspkr-czntyeauwa.now.sh! [3s]
> Scaled pstspkr-nggeyzhofl.now.sh down to 1 instance [2s]
> Error! An unexpected error occurred
```

Usually I have to wait a little bit, then do `now alias` again.
Then scale my last deploy manually, and remove the previous deploy manually. Annoying.

Sometimes when doing `now alias` I get this error:
`The alias you are trying to configure is already in use by a different account.` (Uhm....)

So overall, it all feels a bit unreliable while the main USP of now is ease of deploy.

Am I doing something wrong here?

**Comment by timneutkens** [comment]
Make sure you use `--safe` instead of `--save` 👍

**Comment by satyavh** [comment]
uhm yes, that was a typo :-) I use --safe

**Comment by satyavh** [comment]
Why is this closed? The issue is still there!

**Comment by leo** [comment]
On, sorry. I thought the issue was the typo!

**Comment by bberak** [comment]
Hi there, I'm also experiencing this problem when issuing the ```now alias``` command. The alias I'm using is an external domain that is owned by my account (I can see this via my Zeit dashboard).

Any help would be greatly appreciated!

**Comment by abmirayo** [comment]
Hey team, I'm experiencing this error as well, but only if I run:
```now; now alias``` 
If I run ```now``` and then, after it's done, I manually run ```now alias``` it works correctly. Maybe a timing issue?

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
