### ISSUE TITLE
Log the user's version when using `--debug`

### ISSUE THREAD

**Issue by timneutkens** [vercel/vercel#1066]
Makes debugging with a customer easier, because you don't have to ask for the now-cli version 👍

**Comment by jamo** [comment]
+ node version

**Comment by timneutkens** [comment]
@jamo I'm not sure if that's still relevant since we always `pkg` now-cli. You always download it, even with `npm install -g now`

**Comment by leo** [comment]
exactly - the node version is always the same and you can get it from `package.json` in this repo.
