### ISSUE TITLE
docker build cache

### ISSUE THREAD

**Issue by xinshangshangxin** [vercel/vercel#1067]
docker always use newer image to build, I need cache for quickly build 
![image](https://user-images.githubusercontent.com/8779091/34811365-76a339aa-f6db-11e7-9e7a-052f7ed9575a.png)

**Comment by sreeramjayan** [comment]
@xinshangshangxin 
Doesn't docker always look for the cached image unless the --no-cache option is specified? I don't understand how now would be impacting this.

**Comment by xinshangshangxin** [comment]
@sreeramjayan I think `now` use different machine to build same project

**Comment by OlliV** [comment]
Yeah currently unfortunately we can't guarantee that you can hit a host having the same cache layers available.

**Comment by ewolfe** [comment]
AWS CodeBuild and Docker Hub face the same problem.

> The infrastructure costs of [having a cache] would be prohibitive, all of the image layers are created from scratch each time.
>
> https://github.com/nathanleclaire/tarzan

The above project tried to solve the issue but is deprecated. The hunt for a (cloud) build system with layer caching continues...
