### ISSUE TITLE
"target" in now.json does not work

### ISSUE THREAD

**Issue by ksmithut** [vercel/vercel#1075]
In the README, it talks about a "target" configuration option in the `now.json` as an option to deploy a "dist" directory. Here's my example:

`now.json`
```json
{
  "name": "target-test",
  "type": "static",
  "target": "dist"
}
```

`index.html`
```html
<!DOCTYPE html>
<html>
<head><title>Nope</title></head>
<body><h1>Nope</h1></body>
</html>
```

`dist/index.html`
```html
<!DOCTYPE html>
<html>
<head><title>Yup</title></head>
<body><h1>Yup</h1></body>
</html>
```

From the terminal, I run `now`, then go to the deployment url, and it shows "Nope", the project root level `index.html`.

```
$ now --version
9.1.0
$ node --version
v9.4.0
$ sw_vers -productVersion  # Mac Version
10.13.2
```

**Comment by eivindml** [comment]
I'm pretty shure this issue is still relevant with now 2 as well and should be opened.
