### ISSUE TITLE
Now-CLI on RPi: cannot execute binary file

### ISSUE THREAD

**Issue by tautf** [vercel/vercel#1077]
Hey guys,

im trying to run now on my rpi 3.
After installing now by 
`sudo npm i -g now --unsafe-perm`

i tried to run `now `but i am reciveing the following error:
`-bash: /usr/bin/now: cannot execute binary file: Exec format error`

When running now with sudo recieving this error:
`/usr/bin/now: 1: /usr/bin/now: Syntax error: "(" unexpected`

Somebody has an idea whats the Problem here?

**Comment by matheuss** [comment]
@tautf can you share the contents of `/usr/bin/now`? If it's a binary, just the first few characters 👍

**Comment by tautf** [comment]
@matheuss Yes its a binary, i only know the command for hexdumps.
can you tell me another command for viewing the hole file?

When running `sudo xdd -b /usr/bin/now | less` the file starts with` .ELF......`

**Comment by TooTallNate** [comment]
Please run `file <filename>`

**Comment by TooTallNate** [comment]
However, I'm pretty sure that we do not ship RPi binaries for Now at this time /cc @igorklopov @leo

**Comment by leo** [comment]
Yes, that's the reason it's failing, I'd say. What kind of binaries do we need?

**Comment by TooTallNate** [comment]
For ARM CPUs. `pkg` can output for that architecture, but last time I checked `pkg` needed to be run on that actual hardware for it to produce the correct binaries. That maybe has changed though /cc @igorklopov

**Comment by leo** [comment]
Is there a CI for that?

**Comment by tautf** [comment]
Thank you guys, i already had an older version of now running on another pi :/

**Comment by jamo** [comment]
@igorklopov could we just like check whether there is a release which actually works for the platform. And if not, fallback to a normal install.

**Comment by igorklopov** [comment]
@jamo i think fallback approach could be rather complex. I am going to finish new version of pkg soon and try compiling now-cli for RPi.

**Comment by igorklopov** [comment]
@tautf Please tell me, how did you get `now-cli` for RPi? Did you `pkg`ed it yourself? I think we never provided such binaries.

**Comment by TooTallNate** [comment]
@igorklopov Probably an older version of Now from before we served `pkg` binaries.

**Comment by jamo** [comment]
@igorklopov, can we actually support all possible platforms where one could compile nodejs to. Iff not, I'd say we should do a proper OS+platform detection and provide an alternative

**Comment by tautf** [comment]
@igorklopov i installed it with npm

**Comment by Mr-Kumar-Abhishek** [comment]
```
$ now -v
bash: /home/pi/.config/versions/node/v12.0.0/bin/now: cannot execute binary file: Exec format error
```
OS + platform detection is not implemented yet I presume ? So how to install the correct binary manually for the time being ? Or I have to compile it from source ?
```
$ npm -v
6.9.0
```
```
 $ node -v
v12.0.0
```
```
$ hostnamectl
   Static hostname: *removed*
         Icon name: computer
        Machine ID: 2c9b9d45656b45afb58b1f0a4682f91a
           Boot ID: 96cde3b4f50d4a0a96921e3d64e4a991
  Operating System: Raspbian GNU/Linux 9 (stretch)
            Kernel: Linux 4.14.98-v7+
      Architecture: arm
```

```
 $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.9 (stretch)
Release:	9.9
Codename:	stretch
```

**Comment by Kheirlb** [comment]
Trying to run now on my raspberry pi myself. Any updates on this issue?

`$ npm -v
6.4.1`

**Comment by styfle** [comment]
This still seems to be an issue with pkg, however there is a workaround.

First make sure you have Node 10+

If not, you can install Node with the following steps:

```
cd ~/Downloads
uname -a # mine is armv7l
wget https://nodejs.org/dist/v10.16.0/node-v10.16.0-linux-armv7l.tar.gz
tar -xzf node-v10.16.0-linux-armv7l.tar.gz
cd node-v19.16.1-linux-armv7l/
sudo cp -R * /usr/local/
node --version
npm --version
```

Then clone the CLI source code and build it:

```
cd ~/Downloads
git clone https://github.com/zeit/now-cli
cd now-cli
npm install
npm run build-dev
node dist --version # mine is 15.7.0-canary.9
```

If you see a version printed to stdout then the cli is working.

Finally, create a shell script called `/usr/local/bin/now` with the following contents:

```
#!/bin/bash
exec node ~/Downloads/now-cli/dist "$@"
```

Run `sudo chmod +x /usr/local/bin/now` to make it executable.

```
now --version # works
```

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!
