### ISSUE TITLE
Pass flags to yarn install

### ISSUE THREAD

**Issue by serranoarevalo** [vercel/vercel#1078]
My project has some dependencies that need me to add --ignore-engines when I install them.
`yarn --ignore-engines`. How can I accomplish this using now?

**Comment by leo** [comment]
cc @TooTallNate

**Comment by hamxabaig** [comment]
Is there a solution?

**Comment by jamo** [comment]
Please checkout this serverless docker example: https://github.com/zeit/now-examples/blob/master/node-express/Dockerfile

**Comment by hamxabaig** [comment]
Tried it but the minimum size of image for public projects is 100Mib and mine was 200Mib 😅  Though i removed the `engines` from `package.json` and it worked!

**Comment by jamo** [comment]
Maybe your image contains something it should not?

**Comment by mahmoudfelfel** [comment]
You can also add a `.yarnrc` file and add any flags to it, e.g.:
```
--install.ignore-engines true
```
https://yarnpkg.com/lang/en/docs/yarnrc/

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
