### ISSUE TITLE
(create-react-app) The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.

### ISSUE THREAD

**Issue by OmarKhattab** [vercel/vercel#1080]
Trying to deploy using now.sh and serve.
I have done npm install --save serve.

package.json

  "name": "fashionoverflow",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "axios": "^0.16.2",
    "feather-icons": "^3.3.0",
    "firebase": "^4.7.0",
    "material-ui": "^0.19.1",
    "prop-types": "^15.6.0",
    "re-base": "^3.2.0",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-feather": "^1.0.7",
    "react-router-dom": "^4.2.2",
    "react-scripts": "1.0.13",
    "react-share": "^1.16.0",
    "react-tap-event-plugin": "^2.0.1",
    "recompose": "^0.26.0",
    "serve": "^6.4.8"
  },
  "scripts": {
    "start": "react-scripts start",
    "now-start": "serve --single ./build",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

``` 
FashionOverflow git:(master) ✗ now
> Deploying ~/Desktop/FashionOverflow under ******@gmail.com
> Using Node.js 8.9.4 (default)
> Ready! https://fashionoverflow-sifbkotzzx.now.sh (copied to clipboard) [8s]
> You (*******@gmail.com) are on the OSS plan. Your code and logs will be made public.
> NOTE: You can use `now --public` to skip this prompt
> Synced 1 file (747B) [2s] 
> Initializing…

> Building
> ▲ npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 15 main dependencies…
> ✓ Installed 1476 modules [26s]
> ▲ npm run build
> > fashionoverflow@0.1.0 build /home/nowuser/src
> > react-scripts build
> Creating an optimized production build...
> The build failed because the process exited too early. This probably means the system ran out of memory or someone called `kill -9` on the process.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! fashionoverflow@0.1.0 build: `react-scripts build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the fashionoverflow@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2018-01-18T01_08_03_844Z-debug.log
> Error! The build step of your project failed. To retry, run `now --force`. ```

**Comment by sergiodxa** [comment]
You are on the OSS plan which only give you up to 512MB of RAM and it looks your app have big dependencies like material-ui and recompose, your build step must be requiring too much RAM to build the app.

You can either upgrade to Premium (to have up to 1GB of RAM) or build in your local machine (or CI) and deploy the built files + serve, that way you will not run out of memory.

**Comment by garkuwa** [comment]
What worked for me is memory swapping. I know it's not the best approach since it uses 'emergency' memory but it does the job.

In gitlab, you simply add a setting to `config.toml`:
`memory_swap = "2000m"` (or any other value)
