### ISSUE TITLE
What are HW limits of instance?

### ISSUE THREAD

**Issue by homoky** [vercel/vercel#1081]
Hi guys, 

what are limits for each instance?

**Comment by OlliV** [comment]
Does the plan limits answer to your question or do you have something more specific in your mind?

https://zeit.co/account/plan

**Comment by homoky** [comment]
No it does not. Where is mentioned HW that it runs on???

On #1080 I found this from @sergiodxa:

```
You are on the OSS plan which only give you up to 512MB of RAM and it looks your app have big dependencies like material-ui and recompose, your build step must be requiring too much RAM to build the app.

You can either upgrade to Premium (to have up to 1GB of RAM) or build in your local machine (or CI) and deploy the built files + serve, that way you will not run out of memory.
```

**Comment by OlliV** [comment]
The HW is "modern" x86 but can't promise much more than that and the above memory constraints ^
