### ISSUE TITLE
name in now.json ignored if you deploy sub directory

### ISSUE THREAD

**Issue by JuanCaicedo** [vercel/vercel#1092]
Hi there! I ran into a problem when trying to deploy a sub directory

I put together [this repo](https://github.com/JuanCaicedo/now-dir-deploy-test) to recreate it, but I can put a summary here.

- In `now.json`, I list a `"name": "foo"` for my deployment.
- I deploy `dist/` using `now dist`
- I would expect a url like `https://foo-{id}.now.sh`
- I get a url like `https://{id}.now.sh`
- I think other keys in `now.json` are likewise ignored, but I need to verify

Let me know if I can provide any more info!

**Comment by JuanCaicedo** [comment]
I think this problem comes from the fact that at [src/providers/sh/commands/deploy.js#L436](https://github.com/zeit/now-cli/blob/canary/src/providers/sh/commands/deploy.js#L436), `deploymentName` will already be defined in the case of `$ now dist`. I think perhaps the name from `now.json` should be given precedence

**Comment by JuanCaicedo** [comment]
Got it! I guess my expectation was that it would be read from the directory where the cli was called from, but I guess from the deployed directory makes sense in case you want to deploy multiple projects, or if you're deploying projects in other locations.

This was a confusing behavior, though I can see why it exists and shouldn't change. Should there be a note someplace so that when a user learns about deploying `$ now <dir>`, they're aware of where they should put `now.json`? Not sure where that documentation would be, though I'm willing to type it up. 

I'll close this issue after your thoughts on ^, or you can feel free to 😀

**Comment by leo** [comment]
If you'd like, you can document it [here](https://github.com/zeit/docs/blob/master/pages/docs/features/now-cli.js). Thank you! 😊
