### ISSUE TITLE
Alias to remote server

### ISSUE THREAD

**Issue by ccutch** [vercel/vercel#1093]
Hi I am currently hosting a domain with now and would like to use an external server for a subdomain. Is there a way to update the dns records

**Comment by leo** [comment]
Sure! Just set the `CNAME` or `ALIAS` record appropiately, like [this](https://zeit.co/world#get-started). 😊

**Comment by timneutkens** [comment]
`now dns add <your domain> <subdomain> <type> <value>`

For example if you want to add a record for abc.example.com you'd do it like this:

```
now dns add example.com abc A 127.0.0.1
```

Or a `CNAME`

```
now dns add example.com abc CNAME <value>
```

More examples can be found under `now dns --help`
