### ISSUE TITLE
now alias swallowing errors

### ISSUE THREAD

**Issue by goldensunliu** [vercel/vercel#1094]
Pretty sure free plans are not allowed to set up alias with custom domains, however, when I try to do so the cli just hangs on
```
Verifying the DNS settings for $MY_CUSTOM_DOMAIN (see https://zeit.world for help)
```
tried with version 8.4.0 and 9.2.7

Steps to reproduce:

1. deploy a simple app with the free plan
2. follow https://zeit.co/world#get-started set up your domain name servers
3. run `now alias $TheDeployedUrl $CustomDomain`

**Comment by goldensunliu** [comment]
related discussion https://github.com/zeit/now-cli/issues/989#issuecomment-359684599

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
