### ISSUE TITLE
Support HTTP2 servers

### ISSUE THREAD

**Issue by sholladay** [vercel/vercel#1095]
For a streaming service, I need to be able to send [HTTP trailers](http://engineering.pivotal.io/post/http-trailers/) to the client, but apparently browsers don't really [support them on HTTP 1.1](https://stackoverflow.com/questions/13371367/do-any-browsers-support-trailers-sent-in-chunked-encoding-responses), despite the spec. With HTTP/2, proper support for trailers exists.

During the process of experimenting, I discovered that Now doesn't seem to support running an HTTP/2 server. I believe this will make it impossible for me to send trailers, even though Now fronts my server with an HTTP2-compliant proxy.

**Comment by sholtomaud** [comment]
Any updates on http/2 for Zeit servers?

**Comment by leo** [comment]
We already support HTTP/2 out of the box!

**Comment by sholladay** [comment]
Now itself adds an HTTP/2 layer on top. But I was unable to make my origin server be HTTP/2. This is pretty problematic, because it means I can't use some HTTP/2 features.
