### ISSUE TITLE
"TypeError: stdin.setRawMode" when domain is available.

### ISSUE THREAD

**Issue by karl-run** [vercel/vercel#1097]
Version: `10.0.0-canary.15`
OS: Windows 10

```
$ now domain buy example.games
> The domain "example.games" is available to buy under <my user>! [1s]
> Error! Unknown error: TypeError: stdin.setRawMode is not a function
TypeError: stdin.setRawMode is not a function
    at module.exports.resolve (C:\snapshot\now-cli\dist\now.js:1386:11)
    at new Promise (<anonymous>)
    at module.exports (C:\snapshot\now-cli\dist\now.js:1383:10)
    at module.exports (C:\snapshot\now-cli\dist\now.js:2756:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by karl-run** [comment]
Still getting this on version `10.2.2`. But now I'm also getting it on `now domain add example.com`.

**Comment by karl-run** [comment]
Using git bash (mintty 2.8.3) on Windows 10 still.

**Comment by ahsath** [comment]
same here =/

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
