### ISSUE TITLE
Unable to deploy app (interal error)

### ISSUE THREAD

**Issue by KammererTob** [vercel/vercel#1099]
I am trying to deploy hazel on now (with `now zeit/hazel`) but it always throws me these errors:

> [debug] Retrying: Error: An unexpected internal error occurred
> Error: An unexpected internal error occurred
> at module.exports.EventEmitter.create.deployment.retry (C:\snapshot\now-cli\dist\now.js:437:15)
> at 
> at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] get files ready for deployment: 0.298ms
> [debug] v2/now/deployments: 1266.614ms
> [debug] Retrying: Error: An unexpected internal error occurred
> Error: An unexpected internal error occurred
> at module.exports.EventEmitter.create.deployment.retry (C:\snapshot\now-cli\dist\now.js:437:15)
> at 
> at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] get files ready for deployment: 0.349ms
> [debug] v2/now/deployments: 1211.761ms
> [debug] Retrying: Error: An unexpected internal error occurred
> Error: An unexpected internal error occurred
> at module.exports.EventEmitter.create.deployment.retry (C:\snapshot\now-cli\dist\now.js:437:15)
> at 
> at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] get files ready for deployment: 0.383ms
> [debug] v2/now/deployments: 1143.849ms
> [debug] error: Error: An unexpected internal error occurred
> Error: An unexpected internal error occurred
> at module.exports.EventEmitter.create.deployment.retry (C:\snapshot\now-cli\dist\now.js:437:15)
> at 
> at process._tickCallback (internal/process/next_tick.js:188:7)
> Error! Unexpected error. Please try again later. (An unexpected internal error occurred)

I tried to reinstall/reauth `now` and also disabled my firewall. I initially opened a ticket in the zeit/hazel repository, because i thought that the errors were caused by it - but it seems that the problem is with `now` (https://github.com/zeit/hazel/issues/39)

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
