### ISSUE TITLE
Corrupt data stream due to HTTP/2 (suspected)

### ISSUE THREAD

**Issue by pqvst** [vercel/vercel#110]
After quite a few hours of investigation I suspect that multipart/form-data data streams become corrupt (garbled) due to HTTP/2. If I try to a upload a file when using HTTP/2 the first couple of bytes become garbled. If I disable HTTP/2 (chrome --disable-http2) then I am unable to reproduce the issue. I have only been able to reproduce the issue with one specific file on some computers. Not reproducable on all computers that I've tested with.

See linked GitHub project for a minimal test project with detailed investigation observations.
https://github.com/pqvst/form-test

If the culprit is indeed the HTTP/2 stack in _now_ then I would say that this is a pretty critical issue since it means that file uploads aren't guaranteed to work. Perhaps there are other scenarios as well?

**Comment by jamo** [comment]
Closing this now.
The issue was fixed and confirmed fixed in early december. (and I just forgot to update the issue)
