### ISSUE TITLE
Email autocompletion is broken/autocompletes way incorrectly

### ISSUE THREAD

**Issue by jamo** [vercel/vercel#1104]
Here I'm typing in my email and after .fi I hit enter. Which one would expect to complete the prompt and let me proceed to the email validation.
Instead, however, it autocompletes w/o suggesting it `inbox.com` to the fully typed in domain.

See gif below:
![login2](https://user-images.githubusercontent.com/1354151/35774946-f28e904c-0986-11e8-8c7a-7ce76c2a5095.gif)

Edit, just updated now so using the latest version.

**Comment by sreeramjayan** [comment]
@jamo It seems to be an issue with the email-prompt module. 
https://github.com/zeit/email-prompt/pull/20 should fix this issue once it has been merged.

**Comment by rauchg** [comment]
@sreeramjayan thanks for diagnosing this. I just released `email-prompt` `0.3.2` 🕵️‍♂️

**Comment by leo** [comment]
@rauchg 👌 Can you upgrade it here, please?
