### ISSUE TITLE
Deploy LDAP Docker image

### ISSUE THREAD

**Issue by RemyLespagnol** [vercel/vercel#1107]
Hi Zeit team :)

I have a problem, maybe it's easy... but I can't achive that.

I want to deploy a LDAP on the cloud to access it by other application.
So I want to use [this docker image](https://github.com/osixia/docker-openldap). For that I push this image to now with the Dockerfile :
```
FROM osixia/openldap:1.1.11
EXPOSE 389
``` 

When I go to the now url I have nothing (maybe it's the good behavior).

When I run the [phpldapadmin docker image](https://github.com/osixia/docker-phpLDAPadmin) : `docker run -p 6443:443  --env PHPLDAPADMIN_LDAP_HOSTS=ldap-sbfenjuqmu.now.sh --detach osixia/phpldapadmin:0.7.1`

I can't login... I use the `admin` password.
![image](https://user-images.githubusercontent.com/2819925/35769317-7c0ddfea-0909-11e8-9049-e2a15a4fc4c6.png)

I don't know if the docker is succesfully deploy to now... and I don't know how to call the LDAP from the now url..

Have you got an idea to have an OpenLDAP instance on the cloud to access by other apps?

Thanks
Rémy.

**Comment by OlliV** [comment]
Currently we only support exposing http as a protocol so you'd need a some kind of proxy there. The more serious problem for your use case is that we do not offer persistent storage. So in case your deployment restarts you would lose all your data.

**Comment by RemyLespagnol** [comment]
Yeah I see know why it's not working...

For the persistent storage, it's not a problem, because it's just for a fake LDAP solution :)

So I see that the proxy solution is the best one.
Thank you @OlliV :)
