### ISSUE TITLE
Add option to now scale to not error if there are no matching deployments

### ISSUE THREAD

**Issue by SteveALee** [vercel/vercel#1108]
Could the now `scale` have an option not to error when there are no matching deployments? 

The scenario is my npm script to roll back to 0 live instances before I deploy given there are only 3 on the OSS Plan and the now cli errors if we hit the deployment limit. 

For now during intially dev `now rm` is in actually the correct option as I do not want any old deployments around to roll back to

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), there are no instance limits to the Free plan anymore.

In turn, I'm closing this.
