### ISSUE TITLE
File size limit exceeded (1 MB) on premium account

### ISSUE THREAD

**Issue by tolu** [vercel/vercel#1111]
In the spirit of *a picture says more than a thousand words*...

![image](https://user-images.githubusercontent.com/658586/35986262-ddf3f706-0cf8-11e8-968f-23b634c85246.png)

Running
* `now-cli` v9.2.8
* `npm` v5.5.1
* `node` v8.9.1
* Windows 10

Also tested updating node and npm to v9.5.0 / v5.6.0 without any luck.

**Comment by gle6as** [comment]
Same thing, also with now app for OS X. My current plan is on demand

**Comment by SHabdelrahman** [comment]
You can write "now -d" in order to know which file is causing the error.

**Comment by OlliV** [comment]
Is this still happening?

**Comment by vzaidman** [comment]
yes

**Comment by OlliV** [comment]
We have a plan caching of 30 minutes that is probably affecting uploads. Let me know if you experience the same error after that. We are fixing the caching so that changing the plan is in effect immediately.

**Comment by tolu** [comment]
@OlliV just giving it time worked for me, good to know about the `-d` option and how the cache works.

Thanks!

**Comment by TurtleWolfe** [comment]
maybe a warning text.. go get coffee.. and wait a bit

**Comment by TurtleWolfe** [comment]
I mis understood..  I'm trying to track down a different error.. I'm sure I'm doing something wrong

**Comment by Qix-** [comment]
@TurtleWolf feel free to open a new issue and we can look into it!
