### ISSUE TITLE
Named pipe prevents deployment

### ISSUE THREAD

**Issue by tomberek** [vercel/vercel#112]
A fifo file in the root prevents deployment, likely waiting for fifo output. Suggest checking for filetype before reading contents.

**Comment by OlliV** [comment]
Hi,
What's your use case? Do you want to use the pipe for transferring data to `now`, ignore the file, or do you need the pipe file in your deployment?

**Comment by tomberek** [comment]
I was testing something else and happened to have the fifo in the folder. Then deployment just would get stuck (presumably waiting on a fifo read). I'd suggest ignoring it.

**Comment by OlliV** [comment]
https://github.com/zeit/now/pull/128
