### ISSUE TITLE
Include a list of files over 1Mb in Error: File size limit exceeded (1 MB) message

### ISSUE THREAD

**Issue by BurkovBA** [vercel/vercel#1128]
This error message is just very non-descriptive. Please, include a list of files over 1MB into output. It's very  inconvenient to trace a big folder manually.

Thank you.

**Comment by OlliV** [comment]
Great improvement idea, thanks 😅

**Comment by sreeramjayan** [comment]
@OlliV 
Was curios to know if file size checks would be handled on the client side or the api?

**Comment by putuyoga** [comment]
would be great!
