### ISSUE TITLE
 Unexpected character '@'

### ISSUE THREAD

**Issue by jisaac89** [vercel/vercel#1129]
> Failed to build
> { Error: (client) ./pages/index.tsx
> Module parse failed: Unexpected character '@' (8:0)
> You may need an appropriate loader to handle this file type.
> | import { Emerge, Toolbar, Button } from '../utils/recoilClient';
> |
> | @inject('appStore')

Using next-typescript as a plugin - thinking it has something to do with that, as running "next build"  locally works perfectly. I also have the "experimentalDecorators" flagged true on my tsconfig.json.

Or there is an issue with the .next "pages" folder handling .tsx files and using decorators when deploying to .now

**Comment by pranaygp** [comment]
this might not fix it, but sometimes deps can be mismatched between server and client. It's a long shot but try to drlete your node_modules folder completely and `yarn` or `npm install` to simulate a fresh build like on now servers. If it fails building locally after, then it means youre missing some dep from your package.json, or inconsistency with `yarn.lock` and deps

**Comment by jisaac89** [comment]
Thank you for the input! I cleaned the "node modules" folder, did a fresh npm install and checked to see if my local build worked and it did. Sadly deploying with "now" still returns the following errors:

`> Initializing…
> Building
> ▲ npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 25 main dependencies…
> ✓ Installed 1102 modules [8s]
> > react-recipe@1.0.0 preinstall /home/nowuser/src
> > git clone https://www.github.com/jisaac89/recoil.git
> warning: redirecting to https://github.com/jisaac89/recoil.git/
> > react-recipe@1.0.0 build /home/nowuser/src
> > rimraf ./.next && next build
> > Failed to build
> { Error: (client) ./pages/about.tsx
> Module parse failed: Unexpected character '@' (8:0)
> You may need an appropriate loader to handle this file type.
> | import { Emerge, Toolbar, Button } from '../utils/recoilClient';
> |
> | @inject('appStore')
> | @observer
> | class Index extends React.Component {
>  @ multi ./pages/about.tsx
>     at /home/nowuser/src/node_modules/next/dist/server/build/index.js:207:31
>     at runWithDependencies (/home/nowuser/src/node_modules/webpack/lib/MultiCompiler.js:154:4)`

I had another typescript project with react that successfully deployed with now. The only difference between the two is that the one that fails uses next js with next-typescript instead of webpack and ts-loader.

https://github.com/jisaac89/react-recipe is the repo Im having a issue in if your interested =)

**Comment by jisaac89** [comment]
Fixed**, pulled a rookie move - don't put tsconfig.json on the .gitignore =)
