### ISSUE TITLE
`now secret add` fails (unexpected error)

### ISSUE THREAD

**Issue by maeligg** [vercel/vercel#1133]
I ran the command : 

`now secret add consumer_key xxx`

I got the following output : 

`Error! Unexpected error. Please try again later. (An unexpected internal error occurred)`

I'm using now version 9.3.3.

Could be related to https://github.com/zeit/now-cli/issues/915 ?

**Comment by maeligg** [comment]
Answering my own question as it might be useful to someone else : 
Turns out I had already set a secret with the same name a while ago. The error message didn't really point me that way...

**Comment by timneutkens** [comment]
Sorry for the inconvenience! We're tracking this issue here: https://github.com/zeit/now-cli/issues/1058
