### ISSUE TITLE
Travis with now

### ISSUE THREAD

**Issue by James-E-Adams** [vercel/vercel#1141]
Hi!

I tried following https://zeit.co/docs/examples/travis.

It didn't cover how travis 'gets' now, so I've tried both adding `now` as a dev dep as well as installing it globally before deploying using `npm i -g now`. 

But when it tries to deploy, I get the error listed here:

```bash
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
> Error! An unexpected error occurred!
  ReferenceError: story is not defined
    at Promise (/snapshot/now-cli/dist/now.js:5982:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) ReferenceError: story is not defined
    at Promise (/snapshot/now-cli/dist/now.js:5982:34)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Travis: https://travis-ci.org/James-E-Adams/github-metrics
Source repo: https://github.com/James-E-Adams/github-metrics

Am I missing something? I followed the rest of the guide without a problem.

**Comment by siddharthkp** [comment]
You might have to pass a token with `-t secret_token` that you can set as an environment variable in travis. Or if you are using a team account, them also mention the team with `--team`.

I'm working on something that might be useful: https://github.com/siddharthkp/now-cd
