### ISSUE TITLE
Can't deploy anymore: Chalk template literal is missing 1 closing bracket 

### ISSUE THREAD

**Issue by satyavh** [vercel/vercel#1158]
Suddenly can't deploy anymore, I'm on version 3.8.20, get error:

`> Error! Unexpected error. Please try again later. (Chalk template literal is missing 1 closing bracket (`}`))`

I noticed there's already an issue for this with a merge in canary?

**Comment by leo** [comment]
@satyavh This was fixed earlier in https://github.com/zeit/now-cli/pull/1151 - please upgrade your Now CLI version to be at least `10.1.0` (or `11.0.0-canary.20` on the canary channel). 😊

**Comment by satyavh** [comment]
Ok clear. So it seems the auto update mechanism (via desktop app) doesn't work properly. I'm on now cli 10.0.1, many versions behind.
