### ISSUE TITLE
Error sh: 1 xvfb-run: not found while deploying Node Js app

### ISSUE THREAD

**Issue by exsanik** [vercel/vercel#1159]
My app uses nightmare.js  this plugin doesn't work on server because of electron so people install xvfb to ran app under it. 
To use it i needed to set such commands:
```
apt-get -y update

apt-get -y upgrade

apt-get -y --force-yes install make unzip g++ libssl-dev git xvfb x11-xkb-utils 
xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps clang 
libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev libgconf2-dev 
libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-
multilib g++-multilib
```
I made Dockerfile:
```
FROM ubuntu:14.04
LABEL name "docker"
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y --force-yes install make unzip g++ libssl-dev git xvfb x11-xkb-
utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps clang 
libdbus-1-dev libgtk2.0-dev libnotify-dev libgnome-keyring-dev libgconf2-dev 
libasound2-dev libcap-dev libcups2-dev libxtst-dev libxss1 libnss3-dev gcc-
multilib g++-multilib
FROM node:6-onbuild
RUN npm install
RUN npm run start
EXPOSE 80
```
And this is my package.json start script and dependecies
`"start": "xvfb-run node --harmony index.js"`
```
"dependencies": {
    "mongoose": "^5.0.3",
    "nightmare": "^2.10.0",
    "node-cron": "^1.2.1",
    "node-telegram-bot-api": "^0.30.0"
  }
```
Actually everything goes allright until this line `RUN npm run start`
Then I got `sh: 1 xvfb-run: not found` and in the end `BUILD ERROR`

I don't understand what I am doing wrong? Please, help me

**Comment by ricardocasares** [comment]
Having the same issue with `npm-run-all`, in my scripts:

```json
"scripts": {
   "build": "run-s do some stuff"
}
```

Gettin'

```sh
> sh: run-s: not found
# Also tried to do $(npm bin)/run-s but:
> sh: /home/nowuser/src/node_modules/.bin/run-s: not found
```

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
