### ISSUE TITLE
Feature request: environment variables via package.json

### ISSUE THREAD

**Issue by jimpick** [vercel/vercel#116]
From Slack:

jimpick [12:10 PM]  
Trying out now secrets. Very nice!

[12:11]  
I've got a { ..., now: { alias: 'myalias.now.sh' } } in package.json...

[12:11]  
(but more JSONy :-)

[12:12]  
And { ... "scripts": { "deploy": "now -e CONSUMER_KEY=@consumer_key -e CONSUMER_SECRET=@consumer_secret && now alias" } } (edited)

[12:12]  
It would be nice if the now cli could deduce those -e arguments from the "now" section in package.json. That would really clean that line up.

easyrider [12:13 PM]  
joined #now

jimpick [12:14 PM]  
maybe { ... "now": { "alias": "myalias.now.sh", "environment": { "CONSUMER_KEY": "@consumer_key", "CONSUMER_SECRET": "@consumer_secret" } } }  ? (edited)

[12:14]  
just a thought...

[12:15]  
then I could just do { ... "scripts": { "deploy": "now && now alias" } } (edited)

jamo [12:17 PM]  
:+1:

jimpick [12:17 PM]  
sorry, i suck at typing JSON

jamo [12:17 PM]  
at least I got the idea :slightly_smiling_face:

[12:17]  
that soulds something we definitely should have

jimpick [12:18 PM]  
cool

jamo [12:18 PM]  
so that it won't get lost to slack logs before someone finds time to implement it, would you mind adding the feature request here: https://github.com/zeit/now/issues/new

**Comment by ericf** [comment]
@jimpick here's a PR to implement this feature, it's been something I've wanted as well! https://github.com/zeit/now/pull/119
