### ISSUE TITLE
Debounce `wait` utility to 300ms

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#1166]
If 300ms elapse, we actually render the [ora](https://github.com/sindresorhus/ora). This will make it not render unnecessarily for fast commands.

### Example

```
▲ now ls 
⠏ Fetching deployments
```

The "⠏  Fetching deployments" line would only be rendered if `now ls` is taking longer than 300ms.

**Comment by riddla** [comment]
@leo, can we close this bug now?

**Comment by leo** [comment]
Indeed!
