### ISSUE TITLE
now alias tries to create an existing domain twice on every alias operation

### ISSUE THREAD

**Issue by OlliV** [vercel/vercel#1170]
Every time I run

```
now alias sse-test-eaxbahyvso.now.sh  mynowdomain.xyz
```

for a domain that is already verified, the command makes a `POST` request to `api.zeit.co/domains` twice which returns 409 `not modified` both times.

**Comment by leo** [comment]
This should not be happening, I believe!

**Comment by Ethan-Arrowood** [comment]
Fixed! 🎊
