### ISSUE TITLE
How to pass Docker build-time variables?

### ISSUE THREAD

**Issue by Siilwyn** [vercel/vercel#1177]
Trying to use a private npm registry like described in [npm's Docker and private packages](https://docs.npmjs.com/private-modules/docker-and-private-modules) where the npm token is passed in as a build argument. Can't find any way to do this with `now` though.

**Comment by rauchg** [comment]
We're working on this. Most likely it will happen in `now.json` via a `dockerBuild` parameter.

**Comment by Siilwyn** [comment]
Okay, thanks for the quick & clear reply! Another way to achieve this is with pre-build private Docker images which if I'm not mistaken are not supported either.
