### ISSUE TITLE
now static site deployments require node version 6.x.x

### ISSUE THREAD

**Issue by jefflam** [vercel/vercel#118]
Running 'now' for a static deployment such as a index.html + scripts folder compiled app or even just a single index.html document on node v4.2.6 throws:

```
> Deploying ~/Sites/app/app-fe/dist
> Error! Unexpected error. Please try later. (this is not a typed array.)
```

Running the same commands on node v6.9.1 resolves it.

Would be good to throw a more useful error; such as asking the user to utilize a newer node version.

**Comment by leo** [comment]
https://github.com/zeit/now/commit/1ee41f3c2a1448d6b3a9b237e35c844ca6aa385b
