### ISSUE TITLE
login doesn't work in emacs shell

### ISSUE THREAD

**Issue by glasser** [vercel/vercel#1190]
If you try to run `now` within an Emacs shell, it fails to properly read your email address.

To reproduce:

- Run `emacs -q` (for example, GNU Emacs 25.3.1). The -q turns off all local customization
- M-x shell
- In the shell:
```
$ now login
> Enter your email: glasser@apollographql.com
```

After entering your email, `now` just hangs.  This is presumably an issue in the email-prompt npm module.

**Comment by rauchg** [comment]
@glasser 

Thanks for the great reproduction instructions 👍 If we can't figure out a way of fixing it, we might want to sniff the `TERM` env var in `email-prompt` perhaps.

**Comment by glasser** [comment]
Sure, or `$INSIDE_EMACS`.

**Comment by leo** [comment]
Agreed. We should definitely fix this!
