### ISSUE TITLE
Use `ajv` for validating `now.json`

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#1193]
Right now, we're validating the types and constraints manually, which is error prone and hard to maintain.

**Comment by markozxuu** [comment]
@rauchg Any way which can help solve this error?

**Comment by rubenmoya** [comment]
This issue can be closed since it was fixed in #1239

**Comment by markozxuu** [comment]
@timothyis It's time to close 😄

**Comment by markozxuu** [comment]
@pranaygp close :)

**Comment by timothyis** [comment]
Thank you for the ping
