### ISSUE TITLE
Instead of using `await exit()` or invoking `process.exit()` directly, use return values

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#1194]
In many parts of the codebase we use:

```js
if (error) {
  // something
  process.exit(1)
}
```

However, the current design of the CLI is that each sub-command has a C-style `main` function, configured to be `async`, whose *return value* is used as the exit code.

This makes writing tests and writing cleaner code a lot easier. Instead, we should be using:

```js
if (error) {
  // something
  return 1
}
```

**Comment by riddla** [comment]
@rauchg, I also found the pattern `return process.exit(1)` in the `scale` command – as the process will be terminated directly that also makes no sense, or am I mistaken? These should be replaced also in my opinion. What do you think?

**Comment by Qix-** [comment]
@riddla I'm not 100% on those but it might be for static analysis reasons. Unless the analyzer knows that `process.exit()` is a no-return function, then it might mistakenly evaluate the rest of the call graph and report false-positive errors.

Again, I'm just speculating. If that's not the case, then you're right and they should be corrected.

**Comment by satyarohith** [comment]
I'm working on this issue.

**Comment by leo** [comment]
Implemented!
