### ISSUE TITLE
Deploy command does not exit when it shows an error

### ISSUE THREAD

**Issue by riddla** [vercel/vercel#1196]
While working on a solution for #1010 I discovered that the current Canary release (`11.0.0-canary.30`) does not exit after showing a deploy error.
I just set up a directory with a single file that exceeds my current plan (> 1 MB) and tried to deploy it. The (to be improved) "File size limit exceeded" error occurs, but the process is still alive. I had to break out of i manually.

This behaviour does not appear on the stable version (`10.1.6`).

**Comment by rauchg** [comment]
We are investigating. Giving this priority even though it's in canary

**Comment by riddla** [comment]
@rauchg, I tried to debug the issue myself with the help of https://www.npmjs.com/package/why-is-node-running, but I only found out that the ,responseError‘ promise still seems to be around even after the error messages have appeared. 

But as this is my first time debugging the node async loop, even that might not be a correct finding ;)

**Comment by riddla** [comment]
@rauchg, maybe you can point me to some node debugging resources (articles/tools?) that could help me helping you? :)

**Comment by riddla** [comment]
@rauchg, meanwhile: whatever you did (or are doing) within https://github.com/zeit/now-cli/tree/better-list, it fixes this bug :)
