### ISSUE TITLE
"now aws" crashes

### ISSUE THREAD

**Issue by schrockn** [vercel/vercel#1198]
I'm experimenting with the platform and trying to run `now aws login`.

However  I the following error:

```
[schrockn@mbp ~]$ now aws
> Error! An unexpected error occurred in deploy: TypeError: Cannot read property 'useVendorConfig' of undefined
    at getAWS (/snapshot/repo/dist/now.js:13112:22)
    at Object.deploy (/snapshot/repo/dist/now.js:12528:17)
    at <anonymous>
```

The version is 10.1.6

```
[schrockn@mbp ~]$ now -v
10.1.6
```

**Comment by schrockn** [comment]
Also this is node v8.10

```
[schrockn@mbp ~]$ node -v
v8.10.0```

**Comment by rauchg** [comment]
@schrockn multiple provider support is still under heavy development. I just updated the README to reflect that, since the `canary` branch is rendered by default. 

For the stable API, please [refer to our docs](https://zeit.co/docs).
