### ISSUE TITLE
Support easier aliasing of latest deployment

### ISSUE THREAD

**Issue by slorber** [vercel/vercel#120]
Hi,

I've seen there's a `now alias` shortcut recently added, but as far as I understand it does not satisfy me, because I don't want to have a single default target in my config.

I want to be able to run something like:

```
now
now alias latest dev.domain.com
```

But I don't want to hardcode a single domain in my package.json as I can also do:

```
now
now alias latest prod.domain.com
```

I understand it may be dangerous to alias automatically without prior verifications of the deployment, but in my case for dev envs we don't care that much, and we run 2 frontend deployments in production, one being first deployed immediately to a small subset of users for real testing, and one being aliased manually after testing is done.

(as a sidenote for my own deployment usecase, it would be nice to be able to alias one target to another, like CodePush does: `now alias prod-beta.domain.com prod.domain.com` would make the deployment behind "prod-beta" being aliased to "prod", so at the end both domains will point to the same deployment)

**Comment by albinekb** [comment]
`now --automatic-alias` - or something similar would be cool too!

**Comment by TehShrike** [comment]
In the short term, I published a really simple CLI app last night that allows you to pass in all the details: [now-alias](https://github.com/TehShrike/now-alias) and here's another one that detects all the details automatically: [now-realias](https://github.com/remy/now-realias).

**Comment by arunoda** [comment]
Or a command like this:

``` sh
now --alias=abc.mydomain.com
```

I think this is pretty common thing to do when we are doing continuous deployments.

**Comment by electerious** [comment]
The following might make sense as every (existing) alias has its own id:

```
now --alias=tqpTVSLz5jBbevVrMc1a7EvE
```

**Comment by slorber** [comment]
Thanks @TehShrike will look at that

@electerious what's the point of using that id? it looks to me more confusing than using domain from an user perspective

**Comment by electerious** [comment]
@slorber It would be equal to the rest of the CLI.

**Comment by leo** [comment]
I'm going to work on this today!

**Comment by slorber** [comment]
awesome :)

**Comment by leo** [comment]
[Done!](https://github.com/zeit/now-cli/releases/tag/0.37.0) 🚀

**Comment by slorber** [comment]
thanks @leo I'm going to test (but currently have troubles don't know why I can't upgrade now locally :s)

Is there a way to link multiple aliases to the deployment at once? using multiple times the --alias option or providing a list of aliases?

**Comment by leo** [comment]
@slorber Not yet. But that should be a separate issue! Not sure if it's currently possible to assign multiple aliases to a single deployment.

If you're using Now Desktop, you shouldn't upgrade the CLI but rather wait a few minutes until it automatically updates. If you got it from npm, you need to upgrade manually!

**Comment by slorber** [comment]
Ok I'll open a separate issue

I'm not using Now Desktop but CLI, andI think it's a problem on my computer maybe related to NVM or something.

```
$ npm install -g now@0.37.0
/Users/sebastienlorber/.nvm/versions/node/v6.9.0/bin/now -> /Users/sebastienlorber/.nvm/versions/node/v6.9.0/lib/node_modules/now/build/bin/now
/Users/sebastienlorber/.nvm/versions/node/v6.9.0/lib
└── now@0.37.0

$ now -v
𝚫 now 0.28.0
> UPDATE NEEDED Current: 0.28.0 – Latest 0.37.0 (released 10m ago)
> Run `npm install -g now` to update

$ which now
/Users/sebastienlorber/.nvm/versions/node/v6.9.0/bin/now

$ /Users/sebastienlorber/.nvm/versions/node/v6.9.0/bin/now -v
𝚫 now 0.37.0
```

**Comment by leo** [comment]
@slorber I recommend removing the npm version completely and letting Now Desktop handle it (you can install the node-enclosed binary from within the app).

You won't have to update the CLI in the future!

**Comment by slorber** [comment]
Yes will give it a try thanks but it's only for mac and I'm fine with the CLI anyway :)

Was able to update finally, it was just that NVM didn't configure my path correctly and the now used was from /usr/local/bin/now

**Comment by leo** [comment]
@slorber Win and Linux support coming this week!

**Comment by den1k** [comment]
Looks like this is not supported anymore?
I want to setup different aliases for different deployments, always wanting to alias the latest deployment, like:


`now && now --alias dev.my-domain.com`
OR
`now && now --alias snapshot.my-domain.com`

**Comment by ghost** [comment]
Hi! Is it still possible to do this with the Vercel CLI, or is there any alternative way?

**Comment by sam-at-work** [comment]
I installed an npm package called `cli-clipboard` which lets you do the following:
`now && now alias set $(npx clipboard) dev.my-domain.com`

If you are on a Mac, you could just do:
`now && now alias set $(pbpaste) dev.my-domain.com`

**Comment by ScreamZ** [comment]
Hidden commands are best, this is cool to still be allowed to alias something on our own

**Comment by sam-at-work** [comment]
Update to above comment:
I have found a better way to do it:
`now | xargs -I{} now alias {} dev.my-domain.com`

if you want to alias to multiple domains:
`now | xargs -I{} sh -c '{ now alias {} dev1.my-domain.com; now alias {} dev2.my-domain.com; }'`
