### ISSUE TITLE
now alias error: 'deployment `readyState` is `INITIALIZING` and not `READY`

### ISSUE THREAD

**Issue by brandonmp** [vercel/vercel#1211]
Using `now@10.2.1` on bash-for-windows

Deployment **works fine** and is accessible at the hash .now.sh URL, but when attempting to assign an alias, I get this error:

```
> Error! Unknown error: Error: The deployment `readyState` is `INITIALIZING` and not `READY`
Error: The deployment `readyState` is `INITIALIZING` and not `READY`
    at module.exports.Now.createAlias.alias.retry (/snapshot/repo/dist/now.js:3968:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I've tried re-deploying a few times, but no change in symptoms. 

Anyway to work around this, or any other way to assign an alias besides CLI?

**Comment by brandonmp** [comment]
gd it. Just as I tried to run it with `DEBUG=*` to add to this issue, it worked. I'll close this & just re-open if it happens again / to someone else. 

```
$ DEBUG=* now alias project-some-hash.now.sh some-alias.now.sh
  now:main start +0ms
  now:main falling back to default now provider 'sh' +20ms
  now:main user supplied known subcommand alias +0ms
> Success! some-alias.now.sh now points to project-some-hash.now.sh! [998ms]
```

**Comment by southpolesteve** [comment]
I am also seeing this after upgrading to the lastest `now-cli`

```
> Assigning alias graph.movecounselors.com to deployment...
> graph.movecounselors.com is a custom domain.
> Verifying the DNS settings for graph.movecounselors.com (see https://zeit.world for help)
> Verification OK!
> Error! Unknown error: Error: The deployment `readyState` is `INITIALIZING` and not `READY`
Error: The deployment `readyState` is `INITIALIZING` and not `READY`
    at module.exports.Now.createAlias.alias.retry (/snapshot/repo/dist/now.js:3968:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by markozxuu** [comment]
@southpolesteve Are you still experiencing that error?

**Comment by pantharshit00** [comment]
Same here
now:main start +0ms
  now:main falling back to default now provider 'sh' +47ms
  now:main user supplied known subcommand alias +0ms
> Error! An unexpected error occurred in alias: Error: Fetching a deployment failed
    at module.exports.EventEmitter.findDeployment.hostOrId.retry (/snapshot/repo/dist/now.js:634:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)


For now I am downgrading to 10.x release which feels stable to me

**Comment by leo** [comment]
This is not happening as of Now 2.0 anymore: https://zeit.co/blog/now-2
