### ISSUE TITLE
Long Running Docker Jobs

### ISSUE THREAD

**Issue by danrasmuson** [vercel/vercel#1214]
I'm wondering if `now` can handle long running tasks and not just short web services tasks? Think `serverless docker`.

Here is the example I setup.

## Code

Dockerfile
```
 FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip install -r requirements.txt
ENTRYPOINT ["python"]
EXPOSE 5000
CMD ["app.py"]
```

app.py
```
from flask import Flask
import time
app = Flask(__name__)

@app.route('/')
def hello_world():
  time.sleep(2)
  return 'Label On!'

if __name__ == '__main__':
  app.run(debug=True,host='0.0.0.0')
```

requirements.txt
```
Flask==0.10.1
```

## My Test

Then I deployed to now and scaled the deployment.

```
now
now scale <url> 1 auto
```

Lastly I sent a bunch of requests in the hope they would occur in parallel.

```
curl <deployment-url> & curl <deployment-url> & curl <deployment-url> & curl <deployment-url> & curl <deployment-url> & curl <deployment-url> & curl <deployment-url> & ...
```

But the requests were just processed sequentially :(

I also increased the scale of my deployment but didn't see any changes.

```
now scale <url> 5
```

**Comment by rauchg** [comment]
This is definitely how it works. How are you determining that they happened sequentially?

**Comment by danrasmuson** [comment]
The result I'm getting is...

```
<2 second pause>
Label On!
<2 second pause>
Label On!
<2 second pause>
Label On!
<2 second pause>
Label On!
<2 second pause>
Label On!
```

And if the requests were all hitting different instances I would expect...

```
<2 second pause>
Label On!
Label On!
Label On!
Label On!
Label On!
```
