### ISSUE TITLE
"now alias" error: The deployment `readyState` is `INITIALIZING` and not `READY

### ISSUE THREAD

**Issue by trevordmiller** [vercel/vercel#1217]
My workflow with `now` is to:
1) make changes
2) run `now` to deploy the changes, check they are ok
3) when everything looks good, run `now alias` to update my production custom domain with this latest deployment

I have the following now config in my `package.json`:

```json
"now": {
  "alias": "trevordmiller.com"
}
```

After upgrading from now `9.0.1` to `10.2.2`, running `now`, then `now alias` is giving me this error:

```
Error! Unknown error: Error: The deployment `readyState` is `INITIALIZING` and not `READY
```

![image](https://user-images.githubusercontent.com/5497885/38156070-9b02544e-3438-11e8-9d8a-57cecf64d72d.png)

Am I doing something wrong or is this a bug?

**Comment by trevordmiller** [comment]
Running `now ls` gives me the following:

![image](https://user-images.githubusercontent.com/5497885/38156387-ae5a78a8-343a-11e8-8862-bc00979bcb33.png)

I'm not sure if this is related, but is the `undefined` in `151 deployments found under undefined` a problem?

**Comment by markozxuu** [comment]
@trevordmiller I just tried in a static implementation, with the version of ``11.0.0-canary.33``works well, I'll have to try it in a nodejs application. When I have more information about the problem, I will let you know 🙏 

Related problem ----> #1211

**Comment by trevordmiller** [comment]
@MAPESO Thanks for looking into it. Here is my repo if it is helpful: https://github.com/trevordmiller/trevordmiller-website. I’ve tried re-running `now && now alias` multiple times with the same error.

**Comment by trevordmiller** [comment]
I’m on latest now CLI + macOS

**Comment by trevordmiller** [comment]
Also not sure if it is related but I use now via npm scripts instead of installing it globally (see the project’s package.json scripts: https://github.com/trevordmiller/trevordmiller-website)

**Comment by trevordmiller** [comment]
See thr project’s^ scripts in package.json: https://github.com/trevordmiller/trevordmiller-website

**Comment by markozxuu** [comment]
@trevordmiller I just deploy an application in React and I had an error caused by the ``yarn.lock`` file. add the file to ``.gitignore`` and the problem disappears.

I had no problem with now alias 😞

**Comment by markozxuu** [comment]
I will continue investigating this strange error :/

**Comment by trevordmiller** [comment]
I'm not sure if this is related, but is the `undefined` in `151 deployments found under undefined` a problem?

**Comment by brandonmp** [comment]
this happened to me in #1211 
It cleared up on its own inexplicably, but i just reopened as it's back now

**Comment by southpolesteve** [comment]
I am seeing similar errors right now `Deployment may only be scaled when it's READY or FROZEN, it was: BUILDING`

**Comment by javivelasco** [comment]
By now the `alias` command has been almost completely rewritten so I'm going to close this issue. Please reopen is somebody experience it again.
