### ISSUE TITLE
No output when using Now inside Travis CI

### ISSUE THREAD

**Issue by guiscaranse** [vercel/vercel#1222]
So, I've noticed that using Travis CI to directly deploy to now is causing some issues. Sometimes docker images take longer than the 10 minutes limit from Travis to compile. Travis will however reset the 10 minutes timer after a output from shell. 
I've noticed that when deploying from Travis using Now, it will not only produce nothing to the log, but Travis will sometimes throw a error because no output was given in the last 10 minutes.
Using `travis_wait` doesn't work and I have no idea why that. I think that maybe you guys should take a look at why there is no output from Now when running inside a CI

Here it is a screenshot of the problem
![image](https://user-images.githubusercontent.com/4432205/38177457-43dca1fa-35d8-11e8-8cd2-331fa6e0e365.png)

**Comment by leo** [comment]
This should be fixed with this https://github.com/zeit/now-cli/pull/1245 😊

**Comment by guiscaranse** [comment]
@leo it's available only in canary or is already in stable?
