### ISSUE TITLE
Documentation for other providers?

### ISSUE THREAD

**Issue by Siilwyn** [vercel/vercel#1227]
If I remember correctly there was some minimal explanation about the CLI in the readme which I can't find back on the website. Can I find any information about the usage of other providers somewhere? The CLI help message doesn't note anything about, the basic usage says:
`𝚫 now [options] <command | path>`
While it is:
`𝚫 now [options] [provider] <command | path>`

**Comment by rauchg** [comment]
We are working on improving official documentation as other providers become stable. For now, you'll have to refer to the `--help` / source code while it's in experimental mode.
