### ISSUE TITLE
Consider reading `.nvmrc` in addition to package.json→{,now.}engines.node

### ISSUE THREAD

**Issue by mathiasbynens** [vercel/vercel#123]
Currently, `now` reads `engines.node` or `now.engines.node` from `package.json` and uses that to determine the Node.js version to be used. https://zeit.co/now#what-version-of-node.js-do-you-run Being able to specify the Node.js version on a per-project basis is 👍!

However, lots of projects already have a `.nvmrc` file in their root directory that specifies the Node.js version to be used. Such projects currently have to duplicate that info to `package.json` for `now` to pick it up.

Suggestion: have `now` check for the existence of `.nvmrc` before attempting to read `package.json`.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
