### ISSUE TITLE
Could't find a deployment to alias. Please specify one from the command line.

### ISSUE THREAD

**Issue by jineshshah36** [vercel/vercel#1233]
When I run:

    now alias acmeco.arthr.sh -r rules.prod.subdomain.json

I get:

    > Error! Could't find a deployment to alias. Please specify one from the command line.

I'm running now 11.0.0. Before the update today, this command worked fine

**Comment by javivelasco** [comment]
Duplicate of #1229

**Comment by jineshshah36** [comment]
Is it a duplicate? I'm trying to use path aliases, not a specific deployment.

**Comment by jineshshah36** [comment]
Please reopen this issue, it's not fixed
