### ISSUE TITLE
Error! Custom domains are only enabled for premium accounts

### ISSUE THREAD

**Issue by JoseCage** [vercel/vercel#124]
Hello. Before all. Thank you som much for [zeit/now](https://github.com/zeit/now) project.

I have the project https://slack-invite-automation-gzrjrzqhif.now.sh on now.sh platform, so i tried to set a custom domain and return me message bellow. Can you help please help me.? If is required to upgrade the account or it sounds a dns configuration error?

`now alias set https://slack-invite-automation-gzrjrzqhif.now.sh app.josecage.com --debug`
> [debug] Checking for updates.
> [debug] Up to date (0.28.1).
> [debug] /list: 16848ms
> [debug] matched deployment wHGtUDaYCgjmhWOItJy2nWa6 by url slack-invite-automation-gzrjrzqhif.now.sh
> app.josecage.com is a custom domain.
> Verifying the DNS settings for app.josecage.com (see https://zeit.world for help)
> [debug] #1 GET /whois-ns: 1977ms
> [debug] Found domain josecage.com and nameservers graham.ns.cloudflare.com,heather.ns.cloudflare.com
> [debug] Trying to register a non-ZeitWorld domain josecage.com for the current user
> [debug] #1 POST /domains: 1023ms
> Error! Custom domains are only enabled for premium accounts. Please upgrade at https://zeit.co/account.

**Comment by jamo** [comment]
Yes, custom domains (not *.now.sh) do require premium plan.
You can change to premium plan at https://zeit.co/account#plan

**Comment by JoseCage** [comment]
@jamo Thank you so much and sorry..

As soon as possible i will update the plan for sure..

:+1:
