### ISSUE TITLE
Serverside connection fails resolving with EAI_AGAIN

### ISSUE THREAD

**Issue by pozylon** [vercel/vercel#1246]
name: 'FetchError',
  message: 'request to https://engine.unchained.shop/graphql failed, reason: getaddrinfo EAI_AGAIN engine.unchained.shop:443',
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN' }

unchained-website / flljhfpwxi

**Comment by brandonmp** [comment]
I just hit this as well, also with a `/graphql` endpoint. I'm using now's path alias feature to map the `/graphql` path to another now deployment.

Rolling back to a previous deployment (apparently) solved the error
