### ISSUE TITLE
Timeout while verifying instance count

### ISSUE THREAD

**Issue by mxstbr** [vercel/vercel#1247]
Constantly getting this error when running `now scale xyz`:

```
> Error! An unexpected error occurred in scale: Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:8878:13)
    at <anonymous>
```

**Comment by hakonkrogh** [comment]
+1
Getting when deploying to bru1

**Comment by mgranados** [comment]
+1 to sf1

**Comment by vtvz** [comment]
```
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
> Using Node.js 8.11.1 (default)
> https://experiment-qcjvbbvnfs.now.sh [in clipboard] (bru1) [912ms]
> Building…
> ▲ npm install
> ▲ Snapshotting deployment
> ▲ Saving deployment image (463)
> Build completed
⠧ Verifying instances in bru1> Error! An unexpected error occurred!
  Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:6281:13)
    at <anonymous> Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:6281:13)
    at <anonymous>
```

**Comment by omarkhaled11** [comment]
same here, deploying to bru1

**Comment by rauchg** [comment]
We are looking into this. To confirm, do you see anything in the app logs that would point to startup issues / not opening a HTTP port?

**Comment by omarkhaled11** [comment]
The app I uploaded doesn't record logs, the deployment was successful after a couple of tries, but the url provided gives 503 error, here's the given link https://brantu-task-ctmovfwubg.now.sh

what was happening is that the upload process goes fine but it gets stuck at verifying and then times out

**Comment by nnennajohn** [comment]
Same here. Just sent you guys an email before heading here to check the conversation.

![screen shot 2018-04-08 at 6 53 08 am](https://user-images.githubusercontent.com/1761197/38468374-8e5c5efc-3af9-11e8-8767-fd37c1b0d2e4.png)

**Comment by rwboyer** [comment]
I get the same on sfo1 trying to deploy anything with now

**Comment by heymartinadams** [comment]
Same!
```
Verifying instances in sfo1> Error! An unexpected error occurred!
  Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:6281:13)
    at <anonymous> Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:6281:13)
    at <anonymous>
```

**Comment by heymartinadams** [comment]
Ah! There was an error in my code, which I only discovered by deploying via `localhost` instead of `now`. Once fixed, I no longer received a timeout. So it might only occur if there’s an unrelated bug.

```
/Users/__USER__/Apps/__MY_APP__/node_modules/graphql-yoga/node_modules/graphql-tools/dist/schemaGenerator.js:341
                throw new SchemaError(typeName + "." + fieldName + " defined in resolvers, but not in schema");
                ^
```

**Comment by nnennajohn** [comment]
@heymartinadams So were you able to successfully deploy after this?

**Comment by heymartinadams** [comment]
Yes indeed, @nnennajohn! 😎

**Comment by nnennajohn** [comment]
Bummer for me. Successfully got it on heroku though, so I know its not some rouge function. :) Will wait to hear from the support team after the weekend. Hopeful. :)

**Comment by akabab** [comment]
+1, both `bru` and `sfo`, timeout

**Comment by antony** [comment]
Sorry, getting the same with bru1 and sfo1 since last night.

*update:* I also had broken code (third party dep) and it works fine after fixing that, same as @heymartinadams. This is a non issue for me!

Or rather... this is a messaging issue.

**Comment by bookofdom** [comment]
Any updates on this? this is holding me back.

**Comment by ianjsikes** [comment]
Just wanted to add, I'm seeing this too. It's only affecting one of my projects. I'm able to build and run it locally:
<img width="516" alt="image" src="https://user-images.githubusercontent.com/5607226/38632165-b9f72c58-3d70-11e8-9a0c-0c4c79074a66.png">

**Comment by benjtinsley** [comment]
i, too, am getting this error:

```
⠼ Verifying instances in sfo1> Error! An unexpected error occurred!
  Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:8446:13)
    at <anonymous> Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:8446:13)
    at <anonymous>
```

there are no errors in my code, i ran a standard JS task to clean and report any JS error, which came back with none.

**Comment by springrid** [comment]
Same here! Waiting for a way to deploy my app. :O

**Comment by ntziolis** [comment]
Yup keep seeing this again more and more last few days in our deployments (always bru1). This is completely breaking down our continuous deployments for 2 projects:
![image](https://user-images.githubusercontent.com/265338/39651133-048a77f2-4feb-11e8-91a0-50e52217c2c2.png)

Note sure what causes the log rate limiting, but we are on a paid account and far away from any limits nor do we deploy excessively.

Update:
This might be only happening on our CI agents where its pulling the latest version of the now CLI during every build. I'll check if this goes away to setting this to same as local version, but if that makes it go away then an error was introduced in a later version.

**Comment by javivelasco** [comment]
I'm pretty sure this is happening to you because you ran into a logs rate limit so we are unable to get the logging events to ensure that the instance is running. Temporarily you can just run the deploy with `--no-verify` but maybe we should consider this case on our side @rauchg

**Comment by ragingwind** [comment]
It's happened again to me. my app, and I also tested with now-example/hello-go. When I used `--no-verify`, deploying was completed but the apps didn't work well.

```
now
> Deploying ~/Workspace/now-examples/go-hello under
> https://go-hello-zfxrcdeozk.now.sh [in clipboard] (sfo1) [4s]
> Building…
> Sending build context to Docker daemon  4.096kB
> Step 1/7 : FROM golang:1.9-alpine as base
>  ---> b0260be938c6
> Step 2/7 : WORKDIR /usr/src
>  ---> Using cache
>  ---> 3c896b471e39
> Step 3/7 : COPY . .
>  ---> 606d53d6f6f1
> Step 4/7 : RUN CGO_ENABLED=0 go build -ldflags "-s -w" -o main
>  ---> Running in 1d409d44bdc9
> Removing intermediate container 1d409d44bdc9
>  ---> 323e9d832b79
> Step 5/7 : FROM scratch
>  --->
> Step 6/7 : COPY --from=base /usr/src/main /go-http-microservice
>  ---> cfe6c5685dea
> Step 7/7 : CMD ["/go-http-microservice"]
>  ---> Running in da80dd77058f
> Removing intermediate container da80dd77058f
>  ---> 15f3d2c0f800
> Successfully built 15f3d2c0f800
> Successfully tagged registry.now.systems/now/685e5f16b3f11c86f95fb93bcbe4b83178a48758:latest
> ▲ Storing image
> Build completed
⠹ Verifying instances in sfo1> Error! An unexpected error occurred!
  Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:6281:13)
    at <anonymous> Error: Timeout while verifying instance count (10m)
    at waitForScale (/snapshot/repo/dist/now.js:6281:13)
    at <anonymous>
```

**Comment by IsmiKin** [comment]
I'm having same here :raised_hand_with_fingers_splayed: (I'm using `now-cli` version `12.1.2`)

**UPDATE**: I changed the region from `bru1` to `sfo1` and it seems working back.. issues with `bru1` region? I have another deployment on `bru1` though.

All the process went fine, here the logs from the deployment:
```
11/14 12:11 PM (6m) yarn
11/14 12:11 PM (6m) yarn install v1.9.4
11/14 12:11 PM (6m) [1/4] Resolving packages...
11/14 12:11 PM (6m) [2/4] Fetching packages...
11/14 12:12 PM (6m) info fsevents@1.0.17: The platform "linux" is incompatible with this module.
11/14 12:12 PM (6m) info "fsevents@1.0.17" is an optional dependency and failed compatibility check.Excluding it from installation.
11/14 12:12 PM (6m) info fsevents@1.2.4: The platform "linux" is incompatible with this module.
11/14 12:12 PM (6m) info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
11/14 12:12 PM (6m) [3/4] Linking dependencies...
11/14 12:12 PM (6m) [4/4] Building fresh packages...
11/14 12:12 PM (6m) Done in 23.48s.
11/14 12:12 PM (6m) npm run build
11/14 12:12 PM (6m)
11/14 12:12 PM (6m) > centralized-login@0.1.0 build /home/nowuser/src
11/14 12:12 PM (6m) > react-scripts build
11/14 12:12 PM (6m)
11/14 12:12 PM (6m) Creating an optimized production build...
11/14 12:12 PM (6m) Compiled successfully.
11/14 12:12 PM (6m)
11/14 12:12 PM (6m) File sizes after gzip:
11/14 12:12 PM (6m)
11/14 12:12 PM (6m)   144.03 KB  build/static/js/main.88c0f8b5.js
11/14 12:12 PM (6m)   18.72 KB   build/static/css/main.b014df2d.css
11/14 12:12 PM (6m)
11/14 12:12 PM (6m) The project was built assuming it is hosted at the server root.
11/14 12:12 PM (6m) To override this, specify the homepage in your package.json.
11/14 12:12 PM (6m) For example, add this to build it for GitHub Pages:
11/14 12:12 PM (6m)
11/14 12:12 PM (6m)   "homepage": "http://myname.github.io/myapp",
11/14 12:12 PM (6m)
11/14 12:12 PM (6m) The build folder is ready to be deployed.
11/14 12:12 PM (6m) You may serve it with a static server:
11/14 12:12 PM (6m)
11/14 12:12 PM (6m)   yarn global add serve
11/14 12:12 PM (6m)   serve -s build
11/14 12:12 PM (6m)
11/14 12:12 PM (5m) Snapshotting deployment
11/14 12:12 PM (5m) Saving deployment image (25.8M)
```

```
$ now
....
> ▲ Snapshotting deployment
> ▲ Saving deployment image (25.8M)
> Build completed
> Verifying instantiation in bru1
> Error! Instance verification timed out (3m)
> Read more: https://err.sh/now-cli/verification-timeout
```

**Comment by hleumas** [comment]
I am having the same problem with bru over the last few days.

Every now and then my deployment refuses to scale in bru with verification timeout (yes, it really is not running). There is no error in logs.

**Comment by paulogdm** [comment]
@hleumas We have fixed a problem with scaling affecting BRU1 a few hours ago. Can you retry?

**Comment by hleumas** [comment]
It's working seamlessly. Thanks @paulogdm .

**Comment by drobnikj** [comment]
+1
I have the same issue in BRU1 region today. Is there a way to increase timeout?

**Comment by s-r-jones** [comment]
We have not been able to scale up BRU1 on the first try for about a month.

**Comment by antony** [comment]
Between 40% and 80% of my deploys fail (it varies from day to day( on BRU1 due to this problem. I'm running out of options.

Today I've had 2 successful deploys out of 12 and still going.

**Comment by nathanabloom** [comment]
> This should never happen again in the latest both stable and canary releases!
> Please reopen if anybody else experiences this issue.

@javivelasco This should be reopened. I have instance verification timeouts for latest stable release versions in bru1. Tested versions 14.2.0 on up all the way to lts 15.3.0. 

It feels like there just aren't enough resources allocated for bru1 anymore: 

<img width="1437" alt="Screen Shot 2019-05-30 at 10 28 00 AM" src="https://user-images.githubusercontent.com/6900211/58647957-da0d8c80-82c5-11e9-9a46-2fb1ea82f075.png">

Is this true?
