### ISSUE TITLE
Allow override start script from now.json

### ISSUE THREAD

**Issue by robinvdvleuten** [vercel/vercel#1248]
It would be nice to have the ability to set a custom start script in the `now.json` file. This allows to have multiple "now" projects in a single repository.

**Comment by timneutkens** [comment]
Not sure how this would work, how would you have multiple projects in one directory 🤔

You could have multiple projects in one repository, in separate directories, all with their own now.json / package.json.

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), there are no `start` or `now-start` scripts anymore. Please adapt your deployment, if you have the time! 😊
