### ISSUE TITLE
Deploying to bru1 via package.json

### ISSUE THREAD

**Issue by seveves** [vercel/vercel#1254]
I've added this to the `now` section in my `package.json`:
```
"scale": {
      "bru1": "auto"
}
```

This outputs `scale['bru1'] should be object` but I used it like described in the [docs](https://zeit.co/docs/features/configuration#scale-(object))

now version is 11.0.1 on Windows 10 x64.

PS: I'm so happy that EU servers are now available. Great work!

**Comment by leo** [comment]
This should definitely work! Thanks for reporting 😊

**Comment by leo** [comment]
We updated the documentation. It now [shows](https://zeit.co/docs/features/configuration#scale-(object)) the correct config options... 😊 

Sorry for the confusion!
