### ISSUE TITLE
`now alias` with token failing, due to "too many args"

### ISSUE THREAD

**Issue by mattfysh** [vercel/vercel#1262]
```
now -t $NOW_TOKEN alias $URL $ALIAS
> Error! `now alias <deployment> <target>` accepts at most two arguments
```

This works if I remove the token, therefore the alias command appears to be erroneously including the token when performing args length validation.

Upon searching the repo, I found that the `scale` command may also be affected

**Comment by mattfysh** [comment]
@Qix- that worked! thank you :)

**Comment by Qix-** [comment]
It will be soon :+1: Definitely a bug.
