### ISSUE TITLE
`now alias MYDOMAIN -r rules.json` does not set the proxy rules

### ISSUE THREAD

**Issue by flaviogranero** [vercel/vercel#1265]
Hi,

After a successful deploy with `now deploy`, I'm trying to update a custom domain alias with the command:

`now alias MYDOMAIN -r rules.json`

The domain is correctly set, and the alias is created with success, pointing to the new instance. The problem is I need some proxy rules to consume an external API, and those rules (which are defined in rules.json file) are not being set at the custom domain.

I'd really appreciate a workaround for this, as my current production site is down atm.

now-cli version: 11.0.5

Thanks

**Comment by javivelasco** [comment]
Hi @flaviogranero! Sorry, it looks like with the refactoring we missed the use case. I'm working on a fix we are releasing ASAP. Thanks for reporting

**Comment by javivelasco** [comment]
This is fixed in the latest release!
