### ISSUE TITLE
Update Checker is not working and reporting bad warnings

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#1268]
For @sergiodxa the program is simply not reporting that a new version is available. He's still in `11.0.0-canary.33` and not getting any sort of warning.

This probably extends to many other users.

**Comment by rauchg** [comment]
In addition, it renders `UPDATE AVAILABLE` when there is in fact no update available

![image](https://user-images.githubusercontent.com/13041/38447757-591188f8-39b4-11e8-91de-bc6af540373e.png)

**Comment by leo** [comment]
This is fixed, now that we're using a new update checker. Verified with @sergiodxa when I was in SF!
