### ISSUE TITLE
[12.0.0-canary.5] `--regions sfo` deploys in bru

### ISSUE THREAD

**Issue by lmachens** [vercel/vercel#1270]
I am using https://github.com/jkrup/meteor-now for deployments, but I think this question belongs here.
Passing `--regions sfo` to set the deployment region is not working for me. It always scales new deployments to `bru 0 1`.
@timneutkens told me to try out `--force` , but it is the same.

**Comment by lmachens** [comment]
@javivelasco this is still an issue. using `12.0.0-canary.33`

**Comment by javivelasco** [comment]
@lmachens You can configure the default deployment regions using `now.json` as stated in the documentation. Also, you have flags to decide where to deploy in the deploy command. I tested them and it works nicely.

**Comment by lmachens** [comment]
@javivelasco Did you try it out with `meteor-now` too? I am not using a `now.json` and pass only env params.
Maybe it is related to `meteor-now` but it just pass the arguments to `now`.

**Comment by lmachens** [comment]
It is related to `meteor-now`.
See https://github.com/jkrup/meteor-now/pull/109
