### ISSUE TITLE
Deployment time has increased

### ISSUE THREAD

**Issue by gkiely** [vercel/vercel#1271]
Problem: verifying instances message takes a lot of time (typically 30s)

<img width="270" alt="screen shot 2018-04-07 at 11 13 40 am" src="https://user-images.githubusercontent.com/1948935/38458585-c34cd5ba-3a54-11e8-9a29-a9cc05b14c6b.png">

**Comment by javivelasco** [comment]
If you want to skip the verification step you can pass `--no-verify` when you deploy.

**Comment by gkiely** [comment]
Perfect thanks.
