### ISSUE TITLE
Now alias tries to set the alias `alias.now.sh` if you use a token

### ISSUE THREAD

**Issue by antony** [vercel/vercel#1278]
Depending if you pass --token first or last, the command works, or tries to do something insane.

I'd expect this to work either way around.

```bash
>
$ now alias --token=my-token    
> Assigning alias abc.now.sh to deployment aaa-bbb.now.sh
> Success! abc.now.sh now points to aaa-bbb.now.sh! [3s]

>
$ now --token=my-token alias
> Assigning alias alias.now.sh to deployment aaa-bbb.now.sh
> Error! The alias alias.now.sh is in use by a different team.
```

**Comment by antony** [comment]
Possibly related to #1262

**Comment by antony** [comment]
```bash
$ now -v
11.0.6
```

Should I be using a canary version?

**Comment by javivelasco** [comment]
@antony no need to use canary but errors should be always reproduced on canary before opening the issue. In this case it's a solved issue :) Thanks for reporting though
