### ISSUE TITLE
Builds failing, but only indication is dashboard 'error' badge

### ISSUE THREAD

**Issue by brandonmp** [vercel/vercel#1283]
Using `next@5.1` with `typescript@2.8` and `now@11.0.7` (have also tried `now@12.0.0-canary.5`)

The branch builds and runs locally (win 10, node 9 using bash for windows) in ~120 seconds with no errors. 

However, when deploying to `now`, the build hangs indefinitely on `next build`. 

The only indication that something's gone wrong is in the `now.sh` dashboard, where the big red "ERROR" badge appears (usually within the first few minutes of deploying):

![image](https://user-images.githubusercontent.com/14139991/38535206-7500120c-3c50-11e8-804c-380006ef58c8.png)

But the logs show no error (these are from `now.sh`, but they basically mirror my terminal): 

```
04/09 11:43 PM (4m) install
04/09 11:43 PM (4m) ✓ Using "yarn.lock"
04/09 11:43 PM (4m) ⧗ Installing 89 main dependencies…
04/09 11:43 PM (4m) npm run build
```
note that my `build` script is simply `NODE_ENV=production next build`

**But,** when I switch to my `master` branch and deploy, however, it builds fine. There aren't any architectual differences b/t the two branches (just a new route and some new components), so the build process is about the same.

So, I assume it's gotta be something in my code that's breaking the build, but I can't figure out why:

(a)  it builds locally just fine
or (b) there's no error message at all

Is there anyway to debug this? or maybe more detailed logs available server-side? `now` should be printing some indication as to why it's failing, right?

**Comment by rauchg** [comment]
Thanks @brandonmp. We've had a few reports of build failures like this, and we're looking into them. ERROR definitely means the job exited with a non-zero error code, ran out of time or resources. 

We should definitely add a special log line here (or simply more metadata to the `build-stop` event in `now inspect <url>`), for all of us to find out what went wrong.

This is a top priority for us right now, so it should be fixed shortly.

**Comment by brandonmp** [comment]
thanks @rauchg . I actually upgraded to Pro to try and rule-out memory constraints, but that didn't help.

Besides resource constraints, are there any other places you'd suggest checking to find the problem here? The fact that it works locally, but not on `now`, suggests some weird env. problem. Is there some way to reproduce the `now` build environment locally? 

I def. appreciate you all are working hard to get it fixed fast, but in the mean time, I can't deploy til' I figure this out, so I've gotta keep troubleshooting :/

**Comment by JosephScript** [comment]
Running into the same issue here.I'm using webpack so I was able to find an error using the verobse flag like this: `webpack --display verbose`.

Hopefully that helps!


*edit*

Here's the error:

```
> webpack --config webpack.config.js --devtool source-map --display verbose
> module.js:549
>     throw err;
>     ^
>
> Error: Cannot find module '/home/nowuser/src/webpack.config.js'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at requireConfig (/home/nowuser/src/node_modules/webpack/bin/convert-argv.js:97:18)
>     at /home/nowuser/src/node_modules/webpack/bin/convert-argv.js:104:17
>     at Array.forEach (<anonymous>)
>     at module.exports (/home/nowuser/src/node_modules/webpack/bin/convert-argv.js:102:15)
>     at yargs.parse (/home/nowuser/src/node_modules/webpack/bin/webpack.js:171:41)
>     at Object.Yargs.self.parse (/home/nowuser/src/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
```

The file is named correctly and in the root of the app. So I'm not much farther on finding a solution, but one step at a time.

**Comment by jamo** [comment]
The main UX issue here seems that `now-cli` doesn't exit when deployment fails. 
We have a fix coming up shortly.

**Comment by brandonmp** [comment]
@jamo  I agree that's a problem, however there's something else at play here for me (though fwiw it's likely out of scope for this issue). 

as i mentioned in my OP, my build completes fine locally, but the project simply won't build on `now`. 

even more confusing: when I bundle my app in a simple `docker` container, it deploys to `now` just fine:

```
FROM node:alpine

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json yarn.lock /usr/src/app/
RUN yarn
# Bundle app source
COPY . /usr/src/app
RUN yarn build
EXPOSE 3000
CMD [ "npm", "start" ]
```

So the lack of error message is definitely a pain, but at the end of the day, the fact that the `now` environment breaks an otherwise functional build is more troubling imo.

**Comment by JosephScript** [comment]
Just wanted to help others who might run into this issue.

My issue was resolved by removing the `files` entry from my `package.json`, which will prevent any other files from being uploaded other than what's in the list there (used commonly when publishing packages to NPM). See more [here](https://docs.npmjs.com/files/package.json#files).

I would suggest looking through your package.json for any other configurations that might cause an issue.

**Comment by markozxuu** [comment]
@rauchg @jamo The problem is the file ``yarn.lock`` a solution could be that the file is ignored in the build process.

**Comment by JosephScript** [comment]
What @MAPESO  said could be true. When you make a deployment and see the error badge there, you can click "files" on the top right to see what files are on the server. If you're missing some that could be a good indication.

**Comment by karl-run** [comment]
I'm also seing this. I haven't been able to deploy since monday because of it.

**Comment by brandonmp** [comment]
@karl-run i mentioned this above, but in case it might help, moving my app to a `Dockerfile` and deploying that instead of the `node` deployment worked. 

i also rolled back to `now@10.6.1` , not sure if that mattered, though.

**Comment by 13806** [comment]
Running` npm install` instead of `yarn install` at npm v5.3.0 fixes this one for me.

**Comment by markozxuu** [comment]
@rauchg @jamo This problem is more related to the number of dependencies, when they are few it does not cause any problem, but projects like create-react-app there is a conflict with the file ``yarn.lock``

**Comment by karl-run** [comment]
@MAPESO That's not correct. I'm getting this error on a node server with a few dependencies.

**Comment by PhilipBridges** [comment]
Having this issue too :/

Tried deploying a build that previously worked totally fine, but it just isn't working anymore.

edit: My "invisible" issue was fixed by updating my yarn.lock.

**Comment by den1k** [comment]
Running into this too, would be great to auto-rollback the CLI when this is knows. Just lost a few hours due to this.

**Comment by trevordmiller** [comment]
> "Tried deploying a build that previously worked totally fine, but it just isn't working anymore."

Same, starting this week. I'm a premium user. Everything is working as expected locally but fails on `now`.

**Comment by brandonmp** [comment]
FWIW I think my issue was that `devDependencies` weren't being installed in the `now` build environment. This is how it's supposed to work according to the docs, I just didn't realize / think of it.

So, some build dependencies were listed under `devDependencies`, and when the build couldn't find them post `yarn`, it failed (the failing silently was another matter I think). Moving everything to regular `dependencies` did the trick.

HTH someone

**Comment by den1k** [comment]
Since we use docker the above doesn’t apply to us.
