### ISSUE TITLE
now alias fails with "TypeError: Cannot read property 'includes' of undefined"

### ISSUE THREAD

**Issue by richardthombs** [vercel/vercel#1286]
I have two deployments, one is a website frontend and the other is an api backend. Before 11.x was released, I used to set up the path aliasing by running `now alias -r now-rules.json` from the root of my project (the deployments are in sub-directories).

When I do that now, firstly I get asked "Assigning alias xxx to deployment yyy, are you sure?", which never used to happen, and then the alias itself fails with the error "Cannot read property 'includes' of undefined"

```
now alias retailarmy.com -r now-rules.json
> Assigning alias retailarmy.com to deployment retailarmy-yvfogqnqer.now.sh
> Are you sure? [y|N] > Error! An unexpected error occurred in alias: TypeError: Cannot read property 'includes' of undefined
    at Now.findDeployment (C:\snapshot\repo\dist\now.js:594:24)
    at fetchDeployment (C:\snapshot\repo\dist\now.js:3810:34)
    at fetchDeploymentFromAlias (C:\snapshot\repo\dist\now.js:4563:74)
    at assignAlias (C:\snapshot\repo\dist\now.js:4601:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

now-rules.json looks like this:

```
{
    "rules": [
        {
            "pathname": "/api/**",
            "dest": "api.retailarmy.com"
        },
        {
            "dest": "static.retailarmy.com"
        }
    ]
}
```

**Comment by rauchg** [comment]
@richardthombs this issue should be fixed in canary, and in the stable that lands next
