### ISSUE TITLE
updating now alias to new deployments does not scale down existing deployments (noticed on v11.0.7)

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#1287]
Just noticed this on version 11.0.7, but this problem has been going on for a few days ever since around the time the BUR region came online (unrelated, but now-cli was updated for it).

This problem goes away in version 12.0.0-canary.9 release.

I am just wondering if there is any chance for the fix to make its way to v11 so I don't have to be on canary.

1. I have an alias with scaling set to min: 1 max: 3.
2. My deployment steps deploy a new deployment, defaults to min: 0 max: 1
3. The deployment is tested, if ok, apply assign alias to new deployment so it gets min: 1 max: 3 scaling; while the old deployment fall back to min: 0 max 1 and idles out to 0 in time. I use the old deployments for record keeping and rollback.

Started a few days ago in version 11, when an alias is moved, the old deployment is not scaled back down.

Upgrading to version 12 canary fixed this, but I don't want to be on canary. Is it possible for this bug to be addressed in the current version?

**Comment by rauchg** [comment]
This is indeed being upgraded to stable 👌

**Comment by wiiiimm** [comment]
@rauchg thanks for the quick comment. any idea on ETA. It is currently breaking some of my deployment steps so I am on canary now. When should I check back and try v11 again?

**Comment by wiiiimm** [comment]
issue is fixed now in `v11.1.4`
