### ISSUE TITLE
getting  a "deploy failed" error

### ISSUE THREAD

**Issue by mreinstein** [vercel/vercel#129]
### repro steps:

1. go to https://nodered-ldzodlpekq.now.sh

2. go to the web tab

3. from the nodes listed in the left pane, under "output", drag a "debug" node onto the main work area

4. drag a 2nd "debug" node onto the canvas

5. click the red "deploy" button  in the top right.

6. Notice you get the error below:

<img width="679" alt="screen shot 2016-11-14 at 9 08 16 pm" src="https://cloud.githubusercontent.com/assets/718067/20295817/27f6d35a-aabc-11e6-8520-40a162fb64e6.png">

**Comment by mreinstein** [comment]
my `package.json`:

``` javascript
{
  "name": "nodered",
  "private": true,
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node-red -p 80",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "aws-config": "x.x",
    "aws-sdk": "x.x",
    "dynamodb-data-types": "x.x",
    "node-red": "^0.15.2",
    "node-red-contrib-aws": "x.x",
    "node-red-contrib-aws-dynamodb": "x.x",
    "node-red-node-watson": "^0.4.28"
  },
  "engines": {
    "node": "4.x.x"
  }
}
```

**Comment by jamo** [comment]
I actually couldn't reproduce the error; however I saw a bunch of such errors in the logs
The error comes from `body-parser` and seems like there would be something wrong in the json it receives...

**Comment by mreinstein** [comment]
@jamo thanks for taking a look! you may have to add a few debug nodes to trigger it.

There doesnt seem to be any way to view logs or track these things down. do you have any suggestions in terms of debugging going forward?

**Comment by jamo** [comment]
For now, it's recommended to use external logging services, like papertrail. A temporary insecure bad-for-production-use way would also to redirect stdout and stderr to a file, under `/tmp` and serve the log file as part of the application...

**Comment by jamo** [comment]
btw, you can also DM me in zeit.chat Slack community

**Comment by mreinstein** [comment]
ok, I guess for now I'll close this with the assumption that it is something wrong with my application. Thanks for your time!
