### ISSUE TITLE
transition to webpack 4

### ISSUE THREAD

**Issue by markozxuu** [vercel/vercel#1291]
the new version of **Webpack 4** offers some performance advantages that refer to the production mode that we could take advantage of with ``now-cli``

**Comment by markozxuu** [comment]
I was going to send a PR, but first I want to know your opinion @leo 🙏

**Comment by leo** [comment]
I would love to use the latest Webpack in here 👍

**Comment by markozxuu** [comment]
@leo I take care of that task 🙏

**Comment by leo** [comment]
Sorry for closing your PR! But as of Now CLI 12.0.0, we decided to switch to Rollup instead. I will take care of that this week.
