### ISSUE TITLE
Now v11 sometimes failing with certain logs

### ISSUE THREAD

**Issue by nickbreaton** [vercel/vercel#1298]
Hello zeit and friends,

First off thanks for creating this awesome tool. I am currently building a project using for my university class and using `now` for continuous deployment really puts us ahead of the curve. 

We are currently running each push to our `dev` branch through Travis CI and having Travis run `now deploy` on our project. I am using a docker image that produces quite a bit of logs. I have been using whatever the latest available version of `now` on each deploy. About 7 days ago I see that my build started failing the majority of the time. This is due to the now CLI exiting with an error: 

```
> Error! An unexpected error occurred!
  TypeError: Cannot read property 'replace' of undefined
    at printEvent (/snapshot/repo/dist/now.js:11109:17)
    at Parser.onData (/snapshot/repo/dist/now.js:11323:34)
    at Parser.emit (events.js:159:13)
    ...
```

To be clear, the deploy still continued and completed through now, but the command exited with that error. You can probably see how the throughs a wrench into our CD pipeline.

I took a look at the `printEvent` method and it seems it was changed about 9 days ago. So I'm pretty confident the issue lies here.

https://github.com/zeit/now-cli/blame/abdb261717e6525aef310bd91add7399308e0ee0/src/providers/sh/commands/deploy.js#L1006

There are only two three `.replace` function calls in that method and two of them look like they are definitely called on strings. This leaves me to believe `text.replace(/\n$/, '')` is the culprit.

As stated earlier, this error only occurs some of the time. I believe this to be due to us being on a free plan so our logs are rate limited, so we only receive the output that causes this error some of the time. 

I am wondering if anyone knows what could cause `text` to be `undefined`. If you have any ideas please let me know. I will attempt to submit a PR to fix this, however I wanted to document it first.

I was able to reproduce this locally, but if you would like to see the Travis logs you can see them [here](https://travis-ci.org/tasklog/tasklog/builds). One specific commit with the error is [here](https://travis-ci.org/tasklog/tasklog/builds/364621292). 

Thanks again for producing this tool. Hopefully I can find a fix for this issue when I get a moment.

**Comment by leo** [comment]
This is fixed as of Now CLI 12.0.0!
