### ISSUE TITLE
Error on logs page (version 11.1.4)

### ISSUE THREAD

**Issue by tima101** [vercel/vercel#1306]
When I look at logs of any deployment, I frequently get error on the page: `An error has occurred`
![image](https://user-images.githubusercontent.com/10218864/38771634-6acdcbba-3fdb-11e8-9542-cf0045e0b954.png)

To temporary get rid of it, I have to refresh tab.

When error occurs, browser console shows this error.
```
Cannot read property 'localeCompare' of undefined
TypeError: Cannot read property 'localeCompare' of undefined
```

**Comment by rauchg** [comment]
The bug has been fixed and should be live. Please let us know if anything else goes wrong. Thank you for your feedback!

The root cause of the issue was a heartbeat packet (an empty JSON object) emitted by the JSON stream not being ignored correctly.
