### ISSUE TITLE
"Timeout while verifying instance count" is misleading

### ISSUE THREAD

**Issue by veksen** [vercel/vercel#1308]
The error doesn't seem to be what it really is. It seems to be shown when a deployment fails, which can be really offsetting for a new user, because it sounds like the problem comes from now.sh, but it's not! (unless there are times where it really is?)

**Comment by rauchg** [comment]
@veksen. Yep we are fully aware and we have a good improvement in the canary channel. It shows the instance logs while they're booting up for the first time, so you can get feedback on whether there are obvious user errors or not.

Please try out the canary channel and let me know what you think!

**Comment by rauchg** [comment]
The improvement by @javivelasco just landed in canary and stable channels.

![image](https://user-images.githubusercontent.com/13041/38847757-28ad128e-41b8-11e8-981c-ab6f1ac86160.png)

Notice that you can see the instance logs (indexed with `[$N]`, in case you're verifying several DCs / instances at once).

Let me know what you think
