### ISSUE TITLE
(zeit.co homepage) UI bug on add-ons page

### ISSUE THREAD

**Issue by brandonmp** [vercel/vercel#1310]
forgive the misplaced issue, I didn't see a repo for homepage stuff

On the page: https://zeit.co/account/add-ons

the running total at page load is returning `NaN`:
![image](https://user-images.githubusercontent.com/14139991/38780969-6b1d878c-40ac-11e8-98e2-0ed097f9fcd9.png)

adding items to the cart doesn't change it:
![image](https://user-images.githubusercontent.com/14139991/38780992-b9e692c8-40ac-11e8-8284-e71a0faff4ce.png)

authenticated, Chrome 65 / win 10

**Comment by leo** [comment]
Fixed!
