### ISSUE TITLE
If .gitignore present, first use that then override with "files" option

### ISSUE THREAD

**Issue by gkiely** [vercel/vercel#1312]
Use case: I have ignored files in .gitignore but just wanted to add a 'dist' folder to my deployment.

Problem: I added 'dist' to "files" option in now.json, but now it only uploads 'dist', this is not what I expected/wanted, i now have to go through all my files and add them to "files" which is annoying.

Solution: Upload all files except those specified in .gitignore, allow "files" option to override.

**Comment by juanmaguitar** [comment]
I think the PR #1126 is related to this.
I think how it works now is:
- Only a `.gitgnore` → It will upload all the files but the ones in `.gitignore` 
- a `.gitgnore` and a `now.json` w/ a `files` property → It will upload ONLY the files and folders specified at the `files` property 

In my case i had this `.gitignore`
```
js/config.js
```
So, the first `now` deployed all the files but this one that is needed for my project in production
To solve this i created this `now.json`
```
{
  "files": [ 
    "js",
    "css",
    "index.html"  
  ],
  "type": "static"
}
```
With this `now.json`, all these files & folders (`css` & `js` folders & `index.html` file), specified at the `files` property, were properly deployed (including the  `js/config.js` in `.gitignore`)

**Comment by gkiely** [comment]
@juanmaguitar 

> a .gitgnore and a now.json w/ a files property → It will upload ONLY the files and folders specified at the files property

Yeah this is the problem I'm referring to.

For me the best use case would be to upload everything by default, except those in .gitignore and then override with now.json where needed.

**Comment by juanmaguitar** [comment]
@gkiely 

> For me the best use case would be to upload everything by default, except those in .gitignore and then override with now.json where needed.

Agree! That would be a more natural behavior

**Comment by gkiely** [comment]
For anyone else running into this, as @rdev has pointed out you can use .npmignore to get around the issue for the time being.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

The `files` property is not supported anymore.

Since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
