### ISSUE TITLE
multiple now deploy throws error

### ISSUE THREAD

**Issue by kamilml** [vercel/vercel#1325]
![img](https://i.imgur.com/AidUHCY.png)

I was doing multiple deploys at the same time, with different enviroment variables, and get this error.
I got this at the 4th and 6th try.

Anyway, my deployments are doing ok.

**Comment by rauchg** [comment]
Is your client up to date? Can you please share your client version?

**Comment by kamilml** [comment]
it is not :(
v9.3.0

but I am updating to 9.3.3 just now.

**Comment by jamo** [comment]
11.1.7 is the latest stable release btw
https://github.com/zeit/now-cli/releases/tag/11.1.7
