### ISSUE TITLE
Feature Request: Self destroy flag 💣

### ISSUE THREAD

**Issue by onordbo** [vercel/vercel#1327]
I know that the domains are pretty much impossible to discover by random users, but the sleeping state of any given now instance is still stored on a server somewhere, and can be "woken" up again if someone visits an old link. This causes a lot of confusion if people are unintentionally opening old temporary deployments.

As a user that works on projects where a lot of temporary Now deployments are passed around quite often, I'd like to be able to flag a deployment with something along the lines of `--destroy 48h`. The idea being here that a deployment would automatically tear down itself (like `now rm` does) after a specified amount of hours.

**Comment by Qix-** [comment]
What about a "delete on scale to 0" option? Would that solve the use-case?

**Comment by onordbo** [comment]
@Qix- That would definitely solve the principal use-case, although I think the flexibility of a user defined duration would come in very handy in a few situations where one would need a deployment to be available for longer than the default duration until the deployment scales down.

**Comment by leo** [comment]
WIth the new pricing introduced in [Now 2.0](https://zeit.co/blog/now-2), instances are completely gone. Furthermore, quickly accidentally opening a deployment will cause in unfreezing very quickly and causing basically no load (no money wasted).

If you completely want to prevent this, please run `now rm <deployment>`.
