### ISSUE TITLE
Load balancer and user session

### ISSUE THREAD

**Issue by tima101** [vercel/vercel#1338]
I've searched through issues and google - could not find an answer.

Does load balancer at Now have feature similar to [sticky cookie](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#sticky) feature of Nginx?

If I scale app to 2 instances.
App's user logs into instance-1. 
Does Now's load balancer ensure that user's requests are forwarded to instance-1 and _not_ instance-2?

**Comment by tima101** [comment]
@ashtonsix Thanks. Have you tested it? Does it work?

@leo Please consider adding `session-affinity` to [Configuring Now](https://zeit.co/docs/features/configuration)

**Comment by ashtonsix** [comment]
@tima101 not yet, but I'm gonna (some point this month)

**Comment by leo** [comment]
This flag does not apply anymore (since [Now 2.0](https://zeit.co/blog/now-2)). 😊

**Comment by Introvertuous** [comment]
@leo sorry I am unclear of the resolution here, are you saying that user session is no longer possible with v2?

**Comment by juliangruber** [comment]
They are still possible, but only when not relying on sticky routing. It's common practice to store sessions in a database that all your deployments have access to.
