### ISSUE TITLE
travis deploy fails after timeout

### ISSUE THREAD

**Issue by sobolevn** [vercel/vercel#1340]
While running deploy on `travis` my build freezes:

```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
```

Link: https://travis-ci.org/wemake-services/wemake-vue-template/builds/375803900#L1265

That's what I do:

```sh
  npm install -g now

  # Building new instance:
  now deploy \
    --token="$NOW_TOKEN" \
    --no-clipboard \
    --public \
    --npm \
    --dotenv=config/.env \
    --local-config=../now.json

  # Setting new instance as a default one:
  now alias --token="$NOW_TOKEN" --local-config=../now.json
```

Link to the full source code: https://github.com/wemake-services/wemake-vue-template/blob/master/tests/deploy.sh#L19

That's how my deploy looks inside dashboard:
<img width="835" alt="2018-05-07 12 25 06" src="https://user-images.githubusercontent.com/4660275/39695551-a7d98b96-51f3-11e8-8f7b-c2ece8b2c470.png">

Everything works fine locally.

**Comment by leo** [comment]
This should be working just fine as of [Now 2.0](https://zeit.co/blog/now-2) (considering you will adapt your code)! 😊
