### ISSUE TITLE
Can't install npm modules from 3rd party registries (FontAwesome pro)

### ISSUE THREAD

**Issue by MarkLyck** [vercel/vercel#1341]
I could successfully deploy my app using the now CLI before adding the fontawesome pro packages to my dependencies.

after adding the pro dependencies (which require an npm registry with an auth-token that gets validated on their end). I got the error

```
> Could not find "@fortawesome/fontawesome-pro-regular" in the module registry!
>
> If this is a private module then pass the `--forward-npm` flag and try again!
```

I then did as the instructions said and ran the command `now --public --forward-npm` assuming it would forward my .npmrc file containing the auth-token required.

However I still get the same error? How can I add npm packages that require a .npmrc file that sets it to the correct validated registry?

the .npmrc file looks like this

```
@fortawesome:registry=https://npm.fontawesome.com/
//npm.fontawesome.com/:_authToken=XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX
```

I can install the npm modules fine on my local machine. It seems like now doesn't support 3rd party registries at all. :(

**Comment by robinvdvleuten** [comment]
Same here! It would be nice if a `.npmrc` file in the root of the project is respected. This is also the way a lot of CIs and Heroku work.

**Comment by juhaelee** [comment]
would really love this ability as well!

**Comment by julianrubisch** [comment]
For the record, the responsible section seems to be (?) 

https://github.com/zeit/now-cli/blob/3ee18e70511d839f9f5ed2da86100ac50f272c08/src/providers/sh/util/index.js#L921

**Comment by bloqhead** [comment]
Also a blocker for me as well. I'm using the Pro SVG icons in a Vue project and I can't deploy because of this. So now I have to either resort to using the free Font Awesome (even though I paid for Pro) and rewrite parts of my code, or find another way to host the site.

**From my `package.json` file:**
```
"dependencies": {
  "@fortawesome/fontawesome": "^1.1.8",
  "@fortawesome/free-brands-svg-icons": "^5.1.0",
  "@fortawesome/pro-light-svg-icons": "^5.1.0",
  "@fortawesome/pro-regular-svg-icons": "^5.1.0",
  "@fortawesome/vue-fontawesome": "^0.1.0",
...
},
```

**Comment by bloqhead** [comment]
**Update for those still having trouble:** https://cl.ly/spXJ

**Comment by robinvdvleuten** [comment]
@bloqhead yeah I was aware of that, but you'll run into other unfortunate issues like missing env vars while building the container 😔

**Comment by bloqhead** [comment]
@bswank I wish there was one. I ended up going back to the free version for now until something changes.

**Comment by TooTallNate** [comment]
Just wanted to chime in real quick and say that with the ["Build Env" vars feature that was announced earlier today](https://zeit.co/blog/build-env), it's now possible to set up private 3rd party npm registries in your Dockerfile by utilizing Now Secrets (this is a lot more secure as well).

We're working on getting specific examples for @fontawesome set up as well.

**Comment by abusada** [comment]
[This](https://github.com/zeit/now-build-env-starter-dynamic) worked for me

**Comment by benbonnet** [comment]
@leo a bit unfamiliar with private repos yet; would you mind linking to the specific part of the docs that explains how to declare a private registry in now 2.0?
