### ISSUE TITLE
Unable to renew certificate

### ISSUE THREAD

**Issue by laurendorman** [vercel/vercel#1347]
I received an email from ZEIT Now stating "Automatic certificate renewal failed for `laurendorman.io`".

I attempted to fix this manually with `now-cli`, but with no success.

In my first attempt, I tried to `add` a certificate to the domain:
```
$ now certs add laurendorman.io www.laurendorman.io
> Error! Too many certificates already issued for exact set of domains: laurendorman.io, www.laurendorman.io
```

And finally, with an attempt to alias the domain:
```
$ now alias out-zopinwheru.now.sh laurendorman.io
> Assigning alias laurendorman.io to deployment out-zopinwheru.now.sh
> Error! Too many certificates already issued for exact set of domains: laurendorman.io, *.laurendorman.io
```

It is important to note that I am also aliasing `www.laurendorman.io` – which may be a part of the issue (wildcard cert perhaps?). It is failing for both.

Unfortunately, this means that my site is down. 😞

**Comment by javivelasco** [comment]
Hi @laurendorman, the email you received is coming from the automatic certificate renewal. It looks like the certificates were generated correctly but we didn't store them and request them again until the point we got rate limited by let's encrypt. I will look further but it's possible that we have to wait until the rate limit is gone :(

Sorry about it, I'm working on it

**Comment by laurendorman** [comment]
@javivelasco, thanks for taking a look. 🙂

Any updates here? I've updated to the latest version of `now-cli`, but still no luck. Site is still down. 😞

Is there any way to disable TLS temporarily from within the Now dashboard or the `now-cli`? I am not processing any forms or handling sensitive data, so I would be OK with disabling it as a temporary solution.

**Comment by javivelasco** [comment]
Are you still getting the same error? After a few days the LE error should be gone. Please try to create the certificate by aliasing and let's see what happens.

**Comment by laurendorman** [comment]
@javivelasco, still no luck. Seeing two different errors here.

```
$ now alias out-zopinwheru.now.sh laurendorman.io
> Assigning alias laurendorman.io to deployment out-zopinwheru.now.sh
> Error! An unexpected error occurred in alias: TypeError: Cannot read property 'includes' of null
    at getCertRequestSettings (/snapshot/repo/dist/now.js:3472:19)
    at createCertificateForAlias (/snapshot/repo/dist/now.js:3394:7)
    at createAlias (/snapshot/repo/dist/now.js:5672:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

and:
```
$ now alias out-zopinwheru.now.sh www.laurendorman.io
> Assigning alias www.laurendorman.io to deployment out-zopinwheru.now.sh
> Error! There is a validation in course for undefined. Wait until it finishes.
```

**Comment by laurendorman** [comment]
@javivelasco, I've also tried removing the domain and adding it back... I am running out of ideas here. 😬

**Comment by javivelasco** [comment]
@laurendorman Sorry about the delay! The rate limit should be gone now but it looks like your domain is misconfigured. Please reach me out in Slack to figure it out!

**Comment by laurendorman** [comment]
Turns out there I had a faulty DNS record that caused the error. I am surprised it worked the first time around. 😝 

Thanks for your help, @javivelasco!
