### ISSUE TITLE
Cannot verify and add external domain via TXT record.

### ISSUE THREAD

**Issue by joonhocho** [vercel/vercel#1355]
I added and removed external domain and trying to re-add it again.
It worked fine the first time, but now as I am trying to re add it, it fails to verify TXT record, even though TXT record is set correctly.
I have verified TXT record multiple times via `dig` and other online tools.
Is there some kind of local cache that is blocking this verification?

```
dig _now.mydomain.com TXT +short
> "033..."
```

**Comment by OlliV** [comment]
There is a slight delay on that but it should work usually in few minutes. One thing to note is that the token for authorization is tied to the `now-cli` auth token. So you have to use the same auth token both times. Do you see the same token in the error message that you can see with `dig`?

**Comment by joonhocho** [comment]
@javivelasco I fixed it, but I had to do it another way. I forgot how I fixed it, though.

**Comment by joonhocho** [comment]
@javivelasco Oh I remember now. I had to use another computer to get it working. I think there is some local cache issue with Now client.

**Comment by javivelasco** [comment]
Great! Thanks @joonhocho

**Comment by joonhocho** [comment]
@javivelasco This still is a bug, though. It should provide a way to clear cache other than using another computer.

**Comment by javivelasco** [comment]
Not really, that's unrelated to `now-cli`, we are not caching anything :)

**Comment by joonhocho** [comment]
@javivelasco hmm. I still don't get how it doesn't works on one computer and works on another. It seems like a bug with the client to me.

**Comment by javivelasco** [comment]
Because your computer caches the DNS but it's not the CLI itself :)

**Comment by joonhocho** [comment]
@javivelasco If that is the case, maybe it's worth explaining it in the document somewhere. Because, some people like me will have similar issue, waste hours, and probably think it's a problem with Now client. I don't think you want your customers turn around because they may think your product is buggy. Just my thoughts. Thanks!
