### ISSUE TITLE
--local-config does not fail if config is not found

### ISSUE THREAD

**Issue by fregante** [vercel/vercel#1356]
```
now -v
11.1.12
```

`now --local-config=not-found.json` should fail, but it just completely ignores the configuration and goes on without it.

This causes incorrect deployments or just unrelated errors... until you figure out that the configuration isn't picked up.

**Comment by leo** [comment]
Agreed. We should definitely fail if it doesn't exist. **But only if a custom path was specified!**

**Comment by Ethan-Arrowood** [comment]
Fixed! 🎊
