### ISSUE TITLE
now alias not working in 11.1.12

### ISSUE THREAD

**Issue by nifte** [vercel/vercel#1359]
**Now CLI version:** 11.1.12
**Command:** now alias \<deployment> \<domain>
**Error:**
```
> Error! An unexpected error occurred in alias: TypeError: Cannot read property 'includes' of null
    at getCertRequestSettings (C:\snapshot\repo\dist\now.js:3472:19)
    at createCertificateForAlias (C:\snapshot\repo\dist\now.js:3394:7)
    at createAlias (C:\snapshot\repo\dist\now.js:5672:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by shahruz** [comment]
Same here.

**Comment by Dashue** [comment]
Another one here

**Comment by mscoutermarsh** [comment]
For others running into this.

I downgraded and it's working.

`npm install -g now@11.1.11`

**Comment by brandondurham** [comment]
Same story here. Downgrading worked. Thank you, @mscoutermarsh.

**Comment by Dashue** [comment]
I jumped on the canary channel (using now desktop), and that solved it for me.

**Comment by nifte** [comment]
Looks like its still broken on the CLI canary channel. I'll try the desktop one.

**Comment by jonscottclark** [comment]
Thanks @mscoutermarsh

**Comment by javivelasco** [comment]
Fixed in the latest canary
