### ISSUE TITLE
Redeploying with --public requires --force

### ISSUE THREAD

**Issue by taravancil** [vercel/vercel#136]
If you're a premium user and deploy an app normally, then decide to redeploy with the `--public` option without changing any files, `--force` is required to trigger a new deploy.

**Comment by taravancil** [comment]
I'll work on this in a bit

**Comment by taravancil** [comment]
Oh, wait. If I'm understanding this correctly, I can't fix this. It's up to you all to determine how [data `POST`ed to `/now/create`](https://github.com/zeit/now/blob/6d83be5f25507701fec8f345af9051d194284e69/lib/index.js#L125) is handled, and whether or not it will trigger a new deployment.

**Comment by OlliV** [comment]
Sounds about correct. I suppose it would make sense to have implicit `--force` in this case.
