### ISSUE TITLE
Environment variable NOW_URL isn't set in windows

### ISSUE THREAD

**Issue by jessehouwing** [vercel/vercel#1360]
I've tried to use the NOW_URL variable after running now on windows, but the variable remains empty :(

```
C:\temp\tmp>set NOW_URL
Environment variable NOW_URL not defined

C:\temp\tmp>now
> Deploying C:\temp\tmp under jhouwing@xpirit.com
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
> https://tmp-asdadsasdasd.now.sh [in clipboard] [7s]
> Deployment complete!

C:\temp\tmp>
C:\temp\tmp>set NOW_URL
Environment variable NOW_URL not defined

C:\temp\tmp>set NOW
Environment variable NOW not defined
```

**Comment by jessehouwing** [comment]
"expose these environment variables" to me feels like exposes them to the caller. The rest of the docs seem to talk about passing variables INTO now, this section read to me like passing values BACK to the caller (2 other colleagues included).

I'm trying to read the URL in a CI environment to pass it on as an output variable, access to the actual url is pretty handy. Reading it from the clipboard isn't an option.

**Comment by sergiodxa** [comment]
> I'm trying to read the URL in a CI environment to pass it on as an output variable, access to the actual url is pretty handy. Reading it from the clipboard isn't an option.

@jessehouwing when you are using Now in a CI environment the result is the URL so you can:
1. Directly save the result as env variable.
2. Pipe the result to another bash script
3. Use something like `echo $(now)` to pass the URL to another bash script

**Comment by jessehouwing** [comment]
I tried that in VSTS and can't get it working. How does it detect that it's
in a ci environment?

**Comment by leo** [comment]
Closing this issue now, as the environment variable is only meant to be used within a deployment.
