### ISSUE TITLE
Deployment problem

### ISSUE THREAD

**Issue by emek** [vercel/vercel#1362]
Hello everyone, I have a problem about to deploy my project to now.sh.

`(master)⚡ ∆ now --force
> Deploying ~/Desktop/deployment-biDamla-API/biDamla-API under emekturkeli@gmail.com
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
> Using Node.js 8.11.1 (default)
> https://bi-damla-api-snrbvwwrng.now.sh [in clipboard] (bru1) [7s]
> Building…
> ▲ npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 45 main dependencies…
> ✓ Installed 1206 modules [12s]
> ▲ Snapshotting deployment
> ▲ Saving deployment image (95.0M)
> Build completed
> Verifying instantiation in bru1
> [0]
> [0] bi-damla-api@0.0.0 start /home/nowuser/src
> [0] micro
> [0]
> [0] micro: Error when importing /home/nowuser/src/src: MissingEnvVarsError: The following variables are defined in /home/nowuser/src/.env.example but are not defined in the environment: SENDGRID_KEY, MASTER_KEY, JWT_SECRET.
> [0] Make sure to add them to /home/nowuser/src/.env or directly to the environment.
> [0] If you expect any of these missing variables to be empty, you can use the allowEmptyValues option:
> [0]
> [0] require('dotenv-safe').load({
> [0]   allowEmptyValues: true
> [0] });
> [0] Also, the following error was thrown when trying to read variables from /home/nowuser/src/.env: ENOENT: no such file or directory, open '/home/nowuser/src/.env'
> [0]     at Object.config (/home/nowuser/src/node_modules/dotenv-safe/index.js:37:19)
> [0]     at Object.<anonymous> (/home/nowuser/src/src/config.js:15:10)
> [0]     at Module._compile (module.js:652:30)
> [0]     at loader (/home/nowuser/src/node_modules/babel-register/lib/node.js:144:5)
> [0]     at Object.require.extensions.(anonymous function) [as .js] (/home/nowuser/src/node_modules/babel-register/lib/node.js:154:7)
> [0]     at Module.load (module.js:565:32)
> [0]     at tryModuleLoad (module.js:505:12)
> [0]     at Function.Module._load (module.js:497:3)
> [0]     at Module.require (module.js:596:17)
> [0]     at require (internal/module.js:11:18)
> [0] micro: https://err.sh/micro/invalid-entry
> [0] npm ERR! code ELIFECYCLE
> [0] npm ERR! errno 1
> [0] npm ERR! bi-damla-api@0.0.0 start: `micro`
> [0] npm ERR! Exit status 1
> [0] npm ERR!
> [0] npm ERR! Failed at the bi-damla-api@0.0.0 start script.
> [0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [0]
> [0] npm ERR! A complete log of this run can be found in:
> [0] npm ERR!     /home/nowuser/.npm/_logs/2018-05-19T16_50_43_089Z-debug.log
> [0] More details: https://err.sh/now-cli/no-open-port-found
> [0] micro: Error when importing /home/nowuser/src/src: MissingEnvVarsError: The following variables are defined in /home/nowuser/src/.env.example but are not defined in the environment: SENDGRID_KEY, MASTER_KEY, JWT_SECRET.
> [0] Make sure to add them to /home/nowuser/src/.env or directly to the environment.
> [0] If you expect any of these missing variables to be empty, you can use the allowEmptyValues option:
> [0]
> [0] require('dotenv-safe').load({
> [0]   allowEmptyValues: true
> [0] });
> [0] Also, the following error was thrown when trying to read variables from /home/nowuser/src/.env: ENOENT: no such file or directory, open '/home/nowuser/src/.env'
> [0]     at Object.config (/home/nowuser/src/node_modules/dotenv-safe/index.js:37:19)
> [0]     at Object.<anonymous> (/home/nowuser/src/src/config.js:15:10)
> [0]     at Module._compile (module.js:652:30)
> [0]     at loader (/home/nowuser/src/node_modules/babel-register/lib/node.js:144:5)
> [0]     at Object.require.extensions.(anonymous function) [as .js] (/home/nowuser/src/node_modules/babel-register/lib/node.js:154:7)
> [0]     at Module.load (module.js:565:32)
> [0]     at tryModuleLoad (module.js:505:12)
> [0]     at Function.Module._load (module.js:497:3)
> [0]     at Module.require (module.js:596:17)
> [0]     at require (internal/module.js:11:18)
> [0] micro: https://err.sh/micro/invalid-entry
> [0] npm ERR! code ELIFECYCLE
> [0] npm ERR! errno 1
> [0] npm ERR! bi-damla-api@0.0.0 start: `micro`
> [0] npm ERR! Exit status 1
> [0] npm ERR!
> [0] npm ERR! Failed at the bi-damla-api@0.0.0 start script.
> [0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [0]
> [0] npm ERR! A complete log of this run can be found in:
> [0] npm ERR!     /home/nowuser/.npm/_logs/2018-05-19T16_51_53_128Z-debug.log
> [0] More details: https://err.sh/now-cli/no-open-port-found
> [0]
> [0] bi-damla-api@0.0.0 start /home/nowuser/src
> [0] micro
> [0]
> [0] micro: Error when importing /home/nowuser/src/src: MissingEnvVarsError: The following variables are defined in /home/nowuser/src/.env.example but are not defined in the environment: SENDGRID_KEY, MASTER_KEY, JWT_SECRET.
> [0] Make sure to add them to /home/nowuser/src/.env or directly to the environment.
> [0] If you expect any of these missing variables to be empty, you can use the allowEmptyValues option:
> [0]
> [0] require('dotenv-safe').load({
> [0]   allowEmptyValues: true
> [0] });
> [0] Also, the following error was thrown when trying to read variables from /home/nowuser/src/.env: ENOENT: no such file or directory, open '/home/nowuser/src/.env'
> [0]     at Object.config (/home/nowuser/src/node_modules/dotenv-safe/index.js:37:19)
> [0]     at Object.<anonymous> (/home/nowuser/src/src/config.js:15:10)
> [0]     at Module._compile (module.js:652:30)
> [0]     at loader (/home/nowuser/src/node_modules/babel-register/lib/node.js:144:5)
> [0]     at Object.require.extensions.(anonymous function) [as .js] (/home/nowuser/src/node_modules/babel-register/lib/node.js:154:7)
> [0]     at Module.load (module.js:565:32)
> [0]     at tryModuleLoad (module.js:505:12)
> [0]     at Function.Module._load (module.js:497:3)
> [0]     at Module.require (module.js:596:17)
> [0]     at require (internal/module.js:11:18)
> [0] micro: https://err.sh/micro/invalid-entry
> [0] npm ERR! code ELIFECYCLE
> [0] npm ERR! errno 1
> [0] npm ERR! bi-damla-api@0.0.0 start: `micro`
> [0] npm ERR! Exit status 1
> [0] npm ERR!
> [0] npm ERR! Failed at the bi-damla-api@0.0.0 start script.
> [0] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [0]
> [0] npm ERR! A complete log of this run can be found in:
> [0] npm ERR!     /home/nowuser/.npm/_logs/2018-05-19T16_53_07_681Z-debug.log
> Error! Instance verification timed out (3m)
> Read more: https://err.sh/now-cli/verification-timeout`

Is there anybody to know that how to solve this problem?

Thank you.

**Comment by Dashue** [comment]
Doesn't look like a 'now' issue. It's clearly telling you 
[0] micro: Error when importing /home/nowuser/src/src: MissingEnvVarsError: The following variables are defined in /home/nowuser/src/.env.example but are not defined in the environment: SENDGRID_KEY, MASTER_KEY, JWT_SECRET.
[0] Make sure to add them to /home/nowuser/src/.env or directly to the environment.

That you have an .env.example file but are missing a .env file?
If you intend to use SENDGRID_KEY, MASTER_KEY, JWT_SECRET env variables, either add them to .env file or to the environment. Otherwise remove the .env.example file.

**Comment by emek** [comment]
Tried to remove .env and .env.example file but it did not work :(

**Comment by dariye** [comment]
hey @emek I would recommend putting a [`now.json`](https://github.com/pauldariye/greenhouse-proxy-server/blob/master/now.json) in the project root directory. Check out that example.

**Comment by javivelasco** [comment]
I'm closing this since it looks like it's not a now issue
