### ISSUE TITLE
Improved instance verification

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#1363]
Algorithm:

- Decide if the deployment is Now Cloud 2.0 enabled
  - No
     - fall back to current verification mechanism
  - Yes
     - enumerate the list of DCs it's enabled in based on the `POST` creation response
     - generate concurrent `HEAD` requests to each `alias-$dcId.zeit.co` with `Host: $deploymentUrl` and the `X-Now-Shallow: 1` headers
       - For example, if `sfo1` was enabled, perform `HEAD https://alias-sfo1.zeit.co`
     - consider the response valid only if `X-Now-Shallow` header is in the response
     - if the request is successful and responds with `204`, consider the DC verified
     - if the request is unsuccessful (network error or non-204), retry up to 3 times

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
