### ISSUE TITLE
Include file in deployment I wouldn't want to publish to npm

### ISSUE THREAD

**Issue by jacobmischka** [vercel/vercel#137]
In my project I have a `.env.json` file with some config values. Because it includes some objects and arrays, I can't easily use env vars instead.

If I were to publish my project to npm, I wouldn't want to include this file, but I do need to include it in a deployment.

It would be great if there were a way to do this, maybe a `.nowignore` file that takes precedence, as an initial idea.

Thanks for everything you guys do! Seems like everything coming out of Zeit is gold.

**Comment by danprince** [comment]
Can't find any documentation on this and the only workaround I've got working is to remove `.env` from my .gitignore before deploying, then re-adding afterwards.

Looks like there are some kinds of rules for specifying files and ignoring special files, but can't see any docs on those either. https://github.com/zeit/now/pull/128 https://github.com/zeit/now/issues/127

Second the motion for a `.nowignore` file :+1:

**Comment by leo** [comment]
`now.files` in package.json!

**Comment by danprince** [comment]
Thanks @leo. Any examples of how you're supposed to use `now.files`? Is it a blacklist, or a whitelist? Does it override `.gitignore` etc?

I'm glad that there's a solution, but the discoverability for these features is pretty much zero. Without stumbling across this thread, how are folks supposed to find out about this option?

**Comment by leo** [comment]
Like `files` in package.json (for npm), it allows you to include files that you want to deploy. Yes, it should override it.

**Comment by jacobmischka** [comment]
Is `now.files` a new addition? when I asked about this a couple weeks ago in the slack channel I was told that there was no way to do it.

Either way, this is exactly what I was looking for, thanks!

**Comment by leo** [comment]
@jacobmischka It's not documented yet. 😊

**Comment by jimthedev** [comment]
@leo I am on 0.34.0 and don't think now.files is actually working. I am adding files and directories to mine and now when I run `now -d` it simply filters the files that it says it is ignoring to just those files. I am guessing it is a bug in get-files but I haven't found it yet.

**Comment by tvedtorama** [comment]
@leo I am having no luck with this either.  I tried:

```
  "now.files": [
    "./build/utils/**/*.js",
    "./utils/**/*.ts"
  ],
```

And something like

```
  "now.files": [
    "build/utils",
    "utils"
  ],
```

But these files are ignored whatsoever.  I did deploy once before adding these settings and when I deploy again, using `now -d` I don't see any files being uploaded - and only bad stuffs happen when now tries to run my app.
