### ISSUE TITLE
EACESS: permission denied, when attempting to open file for writing in the /tmp/ folder

### ISSUE THREAD

**Issue by bjornlll** [vercel/vercel#1370]
During the build process I cache a number of JSONL objects in a folder `/home/nowuser/src/nedb-cache/` that I then copy over to `/tmp/` as and when they are requested by the user. For some reason, when I attempt to open the file, I get an EACESS error.

Has anyone of you encountered this before? If it helps, I am using `nedb` as a read-only database in my node app. 

```
05/24 06:47 PM (4m)
[db] Copied collection from /home/nowuser/src/nedb-cache/meta.nedb to /tmp/meta.nedb
05/24 06:47 PM (4m)
[db] Loaded collection from /tmp/meta.nedb
05/24 06:47 PM (4m)
[Terminating] Exit code: 1
05/24 06:47 PM (4m)
Error: EACCES: permission denied, open '/tmp/meta.nedb'
```

**Comment by bjornlll** [comment]
Also, I should mention: The account I am currently using is on the free tier. Could it be the 1 mb limit that's causing me trouble?

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), this is not happening anymore, as we don't support Docker anymore.

Please consider uploading your application using the new format specified in the blog post, that will definitely get rid of your problem! 😊
