### ISSUE TITLE
Installed now cli for first time, but no CLI window

### ISSUE THREAD

**Issue by edcarstens** [vercel/vercel#1376]
I have the little triangle icon in my tray. When I click it, a status window pops up in the corner. There is no command line anywhere.

**Comment by pranaygp** [comment]
The `now` [desktop application](https://github.com/zeit/now-desktop) doesn't trigger a new now CLI when clicked. It's supposed to provide you a GUI version of much of the functionality that the CLI provides you.

In addition, the desktop app also keeps the CLI version updated. To actually use the `now-cli`, you should be able to run `now` in a new terminal window.

**Comment by leo** [comment]
Thank you for answering, @pranaygp!
