### ISSUE TITLE
Now scale 1 1 is taking two instance

### ISSUE THREAD

**Issue by rodmansw** [vercel/vercel#1377]
![now-scale](https://user-images.githubusercontent.com/23584702/40632965-2f876fa0-62ba-11e8-87e8-f7c8f883cc02.png)

**Comment by sergiodxa** [comment]
That's expected, you are scaling to min 1 max 1 instances in bru1 and sfo1 datacenters, that is 2 instances.

If you only want to scale one DC use `now scale <url> sfo1 1 1` or `now scale <url> bru1 1 1`

**Comment by HamadaFMahdi** [comment]
Thanks for your help!

I had 1 instance in sfo1 and 1 in bru1. After running `now scale <url> bru1 1 1`,  it didn't change anything. To have only 1 instance running in bru1 I had to do `now scale <url> sfo1 0 0`.

Just in case anyone else had a similar issue.
