### ISSUE TITLE
Update Basic Auth documentation

### ISSUE THREAD

**Issue by davepenfold** [vercel/vercel#1383]
https://zeit.co/docs/other/faq#how-can-i-setup-basic-http-authentication-for-my-deployment

`serve` 7.0.0+ has had `--auth` flag removed, update documentation or provide alternate instructions for adding basic auth to deployments.

**Comment by sergiodxa** [comment]
@davepenfold please create an issue on [zeit/docs](https://github.com/zeit/docs) or if you want a PR updating the docs 😉
