### ISSUE TITLE
Static SPA deployment with no package.json?

### ISSUE THREAD

**Issue by good-idea** [vercel/vercel#1388]
Is it possible to make a static deployment that uses `--single`?

I know that [this post](https://zeit.co/blog/now-static) recommends having a `build` and `start` command in package.json.

What I'm trying to deploy is already bundled, so it doesn't need a build script. But, I still need to create a basic package.json so I can have it `serve --single`.

Is there a way to do this without a package.json?

**Comment by leo** [comment]
Coming very soon! 🤫Please monitor our [Twitter account](https://twitter.com/zeithq).
