### ISSUE TITLE
serve.json how to

### ISSUE THREAD

**Issue by rootedsoftware** [vercel/vercel#1390]
I'm not clear on how I can use the serve `serve.json` file and deploy using `now`. I have a build directory and the `serve.json` file is in that directory. If I use serve locally the headers specified in the `serve.json` file are present on the files being served. If I deploy to `now` using the same build folder those headers aren't present. 

Here is what I have in my package.json file

```
    "build": "parcel build ./public/index.html -d ./build",
    "now-start": "serve --single ./build",
    "now-deploy": "now",
```

**Comment by leo** [comment]
@c316 Did you deploy the `build` directory by any chance? Because what you need to do is deploy the directory that contains the `package.json` file you've shown above.

**Comment by rootedsoftware** [comment]
@leo I deploy using `npm run now-deploy` from the directory that contains both the package.json file and serve.json file

**Comment by leo** [comment]
@c316 Okay. And `serve.json` is inside of `./build` and you're using `serve@7.2.0`?

**Comment by rootedsoftware** [comment]
@leo yes and yes. I have serve installed globally and in the package.json file at `^7.2.0`

Also, I just did another deployment if you need to look at the logs 

https://zeit.co/joshb/coffee/cowrnxptnz

**Comment by sergiodxa** [comment]
@c316 you need to have the following file structure:

```
./build
./serve.json
./package.json
```

if your `./serve.json` is in `./build` and you deploy `./` then `serve` will not read it. Also have serve as a dependency in package.json.

**Comment by rootedsoftware** [comment]
Ok, so I'm not clear on what is happening when I run `npm run now-deploy`. Here is what I think happens

I run `npm run now-deploy`
now run the `build` script from the `package.json` file, `parcel build ./public/index.html -d ./build` parcel builds the application and it doesn't do anything with the `serve.json` file. 
Once that finishes now runs the `now-start` command, `serve --single ./build`. 

I'm not sure where in this process now is aware of the `serve.json` file and know it should be uploaded and used. I'm not seeing that file listed when now does its upload.

**Comment by rootedsoftware** [comment]
Still no luck with the the serve headers loading. Any help would be appreciated.

**Comment by sergiodxa** [comment]
@c316 could you create a repo to replicate it? that way it will be easier to check what is wrong

**Comment by rootedsoftware** [comment]
@sergiodxa I've added a test repo here

https://github.com/c316/test-serve

I deploy this to now using the `npm run now-deploy` command

**Comment by leo** [comment]
@c316 Thank you for providing the example.

The problem is that you actually added `serve.json` in the root directory. However, you are running `serve --single ./build` which means that `serve.json` should be inside `./build`.

But in general, you don't need to use `serve` on Now, just do it [like this](https://zeit.co/blog/new-static-deployments).

**Comment by rootedsoftware** [comment]
@leo ok, I read that article and it isn't clear to me how I can remove serve. What command should be listed in my package.json in place of the `"now-start": "serve --single ./build",` line? I have to have a start or now-start line in package.json, but I'm not sure what should be started if I don't need to use serve any longer...
