### ISSUE TITLE
Auto-alias on deployment

### ISSUE THREAD

**Issue by hiddentao** [vercel/vercel#1391]
I have two branches in my repo - `dev` and `master` - the instance deployed from each branch has a branch-specific subdomain, thus:

* `dev` = `sync-dev.mydomain.com`
* `master` = `sync.mydomain.com`

The problem I have with the `now alias` command as it stands is that, unless I manually specify the now.sh URL to alias, it just uses the latest deployed instance. But sometimes my CI builds are running simultaneously, meaning that the dev branch alias gets applied to the master branch instance and vice versa. 

I could use text extraction techniques to extract the deployed instance URL from the `now` command output and then feed that to the `alias` command, but I'm wondering if it would be possible to have an `--alias` flag added instead that would instruct `now` to alias the deployed instance once it was setup. This would ensure the right instance gets aliased, and also saves on the extra command call. So something like:

```
now ---team ... --token ... --alias sync-dev.mydomain.com
```

The flag would require you to specify the alias domain name and/or you would have the alias specified in the `now` config already.

_Note: I've noticed that there used to be an `--alias` flag that has now been replaced by the `alias` command. So in a way I'm asking for its re-introduction as a shortcut alternative to calling `alias` separately_

**Comment by sergiodxa** [comment]
You can currently do that. Check ["How Do I Deploy and Alias in a Single Command?"](https://zeit.co/docs/other/faq#how-do-i-deploy-and-alias-in-a-single-command) in our FAQ.

Also since you have two possible aliases you will need two now.json files.

```json
// now.json
{
  "name": "sync",
  "alias": "sync.mydomain.com"
}
```
```json
// now.dev.json
{
  "name": "sync",
  "alias": "sync-dev.mydomain.com"
}
```

Something like that, then you can run the following command to deploy and alias to dev:

```shell
now && now alias -A ./now.dev.json
```

That will deploy (`now`) and then alias (`now alias`) the latest deployment, it will also use the `./now.dev.json` file for the configuration (`-A` or `--local-config`) from where it will read the expected alias.

For deploy and alias to production use:

```shell
now && now alias
```

In this case you don't need to use `-A` since Now will automatically use the `now.json` file which is your production command.

> You may prefer to use now.json for dev and now.prod.json for production in order to avoid possible mistakes when running `now && now alias`.

Another option is to remove use `now && now alias sync.mydomain.com` or `now && now alias sync-dev.mydomain.com` when deploying (you still need a now.json with at least the name key).

**Comment by hiddentao** [comment]
@sergiodxa Thanks for the suggestion. In fact, this is actually how I currently have it setup. Yet I somehow managed to end up in the situation described in my original post, wherein the dev instance's alias got applied to the production instance. And I'm pretty sure this was due to the possible (though unlikely) race condition since you're still having to run `now alias` _after_ the deployment command and it assumes the latest instance to be the right one to alias.

**Comment by ChrisTalman** [comment]
Does this work with Now 2.0?

**Comment by sergiodxa** [comment]
@hiddentao you could pipe the final URL to the alias like this:
```bash
now alias $(now) sync.mydomain.com
```
This will pipe send the result of `now` which will be the deployment URL to the alias command and solve the race condition.

@ChrisTalman AFAIK this didn't changed

**Comment by hiddentao** [comment]
@sergiodxa Thanks!

**Comment by jaydenseric** [comment]
@sergiodxa how do you do that when the alias hostname is in a `-A` local config file?

```json
{
  "deploy": "now -A $NOW_CONFIG_PATH alias $(now -A $NOW_CONFIG_PATH) && now rm enamor-app -s",
  "deploy:development": "NOW_CONFIG_PATH=now.development.json npm run deploy",
  "deploy:production": "NOW_CONFIG_PATH=now.production.json npm run deploy"
}
```

With `npm run deploy:development` results in:

```
Success! Deployment ready
> Assigning alias enamor-app-geghhymdum.now.sh to deployment enamor-app-geghhymdum.now.sh
> Error! The alias enamor-app-geghhymdum.now.sh is a deployment URL or it's in use by a different team.
```

**Comment by sergiodxa** [comment]
As far as I remember if you pass the deployment URL you need to manually pass the alias too or it's going to use the deployment URL as the alias and the latest deployment as deployment URL.

So you need to always pass both, deployment and alias, instead of relying on the alias key of the now.json

**Comment by YashKumarVerma** [comment]
> now alias $(now) sync.mydomain.com

how do i use it along a `--token`

**Comment by YashKumarVerma** [comment]
@sergiodxa 

Gave this error
```
> Success! Deployment ready [34s]
> Error! An unexpected error occurred in alias: Error: An unexpected error occurred while trying to fetch your personal details: invalid json response body at https://api.zeit.co/www/user reason: Unexpected token A in JSON at position 0
    at e.exports (/snapshot/repo/dist/now.js:9:96127)
    at process._tickCallback (internal/process/next_tick.js:68:7)
The command "now alias $(now --token ${token}) labyrinth-bot --token ${token}" exited with 1
```

**Comment by renatorib** [comment]
+1 for `--alias` flag shortcut

**Comment by TooTallNate** [comment]
Closing this since we have introduced [implicit automatic aliasing](https://zeit.co/blog/automatic-aliasing).

**Comment by tedmiston** [comment]
@TooTallNate Has this changed again?

There is no mention in the docs you linked of "implicit automatic aliasing" or anything like the ability to auto alias separate Dev, Prod, etc deployments.
