### ISSUE TITLE
Improve information about instance usage

### ISSUE THREAD

**Issue by lorensr** [vercel/vercel#1393]
```
$ now scale mydomain.com all 1 auto
> Fetched deployment "mydomain-yxozomuvye.now.sh" [452ms]
> Error! You can't scale to more than 10 max instances with your current plan.
```

1. Say how many instances a scale command requires. In this case, I think it's 2? (Minimum of one in each of 2 datacenters)
2. Say how many instances I'm using
3. Provide a better way to see which deployments are using instances. When I do `now ls`, I see the number of instances used by each most-recent deployment for each app. But I don't see a total for all deployments of an app—I would have to `now ls -a appname` and sum in my head, and repeat for all apps. And I have over 10 apps.

Also, I think there might be a bug in the scale command—I don't think I'm using more than 8 instances. I only see 4 in the top-level `now ls`.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
