### ISSUE TITLE
User friendly now.json schema errors

### ISSUE THREAD

**Issue by sergiodxa** [vercel/vercel#1402]
When trying to deploy with a now.json containing extraneous keys the error is not clear nor user friendly.

**now.json with a random key**
```json
{
  "RANDOM_KEY": "value"
}
```

**CLI Error**
```bash
> Error! An unexpected error occurred!
  Error: You have the following errors inside `now.json` [{"keyword":"additionalProperties","dataPath":"","schemaPath":"#/additionalProperties","params":{"additionalProperty":"RANDOM_KEY"},"message":"should NOT have additional properties"}]
```

This error should be handled and displayed in a simpler way.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
