### ISSUE TITLE
now-cli not uploading tsconfig.json

### ISSUE THREAD

**Issue by shrugs** [vercel/vercel#1403]
Hi! I have a pretty basic typescript project https://github.com/XLNT/at-p which uses micro and now.

It was previously not build my typescript (using the `npm` deployment type) because when it ran `npm run build` the `tsc` command just output its help information (which is what happens if there's no `tsconfig.json` file in the current folder.

This was fixed in this commit: https://github.com/XLNT/at-p/commit/89a676b933db1506405a2ba47257e07624915ec3#diff-96c813af76efae3c872399365c060e54 by adding the `files` key in `now.json` to directly whitelist `src` and `tsconfig.json`

It now builds correctly. My tsconfig.json is not included in gitignore, so https://github.com/zeit/now-cli/issues/1129 isn't the same issue.

I'm hoping that I can remove the `files` key in `now.json` in the future, since I wouldn't expect it to be necessary.

**Comment by shigurenimo** [comment]
I have the same problem.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
