### ISSUE TITLE
Ambiguous error on Aliasing 

### ISSUE THREAD

**Issue by l3wi** [vercel/vercel#1405]
<img width="649" alt="screen shot 2018-06-12 at 7 49 11 pm" src="https://user-images.githubusercontent.com/1716917/41348509-667208a4-6f3f-11e8-85ca-8a69c7f250f0.png">

## What you expect:
Given I was using 38/50 deploys, I am able to create new deployments and alias them. I would expect that I could alias this specific deployment. 

## What was happening:
The alias scaling settings were set to `min 1 max 10` on both zones. So when I try to alias: 38 + 20 = 58 and it throws the error. 

## Suggested solution
The repsonse doesn't explain the issue and it looks like there is an error in the CLI. 

A better explanation of the error and/or the inclusion of the deployments you are trying to reserve would clear thing up.

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), there are no instances anymore. In turn, this problem will not pop up again! 🙏
