### ISSUE TITLE
Document `now inspect`

### ISSUE THREAD

**Issue by Rowno** [vercel/vercel#1408]
I couldn't find `now inspect` documented anywhere, the only way I found out about it was from an error message. 🤦‍♂️ 

![image](https://user-images.githubusercontent.com/605501/41503931-0887309a-7195-11e8-9b40-388767fd8537.png)

**Comment by lorensr** [comment]
Would be great to be listed under `now -h`

**Comment by DannyBen** [comment]
The fact that it is `now inspect` is not shown in `now help` seems like a bug to me, Help screen should show all the available commands.

**Comment by rauchg** [comment]
Massive oversight! Thanks @lorensr @DannyBen for pointing it out

**Comment by joecohens** [comment]
In case you missed it, we already list the `inspect` command on the help list. Thank you for the suggestion!
