### ISSUE TITLE
View current scale settings

### ISSUE THREAD

**Issue by lorensr** [vercel/vercel#1409]
It would be nice to be able to view scale settings, like `now info <url>` that said eg `all min:1 max:4`

**Comment by sergiodxa** [comment]
Hello @lorensr, this could be done using `now inspect <url>` command which give you scale config per DC and more information.

**Comment by lorensr** [comment]
@sergiodxa nice! can you add it to the command list?

![image](https://user-images.githubusercontent.com/251288/41504961-cf61bb64-71cb-11e8-9846-805334009fad.png)

**Comment by lorensr** [comment]
Issue opened: https://github.com/zeit/now-cli/issues/1408
