### ISSUE TITLE
I cannot uninstall now-cli through NPM. 

### ISSUE THREAD

**Issue by fromneo** [vercel/vercel#1411]
This issue isn't fixed. 
https://github.com/zeit/now-cli/issues/838.

<img width="439" alt="screen shot 2018-06-18 at 7 18 56 am" src="https://user-images.githubusercontent.com/10500747/41513041-e647c9ac-72c7-11e8-95a4-82e9990e99f1.png">

**Comment by jamo** [comment]
Can you share the output of `ls -l $(which -a now)`

**Comment by fromneo** [comment]
Solved this. Had to manually remove the now binary at `/usr/local/bin/`. It was installed along with Now desktop. Its not managed by npm and thus wasn't working with the npm command.
