### ISSUE TITLE
Nit: Error copying to clipboard -> next to url `[in clipboard]`

### ISSUE THREAD

**Issue by jamo** [vercel/vercel#1412]
If copying to clipboard fails we should not claim that it's copied to the clipboard 

> [debug] [2018-06-19T11:20:18.615Z] Error copying to clipboard: Error: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel
[2018-06-19 11:20:18] > https://xxxxxxxxxxxxx.now.sh [in clipboard] (sfo1) [3s]

**Comment by leo** [comment]
Fixed as of Now CLI 12.0.0!
