### ISSUE TITLE
now.json static subdirectory configuration that's ignored leads to 404

### ISSUE THREAD

**Issue by wolverian** [vercel/vercel#1417]
Given the following `now.json`:

~~~json
{
  "type": "static",
  "static": {
    "public": "out"
  }
}
~~~

and `.gitignore`:

~~~
out/
~~~

and running `now` in the root directory of the project:

**Expected:** After `now`, I can see the site at the deployment URL.

**Actual result:** The deployment URL is 404.

What happened is that `now` uploaded the current working directory _without_ `out/`, as it's ignored.

**Comment by wolverian** [comment]
Possible fixes:

- Refuse to deploy when `static.public` is ignored.
- Let `static.public` override `.gitignore`.

**Comment by leo** [comment]
@wolverian Sounds like a very good idea, thank you!

In the mean time, add this to your `now.json` file:

```
{
  "files": [
    "dist"
  ]
}
```

That will make the upload work again.

**Comment by marvinhuebner** [comment]
@leo i've added this to my `now.json`:
```json
{
  "files": [
    "dist"
  ]
}
```

But the `dist` folder is still ignored when I'm doing a deployment with `now --static`. 

`now --version`: 11.2.5

**Comment by leo** [comment]
As of Now CLI 12.0.0 (v2 pipeline, as described [here](https://zeit.co/blog/now-2)), we don't support this property anymore. Closing! 😊
