### ISSUE TITLE
Environment variables lost after crash restart

### ISSUE THREAD

**Issue by pqvst** [vercel/vercel#142]
If a docker deployment crashes **with environment variables specified in the now command**  then those environment variables are lost after the restart.

    now --docker -d -f -e NODE_ENV=production

Test project:
https://github.com/pqvst/envtest/tree/master

**Comment by jamo** [comment]
This was fixed recently; there was a race condition which caused some deployments to fail as described in the issue above

Thanks for your error report and apologies for the long response time.
