### ISSUE TITLE
Fail on invalid scale settings

### ISSUE THREAD

**Issue by pranaygp** [vercel/vercel#1423]
if your `now.json` file has the following config:
```
...
"scale": {
  "sfo1": {
    "min": 2,
    "max": 1
  }
}
...
```

It should fail since that's an invalid configuration

**Comment by leo** [comment]
I wonder if we could do this calculation in [zeit/schemas](https://github.com/zeit/schemas)...

**Comment by antonmoiseev** [comment]
I submitted changes into [zeit/schemas](https://github.com/zeit/schemas) to address this issue, but it looks like this project doesn't utilize the schemas and imperatively validates provided configs.

What are your thoughts on this? Do you just want to add one more check to the current code or do you think it worths migrating to validation against the schemas?

JSON schemas could enable better now.json editing experience in editors like VS Code, WebStorm and Sublime Text:

#### VS Code
<img width="724" alt="now-json-schema-vscode" src="https://user-images.githubusercontent.com/182853/48113664-5468b780-e275-11e8-9641-b7577e5ac865.png">

#### WebStorm
<img width="798" alt="now-json-schema-ws" src="https://user-images.githubusercontent.com/182853/48113886-3a7ba480-e276-11e8-883a-8970e4738c2f.png">

**Comment by antonmoiseev** [comment]
No problem, that was my initial thought when I saw the announcement, however didn’t have a chance to take a look at the latest code. Absolutely love Now 2.0 👏
