### ISSUE TITLE
Incorrect link in Now GitHub message

### ISSUE THREAD

**Issue by seejamescode** [vercel/vercel#1424]
Example: https://github.com/seejamescode/test-devops-v3/pull/1#issuecomment-400415367

Link goes to: https://zeit.co/docs/features/github-integration?utm_source=automated&utm_medium=github&utm_campaign=now_bot

Should go to: https://zeit.co/docs/features/now-for-github?utm_source=automated&utm_medium=github&utm_campaign=now_bot

**Comment by pranaygp** [comment]
Thanks @seejamescode for that catch 🔍 

I'm creating an issue to track this bug internally on the correct repo so I'll be closing this

**Comment by seejamescode** [comment]
Hey @pranaygp, can we get a public repo for issues? There’s a lot of feedback I would love to give and track.
