### ISSUE TITLE
Scaling rules result in double the expected instances

### ISSUE THREAD

**Issue by JosephScript** [vercel/vercel#1426]
When I run `now scale <url> 1` I expect 2 instances (sfo1 and bru1). However every deployment shows 4 instances. The same also occurs with `now` when using the following scaling rules in the now.json:

```
{

  "scale": {
    "sfo1": {
      "min": 1,
      "max": 1
    },
    "bru1": {
      "min": 1,
      "max": 1
    }
  }
}
```

Local node v9.8.0
Now v3.9.0

**Comment by Zertz** [comment]
If I'm not mistaken, this is related to #1427

Have you tried running `now inspect [app]`?

**Comment by JosephScript** [comment]
Looks like the same issue. I ran inspect and it looks right. But the dashboard shows double.

**Comment by mtskf** [comment]
Exactly the same issue here :(

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
