### ISSUE TITLE
now domain add --external unfriendly looking error

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#1429]
a more friendly looking error would be nice.
currently, a js error is thrown

now domain add --external somedomain.com

> Are you sure you want to add "somedomain.com"? [y|N] 
> Error! Unknown error: Error: Verification required: Please add the following TXT record on the external DNS server: _now. somedomain.com: 3bec75c6ebe6c633d345c2cf13f94c557f32c4761f181556490c732e518eadcd
Error: Verification required: Please add the following TXT record on the external DNS server: _now.icahygiene.com.hk: 3bec75c6ebe6c633d345c2cf13f94c557f32c4761f181556490c732e518eadcd
    at module.exports.EventEmitter.setupDomain.name.retry (/snapshot/repo/dist/now.js:1876:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by javivelasco** [comment]
Hi @williamli , what version of `now` are you using? Soon we will be landing in stable some changes that are now on `canary` but I'm surprised you're getting that unfriendly error. Here is what it looks like in the latest:

<img width="669" alt="screenshot 2018-06-30 10 37 23" src="https://user-images.githubusercontent.com/1634922/42123914-c11a7a42-7c51-11e8-8ccd-a6d172ca62db.png">

**Comment by wiiiimm** [comment]
@javivelasco I saw it on the latest stable release for macos and linux 3 days ago.

**Comment by wiiiimm** [comment]
@javivelasco works now
