### ISSUE TITLE
FR: `now alias <ID> *.domain.com`

### ISSUE THREAD

**Issue by remy** [vercel/vercel#143]
It would really useful to be able to alias wildcard DNS to a now instance.

Specifically, I have three products that all rely on the cname to work out what to serve, two of which:

- confcodeofconduct.com : de.confcodeofconduct.com etc
- mit-license.org : rem.mit-license.org

Thanks.

![giphy](https://cloud.githubusercontent.com/assets/13700/20607151/eb3f4046-b26d-11e6-90f8-38eaf3da5d9c.gif)

**Comment by amccloud** [comment]
@leo any updates for this?

**Comment by leo** [comment]
@amccloud I think it's a great idea, but we currently have many other more important issues to tackle.

**Comment by adrianmcli** [comment]
Is this on the roadmap? It's been almost a year since the issue was created.

**Comment by rauchg** [comment]
Definitely on the roadmap @adrianmcli. It's pending on Lets Encrypt landing support for wildcard certificates, which happens January 2018.

**Comment by wiiiimm** [comment]
@rauchg just wondering how is it going now?

**Comment by tzarger** [comment]
It appears Lets Encrypt supports wildcard ssl now.. has wildcard hosting on Now been implemented? @rauchg

**Comment by sco** [comment]
+1 for this capability -- needed for a project I'm working on

**Comment by jefflam** [comment]
hey guys! just wanted to check to see if this has any progress too

**Comment by adrianmcli** [comment]
I wonder if it might be slated for announcement on Zeit day.

**Comment by adrianmcli** [comment]
https://zeit.co/blog/wildcard-certs

Yay! I think we can close this issue now, @remy

**Comment by wiiiimm** [comment]
@adrianmcli not yet. still need to actually support `now alias <ID> *.domain.com` first

**Comment by seanconnollydev** [comment]
I must be misunderstanding that blog post because I don't see any wildcard certs generated for my `now.sh` aliases.

**Comment by EricKavalec** [comment]
Any updates? Thanks!

**Comment by futurist** [comment]
+1 for this, very needed!

**Comment by michieldewilde** [comment]
+1

**Comment by juanpujol** [comment]
+1 Any news on this? Working on a multi-tenant app that will benefit a lot of this feature.

**Comment by Sambillingham** [comment]
Is there any news on this or a work around others are using?

**Comment by reckr** [comment]
It's January 2019 now, what's the status?

**Comment by ties-v** [comment]
> 
> 
> Is there any news on this or a work around others are using?

@Sambillingham I currently have a boilerplate Now v2 now.json with some routes for different parts, like an static site and API. For each subdomain I want to be available I rename the project name in now.json and the alias and deploy it. It is not the most easy way, but using aliases for the services under the hood this only has to be done once. And I think you can automate this deployment using Now's API because you only supply a config json (have not tried it yet).

**Comment by ajainvivek** [comment]
Any update on this?

**Comment by berkant** [comment]
Do this people. Heroku has this wildcard feature but I need FaaS.

**Comment by nahtnam** [comment]
Would like to see this as well, currently resorting to Heroku for this. Please support nesed subdomains such as (hello.world.example.com) as well.

**Comment by Gdewilde** [comment]
Hey @OlliV, any estimates on the delivery date? It's currently a blocker for us at Apideck and GDPR Form. We would be happy to switch to Zeit as soon as this is supported.

**Comment by PullJosh** [comment]
It would also be very useful to be able to add subdomains to the `routes` of an existing instance (aliased or not).

Ideally, I could create routes that look something like the following:
```
{
  "src": "(?<subdomain>[^\.]+).[DEPLOYMENT_URL]/abc",
  "dest": "/endpoint?sub=$subdomain"
}
```

**Comment by remy** [comment]
@PullJosh been waiting for that particular feature since late 2016. Still need it today for both original project and new projects.

**Comment by fanweixiao** [comment]
Agree to @PullJosh 's suggestion, waiting for this feature, it's really useful.

**Comment by unix** [comment]
I set up a gateway(`nginx`) to forward all requests to `serverless`, it looks like it can work. Maybe you can try it, but this need a cloud server:
```
listen 80;
server_name  ~^(.*).domain.com;
set $key $1;

location / {
  resolver 8.8.8.8;
  proxy_pass https://domain.now.sh/$key;
  proxy_redirect off;
}
```
Even if you have many `now` services, you can proxy all requests with only one Nginx server. This is not a good solution, but it works well. I'm also waiting for new features.

**Comment by mkrn** [comment]
Just to clarify my use case is pointing wildcard subdomains to the same deployment. Is it possible with a single alias at the moment?  Alias * to production deployment? 

Seems like no luck... Is this feature planned?

Currently, I point CNAME * to CloudFront, which then has wildcard cert and points to my ELB with ECS cluster.  Hoping to move to now, which would simplify things a ton! 

Thanks

**Comment by mikeal** [comment]
I need this as well.

I can tell you a bit about my use case and why this is so important.

I’m working on an SPA and one of the things it does is load in code dynamically, which is rather difficult to do securely. The best solution I’ve found is to load in an iframe at a location with a uniquely named identifier stuck to the domain so each dynamic load of the code is at a different domain name and won’t share any local storage. Every subdomain gets the same static content and then dynamically loads more code based on the subdomain. For the particular thing I’m trying to do, this iframe setup is the only option and it would be really nice if I could use Zeit for it.

**Comment by bart** [comment]
Isn't it possible to assign a wildcard domain to a now deployment? That's very very bad! Really need such a feature for a project where each customer gets its custom subdomain. From my point of view this is a MUST feature. Having dynamic subdomains is a common use case for lots of projects.

**Comment by paulogdm** [comment]
@bart Stay tuned for our announcements. You don't need to wait for this feature anymore.

**Comment by Gdewilde** [comment]
Thanks for the update @paulogdm! Any ETA?

**Comment by leo** [comment]
Next week!

**Comment by Gdewilde** [comment]
You made our weekend guys! Thanks for the effort.

**Comment by bart** [comment]
Will it also work with an external DNS like cloudflare? :)

**Comment by hhff** [comment]
Amazing, can't wait for this!

**Comment by leo** [comment]
Wildcard Domains are now available! 🎉 

https://twitter.com/zeithq/status/1171464312763760641

**Comment by hhff** [comment]
@leo this seems to mean we need to host our DNS with now.sh

How can we use wildcard domains with external DNS?

(also, THANK YOU!)

**Comment by unitof** [comment]
Can I route specific subdomains using `now.json`, or need to use a third party tool to parse the subdomain from the host (like in your example)?

**Comment by rauchg** [comment]
@hhff using an external DNS provider is not currently possible because we need to issue wildcard TLS certificates. We want to give you a fully automatic, reliable and performant solution, so that's not an option at the moment.

ZEIT DNS is backed by a AnyCast network with world-wide POPs (points of presence) coverage and hundreds of monitoring nodes with 100% uptime. If there's a feature you'd like to see in our built-in DNS offering, please let me know.

**Comment by leo** [comment]
@unitof Routing specific subdomains in `now.json` is not possible. However, parsing `req.headers.host` requires no third party tool – you can do it right inside your own code.

**Comment by rauchg** [comment]
As well as `window.location.hostname` on the client-side

**Comment by bart** [comment]
@rauchg First of all thanks for the feature. But why do you need to issue a wildcard TLS certificate if a provider like Cloudflare is already doing it? I don't get the point here. From my point of view it's mandatory to be able to use an external DNS which has some special configurations. Our Cloudflare config for example has some page rules to cache cdn.domain.tld subdomain requests. Think stuff like that is not possible with zeit CDN, right?

**Comment by MarvinMiles** [comment]
> Routing specific subdomains in `now.json` is not possible. However, parsing `req.headers.host` requires no third party tool – you can do it right inside your own code.

@leo Hey

How to use ` stale-while-revalidate` with parsing `req.headers.host` on domain and subdomain? Without SWR in header it works perfectly - I get different content on different domains within one deployment. But with SWR I get same cached content. Any solutions?

Thanks!
