### ISSUE TITLE
`now.json` Setting Headers

### ISSUE THREAD

**Issue by jaruba** [vercel/vercel#1431]
I'm trying to deploy static json files with CORS.

My `now.json` file looks like this:

```
{
  "static": {
    "headers": [
      {
        "source": "**",
        "headers": [
          {
            "key": "Access-Control-Allow-Origin",
            "value": "*"
          }
        ]
      }
    ]
  }
}
```

Based on [this docs page](https://zeit.co/blog/new-static-deployments) and [this online minimatch tester](http://www.globtester.com/) it should be correct and `Access-Control-Allow-Origin` should be set to `*` for all file request headers, but it isn't.

In all my attempts to change headers like this, with any one source file or all, the headers are never changed.

Am I missing something here, or is this a bug?

**Comment by leo** [comment]
Hey!

Thank you for opening an issue. However, I have to tell you that this (very likely) comes from the configuration file being placed in the wrong directory.

E.g. If you run `now ./build`, it needs to be placed *inside* the "build" directory, not outside. If it's outside, it won't be read.

As you can see, it does work:

![image](https://user-images.githubusercontent.com/6170607/42174509-e89c52f2-7e22-11e8-810c-75684f725ecf.png)

I copied your exact config.

**Comment by jaruba** [comment]
Hi, thank you for your reply and your confirmation that the config works.

But sadly, I'm not running `now ./build`, I'm running `now` directly, there is no build process and `now.json` is in the top directory.

```
$ now --version
11.2.5
```

**Comment by leo** [comment]
@jaruba Can you send me your deployment to leo@zeit.co? Then I can check it.

**Comment by leo** [comment]
That is very weird, @jaruba. I just ran `now` in the repository you gave me:

![image](https://user-images.githubusercontent.com/6170607/42240791-bce36b82-7f08-11e8-90e1-a5b1eadbf9b2.png)

You can click [here](https://stremio-static-addon-example-ujswbajtzu.now.sh/manifest.json) to verify the result for yourself.

Can you try running just `now --force --debug` inside the directory and post the output here?

**Comment by jaruba** [comment]
@dhinus Thanks for checking that, I broke my hand a day ago and postponed testing. 🙄

**Comment by jaruba** [comment]
@leo as @dhinus mentioned, I'm not seeing any `Access-Control-Allow-Origin` header in the link you provided either.

**Comment by jaruba** [comment]
The header settings seem to be working correctly in the latest version of `now`, closing
