### ISSUE TITLE
`now rm` unusable due to rate limit when removing projects with many instances

### ISSUE THREAD

**Issue by zgeoff** [vercel/vercel#1440]
steps to reproduce:

1. have a project with 80 instances
2. `now rm <project>`
3. `An unexpected error occurred in rm: Error: Rate limit exceeded (429)`

**Comment by rauchg** [comment]
Sounds like limiting the concurrency of our `now rm` operation would be a great idea

**Comment by igorklopov** [comment]
@meatwallace We adjusted the limits. Please try again.

**Comment by zgeoff** [comment]
Resolved. Thanks.
