### ISSUE TITLE
The cli creates a record for each subdomain alias

### ISSUE THREAD

**Issue by OlliV** [vercel/vercel#1443]
This code is looking if `*` CNAME record points to `alias.zeit.co` and if it does then it creates a new CNAME.

https://github.com/zeit/now-cli/blob/acdfde5aa2e2c3de4208bce92d031877bbe2f2d3/src/providers/sh/commands/alias/maybe-setup-dns-records.js#L31-L32

**Comment by OlliV** [comment]
@javivelasco did we fix this?

**Comment by javivelasco** [comment]
I think so, yeah! Closing
