### ISSUE TITLE
Exposing env. specified via Now CLI to Docker RUN command

### ISSUE THREAD

**Issue by nieltg** [vercel/vercel#1446]
[The documentation here](https://zeit.co/docs/features/env-and-secrets) says that environment variables specified via Now CLI will be available on `RUN` and `CMD` instructions. But in my deployment, it just exposes to `CMD` instructions. I can't access it from `RUN`.

**Keyword:** env, environ, environment, `RUN`, Docker, Dockerfile

Here is the command I use:

```
$ now --public -e SECRET_KEY=@linecms-demo-secret-key
```

Here is `RUN` command to test on `Dockerfile`:

```
RUN sh -c "export"
```

And this is the output of the command:

```
> Step 15/19 : RUN sh -c "export"
>  ---> Running in 9be8e9bbcc2d
> export ALLOWED_HOSTS='*'
> export GPG_KEY='<secret>'
> export HOME='/root'
> export HOSTNAME='9be8e9bbcc2d'
> export LANG='C.UTF-8'
> export PATH='/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
> export PROJECT='linecms'
> export PROJECT_DIR='/opt/linecms'
> export PROJECT_SERVER_DIR='/opt/linecms/server'
> export PROJECT_STATIC_DIR='/opt/linecms/static'
> export PWD='/opt/linecms/server'
> export PYTHONUNBUFFERED='1'
> export PYTHON_PIP_VERSION='10.0.1'
> export PYTHON_VERSION='3.6.6'
> export SHLVL='2'
> export STATIC_ROOT='/opt/linecms/static'
> export USE_WHITENOISE='1'
>  ---> 4c1cc9bb3ba8
```

Thank you very much.

**Comment by develomark** [comment]
I also have this issue. I think it is the same issue as #522. 

I don't believe that now is passing any env to the docker deployment.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
