### ISSUE TITLE
Deployment stopped working without showing any errors

### ISSUE THREAD

**Issue by kumarabhirup** [vercel/vercel#1447]
**The problem is completely expressed in the StackOverflow question below...**
https://stackoverflow.com/questions/51229080/zeit-now-deployment-stopped-working-no-errors-are-shown

**Comment by matheuss** [comment]
Hi @KumarAbhirup,

We are currently focusing on hosting HTTP/WebSocket servers, so every deployment is frozen when they don't receive an HTTP request for a while. You can read more about it here: https://zeit.co/docs/guides/app-lifecycle-and-scalability#instances-&-scaling

For example, if you want to ensure that your deployment will **always** have one running instance in our `sfo` region (regardless of incoming traffic), you can run `now scale deployment.now.sh sfo 1`.
