### ISSUE TITLE
Make `now` CLI installation binary update atomic

### ISSUE THREAD

**Issue by jamo** [vercel/vercel#1454]
`npm i -g now` renders `now` useless until the download of the binary completes.
Can't we just update the binary once we have downloaded it completely.

```
$ now
Please wait until the 'now' installation completes!
```

**Comment by igorklopov** [comment]
IIRC it is npm's "feature"

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!
