### ISSUE TITLE
Add option not to output email addresses

### ISSUE THREAD

**Issue by Vinnl** [vercel/vercel#1460]
I run deployments to Now.sh in a public CI instance, which is great. I also want to clean up deployments I no longer use, using `now rm`. Unfortunately, that command also lists the email address associated with the current account, exposing it to scrapers. It would thus be nice if the CLI had an option not to display that.

**Comment by joecohens** [comment]
Hi @Vinnl can you share more information of where are you seeing the email addresses leaked? The `now rm` command should only display something like this:

Note that I'm using the `-y` flag in order to skip the removal confirmation which I think it would be ideal for your case.

```bash
$ now rm micro -y
> Found 1 deployment for removal in joecohens [2s]
> Success! 1 deployment removed [3s]
- micro-cryeynvlgx.now.sh
```

**Comment by Vinnl** [comment]
Hmm well, for obvious reasons I deleted the output of the CI job back then. That said, when I tried to rerun it now, the token was no longer logged (it also included the `-y` flag). Perhaps this changed between v11.2.8 of the CLI which was used back then, and v11.4.6 that was used now? In any case, I guess this is no longer an issue then :)

**Comment by joecohens** [comment]
@Vinnl it seems that you haven't created a username for your account yet, please go to your account on https://zeit.co/account and add a username to your account, with that we will show the username instead of the email.

**Comment by Vinnl** [comment]
@joecohens That makes sense now that I can compare it with your output, and I've now changed it :) However, I'd still think it makes sense to be able to suppress the output of email addresses for users without usernames. Up to you of course, just a point of feedback :)
