### ISSUE TITLE
now alias shows old version on Chrome 67

### ISSUE THREAD

**Issue by lonelydatum** [vercel/vercel#1461]
When I deploy using "now alias _____ prequilt.com", then going to prequilt.com still shows an old version I deployed weeks ago. Is this a caching issue?

The error happens on Chrome Version 67.0.3396.99.
Its fine when I view it in Chrome Incognito.
Im using Now 4.0.0-canary

To reproduce this, go to https://prequilt.com using both Chrome Version 67.0.3396.99 and Chrome Incognito.

Thank you.

**Comment by leo** [comment]
Please take a look at the caching headers you are sending from your deployment. If those headers instruct the browser to cache the files, that's what will happen! 😊 

It doesn't happen in Incognito mode, because that doesn't allow caching.
