### ISSUE TITLE
Cloudflare error 1000 causing api calls to 403

### ISSUE THREAD

**Issue by kc-beard** [vercel/vercel#1462]
Our api calls on now deployments are returning 403s with a cloudflare error of `Error 1000: DNS points to prohibited IP`. 

Additional details that may help: 

- We proxy our api calls through an express route `/api` and then hit our endpoint, which is fronted by cloudflare. So the calls that are failing look like `our-domain-rabmbjdyrc.now.sh/api`
- cloudflare is complaining that we need to `change the DNS A records for our-api-url.com to resolve to a different IP address.`

Is there a workaround for this? Is this an issue on your end from your recent cloudflare changes or is something wrong with our configuration?

**Comment by jamo** [comment]
Suspecting it's because of routing twice through cloudflare.

While we are looking for a global and safe fix, you could try to delete `cf-ray`-header of the proxied request. This is the most likely cause for the issue you are observing.

**Comment by kc-beard** [comment]
Thanks for your response. Is there anyway to disable cloudflare on our `.now.sh` domains? We're on a pro plan and it's unfortunate to have the feature automatically enabled and break all new deployments.

**Comment by zaklampert** [comment]
+1

**Comment by jschumme** [comment]
+1

isn't that a real showstopper bug? All nextjs deployments doing api requests in getInitialProps are broken...

**Comment by sobolevn** [comment]
The same happens for `nuxt.js`: https://github.com/wemake-services/wemake-vue-template/issues/713

**Comment by encho** [comment]
+1 with micro-proxy

**Comment by stevez86** [comment]
Along the lines of @jamo and this: https://sskaje.me/2016/08/error-1000-cloudflare/  I'm currently deleting the following headers for my proxy request and it appears to work. Haven't experimented further and not sure what the cons of this are (it feels very hacky), but you might want to try it. If you're using express and express-http-proxy this my solution:

```
import proxy from 'express-http-proxy';

const app = express();
app.use(
  '/api',
  proxy(<api url>, {
    proxyReqOptDecorator: (proxyReqOpts, srcReq) => {
      [
        'cf-connecting-ip',
        'cf-ipcountry',
        'cf-visitor',
        'cf-ray',
        'x-forwarded-for',
        'x-forwarded-proto',
      ].forEach(header => {
        if (proxyReqOpts.headers[header]) {
          delete proxyReqOpts.headers[header];
        }
      });
      return proxyReqOpts;
    },
  }),
);
```
Note: deleting just the cf-ray header did not fix it for me. If anyone finds that not all these headers need to be deleted, please let us know

**Comment by TooTallNate** [comment]
Closing because a valid workaround is documented in this issue, and there's nothing we can do about it on our end because it's a CloudFlare-specific error.
