### ISSUE TITLE
alias not working

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#1468]
I cannot set alias for the latest deploy

- [config](https://github.com/CodingBauer/CovertHabit/blob/0c9aad0e18e482e88ffbddbf1c3055310dd6db04/package.json#L41-L45)
- [failure](https://travis-ci.org/CodingBauer/CovertHabit/builds/403710478#L765)

This works:
```
$ node_modules/.bin/now alias coverthabit-ywvzrdnsel.now.sh coverthabit
> Assigning alias coverthabit to deployment coverthabit-ywvzrdnsel.now.sh
> Success! coverthabit.now.sh now points to coverthabit-ywvzrdnsel.now.sh [2s]
```

This does not
```
$ node_modules/.bin/now alias
> Error! Couldn't find a deployment to alias. Please provide one as an argument.
```

Not sure what I am doing wrong.

**Comment by zachlendon** [comment]
We are also having this issue now, we weren't before...

**Comment by bestwestern** [comment]
Same with alias with parameter:
```
now alias https://build-jkloxylm.now.sh mysitebaseurl
Error! Response error
```

**Comment by bestwestern** [comment]
My errror went away after updating the CLI
