### ISSUE TITLE
Can't deploy static sites if I reached the limit of active instances

### ISSUE THREAD

**Issue by sergiodxa** [vercel/vercel#1478]
Static sites are free and doesn't consume instances, yet if I reached my limit of active running instances I can't create a new static deployment.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
