### ISSUE TITLE
Configuration file not honored when prompted for public deployment

### ISSUE THREAD

**Issue by sergiodxa** [vercel/vercel#1479]
When deploying with an OSS account and not specifying the deployment is going to be public the configuration defined in `now.json` is not being honored. 

**Example**:
`now.json`
```json
{
  "files": [
    "test.html"
  ]
}
```

`index.html`
```html
<h1>It doesn't work!</h1>
```

`test.html`
```html
<h1>It works!</h1>
```

- ✅ When deploying with a paid account it uploads the test.html and not the index.html (https://static-hbyvviucqe.now.sh) 
- ✅ When deploying with an OSS account adding `"public": true` to the now.json it uploads the test.html and not the index.html (https://static-puwkpwvqwa.now.sh)
- ✅ When deploying with an OSS account adding `--public` to `now` it uploads the test.html and not the index.html (https://static-uaixtripzi.now.sh)
- ❌ When deploying with an OSS account without adding `"public": true` or `--public` the user is prompted for confirmation for the deployment being public and index.html is upload alongside test.html (https://static-juowmoiunl.now.sh and https://static-juowmoiunl.now.sh/test)

**Comment by markozxuu** [comment]
Maybe that problem is related to `now-desktop` cc @sergiodxa

**Comment by markozxuu** [comment]
I will take care of solving this problem 😸 ❤️

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
