### ISSUE TITLE
Bitbucket server support

### ISSUE THREAD

**Issue by timneutkens** [vercel/vercel#148]
Since `now` now supports Github, Gitlab and Bitbucket maybe add support for Bitbucket server.
Url is formatted like this: 
`ssh://git@<SERVER_URL>/<PROJECT>/<REPOSITORY>.git`

**Comment by timneutkens** [comment]
I'm closing this Since it wasn't asked for By anyone else 👍🏻

**Comment by gkiely** [comment]
This would be great to have!

**Comment by dangayle** [comment]
Can we re-open this?
