### ISSUE TITLE
State of Universal Now

### ISSUE THREAD

**Issue by cangoektas** [vercel/vercel#1480]
I was really excited when I first heard about Universal Now. I remember at the time there wasn't any documentation about it other than the blog post. Setting `now` up and trying to deploy my first function also wasn't easy, and I had to read through the code just to understand what commands were supported. But I knew that the product was very young and didn't think it was a big issue. I loved the idea and the concept behind it. I remember executing `now deploy`, seeing how a single command would provision multiple AWS resources, and being able to curl my microservice just seconds after that completely blew me away. I just want to share how inspiring that was and thank you for this amazing work.

That being said, unfortunately, it feels like Universal Now hasn't been the focus of ZEIT ever since (please correct me if I'm wrong). There is no documentation around and running `now aws help` still only prints out `halp` to the console, and there's no mention of `aws` or `gcp` when running `now help`.

1. Are there any plans to actively support and maintain Universal Now?
2. Was this maybe a business-related decision to not put efforts into supporting AWS/GCP?

Maybe this also wasn't a conscious decision but just something that happened naturally when focusing on your own product which is understandable. I'd enjoy working on tooling for Lambda, and I'm tempted to jump into this, but I'd like to understand how you see the future of Universal Now a bit better first. I'd appreciate your thoughts on this.

**Comment by rauchg** [comment]
1. Yes
2. No

The current roadmap is very strictly focused on polishing the current Now UI. We still have some important additions to make to `now.json` (and some minor deprecations). 

We have a blog post coming up on this in the coming weeks that will bring a lot of clarity :)

**Comment by philcockfield** [comment]
>> We have a blog post coming up on this in the coming weeks that will bring a lot of clarity :)

Great - looking forward to reading that when it lands @rauchg.  `now` has become such strategic play in product creation...what you guys are doing is so beautiful.
