### ISSUE TITLE
Environment variable starting with the digit zero (0) hangs build

### ISSUE THREAD

**Issue by yieme** [vercel/vercel#1481]
FYI: If you have an environment variable in `now.json` that begins with the digit zero `0` then deploying with `now` will get stuck at 'Building...' as of now cli 11.3.2.

**Comment by leo** [comment]
@yieme What was the last version of Now CLI you used (before 11.3.2)?

**Comment by yieme** [comment]
11.2.10 and then 11.3.1, if I recall correctly. Hope this helps :-)

**Comment by leo** [comment]
I see. This should definitely not be happening.

**Comment by TooTallNate** [comment]
I can confirm that this happens with both Now v1 and Now v2.

* v1 - Stuck at "building" forever and the deploy command never completes
* v2 - Deployment fails quickly with `Error! Your deployment failed. Please retry later. More: https://err.sh/now-cli/deployment-error`

**Comment by TooTallNate** [comment]
Also note that it's the environment variable _name_ that triggers this behavior. An env var _value_ beginning with 0 works as expected.

**Comment by styfle** [comment]
Vercel CLI prints a proper error message now.


```
$ vercel -e 0ZERO=0ZERO
Vercel CLI 21.3.0
Error! The env key "0ZERO" contains invalid characters. Only letters, digits and `_` are allowed, and must begin with a letter
```
