### ISSUE TITLE
Errors deploying Docker to NOW (too many files to deploy ~8,299 files)

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#1484]
It was working till this morning.

Now I have been getting various errors in command line:

> [debug] [2018-07-28T07:58:03.044Z] POST https://api.zeit.co/v4/now/deployments?teamId=team_okZnJ6xhdZ2yoWFB4axtsHBp [object Object]: 122098.950ms
> [debug] [2018-07-28T07:58:03.046Z] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/repo/dist/now.js:1672:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] [2018-07-28T07:58:05.489Z] Get files ready for deployment
> [debug] [2018-07-28T07:58:05.624Z] Get files ready for deployment: 134.693ms
> [debug] [2018-07-28T07:58:05.625Z] POST https://api.zeit.co/v4/now/deployments?teamId=team_okZnJ6xhdZ2yoWFB4axtsHBp [object Object]

sometimes

> Error! Build failed

sometimes 

> Error! Unexpected response

====

I sometimes do get a build URL, sometime CLI just sit there for about 20 to 30 minutes

If I look up the link in browser, there will just be an empty log and the state will be "initializing"... and after a while, it will become "error"

**Comment by wiiiimm** [comment]
Here is my most recent deployment call

now --local-config=now-production.json -f --debug
> Deploying ~/projects/bbiHQ/lex-wp under bbi
> [debug] [2018-07-28T08:14:26.622Z] Detected `deploymentType` = `docker`
> [debug] [2018-07-28T08:14:26.622Z] Detected `deploymentName` = "lex-wp-production"
> [debug] [2018-07-28T08:14:26.622Z] Scale presets for deploy: {"bru1":{"min":0,"max":1}}
> [debug] [2018-07-28T08:14:26.633Z] Getting files
> [debug] [2018-07-28T08:14:29.410Z] Getting files: 2776.374ms
> [debug] [2018-07-28T08:14:29.612Z] Computing hashes
> [debug] [2018-07-28T08:14:35.991Z] Computing hashes: 6378.870ms
> [debug] [2018-07-28T08:14:36.469Z] Get files ready for deployment
> [debug] [2018-07-28T08:14:36.624Z] Get files ready for deployment: 153.709ms
> [debug] [2018-07-28T08:14:36.624Z] POST https://api.zeit.co/v4/now/deployments?teamId=team_okZnJ6xhdZ2yoWFB4axtsHBp [object Object]
> [debug] [2018-07-28T08:16:38.881Z] POST https://api.zeit.co/v4/now/deployments?teamId=team_okZnJ6xhdZ2yoWFB4axtsHBp [object Object]: 122254.433ms
> [debug] [2018-07-28T08:16:38.888Z] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/repo/dist/now.js:1672:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] [2018-07-28T08:16:40.453Z] Get files ready for deployment
> [debug] [2018-07-28T08:16:40.671Z] Get files ready for deployment: 216.518ms
> [debug] [2018-07-28T08:16:40.672Z] POST https://api.zeit.co/v4/now/deployments?teamId=team_okZnJ6xhdZ2yoWFB4axtsHBp [object Object]
> [debug] [2018-07-28T08:18:42.365Z] POST https://api.zeit.co/v4/now/deployments?teamId=team_okZnJ6xhdZ2yoWFB4axtsHBp [object Object]: 121690.124ms
> [debug] [2018-07-28T08:18:42.366Z] Retrying: Error: Unexpected response
Error: Unexpected response
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/repo/dist/now.js:1672:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] [2018-07-28T08:18:44.920Z] Get files ready for deployment
> [debug] [2018-07-28T08:18:45.085Z] Get files ready for deployment: 164.522ms
> [debug] [2018-07-28T08:18:45.085Z] POST https://api.zeit.co/v4/now/deployments?teamId=team_okZnJ6xhdZ2yoWFB4axtsHBp [object Object]



![screen shot 2018-07-28 at 16 20 30](https://user-images.githubusercontent.com/179761/43354611-2b62cb84-9282-11e8-938b-4965bbdab7e3.png)

**Comment by wiiiimm** [comment]
inside my `wp-content` folder, which I tried to deploy (wordpress), I have around 8,299 files and totalling to around 200MB.

The deployment problem went away if I were to tar.gz that folder and then extract the content inside Dockerfile with

```
ADD payload.tar.gz /var/www/html/
```

Doing this will allow me to deploy, but will no longer allow me to use the same Dockerfile for development as there is no payload.tar.gz file until I deploy.

**Comment by wiiiimm** [comment]
I guess I can also get around with this by using

```
ADD deploy/*.tar.gz /var/www/html/
```

instead so it won't expect a tar.gz to extract if there is none...

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
