### ISSUE TITLE
[feature request] improve sort / filter ability on `ls` commands 

### ISSUE THREAD

**Issue by mxmzb** [vercel/vercel#1487]
i'd really like to have a way to sort / filter the list there, I have like 5 domains and 10 apps and it's already getting very tedious to understand what's going on.

i suggest having something along the following lines, which is extremely valuable imho: 

1. `now alias ls --sort url` would sort by url column instead of age column
2. `now alias ls --sort source` would sort by source column instead of age column
3. `now alias ls --sort domain` would sort by domain (currently doesn't have its own column)
4. `now ls --sort url` would sort by url column instead of age column
5. `now ls --sort app` would sort by app column instead of age column
6. `now ls --sort domain` would sort by domain (currently doesn't have its own column)

additionally you could also have a `--filter` flag which would do exactly the same but filtering by the passed value (you already have it partly in place for `now ls` where you can do `now ls <appname>`). i don't think there is a need to also have a sort direction though.

**Comment by paulogdm** [comment]
I would do a little research in what should be the default sorting, in terms of UX.
For teams the output of `now ls` can be lots of lines, and a sorting by `app` name should be better. For individuals it can be interested to sort by `age`, like today. Just giving my input...
Let me see if I can do at least `now ls --sort` in a PR,
Edit: Hmmm https://github.com/zeit/now-cli/search?q=sort&unscoped_q=sort

**Comment by leo** [comment]
For this purpose, we deployed support for [metadata](https://zeit.co/blog/deployment-metadata)! 😊
