### ISSUE TITLE
How to pass arguments to "docker run"

### ISSUE THREAD

**Issue by backflip** [vercel/vercel#149]
How would I deploy something like https://github.com/magnetikonline/dockerhtml5validator? Simply running `now` properly deploys the machine (https://dockerhtml5validator-azybyqnlkf.now.sh) but fails to handle form requests (redirecting https://dockerhtml5validator-azybyqnlkf.now.sh/check?uri=https%3A%2F%2Fwww.google.ch&charset=%28detect+automatically%29&doctype=Inline&group=0 to localhost:8888, e.g.). I assume I have to properly configure this port. However, I don't understand whether I can pass any arguments to `docker run` (as described in https://github.com/magnetikonline/dockerhtml5validator/blob/master/run.sh) when it's triggered by now. `now -p 8080:80 -p 8888:8888` doesn't fix it either.

Disclaimer: I have no clue how to use Docker.

**Comment by backflip** [comment]
Which ports can be used?

**Comment by OlliV** [comment]
Currently we only support exposing a single port. Therefore `-p` is not needed as we automatically map the exposed port to 80.

**Comment by leo** [comment]
^

**Comment by backflip** [comment]
Thanks for clarifying! Will try to adapt https://github.com/magnetikonline/dockerhtml5validator to use one port only.

**Comment by magnetikonline** [comment]
@backflip yeah I don't think you can use this project with my Docker image. The validator is split into two services - the "classic" W3C validator and the new "HTML5" validator, which both work in tandem - and thus need two ports.

**Comment by backflip** [comment]
Hey @magnetikonline, I decided on [exposing](https://github.com/magnetikonline/dockerhtml5validator/blob/master/Dockerfile#L21) 8888 instead of 80 since I need the HTML5 validator only. Works like a charm.

**Comment by backflip** [comment]
Thanks for making it so incredibly easy to deploy my own HTML validator, @magnetikonline and @OlliV & @leo (and @rauchg, of course)!! ❤️

**Comment by magnetikonline** [comment]
Thanks @backflip appreciate the kind words!
