### ISSUE TITLE
Region selection

### ISSUE THREAD

**Issue by leo** [vercel/vercel#15]
@rauchg indicated that I can "handle the region affinity, you'll just have to add a field to `package.json` under the `now` namespace." What field should I use to do this?

@aexmachina

**Comment by leo** [comment]
No features in here

**Comment by andywer** [comment]
Hey there! I am facing the same situation. @leo closed his issue, but what is the outcome?

Can I set the region somehow?

Thx! :)

**Comment by simonexmachina** [comment]
I was told by @rauchg:

> To handle the region affinity, you'll just have to add a field to `package.json` under the `now` namespace.

But I never managed to find out the name of the field 😉

**Comment by leo** [comment]
We'll be documenting this very soon! Since this is a feature we're working on secretly, this is the only thing I can tell you... 😊

**Comment by maximilianschmid** [comment]
+1 region selection

**Comment by leo** [comment]
We're on it!

**Comment by hongymagic** [comment]
Are there any updates to this? Region latency from Australia/Sydney is pretty bad right now and would love to be able to change this to default to region closer to where my customers are.

**Comment by debianw** [comment]
I'm having critical latency issues too. Could this be related to a region ? #592

**Comment by shogochiai** [comment]
+1 for region selection from Singapore.

**Comment by nicolasdao** [comment]
+1 for region selection from Sydney.

**Comment by wytanj** [comment]
+1 for Singapore come on @rauchg you were here just last year lol

**Comment by summyd** [comment]
+1 us-east-1

**Comment by timhanlon** [comment]
+1 for Sydney

**Comment by agustif** [comment]
+1 For Europe

**Comment by tkshi** [comment]
+1 for Tokyo

**Comment by edhollinghurst** [comment]
Is there any estimate for when the Brussels region will be available? I'm trying to persuade my client to use Now but they are reluctant without a European region to deploy to.

**Comment by pranaygp** [comment]
We have a region in EU (in Brussels) that you can deploy to. Check out https://bru.now.sh/ to test your latency to BRU.

To deploy to BRU, you should be able to run:
```
now --regions bru
```

**Comment by edhollinghurst** [comment]
OK great - thanks!

**Comment by timneutkens** [comment]
Just to be clear, BRU is not in general availability yet. When it's available you'll be able to do something similar to what @pranaygp's showing 👍

**Comment by clodal** [comment]
Now.sh introduced the BRU1 (Belgium) region 2 days ago. https://zeit.co/blog/multi-dc
