### ISSUE TITLE
Need a space in the error message for adding subdomain alias

### ISSUE THREAD

**Issue by plainspace** [vercel/vercel#1504]
https://github.com/zeit/now-cli/blob/8296de16ef609479ddb40f77b09d520d6067d998/src/providers/sh/commands/domains/add.js#L60

current: 
`now domain add -esome-domain.com`

desired:
`now domain add -e some-domain.com`

**Comment by joecohens** [comment]
Fixed on https://github.com/zeit/now-cli/pull/1509
