### ISSUE TITLE
Adding an external subdomain fails

### ISSUE THREAD

**Issue by G100g** [vercel/vercel#1508]
Hi all,
 I'm adding an external subdomain, with DNS records managed by the external provider Aruba, but something goes wrong.

First I added a CNAME to my DNS records, pointing to **alias.zeit.co**
Then running the alias command return an error

```
λ now alias https://axel-signalingserver-tvcnkmdbut.now.sh signaling.axeltechnology.com
> Assigning alias signaling.axeltechnology.com to deployment axel-signalingserver-tvcnkmdbut.now.sh
> Nameservers: dns2.technorail.com, dns.technorail.com, dns4.arubadns.cz, dns3.arubadns.net
> Error! No permission to access domain axeltechnology.com under development@axeltechnology.com
```

I followed this guide in the [documentation](https://zeit.co/docs/getting-started/assign-a-domain-name#4.-using-a-custom-domain-with-a-cname)

Then I tried to add an external domain.
I created a [TXT record](https://mxtoolbox.com/SuperTool.aspx?action=txt%3aaxeltechnology.com&run=toolpage) with the hash value.

and the command to add domain fail

```$ now domain add -e axeltechnology.com```

```
λ now domain add -e axeltechnology.com
> Are you sure you want to add "axeltechnology.com"? [y|N]
> Error! We couldn't verify the domain axeltechnology.com.

  Please make sure that your nameservers point to zeit.world.
  Examples: (full list at https://zeit.world)
    a.zeit.world        96.45.80.1
    b.zeit.world        46.31.236.1
    c.zeit.world        43.247.170.1

  As an alternative, you can add following records to your DNS settings:
    name        type         value
    _now        TXT          8f2587a2f760134367f3c8720ef9a2e8a59cb944b0a81040bba1526a4f639c4b
                ALIAS        alias.zeit.co
```

> Note: Aruba prevent me to insert the name **_now** to my record.

I'm with the free tier.

Thanks in advance to anyone could help me.

**Comment by joecohens** [comment]
Hi @G100g, sorry for the delayed response. It is important that you add the `_now` TXT record with your DNS provider so we can verify it.

**Comment by G100g** [comment]
Thank you Joe for your confirmation.

Best
