### ISSUE TITLE
env vars in Dockerfiles

### ISSUE THREAD

**Issue by brandonmp** [vercel/vercel#151]
I'm trying to deploy a `Docker` that uses `node` and some private `npm modules`, but can't seem to pass-in my `NPM_TOKEN` in the documented way.  

my dockerfile:

```
FROM node:argon
LABEL name="docker-thing" version="1.0"
RUN apt-get update &&\
    apt-get install -y imagemagick graphicsmagick
WORKDIR /app
COPY ./dist .
ARG NPM_TOKEN  
COPY .npmrc .npmrc
COPY ./package.json .
RUN npm i --production
RUN rm -f .npmrc
CMD node ./app.js
```

and my `.npmrc` reads:
`//registry.npmjs.org/:_authToken=${NPM_TOKEN}`

to build, i normally run:  
`docker build --build-arg NPM_TOKEN=${NPM_TOKEN} -t docker-thing .`

that is, NPM_TOKEN is alphanumeric, in my `bash env vars`, and has a pattern of `XXX-XXX-XXXX`

To add the secret to `now`, i ran:
`now secret add npm_token XXX-XXX-XXXX`

then to start `now`:
`now -e NPM_TOKEN=@npm_token`

Unfortunately this results in a failure @ the `npm i --production` step, ie, `@scope/module is not in the NPM registry` --- which implies a failed authentication

I have tried hard-coding my `NPM_TOKEN` into my local `.npmrc` (and then changing my token, of course), and that works, so I suspect my problem is one of syntax.  

Thanks in advance for insight anyone might have

**Comment by gajus** [comment]
From what I can tell, the ENV variables are not being passed as neither the ENV variables or the build args.

It would be ideal to be able to specify the build args (and fix the ENV).

**Comment by leo** [comment]
If this problem still occurs, please move it over to [this repo](https://github.com/zeit/now-cloud). That's where we'll collect the bugs of the platform from now on (separate space, easier to work on)! 😊
