### ISSUE TITLE
How do I automatically alias my deployment upon merging a pull request

### ISSUE THREAD

**Issue by kudapara** [vercel/vercel#1512]
Is there a way that after a successful deployment of my Node app by the Now app for Github to automatically alias the deployment without having me to go to the terminal and manually type. 

```bash
> now alias
```

**Comment by ericmasiello** [comment]
+1

**Comment by kudapara** [comment]
Please assist 🙏 

@leo @rauchg @matheuss @TooTallNate @javivelasco @rase-

**Comment by kudapara** [comment]
Apparently the zeit team is still working on the feature. I got the answer in this thread.

https://spectrum.chat/?t=74de4ef8-7ce2-48da-a2aa-0a56dd7157d8
