### ISSUE TITLE
Passing arguments to docker run

### ISSUE THREAD

**Issue by frandiox** [vercel/vercel#1513]
Hi! Is there any way to pass arguments to `docker run`? I'd like to connect Google Stackdriver to Docker for logging [like this](https://cloud.google.com/community/tutorials/docker-gcplogs-driver). I've also tried to create `/etc/docker/daemon.json` but no luck. Any ideas?

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
