### ISSUE TITLE
Using the API directly and re-usable CLI logic

### ISSUE THREAD

**Issue by Siilwyn** [vercel/vercel#1517]
Hi there, I'm looking into using the API directly programmatically instead of spawning the CLI to deploy. Things like aliasing, listing and deleting deployments is straightforward however for deploying and thus parsing Now configuration and uploading files it seems quite some internal logic exists. For example the uploading part looks for already existing files to save some bandwidth and ignores certain files by default.

With the [now-client](https://github.com/zeit/now-client) deprecated I'm wondering, are there any plans to make the config and file uploading logic re-usable? Would love to import them instead of having to duplicate logic from this codebase.

Silly example: `const { getDeploymentFiles } = require('now-cli-helpers');`. Also looking into this to avoid having to download the binary so that's why the example uses a different module name.

**Comment by leo** [comment]
Yep! We're most likely going to split out this logic into a separate package at some point. For now, please refer to our [API docs](https://zeit.co/api) and copy the logic from Now CLI, if needed.

**Comment by Siilwyn** [comment]
Thanks, that is great to hear!

**Comment by leo** [comment]
[Here you go!](https://github.com/zeit/now-client)
