### ISSUE TITLE
(probaly wrong repo) Bug on https://zeit.co/, after registration confirmation.

### ISSUE THREAD

**Issue by jukefr** [vercel/vercel#1518]
Hey, sorry if this is the wrong repo but I could not find the repo for the site...

**Problem :**
I registered on your site with my github account.
I was showed a page with the code to verify I wasn't being man in the middled or whatnot, and the page told me it was waiting for me to verify my account, which I did by clicking the link in the mail and when this new page told me I was done, I closed it and went back to the first tab that was waiting for confirmation.

The tab refreshed and redirected me to [https://zeit.co/,](https://zeit.co/,) which results in a 404.

This isn't all that important but I figure you might not be aware of this.

**Comment by jamo** [comment]
Thanks, I passed this along to the team (and correct private repo)

**Comment by joecohens** [comment]
Thank you @jukefr this issue is already fixed. If you still need help with this issue, please respond and we will get back to you immediately.
