### ISSUE TITLE
Assigning alias in initial now build

### ISSUE THREAD

**Issue by evanmrose** [vercel/vercel#1519]
I am trying to assign an alias to my now deploy within CircleCI. I was wondering if it is currently possible to assign an alias to the deploy inline so for example instead of:

`now -t ${token}`
`now -t ${token} alias {OLD_NOW_URL} blabladev`

it would be:

`now -t ${token} alias blabla-dev`

The docs here: https://zeit.co/docs/features/aliases seem to only reference the two step approach.

**Comment by sergiodxa** [comment]
You could create a now.json with the key `alias` and `name` and then run:

```bash
now -t ${token}
now alias -t ${token}
```

And Now will apply the alias defined in now.json to the latest deployment with the name defined in now.json.

Another option is to run `now -t ${token} alias $(now -t ${token}) blabladev` to run the deploy and alias in one command and pass the deployment URL directly to the alias command.
