### ISSUE TITLE
Secure/private URL's

### ISSUE THREAD

**Issue by aesopwolf** [vercel/vercel#152]
I'm interested in making each deploy completely private. Preferably each deploy would only be available from behind an Amazon VPC so only employees can visit the urls from within our office.

Surely, some application level logic can be used to secure each deployment. But I was wondering if you have any other suggestions to make this possible?

**Comment by leo** [comment]
We probably won't implement this. Please do it on the side of the application!

**Comment by leerob** [comment]
Hello! I wanted to give an update here. VPC peering is now on our roadmap. Feel free to [contact us](https://vercel.com/contact/sales) if this is something your team needs. Thank you 👍
