### ISSUE TITLE
`name` field contains an invalid domain

### ISSUE THREAD

**Issue by rootedsoftware** [vercel/vercel#1525]
I'm trying to alias a deployment
I have my CNAME setup at DigitalOcean and I've used NSLOOKUP to confirm that the name servers there are publishing the records

```
MBP:foster bobby$ now alias https://foster-ujntgjvlsx.now.sh/ foster.joshjoe.com
> Assigning alias foster.joshjoe.com to deployment foster-ujntgjvlsx.now.sh
> Nameservers: ns1.digitalocean.com, ns2.digitalocean.com, ns3.digitalocean.com
> Error! An unexpected error occurred in alias: foster.joshjoe.com: The `name` field contains an invalid domain name ("foster.joshjoe.com") (400)
    at responseError (/snapshot/repo/dist/now.js:2564:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
```
MBP:foster bobby$ nslookup
> server ns1.digitalocean.com
Default server: ns1.digitalocean.com
Address: 2400:cb00:2049:1::adf5:3a33#53
Default server: ns1.digitalocean.com
Address: 173.245.58.51#53
> foster.joshjoe.com
Server:         ns1.digitalocean.com
Address:        2400:cb00:2049:1::adf5:3a33#53

foster.joshjoe.com      canonical name = alias.zeit.co.
```

I'm following the guide here: https://zeit.co/docs/getting-started/assign-a-domain-name

**Comment by rootedsoftware** [comment]
I was able to fix this by doing `now domain add -e foster.joshjoe.com` then after I added the TXT record to joshjoe.com I was able to re-run the `now alias https://foster-ujntgjvlsx.now.sh/ foster.joshjoe.com` command and this time it worked. 

I still think that there is a bug because the CLI clearly states that this kind of manual adding of domains isn't necessary.

**Comment by mattwynne** [comment]
I worked around this just now by trying to add an alias to my root domain (which failed, but differently) and then it somehow let me add the alias on the subdomain.

**Comment by mmmerl** [comment]
i experienced the same - ended up having to add the TXT record asked for when running `now domain add -e myrootdomain.com`, then intentionally trying to alias the root domain, and finally successfully aliasing the subdomain (so a mixture of the above two workarounds).

**Comment by styfle** [comment]
Thanks all! I too had to add the root domain instead of a sub domain (even though I only wanted to alias a subdomain).

See [this tweet](https://twitter.com/styfle/status/1030875751908814854) for my solution.
