### ISSUE TITLE
Alias success message url not clickable

### ISSUE THREAD

**Issue by albinekb** [vercel/vercel#1526]
When aliasing, it would be nice if the final output line:

`> Success! test.now.sh now points to test-vvajzszkni.now.sh [4s]`

included https:// for the alias domain, to make it clickable in terminals like Terminal.app, iTerm and Hyper:

`> Success! https://test.now.sh now points to test-vvajzszkni.now.sh [4s]`

I can create a PR if you want this, otherwise feel free to close. Just a minor thing 😃 

Edit: Looks like it's actually clickable in iTerm (3.2.0), but not in Terminal.app or Hyper.app.

**Comment by TooTallNate** [comment]
Closing because the aliased URL is now clickable with the `https://` prefix in the latest Now CLI.
