### ISSUE TITLE
 Failed to find deployment vrZSlz7TtRjmNVeLbbvK69Vc under xsestech

### ISSUE THREAD

**Issue by xsestech** [vercel/vercel#1529]
I tried to copy Yandex skill and It gave me an error
![2018-08-16 12-37-24](https://user-images.githubusercontent.com/29453203/44201155-39444b00-a151-11e8-80f3-d687904b8ad0.png)

**Comment by leo** [comment]
☝️ Closing now, in favor of this comment.
