### ISSUE TITLE
Local configuration rules are too strict

### ISSUE THREAD

**Issue by ben-goldberg** [vercel/vercel#1531]
As you note in the docs for [configuring now](https://zeit.co/docs/features/configuration):

>You can choose between creating a separate file for configuring Now (named now.json) or using the package.json file for this (if it's a Node.js project). Please note that it's not possible to use both methods to configure Now for a given project. If you use now.json, you can't include the now namespace within package.json, and vice-versa.

We need to have different configurations for deploying to "staging" vs "production". It would be nice if we could leave our default config (for staging) in the `package.json` file, and have our production config in its own file to be deployed with `now --local-config=now.prod.json`.

If I try to do this I get an error, as I'd expect given the documentation copied above:
> Error: You have a `now` configuration field inside `package.json` but configuration is also present in `now.json`! Please ensure there's a single source of configuration by removing one.

But it seems to me that I've just told `now-cli` which config I want to use, so there shouldn't be any confusion about what the "source of truth" is.

**Comment by leo** [comment]
As of Now CLI 12.0.0, the v2 pipeline (https://zeit.co/blog/now-2) only supports `now.json`. In turn, this problem should be gone!
