### ISSUE TITLE
Can't Use Puppeteer -- Error: Failed to launch chrome!

### ISSUE THREAD

**Issue by joemccann** [vercel/vercel#1535]
I have an application that uses Puppeteer (headless Chromium) yet Now is failing to launch it.

This works fine locally when installing and running with `npm` or `Docker`, but fails on Now.

I have the following arguments set in my Puppeteer instances as well

```js
		const browser = await puppeteer.launch({
			headless: true,
			args: ['--no-sandbox', '--disable-setuid-sandbox'],
			ignoreHTTPSErrors: true,
			dumpio: false
		})
```

```sh
08/19 11:44 AM (5m)
npm install
08/19 11:44 AM (5m)
08/19 11:44 AM (5m)
> puppeteer@1.7.0 install /home/nowuser/src/node_modules/puppeteer
08/19 11:44 AM (5m)
> node install.js
08/19 11:44 AM (5m)
08/19 11:44 AM (5m)
08/19 11:44 AM (5m)
Chromium downloaded to /home/nowuser/src/node_modules/puppeteer/.local-chromium/linux-579032
08/19 11:44 AM (5m)
08/19 11:44 AM (5m)
> nodemon@1.18.3 postinstall /home/nowuser/src/node_modules/nodemon
08/19 11:44 AM (5m)
> node bin/postinstall || exit 0
08/19 11:44 AM (5m)
08/19 11:44 AM (5m)
Love nodemon? You can now support the project via the open collective:
08/19 11:44 AM (5m)
 > https://opencollective.com/nodemon/donate
08/19 11:44 AM (5m)
08/19 11:44 AM (5m)
npm WARN api@1.3.0 No repository field.
08/19 11:44 AM (5m)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
08/19 11:44 AM (5m)
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
08/19 11:44 AM (5m)
08/19 11:44 AM (5m)
added 367 packages in 10.882s
08/19 11:44 AM (5m)
Snapshotting deployment
08/19 11:45 AM (5m)
Saving deployment image (99.9M)
08/19 11:45 AM (4m)
npm start
08/19 11:45 AM (4m)
08/19 11:45 AM (4m)
> api@1.3.0 start /home/nowuser/src
08/19 11:45 AM (4m)
> node server.js
08/19 11:45 AM (4m)
08/19 11:45 AM (4m)
Crypto Analytics API Server running on port. 4000
Error: Failed to launch chrome!
08/19 11:46 AM (3m)
/home/nowuser/src/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
    at onClose (/home/nowuser/src/node_modules/puppeteer/lib/Launcher.js:299:14)
08/19 11:46 AM (3m)
    at Interface.helper.addEventListener (/home/nowuser/src/node_modules/puppeteer/lib/Launcher.js:288:50)
08/19 11:46 AM (3m)
    at emitNone (events.js:111:20)
08/19 11:46 AM (3m)
    at Interface.emit (events.js:208:7)
08/19 11:46 AM (3m)
    at Interface.close (readline.js:368:8)
08/19 11:46 AM (3m)
    at Socket.onend (readline.js:147:10)
08/19 11:46 AM (3m)
    at emitNone (events.js:111:20)
08/19 11:46 AM (3m)
    at Socket.emit (events.js:208:7)
08/19 11:46 AM (3m)
    at endReadableNT (_stream_readable.js:1064:12)
08/19 11:46 AM (3m)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
08/19 11:46 AM (3m)
Error: Failed to launch chrome!
08/19 11:46 AM (3m)
/home/nowuser/src/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
    at onClose (/home/nowuser/src/node_modules/puppeteer/lib/Launcher.js:299:14)
08/19 11:46 AM (3m)
    at Interface.helper.addEventListener (/home/nowuser/src/node_modules/puppeteer/lib/Launcher.js:288:50)
08/19 11:46 AM (3m)
    at emitNone (events.js:111:20)
08/19 11:46 AM (3m)
    at Interface.emit (events.js:208:7)
08/19 11:46 AM (3m)
    at Interface.close (readline.js:368:8)
08/19 11:46 AM (3m)
    at Socket.onend (readline.js:147:10)
08/19 11:46 AM (3m)
    at emitNone (events.js:111:20)
08/19 11:46 AM (3m)
    at Socket.emit (events.js:208:7)
08/19 11:46 AM (3m)
    at endReadableNT (_stream_readable.js:1064:12)
08/19 11:46 AM (3m)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
08/19 11:46 AM (3m)
Error: Failed to launch chrome!
08/19 11:46 AM (3m)
/home/nowuser/src/node_modules/puppeteer/.local-chromium/linux-579032/chrome-linux/chrome: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
08/19 11:46 AM (3m)
08/19 11:46 AM (3m)
    at onClose (/home/nowuser/src/node_modules/puppeteer/lib/Launcher.js:299:14)
08/19 11:46 AM (3m)
    at Interface.helper.addEventListener (/home/nowuser/src/node_modules/puppeteer/lib/Launcher.js:288:50)
08/19 11:46 AM (3m)
    at emitNone (events.js:111:20)
08/19 11:46 AM (3m)
    at Interface.emit (events.js:208:7)
08/19 11:46 AM (3m)
    at Interface.close (readline.js:368:8)
08/19 11:46 AM (3m)
    at Socket.onend (readline.js:147:10)
08/19 11:46 AM (3m)
    at emitNone (events.js:111:20)
08/19 11:46 AM (3m)
    at Socket.emit (events.js:208:7)
08/19 11:46 AM (3m)
    at endReadableNT (_stream_readable.js:1064:12)
08/19 11:46 AM (3m)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

I was able to get the `Dockerfile` version to launch and build on Now, but it is > 300 MB so fails given the hard limit of 100 MB.

Any help is appreciated!

**Comment by simonw** [comment]
This issue is being discussed in more depth in #1523

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), we don't encourage you to use Docker anymore. However, I'm going to leave this issue open until Now 2.0 can also host Puppeteer.

**Comment by nitish24p** [comment]
Facing an issue while doing this https://github.com/zeit/now-cli/issues/2357

**Comment by jinwyp** [comment]
> As of today, we are announcing a full puppeteer example!
> https://zeit.co/blog/serverless-chrome
> 🎉
> @styfle

In this demo，use chrome-aws-lambda and puppeteer-core is different from  puppeteer

the full chrome support more feature such as chinese character.

I finished a  demo for screenshot https://now-demo.jinwyp.now.sh/

Type www.google.com it work fine. 
But type www.baidu.com , chinese characters can't display .

**Comment by styfle** [comment]
Hi @jinwyp 

The [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda) package is very minimal so you will likely have to add additional fonts to display Chinese characters.

See these related issues:

- https://github.com/alixaxel/chrome-aws-lambda/issues/4
- https://github.com/alixaxel/chrome-aws-lambda/issues/16

**Comment by jinwyp** [comment]
> Hi @jinwyp
> 
> The [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda) package is very minimal so you will likely have to add additional fonts to display Chinese characters.
> 
> See these related issues:
> 
> * [alixaxel/chrome-aws-lambda#4](https://github.com/alixaxel/chrome-aws-lambda/issues/4)
> * [alixaxel/chrome-aws-lambda#16](https://github.com/alixaxel/chrome-aws-lambda/issues/16)

Another problem different from puppeteer 

When you type "bbc.com" using puppeteer , it is screenshot ok,  but using puppeteer-core it got crashed ,  same with "baidu.com".   

It is seem like puppeteer-core can't not handle redirect link normally,  using puppeteer open "bbc.com" can redirect to "www.bbc.com", but puppeteer-core  got error.

**Comment by jinwyp** [comment]
When I add font  using await chrome.font('https://raw.githack.com/googlei18n/noto-cjk/master/NotoSansKR-Regular.otf'); 

the screenshot  language is Korea,  it is wired 

and I try set args with ''--lang=en-US''  or   setExtraHTTPHeaders with  'Accept-Language': 'en-US',.

the result is still Korea ,  too weird....

**Comment by styfle** [comment]
bbc.com works fine https://screenshot-v2.now.sh/bbc.com

![img](https://screenshot-v2.now.sh/bbc.com)

**Comment by jinwyp** [comment]
> bbc.com works fine https://screenshot-v2.now.sh/bbc.com
> 
> ![img](https://camo.githubusercontent.com/beded138091ef9215aa9e10518d292e9e94139d2/68747470733a2f2f73637265656e73686f742d76322e6e6f772e73682f6262632e636f6d)

I use this https://github.com/styfle/screenshot-v2

and deploy ,  bbc.com still not working. 

https://now-demo-mvc5gxelh.now.sh/backend/pic.js?url=http%3A%2F%2Fwww.bbc.com&en=true

Show error below

502: An error occurred with your deployment
Code: NO_STATUS_CODE_FROM_LAMBDA (more)

**Comment by jinwyp** [comment]
> It looks like you made changes to the original screenshot-v2 example so perhaps you are incorrectly decoding the query string parameters or maybe something else is crashing. Check the logs at https://now-demo-mvc5gxelh.now.sh/_logs (I can't view the logs because this deployment is not public).

I found the reason for bbc.com crashed 

 await page.screenshot({ fullPage: false});  When set 'fullPage" to 'true',  crashed. 

Another issue ,  I can't run "now dev" to debug this due to chrome-aws-lambda on local machine.  
Every time I change the code, need to run "now" to upload and debug on the server.

**Comment by styfle** [comment]
Correct `chrome-aws-lambda` only runs in a Lambda.

See [og-image](https://github.com/zeit/og-image) for how you can use `now dev` locally with your current Chrome installation. In particular, the [options.ts#L2](https://github.com/zeit/og-image/blob/b19f6c59b9e65bda9b34cfe8aa76674562a258ee/src/options.ts#L2) file specifies the path the local Chrome.

**Comment by kjr247** [comment]
I got it working, but we had to ramp up the memory and timeout waaaay up. 256 and 1 min 45 seconds.
