### ISSUE TITLE
website works intermittently with alias to my own domain

### ISSUE THREAD

**Issue by johnking** [vercel/vercel#1537]
Hi, 

  I am deploying my website at ZEIT with a free tier account, and found a weird and annoying issue: 

  1. It works smoothly with the random-generated URL 
  2. It works intermittently with the alias (which is my own domain)

   Because I need to have a stable URI in order to integrate with google OAUTH and github, so random-generated URL doesn't work for it. 

  this intermittent link is blocking my further work. 

   Does anyone else experience the similar issue before? 

thanks

**Comment by jamo** [comment]
Hey,

The idea is that each time you deploy you will get a new unique url. And you can then `alias` the deployment to a human-friendly domain when you'd like to "promote" it to production.

For 2nd part, I would recommend looking into deployment logs `now logs` to see what's happening with the deployment.

**Comment by johnking** [comment]
@jamo thanks for your reply, I will keep an eye open on the pattern when and why the link is intermittent when aliased to my own domain.

**Comment by sholladay** [comment]
Does it happen around the time that you update the alias? To my knowledge, `now alias` doesn't wait for the app to be ready, so there could probably be a brief window of downtime (or at least a very delayed HTTP response). Not 100% sure, though.

**Comment by joecohens** [comment]
Hi @johnking it looks to me that your deployment is freezing. 

Deployments have a [default scale](https://zeit.co/docs/getting-started/scaling#default-scaling) configuration which sets each deployment to freeze after a while from inactivity.

This lets you have any amount of deployments without worrying about your currently running instances. They will be unfrozen when a new request comes and keeps the instance running for a while (eventually freezing from inactivity with no requests again).

This behaviour can be completely avoided using the now scale command.

You can read more about your app lifecycle here https://zeit.co/docs/getting-started/scaling#default-scaling

I'm closing this issue for now, if you still need help, please respond and we will get back to you immediately.
