### ISSUE TITLE
now scale bug

### ISSUE THREAD

**Issue by joshhopkins** [vercel/vercel#1539]
`now scale [deployment] 1 1`

Prints in terminal:

```
> Scale rules for bru1, sfo1 (min: 1, max: 1) saved [6s]
> ✔ Scaled 1 instance in sfo1 [3s]
> ✔ Scaled 1 instance in bru1 [5s]
> Success! Scale state verified [5s]
```

Shows in menu bar app:

<img width="333" alt="screen shot 2018-08-21 at 1 24 51 pm" src="https://user-images.githubusercontent.com/11452674/44382082-0da4d480-a546-11e8-8d93-264925e0a192.png">

**Comment by leo** [comment]
What @tomsvogel said is correct. However, we should definitely work on displaying this in a better way and showing exactly which DC received which scaling rules.

**Comment by joshhopkins** [comment]
Got it. So there's no way of keeping only one instance alive? I have a cron job running and with 2 instances running in parallel it's firing twice.

**Comment by tomsvogel** [comment]
@joshhopkins then you need to shutdown one DC
now scale [deployment] [sfo1 / bru1] 0 0

cronjobs started by your app?

**Comment by joshhopkins** [comment]
Right, that's how to shutdown a DC – thanks @tomsvogel! Yeah – jobs are started with `npm start`
