### ISSUE TITLE
Assign a custom domain should not ignore regions field.

### ISSUE THREAD

**Issue by saeta-eth** [vercel/vercel#1542]
Hi there!

It's reproducible following some steps. I have used `now.json` to config my deployment process. I have filled the `region` field to make the deploy just on sfo1 and the `alias` field to have the latest deployment on a readable URL.
```
// now.json
{
 "name": "no-name-project",
 "alias": ["fake-alias"],
 "regions": ["sfo1"]
}
```
Then, just type:

- `now`
- `now alias`
- `now scale fake-alias.now.sh sfo1 1`

Until here, I have my scaled deployment on `sfo1` and everything work fine.
The issue appears when I try to have a custom domain. For instance: my-fake-custom-domain.com.

- `now alias fake-alias.now.sh my-fake-custom-domain.com`

My deployment is scaled on `sfo1` and `bru1`.

**Comment by leo** [comment]
When you assign an alias to a domain, the scaling rules of the deployment that was previously located behind that alias are assigned.

What do you need to do is `now scale my-fake-custom-domain.com` instead of `now scale fake-alias.now.sh` in order to prevent it.
