### ISSUE TITLE
Docker deployment slot config CPU not affecting performance

### ISSUE THREAD

**Issue by Strernd** [vercel/vercel#1543]
I did a little benchmark script and deployed it with "c.125-m512" and "c1-m4096" for the slot parameter. The script calculates the 41. fibonacci number recursive and returns the time (ms) needed. 
I'd expect, that the deployment with c1 is 8 times faster as c.125, but it's both the same.

You can find the deployments here and test it:
https://zeit.co/bernd-strehl/zeit/pjqyjsemcj/source?f=now.json
https://zeit.co/bernd-strehl/zeit/ivbfzsopcm/source?f=now.json

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
