### ISSUE TITLE
Feature request: auto alias after automated delivery from github pull request

### ISSUE THREAD

**Issue by xiechao06** [vercel/vercel#1544]
When auto deployment completed when merging a pull request, I must run "now alias" on my local machine to alias my domain to the newly generated domain. 
I wish if now.json contains alias field, "now alias" will be executed automatically after auto deployment. Thanks!

**Comment by javan** [comment]
Yes please ☺️

**Comment by scabfos** [comment]
Yes please, I find this a must! 😍

**Comment by somarlyonks** [comment]
(If you are deploying npm or static)Add this to `package.json` scripts:

```bash
"deploy": "now [-args] | now alias $(cat) <your alias>",
```
And depoly with `npm run deploy`.

**Comment by joecohens** [comment]
In case you missed it, we already support auto aliasing from our GitHub integration! 😄More information here: https://zeit.co/blog/every-push-now
