### ISSUE TITLE
Add "list" property to now.json

### ISSUE THREAD

**Issue by leo** [vercel/vercel#155]
For passing flags to the `list` command that gets executed on the server

**Comment by rauchg** [comment]
-1

**Comment by leo** [comment]
@rauchg Then we at least need a `now` flag for `--single` of `list`. I really don't want people to create a entire file just for that. Especially because this file within `./dist` gets lost each time you re-build your project (usually, because the dir gets cleaned up).

This basically means you would have to create a new `package.json` each time you make changes to your project (because you might want to spawn a new deployment to see how these changes look on production, or to share them with others).

`--single` in `now` could basically be an alias for: 

1. Force `--static`
2. Use `list -s ./content` instead of `list ./content`

**Comment by rauchg** [comment]
I think it's ok for people to use `list` in `package.json` `start` for advanced scenarios, such as passwords. We should document it. 

I don't want to make anything about static file serving specific to a module like `list`. `list` is simply _our_ suggestion / implementation. Configuration also only gets you _so far_. Then people will want the password to only apply to a certain sub-directory… custom servers and code is the real solution.

**Comment by leo** [comment]
@rauchg I completely with agree with what you've just said. But serving single page applications is NOT an advanced scenario, if you ask me. It's basically what the majority of users are using the static feature of `now` for.

Like I said, that's completely fine for advanced scenarios. But really, we cannot ask people to throw a new `package.json` into their `./dist` dir EACH TIME they made changes and want to deploy them.

https://zeit-community.slack.com/archives/now/p1480844031000025

**Comment by leo** [comment]
or WE will have to write a package that automates this.

**Comment by leo** [comment]
👌 

Build in `build`, then `list ./dist -s` in `start`.
