### ISSUE TITLE
Error generating a certificate

### ISSUE THREAD

**Issue by alexverdaguer** [vercel/vercel#1550]
<img width="722" alt="errors" src="https://user-images.githubusercontent.com/8429850/44581408-da5c8280-a79d-11e8-9c48-9fb446ce11d7.png">
Hi,

I have different apps pointing to different subdomains. Everything was working fine till yesterday.

Now 2 subdomains don't work  "ERR_SSL_PROTOCOL_ERROR".

I tried to create the alias again but it gets an error while generating the certificate...

Subdomains : 
- www.espiroflex.com & clientes.espiroflex.com don't work 
- admin.espiroflex.com do work.

All 3 subdomains have CNAMEs pointing to alias.zeit.co

Please need a solution.

thank you !

**Comment by javivelasco** [comment]
Solved. Check the [answer here](https://spectrum.chat/?t=e621f61c-25bb-4058-bd27-d2747d4e1e11)
