### ISSUE TITLE
now alias triggers an error: Maximum number of concurrent instances exceeded

### ISSUE THREAD

**Issue by ericmasiello** [vercel/vercel#1553]
I keep getting this error everytime I run `now alias`

```
synbydesign (master)$ now alias
> Assigning alias synbydesign.com to deployment synbydesign-rdkjtmuoct.now.sh
> Error! An unexpected error occurred in alias: Error: Maximum number of concurrent instances exceeded 21/20 (400)
    at responseError (/snapshot/repo/dist/now.js:2561:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

I was on version 11.4.??? and tried switching to the latest 12 canary version (12.0.0-canary.78) to see if that helped. I get the same error in both cases.

If it helps, this is my `now.json` file:

```
{
  "name": "synbydesign",
  "type": "docker",
  "alias": [
    "synbydesign.com",
    "www.synbydesign.com"
  ],
  "env": {
    "NODE_ENV": "production"
  },
  "scale": {
    "sfo1": {
      "min": 1,
      "max": "auto"
    }
  }
}
```

**Comment by leo** [comment]
This error is intentional. Every plan has an instance limit. In your case, you hit the instance limit of the plan your deployment was created on.

Check out Now 2.0, which completely gets rid of instances 😊 

https://zeit.co/blog/now-2
