### ISSUE TITLE
Error when trying login or deploy on Ubuntu

### ISSUE THREAD

**Issue by viniciusvolpesousa** [vercel/vercel#1555]
When I'm trying to login or doing a deploy using this cli, I'm getting this error:

```
> Enter your email: (here I put my email)
> Error! An unexpected error occurred while trying to log in: invalid json response body at https://api.zeit.co/now/registration reason: Unexpected token A in JSON at position 0
```

**Comment by leo** [comment]
I'm sorry to say that we're currently experiencing issues with our GRU1 datacenter, which is most likely closely located to you.

The team is investigating the issue and working on resolving it.

Until then, using a VPN connection to the US or Germany will help, if you already have an app for that.

We should be fully back very soon!

**Comment by viniciusvolpesousa** [comment]
Thank you @leo for your feedback. I was just testing the platform, I will wait for use that without a VPN.
