### ISSUE TITLE
now alias ignores scaling in now.json

### ISSUE THREAD

**Issue by OlliV** [vercel/vercel#1557]
I have the following scale config in `now.json`:

```
  "scale": {
    "bru1": {
      "min": 0,
      "max": 5
    },
    "gru1": {
      "min": 0,
      "max": 5
    },
    "sfo1": {
      "min": 0,
      "max": 5
    }
  }
```

Then I deploy and alias but the previous deployment was scaled differently. `now-cli` seems to ignore my config and instead copies the scaling config from the previous deployment:

```
> ✔ Scaled 1 instance in sfo1 [1s]
> ✔ Scaled 1 instance in bru1 [1s]
```

**Comment by nonnontrivial** [comment]
Is it that `now alias` is expecting `--rules` and is then falling back to a previous deployment when it does not see them? https://github.com/zeit/now-cli/blob/canary/src/providers/sh/commands/alias/set.js#L83

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
