### ISSUE TITLE
Invalid email address error on initial login

### ISSUE THREAD

**Issue by StephenCleary** [vercel/vercel#1558]
My email address is of the form `first.last@xoxy.net`

It appears that this is rejected by `now`:

```
PS $> now
> No existing credentials found. Please log in:
> Enter your email: first.last@xoxy.net
Invalid email address
```

**Comment by jsbrn** [comment]
I am having the same issue. Email format: `<myemail>@mail.com`.

**Comment by sayanmallick** [comment]
Same here. If you find a solution please inform

**Comment by Vista1nik** [comment]
They validate email by [email-validator](https://npm.im/email-validator)

**Comment by jsbrn** [comment]
Might be good to submit a pull request there, then. I'll have a look later today.

**Comment by leo** [comment]
Thank you! Would be awesome if you could submit a pull request.

**Comment by Vista1nik** [comment]
i'm work on this. 👍

**Comment by leo** [comment]
wow, thank you @Vista1nik! 👏 🙏

**Comment by Vista1nik** [comment]
@leo This problem in Now API, not in CLI.

`/now/registration` Endpoint returns "invalid_email" to some email providers.

**Comment by leo** [comment]
@Vista1nik I see, thanks!

@OlliV and @arunoda please take a look.

**Comment by eliasbutting** [comment]
Right now it doesnt even accept [mail]@gmail.com. Cant create a new account or login to an exisiting one via cli.

**Comment by TooTallNate** [comment]
Closing because this appears to be fixed at this point. I get a message saying to create the account at https://zeit.co first:

```
$ now login
> Enter your email: first.last@xoxy.net
> Error! Please sign up: https://zeit.co/signup

$ now login
> Enter your email: ryan.wans@icloud.com
> Error! Please sign up: https://zeit.co/signup
```

@ryanrocket There is a user account associated with the email address zeit@ryanwans.com. Were you able to get this sorted out after all?

**Comment by hoschi-it** [comment]
This problem still occurs for me trying to register with **xxxxx@web.de**.

**Comment by olegKusov** [comment]
This problem actual for me. Cant login with @yandex.ru

**Comment by mrcnserkan** [comment]
I have the same problem for my ...@email.com address

**Comment by jantonioavalos** [comment]
Same problem. Terminal keeps waiting for confirmation.
I get the email, click at Verify...
And browser tab keeps saying "Verifying". But nothing happens.

(I'm using the same email that I used at my Vercel profile)

**Comment by zerrium** [comment]
I can't signup with @mail.com any fix or solution for this?

**Comment by agamm** [comment]
<mydomain>.dev
doesn't work either.
