### ISSUE TITLE
Now alias is not working

### ISSUE THREAD

**Issue by michaelerobertsjr** [vercel/vercel#1559]
Alias seems to be broken.

I am able to see the deployment listed when I use` now ls` and then when I run `now alias <url>` it gives me an error: ***Error! Couldn't find a deployment to alias. Please provide one as an argument.***

This has previously worked and I can still use `alias ls` and see others.

**Comment by michaelerobertsjr** [comment]
Appears it is now working again.

**Comment by fsiokouros** [comment]
Can you share what you did to solve this issue?

**Comment by jayesh-solutelabs** [comment]
@fsiokouros 

In my case , i have just changed the name in now.json and issue sorted out. (earlier there is another name instead of project name)
