### ISSUE TITLE
Handle not modified error reporting

### ISSUE THREAD

**Issue by sean-roberts** [vercel/vercel#156]
While assigning an alias, it looks like the 409 error conflict of 

{ error: 
   { code: 'not_modified',
     message: 'The domain you are trying to associate is already associated with this deployment',
     uid: '{...myuid}',
     alias: ' ...{alias name}' } }

is not be propagated to the stdout. When I am running into this the current output is:

```
Error! Unknown error: Error: Unexpected error occurred while setting up alias: {"uid":"{...myuid"}
    at Alias._callee5$  ....stack trace
```

I ran across this issue when trying to debug a different issue. Once that was fixed, I started seeing this issue (because the previous deploy worked), causing a red herring and some wasted time.

**Comment by jamo** [comment]
Thanks for the error report, I've just pushed a fix for this and it'll be released shortly.
