### ISSUE TITLE
Provide official docker image

### ISSUE THREAD

**Issue by spawnia** [vercel/vercel#1562]
Hi,

i would like to try using `now`, but want to integrate it as part of my CI pipeline.

For that purpose, i require an image that has the now-cli in it. Would you be willing
to provide this as an alternative installation method?

I can help out with a PR.

Many thanks.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2

**Comment by spawnia** [comment]
@leo This issue still applies. I did read about the new release, and i can not find any mentions of a dockerized `now` cli.
