### ISSUE TITLE
Paid plan - Error: Rate limit exceeded (429)

### ISSUE THREAD

**Issue by LDubya** [vercel/vercel#1563]
I am on the premium paid plan.

Today I tried deploying a new app. The last time I used Zeit now was 17 days ago. I haven't deployed anything since then. Today, on the very first deploy attempt, I got the error message: Error: Rate limit exceeded (429).

```
~/path-to-app now
> Deploying ~/path-to-app under {zeit_username}
> Upload [============--------] 62% 205.3s (73.49MB) [1634 files]> Error! Upload failed
> Error! An unexpected error occurred in deploy: Error: Rate limit exceeded (429)
    at responseError (/snapshot/repo/dist/now.js:2564:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> Upload [===================-] 97% 20.7s (73.49MB) [1634 files]%
```
(fails and quits)

I've tried it two more times and am receiving the same error. 

I am using the latest version of the CLI. I even did npm i -g now to re-download it. I verified I am logged in with now -whoami.

What rate limit have I exceeded? I had only given a single command. I have searched through your documentation at ( https://zeit.co/api#api-basics/rate-limits ) and it mentions a rate limit, but it doesn't give any details for me to try to troubleshoot.

Hopefully this is just a bug, but if it's normal for me to be getting rate-limited just by deploying an app every 17 days or so, I'm really not satisfied with the service.

**Comment by mdugue** [comment]
same here… any news on that?

**Comment by timothyis** [comment]
Hi there, I'm sorry to see this! I'm going to close this issue in favor of #1514, however, since it's the same problem.
