### ISSUE TITLE
New command: retrieve URL or ID given alias

### ISSUE THREAD

**Issue by jamesplease** [vercel/vercel#1564]
:wave: Hi there!

I'm really enjoying using now. One thing I've been thinking about is how to recreate the deployment workflow I've been accustomed to. A tl;dr is two commands:

- deploy an app to an environment, such as "staging"
- move one environment to another, such as "staging" to "production"

The first command can be achieved using something like this:

```
now --public | xargs -I {} now alias {} staging.my-app.com
```

However, I don't think that it is possible to write the second command right now. I would need something like:

`now resolve-alias staging.my-app.com`

which would output either the `.now.sh` URL of the deployment (or its ID). Does something like that exist? If not, would you be open to adding it?

I would use this command for a few other things, too, like scaling back the previous "production" deploy to 0 instances.

Thanks!

---

**Update:** It looks like `now alias staging.my-app.com my-app.com` works to create the "tl;dr" command that I wrote above, but there are other ways I could use getting the ID from an alias; e.g. scaling

**Comment by leo** [comment]
If you run `now alias ls | grep staging.my-app.com` you will find the alias and next to it the URL of the deployment behind that alias!
