### ISSUE TITLE
now docker with --local-config is broken?

### ISSUE THREAD

**Issue by phil-lgr** [vercel/vercel#1565]
![image](https://user-images.githubusercontent.com/9644867/44949297-9cdea180-adfc-11e8-9d29-bfb628c3260b.png)

now version is v11.4.1

.now/.preprod.json
```
{
  "type": "docker",
  "public": true,
  "files": ["dist/", "src/client/nginx.conf", "src/client/mime.types"],
  "name": "preprod",
  "alias": "preprod.enterprise-starter.app"
}
```

when I run `node_modules\.bin\now  --team enterprise-starter --local-config .now\now.preprod.json`

I get 
```
Deploying ~\Documents\Code\enterprise-starter under enterprise-starter
> Error! An unexpected error occurred!
  TypeError: Cannot read property 'length' of undefined
    at readMetaData (C:\snapshot\repo\dist\now.js:18564:30)
    at <anonymous> TypeError: Cannot read property 'length' of undefined
    at readMetaData (C:\snapshot\repo\dist\now.js:18564:30)
    at <anonymous>
```

Was working with previous version.. not sure what's going on..

**Comment by phil-lgr** [comment]
I have two Dockerfiles in my repo:

![image](https://user-images.githubusercontent.com/9644867/44949467-d664dc00-adff-11e8-9744-2b1b49cb62de.png)

Turns out that I need to leave a Dockerfile in the root... the CLI should be tell us what to do?

**Comment by b-barry** [comment]
In the root? What do you mean exactly?

**Comment by phil-lgr** [comment]
Root of the project

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
