### ISSUE TITLE
now.files does not allow overriding node_modules ignore

### ISSUE THREAD

**Issue by jimthedev** [vercel/vercel#157]
In the Alle monorepo style you follow the following structure:

./packages/node_modules/package1
./packages/node_modules/package2

The problem is that now does not follow this same behavior and instead of `/node_modules` being ignored `node_modules/**/*` is ignored. This behavior differs from npm and means that if you have a directory called node_modules anywhere in your codebase, there is no way to override it. You can try to put exact file paths in now.files but it does not actually override the default `node_modules/**/*` ignore rule. Instead, if you run `now -d` you'll see that now is actually just ignoring the directory as if the rule wasn't there.

**Comment by remy** [comment]
I'd like to chime in on this to may offer another perspective where `files` support is useful. 

I have `.env` in my project directory. However, to prevent it from going to github, my `.gitignore` file is:

```
.env
```

However, I need it to go up to my new Zeit instance, so I'd expect to have this in my package:

```json
  "files": [ ".env" ]
```

But the `now` client doesn't seem to respect that logic, and the `.env` file is not included in the deploy.

The only work around I have right now, is an inverse rule in my `.npmignore`:

```
!.env
```

Having this along side the `.gitignore` file does work, and the `.env` _is_ deployed to the instance, but it's pretty confusing (IMHO).

**Comment by jamo** [comment]
Currently it tries to behave just like `npm` when selecting which files to include: https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by remy** [comment]
@jamo indeed, and that does work (you can see my work around using the `.npmignore` file), but it's a bit unintuitive to keep a file out of github but allow through to zeit using two ignore files with inverse rules (if you follow!)

**Comment by leo** [comment]
I see. Let's allow people to overwrite all ignored files (no matter in which config file or property they ignored it) using `files`. Everyone ok with that? 🚀

**Comment by leo** [comment]
@remy Have you tried `now.files` in `package.json`?

**Comment by remy** [comment]
Not now.files, sorry, I didn't even know that was a thing. I can give it a try.

**Comment by leo** [comment]
@remy Cool! Yea, we'll document `now.` in a special place very soon.

**Comment by remy** [comment]
Ah, perfect, well that suits my case.

**Comment by remy** [comment]
@leo just tested - sorry to say that it looks like `.gitignore` has precedence over `now.files`: https://env-uqczpwmdzf.now.sh/_src/?f=package.json&h=216%3B12 you can see there's no `.env` file listed.

**Comment by leo** [comment]
@remy We're going to release support for a separate config file very soon and I'll take a look at this afterwards!

**Comment by slorber** [comment]
hey, just to mention that I tried adding a "./cordova" in my .npmignore (for my usecase, should be added to git, but not sent to zeit)
I'm getting this error in my app: `Uncaught Error: Cannot find module "integration/cordova/clipper"`once deployed to Zeit so it seems Zeit filter also deeply nested folders found in .gitignore while this is unexpected

**Comment by marktrobinson** [comment]
Just to add to this `now.files` inside `now.json` is *not* overriding my `.gitignore`

Here's the scenario

## .gitignore
```
node_modules
dist
```

## now.json
```
{
  "email": "some@email.com",
  "token": "my-token",
  "alias": "my-alias",
  "files": [
    "dist"
  ]
}
```

## Snippet from package.json
```
"scripts": {
    "start": "serve dist",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

`now` will not deploy my `dist` folder.  If I run `serve dist` locally it works correctly, am I missing something obvious here?  I've followed the documentation

**Comment by marktrobinson** [comment]
FYI Future people, the solution was to add an `.npmignore` with:

```
!dist
```

**Comment by shian15810** [comment]
@jimthedev I was able to deploy my app in `/src` with the following `.npmignore`:
```
!/src/node_modules
!/src/node_modules/*
!/src/node_modules/**
!/src/node_modules/**/*
```

**Comment by jacobmischka** [comment]
Because I don't want to permanently change my .npmignore, I'm using this package.json script as a workaround. Might be useful for others.

```
"deploy": "echo '!.env.json' >> .npmignore ; now -e NODE_ENV=production ; sed -i '$ d' .npmignore"
```

**Comment by okeeffed** [comment]
Looks like that same .npmignore fix works the same for .dockerignore for anyone pulling out their hair over now.json for ignored files when using Docker

**Comment by mathiasbynens** [comment]
Got hit by this while trying to deploy a static version of Speedometer, which relies on assets in `node_modules`.

It seems like these ignores shouldn’t even apply for static deployments (i.e. `now --static`).
