### ISSUE TITLE
GitHub Integration for private repository does not work

### ISSUE THREAD

**Issue by Ailrun** [vercel/vercel#1570]
When I try to use GitHub Integration with private repository, it does not make any `checks`.
Is this intended, or is this a problem related with my zeit/now plan?

**Comment by jamo** [comment]
Have you authorized the integration for the private repositories?
You can configure the integration over at https://github.com/apps/now

**Comment by Ailrun** [comment]
@jamo I allowed access to selected repositories only, but those selected repositories include the private repository of this issue.

**Comment by jamo** [comment]
ok, hmm.

Do you have `now.json` in the repository root?

https://zeit.co/blog/now-for-github

**Comment by Ailrun** [comment]
Yes, of course.

**Comment by jamo** [comment]
Can you DM me the repository URL and I'll share the information with the engineers who are working with the integration 
I'm `@jarmo` in zeit.chat - or then you can send us an email to support@zeit.co

**Comment by Ailrun** [comment]
@jamo How? I mean, it's a private repository, so how I can share a link?

**Comment by Ailrun** [comment]
I sent a DM in zeit.chat.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
