### ISSUE TITLE
Rate limit on OSS plan?

### ISSUE THREAD

**Issue by PetrSnobelt** [vercel/vercel#1571]
Hi,
I'd like to deploy a new version of my project under OSS plan as a static site, but I got 
```
Error! An unexpected error occurred!
  Error: Rate limit exceeded (429)
    at responseError (/snapshot/repo/dist/now.js:2561:15)
```
So I delete all previous versions but it doesn't help.

Any suggestion?
Thanks

**Comment by PetrSnobelt** [comment]
OK, it is probably due to bandwidth or storage limit. But the better message would be helpful.

**Comment by PetrSnobelt** [comment]
But on usage dashboard page is:
0 Domains
0 / 3 Instances
74 MB / 1 GB Bandwidth
0 B / 100 MB Logs

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
