### ISSUE TITLE
Get an `Error! The supplied domain is invalid (400)` message when using path alias rules

### ISSUE THREAD

**Issue by zackkrida** [vercel/vercel#1576]
I have a static webapp on one domain `myclient.now.sh`, and a docker install running a graphql server on another `myserver.now.sh`. When I try to run `now -r ./rules.json` on my static webapp deployment with the following rules.json file:

```json
{
  "rules": [{ "pathname": "/graphql/**", "method": ["POST"], "dest": "myserver.now.sh" }]
}
```

 I get the following output:

```
❯ now alias -r ./rules.json
> Assigning path alias rules from ~/my-app-path/rules.json to myclient
> Error! The supplied domain is invalid (400)
```

My domains above are fake, but I am using a now alias for each service.

**Comment by zackkrida** [comment]
This is an issue in both `12.0.0-canary.84` and `11.4.2`

**Comment by jamo** [comment]
You should specify the FQDN to which the path-aliases are applied in the alias command 

`now alias -r ./rules.json my-domain.com`

**Comment by zackkrida** [comment]
That indeed worked -- thanks. Feel free to close this. I didn't see anything about specifying the FQDN in any documentation.

**Comment by jamo** [comment]
cc/ @timothyis

**Comment by jamo** [comment]
@zackkrida would you mind sharing a link to where this is missing?
It seems that we have the domain specified in the examples on the path-aliases feature page: https://zeit.co/docs/features/path-aliases

**Comment by zackkrida** [comment]
i think it must've just been an oversight on my part. I re-read the docs and the announcement i was using and the url is indeed there. Thanks for looking into this!

**Comment by timothyis** [comment]
I'll try to make it more obvious still, @zackkrida. Thanks for the feedback! Sometimes it can be overwhelming reading docs and missing something, so we will try and make it easier to read in future.
