### ISSUE TITLE
'dist'  folder is not deployed via static option

### ISSUE THREAD

**Issue by iclear** [vercel/vercel#158]
i run `npm build` locally, and run `now --static` expecting the index.html and dist folder to be deployed.
likely 'dist' folder is not deployed.

**Comment by leo** [comment]
It might have been ignored in `.gitingore` or somewhere else? Have you read through [this](https://zeit.co/blog/now-static)?

**Comment by iclear** [comment]
that‘s it. thanks, leo.
i forgot the .gitignore file.
