### ISSUE TITLE
Is there an easy way to remove all unaliased instances

### ISSUE THREAD

**Issue by hiddentao** [vercel/vercel#1582]
When I deploy a new instance I usually then set my domain `alias` to point to it. I would then like to easily remove all unaliased instances since they are no longer going to be serving requests. Is there an easy way to do this?

**Comment by mponizil** [comment]
```now rm <app> --safe```

**Comment by hiddentao** [comment]
@mponizil Thanks, but is `<app>` the domain alias or the instance id?

**Comment by mponizil** [comment]
Neither - it's the app name, which I believe comes from `package.json#name` or `now.json#name`.

**Comment by hiddentao** [comment]
Even better, thanks.
