### ISSUE TITLE
now.json is sometimes appended to ~/.now/config.json

### ISSUE THREAD

**Issue by OlliV** [vercel/vercel#1589]
Every now and then when I deploy a deployment that has a `now.json` file the content of the file is appended into my Now config file `~/.now/config.json`.

```
% cat ~/.now/config.json
{
  "_": "This is your Now config file. See `now config help`. More: https://git.io/v5ECz",
  "sh": {
    "user": {
      "uid": "abc",
      "email": "myemail",
      "username": "abc",
      "date": null,
      "avatar": null
    }
  },
  "engines": {
    "node": "`9.4.1"
  },
  "scale": {
    "bru1": {
      "min": 0,
      "max": 5
    },
    "gru1": {
      "min": 0,
      "max": 5
    },
    "sfo1": {
      "min": 0,
      "max": 5
    }
  },
  "type": "docker",
  "features": {
    "cloud": "v2"
  },
  "env": {
    ...
  },
  "alias": [
    ...
  ],
  "name": ...,
  "build": {
    "env": {
      ...
    }
  },
  "limits": {
    "maxConcurrentReqs": 100,
    "duration": 900000,
    "timeout": 900000
  }
}
```

I suspect this might happen when I'm changing between teams because I suppose that's the only time `config.json` is written.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
