### ISSUE TITLE
Next.js v6/7 _app.js causing error when deploying

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#1591]
I've upgraded my app to use v6.1.2 Next.js to use `_app.jsx` so that I can use `next-ga` for Google Analytics. When I deploy I get this error message:

```
{ Error: (client) ./pages/_app.jsx
Module build failed: Error: Cannot find module 'babel-plugin-module-resolver' from '/home/nowuser/src'
```

This problem persists when I use `_app.js` instead of `_app.jsx`.

Upgrading to v7.0.0 gives a slightly different error message:

```
{ Error: (client) ./pages/_app.js
Module build failed (from ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js):
```

Can someone please help with this issue?

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
