### ISSUE TITLE
Error: Service Temporarily Unavailable

### ISSUE THREAD

**Issue by tima101** [vercel/vercel#1593]
Our deployment (https://app1-miphneytdw.now.sh/) was running as expected, then I began seeing errors on logs:

![screenshot from 2018-09-20 10-47-48](https://user-images.githubusercontent.com/10218864/45837347-03503480-bcc4-11e8-853e-a83bcce64e5e.png)

Please advise on how to fix or avoid this error.

**Comment by OlliV** [comment]
What is it trying to request there?

**Comment by tima101** [comment]
@OlliV Based on logs, I would guess it's googlebot trying to access `/robots.txt` but I could be wrong.

When I tried to load any page, I get failed to fetch error and on logs, I get 2 errors: one error described in original comment (see above), second:
```
Error: ENOENT: no such file or directory, stat '/home/nowuser/src/production-server/static/robots.txt'
```

Is it possible that missing `robots.txt` crashes app?

Thanks.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
