### ISSUE TITLE
Deploying subfolders does not respect deployment name in now.json

### ISSUE THREAD

**Issue by programbo** [vercel/vercel#1595]
The issue can be replicated by running `now dist` with the `name` key specified in `now.json` - the deployment will still be called `dist-**********.now.sh`. Explicitly using the `--name` or `-n` flags behaves as expected:

e.g. `now dist -n mkdeck` -> `mkdeck-**********.now.sh`

The issue is exacerbated when following a deployment with `now alias`. The command attempts to use the correct name (from folder or config) and this will fail as the deployment has the wrong name - or worse, alias an old deployment with a matching name.

now.json
```
{
  "name": "mkdeck",
  "alias": "mkdeck.meerkats.cloud"
}
```

chaos
```
> now dist

> Deploying ~/Documents/Experiments/mkdeck/dist under meerkats
> Synced 4 files (417.24KB) [8s]
> https://dist-aqettrmncy.now.sh [in clipboard] [1s] 👈🏼WRONG NAME 🤔
> Deployment complete!

> mkdeck@1.0.0 postpublish /Users/john/Documents/Experiments/mkdeck
> now alias

> Assigning alias mkdeck.meerkats.cloud to deployment mkdeck-zxuipjmdvn.now.sh 👈🏼OLD INSTANCE 😱
> Success! mkdeck.meerkats.cloud now points to mkdeck-zxuipjmdvn.now.sh [4s]  👈🏼 NOT SUCCESS! 😭😭😭
```

**Comment by leo** [comment]
This is working fine since Now 12.0.0!
