### ISSUE TITLE
create-react-app build on now fails

### ISSUE THREAD

**Issue by reflog** [vercel/vercel#160]
Hi. I'm trying to run 'react-scripts build' step in package.json scripts 'now-build' step.
I'm getting the following error:
```
> ▲ npm run now-build
>
>   - index.js:47 Compiler.<anonymous>
>     [src]/[b6a523076d54485fee7b51e624a717feb64ba053]/index.js:47:40
>
> Error Error: Command react-scripts build ended with code 1
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/ace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

Any suggestions on how to handle this?

Thanks in advance!

**Comment by j** [comment]
Hey @jamo @reflog @rase- , I also threw this issue on their repository.

https://github.com/facebookincubator/create-react-app/issues/1185

**Comment by jamo** [comment]
Thanks for reporting this, current workaround is to downgrade `react-scripts` to version `0.7.0`.
We are working on a fix

**Comment by gaearon** [comment]
Just a friendly heads up—we’ll have to temporarily remove the section about Now in User Guide if support is broken so that people don’t waste time on it. Do you have any ETA on the fix? Sorry for being annoying.

**Comment by jamo** [comment]
I'm happy to announce that the underlying issue with `now` has been finally fixed and `react-create-app`s can now again be deployed on now

Demo app here: https://react-create-app-demo-zqahqhmybz.now.sh/ 
and src here: https://react-create-app-demo-zqahqhmybz.now.sh/_src/?f=package.json

Apologies for the radio silence 😅

**Comment by gaearon** [comment]
Thank you so much!

**Comment by kristojorg** [comment]
Hi @jamo I'm still seeing errors trying to deploy create-react-app with now. you can conveniently see the error served here: https://replacement-idrrunzrtn.now.sh/ 😉  thoughts?

**Comment by jamo** [comment]
Based on the error:
```
Failed to compile.

Error in ./src/index.js
Module build failed: Error: EACCES: permission denied, mkdir '/home/nowuser/src/node_modules/.cache'
 @ multi main
```

I'd say it's trying to run the dev server in production?

**Comment by kristojorg** [comment]
Yea it is trying to do that, not sure why though... now should be running the `build` command right?

**Comment by knowbody** [comment]
I also just tried now on `create-react-app` project and it fails with:

```sh
Failed to compile.

Error in ./src/index.js
Module build failed: Error: EACCES: permission denied, mkdir '/home/nowuser/src/node_modules/.cache'
 @ multi main
```

**Comment by jamo** [comment]
It doesn't ship with the a production webserver. And the `start` runs the dev server instead a production useable server...

So to deploy it you'll need to  `npm run build` to generate a minified bundle that may be deployed with ~any web server solution.

And then for example use `serve` to serve that static minified bundle:

`npm i -S serve@3.1.0`

and add `now-start` script:
```
{
  "start": "react-scripts start",
  "now-start": "serve build/",
  "build": "react-scripts build",
  "test": "react-scripts test --env=jsdom",
  "eject": "react-scripts eject"
}
```
Here is a full empty demo app https://react-app-demo-vygvkezcul.now.sh/_src
(that I likely will one day accidentally delete...)

**Comment by knowbody** [comment]
thank you! @jamo

**Comment by DarrylD** [comment]
@jamo works perfect!

**Comment by kristojorg** [comment]
I think this might be outdated, right @jamo ? If you do this now it will deploy as a site with a backing instance running serve, whereas if you just run `yarn build` and then `now` in the `./build` directory, it will serve as a static site over CDN (and not count against your concurrent instances?

**Comment by johhansantana** [comment]
trying to deploy fails at build phase:
```
> Initializing…
> Building
> ▲ npm install
> ✓ Using "yarn.lock"
> ⧗ Installing 15 main dependencies…
> ▲ npm run build
> app-name@0.1.0 build /home/nowuser/src
> react-scripts build
> Creating an optimized production build...
> > Error! The build step of your project failed. To retry, run `now --force`.
```

```
"react-scripts": "1.1.4",
```

**Comment by markozxuu** [comment]
@reflog Hi 😸, I will ignore the ``yarn.lock`` file and try again to deploy.
that should work ❤️

**Comment by markozxuu** [comment]
@reflog If the problem persists, let me know 🙏 😄

**Comment by reflog** [comment]
it's working fine now, thanks
