### ISSUE TITLE
_now TXT Record Deleted, what's my Token ?

### ISSUE THREAD

**Issue by williamleiby** [vercel/vercel#1603]
When attempting to transfer over my domain to Now.sh from Heroku, I was configuring my DNS via Cloudflare and deleted my _now TXT record without realizing the difficulty of getting the token back. I am unable to alias my domain properly and have hit a roadblock. Any help would be greatly appreciated.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
