### ISSUE TITLE
Static type in now.json ignoring .dockerignore?

### ISSUE THREAD

**Issue by fathert0rque** [vercel/vercel#1606]
[I'm following the instructions here](https://zeit.co/docs/examples/create-react-app) to create a static site with a build step. I'm using the standard `create-react-app` boilerplate @ 2.0.2. The problem I'm seeing seems pretty simple and may have a simple answer. I tested it a number of different ways. 

I have copied the Dockerfile from the linked article and it works, except it seems that when `now.type` is set to `static`, `.gitignore` is respected and `.dockerignore` is discarded.

By adding `RUN ls -lha .` to the Dockerfile, I can confirm that this is the case.

When I change `now.type` to `docker`, whitelisting in `.dockerignore` to override `.gitignore` works as expected. This can also be confirmed by inspecting the directory during Docker build. However, by doing this you lose the benefits of having selected `static` as your type. 

This isn't a total showstopper because the app builds properly, but my `.env` file gets discarded by `.gitignore` and prevents `NODE_PATH` from being set along with some other problems. This appears to be because it's in `.gitignore` and can't be whitelisted by `.dockerignore.`

Here is my now.json:
```
{
  "name": "myapp",
  "alias": "mysite.com",
  "dotenv": true,
  "public": false,
  "type": "static",
  "static": {
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

Thanks in advance for any guidance you're able to provide.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
