### ISSUE TITLE
Error: Logs from deployments of your account are rate limited. 

### ISSUE THREAD

**Issue by revskill10** [vercel/vercel#1607]
I got error:

```
Logs from deployments of your account are rate limited. 
The reason is "writes from api-lgbdalnnyp.now.sh". Please upgrade your plan.
```
though i already use `now rm` to remove existing deployments.

I use free plan only to dev and test and i don't want to upgrade the plan.
How to resolve in this case ?

**Comment by tomredman** [comment]
See https://github.com/zeit/now-cli/issues/1169

**Comment by TooTallNate** [comment]
Closing, please refer to #1169 for the detailed information.
