### ISSUE TITLE
Feature request: Auto-remove unaliased deployments on PR with github integration

### ISSUE THREAD

**Issue by codepunkt** [vercel/vercel#1608]
At the moment, using the `OSS` pricing model, it is not possible to sustain automatic deploys via github integration.

It would be great if we could configure github integration to automatically `rm --safe --yes` all unaliased deployments on a new deployment. I know and understand that this would mean having only the latest PR as a deployment at a time. For our purposes, that is way better compared to having the first n PRs available as a deployment and failing all others afterwards without manually removing the unaliased ones.

I tried `rm --safe --yes` in `now-build` script, but that obviously wont work as i don't have auth specified. Would it be possible (and secure?!) to add an auth token as a secret, use that as an environment variable and then using that as a `rm --safe --yes --token $ENV_VAR` inside of `now-build`?

Any help is appreciated!

**Comment by leo** [comment]
With Now 2.0 (https://zeit.co/blog/now-2), there is no reason to remove old deployments anymore. In turn, I'm closing this issue! 😊
