### ISSUE TITLE
Feature Request: Additional Files

### ISSUE THREAD

**Issue by zachinglis** [vercel/vercel#1609]
I want to upload specfic files, despite the fact they're ignored by my Git repo. Gatsby for example is set up to use scoped environment variables. `env.development.json` and read from them 

There's two ways I can see to do this; Have a default keyword to include original.
```
files: [
  DEFAULT, .env.staging
]```

or a seperate `extraFiles` keyword.

Opinions? User error and actually already achievable?

**Comment by leo** [comment]
As of Now CLI 12.0.0, we do not respect `.gitignore` anymore. In turn, this is not a problem anymore.

Please consider using `.nowignore` (same syntax as `.gitignore`).
