### ISSUE TITLE
call docker executable from npm script

### ISSUE THREAD

**Issue by chuongnh3atgmaildotcom** [vercel/vercel#1620]
I'm trying to deploy vue-storefront to now. It required a nodejs server as frontend (listening 3000) and a docker container as backend (listening 8080). 

  The doc said that now can build image and start container if it detect dockerfile. But I need to call docker executable from npm script, and I can't.

  e.g. in "now-build" script (using https://github.com/shelljs/shelljs)
> shell.exec(\`docker run -d  -l "label.vuedeploy=app"  --network=vue-storefront-api_default  -h app -p 8080:8080 -v $(pwd)/var:/var/www/var --name vue-storefront-api_app_1 vuedeploy_api\`)

and output:

> 
> /bin/sh: docker: not found
> exec: /bin/sh: docker: not found

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
