### ISSUE TITLE
Can't deploy nodejs app (videochat using SimpleWebRTC)

### ISSUE THREAD

**Issue by edparra21** [vercel/vercel#1621]
Hello, sorry if this has been asked before, but i can't find any topics about it.

I'm following a tutorial about developing a video chat using Webrct dependecies, and everything works fine locally, but to finally test it out I need to upload it to a server to make p2p connection. The issue is that after trying to deploy the project, the build fails. this is a screenshot of the process:
![image](https://user-images.githubusercontent.com/42215666/47119433-78b21500-d230-11e8-927a-27899f228ec8.png)
Hope you can help me.

**Comment by edparra21** [comment]
after `>Skip Install` goes the Error:
`Error! Build Failed`

and thats it. am i missing somenthing?

**Comment by jamo** [comment]
Does the package always assume TTY (and fails to check if it's run interactively or not)

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
