### ISSUE TITLE
Can you reduce the number of retries?

### ISSUE THREAD

**Issue by steven10172** [vercel/vercel#1622]
Currently the number of retries for the download that kicks off on post-install if really high. Can you reduce this to a smaller number? Currently, in CI network jailed environment, it takes forever to fail the installation and to unsuspecting users, it looks like their build has hung.

By default `async-retry` uses a value of 10, is there a specific reason you've set it to 500?

https://github.com/zeit/now-cli/blob/39fffe6874e5e2fbd5887150bb8601d060066709/download/src/index.js#L136

**Comment by leo** [comment]
@igorklopov

**Comment by leo** [comment]
We are going to replace Webpack with Rollup soon. That PR will also include a fix for this.
