### ISSUE TITLE
Creact React App (SPA) - rewrites doesn't work

### ISSUE THREAD

**Issue by wishfulthinkerme** [vercel/vercel#1623]
Hey,
I am deploying the app successfully, but it seems that rewrites don't work at all.

```
{
  "name":"mybestsystem-system",
  "alias": "system.mybestsystem.app",
  "type": "static",
  "public": true,
  "static": {
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```
_*mybestsystem is fake name here._

When I reach **system.mybestsystem.app** everything works fine, routing is perfect. When I reach e.g. **system.mybestsystem.app/my-best-route** and refresh I got **404 | requested path could not be found**. 

This is standard create-react-app with routing. Not sure what is wrong. I've followed the docs https://zeit.co/docs/examples/create-react-app#instructing-the-build.

Anyone already solved it?

Best Regards

**Comment by ivan-navarro-75** [comment]
same issue here, have you find the way to fix this?
thx!

**Comment by zd333** [comment]
Also experiencing the issue.
Looks like platform ignores `rewrites` setting of `"type": "static"` mode.

**Comment by wishfulthinkerme** [comment]
Yes, It seems like this config works correctly. I believe you must add `"public": "build"` to **"static"**.
Please let me know if that works for you
 
```
{
  "name":"xxx",
  "alias": "xxx.xxx",
  "type": "static",
  "public": true,
  "static": {
    "public": "build", 
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

**Comment by ivan-navarro-75** [comment]
now it is working, thanks @wishfulthinkerme

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
