### ISSUE TITLE
Setting environment variables in now.json not working as expected

### ISSUE THREAD

**Issue by jsbrn** [vercel/vercel#1625]
I don't know if there is something I am missing but unless I specifically set the environment variables when I deploy manually, they won't be defined in Node when the app is started.

**Comment by DagAgren** [comment]
I think I'm having the same problem, but in the desktop app where I don't think you can even set environment variables. Deployed code just does not work as it has no env variables with secrets.

**Comment by jsbrn** [comment]
For now, my workaround is to just run a batch file.

`now -e MONGODB_USERNAME=@mongodb_username -e MONGODB_PASSWORD=@mongodb_password`

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
