### ISSUE TITLE
4 minute gap in build output

### ISSUE THREAD

**Issue by kevinburke** [vercel/vercel#1628]
We run `now web ...` from a CircleCI environment. The client reported a timeout for a recent deployment:

```
> [4/4] Building fresh packages...
> Done in 45.34s.
> ▲ npm run now-build
> 
> web@1.0.0 now-build /home/nowuser/src
> 
> built on ci
> ▲ Snapshotting deployment
> ▲ Saving deployment image (110.8M)
> Build completed
> Verifying instantiation in sfo1
> Error! Instance verification timed out (3m)
> Read more: https://err.sh/now-cli/verification-timeout
Exited with code 1
```

However, the server logs indicate that the build completed successfully.

```
10/23 09:04 AM (1h) [4/4] Building fresh packages...
10/23 09:04 AM (1h) Done in 45.34s.
10/23 09:04 AM (1h) npm run now-build
10/23 09:04 AM (1h)
10/23 09:04 AM (1h) > web@1.0.0 now-build /home/nowuser/src
10/23 09:04 AM (1h) > echo 'built on ci' 
10/23 09:04 AM (1h)
10/23 09:04 AM (1h) built on ci
10/23 09:04 AM (1h) Snapshotting deployment
10/23 09:05 AM (1h) Saving deployment image (110.8M)
10/23 09:09 AM (1h) npm run now-start
10/23 09:09 AM (1h)
10/23 09:09 AM (1h) > web@1.0.0 now-start /home/nowuser/src
10/23 09:09 AM (1h) > NODE_ENV=production WEB=true node build/router/index
10/23 09:09 AM (1h)
10/23 09:09 AM (1h) Web is ready!
```

There are a few concerning things here:

- how or why is the client timing out if the build actually succeeded? This seems like it could lead to problems; imagine this sequence:

1) I start deploy
2) I realize code being deployed has an error
3) I read that client says build timed out
4) Deployment actually succeeds, faulty code pushed to production, I take no action to mitigate because of (3).

- Why was there a 4 minute gap between "Saving deployment image" and "npm run now-start"?

Happy to send the exact deployment URL and team name in private messages.

**Comment by kevinburke** [comment]
@bijection @antimatter15 @carlpeaslee

**Comment by kevinburke** [comment]
Just hit another one, on this one, `npm run now-start` runs twice for some reason. I am not sure what this implies for the reliability of the server, or whether this is an error on our end or yours.

```
10/23 11:27 AM (14m) Done in 41.32s.
10/23 11:27 AM (14m) npm run now-build
10/23 11:27 AM (14m)
10/23 11:27 AM (14m) > web@1.0.0 now-build /home/nowuser/src
10/23 11:27 AM (14m) > echo 'built on ci' 
10/23 11:27 AM (14m)
10/23 11:27 AM (14m) built on ci
10/23 11:27 AM (14m) Snapshotting deployment
10/23 11:28 AM (13m) Saving deployment image (110.9M)
10/23 11:31 AM (10m) npm run now-start
10/23 11:31 AM (10m)
10/23 11:31 AM (10m) > web@1.0.0 now-start /home/nowuser/src
10/23 11:31 AM (10m) > NODE_ENV=production WEB=true node build/router/index
10/23 11:31 AM (10m)
10/23 11:31 AM (10m) Web is ready!
10/23 11:33 AM (8m) npm run now-start
10/23 11:33 AM (8m)
10/23 11:33 AM (8m) > web@1.0.0 now-start /home/nowuser/src
10/23 11:33 AM (8m) > NODE_ENV=production WEB=true node build/router/index
10/23 11:33 AM (8m)
10/23 11:33 AM (8m) Web is ready!
```

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
