### ISSUE TITLE
remove command confuses app named 'help' for the flag '--help'

### ISSUE THREAD

**Issue by chrstphrknwtn** [vercel/vercel#1631]
I have an app named 'help' (perhaps foolishly), and I am not able to clean up previous deployments using `now rm help -s -y` because the remove command interprets the named app 'help' as shorthand for `--help`.

Expected behaviour is that the given app name is respected regardless of similarity to flags. The `now ls` command works as as expected.

**Works** (lists all deployments for app named 'help')
````shell
now ls help
````

**Fails** (erroneously shows help for remove command)
````shell
now rm help
````

**Comment by chrstphrknwtn** [comment]
Additionally, using quotes `now rm 'help' -s -y` also fails.

Have attempted in `bash` and `zsh`.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
