### ISSUE TITLE
now secrets add doesn't allow "/"

### ISSUE THREAD

**Issue by tkloht** [vercel/vercel#1633]
i'm trying to add a secret as follows: 

```
❯ now secrets add test/test/test "heyheyhey"
> Error! Only alphanumerics and `/ . _ -` are allowed as `name`
```

it does work when using dots or backslash though

```
now secrets add test\testtest "heyheyhey"
```

**Comment by tkloht** [comment]
actually when using a backslash the command doesn't show an error, but the backslash will just be removed.

**Comment by robertgrzonka** [comment]
> actually when using a backslash the command doesn't show an error, but the backslash will just be removed.

![zrzut ekranu 2018-11-9 o 13 20 20](https://user-images.githubusercontent.com/35585466/48262313-5459ea80-e422-11e8-9e37-123b61768b35.png)

Maybe this could help in some way?

**Comment by tkloht** [comment]
No, that doesn't address this issue because i am not talking about the value but the name of the secret.
I do not need slashes, or at least it is not important to me. However the error message (see initial bugreport) clearly states that `Only alphanumerics and / . _ - are allowed as name` which is not correct.

For me personally it would be fine to just adjust the error so that it lists the actually possible characters which can be used in the name.

**Comment by TooTallNate** [comment]
Thank you @tkloht, the error message from the API has been adjusted according to your suggestion:

```
$ now secrets add test/test/test "heyheyhey"
> Error! Only alphanumerics and `. _ -` are allowed as `name`
```
