### ISSUE TITLE
now scale instance made 2 times more instance

### ISSUE THREAD

**Issue by eyexx** [vercel/vercel#1635]
When I run command ```   now scale  https://mysite.now.sh 1 3```,
it scaled ``` min: 2, max: 6```.

However, in [readme](https://zeit.co/docs/getting-started/scaling), it says that 
when we run command like ``` npx now scale  https://mysite.now.sh 2 15 ```,
it scaled ```min: 2, max: 15```.

Is the readme wrong?

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
