### ISSUE TITLE
Running single-instance in V2

### ISSUE THREAD

**Issue by LDubya** [vercel/vercel#1639]
Hi Zeit,

I see that in V2 you’ve removed “now scale”.

So how do we keep a deployment to a single instance now?

It’s fairly common for people to have scheduled tasks / cron jobs running on an instance as a microservice. We need to be able to keep those instances down to 1. They should never scale. The reason is that if you have the same scheduled tasks running on multiple instances they will execute multiple times, when they should only execute once. 

I’d like to upgrade to V2 but I need to know how to ensure that for a specific project it will stay at 1 instance and never scale up instances.

See the following issue if it helps explain the use case:

https://github.com/zeit/now-cli/issues/1539

**Comment by leo** [comment]
This feature is not yet implemented. In the future, there will most likely be a configuration property for preventing Lambdas from freezing. But for now, the feature is still in the works.

**Comment by TooTallNate** [comment]
Closing because keeping Lambdas alive forever basically defeats the point of Lambdas, which is to be running on-demand.

**Comment by LDubya** [comment]
> Closing because keeping Lambdas alive forever basically defeats the point of Lambdas, which is to be running on-demand.

@TooTallNate you closed without addressing the spirit of the question. What is the best practice for running scheduled tasks on now v2? Nobody has answered this question. Everyone said it would be supported in the future, including responses on this thread and the one I'm linking to below, but as of today there is no real answer.

See: https://spectrum.chat/zeit/general/in-v2-how-can-you-keep-a-node-server-cron-job-alive~18dc0165-507f-4d1e-874a-77d0bbafe20a

How is this resolved?

**Comment by leo** [comment]
@LDubya Sorry for the inconvenience that was caused.

With regards to your question: At the moment, we unfortunately don't support scheduled tasks on Now 2.0 yet. For that, you will need to use Now 1.0 or a third party service that then invokes your Now 2.0 deployments in a scheduled manner.

We'll be sharing more details on our [Twitter channel](https://twitter.com/zeithq) about this feature, once it's ready. Stay tuned!

**Comment by glococo** [comment]
Hi,
I face a similar issue with a webRTC rest API.

I can't save few signal webRtc data because the next peer could not connect to the same instance. Thus leaving two clients connected to 2 different instances for sharing few signal bytes.
At this point, I have only one option, use a database, which result in a waste of resources to just forward few vars.

Please, I beg you. Consider it.
I need to limit the running instances to max-one.

Thanks
