### ISSUE TITLE
V2 routes not working

### ISSUE THREAD

**Issue by KidkArolis** [vercel/vercel#1640]
I have the following `now.json`:

```json
{
  "version": 2,
  "builds": [
    { "src": "server/index.js", "use": "@now/node-server" },
    { "src": "package.json", "use": "@now/static-build" }
  ],
  "routes": [
    { "src": "/api/unicorn", "dest": "server/index.js" }
  ]
}
```

After deployment:

* accessing `/server/index.js` gives express's `Cannot GET /server/index.js`
* accessing `/api/unicorn` gives now's `404: The page could not be found`

Locally, I can hit `/api/unicorn` on that node service and it works.

What am I doing wrong?

**Comment by rauchg** [comment]
Note that Express is thinking that your incoming route is `/server/index.js`. You should look into adding a middleware that strips the path?

**Comment by KidkArolis** [comment]
Apologies for an unclear bug report. Also, congrats on launching V2!

Here's a more detailed explanation.

## Steps to reproduce

https://github.com/KidkArolis/now-routing-issue

    $ git clone git@github.com:KidkArolis/now-routing-issue.git
    $ now

## What I expected?

Visiting `/api/unicorn` would connect to `server.js` lambda preserving the request url so that express could do the route matching. I thought this is what the routes config is for:

```
"routes": [
    { "src": "/api/unicorn", "dest": "server.js" }
]
```

## What happens instead?

Visiting https://now-routing-issue-brg7t6b2i.now.sh/api/unicorn just returns 404:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/324440/48302651-124ea880-e4f7-11e8-817d-72d87720a03d.png">

It's as if the route `/api/unicorn` is not matched at all?

---

I understand that you encourage using `@now/node` and I understand the disadvantages of using express here. It's just not clear to me why the route `/api/unicorn` doesn't seem to hit my server.js at all. If this is not supported, then I don't quite understand the purpose of `@now/node-server`.

**Comment by KidkArolis** [comment]
Btw, this isn't specific to `@now/node-server`, the routing doesn't work with `@now/node` either:

```
//server.js

module.exports = (req, res) => {
  res.end(`Hello from Node.js on Now Lambda!`);
};
```

```
// now.json
{
  "version": 2,
  "builds": [
    { "src": "server.js", "use": "@now/node" }
  ],
  "routes": [
    { "src": "/api/unicorn", "dest": "server.js" }
  ]
}
```

```
GET /server.js –> works
GET /api/unicorn –> 404
```

**Docs:**
<img width="397" alt="image" src="https://user-images.githubusercontent.com/324440/48302760-876ead80-e4f8-11e8-93ed-61ed05a7c82f.png">

**Comment by KidkArolis** [comment]
OK! I found @rauchg's post on Spectrum with the express example.

What I was doing wrong was ommiting `/`, i.e.:

```diff
-{ "src": "/api/unicorn", "dest": "server.js" }
+{ "src": "/api/unicorn", "dest": "/server.js" }
```

Phew... I think I got confused because in builds you define it as `"src": "server.js"` without the slash.

But I get it now that the routes are mapping full URL paths to others. Maybe a warning should be printed since all URLs would have to start with `/` in dest?

**Comment by doprdele** [comment]
Is this possible?

```json
{
    "version": 2,
    "name": "proxywow-delivery",
    "builds": [
        { "src": "next.config.js", "use": "@now/next" },
        { "src": "./api/index.js", "use": "@now/node" }
    ],
    "routes": [
        { "src": "/", "dest": "/api/index.js" },
        { "src": "/next", "dest": "/next.config.js" }
    ]
}
```

 I want a next app served at /next and an index.js served at /

**Comment by doprdele** [comment]
Tried that, doesn't appear to be working.

```
{
    "version": 2,
    "name": "proxywow-delivery",
    "builds": [
        { "src": "next.config.js", "use": "@now/next" },
        { "src": "api/index.js", "use": "@now/node"}
    ],
    "routes": [
        { "src": "/abcd", "dest": "/next.config.js"},
        { "src": "/", "dest": "/api/index.js"}
    ]
}
```

The '/' route successfully goes to the /api/index.js function , but, whereas the Next code works locally, it results in a 404 when I go to 

https://proxywow-delivery-qsisfmawt.now.sh/abcd

**Comment by dbauszus-glx** [comment]
Can't get routes to work for static files neither.

```
  "builds": [{
    "src": "serverless.js",
    "use": "@now/node-server",
    "config": { "maxLambdaSize": "50mb" }
  },{
    "src": "./public/*/**",
    "use": "@now/static"
  }],
  "routes": [{
    "src": "/dev/(css|js)/(.*)",
    "dest": "/public/($1)/($2)"
  },{
    "src": "/dev(.*)",
    "dest": "serverless.js"
  }]
```

/dev hits my servless.js lambda.

/public/css/desktop.css returns my css.

but /dev/css/desktop.css => 404

**Comment by unitof** [comment]
I cannot get _any_ routes to work using `@now/static`.

File structure:
```
now.json
index.html
style.css
```

`now.json`
```
  ...
  "builds": [
    {
      "src": "**/*",
      "use": "@now/static"
    }
  ],
  "routes": [
    {
      "src": "/(.*)",
      "dest": "/test"
    }
  ]
```

In theory this should break everything and redirect all traffic to non-existant `/test`, but instead the site continues working as expected (loading `index.html`) on both `now dev` and when deployed.

**Comment by LexSwed** [comment]
same for me, "routes" just ignored. deployed my app with it and without, still doesn't do basically same as comment on top.
I thought they have some validation and ignore incorrect routes, but there is nothing in logs, so

**Comment by TooTallNate** [comment]
Hey @LexSwed, what version of now-cli are you using? Can you provide a repo demonstrating the issue that you are having? Thank you!

**Comment by LexSwed** [comment]
Hey man, sorry for this, it was late night and I messed up the setup.
Basically I had this:
```
// now.json
{
  "version": 2,
  "name": app,
  "builds": [
    // ...api
    {
      "src": "client/package.json",
      "use": "@now/static-build", // gatsby
      "config": { "distDir": "public" } // relative to `client/package.json`
    }
  ],
  "routes": [
    // api
    {
      "src": "/(.*)",
      "dest": "client/public/$1" // here is the mistake, should be just `client` because of `distDir`?
    }
  ]
}
```
Had to check what's up with the filesystem. It always showed my filesystem on root route `/` with my folders, whether I provide `routes` or not, that's why I thought it's ignored. but `"dest": "client/$1"` fixed the issue. Still not obvious how it all works together in one setup file

**Comment by TooTallNate** [comment]
Yes, `"dest": "client/$1"` is the correct syntax.

This is because the static files generated into the `public` dir are actually _served_ from the directory relative to the `package.json` file. This is a bit more natural because consider the case where you had a root-level `package.json` (so no `client` dir). By serving the files relative to the `package.json` file, there would be no need to use `routes` so the configuration is simpler. Otherwise _every_ use of the `@now/static-build` builder would require defining `routes` that map into the `distDir` and that would be quite repetitive.

Hope that explains things for you! If you still are having troubles please create a new issue.
