### ISSUE TITLE
Example of how to use @now/lambda builder?

### ISSUE THREAD

**Issue by i8ramin** [vercel/vercel#1643]
Hi, I am trying to use an actual lambda function (ie, https://github.com/prisma/graphql-yoga/tree/master/examples/lambda), but not sure how to implement it using the documented v2 builders. Noticed that there is a `@now/lamda` package, but no docs about it. Not sure if im on the right path or not, but could use some help!

I created a sample repo here to try a few things out:
https://github.com/i8ramin/graphql-now-lambda-test

Trying to use the `@now/lambda` builder, I get the following error:
```
{ Error: Handler not found in config
    at Object.exports.build (/tmp/utils/build-module/node_modules/@now/lambda/index.js:18:30)
```

But not sure how to pass the `handler` into the builder. Looking at the source code (https://github.com/zeit/now-builders/blob/master/packages/now-lambda/index.js#L8), it seems that it is trying to read that info from the `entrypoint`. Does `entrypoint` in this context map to the value defined in **"src"** under the `builders` key in `now.json`? If so, I tried setting **"src"** to `"src": "handler.js!handler=handler!runtime=nodejs8.10"`, but getting the following error:

```
> Error! One or more build specification(s) were not referenced
```

**Comment by leo** [comment]
@igorklopov

**Comment by i8ramin** [comment]
Hi. Any updates on this? Thanks

**Comment by leo** [comment]
Thank you for creating this!

As part of our strategy of reducing down the platform to "zero config" (no configuration at all) and being more focused on a frontend that is powered by a simple serverless function, we have decided to deprecate the @now/lambda Builder.

**Comment by vzaidman** [comment]
instead of this comment, opened a new issue #2790
