### ISSUE TITLE
default.cow not found when running now/node tutorial

### ISSUE THREAD

**Issue by codeallthethingz** [vercel/vercel#1645]
Going through the set up steps here: https://zeit.co/docs/v2/deployments/official-builders/node-js-now-node#when-to-use-it

But getting the following from my now deployment logs and a 502 from the running instance:
https://temp-imxkpb08t.now.sh/api/cowsay/?text=aoeu

```
Error: ENOENT: no such file or directory, open '/var/task/user/api/cows/default.cow'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at Object.get (/var/task/user/api/cowsay/index.js:1:3111)
    at doIt (/var/task/user/api/cowsay/index.js:1:3949)
    at say$1 (/var/task/user/api/cowsay/index.js:1:3753)
    at Server.cowsay_1 (/var/task/user/api/cowsay/index.js:1:4247)
    at emitTwo (events.js:126:13)
    at Server.emit (events.js:214:7)
    at parserOnIncoming (_http_server.js:619:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
```

Expected to see the cow output.

<img src="https://assets.zeit.co/image/upload/v1541535420/front/docs/official-builders/serverless-cowsay-text.png"/>

**Comment by leo** [comment]
@timothyis

**Comment by timothyis** [comment]
Hi @codeallthethingz and @liudonghua123! Would mind trying the most update to this example? It should have fixed this issue! https://zeit.co/docs/v2/deployments/official-builders/node-js-now-node 🙏

**Comment by liudonghua123** [comment]
@timothyis, Thanks, it's works now.
BTW, I think the documentation is some misleading especially the file structure to the new one, could I make a pr to this documentation (https://zeit.co/docs/v2/deployments/official-builders/node-js-now-node ).

**Comment by liudonghua123** [comment]
However, what's the difference of `const cowsay = require("cowsay/build/cowsay.umd.js").say;` and `const cowsay = require("cowsay").say;`, I tried locally, find nothing difference.

![image](https://user-images.githubusercontent.com/2276718/48452483-445b5580-e7ea-11e8-9691-307f7a80d425.png)

Here (https://github.com/piuccio/cowsay#usage-as-a-module) is the cowsay documentation which use `var cowsay = require("cowsay");`

**Comment by codeallthethingz** [comment]
Thanks for the speedy turn around @timothyis !
