### ISSUE TITLE
Behaviour of v1 --dotenv flag changed without notice

### ISSUE THREAD

**Issue by te-online** [vercel/vercel#1646]
In 11.4.6 it is enough to run `now --dotenv` to also upload a `.env` file with the deployment.
In 12.0.1 the help text still states 

`-E FILE, --dotenv=FILE         Include env vars from .env file. Defaults to '.env'` 

However, it throws an error complaining about that I need to provide a value to that flag (although it has a default value).

**Comment by leo** [comment]
Thanks for reporting this. It should definitely not happen. Releasing a fix in a moment!

**Comment by te-online** [comment]
Thanks a lot 🎉

**Comment by jasonnutter** [comment]
Working on confirming this (12.1.5), but it does appear that not providing a value for the `-E/--dotenv` flag does not result in a `.env` file being parsed by the CLI.

**Comment by te-online** [comment]
@jasonnutter Uh, my mistake: After version 12 didn't work, I set our CI system to always use a fixed, known to work, 11 subversion. Now I changed it to the latest 12.1.11 and it doesn't seem to transfer the `.env` file. Could you have one more look at it, @leo.
