### ISSUE TITLE
now, monorepo and lerna.js compatibility

### ISSUE THREAD

**Issue by armandabric** [vercel/vercel#1663]
To help people to use monorepo with now.sh, it could be a good feature to detect a `lerna.json` file and to run `lerna bootstrap` instead of `npm install` (or `yarn install`)

What did you think?

**Comment by leo** [comment]
Sounds like a great idea! But for this, a separate Builder should be created.

Maybe you want to call it `now-lerna`? 👍 

https://zeit.co/docs/v2/deployments/builders/overview#when-to-use-builders
