### ISSUE TITLE
ENOSPC: no space left on npm / yarn install

### ISSUE THREAD

**Issue by nitzano** [vercel/vercel#1664]
## Description

When trying to deploy a yarn workspace monorepo I receive `"ENOSPC: no space left on device, write"` (free plan) when just installing dependencies:

```
11/15 10:53 AM (4h)
installing to /tmp/252defbc/user/packages/enum-server-api
11/15 10:53 AM (4h)
yarn install v1.12.3
11/15 10:53 AM (4h)
[1/5] Validating package.json...
11/15 10:53 AM (4h)
[2/5] Resolving packages...
11/15 10:53 AM (4h)
[3/5] Fetching packages...
11/15 10:53 AM (4h)
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
11/15 10:53 AM (4h)
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
11/15 10:53 AM (4h)
[4/5] Linking dependencies...
11/15 10:53 AM (4h)
error Could not write file "/tmp/252defbc/user/packages/enum-server-api/yarn-error.log": "ENOSPC: no space left on device, write"
```

Is there any limitation regarding dependencies size or working with monorepos?

## How to reproduce 
To reproduce you can simply try to deploy this branch:

https://github.com/nitzano/enum-server/tree/now_deploy

My `now.json` setup:

```
{
  "version": 2,
  "name": "enum-server",
  "builds": [
    {
      "src": "packages/enum-server-api/package.json",
      "use": "@now/node-server"
    }
  ]
}

```

**Comment by leo** [comment]
Thank you for reporting this. I have created an internal task, so that we're gonna show a much better error message than this one.

However, I'm also closing the issue as this disk size limit is actually intentional: For now, only up to 500mb of dependencies can be installed while building. Please update your code to use less. 😊

**Comment by MarkLyck** [comment]
I have the same problem, my node_modules folder is 254.5MB...

This is a weird requirement... It doesn't make much sense to limit this anyway? Now is supposed to be acceptable to use for large scale production applications. "just don't use dependencies" is not a good answer to this solution...

I'm not going to code something a community of people have already figured out and done well, just to be able to use Now to deploy my applications? Who came up with this requirement??

I'm on a Premium plan by the way.

**Comment by merunga** [comment]
same issue: `node_modules` is 226.1 MB. Going back to V1

**Comment by tylermassey** [comment]
I'm also seeing this issue without hitting the 500mb limit for dependencies. My dependencies are around 290mb.

For what it's worth, a clean install of Create React App w/ TypeScript results in a 240mb `node_modules` folder.

**Comment by yhjor** [comment]
same problem.

I am also on a Premium plan.

**Comment by martindzejky** [comment]
See https://github.com/zeit/now-builders/issues/28. The issue happens when you use `yarn` because it caches the dependencies, which means that they have double the original size.

The solution is to either switch to `npm` or use `"useBuildUtils": "@now/build-utils@canary"` in the Now configuration file. This is a working configuration for me:

```
{
  "version": 2,
  "builds": [
    {
      "src": "package.json",
      "use": "@now/static-build",
      "config": {
        "useBuildUtils": "@now/build-utils@canary"
      }
    }
  ]
}
```

**Comment by NiklasMerz** [comment]
Reduce dependencies is not an option if the app is using Angular. My Angular project with minimal dependencies is just above 500 MB, but I cannot deploy it.

**Comment by MarkLyck** [comment]
Whether (not using Yarn) sort out half of the issue. a 500MB limitation is still just not good enough.

I don't see how now version 2, can ever be taken seriously if it doesn't work, just because one of your dependencies have a massive development bundle inside. This is outside of the single developer or companies' hands. A cap for just 500 MB is not okay for a system that's supposed to be for scalable production applications...

**Comment by JoaoCnh** [comment]
I am using npm and package-lock.json file and yesterday everything was fine and today it always blows up on deployment with 

> ENOSPC: no space left on device, write

**Comment by DanielJackson-Oslo** [comment]
Similar issue. It installs devDep, which I really don't need when deploying to prod.

**Comment by sigo** [comment]
I think it's _fixed_ now official: https://zeit.co/blog/now-builds-faster-safer-better

**Comment by paulogdm** [comment]
It is!

**Comment by ojasuno** [comment]
Error: ENOSPC: no space left on device, write

**Comment by Calandri** [comment]
Error: ENOSPC: no space left on device, copyfile 

What happen?

**Comment by kachkaev** [comment]
I _redeployed build without cache_ and the error was gone. Looks like our error was to do with Yarn / NPM cache growing too big over time. Not sure that the solution is universally applicable, but hope that this helps at least someone!

Got here from a search engine.

<img width="986" alt="Screenshot 2023-01-30 at 14 32 11" src="https://user-images.githubusercontent.com/608862/215505796-eaa5ab34-cad2-4dea-977f-63df04ac7554.png">

**Comment by Yuripetusko** [comment]
We are still getting it building a nx monorepo app every second deploy. Pressing "Redeploy" on vercel always helps

**Comment by mastoj** [comment]
I hit this issue as well. 

@leo, what happened with

> Thank you for reporting this. I have created an internal task, so that we're gonna show a much better error message than this one.

The error message isn't super helpful.

**Comment by Yuripetusko** [comment]
Our issue might be related to nx cache, we will try the fix here and report back

https://github.com/nrwl/nx/issues/10256#issuecomment-1230884787

**Comment by mastoj** [comment]
We are not using nx, and I don't think we have a crazy amount of dependencies. I think we have around 15 direct dependencies and 12 direct dev dependencies. I'm fully aware that there are transient dependencies, but we can't really control that. Of course we can try to rebuild things our self or find different libraries, but that is way to time consuming.

**Comment by mastoj** [comment]
In our case I'm pretty sure it was due to the fact that we generated to many pages during build, removed a lot of them and now things works. Are there any guidelines on how many pages one can generate during build?

**Comment by marysmech** [comment]
I have same problem. We use self-managed gitlab. And deploy runs fine but at the end of the deploy i get this error

```
...
λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)  automatically rendered as static HTML (uses no initial props)
●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
Traced Next.js server files in: 2.244s
Created all serverless functions in: 5.264s
Collected static files (public/, static/, .next/static): 12.584ms
Error: ENOSPC: no space left on device, write
Error: ENOSPC: no space left on device, write
```

I have originally thought that its caused by some of our changes so I tried to redeploy last commit that was successfully deployed and same commit now ends with this error so it seems like some kind of vercel problem.

**Comment by vilkinsons** [comment]
Any further insight on this? Also afflicted (same as Alexander Kachkaev, above).

**Comment by Luwangel** [comment]
Same issue. It happens after I upgrade my app to NextJs v13. It's pretty annoying. Is there any solution?

```
22:43:01.228 | Collected static files (public/, static/, .next/static): 143.753ms
22:43:54.211 | Error: ENOSPC: no space left on device, write
22:43:54.222 | Error: ENOSPC: no space left on device, write
22:43:54.825 | Deployment completed
22:43:54.396 | ENOSPC: ENOSPC: no space left on device, write
```

**Comment by paulogdm** [comment]
@Luwangel @nonparibus please [reach out to our support channels](https://vercel.com/help) or create a [new discussion](https://github.com/vercel/vercel/discussions).

Steps to reproduce are welcome, although I recognize this can be hard as it can be heavily dependent on the codebase. Anyway, let's lock this issue and move the discussion to a better place.
