### ISSUE TITLE
[V2] Now-Cli: V2 still working with Payment Plan of V1

### ISSUE THREAD

**Issue by EduardoHidalgo** [vercel/vercel#1668]
I have a project under platform version 2.0. Nowhere does it say what is the file size limit of my project (unlike version 1 where that limit is mentioned, see images below).

My point and issue is: I assume when i was in platform version 1.0 i have a "File size limit", and if in the new platform version 2.0 doesn't mention it just i don't have "file size limit" what worry about.

I assume i never will see a cli error about "File size limit Exceeded" again, because the platform pricing plan doesn't mention it.

well... i still having Errors about size limit exceeded. Obviusly i'll upgrade my pricing plan in order to resolve this issue, but it doesn't the right approach about this error i guess.

furthermore moreover if in this moment i start my upgrade to "Unlimited" pricing plan, and i get a charge about "file size", im going to get mad.

pricing plan of platform version 1.0
![image](https://user-images.githubusercontent.com/30780192/48577453-35a59900-e8e5-11e8-91bc-834cceb77b7c.png)

pricing plan of platform version 2.0
![image](https://user-images.githubusercontent.com/30780192/48577748-eb70e780-e8e5-11e8-99f7-8aafbc15b990.png)

my console error:
![image](https://user-images.githubusercontent.com/30780192/48579736-51ac3900-e8eb-11e8-806b-1255b1df7a70.png)

**Comment by leo** [comment]
Thank you for creating this issue. The team has resolved the problem and you should now be able to enjoy the full 100 MB. 😊
