### ISSUE TITLE
Error ERR_SPDY_PROTOCOL_ERROR when using Lambda + Custom Domain + res.writeHead

### ISSUE THREAD

**Issue by brunolemos** [vercel/vercel#1670]
- Made a successful deploy. When I open the temp link, it works (it redirects correctly)
- Made it alias to `www.mydomain.com`
  - When I open `mydomain.com/?test=ok`, it should redirect like the temp link did, but it fails with error `ERR_SPDY_PROTOCOL_ERROR`:
![ERR_SPDY_PROTOCOL_ERROR](https://user-images.githubusercontent.com/619186/48589196-b2566880-e921-11e8-8b7b-8b188056b3c3.png)

On Safari the error is:
`“The operation couldn’t be completed. Protocol error” (NSPOSIXErrorDomain:100)`

Based on my research seems to be related to HTTP/2. Some people said it's caused by multiline headers.

---

As you can see, the alias was created:

![image](https://user-images.githubusercontent.com/619186/48589258-ee89c900-e921-11e8-9bf6-18cc5f063516.png)

The domain is registered on Google Domains with these name servers:

<img height="300" src="https://user-images.githubusercontent.com/619186/48589305-1aa54a00-e922-11e8-8e98-16e9d786ac73.png" />

`now.json`
```json
{
  "name": "devhub-www",
  "alias": "www.devhubapp.com",
  "builds": [
    { "src": "index.js", "use": "@now/node" }
  ],
  "routes": [
    { "src": "/.*", "dest": "index.js" }
  ],
  "regions": ["gru1"],
  "version": 2
}
```

`index.js` based on [now-examples/redirect](https://github.com/now-examples/redirect/blob/master/server.js)
```js
module.exports = (req, res) => {
  res.writeHead(301, { Location: `https://devhubapp.com/${req.url.substr(1)}` })
  res.end()
}
```

Any tip?

**Comment by brunolemos** [comment]
Update: This seems to happen with any lambda that sets `res.writeHead(302)` for example and uses a custom domain as alias. If I use `now alias anything-here` that alias to `.now.sh`, it works, but if I do `now alias mydomain.com`, when accessing the url mydomain.com/mylambda it will give the error `ERR_SPDY_PROTOCOL_ERROR`.

May be related to zeit/micro-proxy#24

**Comment by brunolemos** [comment]
After hours of debugging, I can confirm this happens when adding any `res.writeHead`. And only when using a custom domain. After removing all my writeHead, it worked. Seems like a bug that needs to be fixed.

**Comment by brunolemos** [comment]
New findings, here is a TL/DR:

When using `writeHead`, it works on `.now.sh` but not on custom domains:

```js
module.exports = (req, res) => {
  res.writeHead(301, {
    Location: `https://devhubapp.com/${req.url.substr(1)}`,
  })
  res.end()
}
```

When using `res.setHeader` and `res.statusCode` instead of `res.writeHead`, it works perfectly on both `.now.sh` and custom domains:

```js
module.exports = (req, res) => {
  res.statusCode = 301
  res.setHeader('Location', `https://devhubapp.com/${req.url.substr(1)}`)

  res.end()
}
```

When using `micro`, it works perfectly as well, since the implementation is basically the code above:

```js
const { send } = require('micro')

module.exports = (req, res) => {
  res.setHeader('Location', `https://devhubapp.com/${req.url.substr(1)}`)
  send(res, 301)
}
```

So the problem is indeed `writeHead` + custom domains.

**Comment by TooTallNate** [comment]
Hey @brunolemos, sorry for the delayed response here. I just tested out the `writeHead()` version and it appears to work correctly in production, so I'm assuming this got fixed at some point. I'm going to close this one since it worked correctly for me, but please open up a new issue if you are still having problems.
