### ISSUE TITLE
Seeing directoy listing after now alias sometimes

### ISSUE THREAD

**Issue by brunolemos** [vercel/vercel#1679]
So, I've been having a surprising amount of weird issues with now v2. It's hard to reliably reproduce them because seems kinda of random.

For example, sometimes I make a deploy and then an alias and it works great. Other times, the temp link works but the aliased one shows the directory listing instead of the website. 😨

Example:

![image](https://user-images.githubusercontent.com/619186/48789228-babcf380-ecd3-11e8-8353-0b5a2b31b558.png)

![image](https://user-images.githubusercontent.com/619186/48789275-ce685a00-ecd3-11e8-958e-d31898f8fa06.png)

![image](https://user-images.githubusercontent.com/619186/48789308-df18d000-ecd3-11e8-908b-b1d7ce247e81.png)

Maybe it's taking some time to propagate or something like that? Any way this could by improved by now to prevent this?

**Comment by paulogdm** [comment]
Hello Bruno!
First of all, we are investigating if we are having cache issues on our side.
But let's try a few things here:
- Can you try to grab the response headers from both cases, if possible?
- Are you sure this is not a client caching issue somehow?

If you need to share critical information that you don't want to expose publicly, you can also email me here: paulo@zeit.co

Best regards.

**Comment by paulogdm** [comment]
@brunolemos We identified an issue and released a fix.

Could you verify if it is working as expected?
To make sure you are not seeing a cached version, please hit CTRL + F5 or Command + R.

Best regards.

**Comment by brunolemos** [comment]
> To make sure you are not seeing a cached version, please hit CTRL + F5 or Command + R.

I do use Cmd+R most of the times.

@paulogdm I made a new deploy and it worked 🙌

I'll let you know if I face this again. Thanks.

**Comment by brunolemos** [comment]
> @paulogdm We identified an issue

What was it?

**Comment by brunolemos** [comment]
Note: I upgraded from free to paid between my report and your fix, hopefully it isn't related to the issue

**Comment by paulogdm** [comment]
Issues in a

> Note: I upgraded from free to paid between my report and your fix, hopefully it isn't related to the issue

It is not. It was a proxy failure in one of our regions (IAD1, as you can see in your video).
We just told the code to behave :smile:!

**Comment by brunolemos** [comment]
> It was a proxy failure in one of our regions (IAD1)

Oh ok!
Hopefully you can add something later to detect this or prevent it from happening again on any region.

Thanks.
