### ISSUE TITLE
Public API for env vars

### ISSUE THREAD

**Issue by calebboyd** [vercel/vercel#168]
Right now you can create secrets using the REST api but unfortunately the CLI is the only way to get those secrets into a deployment. Additionally, if you attempt to set an `env` key via `now/instant` it results in an internal server error. 

So, This request is for the ability to expose secrets as environment variables to `now/instant` deployments. Perhaps similar to how `now/create` works.

**Comment by leo** [comment]
https://github.com/zeit/now-cloud/issues/1
