### ISSUE TITLE
Express, NextJS, TypeScript and Now

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#1682]
Hi,

This is from one of the examples on zeit/next.js - https://github.com/zeit/next.js/tree/canary/examples/custom-server-typescript

I am trying to deploy this example. If I just say now on the command prompt as you may expect all the contents of the directory gets uploaded. 

As a next step I created now.json. Now in this example we have nextjs and express. The now.json I created with 2 builds one for nextjs and another for node-server. 

Like below -
```
{
    "version": 2,
    "builds": [
        { "src": "next.config.js", "use": "@now/next" },
        { "src": "package.json", "use": "@now/node-server" }
      ]
}
```

Or should I consider doing 2 different deploys one for backend and one for frontend.

**Comment by leo** [comment]
The best way to solve this would be to simply create two directories within your project. After that, set the `src` to the directories you created.
