### ISSUE TITLE
Lambda keeps running after exception being thrown

### ISSUE THREAD

**Issue by brunolemos** [vercel/vercel#1686]
Shouldn't it stop instantly after an uncaught exception?

I had this after not putting `json(req)` inside a try catch:

![lambda-invalid-json](https://user-images.githubusercontent.com/619186/48869877-e4564780-edc5-11e8-8f25-db04152cf2a1.gif)

Which could increase costs unnecessarily.
It seems it charges `120 seconds` of execution each time that happens:

![image](https://user-images.githubusercontent.com/619186/48869984-4151fd80-edc6-11e8-9849-5e4dda8b7d95.png)

**Comment by juliangruber** [comment]
Which builder are you using?

**Comment by brunolemos** [comment]
node

**Comment by TooTallNate** [comment]
Closing because the Lambdas do exit upon `unhandledRejection` now. Please see https://github.com/zeit/now-builders/pull/372.
