### ISSUE TITLE
More helpful error message

### ISSUE THREAD

**Issue by heysailor** [vercel/vercel#1687]
When deploying with the now cli, I often come across the `Error! One or more build specification(s) were not referenced` error.

It'd be very helpful to have a more..helpful message - particularly which build specification is not referenced.

**Comment by heysailor** [comment]
... on further thought, I tend to get the error when the referenced source file is in a directory also listed in `.nowignore`. Maybe I'm just klutsy, but I easily forget to check.

It would seem nice for the cli to report that the src file referenced is also ignored, smoothing the path for people new to now?

**Comment by leo** [comment]
Indeed. We should show a better error here!
