### ISSUE TITLE
node-gyp for libsass hangs forever

### ISSUE THREAD

**Issue by giladgray** [vercel/vercel#169]
I have a project that uses node-sass, which requires installing libsass C library on linux. this seems to go fine but then the build simply stops after this line, never proceeding to actually building the app:

```
> gyp info ok
> Installed in "/home/nowuser/src/node_modules/bd5617c7bf3314494b8af6417e98f590ae814208/vendor/linux-x64-51/binding.node"
```

last week's initial deploy: https://lookit-ewsfnmaycp.now.sh
today's "try again" deploy: https://lookit-ocaoplzrut.now.sh/

relevant package.json sections look like so: 

```json
{
  "dependencies": {
    "cheerio": "0.22.0",
    "classnames": "2.2.5",
    "es6-promise": "3.2.1",
    "express": "4.14.0",
    "font-awesome": "4.6.3",
    "keymaster": "1.6.2",
    "lodash": "4.17.2",
    "react": "15.4.1",
    "react-dom": "15.4.1",
    "whatwg-fetch": "1.0.0"
  },
  "devDependencies": {
    "autoprefixer-loader": "3.2.0",
    "bourbon": "4.2.7",
    "css-loader": "0.26.1",
    "exports-loader": "0.6.3",
    "extract-text-webpack-plugin": "1.0.1",
    "imports-loader": "0.7.0",
    "json-loader": "0.5.4",
    "node-sass": "3.10.1",
    "npm-run-all": "3.1.2",
    "react-hot-loader": "1.3.1",
    "sass-loader": "4.0.2",
    "style-loader": "0.13.1",
    "ts-loader": "1.3.1",
    "typescript": "2.1.4",
    "webpack": "1.14.0",
    "webpack-dev-server": "1.16.2"
  },
  "scripts": {
    "build": "run-s clean copy build:client build:server",
    "build:client": "webpack",
    "build:server": "tsc -p server/tsconfig.json",
    "clean": "rm -rf build/ && mkdir -p build/client/fonts/",
    "copy": "cp ./client/index.html build/client/ && cp node_modules/font-awesome/*/fontawesome-webfont.* build/client/fonts/",
    "dev": "npm-run-all -s clean copy build:server -p start:server dev:client",
    "dev:client": "webpack-dev-server --config webpack-dev.config.js --inline",
    "postinstall": "typings install",
    "start": "node ./build/server/server.js"
  }
}
```

**Comment by luisrudge** [comment]
I'm having the same issue as well!

**Comment by quocnguyen** [comment]
I try to deploy app using leveldb and run into this same problem.

**Comment by mathiasbynens** [comment]
Just had the same issue (`now` hangs) with a jsPerf deploy: `https://jsperfcom-wifpvsewgh.now.sh/` In my case it’s not related to `node-gyp`, though. Trying the same `now` command again completed successfully.

**Comment by jamo** [comment]
I'm closing this now, as https://zeit.co/ace should have fixed all of these issues - given a new dependency suffers form a such issue, please open a new issue/reopen this.

ps. hosting leveldb on a immutable hosting platform shoulds like a, not necessarily wonderfull  idea... :)

**Comment by mattapperson** [comment]
bcrypt@0.8.7 install fails with this error @jamo
