### ISSUE TITLE
Now-cli - exec format error

### ISSUE THREAD

**Issue by prahaladbelavadi** [vercel/vercel#1691]
Related: #1077 ; I encountered a similar problem while trying to serve production files from my distribution folder on a different OS. Not sure if I'm doing this wrong or if this problem is restricted only to raspberri Pi s.

Running `now` in the distribution folder returns `cannot execute binary file: Exec format error`

![image](https://user-images.githubusercontent.com/16673094/48922832-59617400-eecf-11e8-9ffc-4bc6ceece6b1.png)

OS: Windows 8
Installation process; Npm

Steps to reproduce:
- `npm install -g now`
- `cd dist` && `now` 
- Returns error: `cannot execute binary file: Exec format error`

**Comment by igorklopov** [comment]
Seems like a space in path (`ng-book 2`) can be the cause. Can you please try running the same in a path that contains no spaces.
