### ISSUE TITLE
Custom Dockerfile 

### ISSUE THREAD

**Issue by sassanh** [vercel/vercel#1692]
I just want to know the answer of the question asked in https://github.com/zeit/now-cli/issues/507 Is it possible to make `run` ~make run~ use a `Dockerfile` other than the one in `<root>/Dockerfile`?

**Comment by leo** [comment]
Thank you for opening this issue! However, there is currently no such feature and we are not planning to add it either.

Instead of using Docker, we highly recommend [Now 2.0](https://zeit.co/blog/now-2). Thank you!
