### ISSUE TITLE
now.json ignored when path given

### ISSUE THREAD

**Issue by tylermassey** [vercel/vercel#1695]
I have a `build` folder in my project that I want to deploy.

Whenever I run `now deploy build`, I get the following warnings
```
> WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
```

I have a `now.json` file, and specifying where it is with `-A now.json` does not help.

If I just run `now`, I do not get the warning messages, but this is also not what I want to do.

**Comment by leo** [comment]
Thanks! I will take a look at this.

**Comment by leo** [comment]
I have just confirmed that this works 100% as expected.

My guess is that the reason why it doesn't work for you is that you either:

1. Didn't pass the correct path with `-A`
2. Passed `-A` to `npm run build` and not `now`

**Comment by debaosuidecl** [comment]
hey guys help me out here I am getting this really annoying error when attempting to deploy my small authentication project with now

check out the error

`> now --public

> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Deploying ~\Documents\next-cookie-auth under debaosuidecl@gmail.com
> Synced 4 files (42.83KB) [2s]
> Using Node.js 8.11.3 (default)
> https://next-cookie-auth-gbfufgrdrl.now.sh [v1] [in clipboard] (bru1) [15s]
> Building…
> ▲ npm install
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/send-fac8eab4/package.json'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/chalk-7285e45b/package.json'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/chalk-7285e45b/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/send-fac8eab4/HISTORY.md'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/send-fac8eab4/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/chalk-7285e45b/license'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/chalk-7285e45b/readme.md'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/send-fac8eab4/LICENSE'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/send-fac8eab4/README.md'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/source-map-8e7bc791/dist/source-map.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/source-map-5daa4832/dist/source-map.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/react-dom-b464b929/umd/react-dom-test-utils.production.min.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/react-dom-b464b929/umd/react-dom-unstable-native-dependencies.development.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/terser-6fc62c8f/dist/bundle.js.map'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/retrievers'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/traverse'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generateTypeHelpers.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/utils'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/asserts/assertNode.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/asserts/generated'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/builder.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/flow'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/generated'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/react'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/clone/clone.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/clone/cloneDeep.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/clone/cloneNode.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/clone/cloneWithoutLoc.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/addComment.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/addComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/inheritInnerComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/inheritLeadingComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/inheritTrailingComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/inheritsComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/removeComments.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/constants/generated'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/constants/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/ensureBlock.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/gatherSequenceExpressions.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toBindingIdentifierName.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toBlock.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toComputedKey.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toExpression.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toIdentifier.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toKeyAlias.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toSequenceExpression.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toStatement.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/valueToNode.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/core.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/es2015.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/experimental.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/flow.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/jsx.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/misc.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/typescript.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/utils.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/retrievers'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/retrievers'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/traverse'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/traverse'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/asserts/generated'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/flow'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/flow'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/generated'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/react'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/constants/generated'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators'
> npm WARN next-cookie-auth@1.0.0 No repository field.
>
> npm ERR! code E404
> npm ERR! 404 Not Found: event-stream@https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
>
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2018-12-14T07_08_36_698Z-debug.log
> Error! Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-cookie-auth@1.0.0 deploy: `now --public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the next-cookie-auth@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OSUIDE O.C\AppData\Roaming\npm-cache\_logs\2018-12-14T07_08_42_572Z-debug.log`

my package.json file looks like this:

{
  "name": "next-cookie-auth",
  "version": "1.0.0",
  "description": "Cookie authentication with Next.js",
  "main": "server.js",
  "scripts": {
    "dev": "nodemon server.js",
    "start": "set NODE_ENV=production && node server.js",
    "build": "next build",
    "deploy": "now --public"
  },
  "author": "Deba Osuide",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.18.0",
    "cookie-parser": "^1.4.3",
    "express": "^4.16.4",
    "next": "^7.0.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3"
  },
  "devDependencies": {
    "nodemon": "^1.18.5"
  },
  "directories": {
    "lib": "lib"
  }
}


Cannot someone please help me out... Thanks in advance

**Comment by Albert2211** [comment]
{
  "name": "web",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node src",
    "dev": "nodemon src/"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "ejs": "^2.6.1",
    "express": "^4.17.1",
    "morgan": "^1.9.1",
    "now": "^15.6.0"
  },
  "devDependencies": {
    "nodemon": "^1.19.1"
  }
}
Este es mi codigo del package.json y cuando intento correr now me aparece el mismo error que entes mencionaron.  
 WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
