### ISSUE TITLE
[v2] `now alias` doesn't seem to work

### ISSUE THREAD

**Issue by byzyk** [vercel/vercel#1698]
Running `now alias` finishes with OK status but for some reason the actual content doesn't get updated.

#### Example

[`_src` folder](https://vlad-static-webpage-test-khpgykyhl.now.sh) (says `LOGO UPDATED`) is correct but the actual page content [is wrong](https://vlad-static-webpage-test.now.sh/) (says `LOGO 2`).

#### Config file

```json
{
  "version": 2,
  "name": "vlad-static-webpage-test",
  "alias": ["vlad-static-webpage-test"],
  "builds": [
    {
      "src": "./src/*", "use": "@now/static"
    }
  ],
  "routes": [
    {
      "src": "/(.*)", "dest": "/src/$1"
    }
  ],
  "github": {
    "silent": true
  }
}
```

#### Version

`node@10.7.0`
`now@12.1.6`

**Comment by paulogdm** [comment]
Hello @byzyk we fixed a bug with alias yesterday... Can you check if everything is now ok on your end?

**Comment by byzyk** [comment]
Yep, it works now. Thanks for the swift reaction!
