### ISSUE TITLE
Unable to import module 'now__launcher'

### ISSUE THREAD

**Issue by lorenseanstewart** [vercel/vercel#1699]
# Bug report

## Describe the bug

When trying to build and deploy to `now`, everything seems to build fine but at the end of the build process I get the following error:

```
Unable to import module 'now__launcher': Error
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/var/task/next.config.js:2:51)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

## To Reproduce

1. Clone this repo `https://github.com/lorenseanstewart/next-blog-starter`
2. `npm i` from the root
3. `now`
4. To see the error, check logs with `now logs <url-provided-by-deploy>`

## Expected behavior
This project to deploy without errors from `now`.

## System information
 -  macOS
 - Version of Next.js: 7.0.2
 - Version of Now: 2
 - Version of now-cli: 12.1.6

**Comment by lorenseanstewart** [comment]
@ppromsuban I think it is related. Sorry for duplicating the issue.

**Comment by ppromsuban** [comment]
@lorenseanstewart Just referencing so i can keep track of the issue. thanks for raising the issue. (also waiting for a solution 😄 )

**Comment by nickerlan** [comment]
Faced the same issue

**Comment by abnerlee** [comment]
same issue, it worked about 3 weeks ago

**Comment by paulogdm** [comment]
Please, refer to https://github.com/zeit/now-builders/blob/master/errors/now-next-legacy-mode.md.
Only Next.js greater than 8 will be prepared for a serverless environment.

**Comment by juliangruber** [comment]
The original repo `https://github.com/lorenseanstewart/next-blog-starter` isn't available any more, can someone share a way to reproduce?

**Comment by juliangruber** [comment]
@lorenseanstewart is upgrading to Next.js 8 or later (`8.0.3` is the most recent version) an option for you?

**Comment by lorenseanstewart** [comment]
@juliangruber 
Yes! I upgraded to Next.js 8 without any troubles at all. There were errors after upgrading, but deleting `node_modules` and `.next/`, and then running `npm i` fixed the errors.

Here's the link to the repo https://github.com/lorenseanstewart/nextjs-mdx-blog-kit

**Comment by juliangruber** [comment]
I'm happy this now works for you :)
