### ISSUE TITLE
pronostico in response

### ISSUE THREAD

**Issue by qbolec** [vercel/vercel#170]
After a day of not using my app, today, I visited https://lattices-api-mock-clwdcgqqqp.now.sh/abcd1234/pl.general?path=web.lines[4] and received
```
{
pronostico: [
{
type: "BAJAMAR",
hora: "03:00",
altura: "1.50"
},
{
type: "PLEAMAR",
hora: "08:00",
altura: "2.40"
},
{
type: "BAJAMAR",
hora: "15:30",
altura: "1.40"
}
]
}
```
I'm usuing Chrome and a JSONView plugin. After refreshing the page it presented the expected result.

**Comment by qbolec** [comment]
Perhaps I should clarify, that the response was totally unexpected, and seems like a originating from some service unknown to me. The text looks like in Spanish, and related to sea tides, while my service usually outputs text in Polish and is related to text-to-speech :)

**Comment by jamo** [comment]
I'll close this now, since this possible issue is being tracked also elsewhere (internally). 
Anyways this should't definitely happen.
