### ISSUE TITLE
`now alias` not working

### ISSUE THREAD

**Issue by philipaw** [vercel/vercel#1701]
New Now user here. When deploying with `now build-directory -A ../now.json`, everything works and the immutable url shows my application deployed. But when I run `now alias -A now.json`, I get the following error:

```bash
> Assigning alias my-team-alias to deployment my-app-blahblahblahblah.now.sh
> Error! The alias my-team-app is a deployment URL or it's in use by a different team.
> Error! No permission to access deployment "my-team-app.now.sh" under my-team
```

For reference, my now.json looks like this:

```json
{
  "version": 2,
  "name": "my-team-app",
  "alias": "my-team-app",
  "routes": [
    {"src": "^/static/(.*)", "dest": "/static/$1"},
    {"src": ".*", "dest": "/index.html"}
  ]
}
```

Note that my coworker recently signed us up for Zeit and he is the owner of our team in your database. He created the `my-team-app` alias on his end. I already did `now switch` after he invited me to join our Zeit team.

What should I do to make aliasing work for me?

**Comment by paulogdm** [comment]
But he created `my-team-app` alias under the team?
Can you give me the output of `now alias ls` under your team? Can he do the same on his personal account?

**Comment by paulogdm** [comment]
You can do it by typing `now alias rm`.
Glad you got things sorted out!

**Comment by philipaw** [comment]
Thank you so much for the help! I can now deploy!
