### ISSUE TITLE
res.set("Connection", "close") seems to be ignored

### ISSUE THREAD

**Issue by qbolec** [vercel/vercel#171]
Perhaps this is a feature, not a bug, but I'd like to close the connection after serving a request using `res.set("Connection", "close")` but it does not seem to work with your hosting.
I have no idea how you manage to guess on which port my service is running, and map it's http to public https, providing etag cacheing on fly - this is awesome. 
But it seems that in my scenario, I need to explicitly tell the client to disconnect, and I do not know how to do that.
My use case is this: 
```
import urllib3
import certifi
import json
import unittest

class APITest(unittest.TestCase):
    def test_endpoint(self):
        urllib3.PoolManager(
           cert_reqs='CERT_REQUIRED',
           ca_certs=certifi.where()
        ).request("GET", "https://lattices-api-mock-sfqouwpwty.now.sh/deadbeefd/pl.general?path=web.lines[4]")
```
then
```
$ python -m unittest tt.py
/home/jlopuszanski/audioscope-search-api/tt.py:11: ResourceWarning: unclosed <ssl.SSLSocket fd=4, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('10.10.33.51', 60782), raddr=('52.52.87.49', 443)>
  ).request("GET", "https://lattices-api-mock-sfqouwpwty.now.sh/deadbeefd/pl.general?path=web.lines[4]")
.
----------------------------------------------------------------------
Ran 1 test in 1.340s

OK
```
I know I could turn off the warning, but it doesn't seem to be the right solution.

**Comment by jamo** [comment]
Apologies for the delay in our response.

This behaviour is actually correct.
The `Connection: close` header is hop-to-hop header. Hence our router does not per [rfc2616 13.5.1](https://tools.ietf.org/html/rfc2616#section-13.5.1) forward these headers. Similarly it's existence doesn't matter whether client connection is closed or not.
