### ISSUE TITLE
now --alias : handle multiple aliases at once

### ISSUE THREAD

**Issue by slorber** [vercel/vercel#172]
Related to this issue/comment: https://github.com/zeit/now-cli/issues/120#issuecomment-267286842

The new --alias does not support multiple aliasing on the same deployment

Currently I have to do:

``` 
now --alias leo.im
now --alias rem.im
now --alias rauchg.im
```

So at the end there are 3 deployments with the same content, but it makes more sense to have a single one linked to 3 aliases:

```
now --alias leo.im rem.im rauchg.im
```
or
```
now --alias leo.im --alias rem.im --alias rauchg.im
```

**Comment by leo** [comment]
Just talked to @OlliV and it looks like we already support setting multiple aliases for a single deployment. This is also what would happen if you do this (because `now` only creates a new instance if a file changed):

```bash
$ now --alias leo.im
$ now --alias rem.im
$ now --alias rauchg.im
```

So I guess the way to make this even easier would be:

```bash
$ now --alias leo.im rauchg.com
```

**Comment by slorber** [comment]
Ok I'm fine with running 3 commands then if it's the same deployment.

The last command does not work for me:

```
11:18 $ now --alias frontend-dev.stample.co frontend-prod-next.stample.co
> Error! Could not read directory /Users/sebastienlorber/Desktop/Stample-react/frontend-prod-next.stample.co
```

**Comment by leo** [comment]
@slorber Like I said...

>  the way to make this even easier **would be**

😊 

It's not yet implemented. Could be a nice addition though!

**Comment by leo** [comment]
Merged in https://github.com/zeit/now-cli/pull/202
