### ISSUE TITLE
0.35 upgrade: how to validate existing domain?

### ISSUE THREAD

**Issue by slorber** [vercel/vercel#173]
Hi,

I own domain stample.co and with previous CLI versions I was able to create aliases. You can see for exemple a deployment with an alias here: [https://frontend-dev.stample.co/](https://frontend-dev.stample.co/)

Since CLI upgrade, I am unable to alias anything, while it used to work with former CLI (I guess you did not do a breaking change on purpose on the backend).

```
$ now alias stample-bzesdwnulh frontend-dev.stample.co
> frontend-dev.stample.co is a custom domain.
> Verifying the DNS settings for frontend-dev.stample.co (see https://zeit.world for help)
> Error! > The domain stample.co is already registered with now but additional verification is needed, please refer to 'now domain --help'.
```

```
$ now domain ls
> 1 domain found [991ms]

                        id  dns       url                 verified  created
  someId  external  https://stample.co  false     51d ago
```
```
$ now domain add stample.co
> Verifying nameservers…
> Error! Please make sure that your nameservers point to zeit.world.
> Examples: (full list at https://zeit.world)
> - california.zeit.world    173.255.215.107
> - newark.zeit.world        173.255.231.87
> - london.zeit.world        178.62.47.76
> - singapore.zeit.world     119.81.97.170
```

Like the CLI says I added a TXT record to my DNS because I didn't have it before.
I updated my DNS but running `now domain add` still fails

```
_now.stample.co           IN TXT    "someKeyThatIsProbablyPrivate?"
_now           IN TXT    "someKeyThatIsProbablyPrivate?"

frontend-dev              IN CNAME  alias.zeit.co.
frontend-prod             IN CNAME  alias.zeit.co.
frontend-prod-next        IN CNAME  alias.zeit.co.
frontend-staging          IN CNAME  alias.zeit.co.
```

So I already have a domain but I'm not able to verify it. One sure thing is it looks risky to remove the domain and re-add it as it may make my service temporarily unavailable.

**Comment by OlliV** [comment]
Run `now domain add -e stample.co`

**Comment by slorber** [comment]
Thanks it seems to work :)
