### ISSUE TITLE
Are A-records supported?

### ISSUE THREAD

**Issue by nickerlan** [vercel/vercel#1730]
None of my domain registrators supports ALIAS-records (while CNAME cannot be used for @). 
All services i've used before supported A-records to easily catch my domain. 

Is it possible in now ?

**Comment by KBPsystem777** [comment]
So far I just used Nameservers and TXT records on my domain. I think this blog may help: https://medium.com/@moustachedesign/deploying-your-ssr-app-to-zeit-now-from-godaddy-41b51302375f

**Comment by jamo** [comment]
It's highly recommended to not user A records as those do change and are rotated with no real notice.

Some providers support ALIAS records under A record, or then call it cname-flattening.
Both zeit.world dns and cloudflare offer really comprehensive and free dns management that supports alias/cname-flattening out of the box.

**Comment by juliangruber** [comment]
Closing because answered by @jamo ✌️
