### ISSUE TITLE
Is something happening to Zeit Servers?

### ISSUE THREAD

**Issue by nickerlan** [vercel/vercel#1731]
None of deployments working for hours, no matter the code. Tried simple nodejs scripts and even static html.
All statuses are "Initializing"
CLI says "Waiting for deployment to be ready"
In logs once I've seen "finished". And there is no logs now for static tests.

Is everything ok with the service?

**Comment by kolja-esders** [comment]
[Should be resolved.](https://twitter.com/zeit_status/status/1071452629278945280)
