### ISSUE TITLE
Broken deployment-error link

### ISSUE THREAD

**Issue by kolja-esders** [vercel/vercel#1732]
Just received an unspecified error message after my files where uploaded:

```
...
> Error! Your deployment failed. Please retry later. More: https://err.sh/now-cli/deployment-error
```

The link [https://err.sh/now-cli/deployment-error](https://err.sh/now-cli/deployment-error) redirects to [https://github.com/zeit/now-cli/blob/master/errors/deployment-error.md](https://github.com/zeit/now-cli/blob/master/errors/deployment-error.md) which does not exist.

Would suggest to either fix the redirect or create the doc file in case it is missing.

Using now-cli v2.

**Comment by juliangruber** [comment]
@kolja-esders is there a way to reproduce this error?

And I can confirm this document doesn't exist.

**Comment by kolja-esders** [comment]
If you look for the URL in the source you can find it [here](https://github.com/zeit/now-cli/blob/4337f0bab0d133485e2908af9367dc65c17fb450/src/commands/deploy/latest.js#L67) in the deployment process.

Changing the URL there should fix the issue.

**Comment by juliangruber** [comment]
I can see where the url is in the code, but would like to understand what kind of deployment error lead to it, so I know how specific the documentation needs to be.

**Comment by adamlogic** [comment]
I'm seeing the same message and broken URL. I'm not seeing any info about what kind of error it is.

```
❯ now     
(node:82442) ExperimentalWarning: The http2 module is an experimental API.
> Deploying ~/src/gmaps-next under adamlogic
> Using project gmaps-next
> https://gmaps-next-ejammmyi3.now.sh [v2] [2s]
> Error! Your deployment failed. Please retry later. More: https://err.sh/now-cli/deployment-error
```

Is there a way to get some details about the failure?

**Comment by leo** [comment]
Thanks for reporting this! We'll fix it.

**Comment by nickredmark** [comment]
had the same problem, logs exposed this:

{ Error: Invalid tag name "latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest": Tags may not have any characters that encodeURIComponent encodes.

what caused is was either

* I added now*.json to .gitignore
* I tried to deploy with a different now.json file (under a different project name)
* ?

**Comment by nmaro** [comment]
Why was my comment marked as off topic? I have the same error message

Error! Your deployment failed. Please retry later. More: https://err.sh/now-cli/deployment-error

Thought was providing you debug information...

**Comment by nmaro** [comment]
Perhaps it would be interesting to see what @adamlogic output of `now logs https://gmaps-next-ejammmyi3.now.sh` is, to see whether it's the same underlying issue.
