### ISSUE TITLE
Command 'now' not found on Ubuntu 18.04 when installing through now-linux.gz

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#1740]
I installed the Now CLI through its [official app page](https://zeit.co/download#now-cli), using the file `now-linux.gz`.

Then I go to my app directory and run `now`, but I get the error `Command 'now' not found`.

I am on Ubuntu 18.04

I read the issue #958 but doesn't apply here because I haven't used npm.

**Comment by monojack** [comment]
did you forget to add it to the path?

**Comment by ghost** [comment]
> did you forget to add it to the path?

Yes, what command should I execute for that?

**Comment by monojack** [comment]
Depends on your setup. You either add it to your `.bashrc` file:
```sh
export PATH=$PATH:/path/to/now
# or
export PATH=/path/to/now:$PATH
```

 or copy the .bin file to `/usr/local/bin`

https://unix.stackexchange.com/a/26059

**Comment by ghost** [comment]
I have no idea where my Now installation is. What is the usual path?

**Comment by monojack** [comment]
You've downloaded the `gz` file and extracted it somewhere, right? It should be there.

**Comment by juliangruber** [comment]
@togademi you can either run now from the directory you downloaded it to

```bash
$ ./now
```

or need to add it to your `$PATH` as @monojack suggested. Installing it through npm possibly requires less installation knowledge:

```bash
$ # install node / npm somehow, then
$ npm install -g now
```

**Comment by mkomod** [comment]
Hi there, I'm also having this issue running Ubuntu 18.04. I successfully installed using:

`$ npm i -g now`

And the binaries are available in 

`~/.npm-global/bin `

I've tried running now via the command line

```
Command 'now' not found, did you mean:

  command 'nsw' from snap nsw (0+git.b61ddec)
  command 'sow' from deb ruby-hoe
  command 'new' from deb mmh
  command 'new' from deb nmh
  command 'nop' from deb graphviz
  command 'cow' from deb fl-cow
  command 'nw' from deb netrw
```

and have also tried running the binaries via `$ . now` and `$ bash now` however i get the following error:

`bash: .: now: cannot execute binary file`

**Comment by mkomod** [comment]
Apologies I managed to get this fixed by editing my .bashrc file

In paths I added:

`~/.npm-global/bin`
