### ISSUE TITLE
Give more context for errors caused by a missing `name` property

### ISSUE THREAD

**Issue by timothyis** [vercel/vercel#1741]
As per this conversation in the docs: https://github.com/zeit/docs/pull/378#issuecomment-446388601

It would be good to link to the documentation and provide more context for errors that are caused by not having a `name` property attributed to the deployment via `now.json`.

**Comment by zeusdeux** [comment]
I've attempted to solve this using just text. LMK if you prefer adding an outgoing link to an new FAQ question or something of that nature! ^_^

Edit: PR -> https://github.com/zeit/now-cli/pull/1742

**Comment by juliangruber** [comment]
Fixed in above mentioned PR
