### ISSUE TITLE
invalid console message

### ISSUE THREAD

**Issue by revolunet** [vercel/vercel#1744]
Hi, just noticed this message in `config.json` looks like outdated.

```
{
  "_": "This is your Now config file. See `now config help`. More: https://git.io/v5ECz"
}
```

https://github.com/zeit/now-cli/blob/ab81bbea68799e866cdc49a6f083f778f4dc4247/src/util/config/get-default.js#L6

**Comment by juliangruber** [comment]
This has been released now :)
