### ISSUE TITLE
Improve error message for non-string environment variable

### ISSUE THREAD

**Issue by gustavopch** [vercel/vercel#1746]
Tried to deploy with a now.json that contained the following environment variable:
```
  "env": {
    "PORT": 19194
  }
```
Got the error: `Error! Cannot read property 'length' of undefined`
I don't get the error when I declare it as a string though (`"19194"`).
The error message should be improved.

**Comment by juliangruber** [comment]
This has been fixed:

```bash
$ now
> Deploying ~/dev/zeit/now-examples/static under juliangruber
> Using project static
> Error! The property `env['PORT']` in now.json can only be of type `String`.
```
