### ISSUE TITLE
Hi guys I'm trying to deploy my nextJS app and I'm  running into this issue

### ISSUE THREAD

**Issue by debaosuidecl** [vercel/vercel#1751]
// package.json
{
  "name": "next-cookie-auth",
  "version": "1.0.0",
  "description": "simple Cookie authentication with Next.js",
  "main": "server.js",
  "scripts": {
    "dev": "nodemon server.js",
    "start": "set NODE_ENV=production && node server.js",
    "build": "next build",
    "deploy": "now --public"
  },
  "author": "Deba Osuide",
  "license": "ISC",
  "dependencies": {
    "axios": "^0.18.0",
    "cookie-parser": "^1.4.3",
    "express": "^4.16.4",
    "next": "^7.0.2",
    "react": "^16.6.3",
    "react-dom": "^16.6.3"
  },
  "devDependencies": {
    "nodemon": "^1.18.5"
  },
  "directories": {
    "lib": "lib"
  }
}

now --public

> WARN! You are using an old version of the Now Platform. More: https://zeit.co/docs/v1-upgrade
> Deploying ~\Documents\next-cookie-auth under debaosuidecl@gmail.com
> Synced 4 files (42.19KB) [2s]
> Using Node.js 8.11.3 (default)
> https://next-cookie-auth-qipjklnzqn.now.sh [v1] [in clipboard] (bru1) [17s]
> Building…
> ▲ npm install
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/extend-shallow-f79d9912/package.json'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/shebang-command-e777e04b/package.json'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/browserify-sign-73264082/package.json'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/crypto-browserify-5c4a3835/package.json'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/shebang-regex-2c31e0a0/package.json'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/extend-shallow-f79d9912/README.md'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/shebang-command-e777e04b/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/browserify-sign-73264082/README.md'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/crypto-browserify-5c4a3835/.travis.yml'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/shebang-regex-2c31e0a0/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/extend-shallow-f79d9912/LICENSE'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/shebang-command-e777e04b/license'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/browserify-sign-73264082/LICENSE'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/crypto-browserify-5c4a3835/.zuul.yml'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/shebang-regex-2c31e0a0/license'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/extend-shallow-f79d9912/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/shebang-command-e777e04b/readme.md'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/browserify-sign-73264082/algos.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/crypto-browserify-5c4a3835/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/shebang-regex-2c31e0a0/readme.md'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/browserify-sign-73264082/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/crypto-browserify-5c4a3835/LICENSE'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/crypto-browserify-5c4a3835/README.md'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generateTypeHelpers.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/utils'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/asserts/assertNode.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/asserts/generated'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/builder.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/flow'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/generated'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/source-map-2c2447b9/dist/source-map.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/react'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/clone/clone.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/clone/cloneDeep.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/clone/cloneNode.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/clone/cloneWithoutLoc.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/addComment.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/addComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/inheritInnerComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/inheritLeadingComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/inheritTrailingComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/inheritsComments.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/comments/removeComments.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/constants/generated'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/constants/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/ensureBlock.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/gatherSequenceExpressions.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toBindingIdentifierName.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toBlock.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toComputedKey.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toExpression.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toIdentifier.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toKeyAlias.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toSequenceExpression.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/react-dom-b464b929/umd/react-dom.production.min.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/toStatement.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/converters/valueToNode.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/core.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/es2015.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/experimental.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/flow.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/index.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/jsx.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/misc.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/typescript.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/definitions/utils.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications/appendToMemberExpression.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications/flow'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications/inherits.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications/prependToMemberExpression.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications/removeProperties.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications/removePropertiesDeep.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/retrievers/getBindingIdentifiers.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/retrievers/getOuterBindingIdentifiers.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/traverse/traverse.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/traverse/traverseFast.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils/inherit.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils/react'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils/shallowEqual.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/buildMatchMemberExpression.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/generated'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/is.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isBinding.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isBlockScoped.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isImmutable.js'> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isLet.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isNode.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isNodesEquivalent.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isReferenced.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isScope.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isSpecifierDefault.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isType.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isValidES3Identifier.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isValidIdentifier.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/isVar.js'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/matchesPattern.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/react'
> npm WARN tar ENOENT: no such file or directory, open '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/validate.js'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/generators'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/scripts/utils'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/asserts/generated'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/flow'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/flow'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/generated'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/builders/react'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/constants/generated'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/modifications/flow'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/utils/react'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/generated'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/react'
> npm WARN tar ENOENT: no such file or directory, lstat '/home/nowuser/src/node_modules/.staging/@babel/types-fb510155/lib/validators/react'
> npm WARN next-cookie-auth@1.0.0 No repository field.
>
> npm ERR! code E404
> npm ERR! 404 Not Found: event-stream@https://registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz
>
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2018-12-14T06_48_23_566Z-debug.log
> Error! Build failed
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-cookie-auth@1.0.0 deploy: `now --public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the next-cookie-auth@1.0.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OSUIDE O.C\AppData\Roaming\npm-cache\_logs\2018-12-14T06_48_29_276Z-debug.log

I have no idea what to do after several deploys I still get the same error

**Comment by yhjor** [comment]
same issue here, everything is poorly documented and lack of certain data transparency

**Comment by debaosuidecl** [comment]
It's really annoying...such a great react development framework...and little data transparency..
Have you solved the issue yet?

**Comment by debaosuidecl** [comment]
Deploying static sites with now is a breeze...but I have a custom server and still pretty new to now...
Do I need to migrate to now 2.0?

**Comment by Jolg42** [comment]
Same issue with Node 8.11.3 env here and Now v1

**Comment by debaosuidecl** [comment]
Come on
Some of us prefer version 1...😥😥😥
And are still trying to slowly migrate to version 2...
I hope they can sort out the error soon

**Comment by Jolg42** [comment]
I updated my dependencies, looks like one of them was using [a flatmap-stream vulnerable version that got removed from npm](https://github.com/dominictarr/event-stream/issues/116)

Everything is working fine now.

@debaosuidecl It looks like you have the same exact issue here:
`npm ERR! 404 Not Found: event-stream@registry.npmjs.org/event-stream/-/event-stream-3.3.6.tgz`

I recommend running `npm audit` and you'll see something like that:
<img width="568" alt="screenshot 2018-12-20 at 17 33 52" src="https://user-images.githubusercontent.com/1328733/50297599-74e37e80-047d-11e9-9fd9-720f27fbb033.png">

Then checking if you can update the version of the package mentioned as `Dependency of`, `backpack-core` in my case.

**Comment by debaosuidecl** [comment]
Wow thanks a lot ...I ran npm audit after updating  my npm to the latest...it was my nodemon that was in dependency of...
So basically since it was a development dependency, I just took it off my package.json and ran npm install

Works like a charm now!!!
So I'm closing this issue...
Thanks for the contribution
