### ISSUE TITLE
Document forbidden environment variable names

### ISSUE THREAD

**Issue by carloslfu** [vercel/vercel#1752]
I was trying to setup some environment variables and get a weird error:
```bash
now -e AWS_ACCESS_KEY=@aws_access_key -e AWS_SECRET_ACCESS_KEY=@aws_secret_access_key
```
 And get:
> Error! The following environment variables can not be configured: AWS_ACCESS_KEY, AWS_SECRET_ACCESS_KEY

Changing the names to `ACCESS_KEY` and `SECRET_ACCESS_KEY` solved the problem so I guess these variable names are forbidden. The problem is it isn't in the docs.

**Comment by timothyis** [comment]
Hi there @carloslfu, these are already documented here: https://zeit.co/docs/v2/deployments/environment-variables-and-secrets/#reserved-variables

**Comment by sandorvasas** [comment]
It's 2025 january and I'm still getting this error.

**Comment by carloslfu** [comment]
@sandorvasas, these are the new docs: https://vercel.com/docs/projects/environment-variables/reserved-environment-variables#reserved-environment-variables.
