### ISSUE TITLE
now complaining about `type` in `now.json`

### ISSUE THREAD

**Issue by bukinoshita** [vercel/vercel#1759]
I have an application running and when I opened a PR, now bot complained about having `type: docker` on my `now.json`

![duphx9sxqaum9-b](https://user-images.githubusercontent.com/6929565/50153210-ef10d900-02ac-11e9-8656-284264e8e330.jpeg)

So I opened a new PR just to remove this line and now complained to put it back(?)

![duphx9pwkait6v7](https://user-images.githubusercontent.com/6929565/50153216-f0420600-02ac-11e9-97d2-f0f52ffac62d.jpeg)

Here's my `now.json`

**before**

```js
{
  "name": "name",
  "alias": "name",
  "type": "docker",
  "env": {
    "PORT": "@infinity-auth-port-canary"
  }
}
```

**after**

```js
{
  "name": "name",
  "alias": "name",
  "env": {
    "PORT": "@infinity-auth-port-canary"
  }
}
```

**Comment by timothyis** [comment]
Hi there, it looks like you're trying to use features from Now v1.0 (more info here: https://zeit.co/docs/v2/platform/upgrade-to-2-0/)

If you'd like to continue using Now v1.0 for now, along with the `type` property, please add the following aswell:
```
"version": 1
```

For more information on upgrading to Now v2.0 and what has changed, feel free to read our upgrade guide: https://zeit.co/docs/v2/platform/upgrade-to-2-0/
And feel free to reach out if you have any further questions.

**Comment by bukinoshita** [comment]
Thanks! Solved by adding

```
{
  "name": "name",
  "alias": "name",
  "version": 2,
  "env": {
    "PORT": "@infinity-auth-port-canary"
  }
}
```
