### ISSUE TITLE
Bug on install: Failed at the now@12.1.14 postinstall script 'node download/install.js'.

### ISSUE THREAD

**Issue by nielsonsantana** [vercel/vercel#1769]
I'm installing `now-cli` on Ubuntu 16.04 with Node v4.2.6

```
/usr/local/bin/now -> /usr/local/lib/node_modules/now/download/dist/now

> now@12.1.14 postinstall /usr/local/lib/node_modules/now
> node download/install.js

/usr/local/lib/node_modules/now/download/dist/index.js:1
(function (exports, require, module, __filename, __dirname) { module.exports=function(e){var t={};function __webpack_require__(r){if(t[r])return t[r].exports;var n=t[r]={i:r,l:!1,exports:{}};return e[r].call(n.exports,n,n.exports,__webpack_require__),n.l=!0,n.exports}return __webpack_require__.m=e,__webpack_require__.c=t,__webpack_require__.d=function(e,t,r){__webpack_require__.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:r})},__webpack_require__.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},__webpack_require__.t=function(e,t){if(1&t&&(e=__webpack_require__(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(__webpack_require__.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var n in e)__webpack_require__.d(r,n,function(t){return

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/now/download/install.js:16:1)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
npm ERR! Linux 4.4.0-139-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "now"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! now@12.1.14 postinstall: `node download/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the now@12.1.14 postinstall script 'node download/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the now package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node download/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs now
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls now
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log
```

**Comment by jsbrn** [comment]
I also have the same issue, but it looks like it's coming from a different line in index.js. Sorry I don't have a solution for the thread. Still looking.

> /usr/local/lib/node_modules/now/download/dist/index.js:10511
> let { platform } = process;
>     ^
> 
> SyntaxError: Unexpected token {
>     at exports.runInThisContext (vm.js:53:16)
>     at Module._compile (module.js:374:25)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/usr/local/lib/node_modules/now/download/install.js:16:1)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
> npm ERR! Linux 4.15.0-43-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "now"
> npm ERR! node v4.2.6
> npm ERR! npm  v3.5.2
> npm ERR! code ELIFECYCLE
> 
> npm ERR! now@13.1.2 postinstall: `node download/install.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the now@13.1.2 postinstall script 'node download/install.js'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the now package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node download/install.js
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs now
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls now
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /home/jeremy/Documents/Github/openmc.net/npm-debug.log

**Comment by juliangruber** [comment]
Can you please update your nodejs versions? All of those errors should be fixed in a current node version.
