### ISSUE TITLE
Cannot create secret with name containing `/`

### ISSUE THREAD

**Issue by maxdeviant** [vercel/vercel#177]
There appears to be an issue with the `name` validation for secrets.

Running this command:
```sh
now secrets add example.com/test/database_user "my-secret"
```

Results in this error:

```sh
> Error! Only alphanumerics and `/ . _ -` are allowed as `name`
```

It appears that the `/` is the problem, because if I remove it then adding the secret works.

**Comment by OlliV** [comment]
I don't think we can ever allow using `/`.
I would suggest to make a base64 encoded secret that contains something like: 
```domain.com/my/secret=value```
