### ISSUE TITLE
Unable to deploy site to custom domain

### ISSUE THREAD

**Issue by ayushxx7** [vercel/vercel#1772]
I am unable to deploy open--this.site. I feel it has to do something with the domain having the 2 dashes. It throws  Error! The supplied domain is invalid (400), I have added nameservers to godaddy

**Comment by fu-sen** [comment]
I recently touched the custom domain of Punycode (IDN). This is the domain starting with "xn--".
But I have not encountered any problems.
For example: https://github.com/fu-sen/xn--ck8hk4b.tk to https://xn--ck8hk4b.tk/

It is possible that a problem different from the domain is occurring.
Have you tried with a simple file structure?

**Comment by fu-sen** [comment]
This information is old. ZEIT has released a new DNS:
https://zeit.co/blog/domains-on-now-safer-easier-faster

It should have received notification by e-mail for each domain:

**Comment by juliangruber** [comment]
Closing since this doesn't seem to be a problem any more.
