### ISSUE TITLE
Trying to use -m with -t causes deploy to fail with an unhelpful error

### ISSUE THREAD

**Issue by zeusdeux** [vercel/vercel#1776]
# Steps to reproduce

## Instance 1

1. Use metadata when creating a deployment: `now -m ci-build=$SOME_ENV_VAR`
2. The error reported is: `Error! The property ci-build is not allowed in now.json when using Now 2.0 – please remove it.`

## Instance 2

1. Add multiple bits of metadata while creating a deployment: e.g., `now -m branch=$CIRCLE_BRANCH -m build=$CIRCLE_BUILD_URL -m commit=$CIRCLE_SHA1 -m pr=$CIRCLE_PULL_REQUEST -t $NOW_TOKEN`
2. The error reported is: `Error! Failed to validate now.json. Only use properties mentioned here: https://zeit.co/docs/v2/deployments/configuration/`
    - `now.json` is valid as I can deploy by just using `now -t $NOW_TOKEN`
    - I've tried capitalized metadata key names. They cause the same error.

**Comment by zeusdeux** [comment]
Wrt `Instance 2` — If I just do `now -t $NOW_TOKEN`, this succeeds. If I add the metadata it fails. Alternatively, if I perform a `now login` and then run the whole command without `-t $NOW_TOKEN`, it succeeds as well. Colour me confused. 🤔

**Comment by zeusdeux** [comment]
The workaround mentioned on [this thread](https://spectrum.chat/zeit/general/using-meta-alongside-token-causes-deploys-to-fail-with-a-now-json-validation-error~dca2b971-b9fb-4ee5-a8fc-7eb0d2b2d47e) fails as well as you can see [in this failed build on CircleCI](https://circleci.com/gh/zeusdeux/til.mudit.xyz/55?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by zeusdeux** [comment]
Is there a known workaround for this?
[Quoting the values](https://github.com/zeusdeux/til.mudit.xyz/commit/2e4dec5b94b7d342f9b542855a7fb31b560f7dd2) doesn't work either.

**Comment by zeusdeux** [comment]
@paulogdm Could you help with this please? Or help me figure out who to reach out to?

**Comment by paulogdm** [comment]
Can you try to update the CLI?
If you download an example in https://github.com/zeit/now-examples, does it work with `now -m ... - t ...`?

**Comment by zeusdeux** [comment]
@paulogdm I'm on the latest cli version. Haven't tried the examples, I shall and report back.
Though, tbh, [this app](https://github.com/zeusdeux/til.mudit.xyz/blob/master/package.json#L11) where the issue manifests is quite simple. Nothing weird and uses `@now/static` and `@now/node` builders in the recommended way.

**Comment by cb1kenobi** [comment]
This appear to work as expected with Vercel CLI 28.7.2! 🎊
