### ISSUE TITLE
[3] Error: Couldn't find the binary git

### ISSUE THREAD

**Issue by maufurtadoo** [vercel/vercel#1778]
When there is a package that uses a version from github instead of npm, the deploy fails:
Error: Couldn't find the binary git.

My solution was basically switch from a nextjs deploy over a docker build. However, that forces me to fallback into the older version of the api. There is some way to workaround this? As general rule, I will prefer to keep my codebase running with the newest features of the platform...

This is my only problem so far (#devpeopleproblems), for all the rest, Zeit is awesome!

**Comment by paulogdm** [comment]
Hello! I'm excited to announce we finally support GIT in all our deployments!
https://github.com/zeit/now-builders/issues/49
