### ISSUE TITLE
502: NO_STATUS_CODE_FROM_LAMBDA

### ISSUE THREAD

**Issue by pkrawc** [vercel/vercel#1779]
For a `@now/next` build. Simple one route app with only the "@next/sass" builder as a dependency.

**Comment by revskill10** [comment]
Try build on local to see real error ?

**Comment by pkrawc** [comment]
@revskill10 No error on local. It had to do with next/sass compilation. I've just removed next/sass from my build. Issue can be closed or moved to zeit/next repo.
