### ISSUE TITLE
now secrets names limited in length?

### ISSUE THREAD

**Issue by e-founders** [vercel/vercel#178]
As far as I can tell, trying to add a now secret with a name length > 28 characters will fail.

```
now secrets add abcdefghijklmnopqrstuvwxyz01 value
> Success! Secret abcdefghijklmnopqrstuvwxyz01 (sec_eJi9BAO0uYGumSCgIHh7Gxuv) added [899ms]
now secrets add abcdefghijklmnopqrstuvwxyz012 value
> Error! Unexpected error. Please try later. (An unexpected internal error occurred)
```

**Comment by frolic** [comment]
Also just came across this with a nondescript error:

> Error! Unexpected error. Please try later. (An unexpected internal error occurred)

The fix was shortening the secret name.

**Comment by kristianmandrup** [comment]
Any idea for how to resolve #548 ??

**Comment by OlliV** [comment]
The limitation was remove a while back.
