### ISSUE TITLE
error Couldn't find the binary git

### ISSUE THREAD

**Issue by KudohAtsuo** [vercel/vercel#1783]
My NEXT app got this error when it is deployed onto Now server: "Couldn't find the binary git" after 'yarn install something...' according to error log.
I followed the official Now-NEXT deployment configuration of custom server.js use case.
https://zeit.co/docs/v2/deployments/official-builders/next-js-now-next/
Below is my now.json: 
```
{
  "version": 2,
  "builds": [
    { "src": "next.config.js", "use": "@now/next" }
  ]
}
```

And my next.config.js: 

`module.exports = () => ({})`

And my npm scripts:
```
"scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
}
```
My understanding for this error is 'You do not install git'. But my machine is Linux Ubuntu... 

Any help is appreciated.

**Comment by maufurtadoo** [comment]
bro, i just figure it out! 
The binary of git just means that que OS don't have git installed. My workaround was to using this `"gitlab:team/repository"`, this format shouldn't trigger any errors. But, there is a extra step, you need install in your local environment and then be sure that you are not ignoring the` yarn.lock` file in your `.nowignore`. 
As I understood, the `yarn.lock` file stores a different link from the git repository, this other link points to do a zip file, therefore the server of Zeit will be downloading the package from git, without actually using git. :)

PS: Should work on any combination of git provider and package managers.

**Comment by paulogdm** [comment]
Hello! I'm excited to announce we finally support GIT in all our deployments!
https://github.com/zeit/now-builders/issues/49
