### ISSUE TITLE
Specifying "files" in now.json (v1) results in files getting excluded

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [vercel/vercel#1785]
In your docs, it says that `files` is merely an override to add files that are excluded by e.g. `.gitignore`.

But it seems like actually, as soon as one puts anything into `files`, one has to specify ALL files that are supposed to be used for deployment.

Examples:
No `files`
```bash
> ▲ yarn
> yarn install v1.10.0
> [1/4] Resolving packages...
```

With `"files": ["db.json"]`
```bash
> ▲ yarn
> yarn install v1.10.0
> info No lockfile found.
> [1/4] Resolving packages...
```

With `"files": ["db.json", "yarn.lock"]`
```bash
> ▲ yarn
> yarn install v1.10.0
> [1/4] Resolving packages...
```

`create-react-app` also complains about the `public` folder, so I'm guessing that `now-cli` excludes all files except for `package.json` if `files` exists.

If I remove `files` from `now.json` and instead comment out `db.json` in `.gitignore`, deployment works as expected.

now-cli version: 12.1.14

**Comment by leo** [comment]
That is indeed correct. `files` is a relict of Now 1.0, which is why it doesn't work that perfectly. I highly recommend checking out Now 2.0, where we have deprecated all of these options and only offer `.nowignore` for maximum clarity! 😊
