### ISSUE TITLE
WARN using --force  I sure hope you know what you are doing

### ISSUE THREAD

**Issue by peterennis** [vercel/vercel#1794]
I do not know what I am doing!

CLI reports build passes.
Site looks like this:

![capture475](https://user-images.githubusercontent.com/140737/50675993-7eed9d00-0fa6-11e9-8955-f22757386dcf.png)

Following the example for Stencil here: https://github.com/ihackalot/stencil-zeit-now

My component source here: https://github.com/adaept/ae-icons-component

Live on firebase here: https://aeicons.adaept.com/

I read a lot on the site but it is still clear as mud.

1. Can I deploy the build code on now, and how?
2. I have some tests here:
https://zeit.co/adaept/ae-now-app/6v6u7tdk7/source
https://ae-now-app-6v6u7tdk7.now.sh/
How do I get rid of them?
3. Are there docs for using now to deploy Stencil components/apps?
4. Can I deploy a built angular app on now, and how?

I am playing with the idea of using components as lambda functions
but my current status is a strike-out :(

**Comment by paulogdm** [comment]
FYI: https://spectrum.chat/?t=f1f3a310-a7c8-4dbb-85de-7cf0fe51bd7d

1- Yes you can, using the `@now/static-builder` I suppose.
2- `now rm <deployment>` is the CLI command to delete deployments. You can also use [our site]() if you like it more.
3- Not particular to Stencil, but it should work with `@now/static-builder`!
4- Yes you can, with `@now/static-builder`!

Please, take a look at our examples [here](https://github.com/zeit/now-examples). I think `create-react-app`, `Gatsby` and `Docz` will assist you!

**Comment by MehuliK** [comment]
downgrading the npm version to npm@4 worked for me.
