### ISSUE TITLE
Docker mongodb can not connect

### ISSUE THREAD

**Issue by brokolja** [vercel/vercel#180]
This is my dockerfile:

```
FROM ubuntu:latest

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
RUN echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/10gen.list

RUN apt-get update
RUN apt-get install mongodb-10gen

RUN mkdir -p /data/db

EXPOSE 27017 28017
CMD ["usr/bin/mongod", "--smallfiles"]
```

The deployment works but i cant connect to the running mongodb instance from my local machine. Port 28017 is also not reachable.

Testing deployment: https://mongodb-cmjcuzszqz.now.sh/

Thank you very much.

**Comment by leo** [comment]
You shouldn't deploy database services on now. It's only made for applications at the moment. Please use a service like [mLab](https://mlab.com)!

**Comment by brokolja** [comment]
Do you have plans for supporting dbs in future?

**Comment by leo** [comment]
@koljakutschera No. We want to do one thing, but right 😊
