### ISSUE TITLE
Unable to get Apollo Graph endpoint working in Node on Now

### ISSUE THREAD

**Issue by LakshayDuggal** [vercel/vercel#1808]
Hi i am new to now and graphql.
I have a simple apollo client graphql endpoint setup in node.
It runs fine locally when accessing /graphql it shows the graphiql playground but when deployed to now.sh using now command,
the files are just being uploaded and /graphiql endpoint is not showing the UI.
I have start script in the project running index.js and also configured now.json to build all js files but the endpoint seems not to be working.
What am i missing. Please help.
Following is the snapshot of command.
![image](https://user-images.githubusercontent.com/45995948/50819031-d72df180-134e-11e9-92dc-4e3ba664a9bc.png)

**Comment by LiangRenDev** [comment]
Hi, Lak
    Have you solved the issue, after hours of trial, I have found out one workaround for myself, I put all my src code in src so I need to set the routes in src as well otherwise it does not work. But then my API url looks like 'https://server-l6uvj33we.now.sh/src/' 
{
    "version": 2,
    "builds": [{ "src": "src/*.js", "use": "@now/node-server" }],
    "routes": [{ "src": "src/.*", "dest": "index.js" }]
  }

**Comment by juliangruber** [comment]
Looks like this has been solved by the community :)
