### ISSUE TITLE
Idea: implicit `start` command when a server.js file is present?

### ISSUE THREAD

**Issue by TooTallNate** [vercel/vercel#181]
`npm start` works without a `scripts.start` entry in the package.json if there is a `server.js` file in the root. Maybe we should match that behavior and support implicit start in `now` as well?

**Comment by leo** [comment]
Why is npm doing that? Where did this come from?

**Comment by TooTallNate** [comment]
It's just npm's default: https://docs.npmjs.com/cli/start

> If no "start" property is specified on the "scripts" object, it will run `node server.js`.

**Comment by rauchg** [comment]
I don't like magic, but if npm does it, we should do it. We can also add a comment to make clear what's going on :)

**Comment by leo** [comment]
Yea... I don't like it either. But like @rauchg said, I also think we should copy npm.
