### ISSUE TITLE
`.env` file not uploaded despite using --dotenv flag

### ISSUE THREAD

**Issue by te-online** [vercel/vercel#1810]
Following up on an issue with the ~~`--env`~~ `--dotenv` flag in now-cli https://github.com/zeit/now-cli/issues/1646, the bugfix for that seems to have introduced a regression leading to the `.env` file not being uploaded when no value is specified for this particular flag.

Any help is appreciated, since our deployment system cannot be updated with a version newer than 11.4.6 because of this problem.

**Comment by leo** [comment]
I think the flag you are looking for is `--dotenv` – I don't think this behavior ever worked with `--env`.

**Comment by te-online** [comment]
Thanks for your response! I'm sorry, it's a typo in my issue...
This is the command we're using in our deployment service:

`now --dotenv --token $NOW_TOKEN --team $NOW_TEAMNAME`

`.env` file is missing in the deployment created with `now-cli` v. 13.0.0.
In contrast, all env variables are correctly populated when using `now-cli` v. 11.4.6. 
After release 11.4.6 the command stopped working they way it used to work (no other code changed in the deployment source).

**Comment by leo** [comment]
Did you verify that your deployment shows `v1` next to the URL? I will not work with `v2`.

**Comment by te-online** [comment]
I'm sorry, I need some help verifying that 😳. I'm pretty sure it's a v1 deployment/app. But where can I see the version next to the URL? I checked `zeit.co/teams/teamname/deployments` and `now ls appname` on my machine. Both don't show a version.

**Comment by te-online** [comment]
@leo Thanks for taking the time. 😊 

My understanding is this at the moment: There is a breaking change in versions later than 11.4.6, so that they default to deploy as `v2`, even if the project was deployed as `v1` previously. This seems a little counter-intuitive? 

Unfortunately, the latest `now-cli` version still doesn't upload the `.env` file, even when I specify `"version": 1` in my `now.json`. (However, the warning stating I need to add a version to my `now.json`, that I overlooked before, disappeared.)

`dotenv-safe` outputs all the variables as missing and the following statement
```
Also, the following error was thrown when trying to read variables from  .env:
ENOENT: no such file or directory, open '/home/nowuser/src/.env'
```
Seems to clearly indicate that version 13.0.0 doesn't transfer the `.env` file. I'm very confident that this file is present during deployment, because I simply changed the `npm install -g now@{version}` line in our deployment script and it works perfectly fine with version 11.4.6.

Question for me is, do I need to adjust my configuration or is it an actual problem in `now-cli` causing this? There seem to be at least 2 more people experiencing this, from looking at #1646. If it's indeed a configuration issue, I apologize for my ignorance and would appreciate any hints or resources on how to adjust the configuration.

**Comment by codeofsumit** [comment]
I'm having a similar problem in now v2. Worked fine in v1 even though I can't find the docs for it anymore.

```js
> Error! Unknown or unexpected option: --dotenv
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! geoman@1.1.1 release: `now --dotenv=.env.prod`
npm ERR! Exit status 1
```

**Comment by azadoss** [comment]
Any solution?

**Comment by tim-phillips** [comment]
In [an above comment](https://github.com/zeit/now-cli/issues/1810#issuecomment-452306865), @leo is saying that uploading `.env` with the `--dotenv` flag will not work in v2. The solution I found is to use secrets and `now-env`. 

https://zeit.co/docs/v2/deployments/environment-variables-and-secrets
https://github.com/zeit/now-env

see #1842 

(I think for v1 this is still a bug)

**Comment by vadistic** [comment]
I did not feel like retyping secrets this morning... **I present you [`now-dotenv`](https://github.com/vadistic/now-dotenv)** It use Now API to sync your Now Secrets with .env files.

**Comment by styfle** [comment]
Since [Now 18.0.0](https://github.com/zeit/now/releases/tag/now%4018.0.0) you can manage environment variables with `now env` or on the dashboard and then use `now env pull` to write a `.env` file that will be read by `now dev`.

**Comment by styfle** [comment]
Closing since v1 is no longer supported.
