### ISSUE TITLE
Redeploy via Git Hooks

### ISSUE THREAD

**Issue by lukeed** [vercel/vercel#182]
Now that GitHub, GitLab & Bitbucket repos can be deployed, I feel that the natural next step is to introduce (or listen to) git hooks.

AKA, a user sends new commits to their GitHub repo, on the `master` branch. In doing so, `now`, being as smart as it is 😉, knows that its deployment(s) rely on that `repo#master` & then updates itself.

This functionality can be added as a `--auto` or `--hook` flag.

Taking this a step further, we could introduce an "auto-alias" option. So, once automatically re-deployed (via git hook), the project's alias is auto-updated to the latest deployment. 

Perhaps something like:

```
now user/repo#ref --alias name --autodeploy --autoalias
```

**Comment by iaincollins** [comment]
I agree, I would really like this option and would switch some projects over to using now if that was an option. I guess some salient points are:

* I'd want config settings (secrets/env vars) to be 'inherited' from the previous instance.
* For a node project I'd want it to run tests (npm test) and only deploy if they are all passing.
* It would make sense to automatically decommission the previous instance (if not possible to easily detect when it's no longer handling requests, then after X minutes?).

**Comment by david-genger** [comment]
I agree this would be a major push for me to change my workflow to only use NOW, this is the one limitation that holds me back.

**Comment by leo** [comment]
We're keeping our feature roadmap secret, so I'm closing this now - as this repository shouldn't hold any feature requests. Thanks for the proposal, we're considering it!

**Comment by dmoli** [comment]
@leo @david-genger @iaincollins @lukeed any notice about this theme?

I want to use `now` and `git` to the version control... any good practice?

Thanks!

**Comment by dmoli** [comment]
Currently, I work with this logic:

**DEVELOPMENT:**
Script to deploy to *development* environment:

`> git push origin dev && now && now alias dev-domain.now.sh`

- `git push origin dev`: push to the dev branch
- `now`: deploy a new instance
- `now alias dev-domain.now.sh`: point the last deploy uploaded URL to **dev-domain.now.sh**


**PRODUCTION:**
Script to deploy to *production* environment:

`> git merge dev`
`> git push origin master && now alias production-domain.now.sh`

- `git merge dev`: merge the commits from dev to master branch
- `git push origin master`: push to the master branch
- `now alias production-domain.now.sh`: point the last deploy uploaded URL to **production-domain.now.sh**

What do you think?
