### ISSUE TITLE
now login error

### ISSUE THREAD

**Issue by felipebulcao** [vercel/vercel#1829]
Hello! Well I'm really really angry with this bug, I used npm install -g now and it was without error, when I used the now login gave an error saying that it does not exist, I'm from Brazil so the print is in Portuguese.

https://imgur.com/a/7wFGErr

**Comment by paulogdm** [comment]
This is not a `NOW` bug, but how you configured your environment to accept global packages in NPM.
A few hints in [here](https://docs.npmjs.com/downloading-and-installing-packages-globally) and [here](https://stackoverflow.com/questions/31472755/sudo-npm-command-not-found/52087213).
