### ISSUE TITLE
[now-next] Module not found: Can't resolve 'request' when importing firebase database

### ISSUE THREAD

**Issue by yukitch** [vercel/vercel#1830]
I encountered a error below when deploying to now.

ModuleNotFoundError: Module not found: Error: Can't resolve 'request' in '/tmp/5db89640/node_modules/@firebase/database/dist'

My dependencies is only

```
{
  "dependencies": {
    "antd": "^3.12.3",
    "firebase": "^5.7.3",
    "next": "^7.0.2",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  }
}
```

and my now.json is

```

{
  "version": 2,
  "builds": [
      { "src": "next.config.js", "use": "@now/next" }
  ]
}

```

The error occured after install firebase.

**Comment by juliangruber** [comment]
I can't reproduce this, have you tried with the latest version of now-cli? If the error still shows, can you please also share an `index.js` so I can reproduce completely?

**Comment by CarlosBolanos** [comment]
hi.
I'm having the same issue has julian i uploaded my code to a [github repo](https://github.com/CarlosBolanos/bolanos).

i'm using next with redux and firebase
if you add the firebase configuration data in firebase.js and run yarn next it works fine.
but when i do yarn build I'm getting the same error

./node_modules/@firebase/database/dist/index.node.cjs.js
Module not found: Can't resolve 'request' in '...blah.../node_modules/@firebase/database/dist'

**Comment by bolanosdev** [comment]
I'm having the same issue as youkyll.

i created a small github repo (https://github.com/CarlosBolanos/next-redux-firebase)

i was able to deploy to now the part with next and the redux wrapper, but when i require firebase the now cli fail to deploy with the error 'Can't resolve 'request' in '/tmp/73d905f1/node_modules/@firebase/database/dist''.

hope this helps...

**Comment by RyanMilb** [comment]
I'm seeing this issue as well when trying to use firebase with a serverless target in next.config.js.

Thanks for putting that repo together @CarlosBolanos 

[This may be a duplicate issue.](https://github.com/zeit/next.js/issues/6655)

**Comment by samantonis** [comment]
same issue for me , everything works when i run locally , deployment and build works too but i get a 502 when i visit the site. 

url : https://portfolio.samantonis.now.sh

repo to reproduce error : [repo](https://github.com/samantonis/next)

error in the logs:

```
./node_modules/grpc/src/grpc_extension.js Critical dependency: the request of a dependency is an expression
./node_modules/grpc/node_modules/node-pre-gyp/lib/pre-binding.js Critical dependency: the request of a dependency is an expression
./node_modules/grpc/node_modules/node-pre-gyp/lib/util/versioning.js Critical dependency: the request of a dependency is an expression
./node_modules/bytebuffer/dist/bytebuffer-node.js
Module not found: Can't resolve 'memcpy' in '/tmp/7aa87c66/node_modules/bytebuffer/dist'
```

**Comment by Raja0sama** [comment]
Help is here indeed needed because it is not yet been solved

**Comment by skoch** [comment]
My issue occurred during the `next build` phase so I'm inclined to believe it's not `now` related.

`npm i request -D` helped me get over this hurdle. Might not need to save it as a devDependency ... I will test this theory and report back.

**Comment by skoch** [comment]
Confirmed. 

I'd already added `request` as a devDependency and wanted to test to see if it was needed as such.

Steps I took to reproduce:
```
(1) `npm un request`
(2) `next build`
  * success
(3) `next export`
  * success
(4) `now`
  * fail
  * log snippet below
(5) `npm i request`
(6) `now`
  * success
```

Log snippet:
```
2019-05-02T13:27:25.224Z  running "npm run now-build"
2019-05-02T13:27:25.431Z  > project-x@1.0.2 now-build /tmp/3c29403
                          > next build
2019-05-02T13:27:25.912Z  Creating an optimized production build ...
2019-05-02T13:27:25.913Z
2019-05-02T13:27:25.914Z  Loading  ./config/.production.env
2019-05-02T13:27:46.886Z  Failed to compile.
2019-05-02T13:27:46.887Z  ./node_modules/@firebase/database/dist/index.node.cjs.js
                          Module not found: Can't resolve 'request' in '/tmp/3c29403/node_modules/@firebase/database/dist'
```

**Comment by samantonis** [comment]
@skoch when I was looking into this about a month ago I found that it is most likely a firebase related issue, tried solving it but no luck back then

**Comment by samantonis** [comment]
I also tried deploying static version but didn't get that working either (the website builds and loads fine , but firebase stuff fails )

**Comment by mtrabelsi** [comment]
same thing for me when using IOTA library, time to find a serious deployment tools, we pay premium for shitty-crappy-weirdo tools

**Comment by Raja0sama** [comment]
Use this library GitHub repo 
https://github.com/dksami/NextBigThing
and use whatever library you need and it will work however I am afraid that database firebase might not work / 
if fix? star the repo
Feel Free to Fork @mtrabelsi  @samantonis @skoch

**Comment by sudipt1999** [comment]
I am using firebase in nextapp and unable while deploying to ZEIT it shows error 
```javascript
 ./node_modules/@firebase/database/dist/index.node.cjs.js
                          Module not found: Can't resolve 'request' in '/tmp/6d82ffed/node_modules/@firebase/database/dist'
2019-07-08T17:56:01.203Z  > Build error occurred
2019-07-08T17:56:01.203Z  Error: > Build failed because of webpack errors
                              at Object.build [as default] (/tmp/6d82ffed/node_modules/next/dist/build/index.js:192:15)
                              at <anonymous>
                              at process._tickCallback (internal/process/next_tick.js:188:7)
```

Error log comes out to be this,

My package.json file looks like this 
```
{
  "name": "suvidha-next",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "now-start": "node server.js",
    "dev": "node server.js",
    "build": "next build",
    "start": "node server.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@material-ui/core": "^4.1.3",
    "@zeit/next-css": "^1.0.1",
    "cross-env": "^5.2.0",
    "express": "^4.17.1",
    "firebase": "^6.2.4",
    "next": "^8.1.0",
    "react": "^16.8.6",
    "react-autosuggest": "^9.4.3",
    "react-dom": "^16.8.6",
    "react-google-invisible-recaptcha": "^0.2.11",
    "react-icons": "^3.7.0",
    "react-modal": "^3.8.2",
    "react-multi-carousel": "^1.4.6",
    "react-redux": "^5.0.1",
    "react-scroll-locky": "^1.5.0",
    "react-scroll-up-button": "^1.6.4",
    "react-select": "^3.0.4",
    "react-tooltip": "^3.10.0",
    "redux": "^3.6.0",
    "redux-devtools-extension": "^2.13.2",
    "redux-persist": "^5.10.0",
    "url-loader": "^2.0.1"
  }
}

```

and next-config.js looks like this
```
const withCSS = require('@zeit/next-css')

module.exports = withCSS({
  target: 'serverless',
  webpack: function (config) {
    config.module.rules.push({
      test: /\.(eot|woff|woff2|ttf|svg|png|jpg|gif)$/,
      use: {
        loader: 'url-loader',
        options: {
          limit: 100000,
          name: '[name].[ext]'
        },
        
      },
      
     
    },
    )
    return config
  }
},

)

```
Hope it helps for solving the error.

**Comment by diogoviannaaraujo** [comment]
Still getting the error

**Comment by brandontle** [comment]
@diogoviannaaraujo I had the same issue for a week and just fixed it. Try:

* Installing next@9.0.4-canary.7+
* Installing Node v10.16.2+ (can use nvm)
* Deleting your node_modules folder and installing again (`yarn` or `npm i`)
* In your now.json file, put: 
```  
//...
"version": 2,
"name": "project-name",
"builds": [
    {
      "src": "package.json",
      "use": "@now/next@canary",
      "config": { "maxLambdaSize": "10mb" }
    }
  ],
//...
```

Not sure exactly which step fixed it for me, but after doing all of them, my app now deploys via `now` and `now dev` for Next 9.

**Comment by styfle** [comment]
I confirmed the original issue has been resolved in the latest `@now/next`.

```
mkdir example && cd example
yarn init -y && yarn add antd firebase next react react-dom
mkdir pages
echo "module.exports = () => 'hello world'" > pages/index.js
echo '{"version":2,"builds":[{"src":"package.json","use":"@now/next"}]}' > now.json
now
```

**Comment by tofarfar** [comment]
@styfle  Hi, if you import firebase/database into pages/index.js, it won't work.
I just copied your code, it worked as expected. Then I added `import firebase from 'firebase/app'; import 'firebase/database'`, it breaked.

```2019-09-01T02:39:16.467Z  Creating an optimized production build ...
2019-09-01T02:39:16.468Z  
2019-09-01T02:39:25.656Z  Failed to compile.
2019-09-01T02:39:25.656Z  
2019-09-01T02:39:25.657Z  ./node_modules/@firebase/database/dist/index.node.cjs.js
2019-09-01T02:39:25.657Z  Module not found: Can't resolve 'request' in '/tmp/48ba7771/node_modules/@firebase/database/dist'
2019-09-01T02:39:25.657Z  
2019-09-01T02:39:25.657Z  > Build error occurred
2019-09-01T02:39:25.658Z  Error: > Build failed because of webpack errors
2019-09-01T02:39:25.658Z      at build (/tmp/48ba7771/node_modules/next/dist/build/index.js:7:847)
2019-09-01T02:39:25.658Z      at <anonymous>
2019-09-01T02:39:25.658Z      at process._tickCallback (internal/process/next_tick.js:188:7)```

**Comment by styfle** [comment]
Hi @kejiweixun 

Thanks for the repro steps!

I've identified the issue is in node-file-trace: https://github.com/zeit/node-file-trace/issues/58

The workaround is to run `npm install request` or `yarn add request`.

**Comment by styfle** [comment]
On second look, this is not an issue with `@zeit/node-file-trace` because `request` was never installed so it won't be emitted in the traced files.

The workaround is to run `npm install request` or `yarn add request`.

This bug does not affect `@now/node` (thus not an issue with `node-file-trace`), only `@now/next`.

It is a bug in the Next.js webpack bundling as seen in the error message "Build failed because of webpack errors".

----

**Update**: I submitted a PR to [add request](https://github.com/firebase/firebase-js-sdk/pull/2142) as an optional dependency. It looks like the firebase team is going to [remove the conditional require](https://github.com/firebase/firebase-js-sdk/pull/2144) completely. So this will likely be fixed in the next firebase release.

**Comment by Timer** [comment]
Fixed in https://github.com/zeit/now/pull/2924, currently on canary builder.
