### ISSUE TITLE
_logs and _src urls show 404

### ISSUE THREAD

**Issue by apieceofbart** [vercel/vercel#1836]
I try to follow the docs https://zeit.co/docs/v2/deployments/basics/. I'm on this paragraph: 
> It is important to understand that Now keeps track of sources and outputs. If we add the special pathname /_src at the end of the deployment, we will be able to inspect them:

However now matter how I tried appending `_src` or `_logs` shows 404 page. I even made a mistake and `now-cli` pointed me to the logs page that is 404.

**Comment by paulogdm** [comment]
Hello Apiece!
Let's try the following:

- Ensure that you are logged in `zeit.co`.
- Run `now whoami` to guarantee you are in the same context as the site.
- Try to access `deployment.now.sh/_src`.

If you just want to see the logs quickly, you can add `"public": true` to your `now.json`. Be aware this will make your deployment source files and logs publicly available.

**Comment by paulogdm** [comment]
I am really sorry @apieceofbart, but we are not able to reproduce the issue. There must be something related to context. Can you go to your [dashboard](https://zeit.co/dashboard) and try to access the source from your deployment there?

Also, I've created this issue: https://github.com/zeit/docs/issues/413

**Comment by juliangruber** [comment]
Closing because inactive
