### ISSUE TITLE
Add "scope" to now.json

### ISSUE THREAD

**Issue by mxstbr** [vercel/vercel#1839]
I am a member of multiple teams, and it has happened to me many times that I deploy a project with the wrong team.

It would be great to be able to specify a whitelist of possible teams to deploy a certain project with in the `now.json`, for example:

```JSON
{
  "teams": ["space-program", "mxstbr"]
}
```

**Comment by lqmanh** [comment]
Second this :+1:

**Comment by leo** [comment]
This property is most likely gonna be called `scope` and we'll have to rename `--team`. Because `--team leo` makes no sense, as a personal account is not a team.

**Comment by mxstbr** [comment]
That makes sense to me! 👍

**Comment by efleurine** [comment]
Second this ++

**Comment by leo** [comment]
You can now set `scope` in `now.json` for this (details [here](https://zeit.co/docs/v2/deployments/configuration/#scope)).
