### ISSUE TITLE
How can I write files to the local storage?

### ISSUE THREAD

**Issue by brandonmp** [vercel/vercel#184]
My app downloads an image to local storage, then uploads it elsewhere. 

When i try to download to `./`, I get `permission denied`

When I try to download to `./tmp`, the subsequent `read` operation (for the upload) fails.

I see a few issues in this repo w/ similar problems, but they're all dealing w/ `next.js`, which I'm not using.

Is writing to local storage possible?

**Comment by OlliV** [comment]
Writing to `/tmp` is possible but you can only assume the file is accessible to the same process that wrote it there. I.e. there is no persistent storage.

**Comment by brandonmp** [comment]
okay, thanks for quick response @OlliV -- ephemeral storage is fine for my use case.  

the app writes & reads from `tmp` fine in local environment but deploying to `now`, it fails the `read` part of that. I'm sure it's some peculiarity in my code, so I'll have to dig-in and figure out why.

**Comment by lprhodes** [comment]
@brandonmp I'm in the exact same position as you with `/tmp` and `now`. Did you find a work-around?

**Comment by pranaygp** [comment]
I don't know if this helps your use case, but I was working on a project that needed persistent storage, and read them later, between instances. I ended up just storing the files on a different service (like s3, instead of the fs) since perf wasn't that big of a deal to me.

**Comment by brandonmp** [comment]
actually i think i ended up doing the same thing (ie, writing to s3)
