### ISSUE TITLE
Is my now.json not being recognized?

### ISSUE THREAD

**Issue by do-kevin** [vercel/vercel#1841]
Hi, I'm new to using Next.js and Now. I'm trying to deploy my Next site under an explicit name, but it seems like my now.json is not being read. I've also tried placing in the version property but it kept telling me to remove it and then add it back in.

<img width="216" alt="screen shot 2019-01-21 at 6 31 02 pm" src="https://user-images.githubusercontent.com/40156784/51508775-99e44d80-1dab-11e9-9d41-f4aec9cf3fce.png">

package.json:
```
"scripts": {
  "dev": "next",
  "build": "next build",
  "export": "next export",
  "deploy": "cd out && now"
}
```

now.json:
```
{
    "type": "static",
    "name": "next-portfolio",
    "public": true
}
```

<img width="1117" alt="screen shot 2019-01-21 at 6 30 50 pm" src="https://user-images.githubusercontent.com/40156784/51508790-a9639680-1dab-11e9-8a37-2d08f950e978.png">

What am I doing wrong?

**Comment by fschroiff** [comment]
You need a `now-build` step in `scripts`. 

```
"scripts": {
  "dev": "next",
  "build": "next build",
  "now-build": "npm run build",
  "export": "next export",
  "deploy": "cd out && now"
}
```

**Comment by paulogdm** [comment]
As the error said, you are missing a `"version"` in your `now.json`:
```
{
    "version": 1,
    "type": "static",
    "name": "next-portfolio",
    "public": true
}
```
I recommend that you try [Now 2.0](https://zeit.co/docs/v2/platform/upgrade-to-2-0), it should be as simples as:
 ```
{
    "version": 2,
    "name": "next-portfolio",
    "public": true,
    "builds": [
         {"src": "package.json", "use": "@now/static-build" }
    ]
}
```

Please, take a look at our example [here](https://github.com/zeit/now-examples/tree/master/nextjs-static).
