### ISSUE TITLE
Unknown or unexpected option: --dotenv

### ISSUE THREAD

**Issue by steida** [vercel/vercel#1842]
It was there. Now it seems to be removed. What is the replacement? Thank you.

**Comment by paulogdm** [comment]
We deprecated `--dotenv`, for security reasons. Please, use [now secrets](https://zeit.co/docs/v2/deployments/environment-variables-and-secrets/) and env. variables instead.

**Comment by steida** [comment]
Temp workaround for the others:

```"deploy": "env-cmd .env now -e API_ENDPOINT -e API_SECRET -e PRISMA_ENDPOINT -e PRISMA_SECRET"```

Not sure how this is safer. 

Or how `now-secrets.json` is safer than `.env.production`

**Comment by steida** [comment]
Oh, I see, maybe. It's because secrets can be set by one developer while the others are using only keys. OK.

**Comment by paulogdm** [comment]
Exactly.
Not only that, you avoid having a file in the server with all your passwords, api urls, etc. Which is not a good thing...

**Comment by steida** [comment]
But then `now-secrets.json` should be deprecated as well, no?

**Comment by paulogdm** [comment]
Please, read the [docs](https://zeit.co/docs/v2/deployments/environment-variables-and-secrets/) that I linked you. `now secrets` is a command from the CLI to safely store environment variables that you can use in `now.json`: 
`now secrets add secretname secretvalue`
```
{
  "env": {
      "environment_variable": "@secretname"
   }
}
```

**Comment by steida** [comment]
I meant https://github.com/zeit/now-env#secrets

> Then create a now-secrets.json with the secrets names and values.


>

**Comment by paulogdm** [comment]
Oh, `now-env` is a tool to easily bridge `dotenv` with `now secrets` standard. Well, we are maintaining it just fine...
