### ISSUE TITLE
error in depolying

### ISSUE THREAD

**Issue by Ikhan** [vercel/vercel#1845]
This is the error I'm getting below. 
![screen shot 2019-01-25 at 5 52 10 pm](https://user-images.githubusercontent.com/475993/51745812-0de36600-20ca-11e9-8016-f50d433f3f6f.png)

And this is my package.json file

`{
  "scripts": {
    "dev": "node server.js",
    "build": "next build",
    "start": "NODE_ENV=production node server.js"
  },
  "name": "expertiphoneipadrepairnyc",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@zeit/next-css": "^1.0.1",
    "axios": "^0.18.0",
    "body-parser": "^1.18.3",
    "express": "^4.16.4",
    "fs": "0.0.1-security",
    "head": "^1.0.0",
    "isomorphic-fetch": "^2.2.1",
    "next": "^7.0.2",
    "nodemailer": "^5.1.1",
    "pm2": "^3.2.9",
    "react": "^16.7.0",
    "react-dom": "^16.7.0"
  },
  "devDependencies": {},
  "author": "imran khan <mmmimran@gmail.com>",
  "license": "ISC",
  "keywords": [],
  "description": ""
}
`

**Comment by paulogdm** [comment]
There are a few dependencies that concerns me:
- `"pm2": "^3.2.9"`. Are you trying to use PM2 in Now 2.0?
- ` "express": "^4.16.4"`. You don't need custom servers while serving a Next.JS application in 2.0. Take a look at https://zeit.co/guides/custom-next-js-server-to-routes/
- `nodemailer": "^5.1.1"`. Make sure you are not using it to open an SMTP server in a lambda.

What is the output of your logs?

**Comment by Ikhan** [comment]
Thanks @paulogdm so far all deployment was success. But I'm getting "This site can’t be reached"

**Comment by paulogdm** [comment]
That is really strange, can you share the URL with me?

**Comment by Ikhan** [comment]
https://expertiphoneipadrepairnyc-1ec4ef8c7.now.sh/

**Comment by paulogdm** [comment]
What the logs show you? https://expertiphoneipadrepairnyc-1ec4ef8c7.now.sh/_logs

**Comment by Ikhan** [comment]
![screen shot 2019-01-25 at 7 47 27 pm](https://user-images.githubusercontent.com/475993/51751155-2491b900-20da-11e9-97d8-5c9738079b9a.png)

**Comment by paulogdm** [comment]
1- You need your Next version to be greater than 8 (eg: `"^8.0.0-canary.11"`).
2- Include `"now-build": "next build"` in `"scripts"`.
3- Edit `next.config.js` to include `{"target": "serverless"}`
4- Don't forget `{ "src": "package.json", "use": "@now/next" }`

**Comment by Ikhan** [comment]
Thanks @paulogdm worked finally.
