### ISSUE TITLE
Feature Request: cache now-cli downloads

### ISSUE THREAD

**Issue by balupton** [vercel/vercel#1846]
As `npm install now` runs a script that then tells now to download itself, it would be nice if it dumped the download in a cache on the computer (say `~/.cache/zeit/now/`) so that future installations don't need to fetch the download again.

This would be way faster for people not in USA. Australians, for instance, have a terribly slow npm experience.

This slow down is exacerbated by yarn, which seems any change to any dep will cause a several second hang on now while it does its thing.

**Comment by liudonghua123** [comment]
I go through the code and find that it always download the binary each time. And I can not set network proxy either.
So I first made a pr to support proxy, see https://github.com/zeit/now-cli/pull/1844, I will try to made a download cache support pr. 😃

**Comment by mightyiam** [comment]
It takes me around 16 minutes(!).

Update: it took me one minute and ten seconds now.

**Comment by mightyiam** [comment]
Just randomly came across this:

![Screenshot from 2019-03-21 10-14-27](https://user-images.githubusercontent.com/635591/54731663-2059b780-4bc2-11e9-9528-32ab57b9668d.png)

https://docs.cypress.io/guides/getting-started/installing-cypress.html#npm-install

It's open source, so perhaps you could reuse some of their implementation.

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!
