### ISSUE TITLE
How to hide js suffix for @zeit/node builder?

### ISSUE THREAD

**Issue by abnerlee** [vercel/vercel#1847]
My file structure is 
```
- api
   |- test.js
```

now.json is like 
```json
"builds": [
    { "src": "api/*.js", "use": "@now/node" },
    { "src": "./static", "use": "@now/static" }
  ]
```

After run `now`, url `api/test.js` is deployed, but can I deploy using path `api/test` ?

**Comment by paulogdm** [comment]
If I understand your question correctly, you are trying to make `api/test.js` available through `/api/test`, is that correct?
If so, you can do:
```
"routes": [
  {"src": "^/api/test$", "dest": "/api/test.js"},
  {"src": "^/static/(.+)$", "dest": "/static/$1"}
]
```

**Comment by rauchg** [comment]
Another option I like @paulogdm @abnerlee is to use directories with an `index.js` file inside. You get the behavior you want out of the box, without the need to define custom routes ;)
