### ISSUE TITLE
What are the criteria for "light sleep"?

### ISSUE THREAD

**Issue by backflip** [vercel/vercel#189]
When does the [light sleep](https://github.com/zeit/now-cli/issues/146#issuecomment-263239533) mode kick in? And how does it work exactly (i.e. what's the usual time it takes to restart a typical express.js application)?

**Comment by OlliV** [comment]
Currently we are mainly monitoring whether you have incoming traffic. If you do not have any traffic for some time (the exact time and metrics is subject to change) then your deployment will be frozen. When there is any incoming traffic the deployment is up again in a matter of seconds + the time it takes to initialize your application.

You can measure the exact time yourself by deploying something and then leaving the deployment untouched for a day. Generally the goal is to make it so fast the user won't notice anything odd. At least currently we don't ever snapshot the process state, so it also requires that your application is somewhat optimized to accept requests early as possible.

**Comment by backflip** [comment]
Hey @OlliV, a `next.js` application I just created takes about 20s to start. However, it might be waiting for another instance providing the API. 

The app is based on https://github.com/zeit/next.js/tree/master/examples/ssr-caching and uses `static async getInitialProps` to query another now.sh instance proxying the contentful API. Any chance I could speed this up?

**Comment by OlliV** [comment]
I have no idea off the top of my head. You could ask someone on the slack https://zeit.chat/
or DM me there and we can try to look into it together.

**Comment by leo** [comment]
If it's a big app, the building part is probably the one that takes the most time. We're working on improving the performance of Next.js!

**Comment by backflip** [comment]
Sounds good! Anything I can do in the meantime? I fear that the 20s could negatively influence the Google pagerank, e.g., if the crawler has to wait for the machine to wake up. Would it be okay if I implement some kind of (outside) polling mechanism preventing it from going to sleep?

@OlliV, thanks a lot for the offer! I'll try to properly prepare/document everything and provide you with links to the code.

**Comment by leo** [comment]
Oh - what? I don't think we're building on start. Sorry, I think I got that wrong.

**Comment by rlindskog** [comment]
@OlliV Does path aliasing help mitigate this issue if aliasing other [NOW](https://zeit.co/docs/features/path-aliases#5.-universal) instances?

**Comment by jamo** [comment]
Similarly to other aliases; you may control the sleep with `now scale`
Otherwise, we use multiple factors including traffic patterns for putting deployments to light sleep.
