### ISSUE TITLE
 The lambda function size (25.55mb) exceeds the configured limit (5mb).

### ISSUE THREAD

**Issue by demouserforsale** [vercel/vercel#1890]
> You may increase this by supplying `maxLambdaSize` to the build `config`

I am using now v2 with typescript and node@canary and I can't add "maxLambdaSize" to config. I don't think my lambda size is THAT big, it's just a 10+ typescript files, one function. I will inspect my packages, but I deployed this project yesterday and it was fine. 
In fact, outside of 2 packages "@google-cloud/storage" and "sharp" I think I removed many things in my code. 

How do I deploy, if I wouldn't be able to find the source of the problem?

**Comment by paulogdm** [comment]
Please, take a look at customizable lambdas size [here](https://zeit.co/blog/customizable-lambda-sizes). Do notice this may hurt performance!

**Comment by demouserforsale** [comment]
Thank you very much! I missed it in a docs, and it was driving me crazy! Perhaps it should be stated more clearly that now "config" belongs to "builds"?

Also my deployment was fine without sharp, and I found it in their docs that sometimes it's hard to deploy with sharp as dependency when building with yarn. Maybe it will help someone in the future. [https://sharp.pixelplumbing.com/en/stable/install/#heroku](url)
