### ISSUE TITLE
Pass-through and/or Error handling mechanism in `now.json` `routes`

### ISSUE THREAD

**Issue by NathanielHill** [vercel/vercel#1891]
Right now, it's really not possible to have a satisfactory error handling situation.

Currently if an incoming request matches a `src` regular expression, it's passed to the lambda or static files specified in `dest`. If there is no match, a zeit 404 page is returned. There is no option to handle the error yourself.

This means we can't do something as straightforward as `{ "src": "/api/(.*)", "dest": "/api/$1" }` if we wish to handle 404 errors ourselves.

So, at the moment our `routes` specification needs to be much more verbose than optimal.

I propose a pass-through mechanism which would mean if a request matches a regex and there is no matching handler it gets passed down the line to each regex that matches.

If there is no match, perhaps we could specify an error handling page at the bottom. (i.e. if the last `src` is a Next app, passing to the main entry point would let the app handle the error)

This would mean we could do something as simple as:

```
{ "src": "/api/(.*)$", "dest": "/api/$1" },
{ "src": "/(.*)", "dest": "/www/$1", "errorHandler": "/www/error" }
```

And never have to worry about a customer getting a zeit page.

Pass through + errorHandler for each route should be able to solve a lot of current routing problems.

**Comment by NathanielHill** [comment]
Now that I think about it, the pass-through doesn't seem strictly necessary. It could be nice, but maybe confusing.

Just being able to specify a `errorHandler` lambda for each route would work. You could just build one and use it for each route if desired. You should be able to get error status from `req` object and return your custom error page using string templates :+1:

Even simpler, would be just allowing a single global `errorHandler` lambda, which would probably suffice.

**Comment by dav-is** [comment]
We've been discussing this issue internally. It's quite an involved issue so I can't exactly comment on the timeline, but something like this is planned.

**Comment by NathanielHill** [comment]
@dav-is Awesome!

I believe a simple option to specify a global error handler lambda would be the simplest and would probably work quite well.

Spectrum conversation: https://spectrum.chat/zeit?thread=7fc3cf00-3883-4ad1-ab3a-44a87f55cb09

**Comment by revskill10** [comment]
@NathanielHill How about routing error based on status code as i see it's more powerful.

**Comment by NathanielHill** [comment]
@revskill10 I'm not actually sure what you're proposing :thinking: 

I don't see how you could get more powerful than my simplest suggestion (without adding massive complexity)

I propose being able to specify a lambda to handle any routing errors (are there any besides 404?).

This lambda would receive both `req` and `res` objects just like any other lambda, so you could reroute conditionally or display any dynamic content you wanted.

I suppose another related proposal would be a global error handler lambda, which would be passed any failed requests and allow you to craft a custom response. I'm thinking in particular the common 502 error that happens when your lambda crashes.

@dav-is

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
