### ISSUE TITLE
14.0.0-14.0.2 does not work (npm/Windows)

### ISSUE THREAD

**Issue by fu-sen** [vercel/vercel#1894]
I upgraded now cli to 14.0.0 using npm on Windows, but now cli does not work at all:
![now-cli-1400](https://user-images.githubusercontent.com/5434159/52891562-22011b80-31cf-11e9-8915-7fb6970cb08c.jpg)
You do not have to worry about the upgrade time. I ran this after I booted Windows.

This problem can be temporarily avoided by downgrading to 13.1.3:
```
 npm install -g now@13.1.3
```

**Comment by paulogdm** [comment]
@subtleGradient contributed with this:
```
(function (exports, require, module, __filename, __dirname) { MZ�
                                                                ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

**Comment by fu-sen** [comment]
I understood. I am waiting for the reflection of this renovation.
This issue will keep Open until we can see improvements.

**Comment by deebov** [comment]
the same issue on Windows

**Comment by deebov** [comment]
I've tried v13.1.3 but it didn't work

**Comment by corlaez** [comment]
Same issue here. It is severe I hope you can fix it soon

windows 10
node v10.14.2

I also got it fixed with v13.1.3. now desktop was still confused, but now-cli did the job.

**Comment by fu-sen** [comment]
@deebov The problem you encounter is different from this issue.
(My Now CLI worked normally until 13.1.3)

Please proceed with problem solving by either of the following:
- Go to Spectrum chat and consult (Recommend): https://spectrum.chat/zeit
- Establish New issue

**Comment by fu-sen** [comment]
@lrn2prgrm If you are using Now Desktop, you can stop automatic updating of Now CLI:
https://zeit.co/docs/v1/guides/updating-now-cli

Now Desktop and installed by npm or yarn are different Now CLI apps.
It can cause another problem:
https://github.com/zeit/now-cli/issues/1809

**Comment by fu-sen** [comment]
I confirmed the release of 14.0.1-canary.1 and tried it, but this problem is ongoing:
![2019-02-26 08 59 44](https://user-images.githubusercontent.com/5434159/53377491-8c6f4400-39a5-11e9-98c4-a4f029fb0082.jpg)

It was released in 14.0.1. Therefore **14.0.1 is still a problem.**

**Comment by TLA020** [comment]
Indeed doesn't work here either

**Comment by fu-sen** [comment]
I tried 14.1.0-canary.2 but the problem is still ongoing:
![2019-02-28 09 52 02](https://user-images.githubusercontent.com/5434159/53533625-ebb48c00-3b3e-11e9-85dd-f0ac64a21c94.jpg)

So 14.1.0 will be released soon will still have problems. (Edit this post after publishing)

**Comment by fu-sen** [comment]
I tried 14.1.0-canary.2 but the problem is still ongoing:
![2019-02-28 09 57 37](https://user-images.githubusercontent.com/5434159/53533779-801eee80-3b3f-11e9-9f80-250a69ae8fd8.jpg)

**Comment by fu-sen** [comment]
I tried 14.1.0-canary.3, This problem is ongoing
![2019-03-01 09 32 46](https://user-images.githubusercontent.com/5434159/53608244-4b756a80-3c05-11e9-8cfb-938eb0fbe5e7.jpg)
:

**Comment by tlhfckoctbcr** [comment]
Still an issue for me as well. Downgrading to 13.x works in the meantime.

**Comment by fu-sen** [comment]
14.0.2 has been released, but this problem is ongoing:
![2019-03-01 21 45 49](https://user-images.githubusercontent.com/5434159/53639125-b22d6f00-3c6b-11e9-91a7-c5c19f58f18f.jpg)

**Comment by rivy** [comment]
"now\download\dist\now" is missing/empty.
But, as a workaround, [`scoop`](https://github.com/lukesampson/scoop) can be used to install the `now-win.exe` directly with:

```
C:\>scoop install "https://raw.githubusercontent.com/rivy/scoop-bucket/master/now.json"
```

### Additional info

When installed via `yarn`, the "now.cmd" file contains:

```
@"%~dp0\..\..\..\..\..\Yarn\Data\global\node_modules\.bin\now.cmd"   %*
```

That ".bin\now.cmd" file then uses `node` to run "%~dp0\..\now\download\dist\now", but that final file is completely empty:

```
C:>msls -Al node_modules\now\download\dist
total 32M
-rw------a  1 Roy              572k Mar  2 12:40 index.js
-rw------a  1 Roy                 0 Mar  2 12:46 now
-rwx-----a  1 Roy               31M Mar  2 12:46 now.exe*
```

**Comment by AndyBitz** [comment]
Issue got fixed by https://github.com/zeit/now-cli/pull/1922 in release `14.1.0-canary.4`.

**Comment by fu-sen** [comment]
Awesome work!:
![2019-03-04 09 51 27](https://user-images.githubusercontent.com/5434159/53704880-ab694c80-3e63-11e9-8408-b511f275724c.jpg)
