### ISSUE TITLE
webpack analyzer doesn't work as expected

### ISSUE THREAD

**Issue by deebov** [vercel/vercel#1897]
I am trying to analyze bunlde sizes. but it seems that webpack bundle analyzer doesn't work as expected. Or maybe I am doing something wrong. I cloned https://github.com/arunoda/learnnextjs-demo.git. go to the`markdown-blog` branch. And yeah I came from https://nextjs.org/learn/excel/lazy-loading-components/setup . 
Expected behavior: 
![image](https://user-images.githubusercontent.com/28673719/52913996-24559980-32e5-11e9-91f8-8ca0d6560ce3.png)

Current behavior:
![image](https://user-images.githubusercontent.com/28673719/52914001-39322d00-32e5-11e9-8cb3-acc6738f2a80.png)

**Comment by paulogdm** [comment]
Can you please post this on https://spectrum.chat/next-js or https://github.com/zeit/next.js
This is not related with `now-cli`.
