### ISSUE TITLE
The first execution of now-dev limited

### ISSUE THREAD

**Issue by markozxuu** [vercel/vercel#1899]
Hi, unfortunately `now-dev` has some problems that impede me from using it in my application of chat 💔 😿 

## General remarks 👁 

`now-dev` does not support `now secret`, apparently it does not affect the compilation of `ncc` if we have now secret in our file now.json Ideally, **be warned that it does not support now-dev before compiling** because this could make users believe that "now secret" is compatible, which is not for the moment :[

## Main problems 🙍 

- Overly long compile times

## Overly long compile times

**NOTE:** the gif does not represent the total compilation time :]

![long-compile](https://media.giphy.com/media/oyQ8O89LD2cByFhS7t/giphy.gif)

`now-dev` has problems compiling with projects with `package.json` too long, the compilation times of `ncc` can be extended to **2:37:11** which has resulted that lambda never load our project

Example of `auth-chat`

![carbon](https://user-images.githubusercontent.com/16585386/52918945-a1bbe280-32c2-11e9-86f1-9dcb80793039.png)

### Temporary solution 

Recommendations: when `now-dev` is used, a `user` and a `ncc` folder is generated, every time I use now-dev I recommend removing those 2 folders, I've noticed that it has some problems related to the cache

for some strange reason, if we remove **only one dependency** and then reinstall the compilation time of `ncc` it will be much smaller than **2:37:11** gives as it turns out in the lambada loading correctly

with that we rule out that the problem **is not the number of dependencies in your package.json**
this relation to the first execution of lambda I do not know if the first execution is limited or something similar.

**Comment by rauchg** [comment]
Assigning @TooTallNate

**Comment by TooTallNate** [comment]
This appears to happen when the `node_modules` directory exists and is very large. Looking into the fix.

**Comment by markozxuu** [comment]
this problem was already solved thanks to the latest changes @TooTallNate @amio. The compilation time of `ncc` has just improved in this last binary, the waiting times were significantly reduced 🎉
