### ISSUE TITLE
index.js source code displayed instead of deployed app on url.

### ISSUE THREAD

**Issue by JessTaDa** [vercel/vercel#1901]
Hello,

I have tried to deploy my app using the now-cli. Terminal shows the deployment is successful but when I visit the deployed app with the url link, I just see the source code of my index.js file displayed. My node app deploys successfully on localhost:5000 though, so not sure how to make this work. Any tips?

I have tried adding a now.json file stating the use of version 1 & 2 but it still doesn't work.

Thanks for any help!

**Comment by KBPsystem777** [comment]
Hi @JessTaDa! this happened to me a while ago when I deployed an Express server using Now-cli. The resolution I did it to define the `build` and `routes` location in the `now.json` file. Like this:

```
{
    "version": 2,
    "name": "nodejs-express",
    "builds": [
        { "src": "index.js", "use": "@now/node" }
    ],
    "routes": [
        { "src": "/(.*)", "dest": "index.js" }
    ]
}
```


You may check  out this page for details: https://zeit.co/examples/nodejs-express

**Comment by paulogdm** [comment]
Please, for future questions, use our [community chat](zeit.co/chat).

**Comment by jaypokharna** [comment]
Recently I have faced this issue too and found a simple solution to it.
Just create a vercel.json file in the folder with your index.js

{
    "version": 2,
    "builds": [
        {
            "src": "./index.js",
            "use": "@vercel/node"
        }
    ],
    "routes": [
        {
            "src": "/(.*)",
            "dest": "/"
        }
    ]
}

put this code into it 
and just execute the command "vercel" into your terminal , your application will be deployed and you can check it out through the production link.
[vercel.json](https://github.com/vercel/vercel/files/14383699/vercel.json)

**Comment by rohithverma-dev** [comment]
https://github.com/rohithverma-dev/node-express-Vercel

**Comment by abhishek98s** [comment]
### **While using ts**
Had same problem "compiled source code(index.js) displayed instead of deployed app"
- solve by exporting the app 

at the end of the index.ts or index.js export the app

```
export default app;
```

### vercel.json
```
{
    "version": 2,
    "builds": [
        {
            "src": "src/index.ts",
            "use": "@vercel/node"
        }
    ],
    "routes": [
        {
            "src": "/(.*)",
            "dest": "src/index.ts"
        }
    ]
}
