### ISSUE TITLE
Now on WSL Error: spawn xsel EACCES

### ISSUE THREAD

**Issue by tracy-codes** [vercel/vercel#1902]
With using now 14.0.0 on WSL Ubuntu, I get the following error:
![examsim-error](https://user-images.githubusercontent.com/31976538/52932166-2848e200-330c-11e9-8737-67d6c44fde93.png)

I'm running Node v11.9.0 & npm v6.5.0. I've tried rolling back to now v13.1.3 and still encountered the same error as well. Below a text version of the error:
```shell
Error! An unexpected error occurred!
  Error: spawn xsel EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19) Error: spawn xsel EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

The odd thing is, is that my build is still triggered and successfully builds. It's just that the CLI doesn't complete it's process and in cases where I want to alias, it won't work due to this error. Some help with this would be much appreciated!

**Comment by paulogdm** [comment]
That is a first for us. Did you also try to completely remove the CLI and `~/.now` and reinstall?

**Comment by tracy-codes** [comment]
@paulogdm Just removed ~/.now, completely removed the CLI and reinstalled. Still getting the same error. Super odd, it works 100% on windows but not on WSL.

**Comment by tracy-codes** [comment]
@paulogdm For further insight, I'm using NVM to manage my node/npm versions on WSL. I'm wondering if installing plain ol' Node would solve this? I'll try that out later today after I get through some other work.

**Comment by tracy-codes** [comment]
@paulogdm Just a quick update here: pretty sure this is an error with my specific WSL installation. I encountered a similar error with jest --watch but jest --watchAll functions as expected. I'm going to dig a bit more into this issue over the next few days to see what's causing it. Probably some odd file permissions or something.

**Comment by paulogdm** [comment]
Any tips are appreciated for someone who encounters the same error in the future!

**Comment by tracy-codes** [comment]
@paulogdm Just tried with a clean WSL installation, same error. I'm writing this off as the WSL instance doesn't have access to create child processes on the Windows base system. Not really much can be done here, I'll submit an issue to WSL specifically, as this issue seems to persist with other node modules that require child processes.

**Comment by juliangruber** [comment]
@tracy-codes thank you for investigating this! Looks like it's being taking care of in the WSL repo :)
