### ISSUE TITLE
how to upgrade?

### ISSUE THREAD

**Issue by Maxhodges** [vercel/vercel#1903]
I wrote support 5 days ago and go no reply. My lead dev wrote to you THREE WEEKS ago and you didn't answer him.

We are on the 1.0 premium plan but need to upgrade to Pro. How do we do that? we can't figure out any way to upgrade in your UI.

Or do you recommend Heroku instead?

**Comment by paulogdm** [comment]
Hello!
We are dealing with your inquiry in support@zeit.co
Sorry for the trouble! If we don't answer in a few days, feel free to reach me on my email: paulo@zeit.co or my twitter account: paulogdm
