### ISSUE TITLE
websocket deployments broken?

### ISSUE THREAD

**Issue by lipp** [vercel/vercel#192]
It seems that websocket connections are not working for new and old deployments at the moment.

I am getting an invalid ws frame (opcode -1) with HTTP response code 426 or 200 (!) when connecting from (browser) client. There is also a console log the ws connection failed of course.

![ws-req](https://cloud.githubusercontent.com/assets/445883/21561712/9ac6d34e-ce70-11e6-981b-0633c277e106.png)

![ws-req-2](https://cloud.githubusercontent.com/assets/445883/21561689/4af5e242-ce70-11e6-850b-6da9d35aab18.png)

PS: my app was working before (last deployment 6 days ago)
PSS: old deployments also stoped working

**Comment by mstdokumaci** [comment]
Websockets were working yesterday. I can confirm this problem started today.

**Comment by lipp** [comment]
@mstdokumaci thanks for investigating / confirming 👍

**Comment by jamo** [comment]
Apologies for the inconvenience; we've identified and fixed the regression in our services

**Comment by lipp** [comment]
THX 👍
