### ISSUE TITLE
ports other than 3000 are failing

### ISSUE THREAD

**Issue by markozxuu** [vercel/vercel#1927]
## Main problem 🙍 

I'm using `port 8080` everything works fine, the problem occurs when you access another route apparently an error occurs in the main port. This error is only presented using the constructor `@now/node@canary`.

**NOTE:** this problem does not occur if `@tootallnate/node` is used

<img width="628" alt="screen shot 2019-03-04 at 11 59 40" src="https://user-images.githubusercontent.com/16585386/53753604-47e91a00-3e77-11e9-9017-c32494b7d8e1.png">

<img width="1280" alt="screen shot 2019-03-04 at 12 01 04" src="https://user-images.githubusercontent.com/16585386/53753616-4ddefb00-3e77-11e9-9df3-9c5d0f43ba9f.png">

### How to reproduce it ? 🐛 

1. clone the following [repository
](https://github.com/MAPESO/error-port)

2. delete the folder **.git** to avoid compilation failures

3. run the command `DEBUG=*fun* node /Users/path/now-cli/dist/index.js dev --debug --port 8080`

**Comment by TooTallNate** [comment]
This turned out to be a local npm caching issue. `npm cache clean --force` fixed the issue.

In reality, `@tootallnate/node` and `@now/node@canary` are the exact same code so this shouldn't have been happening, but the local npm cache got in the way.

**Comment by markozxuu** [comment]
@TooTallNate Thanks for help ! :)
