### ISSUE TITLE
Looking for guidance

### ISSUE THREAD

**Issue by codigoconjuan** [vercel/vercel#1930]
well to be honest i'm having a really hard time with the docs

working with an express app and trying to test Now CLI

my now.json file

```
{
    "version": 2,
    "name": "nodejs-express",
    "alias": [
        "nodejs-express"
    ],
    "builds": [{ "src": "*/index.js", "use": "@now/node-server" }],
    "routes": [
        { "src": "/(.*)", "dest": "index.js" }
    ]
}
```

already tried a lot of configurations from others people question but haven't found any that works:

i changed from @now/node-server to @now/node too

the deployment says that everything is ready of course it isn't ( The logs doesn't output anything that is helpful or important )

the only time that i saw something on screen was when i added:

 "builds": [{ "src": "*package.json", "use": "@now/node-server" }],

JSON file was uploaded but to be honest i don't understand the really short examples

The structure for my project is like this:

controllers/
models/
routes/index.js
views/
index.js
package.json

and of course the now.json file and others 

not sure if i need to register the routes separated (there're like 20) or what, don't understand the workflow really well, and almost all the examples are from non-real world projects with 1 file

**Comment by paulogdm** [comment]
One thing concerns me:
```
   "builds": [{ "src": "*/index.js", "use": "@now/node-server" }],
```
it should be
```
   "builds": [{ "src": "index.js", "use": "@now/node-server" }],
```
Please, try to copy our examples [here](https://github.com/zeit/now-examples) and try to understand how builds and routes works with basic stuff first.

Also, lambdas are about being small. If you have a single `index.js` dealing with everything it kinda defeats the purpose. We have more "real world examples" with Express:
- [Express](https://github.com/zeit/now-examples/tree/master/express)
- [Canvas PartyParrot](https://github.com/zeit/now-examples/tree/master/nodejs-canvas-partyparrot)

I also need to say `now-cli` is not the place for questions like this. Please, use [our chat](zeit.co/chat).
