### ISSUE TITLE
Inconsistent message on reporting "invalid number of arguments"

### ISSUE THREAD

**Issue by amio** [vercel/vercel#1931]
Currently we output different messages for "invalid number of arguments". We better have a consistent format for same type of message. Then which format should we use for all those cases?

### `now deploy a b c d`

```
> Error! The specified file or directory "a" does not exist.
```

### `now ls a b c d`

```
> Error! `now ls [app]` accepts at most one argument
```

### `now inspect a b c d`

```
> Error! `now inspect <url>` expects exactly one argument

  𝚫 now inspect <url>

  ... (full help message)
```

### `now domains a b c d`

```
> Error! Invalid number of arguments. Usage: `now domains ls`
```

### `now certs a b c d`

```
> Error! Please specify a valid subcommand: ls | issue | rm

  𝚫 now certs [options] <command>

  ... (full help mesage)
```

### `now secrets ls a b c d`

```
> Error! Invalid number of arguments. Usage: `now secret ls`
```

### `now logs a b c d`

```
> Error! Failed to find deployment "a" in amio
```

### `now scale a b c d`

```
> Error! The value "b" is not a valid region or DC identifier
```

### `now init a b c d`

```
> Error! Too much arguments.
```

**Comment by trek** [comment]
Hi @amio,

Thank you for the bug report. We're closing out older issues that have probably been addressed by now.
