### ISSUE TITLE
Show the deployed url at the end of the deploy command

### ISSUE THREAD

**Issue by finnp** [vercel/vercel#1938]
Currently the `now deploy` command ends with `Success! Deployment ready`. Depending on how much output the deploy was producing the url of the deployment is hidden in the logs. It would be nice if it would just print the deployed url again like `Success! Deployment ready at https://xyz-xyz.now.sh`

**Comment by TooTallNate** [comment]
Closing because this has been fixed as of latest Now CLI. The last line of the `now deploy` command looks like:

```
> Ready! Deployed to https://my-project.now.sh [in clipboard] [3s]
```
