### ISSUE TITLE
Weird regenerator error not letting alias work properly

### ISSUE THREAD

**Issue by SpencerCDixon** [vercel/vercel#194]
<img width="1279" alt="screen shot 2017-01-01 at 4 46 30 pm" src="https://cloud.githubusercontent.com/assets/7471018/21583163/fed69f22-d041-11e6-9652-3218602c9a67.png">

**Comment by SpencerCDixon** [comment]
upgrading my node version fixed the issue. closing..

**Comment by OlliV** [comment]
May I ask what version were you using?

**Comment by SpencerCDixon** [comment]
Was using 6.2.2 when the error was occuring
