### ISSUE TITLE
Module not found: Can't resolve './build/Release/scrypt'

### ISSUE THREAD

**Issue by Ugarz** [vercel/vercel#1940]
Hi there,

I am currently following [this Now guide](https://zeit.co/guides/deploying-nextjs-with-now/) to deploy my Nextjs app. I made some changes on my github repository to link Now to Github. Then I created my `next.config.js` and `now.json`.

My `next.config.js`
```js
module.exports = {
  target: "serverless"
}
```
My `now.json`
```json
{
    "name": "eth-todo-list-react",
    "alias": ["eth-todo-list-react.now.sh"],
    "version": 2,
    "builds": [{ "src": "next.config.js", "use": "@now/next" }],
    "routes": [{
        "src": "/_next/static/(?:[^/]+/pages|chunks|runtime)/.+",
        "headers": {
            "cache-control": "immutable"
        }
    }]
}
```

When I deploy it with `now`, I get some errors in logs
```
Module not found: Can't resolve './build/Release/scrypt' in '/tmp/13f82355/node_modules/scrypt'
```
Here is a screenshot of what I get
<img width="1079" alt="Capture d’écran 2019-03-09 à 23 40 58" src="https://user-images.githubusercontent.com/6050079/54078223-e1c02500-42c4-11e9-8c59-127d0d8184bb.png">

Any idea to help me ?

**Comment by Ugarz** [comment]
Hello again 👋 
I cannot find if I'm doing something wrong in configuration, if the `now-cli` coupled by the ci has something broken or if it's a `nextjs` issue. Running the commande `npm run now-build` locally throw the same error, so think it is more a nextjs / webpack configuration 🤔 .

**Comment by juliangruber** [comment]
Hey @Ugarz, can you please post this issue either in [zeit/next.js](https://github.com/zeit/next.js) or our [community chat](https://zeit.co/chat)? 🙏
