### ISSUE TITLE
Error message on timeout

### ISSUE THREAD

**Issue by sarupbanskota** [vercel/vercel#1942]
Whadduppp folks!

It looks we currently don't throw an error message when a deployment times out. This can be confusing if there isn't an error message explaining why: one could wonder if it's something with their internet connection, for example.

Unless we have a technical limitation to not do this, I would suggest we create and throw errors in the event of timeout in a way that is builder specific. e.g for Rust projects, we expect build times to be slow and therefore timeouts can be frequent.

So an error along the lines:

> This build timed out cuz it look longer than 15m. Currently Rust projects take a while to ship because there’s ongoing work on the compiler. Please read [link] for more info.

would be useful!

**Comment by TooTallNate** [comment]
Closing because Now CLI shows a message saying "Check the logs" at this point, which would lead to the 15 minute timeout in the logs.
