### ISSUE TITLE
now.cmd broken on windows?

### ISSUE THREAD

**Issue by brownbl1** [vercel/vercel#1943]
Using `nvm` on windows to install the latest version of node/npm, I then install now using `npm i -g now`. Running it as I usually do results in:
![image](https://user-images.githubusercontent.com/2136925/54155783-455c6680-441b-11e9-9be3-4e9502fb53c4.png)

Running `now -h` or similar results in the same output. I have restarted my machine and tried other global node modules like yarn to try to pinpoint the issue, but it seems to be `now` specific. 

Is this a known issue? If not, are there any other things I could try to understand the root of the problem?

**Comment by mrliptontea** [comment]
Can confirm, I see two issues here:

1. `npm\now.cmd` is missing quotes.
    Its content should be `"%~dp0\node_modules\now\download\dist\now.exe" %*`
2. `npm\node_modules\now\download\dist\now` is plain empty, therefore `now` won't do anything in environments such as git bash, cygwin, etc.

**Comment by albertosantini** [comment]
About #2 there are three issues.

And I see the same issue with `14.1.0` under git bash.

- https://github.com/zeit/now-cli/issues/1943 (this one)
- https://github.com/zeit/now-cli/issues/1926
- https://github.com/zeit/now-cli/issues/1923

**Comment by fu-sen** [comment]
This problem seems to be continuing. Spectrum:
https://spectrum.chat/zeit/now/problem-with-my-now-client~6253c29e-01a4-4f43-a154-c472282b93b0

**Comment by entrptaher** [comment]
I did not even bother to check for issues and went on completely installing `wsl` and configuring it for 2 days, on one machine just for sake of using `now` :D ... 

Then came back to windows, realized `now.cmd` was broken on cmd, worked only when I reinstalled nodejs outside `Program Files`.

**Comment by benbagley** [comment]
Adding quotes worked for me @mrliptontea

**Comment by albertosantini** [comment]
Here it works with now 15.2.0 via #2322.
