### ISSUE TITLE
HTTP 500 on a deployment - no logs

### ISSUE THREAD

**Issue by hormesiel** [vercel/vercel#1954]
I'm getting an HTTP 500 error when navigating to a deployment for a new project that uses the `@now/node` builder, and I don't know why because the logs contain absolutely nothing about this error (`output/index.js` logs are empty).

- Deployment URL : https://now-basic-auth-node-module-7zx6dosc7.now.sh/
- Full source code : https://github.com/flawyte/now-basic-auth/tree/module/node-module

**Comment by paulogdm** [comment]
Please, create a public deployment with `"public":  true`.
Also, this is not a CLI issue, you can use our community chat to post about problems, questions and now related stuff: [zeit.co/chat](zeit.co/chat)
