### ISSUE TITLE
Error! Unknown or unexpected option: -S

### ISSUE THREAD

**Issue by Igloczek** [vercel/vercel#1963]
After upgrade to 14.1.0 and changing all `-T` to `-S` I'm getting this error `Error! Unknown or unexpected option: -S`

Replacing `-S` with `--scope` solving the problem.

This is how the part of broken deployment recipe looks like:
```shell
DEPLOYMENT_URL=$(now -t ${NOW_TOKEN} -S ${NOW_SCOPE} -n ${NOW_PROJECT})
now -t ${NOW_TOKEN} -S ${NOW_SCOPE} alias set ${DEPLOYMENT_URL} ${NOW_URL}
now rm -t ${NOW_TOKEN} -S ${NOW_SCOPE} -s -y ${NOW_PROJECT}
```

This one works perfectly fine:
```shell
DEPLOYMENT_URL=$(now --token ${NOW_TOKEN} --scope ${NOW_SCOPE} --name ${NOW_PROJECT})
now --token ${NOW_TOKEN} --scope ${NOW_SCOPE} alias set ${DEPLOYMENT_URL} ${NOW_URL}
now rm --token ${NOW_TOKEN} --scope ${NOW_SCOPE} --safe --yes ${NOW_PROJECT}
```

**Comment by vladshcherbin** [comment]
`now rm -s` option is broken too:

```
> Error! Option requires argument: -s (alias for --scope)
```

However, in docs (`-h`):

```
-s, --safe                     Skip deployments with an active alias
-S, --scope                    Set a custom scope
```

`--safe` option works, which is a current solution.

14.1.0

**Comment by juliangruber** [comment]
Fixed in the latest canary: https://github.com/zeit/now-cli/releases/tag/14.3.0-canary.13

**Comment by vladshcherbin** [comment]
@juliangruber why wasn't it released as 14.1.2, as a fix for current stable version users?

**Comment by juliangruber** [comment]
It was also released as that, shortly after: https://github.com/zeit/now-cli/releases/tag/14.2.0.

**Comment by vladshcherbin** [comment]
@juliangruber that's awesome, thank you 😉
