### ISSUE TITLE
problems with "hard refresh"

### ISSUE THREAD

**Issue by markozxuu** [vercel/vercel#1970]
**hard refresh** triggers a reconstruction

this is the expected behavior
![2019-03-15 22 23 09](https://user-images.githubusercontent.com/16585386/54470663-6998aa00-4771-11e9-9945-957647265e52.gif)

but for some strange reason when it is used more than 2 times **hard refresh** does not perform the reconstruction process 🙍 

![2019-03-15 22 38 37](https://user-images.githubusercontent.com/16585386/54470760-22abb400-4773-11e9-9228-eb3586f9c77a.gif)

**Comment by TooTallNate** [comment]
This has been fixed.
