### ISSUE TITLE
Unable to issue a certificate

### ISSUE THREAD

**Issue by lovincyrus** [vercel/vercel#1978]
Reference to: #1347 

Unable to issue a cert: https://www.useloom.com/share/34ae34f613184e748019e772612752bc

URL: https://blog.lovincyrus.com

Cloudflare:
CNAME      blog      alias.zeit.co
TXT		_now	QmckKAT2dxUWLcewv8jYhvxAhLDsTmwnpGJARX7wKwQ4to

Crypto
-> SSL: Full (strict)

Page rules
-> blog.lovincyrus.com/.well-known/acme-challenge/*
-> SSL: Off https://github.com/zeit/now-cli/issues/1569#issuecomment-473443677

Any help would be appreciated 🍻

**Comment by paulogdm** [comment]
I can't see the CNAME in place: https://www.whatsmydns.net/#CNAME/blog.lovincyrus.com

**Comment by lovincyrus** [comment]
Interesting, I'll remove the CNAME record and insert it again. I've also purged the cache of CNAME blog.lovincyrus.com using https://1.1.1.1/purge-cache/

**Comment by lovincyrus** [comment]
Fixed!

Changes:
1. Change CNAME blog alias.zeit.co (DNS only)
2. Update page rule to dynamic pattern **.lovincyrus.com/.well-known/acme-challenge/*
3. Add TXT _acme-challenge.blog [value]

Notes:
- https://zeit.co/blog/domain-verification

**Comment by morgs32** [comment]
I'm stuck here too. Got the email that said my certificate expired. Nothing has changed with my Cloudflare configuration. Still I cannot verify and after running `now verify`, `now inspect`, and then `now domains rm` and `now domains add` it seems I've hit a rate-limit on issuing certs?

```
> Error! Too many certificates already issued for exact set of domains: www.morganatwork.com
```

In the blog post mentioned above ^^, there is a screenshot of cloudflare in which DNS and HTTP proxy is turned off:
![image](https://user-images.githubusercontent.com/1364795/56501761-ed1a8900-64dd-11e9-90e0-95c3202037cb.png)

Is that necessary?

**Comment by lovincyrus** [comment]
@morgs32 

> Your CNAME for your domain (www.morganatwork.com) seems to be working fine.

1. Yep, that is necessary. I'd make sure that it's only DNS only like how it's being described on the blog post.
2. Then, I'd https://1.1.1.1/purge-cache/ your CNAME domain
3. It takes some time for DNS propagation. After that, you could try to repeat the same steps: 
`now domains rm, now domains add <domain>, now verify, now inspect, now certs create <domain>, take care of your aliases after that`

Reference:
https://zeit.co/blog/now-certs
