### ISSUE TITLE
Clipboard broken in v14.3.0-canary.9

### ISSUE THREAD

**Issue by ekkis** [vercel/vercel#1979]
I recently upgraded from v14.0.0 and have discovered that the clipboard paste is now broken

I have scripts that do something like `now; url=$(pbpaste)` and I now get nothing in `$url`, which makes stuff break

the fault is experienced on OSX 10.14.3

**Comment by juliangruber** [comment]
@ekkis in case clipboard support doesn't work, the recommended way for scripting is to use Now CLI's stdout. If it detects it's not being executed with a terminal context attached, the output will _only_ be the deployment url.

You could verify this with

```bash
$ now > url.txt
```
