### ISSUE TITLE
now -a fails if alias-id is given without tld

### ISSUE THREAD

**Issue by ntwcklng** [vercel/vercel#198]
Lets assume i have an app called `app-name` with the alias `app-name.now.sh`

If i run `now -a app-name` it fails:
`> Error! Alias with ID "app-name" doesn't exist`

Running `now -a app-name.now.sh` or `now alias app-name-id app-name` works fine.

After debugging a bit i noticed that the promise https://github.com/zeit/now-cli/blob/master/lib/alias.js#L29 is always pending if i run `now -a app-name`. Unfortunately i can't test it any further because i run out of free deploys

**Comment by lukechilds** [comment]
I have the same problem.

**Comment by lukechilds** [comment]
It appears to be because if there's no suffix it assumes you're using the `uid` https://github.com/zeit/now-cli/blob/afc329a61c0bade5e3b98b4f51b4de67bc5e6a22/bin/now-deploy.js#L557
