### ISSUE TITLE
WARN! Your project is missing a now.json file with a `version` property.

### ISSUE THREAD

**Issue by MattGould1** [vercel/vercel#1987]
After upgrading to 14.1.1 we've encountered a couple of issues.

```
WARN! Your project is missing a now.json file with a `version` property. More: https://zeit.co/docs/version-config
Error! Unknown or unexpected option: -S
```

Our `now.json` is named `now.staging.json` and looks like

```
{
  "name": "service-name",
  "alias": ["staging.domain.com"],
  "version": 2,
  "builds": [
    { "src": "index.js", "use": "@now/node-server" }
  ],
  "routes": [{ "src": "/(.*)", "dest": "index.js" }]
}
```

Our now-cli command is

`now -t ${token} -S ${team} -e ${env} -A ${path} deploy dist`

The issue seems to be with `deploy` and `-S`, if we remove `deploy dist` and make changes to our `now.json` file, the build works correctly.

 e.g. `now -t ${token} --scope ${team} -e ${env} -A ${path}`

With `alias` `-S` works fine.

**Comment by juliangruber** [comment]
Fixed in the latest canary: https://github.com/zeit/now-cli/releases/tag/14.3.0-canary.13
