### ISSUE TITLE
Weired status code 200 -> 404 transform

### ISSUE THREAD

**Issue by lipp** [vercel/vercel#199]
i'm trying do so some 0auth authentication including the usual "callback" url. running stuff locally with temporarily adapted callback url works ok. however, when deployed with now, the callback's returned status code (200, seriously tripple checked) *SOMEHOW* gets transformed to 404 followed by a subsequent `/_next/next.bundle.js` get request (this is no next.js app).

![404](https://cloud.githubusercontent.com/assets/445883/21659171/db700e94-d2c9-11e6-8d7f-2469d55587c0.png)

this is my express morgan server log, which shows the two requests and the status codes
- GET /reddit/callback 200
- GET /_next/next.bundle.js 404

```
GET /reddit/callback?state=ef23e9d7532616404620ac8239fa856ad2b8c06db67f888776630182927a0519&code=U-x-7Mpd8mW6B8NtDEzN3mVsMrE 200 316.869 ms - 4062
::ffff:10.100.3.2 - - [04/Jan/2017:20:55:07 +0000] "GET /reddit/callback?state=ef23e9d7532616404620ac8239fa856ad2b8c06db67f888776630182927a0519&code=U-x-7Mpd8mW6B8NtDEzN3mVsMrE HTTP/1.1" 200 4062 "https://ssl.reddit.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"
GET /_next/next.bundle.js 404 2.018 ms - 33
::ffff:10.100.3.2 - - [04/Jan/2017:20:55:07 +0000] "GET /_next/next.bundle.js HTTP/1.1" 404 33 "https://passport.now.sh/reddit/callback?state=ef23e9d7532616404620ac8239fa856ad2b8c06db67f888776630182927a0519&code=U-x-7Mpd8mW6B8NtDEzN3mVsMrE" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36"

```

The `/reddit/callback` response's body also gets *SOMEHOW* populated by this content:
```html
<!DOCTYPE html><html><head></head><body><div><div id="__next"><div class="error error_404 " data-reactroot="" data-reactid="1" data-react-checksum="619030190"><div class="text" data-reactid="2"><h1 data-reactid="3">404</h1><div class="desc" data-reactid="4"><h2 data-reactid="5"><!-- react-text: 6 -->This page could not be found<!-- /react-text --><!-- react-text: 7 -->.<!-- /react-text --></h2></div></div><style data-reactid="8">    .error {      color: #000;      background: #fff;      top: 0;      bottom: 0;      left: 0;      right: 0;      position: absolute;      font-family: "SF UI Text", "Helvetica Neue", "Lucida Grande";      text-align: center;      padding-top: 20%;    }    .error.error_500 {      background: #000;      background: #fff;    }    h1, .desc {      display: inline-block;      vertical-align: top;    }    .desc {      text-align: left;      line-height: 49px;      height: 49px;      vertical-align: middle;    }    .shouldRetry .desc {      height: 29px;      margin-top: -18px;    }    h1, h2, h3 {      margin: 0;      padding: 0;      font-weight: normal;    }    h1 {      border-right: 1px solid rgba(0, 0, 0,.3);      margin-right: 20px;      padding: 10px 23px;      font-size: 24px;      font-weight: 500;    }    .shouldRetry h1 {      padding: 16px 23px;    }    .dark h1 {      border-right: 1px solid rgba(255, 255, 255, .3);    }    .shouldRetry h2, .shouldRetry h3 {      margin: 3px 0;    }    h2 {      font-size: 14px;    }    h3 {      font-size: 11px;      color: rgba(255, 255, 255, .68);    }  </style></div></div><script>__NEXT_DATA__ = {"props":{"code":404,"title":"This page could not be found","shouldRetry":false},"hash":null,"base":"","serviceWorker":false,"component":null}</script></div><script type="text/javascript" src="/_next/next.bundle.js"></script></body></html>
```

???!!?!?

**Comment by lipp** [comment]
This behaviour is can be seen here: https://passport.now.sh (loggin in with reddit obviously :))

**Comment by lipp** [comment]
Same problem with github OAuth: https://login.now.sh/github

**Comment by lipp** [comment]
@jamo thanks for trying! is this something about my "local setup?". already tried different browsers...and machines...(including mobile)...

**Comment by lipp** [comment]
@jamo which browser are you using? (vivaldi?)

**Comment by lipp** [comment]
![github-login](https://cloud.githubusercontent.com/assets/445883/21680265/febc1b84-d348-11e6-920c-6e817c90465b.gif)

**Comment by jamo** [comment]
It was actually chrome in incognito mode.

Thanks for the report, I've identified the issue finally, and it's indeed related to our environment.
I'll let you know once we have the fix deployed so that you can verify it 😊

**Comment by lipp** [comment]
🤗  awesome! thank you very much!!! looking forward to proceed with this.
(the project will provide easy client side login with reddit/github/twitter for all *.now.sh hosted apps https://github.com/lipp/login-with)

**Comment by lipp** [comment]
@jamo any updates on this? looking forward to VERIFY 🤓

**Comment by lipp** [comment]
@jamo any news on this? 😚

**Comment by jamo** [comment]
Apologies for the radio silence on this and the super long time that it took to fix this...

I've just deployed finally a fix to our systems, that should have fixed the issue your deployments were suffering. 
I've tested it with this:  https://login.now.sh/github and it seemed to be working wonderfully.

Could you please verify the possible fix :)

**Comment by lipp** [comment]
@jamo I already played with it some days ago... seems to work just fine! Thanks a lot.

**Comment by jamo** [comment]
Wonderful!

**Comment by djalmaaraujo** [comment]
Sorry, but I am getting the same error with safari now. All browsers seems to work fine, but when I get a redirect from Spotify OAUTH, the server returns a:

Failed to load resource: the server responded with a status of 404 (HTTP/2.0 404)

You can test here: http://pasteandplaylist.now.sh/

**Comment by danielwyb** [comment]
@jamo i'm running into a similar issue. A PUT request returns 404, whereas the same request, sent as a POST request works. Any ideas?
Thanks!

  
![image](https://user-images.githubusercontent.com/13015487/32977979-70ae0976-cc06-11e7-954b-9f1ea67ee138.png)
![image](https://user-images.githubusercontent.com/13015487/32977967-4e59d986-cc06-11e7-9bc8-7416cf2d5c71.png)
