### ISSUE TITLE
Improve the `now init` flow 

### ISSUE THREAD

**Issue by shuding** [vercel/vercel#1991]
To show the full workflow smoothly to a new user, we could ask if the user wants to deploy the project after running `now init`:
> now init (or now init nextjs)
> ... project created ...
>
> Do you want to deploy your project now? [Y/n]

If yes, run `cd` and `now` for them automatically. Otherwise say:
> Your project is created. You can `cd nextjs` and then run `now` to deploy.

furthermore, if the deployment has created we can show:
> Good job. You can make a change and run `now` to deploy again.

**Comment by amio** [comment]
Great! Just a few thoughts:

- We better not to change working directory automatically, this behavior is unusual.
- Two ways to deploy:
  - You can `cd nextjs` and then run `now` to deploy
  - You can run `now deploy nextjs` to deploy
  The latter is more explicit (using `now deploy`), would be better for a new user IMO.

**Comment by shuding** [comment]
> We better not to change working directory automatically, this behavior is unusual.
Yup, good point here.

I’m wondering if we could just `now nextjs` (deploy a folder) as well, IIRC?

**Comment by amio** [comment]
Yep, `now nextjs` is 👌

**Comment by amio** [comment]
After some experience with this flow, I feel it's a bit annoying to bypass the deployment prompt every time.

I guess the majority use cases of `now init` don't need it, it's mainly for first-time user. Is it worth to add this prompt? **better first time** vs **faster every time**.

cc @quietshu @rauchg @timothyis

**Comment by amio** [comment]
After some discussion,

> @quietshu: we can keep this enhancement on hold, maybe in the future we'll have a `isNewUser` (or `lastDeploymentDate`) flag to `user` and can show the prompt / tutorial base on it.

**Comment by TooTallNate** [comment]
Closing based on staleness and the previous comment.
