### ISSUE TITLE
bug in alias logic (affect both now alias and now --target ...)

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#1992]
## Describe the bug

Current aliasing logic when `now alias` or `now --target ...` is called is

1. Fetch the latest deployment
2. link it to an alias

This logic works fine in general unless code changes in the project somehow reverted the project back into a previous deployed state. When this happens, nothing will deployed to now and a previous deployment is returned quickly instead. However, the alias part of the flow still fetches the older "latest" deployment and the deployment with the reverted changes is not aliased.

## To Reproduce

1. deploying version A of site
2. use `now --target production` to deploy and create alias
3. deployment at: URL-A.domain, alias of somedomain.com is created, pointing to URL-A.domain
5. deploying version B of site `now --target production`
6. deployment at: URL-B.domain, alias somedomain.com is now pointing to URL-B.domain
7. for some reason, changes in code is reverted back to version A
8. redeploy with `now --target production`
9. the old server side deployment is reused, without uploading code again, URL-A.domain is reused
10. in the CLI, it is reported that “Ready! Aliases assigned”, it is *reported that somedomain.com os pointing to URL-A.domain* but it is *not the case*. If you visit the dashboard website, somedomain.com is still pointing to URL-B.domain, and if you visit somedomain.com, you will still see URL-B.domain.

Note: can reproduce this bug with the new `now --target` flow as well as the old `now && now alias` flow.

**Comment by trek** [comment]
Hi @williamli,

Thank you for the bug report. We're closing out older issues that have probably been addressed by now.
