### ISSUE TITLE
changes in .nowignore is not enough to trigger a new redeployment

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#1994]
## Describe the bug

A project is not redeployed if its content has previously been deployed.
The URL / ID of the older deployment will be returned.

Changes in just the `.nowignore` file is not enough to trigger a new deployment. The system will think it has previously been deployed and returned an old URL.

## To Reproduce

1. Setup a project, add a html file and a js file and maybe a bunch of img files.
2. Add a .nowignore file, ignore some files
3. deploy, noticed the ignore files are skipped
4. remove everything inside the .nowignore file so no files are ignored
5. deploy, the server will return the same URL, nothing new has been deployed.
6. adding a space in the html file 
7. deploy again, the new .nowignore will be used, eveything is deployed.

## Expected behavior\*\*

Upon every deployment request, the content of `.nowignore` should be considered before the file diff / hash is calculated?

**Comment by styfle** [comment]
We no longer perform deployment deduplication so I'm closing this issue
