### ISSUE TITLE
Error! Could not find deployment

### ISSUE THREAD

**Issue by bdougherty** [vercel/vercel#1995]
When I try to deploy a project under a team, I always get the following error:

```
> Deploying ~/Code/projectName under teamName
> Using project projectName
> Synced 56 files (1.48MB) [5s]
> https://projectName-cbj7bc3yf.now.sh [v2] [3s]
> Error! Could not find deployment (404)
```

When I go to the dashboard, that deployment does actually exist and builds properly. I'm using the latest version of the cli: 14.2.0.

config:

```json
{
  "version": 2,
  "name": "projectName",
  "alias": "projectAlias",
  "scope": "teamName",
  "builds": [
    {
      "src": "package.json",
      "use": "@now/next"
    }
  ],
  "routes": [
    {
      "src": "^/.well-known/(.*)",
      "dest": "/static/.well-known/$1"
    },
    {
      "src": "^/service-worker.js$",
      "dest": "/_next/static/service-worker.js",
      "headers": {
        "cache-control": "public, max-age=43200, immutable",
        "Service-Worker-Allowed": "/"
      }
    }
  ]
}
```

**Comment by ninesalt** [comment]
I also have this error. Something is messed up with deployments right now. My CI pipeline is going crazy all of a sudden.

**Comment by bdougherty** [comment]
I think it may be related to the number of existing deployments. I deleted a bunch of old ones and it's working correctly for me now.

**Comment by ninesalt** [comment]
Just tried that and it didnt work. As far as I can tell what is happening is that it creates a deployment and then tries to reference it because it's done building.

**Comment by juliangruber** [comment]
We just fixed a platform issue. Sorry about that! Could you please try again, and see if it works now?

**Comment by ninesalt** [comment]
Looks like it's fixed now. Thanks. 

PS: It would be nice if you guys would update your [status page](https://zeit-status.co/) when issues like that happen.

**Comment by juliangruber** [comment]
Thank you @ninesalt! I'll forward this to the team 🙏
