### ISSUE TITLE
Event stream response appears not to work

### ISSUE THREAD

**Issue by leo** [vercel/vercel#20]
https://github.com/zeit/now-issues/issues/15

**Comment by Flet** [comment]
Hi @leo! Was this fixed?

Unfortunately the `now-issues` repo is 404 for me, so I can't follow that link.

I do see a little snippet on google from the original ticket:
<img width="592" alt="screen shot 2016-11-03 at 12 28 07 am" src="https://cloud.githubusercontent.com/assets/360233/19956604/79a90204-a15c-11e6-8d55-5ff6045bf592.png">

It looks like @mikael opened it originally when trying to run a signalhub via `now` (which is exactly what I'm trying to do! 😁 ). Mikael, did you ever get it working?
