### ISSUE TITLE
Now deployment hangs in CI

### ISSUE THREAD

**Issue by developius** [vercel/vercel#2002]
Hey team, thanks for building an *exceptional* deployment experience, I am loving every second I'm using Now!

I'm running this command via a GitLab's CI runner to get my app deployed to staging. The deployment completes successfully within a couple of minutes, but the CI job keeps running because the command never completes (or takes a long time - often at least 15 minutes). This issue doesn't occur if the deployment already "exists", where the same code is already uploaded for a different deployment.

Now CLI version: `14.2.2`

```
$ ./node_modules/.bin/now --target staging -e NODE_ENV=staging --token=$ZEIT_TOKEN
> Deploying /builds/<my project> under finniananderson
> Using project <my project>
###### truncated ######
┌ index.js            Ready               [1m]
└── λ index.js (1.51MB) [iad1]
┌ package.json        Ready               [2m]
├── android-chrome-192x192.png (10.91KB)
├── android-chrome-512x512.png (30.72KB)
├── apple-touch-icon.png (10.18KB)
├── browserconfig.xml (246B)
├── favicon-16x16.png (722B)
├── favicon-32x32.png (1.29KB)
├── favicon.ico (10.73KB)
├── img/logo.png (38.12KB)
├── index.html (1.18KB)
├── js/app.js (15.48KB)
├── js/app.js.map (52.5KB)
├── mstile-150x150.png (8.48KB)
├── safari-pinned-tab.svg (4KB)
├── site.webmanifest (452B)
├── css/chunk-vendors.css (173.42KB)
├── js/chunk-vendors.js (1.65MB)
└── js/chunk-vendors.js.map (5.87MB)
###### the command just hangs here
```

I'm not sure if this is an issue with the new version of Now, but this *wasn't* occuring when using an older version (`14.1.1` was fine).

Thanks!

**Comment by juliangruber** [comment]
Can you please confirm that downgrading Now CLI again fixes the problem?

**Comment by bdougherty** [comment]
This was also happening to me on Bitbucket Pipelines. Did not fix it when I went back to 14.2.1, but 14.2.0 works.

**Comment by bhaskarmurthy** [comment]
Same here - had to downgrade to `14.2.0` for it to work again

**Comment by developius** [comment]
Can confirm the same thing with GitLab - `14.2.0` works fine. Great to hear it's not just me 😄

**Comment by homerjam** [comment]
I seem to have this issue locally today. I've tried downgrading (and upgrading) to no avail 😞

**Comment by homerjam** [comment]
The builder seems to hang [here](https://github.com/nuxt/now-builder/blob/master/lib/build.js#L31) in my case which might suggest a problem with `@now/build-utils/fs/download`.

**Comment by homerjam** [comment]
Turns out my bundle was too big. Fixed by adding a few more unnecessary files to `.nowignore`.

**Comment by homerjam** [comment]
This is happening again now 🤦‍♂️

**Comment by juliangruber** [comment]
@homerjam are you using Now 2.0 or 1.0?

**Comment by homerjam** [comment]
2.0

This has been resolved for me by now/now-builders#353

**Comment by TooTallNate** [comment]
Closing due to age, and because it appears to have been fixed based on the comments.

Also, I suggest you take a look at our [Now for GitLab](https://zeit.co/blog/now-for-gitlab) integration which may make your workflow more streamlined.

Please open a new issue if you are still experiencing any troubles!

**Comment by developius** [comment]
@TooTallNate cool - I've been using the Now for GitLab integration and it works perfectly 🚀
