### ISSUE TITLE
inconsistent `now --target` outputs

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2007]
It seems that your personal alias is assigned to the latest deployment no matter what _(another unrelated issue)_.

When `now --target staging` is used you get an alias summary output in the end
> Ready! Aliases assigned [45s]
> - https://next-http2-tests-williamli.bbi-v21.now.sh
> - https://next-http2-tests.bbi-v21.now.sh

But when `now --target production` is used you get an alias summary output that is missing your personal alias making it seem as though only the production alias has been assigned:
> Ready! Aliases assigned [39s]
- https://http2-test.bbi.space [in clipboard]

In reality, your personal alias has also been assigned to the latest production deployment.
<img width="1069" alt="Screenshot 2019-03-22 at 14 47 25" src="https://user-images.githubusercontent.com/179761/54805283-78bbb280-4cb1-11e9-899c-16c611dd0f27.png">

**Comment by leo** [comment]
This is now fixed:

```
♥ nodejs (master) now --target production
> WARN! You specified "--target production" but didn't configure a value for the `alias` configuration property.
> Deploying ~/projects/now-examples/nodejs under lambdas
> Using project nodejs
> https://nodejs-q4n9m86qf.now.sh [v2] [2s]
┌ index.js        Ready               [11s]
└── λ index.js (33.79KB) [sfo1]
> Ready! Aliases assigned [18s]
- https://nodejs.lambdas.now.sh
- https://nodejs-leo.lambdas.now.sh
```
