### ISSUE TITLE
now --target production not aliasing for me

### ISSUE THREAD

**Issue by codemzy** [vercel/vercel#2012]
Not sure what's happened here... but I followed the blog post [https://zeit.co/blog/automatic-aliasing](https://zeit.co/blog/automatic-aliasing) to do this I 

- updated now CLI `npm install -g now` and got Now CLI 14.2.3
- updated my package.json script from `"deploy-server": "now && now alias"` to `"deploy-server": "now --target production"`

When I ran the script `now --target production` no alias (alias defined in now.json and worked with `now alias` (not a custom domain, just a now.sh alias

```
> Build completed
> Verifying instantiation in bru1
> [0] yarn
> [0] yarn install v1.12.3
> [0] my-site@ start /home/nowuser/src
> ✔ Scaled 1 instance in bru1 [24s]
> Success! Deployment ready
```

Checked and had now aliased.

When I ran `now alias` I got the expected behaviour 

```
> WARN! The `now alias` command (no arguments) was deprecated in favour of `now --target production`.
> Assigning alias myalias to deployment my-site-eoscnwfzhf.now.sh
> Scale rules copied from previous alias my-site-hkfraamnug.now.sh [6s]
> ✔ Scaled 1 instance in bru1 [6s]
> ✔ Scaled 1 instance in sfo1 [23s]
> Previous deployment my-site-hkfraamnug.now.sh downscaled
> Success! myalias.now.sh now points to my-site-eoscnwfzhf.now.sh [35s]
```

Not sure why the alias is not working when running `now --target production`

Extra info:

- version 1
- nodejs deployment
- the urls my-site and myalias are not real I've just removed my actual info other than that it is the actual logs I got

**Comment by codemzy** [comment]
As a work around for the time being I've got my package json script as `"deploy-server": "now --target production && now alias"` (I know that's not how it is supposed to be, but it's the way it works for me at the moment 😬

**Comment by juliangruber** [comment]
The new alias feature is only available in the current platform Now 2.0. I hope soon it will be feature complete for you to upgrade to it!

**Comment by cristoforo** [comment]
I'm with now version 1 too, what's the supposed workflow to deploy & alias with a single command?
(btw, a simple warning on the command line about the `--prod` flag not supported in v1 would be very welcomed... I spent 2h trying that out before realizing it was simply not supported in v1)

In other words, how can I automate the deploy and aliasing like I used to do with `now && now alias`?

**Comment by codemzy** [comment]
@cristoforo I just keep using `now && now alias` for my v1 projects and it still works. I think for v1 we just keep using the old way.

**Comment by cristoforo** [comment]
(sorry I opened a new issue in the meantime, please check there -> https://github.com/zeit/now/issues/3061 )
