### ISSUE TITLE
Unable to issue certificate

### ISSUE THREAD

**Issue by doowb** [vercel/vercel#2013]
I have a `.dev` domain that has been pointing to `zeit-world` name servers for a couple of days and when I try to alias a deployment, I get:

```sh
Error! The certificate provider could not resolve the DNS queries for subdomain.mydomain.dev
```

I tried to manually issue the certificate using the following command:

```sh
now certs issue subdomain.mydomain.dev *.subdomain.mydomain.dev
```

And I  get the following error:

```sh
Error! We could not solve the dns-01 challenge for domain subdomain.mydomain.dev
```

All of the issues and messages on spectrum.chat have lead me to think there was an issue a couple of weeks ago with the `now.sh` dns api but that it was resolved. It doesn't seem to be resolved since this is still happening.

**Comment by paulogdm** [comment]
Can you give me the output of `now domains inspect <domain>`?

**Comment by doowb** [comment]
![image](https://user-images.githubusercontent.com/995160/54838008-0f7e7400-4c9e-11e9-91a3-1b2fbfe62a12.png)

**Comment by paulogdm** [comment]
Ok, hold on while we investigate.
Also, be aware this is not the proper channel for this type of support. Save support@zeit.co for any questions or issue you may  have when using now.sh.

**Comment by paulogdm** [comment]
OK, we have an issue here. Sorry!
To keep track of this, can you email support@zeit.co?

**Comment by fu-sen** [comment]
I was trying to move a Web yesterday to Now, and I was encountering a problem where certificates were not issued for a long time. It happens even if it transfers to other services. I think there is a problem on the Let's Encrypt side.

**Comment by TooTallNate** [comment]
Closing because this was followed up in a support email.

@fu-sen If you are still having any problems, please open a new issue.
