### ISSUE TITLE
NuxtJS 2.4.3 Project Build Error

### ISSUE THREAD

**Issue by fofiu** [vercel/vercel#2014]
I'm getting the following error on pretty much the same code as one of the running instances in now -- this has worked before. And any of the old code that has built in the past is still erroring out.

```
FATAL  Nuxt Build Error                                              02:56:33
  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5263:15)
  at <anonymous>
  at process._tickDomainCallback (internal/process/next_tick.js:228:7)

[...]

Error: Exited with 1
    at ChildProcess.child.on (/tmp/utils/node_modules/@now/build-utils/dist/fs/run-user-scripts.js:15:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

```

**Comment by juliangruber** [comment]
Sorry to hear! Would it be possible for you to share a project so we can reproduce this? You could for example remove codes or modules from your code until it's a minimal breaking build.

**Comment by fofiu** [comment]
@juliangruber I posted this in spectrum.chat also... I bet there is some webpack error, but it seems that the build process is not recording the complete log output.
![screencapture-zeit-co-deployments-essa-7c0780fcb2e2af74c40baac93e4847cfd29849cc-au77mozhn-now-sh-logs-2019-03-23-20_37_03_copy-3](https://user-images.githubusercontent.com/2437645/54891092-8e340680-4e82-11e9-837b-e4051d40f4f3.png)

**Comment by fofiu** [comment]
As expected I did have a stupid error in my code but to find out where the error was I had to remove a good bit of my code so that the webpack error log doesn’t get trimmed before the error shows up (see screenshot below).
<img width="804" alt="images" src="https://user-images.githubusercontent.com/2437645/55487202-a1ba3c80-55fb-11e9-9e33-29fb5c550b8b.png">

**Comment by styfle** [comment]
A lot of changes have been made to logs in the last year.

In particular, if a log output is [over 4KB](https://zeit.co/docs/v2/platform/limits#logs
), you'll see a warning that it was truncated.

Are you still experiencing this problem?
