### ISSUE TITLE
Bug in now --target staging for personal account, null team staging URL returned

### ISSUE THREAD

**Issue by tedmiston** [vercel/vercel#2018]
If I am reading the documentation in the new blog post [Automatic Aliasing on Now](https://zeit.co/blog/automatic-aliasing) correctly, it sounds like running either `$ now --target staging` or `$ now` should be equivalent on a single-user account.

From the post, I believe both commands should have the same effect of deploying the site, then aliasing to the new "staging" default URL of `https://<project name>.<username>.now.sh`, however something weird is happening for the former command.

```
$ now --target staging
> Deploying ~/Documents/qcbrunch under tedmiston
> Using project qcbrunch
> https://qcbrunch-r9g8krpw7.now.sh [v2] [7s]
┌ {*.html,*/*.html,css/*.css,images/*,js/*.js}        Ready               [642ms]
├── js/app.js
├── images/favicon.ico
├── images/manifest.json
├── css/app.css
├── images/favicon-16x16.png
├── css/reset.css
├── images/safari-pinned-tab.svg
├── stats.html
├── index.html
├── images/favicon-32x32.png
├── images/apple-touch-icon.png
├── images/android-chrome-512x512.png
└── images/android-chrome-192x192.png
> Ready! Aliases assigned [11s]
- https://qcbrunch.tedmiston.now.sh
- https://qcbrunch.null.now.sh
```

**^ Note the extra second alias**

```
$ now
> Deploying ~/Documents/qcbrunch under tedmiston
> Using project qcbrunch
> https://qcbrunch-4jlohxtfr.now.sh [v2] [7s]
┌ {*.html,*/*.html,css/*.css,images/*,js/*.js}        Ready               [616ms]
├── index.html
├── images/manifest.json
├── images/apple-touch-icon.png
├── images/android-chrome-512x512.png
├── images/safari-pinned-tab.svg
├── images/android-chrome-192x192.png
├── images/favicon-32x32.png
├── js/app.js
├── stats.html
├── css/app.css
├── css/reset.css
├── images/favicon.ico
└── images/favicon-16x16.png
> Ready! Aliased to https://qcbrunch.tedmiston.now.sh [in clipboard] [12s]
```

**^ No extra second alias**

```
$ now --target staging
> Deploying ~/Documents/qcbrunch under tedmiston
> Using project qcbrunch
> https://qcbrunch-r9g8krpw7.now.sh [v2] [5s]
> Ready! Aliases assigned [5s]
- https://qcbrunch.tedmiston.now.sh
- https://qcbrunch.null.now.sh
```

**^ Extra second alias again**

In both cases the normal staging alias is working.

However, when using the staging target, it insists on also aliasing `https://<project name>.null.now.sh` which is also succeeding but seems like a bug.

Per the blog post, should there be a second URL here at all (like`https://qcbrunch.now.sh`)?

You can find my now.json for this deploy here - https://github.com/tedmiston/qcbrunch/blob/7375c62c3b9632c5ad4a2770d4ef1c84b31fb303/now.json.

I am running the latest version currently available on npm.

```
$ now --version
14.2.3
```

Potentially related (but different) issues:
- [inconsistent `now --target` outputs #2007](https://github.com/zeit/now-cli/issues/1992)
- [bug in alias logic (affect both now alias and now --target ...) #1992](https://github.com/zeit/now-cli/issues/2007)

**Comment by wiiiimm** [comment]
I can reproduce this bug on a single user account. 

It seems the api is trying to return a team staging URL when the user is not in a team, hence returned null.

@tedmiston suggest to rename bug to **"Bug in `now --target staging` for personal account, null team staging URL returned"**

**Comment by tedmiston** [comment]
@williamli Thank you, I've updated the title.

**Comment by wiiiimm** [comment]
@tedmiston this issue has been fixed now
