### ISSUE TITLE
Global commands are broken if local `now.json` is invalid

### ISSUE THREAD

**Issue by rdev** [vercel/vercel#2019]
Invalid `now.json` breaks unrelated CLI commands in the directory.

## Reproduction steps

1. Create a `now.json` file with invalid content:
```
{
  "name": "myapp",
  "version": 2,
  "builds": [
    { "src": "src/*.ts", "use": "@now/node@canary" }
  ],
  "routes":
}
```

2. Run `now secrets ls` in the directory

**Comment by leo** [comment]
This cannot be un-broken, unfortunately. You need to fix the file, as global commands depend on `version` and `scope` in `now.json`.
