### ISSUE TITLE
`now dev` .gitignore bug

### ISSUE THREAD

**Issue by daohoangson** [vercel/vercel#2021]
See this repo https://github.com/daohoangson/now-cli-gitignore-bug for reproducible steps. 

The error is `Cannot read property 'fsPath' of undefined` at https://github.com/zeit/now-builders/blob/145e5a10c2f827c14d680e5b7323d2f3cec3884e/packages/now-node/src/index.ts#L60

```js
const entrypointPath = downloadedFiles[entrypoint].fsPath;
```

`@now/node` was trying to get the path for `entrypoint` but `downloadedFiles` doesn't have that key because `now dev` incorrectly excludes "src/test/index.ts".

I think it's a bug with `createIgnoreList` https://github.com/zeit/now-cli/blob/f693acbaa95fab89c1c9665b9a8f4df82ea78a11/src/commands/dev/lib/dev-builder.ts#L244

**Comment by daohoangson** [comment]
@TooTallNate, can you please add the label `now dev` for this issue. I can't do it myself. Thank you.

**Comment by TooTallNate** [comment]
Thank you for the easy reproduction steps. PR incoming 👍

**Comment by daohoangson** [comment]
Awesome. Thank you for the quick fix 👍
