### ISSUE TITLE
Document all the now package.json config options

### ISSUE THREAD

**Issue by Rowno** [vercel/vercel#204]
Currently I can't find the various now `package.json` config options documented anywhere. The only way I discovered that `now.alias` existed was by accidently seeing it while browsing the source code trying to fix an unrelated bug.

Also the `--config` option isn't documented anywhere, I'm guessing it can contain the same options as the ones in the `package.json`?

**Comment by leo** [comment]
On it! Coming very soon.

**Comment by donmccurdy** [comment]
Was this done, and if so where?

**Comment by leo** [comment]
https://zeit.co/docs/features/configuration#files
