### ISSUE TITLE
Reference assets manifest with @now/node

### ISSUE THREAD

**Issue by revskill10** [vercel/vercel#2045]
In my build, for SSR purpose, each static-build will output a `loadable-manifest.json` .
So, how to reference this file on Now so that the server.js could use it with `@now/node` builder ?
My `now.json` is like this:

```js
{
  "name": "ssr-splitter",
  "version": 2,
  "builds": [
    {
      "src": "package.json", "use": "@now/static-build", "config": { "distDir": "build" }
    }, {
      "src": "src/server.js", "use": "@now/node@canary"
    }
  ],
  "env": {
    "NODE_ENV": "production"
  },
  "routes": [    
    {
      "src": "/static/(.*)", "dest": "public/static/$1"
    },
    {
      "src": "^/(.*)", "dest": "src/server.js"
    }
  ]
}
```

In `src/server.js`, i import the manifest:
```js
import stats from '../build/loadable-manifest.json';
```

**Comment by juliangruber** [comment]
Does it work if you `npx @zeit/ncc build src/server.js && node dist/index.js`? This helps check whether it's a problem with ncc or Now.

**Comment by revskill10** [comment]
@juliangruber Yes, it's the escape hatch for me now, and it works.
But i actually want to use `ncc` on `now.sh` to build my stuff in some cases.

**Comment by juliangruber** [comment]
If it works with `ncc` but not Now that's a bug. Can you share a complete example that I can run to reproduce it?

**Comment by mcsdevv** [comment]
Hello @revskill10, are you still experiencing this issue with the latest Now CLI? If so, please provide a reproducible example and we will investigate.
