### ISSUE TITLE
Documentation request: how does now scale?

### ISSUE THREAD

**Issue by kmalakoff** [vercel/vercel#205]
I see in the FAQ about [Does this scale](https://zeit.co/now#does-this-scale), but cannot find information on "How does now scale" to achieve "Dynamic realtime scaling TM" (eg. We don't under-allocate or over-allocate resources).

Could a description of how scaling works be provided somewhere?

**Comment by rauchg** [comment]
@kmalakoff we're launching our new docs website shortly, and I'll close this issue with a permalink to the document

**Comment by leo** [comment]
On it!

**Comment by appodeepa** [comment]
Um, where's the link?

**Comment by rauchg** [comment]
@weislanes we're documenting this and introducing it under the new docs / tutorials section we're working on

**Comment by balupton** [comment]
Is there an issue for that then? So we can track it

**Comment by balupton** [comment]
there*

**Comment by arcataroger** [comment]
@rauchg Were you ever able to update the documentation? In 2021 it's still not obvious to me **how** Vercel scales.
