### ISSUE TITLE
Ensure `now dev` works correctly on Windows

### ISSUE THREAD

**Issue by TooTallNate** [vercel/vercel#2057]
Current testing has been done on Linux + macOS. The first step is to make sure `@zeit/fun` works on Windows (related to https://github.com/zeit/fun/issues/7).

**Comment by radiumrasheed** [comment]
@TooTallNate is this feature `now dev` still under developement ??

I'm having issues with it

**Comment by TooTallNate** [comment]
[`now@15.0.11-canary.2`](https://github.com/zeit/now-cli/releases/tag/15.0.11-canary.2) has initial Windows support, so closing this one.
