### ISSUE TITLE
`now dev` should build next app in development

### ISSUE THREAD

**Issue by cryptiklemur** [vercel/vercel#2059]
Right now, `now dev` builds next in production. Not conducive to local development.

Specifically problematic when trying to use a CDN for production-only builds

**Comment by danoc** [comment]
On a similar note, it doesn't seem to watch for changes. Although I could be missing something.

Edit: Seems like that will come in the future: https://github.com/zeit/now-cli/pull/1883#issuecomment-465605361

**Comment by boennemann** [comment]
+1 on this. I appreciate that there is a way to replicate the production build locally now. 

However for development I want the shortest possible feedback cycles.
In the cloud builds are massively parallelized and cached, while `now dev` seems to build serially(?).
It takes several minutes to get the server running. 
I'm literally faster doing `now` and trying things in the cloud.

I'd really like to have something (at least for @now/node) that just runs `micro-dev` for me, but with the correct routing.

**Comment by leo** [comment]
This is now happening!
