### ISSUE TITLE
`now logs <id|url>` does not work when a local `logs` directory exists

### ISSUE THREAD

**Issue by Foxhunt** [vercel/vercel#2061]
`now logs` will respond with:

> Error! The supplied argument "logs" is ambiguous. Both a directory and a subcommand are known

same goes for a valid deploymentId or url.

`now log` will print:
```
Δ now logs <url|deploymentId>

  Options:

    -h, --help                     Output usage information
    -a, --all                      Include access logs
    -A FILE, --local-config=FILE   Path to the local `now.json` file
    -Q DIR, --global-config=DIR    Path to the global `.now` directory
    -d, --debug                    Debug mode [off]
    -f, --follow                   Wait for additional data [off]
    -n NUMBER                      Number of logs [100]
    ...
```

or actual build logs with a valid deploymentId or url.

`now -v`: 15.0.1
on Windows 10

**Comment by juliangruber** [comment]
> Error! The supplied argument "logs" is ambiguous. Both a directory and a subcommand are known

It looks like there exists a directory `./logs` so Now CLI can't tell whether you mean to show logs or deploy that directory.

It should however be able to work if you `no logs <url|deploymentId>`, so I'm labeling this as a bug.

**Comment by paulogdm** [comment]
Hello,

We have shipped several improvements to logs:

- https://zeit.co/blog/refined-logging
- https://zeit.co/blog/log-drains

For that reason, the command `now logs` is now being overshadowed and shouldn't be the cause for issues anymore.

If you have any questions, let us know on support@zeit.co
