### ISSUE TITLE
How to setup a primary domain with www

### ISSUE THREAD

**Issue by reginpv** [vercel/vercel#2066]
I have 2 aliases like so:
`
"alias": [
    "domain.com",
    "www.domain.com"
  ]
`
They worked ok, but I wanted to set my primary domain with `www`. I saw the tutorial on redirecting to naked domain, but I wanted the opposite.

Any suggestions on how I can do this?

**Comment by paulogdm** [comment]
Just remove the naked domain alias:
`"alias": [ "www.domain.com" ]`
and then follow the guide https://github.com/zeit/now-examples/tree/master/redirect
Remember you only need to deploy the redirect once and then forget about it.

**Comment by reginpv** [comment]
I've followed the instructions and I get the below error:
<img width="1437" alt="Screen Shot 2019-04-06 at 5 41 18 AM" src="https://user-images.githubusercontent.com/9961920/55658000-bcc0c280-582e-11e9-81d0-71149fc20fee.png">

**Comment by reginpv** [comment]
here's my now.json
```
"alias": [
    "www.domain.com"
  ],
"routes": [
    { "src": "/(.*)", "status": 301, "headers": { "Location": "https://www.domain.com/$1" }}
]
```

I issue is I want to require www, non-www to redirect to www's

**Comment by sboerrigter** [comment]
I had the same problem and found out that you should add the config from https://zeit.co/guides/redirect-from-www to `redirect/next.json` and not to the `next.json` file in the project root. Maybe you have the same issue?
