### ISSUE TITLE
`firebase-admin` it does not work

### ISSUE THREAD

**Issue by markozxuu** [vercel/vercel#2067]
**NOTE:**  `now-dev` It is available in the canary version of `now cli` 

## Steps to reproduce 🐛 

```sh
git clone https://github.com/MAPESO/now-dev-bug-firebase
cd now-dev-bug-firebase
yarn install  # dependency installation
now dev # note the error output
```

This problem was `ncc` but it was resolved in this PR https://github.com/zeit/webpack-asset-relocator-loader/pull/12. Even though it now works in `ncc` the problem still persists in`now` and `now dev`

**logs**

```sh
Error: package.json does not exist at /private
```

<img width="652" alt="54972002-0cf67580-4f4f-11e9-949e-62fecb026376" src="https://user-images.githubusercontent.com/16585386/55434981-1cc91780-5556-11e9-9057-fd8c1828ab52.png">

**Comment by betsegaw** [comment]
Adding the text of the error message to make it easier for people to find...
```
(node:15004) UnhandledPromiseRejectionWarning: Error: package.json does not exist at /tmp/zeit-fun-0dde8aa1a33/user/api/src/package.json
    at Object.module.exports.exports.find (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:40129:15)
    at Object.<anonymous> (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:103259:12)
    at __webpack_require__ (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:22:30)
    at Object.<anonymous> (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:65647:12)
    at __webpack_require__ (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:22:30)
    at Object.module.exports.date.setLocales.MMMM (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:81670:27)
    at __webpack_require__ (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:22:30)
    at Object.module.exports.P (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:207731:14)
    at __webpack_require__ (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:22:30)
    at Object.module.exports.Object.defineProperty.value (/tmp/zeit-fun-0dde8aa1a33/user/api/src/decks/index.ts:172279:19)
(node:15004) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by betsegaw** [comment]
Is there any ETA on when this might get investigated/fixed?

**Comment by betsegaw** [comment]
Seems to be fixed as of `15.0.9-canary.1`. @MAPESO is it also fixed for you?

**Comment by markozxuu** [comment]
> Seems to be fixed as of `15.0.9-canary.1`. @MAPESO is it also fixed for you?

@betsegaw could you show me an example 🙏

**Comment by markozxuu** [comment]
@betsegaw The problem still persists, the difference is that now it does not show any error `now dev`.

**Comment by markozxuu** [comment]
@betsegaw Did you manage to connect to **firestore** with` now dev`?

**Comment by betsegaw** [comment]
@MAPESO yes it did and I was able to get a reply from local queries just fine. Will try to put together a sample and send it your way. I am using it currently on a private repo so I can't link directly to my project but yeah, latest canary version seems to work for me.

**Comment by betsegaw** [comment]
Probably a couple of hours before I get the chance to send it though.

**Comment by guybedford** [comment]
@MAPESO another thing you might check here is if node_modules/google-gax and node_modules/google-proto-files both exist.

**Comment by markozxuu** [comment]
@betsegaw 

> Seems to be fixed as of `15.0.9-canary.1`.

I need more information 🙏

**Comment by danoc** [comment]
This is working for me in `15.1.0`, although I don't know which version it was fixed in.

I'm getting these warnings/errors in the terminal, but they don't seem to cause any issues:

```
ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/@firebase/database/dist" attempted to require "request" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/retry-request" attempted to require "request" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
```

If it's not important, is there a way to silence the message?

**Comment by markozxuu** [comment]
> This is working for me in `15.1.0`, although I don't know which version it was fixed in.
> 
> I'm getting these warnings/errors in the terminal, but they don't seem to cause any issues:
> 
> ```
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/@firebase/database/dist" attempted to require "request" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/retry-request" attempted to require "request" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
> ```
> 
> If it's not important, is there a way to silence the message?

works with `now dev` or `now` ? I'm aware that in `ncc` it works

**Comment by danoc** [comment]
> > This is working for me in `15.1.0`, although I don't know which version it was fixed in.
> > I'm getting these warnings/errors in the terminal, but they don't seem to cause any issues:
> > ```
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/@firebase/database/dist" attempted to require "request" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/retry-request" attempted to require "request" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
> > ```
> > 
> > 
> > If it's not important, is there a way to silence the message?
> 
> works with `now dev` or `now` ? I'm aware that in `ncc` it works

It's working for me with both `now dev` and `now`. I'm using it to read and write to Firebase's Firestore and Storage products.

**Comment by markozxuu** [comment]
@danoc 

> This is working for me in `15.1.0`, although I don't know which version it was fixed in.
> 
> I'm getting these warnings/errors in the terminal, but they don't seem to cause any issues:
> 
> ```
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/@firebase/database/dist" attempted to require "request" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/retry-request" attempted to require "request" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
> ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
> ```
> 
> If it's not important, is there a way to silence the message?

Are you still seeing the messages? @danoc : )

**Comment by markozxuu** [comment]
@danoc The messages does not provides any value to the user. It would be a good idea to silence these messages

**Comment by danoc** [comment]
> @danoc
> 
> > This is working for me in `15.1.0`, although I don't know which version it was fixed in.
> > I'm getting these warnings/errors in the terminal, but they don't seem to cause any issues:
> > ```
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/@firebase/database/dist" attempted to require "request" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/hash-stream-validation" attempted to require "fast-crc32c" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/retry-request" attempted to require "request" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/write-file-atomic" attempted to require "worker_threads" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/google-gax/build/src" attempted to require "@grpc/grpc-js" but could not be resolved, assuming external.
> > ncc: Module directory "/private/var/folders/qs/rgfhf56n7pddh_nzcb6ljllh0000gp/T/co.zeit.now/dev/workPaths/sgkdk5vo/node_modules/bytebuffer/dist" attempted to require "memcpy" but could not be resolved, assuming external.
> > ```
> > 
> > 
> > If it's not important, is there a way to silence the message?
> 
> Are you still seeing the messages? @danoc : )

Yes! Still seeing the messages. Although perhaps that's an issue for `ncc`, not `now-cli`.

**Comment by TooTallNate** [comment]
Closing because it sounds like the original reported issue sounds like it was resolved.

As for the `ncc` warnings, the `@now/node` builder no longer uses [`ncc`](https://github.com/zeit/ncc), but now uses [`node-file-trace`](https://github.com/zeit/node-file-trace).

If you are still experiencing any issues, please create a new issue 👍
