### ISSUE TITLE
How to debug Now CLI?

### ISSUE THREAD

**Issue by borekb** [vercel/vercel#2077]
I basically want to do something like

```
node --inspect-brk node_modules/.bin/now
```

but that is a symlink to `node_modules/now/download/dist/now` which is a binary file. What's the best way to start a debugging session?

(My use case is to debug Now builders: https://github.com/zeit/now-builders/issues/343.)

**Comment by borekb** [comment]
I've also tried this:

```
$ NODE_OPTIONS='--inspect-brk' now dev
now: bad option: --inspect-brk
```

I'm on Node v10.12.0.

**Comment by sfkiwi** [comment]
+1. Would it be possible to attach the debugger to the ‘now dev’ process? I’m also looking to debug from either chrome://inspect or visual studio code. Would speed up dev 100X. Im building combo of @now/next with @now/node api routes.

**Comment by borekb** [comment]
I didn't have time to fully look into it but I think that the binary packs Node itself so that's probably why `NODE_OPTIONS` doesn't work.

A suggestion from [this comment](https://github.com/zeit/now-builders/issues/343#issuecomment-479905167) is to clone now-cli and set breakpoints there.

**Comment by offero** [comment]
This is necessary for me. This was the first question I asked while looking to switch to using `now dev`.

**Comment by dearcodes** [comment]
Critical feature if Now CLI is to be considered production ready solution.

**Comment by paul-vd** [comment]
> Critical feature if Now CLI is to be considered production ready solution.

Now CLI is production ready though? `now dev` is a beta feature that is not required for production...

Back to subject this would be a create implementation, will allow for a much better development experience, @TooTallNate any plans for this in the future?

**Comment by TooTallNate** [comment]
Closing this one because as of Now CLI >= v16.0.0, the `pkg` pre-compiled binaries are no longer used, and the installation mechanism is purely `npm`/`yarn`. So the originally proposed `node --inspect-brk node_modules/.bin/now` works as expected.

**Comment by hainessss** [comment]
Can you provide a full example of how to debug using now dev?

**Comment by Vadorequest** [comment]
I've just managed to have working breakpoints when debugging my Next.js app using WebStorm.

First, you need to add the following dev dependencies to your project:
- `yarn add -D cross-env concurrently`

I personally used those specific versions:
    "concurrently": "5.0.0",
    "cross-env": "6.0.3",

---

![image](https://user-images.githubusercontent.com/3807458/68287152-8d06c100-0082-11ea-81d2-b43a1e9e67df.png)

`Application parameters`: `node_modules/cross-env/src/bin/cross-env-shell.js 'npx concurrently -p '{name}' -n 'debugger,now-cli' -c 'gray.bgWhite,yellow.bgBlue' \"node --inspect-brk node_modules/.bin/now\" \"yarn start\"'`

Where my `yarn start` script is `now dev --local-config=now.demo.staging.json --listen 8888`

![image](https://user-images.githubusercontent.com/3807458/68287827-a5c3a680-0083-11ea-9751-c7fceb6f3402.png)


It feels a bit hacky though. The debugger is started multiple times for some reason, and my project was also deployed on Zeit platform but it's not on purpose and rather a bug.

Nevertheless, it allows to run my Next.js app powered by Now CLI from my local computer in debug mode and use breakpoints, which is what I really needed. But I'd prefer to find a cleaner way to do that.

**Comment by jake-101** [comment]
How would this be done in VS Code?

**Comment by Vadorequest** [comment]
@jake-101 I don't know, as I don't use VS Code.

**Comment by dohomi** [comment]
@TooTallNate is it possible to debug now with Now CLI?

```
Node Parameter: node_modules/.bin/now 
Application Parameter: dev --listen 3004
```
The debugger is starting the process but the code never stops at any breakpoint (I am using `now dev` with TypeScript.)

Do I miss anything to make this work?

**Comment by sdgandhi** [comment]
@Vadorequest you're calling `now` twice, first in application parameters, then in your yarn script.

**Comment by jake-101** [comment]
I used env instead of secrets and put everything in a nextjs project. I was able to debug in vs code that way, it also compiles much faster than now cli.

**Comment by Vadorequest** [comment]
We've just released https://github.com/UnlyEd/next-right-now Next.js/Zeit/TypeScript boilerplate, with integrated debug configuration for WebStorm.

If someone would like to add support for VS Code, we'd love a PR! :)
