### ISSUE TITLE
1.0.0 / now alias ls error

### ISSUE THREAD

**Issue by purplecones** [vercel/vercel#208]
I started getting this error after upgrading to 1.0.0 and using `now alias ls`.

```
> Error! Invalid number of arguments. Usage: `now alias rm <id>`
```

![hyper](https://cloud.githubusercontent.com/assets/136654/21773450/26a79a3a-d65d-11e6-9b6d-6408135b45af.png)

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now-cli/pull/209
