### ISSUE TITLE
Using different secrets for the same environment variables

### ISSUE THREAD

**Issue by ric2z** [vercel/vercel#2081]
Hey everyone,

We currently have a production and a development environment/phases, where the env variables we use for dev and prod are different. We solved this by using multiple `now.json` files as `now.prod.json`, and `now.dev.json`.

This solution is ok, but the problem here is that we have to replicate the routing for both environments in these two files.

It would be great to be able to target different phases defined by the users, beyond **staging** and **production**. e.g. test, development, staging, production, etc.

There's a discussion in Spectrum about this: https://spectrum.chat/zeit/now/env-variables-specifically-for-now-target-production~a02bbe92-bcd8-4093-abf2-a334a0e571f8

They offer a solution that looks like a great start:
```
"env": {
  "production": {
    "production_var": true
  },
  "staging": {
    "staging_var": true
  }
}
```

**Comment by ghost** [comment]
@ric2z I have the same setup - but want to migrate to github builds where I don't believe this is supported. So an addition to this request would be to ensure a smooth github process to allow different vars per environment, I have a test database that I wish to use for pull requests and a production for the merge.

**Comment by agrohs** [comment]
We have the same need (and are relatively shocked that this isn't supported). Is there any ETA on here?

**Comment by notrab** [comment]
I actually think this expands further than just a dev/staging/production ENV to customised context similar to how Netlify does it.

**Comment by leo** [comment]
Thank you for reporting this!

We're indeed working on a specification for environment variables that differ in the environment that they're used in (e.g. production and development could have different cloud-based environment variables).

We'll keep you updated about the progress here.

**Comment by aladinflux** [comment]
Hi @leo, is there any progress? It would be great to have this feature.

**Comment by tsujp** [comment]
Any word on progress @leo ?

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by tsujp** [comment]
> Thank you for creating this issue!
> 
> Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.
> 
> In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.
> 
> For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

I'm confused, didn't you say on the 18th August that this was already in the pipeline...

> Thank you for reporting this!
> 
> We're indeed working on a specification for environment variables that differ in the environment that they're used in (e.g. production and development could have different cloud-based environment variables).
> 
> We'll keep you updated about the progress here.

**Comment by aladinflux** [comment]
I think it's in their pipeline and it's just in their priority list maybe. But it would be useful if they implement something like https://expo.canny.io/feature-requests where they can see what the community desperately needs and re-prioritize their tasks.
