### ISSUE TITLE
`"continue": true` in routes is not supported locally

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2088]
In `now.json`, it is possible to set global headers by using `"continue": true`.

This setup currently confuses the heck out of now-dev.

```
routes: [
    { 
      "src": "/.*",
      "headers": {"cache-control": "s-maxage=31536000, max-age=0"},
      "continue": true
    },
...
]
```

**Comment by flintinatux** [comment]
Also seeing this.  I tried to follow the example in the VRS demo, and I got a bunch of 404's.
https://github.com/zeit/vrs/blob/master/now.json#L29

I also went hunting in this repo for a `continue` option in the [`dev-router.ts`](https://github.com/zeit/now-cli/blob/canary/src/commands/dev/lib/dev-router.ts), and couldn't find it.  Looks unsupported entirely, and using it to build-out headers incrementally might take a bit of work.
