### ISSUE TITLE
create-react-app and NOW_GITHUB_* envs

### ISSUE THREAD

**Issue by cedric-marcone** [vercel/vercel#2091]
Hello, 
Apps built with CRA can only access build envs prefixed by REACT_APP_.
Is it possible to declare a build env in now.json for which the value would be read from another env variable (aliasing).

Something may exist but I can't find any info in the documentation.
=> Using a $ would work and match the secret syntax injection with @
```
{
  "build": {
    "env": {
      "REACT_APP_COMMIT_REF": "$NOW_GITHUB_COMMIT_REF"
  }
}
```

What do you think ?

**Comment by cedric-marcone** [comment]
For the record, in the meantime, there's a solution (thanks @paulogdm) :
You can do it at build time on the app's side :

`
"now-build": "REACT_APP_COMMIT_REF=$NOW_GITHUB_COMMIT_REF react-scripts build"
`

**Comment by paulogdm** [comment]
I will be closing this request for the time being, as the solution is easily done in the user-land. If in the future that is not the case, we can reopen it!
