### ISSUE TITLE
`now dev` can only be used with Next.js >=8.0.5-canary.8!

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2093]
I am using `@now/next@canary` builder with `Next ^8.0.5-canary.8`.

When `now-dev` renders, I was greeted with 

> `now dev` can only be used with Next.js >=8.0.5-canary.8!

**Comment by brandontle** [comment]
Can confirm also getting this error using: 

Next@8.0.5-canary.15
Now@15.0.3-canary.1

**Comment by leo** [comment]
This works now
