### ISSUE TITLE
15.0.0^: cli issues with Git Bash (MINGW64)

### ISSUE THREAD

**Issue by jvarness** [vercel/vercel#2106]
When I install `now@15.0.0^`, I'm running into a lot of unexpected behaviors.

It appears the shell script that's being installed during the global install process is being generated as such:

```bash
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/node_modules/now/download/dist/now.exe" "$@"
  ret=$?
else 
  node  "$basedir/node_modules/now/download/dist/now" "$@"
  ret=$?
fi
exit $ret
```

I'm not sure why the cases are being duplicated in this instance... But the biggest problem I was experiencing was that `now` spat out no output regardless of how I tried to use it. I think the bash script may have been why.

I modified the script a little bit and it seems to work from DOS or a terminal emulator like MINGW or CYGWIN:

```bash
#!/bin/sh
basedir=$(dirname "$(echo `which $0` | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
    *MINGW*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "node" ]; then
  node  "$basedir/node_modules/now/download/dist/now" "$@"
  ret=$?
else 
  "$basedir/node_modules/now/download/dist/now.exe" "$@"
  ret=$?
fi
exit $ret
```

**Comment by TooTallNate** [comment]
Closing because we have moved away from the `pkg` pre-compiled binaries, so now this `.cmd` file generation is all being handled by `npm`/`yarn`.

Can you please try out Now CLI >= 16.0.0 and open a new issue if you are still experiencing any troubles? Thank you!
