### ISSUE TITLE
Stop hashing binary files or large files

### ISSUE THREAD

**Issue by arunoda** [vercel/vercel#2108]
Recently there are a bunch of errors we saw on GitHub jobs where jobs are getting failed without proper details.

Interestingly these errors have an exit code of `null`. Which is interesting.
Then I debug into more on this and add more tracing and found the root cause.

Here's an example repo: https://github.com/arunoda/be_black/commits/master
Basically this project has a lot of files and some binary files.

These jobs are failing and this is such [a trace](https://ui.honeycomb.io/zeit/datasets/integrations/result/4rpVhC3VZoq/trace/69vw2MeyYbi).
(Check the right hand side for now-cli debug logs)

The last action now-cli performed is hashing. (actually the starting of the hashing)
The process got killed with exit code `null` and signal `SIGKILL`.
Based on a [Google search](https://stackoverflow.com/a/39169784) this happens when the OS killed the process for "Out of Memory" errors in Linux.

So, the potential fix for this is manage the now-cli memory usage is much efficient way.
And stop hashing bigger files or similar action.

See this issue: https://github.com/zeit/now-cli/issues/2072
I could deploy these in my local machine and it's throwing a not relevant error.
I assume `api-deployments` rejects this deployment.

**Comment by arunoda** [comment]
Discussion on Slack: https://zeit.slack.com/archives/CE2LC9PC6/p1554546608756500
Summary:

Accept a maximum-file size to upload from the cli. If a file is bigger than that, `now-cli` throws an error.

**Comment by OlliV** [comment]
Could it be that it's reading the whole file into memory before creating the digest instead of processing in chunks? I think we could set a limit in the cli anyway because the file size limit is well defined and documented.

**Comment by trek** [comment]
Hi @williamli,

Thank you for the bug report. We're closing out older issues that have probably been addressed by now.
