### ISSUE TITLE
NodeJS http.on('connect',(req,socket)) not invoked

### ISSUE THREAD

**Issue by nosovk** [vercel/vercel#2109]
We write small http proxy using nodejs, it works well on localhost, but if we deploy it on zeit it fails, because httpsServer.on('connect', (clientRequest, clientSocket) never executes.
It seems like bug in nodejs implementation of deployment, because on Request invoked as expected.

You can check it here:
https://zeit.co/nosovk/httpproxy/lmeuh5xx6/source?f=src/index.js&handle=nosovk&appname=httpproxy&id=lmeuh5xx6
by setting httpproxy.nosovk.now.sh as http proxy address

**Comment by nosovk** [comment]
https://github.com/zeit/docs/issues/655
probably that issue is related to my situation - but there he got a conclusion that routes section of config has an error.
 ```
 "routes": [
    { "src": "/(.*)", "dest": "/index.js" }
  ],
```
I use such a config, it should pass all requests to my function.

**Comment by Blucbo** [comment]
I did some checking and found out it's really problem on zeit server.

**Comment by nosovk** [comment]
@juliangruber probably it's more bug rather then question...

**Comment by TooTallNate** [comment]
Closing because the `connect` event happens when a WebSocket connection occurs, and currently there is no support for WebSockets on Now v2 (but we are tracking this feature request).

**Comment by nosovk** [comment]
@TooTallNate it's a few years passed now, is there any updates on a question?
