### ISSUE TITLE
Installing npm package with git+https format

### ISSUE THREAD

**Issue by carlosvillu** [vercel/vercel#211]
In my project I´m trying to install npm private packages and other that point at a github repo directly.

The first one worked out great with the flag `--forward-npm`. But I always get a 404 call to Github when trying to install:

`"@schibstedspain/suistudio-fatigue-deps": "git+https://github.com/SUI-Components/suistudio-fatigue-deps"`

The error is as follows,

>   message: 'Response code 404 (Not Found)',
>   host: 'github.com',
>   hostname: 'github.com',
>   method: 'GET',
>   path: '/SUI-Components/suistudio-fatigue-deps/archive/master.tar.gz',
>   statusCode: 404,
>   statusMessage: 'Not Found' }

However, a simple curl to this url works as you might expect.

Is anybody using the same kind of package in their project ?!

Thx,

**Comment by timswalling** [comment]
I'm getting the same error - but only on non-Github repos.

For example, `git+https://github.com/timswalling/now-git-package.git` works perfectly, while `git+https://tswalling@bitbucket.org/tswalling/now-git-package.git` throws the following error:
```
Installing package now-git-package@git+https://tswalling@bitbucket.org/tswalling/now-git-package.git
Error { HTTPError
    at EventEmitter.<anonymous> (/usr/lib/node_modules/@zeit/ace/node_modules/got/index.js:187:24)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Immediate.<anonymous> (/usr/lib/node_modules/@zeit/ace/node_modules/got/index.js:55:8)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
  message: 'Response code 404 (Not Found)',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/tswalling/now-git-package/raw/archive/master.tar.gz',
  statusCode: 404,
  statusMessage: 'Not Found' }
```

Note that the error references Github, even though the repo is hosted on Bitbucket.

**Comment by leo** [comment]
Landed. Shipping!
