### ISSUE TITLE
`now dev` can only be used with Next.js >=8.0.5-canary.14!',

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2114]
I have Next installed in package.json both as 

```
"next": "8.0.5-canary.22",
```

```
"next": "^8.0.5-canary.22",
```

now-cli at `15.0.3-canary.1`

Still gives me
> `now dev` can only be used with Next.js >=8.0.5-canary.14!'

**Comment by markozxuu** [comment]
@williamli he sent me the project so he could try it and it worked.

We perform several tests and we can rule out that this error is not related to the following options:

- cache problem
- different versions of node

**Comment by leo** [comment]
Works now
