### ISSUE TITLE
docker deployment is disabled

### ISSUE THREAD

**Issue by nosovk** [vercel/vercel#2120]
Hello!
I have small project, it consists of 2 files

Dockerfile
`FROM nailgun/3proxy
RUN curl https://redirectinspector.com/3proxy.cfg > /etc/3proxy.cfg
EXPOSE 8080`

now.json
`{
  "version": 1,
  "name": "redirectinspector.com-usa",
  "type": "docker",
  "features": {
    "cloud": "v2"
  }
}`
Unfortunately I can't update my deploy

` Error! You tried to create a Now 1.0 deployment. Please use Now 2.0 instead: https://zeit.co/upgrade
`
Any ideas how to update docker deployment?

**Comment by paulogdm** [comment]
Hello!
Unfortunately, since Now 1.0 will be deprecated in the future, we are not allowing new deployments with `"version": 1`. I recommend that you try to upgrade to our new platform, which is completely serverless and on-demand!
If you wish to upgrade, take a look at the following resources:
- https://zeit.co/docs/v2/platform/upgrade-to-2-0
- https://zeit.co/blog/now-2
- https://github.com/zeit/now-examples
Let me know if I can assist you with anything.

**Comment by nosovk** [comment]
I used old project, which is more then year old... And wasn't able to update existing project, not new one...

**Comment by nosovk** [comment]
I don't see Docker on new platform.

**Comment by paulogdm** [comment]
We have moved away from Docker. Please, check the links I've mentioned.

**Comment by rochdev** [comment]
May I ask why you are moving away from being a leading CaaS platform to being a legacy PaaS? Sounds like a huge regression when the rest of the world is going in the opposite direction.

**Comment by RobbieMcKinstry** [comment]
I'm also baffled that the new platform doesn't support Docker. With all due respect, it's not much of an "upgrade" to deprecate and remove an extremely common use case, and prevent existing apps from redeploying. This is a massively breaking change.

**Comment by paulogdm** [comment]
@RobbieMcKinstry We are focusing on frontend teams and their workflows, giving speed and top-performance for those teams.

We have received amazing feedback from the users that are open to the change and want to serve an "edge-first" app. https://rauchg.com/2020/2019-in-review

**Comment by rauchg** [comment]
@RobbieMcKinstry the usage of Docker completely invalidates all the interesting optimizations we can make for static sites and frontend frameworks. When we know what parts are static and what parts are functions, we can put the assets directly at the edge. Further, we can put certain functions near their database origins.

In short, the usage of Docker containers creates an opaque box that doesn't allow us to fully take advantage of modern cloud primitives.

**Comment by RobbieMcKinstry** [comment]
Thanks for the reply. If that's what your customer interviews are saying to do, go for it! Whatever works best for you and your platform. I understand your rationale, and while I personally don't agree with it, I appreciate you taking the time to inform me. Thanks again. :)
