### ISSUE TITLE
add support for file / folder import into builds

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2122]
Update: Maybe something like this would help https://github.com/zeit/now-cli/issues/2122#issuecomment-496359178

=============

https://spectrum.chat/zeit/general/keep-key-files-private~c522a52f-869b-4fc2-862e-1751d2bce4e1

Sometimes private files are required to be read by server-side scripts. Libraies like Google Cloud Storage, for example, requires to load service-account info from a file.

It would be great if there is a private folder where we can store files to be used by server side scripts. 

Current hack around include:
1. ~using now secrets and somehow echoing this out with a build script~
2. when lambda initiate, check to see if file exist, if not, write now secret to /tmp for consumption

**Comment by wiiiimm** [comment]
@timothyis either way, we should also provide an official guide on how to do this on Now.

**Comment by williamli** [comment]
```
"builds": [
    { "src": "node-routes/defaultRoute.js", "use": "@now/node", "config": { "maxLambdaSize": "40mb" } },
    { "src": "next.config.js", "use": "@now/next" },
    { "src": "gc-service-accounts/IBCOL-bc7c0de657f9.json", "use": "@now/static" },
    { "src": "gc-service-accounts/IBCOL-ab3604e33e20.json", "use": "@now/static" },
    { "src": "gc-service-accounts/IBCOL-29f16744c004.json", "use": "@now/static" }
  ],
"routes": [
    {
      "src": "/gc-service-accounts/.+",
      "dest": "/node-routes/notFoundRoute.js"
    },
]
```

the `notFoundRoute.js` is a simple node script that return 404

```
const { send } = require('micro');
const notfound = (req, res) => send(res, 404, 'invalid endpoint')
module.exports = notfound
```

**Comment by wiiiimm** [comment]
In the end, the only way that I can get it to work is doing the follow at the start of the lambda, outside of the exported module, to write a file out to /tmp folder when the lambda cold boot.

```
fs.writeFileSync('/tmp/somefile', atob(process.env.FILE_CONTENT_BASE64));
```


FILE_CONTENT_BASE64 a secret saved by

`now secrets add FILE_CONTENT_BASE64 $(cat ./somefile | base64) `

**Comment by wiiiimm** [comment]
https://spectrum.chat/zeit/now/what-is-the-proper-directory-for-reading-files-in-nodejs~6cfe7391-12ff-40df-9c11-115fe1931136?m=MTU1OTAxNjUzNzI3OA==

**Comment by wiiiimm** [comment]
If we can allow a "includes" array to be defined for each of the "builds", that might work.

```
"builds": [
  {"src": "app.js", "use": "@now/node", "includes": ["file1", "file2", "/modules/*"]},
  {"src": "server.js", "use": "@now/node", "includes": ["private_file_1"]},
]
```

**Comment by jcblw** [comment]
@williamli I think this would be a perfect solution to this, this is something I tried when running into this issue.

**Comment by TooTallNate** [comment]
Closing because the `includeFiles` config has been added to the `@now/node` builder.

Please see the documentation: https://zeit.co/docs/v2/advanced/builders#including-additional-files
