### ISSUE TITLE
Symlinks are not preserved on now dev

### ISSUE THREAD

**Issue by WesSouza** [vercel/vercel#2123]
My project ([subway-time](https://github.com/WesSouza/subway-time)) is a monolith and uses symlinks to target a folder with files that are generated outside of the api and web routes.

The web route uses Parcel and imports files from it (in order to get the URL for an XHR call).

These are the folders:

```
[ ] api
[ ] data
[ ] web
  '- [ ] src
        '- [ ] data (symlink to ../../data)
```

And this is the error:

```
🚨  /private/var/folders/t5/p3sspx8j2nn8r8ky54k_n4p80000gq/T/co.zeit.now/dev/workPaths/cuvrdmlo/web/src/lib/api.ts:1:28: Cannot resolve dependency '~/data/subway-lines.json' at '/private/var/folders/t5/p3sspx8j2nn8r8ky54k_n4p80000gq/T/co.zeit.now/dev/workPaths/cuvrdmlo/web/src/lib/~/data/subway-lines.json'
    at Resolver.resolve (/private/var/folders/t5/p3sspx8j2nn8r8ky54k_n4p80000gq/T/co.zeit.now/dev/workPaths/cuvrdmlo/node_modules/parcel-bundler/src/Resolver.js:71:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! subway-time-web@1.0.0 build: `npm run type-check && npm run lint && parcel build ./src/index.html --public-url '/'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the subway-time-web@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wesley/.npm/_logs/2019-04-09T15_56_40_386Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> Error! Exited with 1
```

If I copy the directory manually, it runs flawlessly.

This configuration works with `now`, currently deployed at https://subwayti.me/.

I've tested on both stable and canary.

_(By the way, tremendous job on `now dev`! 👏 👏 )_

**Comment by TooTallNate** [comment]
Hey there @WesSouza. This was likely fixed in https://github.com/zeit/now-builders/pull/359. Can you try with the latest version of now-cli and let me know if it's fixed for you?
