### ISSUE TITLE
Remove old deployments for app that are not aliased

### ISSUE THREAD

**Issue by noeljackson** [vercel/vercel#213]
I'm using `now` to deploy my blog, and trying to make deployment seamless by automatically removing old deployments that are not aliased (the non-production ones).

I make sure to name all my deployments under the same app name, so they all show up when I type `now ls domain.com`

However, if I redeploy, I get a list of all former deployments and have to manually delete them.

For the time being I wrote this deploy script. Is there any easier way than this?

A `now rm --not-aliased my-app` would be amazing to have.

```
echo "Deploying $DOMAIN..."
now --static ./public --token=$TOKEN -n $DOMAIN -a $DOMAIN

ALIAS="$(now alias list|grep "$DOMAIN"|awk '/now\.sh/ { print $2}')"

echo "Currently aliased to $ALIAS, removing all others for $DOMAIN..."
now ls $DOMAIN | grep -v "$ALIAS" | awk '/.*([A-Za-z0-9]{24}).*/ { print $1; }' | xargs -I{} now -y rm {}
```

I would be happy to make a PR for now-cli if this is a wanted feature. There is definitely a more elegant way to do this from within the app's code.

**Comment by matiastucci** [comment]
I was having the same need. So, I did this small thing (I'm using it on my CI): [now-purge](https://github.com/matiastucci/now-purge)

**Comment by kylemh** [comment]
I think this can be closed with the introduction of `now rm domain.com --safe`

**Comment by sergiodxa** [comment]
`now rm <app> --save` Let's you remove all non aliases deployments.

**Comment by lujstn** [comment]
@sergiodxa is there a way to run this command silently?

**Comment by swissspidy** [comment]
@lucasjohnston Just send STDOUT and STDERR to `/dev/null`?

**Comment by styfle** [comment]
This command will remove all your non-aliased deployments with the name `my-app`. 

```
now rm my-app --safe --yes
```

This can be run after the `now alias` command to remove the previous deployment of the project.

```
now && now alias && now rm my-app --safe --yes
```

See the [FAQ](https://zeit.co/docs/other/faq#how-do-i-remove-an-old-deployment) documentation.

**Comment by cryptiklemur** [comment]
And how does this work with the github integration?

**Comment by stevez86** [comment]
I'd love for a feature to delete all but the last x number of deployments. I'd definitely use that with every deployment.

**Comment by lishine** [comment]
> I'd love for a feature to delete all but the last x number of deployments. I'd definitely use that with every deployment.

Temporal solution:
Read the deployments url from the dashboard:
```Array.from(document.querySelectorAll('a>span:first-child.deployment-link-content')).map((el)=>el.innerText).join(' ')```
and then
```vercel remove PASTE the ABOVE urls```

**Comment by hoangvvo** [comment]
> > I'd love for a feature to delete all but the last x number of deployments. I'd definitely use that with every deployment.
> 
> Temporal solution:
> Read the deployments url from the dashboard:
> `Array.from(document.querySelectorAll('a>span:first-child.deployment-link-content')).map((el)=>el.innerText).join(' ')`
> and then
> `vercel remove PASTE the ABOVE urls`

For fellow googler, this is the latest js:

```js
Array.from(document.querySelectorAll('.deployment-entity')).map((el)=>el.querySelectorAll('.link_link__2vTGP')).map(node => node[0].innerText).join(' ')
```

(the hash of the css class might change)
