### ISSUE TITLE
`now dev` "spawn EACCES" error

### ISSUE THREAD

**Issue by fmiras** [vercel/vercel#2135]
When using puppeteer (probably also in another spawning processes cases too) the same lambda that works at now platform fails at now dev command

`now dev` logs for `puppeteer-screenshot`:

```bash
✨  Done in 0.38s.
> GET /zeit.co/blog?type=png
downloading user files...
installing dependencies for user's code...
installing to /var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/user
yarn install v1.15.2
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.09s.
writing ncc package.json...
installing dependencies for ncc...
installing to /var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/ncc
yarn install v1.15.2
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.07s.
running user script...
compiling entrypoint with ncc...
ncc: Version 0.17.3
ncc: Compiling file index.js
ncc: Module directory "/private/var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/user/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/user/node_modules/https-proxy-agent/node_modules/debug/src" attempted to require "supports-color" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/user/node_modules/ws/lib" attempted to require "utf-8-validate" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/user/node_modules/ws/lib" attempted to require "bufferutil" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/user/node_modules/chrome-aws-lambda/source" attempted to require "puppeteer" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/user/node_modules/chrome-aws-lambda/source/puppeteer/lib" attempted to require "puppeteer" but could not be resolved, assuming external.
ncc: Module directory "/private/var/folders/d4/gm55twv926v_p0mf_d4fkx3r0000gn/T/co.zeit.now/dev/workPaths/e2ukoqf1/user/node_modules/chrome-aws-lambda/source/puppeteer/lib" attempted to require "puppeteer" but could not be resolved, assuming external.
spawn EACCES
```

**Comment by elie222** [comment]
Any ideas on this?

**Comment by leopku** [comment]
same problem too

**Comment by maiertech** [comment]
See also https://github.com/zeit/now-cli/issues/2426.

**Comment by 59023g** [comment]
For sure it has to do with `chrome-aws-lambda` being run outside of an AWS Lambda (as @454de6e) pointed out. 

So it has to do something with the Chromium app being launched via `executablePath` option.

First I changed `executablePath` to Puppeteer's Chromium dependency automatically installed via `npm install puppeteer`.  So: 
```javascript
await puppeteer.launch({
 executablePath: "/node_modules/puppeteer/.local-chromium/mac-672088/chrome-mac/Chromium.app/Contents/MacOS/Chromium"
})
```
And I made sure I had permissions to launch via `chmod`. But the issue it appear with `now` is that all the dependencies are moved elsewhere and Chromium app does not come with it. Even locally. See:
```bash
Error: Failed to launch chrome! spawn /private/var/folders/pw/3qwmxxkj5sx7t8z1brg90hn00000gn/T/zeit-fun-ff3070f987b3d/lib/node_modules/puppeteer/.local-chromium/mac-672088/chrome-mac/Chromium.app/Contents/MacOS/Chromium ENOENT
```
This may be on purpose not sure. So on to the next...


Searching the Puppeteer repo I found if you point to a Chromium installation on your machine, it'll work. But it has to be the same revision as your Puppeteer-Core lists in its' `package.json`. So in my case, I'm using revision `672088`. 

Which can be downloaded here: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac/672088/

Once I unzipped that, moved the app to my Applications dir, it worked:

```javascript
await puppeteer.launch({
 executablePath: "/Applications/Chromium.app/Contents/MacOS/Chromium"
})
```

Then practically I just had an `if-else` which changed the `executablePath` and chrome dependency based on the environment. So `'chrome-aws-lambda'` as in the example for the remote deployment, then above for `now dev`.

**Comment by TooTallNate** [comment]
Indeed this error happens because on macOS you can not launch the `chrome-aws-lambda` binary that is compiled for AWS Linux. See here for the recommended way to support `now dev` in your project:

https://github.com/zeit/og-image/blob/c06a2f573d4b467148c2ebd0e305e68a9bf2f9f9/api/_lib/options.ts#L2-L26
