### ISSUE TITLE
`now dev` on Windows 10 throws "statCache does not contain value for next.config.js"

### ISSUE THREAD

**Issue by krstffr** [vercel/vercel#2145]
I have a project which works fine on mac running `now dev`, but throws the following error on Windows 10:

`> Error! statCache does not contain value for next.config.js (resolved to C:\Users\REDACTED\REDACTED\next.config.js)`

Here's the contents of the `next.config.js` file:
```
// next.config.js
const withTypescript = require("@zeit/next-typescript");
module.exports = withTypescript({
  target: "serverless"
});
```

Is this a known issue? Or is `now dev` maybe not ready for Windows yet?

**Comment by PullJosh** [comment]
I'm getting the same error, also with Next, also on Windows 10.

**Comment by PullJosh** [comment]
Hmm... Looks like the problem is also happening on non-Next builds (still Windows 10).

**Comment by joshleblanc** [comment]
Just piping in to say I get that error on a node-server build type. 

now.json

```
{
  "name": "now-test",
  "version": 2,
  "builds": [
    {
      "src": "server/index.js",
      "use": "@now/node-server"
    },
    {
      "src": "client/next.config.js",
      "use": "@now/next"
    }
  ],
  "routes": [
    {
      "src": "/graphql",
      "dest": "server/index.js"
    },
    {
      "src": "/(.*)",
      "dest": "client/$1"
    }
  ],
  "env": {
    "MONGO_URL": "@apollo-test-mongo-url",
    "JWT_SECRET": "@jwt-secret"
  }
}
```

**Comment by joshleblanc** [comment]
I figure I'd get it on the next build too, but it doesn't make it that far. Probably a windows issue. 

Everything's always a windows issue

**Comment by kg55kmr** [comment]
Same problem

**Comment by TooTallNate** [comment]
Thanks for the report everyone. `now dev` on Windows will indeed need some additional work. We are focusing on making it work for Linux and macOS first, but Windows support will be coming after that as well 👍

**Comment by TooTallNate** [comment]
Hey all, can you give [`now@15.0.11-canary.2`](https://github.com/zeit/now-cli/releases/tag/15.0.11-canary.2) a try, which includes initial Windows support. Please open a new issue if you have any issues.
