### ISSUE TITLE
`now dev` is not respecting methods of routes

### ISSUE THREAD

**Issue by khrome83** [vercel/vercel#2148]
## Issue

When sending a `GET` request to `localhost:3000/api/users/14` it returns with the response from the `DELETE` method. It does not appear that `now dev` is respecting methods on the route.

Similarly, if a `POST` request is made to `localhost:3000/api/status`, it is accepted, even though it is not a valid method.

```
{
  "version": 2,
  "name": "now-dev-issue",
  "builds": [
    { "src": "www/package.json", "use": "@now/static-build" },
    { "src": "api/*/*.js", "use": "@now/node@canary" }
  ],
  "routes": [
    { "src": "/api/status", "methods": ["GET"], "dest": "/api/status/list.js" },
    { "src": "/api/users", "methods": ["POST"], "dest": "/api/users/create.js" },
    { "src": "/api/users/(?<id>[^/]+)", "methods": ["DELETE"], "dest": "/api/users/delete.js?id=$id" },
    { "src": "/api/users/(?<id>[^/]+)", "methods": ["GET"], "dest": "/api/users/get.js?id=$id" },
    { "src": "/api/users/(?<id>[^/]+)", "methods": ["PUT"], "dest": "/api/users/update.js?id=$id" },
    { "src": "/(.*)", "dest": "/www/$1" }
  ]
}
```

## Sample Branch
https://github.com/khrome83/now-dev-issue

**Comment by khrome83** [comment]
I validated this only happens with `now dev` and the behavior of methods works as expected when deployed. So this is a valid bug.

**Comment by adamwathan** [comment]
Can confirm, works in production but methods are not respected in development which makes local dev basically impossible right now 😬

**Comment by khrome83** [comment]
@adamwathan - yeah right now I have to switch which methodis first. It seems to take the first one and use that and ignore the other methods, basically the first "match".

The issues seems to be when a "DELETE" method comes in, it takes the first, even if it is a "GET" or "POST". So to develop "DELETE", I had to move that entry higher in the routes object.

This is a HORRIBLE work around. Espcially if you want to run a test suite, or insert and then update something.

**Comment by TooTallNate** [comment]
Hey there, I've posted a PR to fix this, should be landed very shortly. Thanks for your patience!

**Comment by patrikengborg** [comment]
I really can't get this to work. When using:

```
{
  "routes": [
    {
      "src": "/api/user.js",
      "methods": ["GET"],
      "dest": "/api/user.js"
    }
  ]
}
```

The route is still accessible by POST. Was this issue ever fixed?

**Comment by wiiiimm** [comment]
@patrikengborg given that we are on our way to deprecate routes in favour of redirects, rewrites, and headers, you might want to handle method checkings in your code logic.

https://zeit.co/docs/configuration#project/routes
