### ISSUE TITLE
Unable to server website from monorepo with `now dev`

### ISSUE THREAD

**Issue by khrome83** [vercel/vercel#2149]
I recently migrated the `Nuxt` example to a monorepo to resolve issues with the API constantly rebuilding `nuxt generate`.

After following the work done at https://zeit.co/examples/monorepo/ I don't have any idea what is going on. Before moving the Nuxt content into the `www` folder, I could get to the index page. After moving it, I am unable too. I update the build and added the www forward route following the example.

Is there something the `next` example is doing that is missing from a standard `static-build`?

https://github.com/khrome83/now-dev-issue

**Comment by khrome83** [comment]
This appears to be an issue with `now dev` and does not impact actual deploys to now.

**Comment by thasophearak** [comment]
👋 @khrome83 we recently shipped a lot of bug fixes regarding `now dev`. Please feel free to try the monorepo example again. It should be working as expected. Let us know if you have any trouble with it.

**Comment by khrome83** [comment]
sure, I will let you know. What very should `now dev` be at? Or does it ship with `now-cli` and I watch that version?
