### ISSUE TITLE
`@now/node` problem with koa-ts

### ISSUE THREAD

**Issue by markozxuu** [vercel/vercel#2158]
**now version**: 15.0.4-canary.6
**build**: @now/node

## Steps to reproduce 🐛 

```sh
git clone https://github.com/zeit/now-examples
cd nodejs-koa-ts
yarn install  # dependency installation
now dev 
```

I'm testing the example of **nodejs-koa-ts** of now-examples but i can not access the other routes

![2019-04-12 21 46 10](https://user-images.githubusercontent.com/16585386/56073587-832b1280-5d6c-11e9-9ff8-99a82ad3e7e1.gif)

**Comment by markozxuu** [comment]
Thank you @TooTallNate  :)

**Comment by TooTallNate** [comment]
Nice catch @MAPESO 👍
