### ISSUE TITLE
Error with aliasing a subdomain: Unable to verify. Please try the alias again later

### ISSUE THREAD

**Issue by johnlindquist** [vercel/vercel#216]
```
now alias https://ramda-repl-zsofwtzrvd.now.sh repl.johnlindquist.com
> repl.johnlindquist.com is a custom domain.
> Verifying the DNS settings for repl.johnlindquist.com (see https://zeit.world for help)
> Detected zeit.world nameservers! Configuring records.
> DNS Configured! Verifying propagation…
> Error! > We configured the DNS settings for your alias, but we were unable to verify that they've propagated. Please try the alias again later.
```

I've been trying this command for the past day.

johnlindquist.com is pointing to the zeit.world nameservers. Am I missing a config step or is something broken?

**Comment by jamo** [comment]
The propagation test is currently done in the client; so a slow dns server could be causing it.
`dig repl.johnlindquist.com` should return the same A records as `dig alias.zeit.co` 

And as now by default adds `*` CNAME to alias.zeit.co for all zeit.world domains, the result for anything.yourdomain.com should resolve to the same ip address as alias.zeit.co

However, it seems that e.g. asd.johnlindquist.com resolves correctly, but repl.johnlindquist.com doesn't. So did you maybe `now domains add` the subdomain - when adding just the apex domain is needed.

**Comment by johnlindquist** [comment]
@jamo yeah, I've been playing with adding the subdomain as a workaround. I'll remove it and try again.

**Comment by johnlindquist** [comment]
Weird, deleted the 'repl' record, still doesn't work.

Tried with two other domains, they both work:
https://ramdarepl.johnlindquist.com/
https://somerepl.johnlindquist.com/

Wonder why `repl` keeps erroring out :/

**Comment by jamo** [comment]
seems like domain repl.johnlindquist.com is still configured as a external unverified domain -- and thus it causes the dns to behive unexpectedly...
try `now domains ls` and then I'd suggest to `now domains rm <domainId>` for the repl.johnlindquist.com

**Comment by johnlindquist** [comment]
Thanks so much, `now domains rm id` worked. 😄 

For anyone else reading this issue in the future:
Adding a subdomain with `now domains add repl.johnlindquist.com` was a mistake. Then when  tried to fix it, I was only removing the record with `now dns rm recordId` when I should've been removing the domain itself using `now domains rm domainId`.

**Comment by juliaqiuxy** [comment]
For those of you who are still having issues with propagation, try flushing your local DNS before trying again. Here's what worked for me on macOS Sierra:

```bash
sudo killall -HUP mDNSResponder
```

**Comment by irisSchaffer** [comment]
Updating `now` is what did the trick for me.
