### ISSUE TITLE
now ls does not list all deployments

### ISSUE THREAD

**Issue by lipp** [vercel/vercel#217]
`now ls` without additional args does not list all deployments:

```
now ls
...
compliments

  XXX      https://compliments-XXX.now.sh      41d ago

```

whereas with the respective package name it is complete:

```
now ls compliments 
> 5 deployments found [936ms]

compliments

  XXX      https://compliments-xxxrcdds.now.sh      26s ago
  XXX      https://compliments-xxxsnidwqh.now.sh      51m ago
  XXX      https://compliments-xxxxpvfgof.now.sh      52m ago
  XXX      https://compliments-xxxyuapbxn.now.sh      57m ago
  XXX      https://compliments-xxxnxidbxz.now.sh      41d ago
```

```
now --version
𝚫 now 2.0.3
```

**Comment by OlliV** [comment]
What's missing? 🤔

**Comment by lipp** [comment]
some of my deployments... the recent ones

**Comment by jamo** [comment]
Some additional information would make it easier to troubleshoot this :)

**Comment by lipp** [comment]
sorry... updated the issue

**Comment by lipp** [comment]
Ok. Narrowed it down: The shell with the freshly updated `now` does not work (reporting `2.0.3` as version, though). A "new" shell DOES work.

**Comment by lipp** [comment]
Is it mandatory to spawn a new shell after update? I cannot remember doing so with previous updates of now...

**Comment by jamo** [comment]
Indeed it seems that there was a regression in the api causing it to return incomplete lists for a few users... Thanks for reporting!
 
We've now applied a fix and the list should now show up in full.
 Please verify it and reopen/comment in case the list still feels incomplete!

**Comment by jamo** [comment]
Afaik updates will essentially replace the existing binary; so it shouldn't be necessary to open a new shell for the update to take affect

**Comment by lipp** [comment]
THX!

**Comment by OlliV** [comment]
Thanks :)
