### ISSUE TITLE
Now + Gitlab stopped working

### ISSUE THREAD

**Issue by sobolevn** [vercel/vercel#2173]
I am using new `now` + `gitlab` integration. It worked perfectly until today.

For some reason bot stopped to comment on new commits, external CIs are not created, deployment information is now updated.

## How it was

I had this `now.json` file:

```json
{
  "name": "timeless_is",
  "version": 2,
  "alias": "timelessis-git-master.kira-bot.now.sh",
  "builds": [{
    "src": "package.json",
    "use": "@now/static-build"
  }],
  "build": {
    "env": {
      "API_URL_BROWSER": "https://jsonplaceholder.typicode.com"
    }
  }
}
```

And it worked:

- [Stage environment](https://timelessis-git-master.kira-bot.now.sh)
- [Stage styleguide](https://timelessis-git-master.kira-bot.now.sh/styleguide/index.html)

I also had comments from my bot on both merge requests and commits:
<img width="922" alt="Снимок экрана 2019-04-16 в 14 47 33" src="https://user-images.githubusercontent.com/4660275/56207123-a6004400-6056-11e9-8a0a-63b76a649088.png">
<img width="289" alt="Снимок экрана 2019-04-16 в 14 47 19" src="https://user-images.githubusercontent.com/4660275/56207124-a6004400-6056-11e9-8857-0a5422fd05e5.png">

## What happened 

Yesterday I had to test some things locally. So I used `now-cli` with another user (my bot is @kira-bot, my real account is @sobolevn, both are Gitlab usernames). Locally everything worked fine. I had a new project created under my username. I did not change project name in `now.json`.

This is just a story. May be 100% unrelated.

## Problem

Since today I do not receive any comment from my bot on this project. And other projects as well.

I made a quick reproduction repo: https://gitlab.com/sobolevn/now-gitlab-bug/merge_requests/1

With this `now.json`:

```json
{
  "name": "now-gitlab-bug",
  "version": 2,
  "alias": "now-gitlab-bug-git-master.sobolevn.now.sh",
  "builds": [{
    "src": "index.html",
    "use": "@now/static"
  }],
  "build": {
    "env": {
      "API_URL_BROWSER": "https://jsonplaceholder.typicode.com"
    }
  }
}
```

Everything is setup:
1. Integration
<img width="445" alt="Снимок экрана 2019-04-16 в 14 59 24" src="https://user-images.githubusercontent.com/4660275/56207808-5884d680-6058-11e9-8baf-392fd4e28aa1.png">

2. Webhook
<img width="1140" alt="Снимок экрана 2019-04-16 в 14 59 54" src="https://user-images.githubusercontent.com/4660275/56207829-62a6d500-6058-11e9-857c-64796e5c35c1.png">

However, no project is created in my dashboard:
<img width="1073" alt="Снимок экрана 2019-04-16 в 15 01 13" src="https://user-images.githubusercontent.com/4660275/56207885-89650b80-6058-11e9-8aea-345ea6ee24da.png">

## Things I have tried

1. Delete all integrations
2. Delete existing projects
3. Resetup everything
4. Change aliases, names, other fields in `now.json`

**Comment by sobolevn** [comment]
## Update

I have tried to manually execute hooks with `gitlab test webhook`:

<img width="812" alt="Снимок экрана 2019-04-16 в 15 20 26" src="https://user-images.githubusercontent.com/4660275/56209016-2e80e380-605b-11e9-9a37-d580b7f02e20.png">


1. Merge request hook returned:
<img width="282" alt="Снимок экрана 2019-04-16 в 15 19 49" src="https://user-images.githubusercontent.com/4660275/56208966-17da8c80-605b-11e9-8b23-ea3b4436c891.png">

But nothing has changed.

2. Push hook returned the same, but `now` created a new project in the dashboard: 
<img width="1029" alt="Снимок экрана 2019-04-16 в 15 21 20" src="https://user-images.githubusercontent.com/4660275/56209076-52dcc000-605b-11e9-8bd1-f656e9cfeb8d.png">
Link: https://zeit.co/sobolevn/now-gitlab-bug

## Second commit

After the project was created, I made a new commit.
Still no progress.

**Comment by sobolevn** [comment]
As a workaround I will use https://hugo.md/post/now-review-app-post/ for now

**Comment by arunoda** [comment]
@sobolevn since this is not exactly a `now-cli` issue, let's discuss over here: https://spectrum.chat/zeit/now/now-gitlab-com-integration-stopped-working~a2bf7189-baf6-4269-8a15-b7e5d85418de

**Comment by arunoda** [comment]
BTW: @sobolevn, Thanks for making this issue.

**Comment by sobolevn** [comment]
Just for the history. It works again. Nothing has changed from my side.
Thanks!
