### ISSUE TITLE
inconsistently stuck on deploy

### ISSUE THREAD

**Issue by purplecones** [vercel/vercel#219]
I get this occasionally where a deploy gets stuck when deploying a project

![hyper](https://cloud.githubusercontent.com/assets/136654/21918163/7a16122a-d91c-11e6-817f-052c9afe380f.png)

CTRL-C and running command tends to fix it but is not consistent.

![hyper](https://cloud.githubusercontent.com/assets/136654/21918190/c5fb6636-d91c-11e6-992c-8a79a5f81f8d.png)

Anyone else observe this?

**Comment by zrrrzzt** [comment]
Most of my deploys get stuck on ```Initializing```at the moment. Started around 15 hrs ago.

Here's an example https://micro-brreg-mvbzeeupsd.now.sh/

**Comment by jamo** [comment]
Could you try redeploying with `-f` flag - in case it's related to issues with file uploads.
`now -f`
Let me know if it helps

**Comment by onbjerg** [comment]
Same here. Just set up now on CircleCI. Stuck on "Initializing".

**Comment by zrrrzzt** [comment]
I think this might be more related to network or other services and not to the cli. 
A couple of my aliased deployments stopped working for  a couple of hours as well but now everything is back to normal.

**Comment by purplecones** [comment]
@jamo I will try that the next time this issue happens.

**Comment by Stas-Buzunko** [comment]
the same thing. deployed on 4-5th deploy only.
when I tried to deploy next time it took 41sec to deploy, I have one file with 170 lines :D 
![image](https://cloud.githubusercontent.com/assets/12331100/21948287/ba892a76-da1c-11e6-96a8-0d5f61f87448.png)

**Comment by onbjerg** [comment]
It worked after 4-5 deploys for me too, however this also coincides with me adding an alias to the deployment. Maybe related?

With the `-d` flag it seems like it was stuck on "Closing agent".

And yeah, deployments are pretty slow right now for me too.

**Comment by ghost** [comment]
Anyone still experiencing this? I'm finding that when running `now install`, i'm just getting (very quickly):

Initializing
[debug] closing agent

Whereas yesterday I'd see the console logs related to my installation process, build process, etc.

**Comment by leo** [comment]
Should be fixed now! 😊

**Comment by dhruska** [comment]
I seem to be having this problem this evening - repeatedly stuck on Initializing...

**Comment by leo** [comment]
@dhruska Version of `now`?

**Comment by dhruska** [comment]
@leo 6.3.1

**Comment by dhruska** [comment]
If it helps, when I run `now ls` it appears that the instance is stuck in BOOTED state

**Comment by leo** [comment]
@OlliV @jamo

**Comment by jamo** [comment]
We've identified and fixed one rare issue which left a small portion of new deployments hanging in `BOOTED`

**Comment by anaibol** [comment]
This is happening to me on v7.1.1

![screenshot_20170719_161144](https://user-images.githubusercontent.com/3210177/28371382-1ee98656-6c9d-11e7-81e0-ef112f7f62b8.png)
