### ISSUE TITLE
`@now/bash` won't work

### ISSUE THREAD

**Issue by atarumix** [vercel/vercel#2190]
`@now/bash` won't work
now version: 15.0.5
build: @now/bash

```sh
$ git clone https://github.com/zeit/now-examples
$ cd bash
$ now
```
then,
```
$ curl https://bash.atarumix.now.sh
An error occurred with your deployment

NO_STATUS_CODE_FROM_LAMBDA
```
Perhaps this problem is from version 15.0.2 or 15.0.3.

**Comment by paulogdm** [comment]
Hello!
We are working on a fix as we speak. For now, use the following now.json:
```json
{
  "version": 2,
  "public": true,
  "builds": [
    { "src": "index.sh", "use": "@now/bash" , "config": { "useBuildUtils": "@now/build-utils@canary" } } }
  ]
}
```

**Comment by styfle** [comment]
Hi @atarumix 

Just following up here. Are you still using `@now/bash`? I would like to invite you to our slack workspace to get some feedback.
