### ISSUE TITLE
How to distinct now --target staging and now --target?

### ISSUE THREAD

**Issue by greatdolphinls** [vercel/vercel#2192]
Now I am using production and staging server.
But process.env.NODE_ENV is production in the two case.
How can I distinct them?

**Comment by pur3miish** [comment]
Not the most elegant solution, but this works. 

package.json
```json
"scripts" {
  "deploy:production": "now --target production -e STAGED=false",
  "deploy:staged": "now --target staging -e STAGED=true"
}
```
then inside app
```js
process.env.STAGED == true
```

**Comment by leo** [comment]
We will soon be announcing `now.js` (please monitor our [blog](https://zeit.co/blog)), which is going to solve this.

**Comment by andrew-oko-odion** [comment]
Any Update on this issue yet?

**Comment by andrew-oko-odion** [comment]
Also env's in next.config.js always changes envs passed to now 
how can one solve this?
