### ISSUE TITLE
now dev never finishes

### ISSUE THREAD

**Issue by ekkis** [vercel/vercel#2197]
```
~/dev/tst $ now dev
> Running initial builds
```

and that's the last I hear of it.  it never moves onto a next step

running on OSX 10.14.4, Node 11.5.0, Now 15.0.7-canary.2 and my setup is super easy:
```json
 {
	"src": "server.js",
	"use": "@now/node",
	"config": { "maxLambdaSize": "40mb" }
}
```

I know it's beta so there are no docs, but, is there something else I have to do? typically I deploy with just `now`, but when my code fails I'm stuck as the log messages refer to lines in a super-large file generated by now that I can't correlate to my code

**Comment by styfle** [comment]
Can you test with the latest version [15.0.7](https://github.com/zeit/now-cli/releases/tag/15.0.7).

If it still fails please post the contents of `server.js`.

Thanks!

**Comment by ekkis** [comment]
ha! that worked.  when I ran it, it showed the location where it's built as `/var/folders/8q/q2rvsm3d2pj6fwbth49cp3r00000gn` but if I do:
```bash
$ find . -name index.js |grep -v node_modules |more
```
I don't find the file... my file is actually called `server.js` and I find 4 of those:
> ./T/co.zeit.now/dev/workPaths/ne3ha4pg/server.js
> ./T/co.zeit.now/dev/workPaths/l7uqsbfo/server.js
> ./T/zeit-fun-c8078ee2fccb2/server.js
> ./T/zeit-fun-55cc3fda90745/server.js

which is the one I care about?

**Comment by styfle** [comment]
The `workPath` is created for each build so those could be the same file.

I think you misunderstood. I don't need the built files, I need the source `server.js` file so I can reproduce your problem. 😄 

Are you still having a problem?

You can also `now dev --debug` to get more verbose output.

**Comment by ekkis** [comment]
I don't want to burden you with my problem... at least not yet :)

what I was hoping for is that with `now dev` I could avoid making 1,000 deployments as I try to debug my problem.  part of the issue is that when the app breaks in production, it gives me line numbers to a huge `index.js` that I don't have access to, so it's impossible for me to know what's breaking.  now that I'm running locally, if I can find the correct file, I can correlate the error message stack trace to the correct code

**Comment by styfle** [comment]
> when the app breaks in production, it gives me line numbers to a huge index.js that I don't have access to

That was a bug that we fixed a few days ago. See ncc [0.18.1]( https://github.com/zeit/ncc/releases/tag/0.18.1).

Also, we just found another bug in `now dev` regarding static builder so please update to [15.0.8](https://github.com/zeit/now-cli/releases/tag/15.0.8).

**Comment by ekkis** [comment]
ahh.... my line numbers match the source now.  sweet!  I did upgrade to .8
