### ISSUE TITLE
Not all NPM scripts are executed during deployment

### ISSUE THREAD

**Issue by leo** [vercel/vercel#22]
According to [the NPM docs](https://docs.npmjs.com/misc/scripts) `prepublish` script should be executed _on local npm install without any arguments_. It seems that on Now it is not the case.

I depend on this to compile my sources (e.g. `coffee`, `elm` -> `js`).

Consider this [sample package to test scripts execution](https://github.com/lzrski/npm-scripts). This is the output on my local machine:

```
$ npm install

> npm-scripts@1.0.0 preinstall /Users/tadeuszlazurski/Projects/npm-scripts
> echo 'NPM SCRIPT: preinstall'

NPM SCRIPT: preinstall
|
> npm-scripts@1.0.0 install /Users/tadeuszlazurski/Projects/npm-scripts
> echo 'NPM SCRIPT: install'

NPM SCRIPT: install

> npm-scripts@1.0.0 postinstall /Users/tadeuszlazurski/Projects/npm-scripts
> echo 'NPM SCRIPT: postinstall'

NPM SCRIPT: postinstall

> npm-scripts@1.0.0 prepublish /Users/tadeuszlazurski/Projects/npm-scripts
> echo 'NPM SCRIPT: prepublish'

NPM SCRIPT: prepublish
coffee-script@1.10.0 node_modules/coffee-script

lodash@3.10.1 node_modules/lodash
```

and this is output from `now`:

```
 $ now
> Deploying ~/Projects/npm-scripts
> Using Node.js 6.2.1 (default)
> Ready! https://npm-scripts-izbtgitqee.now.sh (copied to clipboard) [3s]
> Upload [====================] 100% 0.0s
> Sync complete (25.9kB) [3s]
> Initializing…
> Building
> ▲ npm install
> Installing package lodash@^3.10.1
> Installing package coffee-script@^1.9.3
> ▲ npm start
> NPM SCRIPT: prestart
> NPM SCRIPT: start
> NPM SCRIPT: poststart
> start exited with status 0
```

As you can see none of the following scripts:
- `preinstall`
- `install`
- `postinstall`
- `prepublish` 

was executed in Now.

@lzrski

**Comment by addyosmani** [comment]
I unfortunately ran into this problem today. None of the `preinstall` and `postinstall` scripts I had in my package were being successfully run using Now during deployment.

**Comment by NekR** [comment]
Same here. For me `postinstall` generated required files and my app cannot build/start without them so it constantly fails.

**Comment by viczam** [comment]
This is a show stopper for me. I use lerna and I `learn bootstrap` as a postinstall script.

**Comment by tad-lispy** [comment]
The workaround is to deploy a Docker image that contains your Node app.

**Comment by leo** [comment]
Should work just fine now!

**Comment by gmaliandi** [comment]
Hi @leo  - I just deployed a project that has a `postinstall` script and it didn't run. Is this already fixed? When will this start running the `postinstall` scripts? (I can send you the link to the deploy by Slack if you want)

**Comment by gmaliandi** [comment]
(nevermind, it's working now!)
