### ISSUE TITLE
Now/node builds are 404

### ISSUE THREAD

**Issue by agstover** [vercel/vercel#2205]
I'm using 'now dev' w/15.0.7-canary.2. I have a monorepo that consists of www (next app) and api (node functions).

The last version of now@canary correctly built and served the api routes, but this new version is causing them to result in 404. 

Something strange I noticed is that the server is trying to serve the api endpoints out of next build 
`> GET /_next/static/5YL9qeNdJTVpTZjtVfGXa/pages/api/auth/signin.js.js`

It's also appending a .js to the route. In the front end app I have a Link that links to api endpoint as such, so not sure why it's looking for signin.js.js 

```    
<Link href='/api/auth/signin.js' >
      <a>
        <button>Sign In</button> 
      </a>
  </Link>
```

My now.json looks like this:

```
{
   version:2,
    "build": {
        "env": {
            "TEST": "This is a test value from build env."
        }
    },
    "routes": [
        { "src":"/api/auth/(.*)", "dest":"/api/auth/$1"},
        { "src": "/(.*)", "dest": "/www/$1" }
    ],
    "builds": [
        { "src": "api/auth/*.js", "use": "@now/node" },
        { "src": "www/next.config.js", "use": "@now/next" }
    ]
}
```

**Comment by laugharn** [comment]
@agstover I was encountering a similar issue with the 15.0.7 canary releases and resolved it by moving `{ "src": "/(.*)", "dest": "/www/$1" }` to be the first object in the routes array, followed by the API routes, and that somewhat counterintuitively worked.

However, if you have other Next-specific routes, they'll still need to be before the catch-all.

**Comment by agstover** [comment]
Yes, that is really counter-intuitive. I tried it and it worked, though. Very strange. Thank your for your help!
