### ISSUE TITLE
How to prevent `--target production` to alias staging url

### ISSUE THREAD

**Issue by kvnwolf** [vercel/vercel#2222]
I am having some troubles trying to understand how the aliasing works between `staging` and `production` environments.

When I run `now --target staging`, I get the following output:

```sh
λ now --target staging
> Deploying ~/dev/tmp/next-now-ci under kevinwolf
> Using project next-now-ci
> https://next-now-ci-a5zl1ydij.now.sh [v2] [2s]
> Ready! Aliased to https://next-now-ci.kevinwolf.now.sh [in clipboard] [2s]
```

But, when I run `now --target production`, it also aliases the staging url:

```sh
λ now --target production      
> Deploying ~/dev/tmp/next-now-ci under kevinwolf
> Using project next-now-ci
> https://next-now-ci-o4nn3ibi0.now.sh [v2] [2s]
> Ready! Aliases assigned [2s]
- https://next-now-ci.now.sh
- https://next-now-ci.kevinwolf.now.sh
```

What I want is to alias `staging` to `https://next-now-ci.kevinwolf.now.sh` and `production` to **only** `https://next-now-ci.now.sh`.

This is because I have a CircleCI configuration in which all commits to master gets deployed with `now --target staging` and when I want to make a production deploy, I have a manual approval step to run `now --target production`.

Having the following commits on `master`:

```
commit-8 => staging
commit-7 => staging
commit-6 => staging
commit-5 => staging
commit-4 => staging => production
commit-3 => staging
commit-2 => staging
commit-1 => staging
```

That means that commits 1 to 4 have been merged into master, therefore, deployed to staging, but on commit 4, I've decided I want to deploy to production, which means, production will now have commits 1 to 4.

Now, imagine I want to deploy `commit-6` (given staging currently shows `commit-8`) to production. Because of the above issue of `now --target production` aliasing staging, staging now will point to `commit-6`, and I won't be able to see `commit-8` on my staging environment anymore (until manually deploying).

I don't know if I've missed something from [the documentation on aliasing deployments](https://zeit.co/docs/v2/domains-and-aliases/aliasing-a-deployment).

If it works, this is my `now.json` file:

```json
{
  "version": 2,
  "name": "next-now-ci",
  "alias": "next-now-ci.now.sh",
  "github": {
    "enabled": true,
    "autoAlias": false
  },
  "builds": [{ "src": "package.json", "use": "@now/next" }],
  "routes": [{ "src": "/show/(.*)", "dest": "/show?id=$1" }]
}
```

And I also have a [repo](https://github.com/kevinwolfcr/next-now-ci) containing all the project code.

**Comment by rauchg** [comment]
We decided that having staging be *behind* production would be an unexpected result, so, going to production also implies staging.

**Comment by kvnwolf** [comment]
@rauchg got it. But take a look at the commit map I put there. Sometimes I want to promote to production something that has been on staging for a while.

Imagine the scenario where all PRs are merged to master so I just pass the staging URL to a client where he will see all the QA approved changes, but I want to release to production once a week.

**Comment by kvnwolf** [comment]
@rauchg or maybe the scenario on which I am integrating PRs into master for a feature hasn't been finished:

```
profile-page-wip-2 => staging
profile-page-wip-1 => staging
forgot-password-flow => staging
login-flow => staging
signup-flow => production
```

Imagine right now, I have `profile-page-wip-2` on staging, since it has been approved by QA, and `signup-flow` on production.

If I want to promote `forgot-password-flow` to production, then because of the current issue, my staging environment (currently `profile-page-wip-2`), will be overwritten by `forgot-password-flow`. Which is also an unexpected behavior.

**Comment by patlux** [comment]
@kevinwolfcr How did you solve this?

**Comment by patlux** [comment]
Ok, I fixed it. I just don't use the `--target` option. Small example:

```bash
NOW_LOG=$(now --token=$NOW_TOKEN -e APP_ENV=staging)
NOW_URL=$(echo ${NOW_LOG} | sed s/'http:\/\/'/''/g | sed s/'https:\/\/'//g)
now --token=${NOW_TOKEN} alias set ${NOW_URL} <staging-url>
```

and for production:

```bash
NOW_LOG=$(now --token=$NOW_TOKEN -e APP_ENV=production)
NOW_URL=$(echo ${NOW_LOG} | sed s/'http:\/\/'/''/g | sed s/'https:\/\/'//g)
now --token=${NOW_TOKEN} alias set ${NOW_URL} <production-url>
```

😺

**Comment by musemind** [comment]
@rauchg what about parallel feature development? we need our stage deployments being independent of production deployment

**Comment by cedric25** [comment]
Quite an old issue but I face something similar.

I'm fine having the same code for both staging and prod after a prod release, but the problem seems to be the environment variables. I don't want the staging environment to use prod env vars... How to prevent that?

I ended up re-deploying my staging environment after each prod release. (Not so great I know, and for a short period of time the staging environment will be using prod env vars for a minute or two.)

Prod URL: mysite.com
Staging URL: dev-mysite.com

```
# CI for each 'main' branch push

# Deploy prod
vercel pull --yes --environment=production
vercel build --prod
vercel deploy --prod --prebuilt

# At this stage, dev-mysite.com now points to the production deployment...
# -> Re-build it with dev env vars:
vercel pull --yes --environment=development
vercel build
vercel deploy --prebuilt >deployment-url.txt
deploymentUrl=`cat deployment-url.txt`; vercel alias $deploymentUrl dev-mysite.com
```
