### ISSUE TITLE
now dev hides console.log calls

### ISSUE THREAD

**Issue by cryptiklemur** [vercel/vercel#2232]
Title describes the issue.

Need a way to view the logs from now dev

**Comment by cryptiklemur** [comment]
Seems to be a problem specific to either next.js, or my particular setup, but things in getInitialProps() arent logging

**Comment by tiernacity** [comment]
@aequasi I was seeing the same behaviour, but since a now cli update (I'm on 15.0.11 today) I now see logs from `getInitialProps()` when using `now dev`.

**Comment by TooTallNate** [comment]
This should be fixed by https://github.com/zeit/now-cli/pull/2269. Please let me know if the issue still occurs after updated to the latest version of now-cli.

**Comment by tiernacity** [comment]
It's fixed for me @TooTallNate. Thanks!

**Comment by eyaleizenberg** [comment]
Still not seeing logs in now 15.6.1 when running `now dev`. What am I missing?
@TooTallNate

**Comment by realfunkyusername** [comment]
Still not seeing logs in now 17.0.4 when running now dev. What am I missing?

**Comment by TAnas0** [comment]
Same goes for me. I can't see my logs neither in development nor in production. Makes me strongly doubt Zeit knowing very well that this issue, one of the most basic of features, has been raised multiple times in multiple channels (Github, Spectrum...)
