### ISSUE TITLE
[now dev] Build env not passed to client

### ISSUE THREAD

**Issue by agstover** [vercel/vercel#2235]
Using most up to date canary branch: 15.0.8-canary.1.

A couple of versions ago all of this was working, but now the build env variables that I'm passing to client side env are being set with `undefined`.

I have this next.config.js

```
const { PHASE_PRODUCTION_SERVER } =
  process.env.NODE_ENV === 'development'
    ? {}
    : !process.env.NOW_REGION
      ? require('next/constants')
      : require('next-server/constants');

const config = {
    target: 'serverless',
    env: {
        HASURA_URL: process.env.HASURA_URL,
        BASE_URL: process.env.BASE_URL
    }
}
module.exports = (phase, { defaultConfig }) => {
  if (phase === PHASE_PRODUCTION_SERVER) {
    // Config used to run in production.
    console.log("HASURA URL!!!", process.env.HASURA_URL)
    return config
  }
  const withCSS = require('@zeit/next-css')
  return withCSS(config);
}
```

And these are env sections from now.json

```
    "env": {
        "HASURA_URL": "http://localhost:8080/v1alpha1/graphql",
        "BASE_URL": "http://localhost:3000"
    },
    "build": {
        "env": {
            "BASE_URL": "http://localhost:3000",
            "HASURA_URL": "http://localhost:8080/v1alpha1/graphql"
        }
    },
```

Strangely this was all working perfectly, and then I added the BASE_URL value to build.env and did `now dev` in the terminal and received this error: `Cannot find module '/home/agstover/.cache/co.zeit.now/dev/builders/node_modules/@now/next'`

I ran it again and it worked, but these issues started appearing. Can't get env variables on client and a constant stream of "http://localhost:3000/_next/on-demand-entries-ping?page=/ 404 (Not Found)" in the browser console.

The repo can be found here: https://github.com/agstover/awesomex

**Comment by ka2n** [comment]
I also encountered this problem and found current `@now/next` builder didn't pass environment variables from dev CLI to next dev-server process. https://github.com/zeit/now-builders/blob/7951be156a0b4beff7fc8efd1a9b7f04cd424f13/packages/now-next/src/index.ts#L127

Update:
It seems fixed in HEAD, awesome. https://github.com/zeit/now-builders/pull/448

**Comment by benbowler** [comment]
Afternoon, I'm deploying an application and our secret isn't visible. Is this releated?

logging process.env returns {}
