### ISSUE TITLE
Smarter errors for 2.0 deployments now.json

### ISSUE THREAD

**Issue by mcsdevv** [vercel/vercel#2236]
Currently, deployments get failed with a generic error, for example:

'The property `aliases` is not allowed in `now.json` when using Now 2.0 – please remove it.'

It would be better if the error messages accounted for close matches to correct config settings and gave the user an actionable message such as:

'The property `aliases` is not allowed in [`now.json`](https://zeit.co/docs/v2/deployments/configuration) - did you mean to use [`alias`](https://zeit.co/docs/v2/deployments/configuration#alias) instead?'

This suggested format also adds a link to the `now.json` configuration documentation as well as the recommend property, removing barriers for users.

**Comment by leo** [comment]
Fixed!
