### ISSUE TITLE
The casing for some header names do not match in 'now' vs. 'now dev'

### ISSUE THREAD

**Issue by atarumix** [vercel/vercel#2238]
now version:15.0.8
build: @now/bash

I found some small difference in request header in 'now' and 'now dev'.

```
$ cat now.json
{
  "version": 2,
  "builds": [{ "src": "*.sh", "use": "@now/bash" }]
}
$ cat index.sh
handler() {
  jq '.headers|keys|sort' $1
}

```

Result when calling what was actually deployed.
```
$ curl -Ss https://***.***.now.sh
[
  "accept",
  "host",
  "user-agent",
  "x-forwarded-for",
  "x-forwarded-host",
  "x-forwarded-proto",
  "x-now-deployment-url",
  "x-now-id",
  "x-now-trace",
  "x-real-ip",
  "x-zeit-co-forwarded-for"
]

```

The result of calling locally  with 'now dev'.
```
$ curl -Ss http://localhost:3000/
[
  "Connection",
  "X-Forwarded-For",
  "X-Forwarded-Host",
  "X-Forwarded-Proto",
  "X-Real-IP",
  "accept",
  "host",
  "user-agent",
  "x-now-deployment-url",
  "x-now-id",
  "x-now-log-id",
  "x-now-trace",
  "x-zeit-co-forwarded-for"
]
```
Some key names are mixed-case only with 'now dev'. 
This difference is not in `@now/node`.

**Comment by TooTallNate** [comment]
_Technically,_ HTTP header names are case-insensitive according to the RFC (see https://stackoverflow.com/a/5259004/376773).

However I agree that `now dev` should be emulating the production router as closely as possible, so I'll send a patch to lowercase the headers before invoking the lambda function 🔜 

Thanks for the report.
