### ISSUE TITLE
godaddy domain not responsive

### ISSUE THREAD

**Issue by karinchechik** [vercel/vercel#2239]
Hi,

When I use the default domain: https://nextjs.karinchechik.now.sh/ I have a responsive design. **Please try the mobile view.**
But when I use my GoDaddy domain - http://karinchechik.me/ The mobile view is the same as the desktop but smaller (not what I want!).

I didn't do the setup from the Now desktop yet. Do I have to? Is this related? 

If I do the 'Verifying with Nameservers' option, would it help?
If not, what else can I do?

**Comment by paulogdm** [comment]
Hello!
It seems the domain "karinchechik.me" is not related to ZEIT in any way: https://www.whatsmydns.net/#A/karinchechik.me
The link shows that it is pointing to a server external to the now platform.

**Comment by paulogdm** [comment]
Please, read our docs regarding on how to use your domain with Now:
https://zeit.co/docs/v2/domains-and-aliases/adding-a-domain#option-1:-using-zeit-dns-nameservers
