### ISSUE TITLE
Newline required before user abort error

### ISSUE THREAD

**Issue by leo** [vercel/vercel#224]
If you're not logged in, the package will ask for your email. If you hit `ctrl` + `c`, it will abort but the error message will be printed in the same line. Should be a new line!

> Enter your email: > Error! Authentication error – User abort

**Comment by matheuss** [comment]
@leo It's fine here 🤔 
<img width="465" alt="screen shot 2017-01-15 at 2 14 19 pm" src="https://cloud.githubusercontent.com/assets/4721750/21964100/f8ef211a-db2c-11e6-94d1-25f10681fd2c.png">

**Comment by leo** [comment]
@matheuss Don't you see? There's no newline between the error and "Enter your email". This is how it should look:

> Enter your email
> Error! Bla bla

**Comment by vuchl** [comment]
Wouldn't that simply be a new line [here](https://github.com/zeit/now-cli/blob/master/lib/error.js#L26)?

**Comment by matheuss** [comment]
Ohhh, I misread the issue 😅 Looks like something we should address on [zeit/email-prompt](https://github.com/zeit/email-prompt)? 🤔

**Comment by leo** [comment]
@matheuss Probably, yep! Because adding the newline to the error method in the CLI would generate an empty line between the previous output and the error in some cases.
