### ISSUE TITLE
Can't deploy paths contain `\n` or  `\t`

### ISSUE THREAD

**Issue by nkzawa** [vercel/vercel#2247]
e.g, `one\ntwo/t\ta\tb.txt` is deployed to `/one/ntwo/t/ta/tb.txt`.

I guess there are other chars which are not handled properly.

**Comment by mcsdevv** [comment]
@nkzawa is this issue still present?

**Comment by nkzawa** [comment]
Seems it partially works now. static works, node runtime and front source page don't as far as I tested a bit.
