### ISSUE TITLE
now.sh creates extra pipeline for gitlab

### ISSUE THREAD

**Issue by sobolevn** [vercel/vercel#2248]
For some reason `now` has started to create extra pipeline (not just an extra step).
This break code review process. Since the original build/test pipeline is replaced with `now` deploy.

So, you do not know whether your tests pass or not. Here's how it looks like:

<img width="939" alt="Снимок экрана 2019-04-27 в 15 48 40" src="https://user-images.githubusercontent.com/4660275/56849939-15eab600-6904-11e9-9ef1-7c3f6d818520.png">

It looks that I actually have just a single `now` job. But, it is not true at all.
That's how it looks internally (for the second commit):

<img width="928" alt="Снимок экрана 2019-04-27 в 15 49 39" src="https://user-images.githubusercontent.com/4660275/56849940-15eab600-6904-11e9-99f8-f223c58ace74.png">

My `.gitlab-ci.yml`: https://github.com/wemake-services/wemake-vue-template/blob/master/template/.gitlab-ci.yml

**Comment by sobolevn** [comment]
I guess it happens because of `only: merge_requests` in my `.gitlab-ci.yml` jobs: 

<img width="920" alt="Снимок экрана 2019-04-27 в 15 53 10" src="https://user-images.githubusercontent.com/4660275/56849981-a5906480-6904-11e9-8865-950186b9267f.png">
<img width="922" alt="Снимок экрана 2019-04-27 в 15 53 06" src="https://user-images.githubusercontent.com/4660275/56849982-a628fb00-6904-11e9-8550-91648db734e2.png">

Link: https://github.com/wemake-services/wemake-vue-template/blob/master/template/.gitlab-ci.yml#L38

**Comment by sobolevn** [comment]
I used to have it working:
<img width="1212" alt="Снимок экрана 2019-04-27 в 16 28 57" src="https://user-images.githubusercontent.com/4660275/56850310-a2e43e00-6909-11e9-9d30-b6a450dc843b.png">

**Comment by paulogdm** [comment]
Hello,

If you are still experiencing this issue, reach out to us on support@zeit.co so we can attack this bug as soon as possible.

We do apologize for the delay in getting back to you.
