### ISSUE TITLE
now's "delta" icon doesn't render correctly on Windows

### ISSUE THREAD

**Issue by awayken** [vercel/vercel#225]
Seen in Microsoft Windows [Version 10.0.14393]. Using either Command Prompt or PowerShell, the unicode "delta" icon that `now` uses renders instead as [tofu](https://en.wikipedia.org/wiki/Noto_fonts#Etymology).

Command Prompt:
![image](https://cloud.githubusercontent.com/assets/156215/21993545/f504e60c-dbe0-11e6-9523-89a105ef95a9.png)

PowerShell:
![image](https://cloud.githubusercontent.com/assets/156215/21993553/feb3d1c2-dbe0-11e6-9e67-ebec81a0666b.png)

**Comment by matheuss** [comment]
@awayken thank you for reporting! I'm aware of that and will work on it this week :v:

**Comment by leo** [comment]
@matheuss fixed?

**Comment by matheuss** [comment]
@leo how? 😮

**Comment by leo** [comment]
@matheuss wanted to write a question mark, sry 😄

**Comment by matheuss** [comment]
Oh 😅 Not yet, will fix it right now 🙌
