### ISSUE TITLE
cannot use next with custom node-server

### ISSUE THREAD

**Issue by andycmaj** [vercel/vercel#2252]
I am unable to run a next app with a custom server.

example:

taken from from [custom-server-express](https://github.com/zeit/next.js/tree/master/examples/custom-server-express) => and then added now config: https://github.com/andycmaj/next-now-bug

When the now builder creates the lambda packages, it seems to exclude the `.next` directory that contains the compiled next pages.

you can see that the `.next` dir is in fact in the build workspace:

<img width="413" alt="ScreenCapture at Sat Apr 27 12:54:40 PDT 2019" src="https://user-images.githubusercontent.com/97470/56854458-a8cb2680-68eb-11e9-8087-06132bea5fdf.png">

... but is NOT in the lambda package:

<img width="410" alt="ScreenCapture at Sat Apr 27 12:55:13 PDT 2019" src="https://user-images.githubusercontent.com/97470/56854463-b680ac00-68eb-11e9-9592-5d9ecbda6aa7.png">

you can clearly see that when you use `now dev`, you're unable to hit the home page:

`> GET /`

```
404: The page could not be found
Code: FILE_NOT_FOUND
```

**Comment by paulogdm** [comment]
Hello!
Now 2.0 doesn't support a custom server... Please, take a look at https://zeit.co/guides/custom-next-js-server-to-routes/
Essentially, to go full serverless, you need to bring your code logic to be page-specific and ditch the custom server. Then you define `"routes"` in your now.json: https://zeit.co/docs/v2/deployments/routes/
