### ISSUE TITLE
Unable to start on Windows

### ISSUE THREAD

**Issue by arunesh90** [vercel/vercel#2255]
After installing the latest version of now-cli I've been unable to start it and instead get a syntax error. Attached screenshot shows more information regarding the errors

Node version: 11.14.0
Now CLI version: 15.0.8

Screenshot: 
![image](https://user-images.githubusercontent.com/5787588/56865084-354c1680-69ca-11e9-9d4b-965099061f6a.png)

**Comment by arunesh90** [comment]
Able to replicate this issue on my laptop also
![image](https://user-images.githubusercontent.com/5787588/56868316-0d23de00-69f1-11e9-9e9c-8e36ced387a8.png)

**Comment by juancamiloqhz** [comment]
Same thing here. It seems that now windows cli is down

**Comment by albertosantini** [comment]
Please, update `now` to `15.2.0` version (or higher).
See #2322.

**Comment by arunesh90** [comment]
Updated with Now Desktop to 15.2.0, but still havving issues. Trying to run the `now` command does nothing and it immediately exists
![image](https://user-images.githubusercontent.com/5787588/57302008-86e75600-70da-11e9-974f-b8a29cbdfc34.png)

**Comment by arunesh90** [comment]
Updated Now CLI manually and it works now. Thanks a lot for the work on Windows compatibility 😄
