### ISSUE TITLE
Error: Can't find npm module when deploying with Dockerfile

### ISSUE THREAD

**Issue by jkrup** [vercel/vercel#226]
I have a project that successfully runs with docker when doing:

```
docker build -t myimage .
docker run -p 80:3000 -e PORT=3000 -e ROOT_URL=http://example.com myimage
```

But when deploying with `now -e PORT=3000 -e ROOT_URL=http://example.com` I get: 

```
/programs/server/boot.js:348
}).run();
   ^

Error: Can't find npm module 'meteor-deque'. Did you forget to call 'Npm.depends' in package.js within the 'meteor' package?
    at Object.require (/programs/server/boot.js:200:17)
    at packages/meteor.js:677:32
    at packages/meteor.js:846:4
    at packages/meteor.js:1380:3
    at /programs/server/boot.js:295:34
    at Array.forEach (native)
    at Function._.each._.forEach (/programs/server/node_modules/underscore/underscore.js:79:11)
    at /programs/server/boot.js:128:5
    at /programs/server/boot.js:344:5
    at Function.run (/programs/server/profile.js:480:12)
```

I posted my entire repo here: https://github.com/mazlix/now-docker-deploy-issue in case anyone would like to reproduce (by doing what I did above [running `docker build/run` works and `now` fails]

Here's just the Dockerfile:
```
 
      FROM node:boron
      ENV NPM_CONFIG_LOGLEVEL warn

      RUN mkdir -p programs/server/
      COPY programs/server/package.json programs/server/package.json

      WORKDIR programs/server/
      RUN npm install

      COPY . ../../
      WORKDIR ../../

      EXPOSE 3000

      CMD ["node", "main.js"]
```

Is there anywhere in the docs where I can see exactly what the docker build/run commands are?

**Comment by jamo** [comment]
After some debugging and discussions in zeit.chat - it seems that this: https://github.com/mazlix/now-docker-deploy-issue/tree/master/programs/server/npm/node_modules is skipped by `now` causing the deployment to fail
