### ISSUE TITLE
Slack integration?

### ISSUE THREAD

**Issue by sedubois** [vercel/vercel#228]
I'd like to have notifications in my Slack group when deploying with `now`, so that my team members are kept informed of changes. Is that possible and how, or if not, could it be implemented?

**Comment by jamo** [comment]
AFAIK it's not supported yet - but would definitely be a nice addition for the team support (once it arrives).

**Comment by timneutkens** [comment]
@sedubois Neat idea, I'd change the name to `Webhook support`, So you can integrate all the things 😄

**Comment by timneutkens** [comment]
@leo great idea ❤️
