### ISSUE TITLE
`now dev` support for now-secrets.json

### ISSUE THREAD

**Issue by davidkaneda** [vercel/vercel#2286]
Seems like this would fit well vs. relying on a .env — Was it omitted on purpose?

**Comment by paulogdm** [comment]
Greetings!
With `now-dev` the helper `now-env` is actually deprecated. We just archived the repository to avoid any confusion.
Now we recommend `.env` for your development environment and secrets in `now.json` for production or staging.
Let me know if you have any questions or feedback for us.

**Comment by davidkaneda** [comment]
Gotcha, thanks!
