### ISSUE TITLE
Better startup "beta" warning for now-dev

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2288]
Right now the start up beta message of `now dev` is very confusing.

> Now CLI 15.0.10 dev (beta) — https://zeit.co/support

We should word it better to ensure the users know it is `now dev` that is in beta, not the `now-cli`.

Something like:

You are using a beta version of now dev on Now CLI 15.0.10 — Support is available at https://zeit.co/feedback/dev.

**Comment by wiiiimm** [comment]
Use https://zeit.co/feedback/dev to collect feedback.

**Comment by leo** [comment]
@williamli We intentionally try to keep these kinds of messages as short as possible, as the space within the terminal is extremely limited and we need to be careful with using it up.

The message only appears when you invoke the `dev` command, so it doesn't hurt that the person reading it thinks the entire program is in beta when they run `now dev`.

Furthermore, the link was already replaced in https://github.com/zeit/now-cli/pull/2278.
