### ISSUE TITLE
Route parameters not passed to getInitialProps({ query }) (NextJS)

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2289]
```
   { 
      "src": "/(?<locale>[^/]*)/registration/", 
      "dest": "/registration/?locale=$locale"
    },
```

parameters are not into NextJS from route to `query`.

**Comment by ducdev** [comment]
I'm using MacOS Mojave 10.14.4, facing same issue when trying `now dev`. @paulogdm confirmed it's known issue for Mac.

**Comment by wiiiimm** [comment]
@ducdev. yep. and this is the official filing of this issue ;)

**Comment by fredrik-sogaard** [comment]
For what it's worth: this worked with `15.0.7-canary.2` on my Mac.

**Comment by maccyber** [comment]
Same issue on Linux with now@15.0.11-canary.1 and below.

Reproduce repository: https://github.com/maccyber/next-custom-route-issue

**Comment by radTuti** [comment]
just want to add that additional request headers do not get passed as well i.e. something like this

```json
  "routes": [
    {
      "src": "/card/(?<key>[^/]+)$",
      "dest": "/card?key=$key",
      "headers": {
        "x-request-path": "/card/$key"
      }
    }
  ]
```

**Comment by mxstbr** [comment]
Same thing is happening here!

**Comment by ducdev** [comment]
> For what it's worth: this worked with `15.0.7-canary.2` on my Mac.

It does not work for me, it causes every single link 404.

**Comment by notrab** [comment]
@leo the above is still an issue for me when using the canary branch. (Tested with https://github.com/maccyber/next-custom-route-issue)

Is anyone else able to get this working with `canary`?

**Comment by ducdev** [comment]
> @leo the above is still an issue for me when using the canary branch. (Tested with https://github.com/maccyber/next-custom-route-issue)
> 
> Is anyone else able to get this working with `canary`?

There is not any new `canary` release after PR issue resolved, should we wait more?

**Comment by ducdev** [comment]
FYI, the fix for this issue is included in new `canary` release: https://github.com/zeit/now-cli/releases/tag/15.1.1-canary.4

I tried and it works.

**Comment by notrab** [comment]
Confirmed also fixed. The previous canary was still being pulled for me. Works on 4 though 👌
