### ISSUE TITLE
[now dev] should warn if no source files matched by `builds`

### ISSUE THREAD

**Issue by antonmoiseev** [vercel/vercel#2291]
I've refactored the project structure a bit and moved handlers into a sub-directory, updated `routes` in now.json, but forgot to update `builds`. `now dev` was returning HTTP 404 whatever URL I specify. An attempt to deploy the project helped me to figure out the problem:

![image](https://user-images.githubusercontent.com/182853/57020502-85c9ab00-6c3a-11e9-8650-6ad9ac6593ee.png)

It would be nice if `now dev` also provided such assistance.

**Comment by TooTallNate** [comment]
This was fixed by https://github.com/zeit/now-cli/pull/2594.
