### ISSUE TITLE
now dev is taking around 10 minutes to start

### ISSUE THREAD

**Issue by kirkness** [vercel/vercel#2292]
Following on from the discussion on Spectrum [here](https://spectrum.chat/zeit/announcements/introducing-now-dev-serverless-on-localhost~051e2bcb-7353-48bf-89a4-cf8f663a124a).

To sum up, I had a go with `now dev` on an existing project, it has 7 builds (2 next apps and 5 now-nodes) all in typescript, it runs nicely. However, it takes around 10 minutes to startup (tried 3 times) and also downloads around 8.7gb worth of files to `/var/folders/np/***/T/co.zeit.now/`, making it pretty impractical to use. Does this sound like a problem with the project specifically or has this been seen by others with apps with a few different builders?

```json
{
  "builds": [
    { "src": "package.json", "use": "@now/node@canary" },
    { "src": "web/next.config.js", "use": "@now/next" },
    { "src": "admin/next.config.js", "use": "@now/next" },
    { "src": "api/lambda/verify-email.ts", "use": "@now/node@canary" },
    { "src": "api/lambda/schedule-email.ts", "use": "@now/node@canary" },
    { "src": "api/lambda/booking-reminder.ts", "use": "@now/node@canary" },
    {
      "src": "api/graphql/index.ts",
      "use": "@now/node@canary",
      "config": {
        "maxLambdaSize": "10mb"
      }
    }
  ],
  "routes": [
    { "src": "/verify-email", "dest": "api/lambda/verify-email.ts" },
    { "src": "/schedule-email", "dest": "api/lambda/schedule-email.ts" },
    { "src": "/booking-reminder", "dest": "api/lambda/booking-reminder.ts" },
    { "src": "/graphql", "dest": "/api/graphql/index.ts" },
    { "src": "^/admin(.*)", "dest": "/admin$1" },
    { "src": "^(.*)$", "dest": "/web$1" }
  ]
}
```

**Comment by leo** [comment]
@kirkness This is very unfortunate.

In fact, we're currently already working on making `now dev` not use these temporary paths anymore and instead run everything in the place where it was located originally (your source files). This will decrease the disk usage by close to 100%.

With regards to the long bootup time, we're also working on running all the builders in parallel instead of one after another, which will also solve that problem.

You can expect both changes to appear on the release channel in the next few days.

**Comment by kirkness** [comment]
Ah awesome, thanks for the speedy response @leo, great news!

**Comment by TooTallNate** [comment]
@kirkness Could you try out `@now/node@dev` as your builder and let me know if that provides a better experience for you?

**Comment by kirkness** [comment]
Slightly better experience, but seems like that's due to the fact that the `now/nodes` only build when they are needed. 

I think this would probably cause quite a frustrating experience if the build time is 1 minute per function, which is the case for each of our Lambdas, even one that is 20 lines long and imports knex and a few typescript types.
