### ISSUE TITLE
[now dev] Can't route a path that matches a file to a 404

### ISSUE THREAD

**Issue by adamwathan** [vercel/vercel#2294]
Here's my now.json:

```json
{
  "name": "now-dev-bugs",
  "version": 2,
  "builds": [
    { "src": "api/*.js", "use": "@now/node" }
  ],
  "routes": [
    {
      "src": "/api/secret.js",
      "status": 404
    },
    {
      "src": "/visible",
      "dest": "/api/secret.js"
    }
  ]
}
```

If you visit `localhost:3000/api/secret.js`, the function is invoked and it's output is displayed even though it is configured to 404 to make that path not work.

This works as expected in production but it's broken in `now dev`.

Reproduction: https://github.com/adamwathan/now-dev-bugs

**Comment by TooTallNate** [comment]
Thank you for the repo instructions 🙏
We'll be looking into this soon.

**Comment by nguyenkhois** [comment]
I have the similar problem with the `now dev` command on Windows 10 but it works well on Ubuntu.

On Windows 10:
```
now init nextjs
cd nextjs
now dev
```

It's broken
```
now dev
> Now CLI 15.0.11 dev (beta) — https://zeit.co/support
> Setting up 1 Builder
> Error! HTTP request failed: 404
```

**Comment by dihmeetree** [comment]
@nguyenkhois install the @15.0.11-canary.2 version of ZEIT Now.. to test until the fix gets merged :) It is fixed in the canary version!

**Comment by TooTallNate** [comment]
@adamwathan I've added a PR that addresses your issue in #2307. Should be merged shortly!
