### ISSUE TITLE
[now dev] Need to codesign the `now` binary on macOS to avoid firewall prompt

### ISSUE THREAD

**Issue by TooTallNate** [vercel/vercel#2299]
[Some users](https://spectrum.chat/zeit/now/now-dev-allow-incoming-connections-osx~05466aa5-b5a0-42cf-ac20-830168803c52) have reported getting a prompt from the macOS Firewall asking to approve `now` when running `now dev`.

I did a bit of research and it appears that code signing should help with this:

 * https://github.com/tj/n/issues/394
 * https://github.com/nodejs/node/issues/11936

**Comment by unitof** [comment]
I've been getting this again (now as `vc dev`, of course); seems to repeat the prompt each time `node` is upgraded though, so maybe this is upstream?

**Comment by TooTallNate** [comment]
Vercel CLI is just a regular npm package at this point (when this issue was created, it was producing a standalone binary via [`pkg`](https://github.com/vercel/pkg)). So there's nothing to do here anymore, we don't have control over the `node` binary.
