### ISSUE TITLE
.env support for npm deploys

### ISSUE THREAD

**Issue by timneutkens** [vercel/vercel#230]
Got this idea from a lot of slack questions about this. @jamo gave the following example:
`sed 's/^/-e /' .env | xargs now --npm`

I think we can add it natively under a flag. @jamo agreed.

You can assign this to me. I'll add it 👍

**Comment by TooTallNate** [comment]
Would the [`dotenv`](https://www.npmjs.com/package/dotenv) npm module suffice?

**Comment by jamo** [comment]
Especially for OSS plan the `.env` file is a terrible idea because all files are exposed

**Comment by timneutkens** [comment]
Except when the file viewer ignores them 🤔 But I Guess it's best to make it explicit to the cli. So you don't get unexpected hidden files 🙂

**Comment by jamo** [comment]
The ignoring stuff in the viewer is more errorprone than just moving it to env - that is already treated with proper respect on containing secrets.
