### ISSUE TITLE
New `now update` command needed

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2300]
In order to give people a straightforward way of upgrading Now CLI (no matter what method they used to install it), we want to introduce a new `now update` command.

In favour of this new command, we'd deprecate the behaviour under the `now upgrade` command, which can currently be used for upgrading the plan. Otherwise there might be confusion occurring around which one of these two commands does what. Also, nobody upgrades their plan from the CLI.

By default, running `now update` would simply replace the binary. That's it.

## Package Managers

In the event, however, that a package manager like `npm`, `yarn` or `brew` is used, we want to run the command that package manager provides for updating it.

In those cases, we want to show this prompt as well:

> Now CLI (/usr/local/bin/now) was installed via npm
Run npm i -g now? [Yn]

As you can see, we would be running the `npm i -g now` command if the user agreed.

That is all.

**Comment by TooTallNate** [comment]
Closed by #2388.
