### ISSUE TITLE
500 'INTERNAL_LAMBDA_INVOCATION_FAILED'  -- OUT OF NOTHING

### ISSUE THREAD

**Issue by lehnavid** [vercel/vercel#2303]
Hi Guys,

anybody else got this problem?
Out of nothing i got a 500 on our production site.

Yesterday everything works fine.

Can't see anything in the logs.

**Comment by paulogdm** [comment]
Hello!
We are investigating this situation at this very moment: http://zeit-status.co

**Comment by lehnavid** [comment]
Ok - wish you good luck to fix this as soon as you can.

**Comment by paulogdm** [comment]
It is fixed. Can you confirm that?

**Comment by lehnavid** [comment]
Yes i can - what caused the problem?

**Comment by paulogdm** [comment]
A post-mortem about this will be created on our status page. I can't disclose information at this time otherwise it can be simp[ly inaccurate.
Thanks again for your patience @lehnavid !

**Comment by lehnavid** [comment]
Ok i understand. Thanks for helping so fast!
