### ISSUE TITLE
@now/static-build: Command "now-dev" not found

### ISSUE THREAD

**Issue by jacobmischka** [vercel/vercel#2304]
If I specify a `"now-dev"` script in my static-builder's `package.json`, I receive the following error, no matter what the script actually does:

```json
"scripts": {
  "now-dev": "echo what"
}
```

```
...
> [debug] [2019-05-02T19:49:47.060Z] v0.5.2 (workPath = /tmp/co.zeit.now/dev/workPaths/0jsk5too)
> [debug] [2019-05-02T19:49:47.060Z] Creating build process for form/package.json
downloading user files...
installing to /tmp/co.zeit.now/dev/workPaths/0jsk5too/form
yarn run v1.15.2
error Command "now-dev" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```
$ now --version
15.0.11-canary.2
```

**Comment by jacobmischka** [comment]
Ah, this should probably go in the builders repo huh.

**Comment by styfle** [comment]
Can you try using `@now/static-build@canary` in about 30 minutes?

I believe we fixed this and we are about to publish canary.

**Comment by jacobmischka** [comment]
Thanks for writing! When I went to post this in the correct repo I noticed that you had literally just published the new canary, and have been waiting for the update to propagate, ha.

```
error Couldn't find any versions for "@now/static-build" that matches "0.5.3-canary.1"
```

I'll check back in a little bit!

**Comment by styfle** [comment]
It's available now 👍

**Comment by jacobmischka** [comment]
Yep works great now, thanks!
