### ISSUE TITLE
now --target production will hang if an alias domain is not linked

### ISSUE THREAD

**Issue by kochie** [vercel/vercel#2309]
There is a bug in the target logic which can affect deployments on GitHub and using the cli.

If one or more of the aliases for an external domain is not linked to your account the GitHub deployment will not alias correctly and will just stay `pending`. 
![Screenshot_2019-05-03 kochie me kochie io](https://user-images.githubusercontent.com/10809884/57142765-f665f880-6def-11e9-820a-4864dbd1b4a4.png)

A similar thing will happen when using the `now --target production` command where the command will just wait.

**Comment by AndyBitz** [comment]
Hey @kochie, thanks for reporting this! The aliasing should now fail with a descriptive error if it uses an external domain that we can't use or can't create a certificate for.
