### ISSUE TITLE
Revert to package.json `name` as deployment name default

### ISSUE THREAD

**Issue by lukeed** [vercel/vercel#231]
I've been deploying my OSS projects out of their respective `dist` directories. Before upgrading to the latest version, my deployment's default name would be parsed from the `dist/package.json`. It's now using the current/targeted directory name as its default.

This quickly becomes a problem when multiple projects (all with `dist`) are deployed and share the same base & identifier.

```sh
# now
dist
  ...      https://dist-ngetttuaxt.now.sh      8m ago
  ...      https://dist-wgbalakrxl.now.sh      12m ago
  ...      https://dist-kwnbojmpnv.now.sh      13d ago

# preferred
colors-app
  ...      https://icolors-ngetttuaxt.now.sh      8m ago

inferno-starter
  ...      https://inferno-starter-kwnbojmpnv.now.sh      13d ago

preact-starter
  ...      https://preact-starter-wgbalakrxl.now.sh      10d ago
```

Without being careful, you'll quickly have a stack of `dist` deployments, and won't know which are safe to get rid of without visiting each url individually.

Lastly, I realize that there **is** a `--name` flag that I can use, but this is only on initial deployment.  I cannot fix/rename a deployment after it's been made. I can only "fix" it by redeploying & including a `--name` flag, which makes your system work more than it should need to.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
