### ISSUE TITLE
[now dev] Out of space

### ISSUE THREAD

**Issue by mihaiserban** [vercel/vercel#2310]
Currently holding 29GB of data in /private/var/folders/1n/20txh40n0x9fjl005dwn_f440000gp/T/co.zeit.now/dev/workPaths/.

And doesn't seem to get cleared.

**Comment by leo** [comment]
Thank you for the report!

This unfortunately happens for [this reason](https://github.com/zeit/now-cli/issues/2292#issuecomment-488323437). However, we're already working on resolving this issue by **not copying any data** anymore. Stay tuned for a release in the next few days!

**Comment by TooTallNate** [comment]
#2326 has been merged and is available in the latest canary release. Could you try `npm i -g now@canary` and let me know if that works better for you? Thanks in advance!

**Comment by mihaiserban** [comment]
@TooTallNate sorry for the late reply, had my macbook serviced.
I've tried Now CLI 15.3.0 & also the latest canary release. I can't find /co.zeit.now/dev/workPaths, so i assume this is fixed now. 👍🏻
also rebuilding a source file is much faster.

**Comment by leo** [comment]
Awesome!
