### ISSUE TITLE
Bogus 15.1.0 release

### ISSUE THREAD

**Issue by sync** [vercel/vercel#2314]
When trying to install latest 15.1.0 1npm i -g now`

I get this error when running on macOS X.

Downloading Now CLI 15.1.0 [                    ] 0%
Error: Not Found https://github.com/zeit/now-cli/releases/download/15.1.0/now-macos.gz

It looks like the release 15.1.0 is bogus

**Comment by TooTallNate** [comment]
Sorry about that, can you try it again? The asset has been uploaded at this point.

**Comment by sync** [comment]
All good now
