### ISSUE TITLE
Nested tsconfig.json broken

### ISSUE THREAD

**Issue by steida** [vercel/vercel#2317]
I made a simple example https://github.com/steida/tsbug

The problem is whenever I add packages/api/tsconfig.json, both deploy and now dev will fail.

```

ERROR in ./packages/foo/index.ts
Module build failed (from /Users/steida/Library/Caches/co.zeit.now/dev/builders/node_modules/@zeit/ncc/dist/ncc/loaders/ts-loader.js):
Error: TypeScript emitted no output for /private/var/folders/11/7qzp98nx1g15w3nfv9nbd6r40000gp/T/co.zeit.now/dev/workPaths/c5n2as4t/packages/foo/index.ts.
    at makeSourceMapAndFinish (evalmachine.<anonymous>:1:2894210)
    at successLoader (evalmachine.<anonymous>:1:2893770)
    at Object.loader (evalmachine.<anonymous>:1:2892441)
 @ ./packages/api/index.ts 2:0-31 6:14-17
```

Sometimes it makes very strange errors like missing Node or Attr types.

**Comment by steida** [comment]
I think we need a demo for Yarn workspaces with TypeScript.

**Comment by mcsdevv** [comment]
Hello @steida, are you still experiencing this issue? If so, please provide a minimal reproducible example so that we can investigate further.

**Comment by steida** [comment]
I am not using monorepo anymore because it's really hard to setup correctly.
