### ISSUE TITLE
Passing email and password to --login flag?

### ISSUE THREAD

**Issue by purplecones** [vercel/vercel#232]
I don't see a way to automate logging into `now` via the command line. For example, how would I be able to deploy with `now` using travis? Passing `--login` flag prompts for checking email and clicking link.

Is there a way for me to pass in my email and password and have the `now` authenticate me directly?

**Comment by matheuss** [comment]
@purplecones we do not work with passwords 🔒 What you can do is:
1. Go to [zeit.co/account#api-tokens](https://zeit.co/account#api-tokens)
2. Create a token named `Travis CI` or something else
3. Use the `now` command on Travis like that: `now --token <token you got from the website>`

Does that helps? :ok_man:

**Comment by purplecones** [comment]
Yes definitely, thanks @matheuss . I didn't catch the `token` flag before. That's actually so much better :-)

**Comment by jamo** [comment]
You may also create `~/.now.json` in travis (take a look of the local config file)

**Comment by boogie4eva** [comment]
@matheuss  When i use your suggestion i am being requested to enter my email ad i am running it in an automated build system like bitbucket pipelines .

**Comment by YashKumarVerma** [comment]
```

+ now@12.1.8
added 1 package in 1.862s
The command "npm install -g now" exited with 0.
1.02s$ now --token {$token}
> Error! Your access token has been revoked. You can log in again using "now login".
The command "now --token {$token}" exited with 1.

```

My token doesn't work ?

**Comment by tedmiston** [comment]
@YashKumarVerma try using `${token}` instead or `$token` without braces.
