### ISSUE TITLE
Be explicit as to what the source of files is for uploads

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#233]
Ideas:

```
> Syncing `.` (1 file ignored from `.gitignore`)
```

```
> Syncing `.` (5 ignored by `.npmignore`)
```

```
> Syncing `files` from `package.json` (3 ignored by `.npmignore`)
```

The idea is to communicate what the _source of truth_ is for the files being uploaded.

**Comment by fibo** [comment]
Ahah, *now* looks awesome, thanks for building it!

I am starting to use it on a side project (that btw uses socket.io, yes I am a fan :))

I had the same idea: *now* could read dot*ignore files,m but, also adding a third option like a .nowignore or an attribute in the *package.json* like

    "now": { "ignore": [ "bundle.js"] }

could be handy and enough flexibleto cover all possibilities.

**Comment by rauchg** [comment]
@fibo Yeah. In general I'm more in favor of *explicit* whitelists, rather than *magic blacklists*. That's why we support `now.files` ;)

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), we only support `.nowignore`! 👏

**Comment by fibo** [comment]
Ahah that is a magic blacklist.

**Comment by NiklasEi** [comment]
@fibo 
You can use it as a whitelist. [See docs](https://zeit.co/docs/v2/platform/upgrade-to-2-0/#.nowignore).
