### ISSUE TITLE
Now not upgradable on windows 10

### ISSUE THREAD

**Issue by Erik-Sovereign** [vercel/vercel#2333]
I'm using now with Windows 10 on a NextJS Project. My package.json states, that I have 
`"now": "^15.2.0" `
installed. But when I'm trying to deploy with the command "now" I get the following message
```
UPDATE AVAILABLE The latest version of Now CLI is 15.2.0
> Read more about how to update here: https://zeit.co/update-cli
> Changelog: https://github.com/zeit/now-cli/releases/tag/15.2.0
```
I tried to install now globally, to uninstall and install it again. I used the command line and now desktop. Nothing worked.

I appreciate every help.

**Comment by leo** [comment]
Was you issue resolved?

**Comment by Erik-Sovereign** [comment]
Yes, I'm pretty certain the issue was on my part, not now-cli's.

Thanks! :)

**Comment by rauchg** [comment]
Thanks for following up @Erik-Sovereign – super appreciated
