### ISSUE TITLE
[now dev] script in package.json with Nuxt perma 404

### ISSUE THREAD

**Issue by khrome83** [vercel/vercel#2338]
now-cli version: `15.1.1-canary.4`
os version: `10.14.4 Mojave`

I have a mono repo build, where `/api` is typescript node. Then `/www` is a nuxt application.

Deploying works fine to now v2. Using just `now dev` CLI command without any `now-dev` command in the script, and it works as expected, just increadible slow, since it runs `nuxt generate`. Using `now-dev` I am telling it to run `nuxt` which should use the development server for Nuxt.

#### Spinner with `net::ERR_ABORTED 404 (Not Found)`
<img width="1275" alt="Screen Shot 2019-05-11 at 10 28 45 AM" src="https://user-images.githubusercontent.com/1844739/57571761-936bf700-73d7-11e9-9e5c-0b3a4eaa9978.png">

### now-cli output from `now dev`
```shell
now dev
> Now CLI 15.1.1-canary.4 dev (beta) — https://zeit.co/feedback/dev
> Setting up 1 Builder
> Success! Builder setup complete
> Ready! Available at http://localhost:3000
10:24:34 ℹ Preparing project for development
10:24:34 ℹ Initial build may take a while
10:24:34 ✔ Builder initialized
10:24:34 ✔ Nuxt files generated
webpackbar 10:24:37 ℹ Compiling Client
10:24:37 ℹ Starting type checking service...
10:24:37 ℹ Using 1 worker with 2048MB memory limit
webpackbar 10:24:44 ✔ Client: Compiled successfully in 6.88s
10:24:44 ℹ Type checking in progress...
10:24:44 ℹ Waiting for file changes
10:24:44 ℹ Memory usage: 278 MB (RSS: 349 MB)
10:24:44 ℹ No type errors found
10:24:44 ℹ Version: typescript 3.4.5
10:24:44 ℹ Time: 7848ms
> GET /
> GET /_nuxt/runtime.js
> GET /_nuxt/commons.app.js
> GET /_nuxt/vendors.app.js
> GET /_nuxt/app.js
```

#### package.json Snippet
```json
  "scripts": {
    "dev": "nuxt",
    "now-dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "now-build": "nuxt generate"
  },
```

#### now.json Snippet
```json
{
  "version": 2,
  "name": "now-test",
  "builds": [
    {
      "src": "./api/comments/*.ts",
      "use": "@now/node@canary"
    },
    {
      "src": "./api/status/*.ts",
      "use": "@now/node@canary"
    },
    {
      "src": "./api/users/*.ts",
      "use": "@now/node@canary"
    },
    {
      "src": "./api/posts/*.ts",
      "use": "@now/node@canary"
    },
    {
      "src": "./www/package.json",
      "use": "@now/static-build"
    }
  ],
  "routes": [
    {
      "src": "/api/posts",
      "methods": ["GET"],
      "dest": "/api/posts/list.ts"
    },
    {
      "src": "/api/status",
      "methods": ["GET"],
      "dest": "/api/status/list.ts"
    },
    {
      "src": "/api/users",
      "methods": ["POST"],
      "dest": "/api/users/create.ts"
    },
    {
      "src": "/api/users/(?<id>[^/]+)",
      "methods": ["GET"],
      "dest": "/api/users/get.ts?id=$id"
    },
    {
      "src": "/api/users/(?<id>[^/]+)",
      "methods": ["DELETE"],
      "dest": "/api/users/delete.ts?id=$id"
    },
    {
      "src": "/api/users/(?<id>[^/]+)",
      "methods": ["PUT"],
      "dest": "/api/users/update.ts?id=$id"
    },
    {
      "src": "/api/comments",
      "methods": ["POST"],
      "dest": "/api/comments/create.ts"
    },
    {
      "src": "/api/comments/(?<id>[^/]+)",
      "methods": ["DELETE"],
      "dest": "/api/comments/delete.ts?id=$id"
    },
    {
      "src": "/api/comments/(?<id>[^/]+)",
      "methods": ["GET"],
      "dest": "/api/comments/get.ts?id=$id"
    },
    {
      "src": "/api/comments/(?<id>[^/]+)",
      "methods": ["PUT"],
      "dest": "/api/comments/update.ts?id=$id"
    },
    {
      "src": "/api/video/comments/(?<id>[^/]+)",
      "methods": ["GET"],
      "dest": "/api/comments/list.ts?id=$id"
    },
    {
      "src": "/(.*)",
      "dest": "/www/$1"
    }
  ]
}
```

**Comment by TooTallNate** [comment]
Note that you need to use the `$PORT` env var in your `now-dev` script, as described in the documentation here: https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build#local-development

**Comment by khrome83** [comment]
@TooTallNate - it does not seem to fix the issue.

#### Using Port Param
```
"now-dev": "nuxt --port $PORT"
```

#### Using Port ENV
```
"now-dev": "NUXT_PORT=$PORT nuxt"
```

https://nuxtjs.org/faq/host-port/

Could it be a different issue?

**Comment by TooTallNate** [comment]
Could you create a repro as a GH repository so I can take a closer look?

**Comment by khrome83** [comment]
@TooTallNate - No Problem.

https://github.com/khrome83/now-dev-issue

Run `now dev` from root and you will see the issue.
Run `npm run dev` from `/www` and you will see it work as expected for just Nuxt. 

This version is using `"now-dev": "nuxt --port $PORT"` which is the nuxt port parameter. 

Let me know what else I can do to help figure this out.

**Comment by TooTallNate** [comment]
Ok ya, I see what's going on now. This is related to an issue that I fixed yesterday in the `@now/static-build` builder. See https://github.com/zeit/now-builders/pull/499. Currently it's only published on the `canary` tag, but I'll cut a stable today.

Let me know if using `@now/static-build@canary` fixes it for you.

**Comment by TooTallNate** [comment]
Ok I published `@now/static-build@0.5.6` which includes the fix in https://github.com/zeit/now-builders/pull/499, so using `canary` is no longer necessary.

**Comment by khrome83** [comment]
@TooTallNate - TYVM worked like a charm. Appreciate the quick response. Today is the first day I have been able to use `now dev` with all the fixes in place. I will keep posting any bugs i seem. Great work to you and all the other contributors.

**Comment by TooTallNate** [comment]
Glad to hear it! I appreciate the bug reports 🙏
