### ISSUE TITLE
[now dev] getting stuck and never finishes

### ISSUE THREAD

**Issue by pajasevi** [vercel/vercel#2339]
I have a problem with `now dev` getting stuck in this state for several minutes trying to build static assets with Parcel.

```bash
$ now dev
> Now CLI 15.2.0 dev (beta) — https://zeit.co/feedback/dev
> Setting up 2 Builders
⠦ Setting up Builder for package.json: ✨  Built in 5.37s.
```

After a couple of minutes, the process fails like this: 

```bash
$ now dev
> Now CLI 15.2.0 dev (beta) — https://zeit.co/feedback/dev
> Setting up 2 Builders
downloading user files...
installing to /var/folders/z6/cw3bj9990rv4c4_n12_f31ph0000gn/T/co.zeit.now/dev/workPaths/oplvjl7g
yarn run v1.15.2
$ parcel watch index.html
✨  Built in 5.63s.

> Error! Failed to detect a server running on port 52001
```

My setup:
- MacOS X Mojave - 10.14.4
- Now 15.2.0
- Node 10.15.3
- `parcel-bundler` 1.12.3

You can simulate this issue on [my repository](https://github.com/pajasevi/UnCSS-Online).

**Comment by TooTallNate** [comment]
The problem is that your `now-dev` script is not binding to the port specified by the `$PORT` environment variable. Please see the [`@now/static-build` local development documentation](https://zeit.co/docs/v2/deployments/official-builders/static-build-now-static-build#local-development) for more details and an example.

**Comment by TooTallNate** [comment]
In your case (parcel), I believe the proper `now-dev` script should be: `parcel serve --port $PORT`. Let me know if that works for you please 🙏

**Comment by pajasevi** [comment]
That works, now the job finishes. I just have to adjust parcel to serve the file in the right format.
Thanks!
