### ISSUE TITLE
[now dev] Issues when converting routes from PCRE to RegExp

### ISSUE THREAD

**Issue by raulg** [vercel/vercel#2341]
There are still some issues when converting PCRE to RegExp for matching the routes. For the following routes configuration, it would catch routes beginning with `/preview?` as the second route `page?uid=preview` despite it being lowest priority

```
"routes": [
    { "src": "/preview\\?(?<query>.*)", "dest": "/preview?query=$query" },
    { "src": "/(?<uid>[^/]+)$", "dest": "/page?uid=$uid" }
  ]
```
Attempted to work around it by defining it more specifically 
```
{ "src": "/(?!preview)(?<uid>[^/]+)$", "dest": "/page?uid=$uid" }
``` 
which fixed the wrong routes issue, but it returned `/page?uid=undefined` for all regular pages. Figured it was a problem with RegExp not handling well named groups, so modified it into 
`{ "src": "/(?!preview)(?<uid>[^/]+)$", "dest": "/page?uid=$1" }`
which does work for this case, but is not the best since routes end up very different from the [Now definition](https://zeit.co/docs/v2/deployments/configuration/#routes)

_Originally posted by @raulg in https://github.com/zeit/now-cli/issues/2023#issuecomment-478062254_

**Comment by TooTallNate** [comment]
I think there's some confusion about the `src` property in the PCRE. The querystring is automatically applied to the `dest` path, so you don't need to match it. The querystring is also not supplied to the `src`, so that's why it's not matching your PCRE.

**Comment by raulg** [comment]
You're correct, turns out the issues were due to leftover workarounds from an early version.
```
"routes": [
  { "src": "/preview", "dest": "/preview" },
  { "src": "/(?<uid>[^/]+)$", "dest": "/page?uid=$uid" }
]
```
Works as intended in version 15.2.1-canary.0
Thanks for the help, it's going to make development a breeze.
