### ISSUE TITLE
[now dev] cache problem with port

### ISSUE THREAD

**Issue by markozxuu** [vercel/vercel#2347]
now version: **15.2.1-canary.0**
OS:  **10.14.4**
builders: [`@now/next`, `@now/node`]

I'm working on a **monorepo** application and after a certain time `@now/next` does not detect the changes I'm making to my project with Next.js. This problem can be solved by changing the port but then the problem returns to the new port.

**NOTE**: this happens with any port

For example: the `/chat` path does not exist but it keeps asking for it every time you access `/`
<img width="676" alt="Screen Shot 2019-05-14 at 23 58 14" src="https://user-images.githubusercontent.com/16585386/57750904-91d95200-76a9-11e9-8076-157a41b2b360.png">

**Comment by TooTallNate** [comment]
@MAPESO About how long does this take to happen? Could you share a video of what you are experiencing?

**Comment by markozxuu** [comment]
@TooTallNate Apparently the problem was related to the **browser cache**. I just cleaned it and it works again 🤔
