### ISSUE TITLE
15.2.0 is flagged by kappersky as trojan

### ISSUE THREAD

**Issue by hissalht** [vercel/vercel#2348]
Weither I run `npm i -g now` or manually download the file from [the release page](https://github.com/zeit/now-cli/releases/tag/15.2.0), the file is deleted in seconds after being extracted.

Kapersky entry from my machine
```
14-May-19 18:43:06	Deleted	Trojan program Trojan.Win32.Denes.akl	C:\Users\HISSALHT-NAME\AppData\Roaming\npm\node_modules\now\download\dist\now.exe	High	
```

Virus total scan link : https://www.virustotal.com/#/file/01d64f9902e209d352d2b979aa7ecbb0075e228845f0e4ca0b10af9fba61dcbc/detection

EDIT : The previous version `15.1.0` does not have this problem : https://www.virustotal.com/#/url/752326393ea959c4870c9cdd68ced8f5f8073da3c2e9b2534930e8f6138e8a7b/detection

**Comment by ukoloff** [comment]
I confirm the issue. [VirusTotal] reports 3 antviruses who complain: Kaspersky, Zone Alarm and Qihoo-360.

[VirusTotal]: https://www.virustotal.com/gui/file/b65710d4781751d79c4e124acf7b59db569c44c390640e4be956bb58e156e920/detection

**Comment by ukoloff** [comment]
Release [15.1.0] is detected as harmful (again, by Kaspersky & Zone Alarm). [15.0.11] is clear.

[15.1.0]: https://www.virustotal.com/gui/file/d69674c26578e9324ea0f8a14905fba79cf9cbc0d39f3ddf4c9b17207137c1d8/detection
[15.0.11]: https://www.virustotal.com/gui/file/2ad24c44d667257dff7f5ea639321013dd969f400315176be3767988c0d0344b/detection

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!

**Comment by filips123** [comment]
@leo Why? Is there any way to install Now without installing whole Node.js and NPM just for single command tool?
