### ISSUE TITLE
External domain alias

### ISSUE THREAD

**Issue by tflx** [vercel/vercel#2349]
I don't understand your instructions for adding a domain I already own. Searching for the same under issues gives me about 130 hits so I'm not alone I guess.

Do I have to change DNS records at my domain provider or can I do without?

I have added a TXT record and added a CNAME record.
The CNAME record looks like this:

*.mydomain.com | alias.zeit.co

Running
`now domains verify mydomain.com`
...tells me my domain was verified using DNS TXT record.

Those changes was done yesterday.
What do I need to do?

**Comment by timothyis** [comment]
Hi @tflx, so just to clarify, you've verified your domain and are unsure of what you can do next?

If so, you can now use your domain to deploy your applications to, using the target aliasing feature: 
https://zeit.co/docs/v2/domains-and-aliases/aliasing-a-deployment/

More specifically, for your applications to be live at your domain, you can use the production deployment environment: https://zeit.co/docs/v2/domains-and-aliases/aliasing-a-deployment/#production

Please let me know if this is what you are confused about. I'd love to improve this flow. Did you read through the docs, or were there other resources you read?

**Comment by tflx** [comment]
Yes it's verified and I SHOULD be able to access my deployments via my domain. But the point is that I can't. I have read through your documentation and believe I have done everything correct. And I have the alias in my now.json file.

**Comment by tflx** [comment]
If I add www.mydomain.com it works - sort of. At least I get a 404 from Zeit.
Without the www I get the standard Chrome "This site can’t be reached".

*Edit:

Okay so after I added www.mydomain.com to aliases in now.json going to www.mydomain.com works great.
But mydomain.com (without www) does not work. Why and how do I fix it?

**Comment by timothyis** [comment]
Would you be able to tell me what your domain name is? I'd be happy to take a look. Feel free to also email me at timothy@zeit.co if you wouldn't like to publicly share it. 

It's very odd that you cannot access your domain without www. when aliasing to it.

I apologise if this is a documentation issue, I'd really like to be able to help improve this.

**Comment by tflx** [comment]
I gave up and went with changing the nameservers instead of the CNAME option.
That was much less painful, but still annoying I have to go with that.
Close this if you want.

**Comment by paulogdm** [comment]
Hello!
Yes, you need to change it in your domain provider. You have two choices:

1. Change NS (recommended)
2. TXT for verification + CNAME.

Take a look at: https://zeit.co/docs/v2/domains-and-aliases/adding-a-domain

**Comment by paulogdm** [comment]
Let me know if you need anything!

**Comment by iamwasimaftab** [comment]
can i use domain Alias for Api ?
i have native android application and i have same website host in other domain so can i merge as Alias with new one to old with changing app api url??
i want to show my new website which upgrade as same feature with .in domain previus was .com.  ???

**Comment by paulogdm** [comment]
> can i use domain Alias for Api ? i have native android application and i have same website host in other domain so can i merge as Alias with new one to old with changing app api url?? i want to show my new website which upgrade as same feature with .in domain previus was .com. ???

Please create a new post if you have questions. Also, you do need to give users as much context as possible with some clarity. Your text should be improved so we can answer if effectively.
