### ISSUE TITLE
Deployment fails when Creat React App is added with React Snap

### ISSUE THREAD

**Issue by nitish24p** [vercel/vercel#2357]
I am trying to use the create-react-app's `now.json` template to deploy my application.
However to pre-render my pages i am using react-snap. The build fails, on the server and i get the following error
```
 $ react-snap
2019-05-16T22:47:04.236Z  Error: Failed to launch chrome!
                          /tmp/77102a3b/node_modules/puppeteer/.local-chromium/linux-656675/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory


                          TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

                              at onClose (/tmp/77102a3b/node_modules/puppeteer/lib/Launcher.js:342:14)
                              at Interface.helper.addEventListener (/tmp/77102a3b/node_modules/puppeteer/lib/Launcher.js:331:50)
                              at emitNone (events.js:111:20)
                              at Interface.emit (events.js:208:7)
                              at Interface.close (readline.js:370:8)
                              at Socket.onend (readline.js:149:10)
                              at emitNone (events.js:111:20)
                              at Socket.emit (events.js:208:7)
                              at endReadableNT (_stream_readable.js:1064:12)
                              at _combinedTickCallback (internal/process/next_tick.js:138:11)
2019-05-16T22:47:04.253Z  error Command failed with exit code 1.
```

My Package.json
```json
 "scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "stage": "yarn run build && cp src/netlify/_redirects build/.",
    "test": "node scripts/test.js",
    "now-dev": "node scripts/start.js",
    "now-build": "yarn run build",
    "postbuild": "react-snap",
}
```

My now.json
```
{
  "version": 2,
  "name": "jsvault",
  "builds": [
    {
      "src": "package.json",
      "use": "@now/static-build",
      "config": { "distDir": "build" }
    },
    {
      "src": "build/**.*.js",
      "use": "@now/node"
    }
  ],
  "routes": [
    {
      "src": "/static/(.*)",
      "headers": { "cache-control": "s-maxage=31536000,immutable" },
      "dest": "/static/$1"
    },
    { "src": "/favicon.ico", "dest": "/favicon.ico" },
    { "src": "/asset-manifest.json", "dest": "/asset-manifest.json" },
    { "src": "/manifest.json", "dest": "/manifest.json" },
    { "src": "/precache-manifest.(.*)", "dest": "/precache-manifest.$1" },
    {
      "src": "/service-worker.js",
      "headers": { "cache-control": "s-maxage=0" },
      "dest": "/service-worker.js"
    },
    {
      "src": "/(.*)",
      "headers": { "cache-control": "s-maxage=0" },
      "dest": "/index.html"
    }
  ],
  "build": {
    "env": {
      "NODE_ENV": "production"
    }
  }
}

```

So react-snap basically opens pupetter and parses the pages, and throws out an index.html

I even tried adding 2 builders something like so
```json
"builds": [
    {
      "src": "package.json",
      "use": "@now/static-build",
      "config": { "distDir": "build" }
    },
    {
      "src": "build/**.*.js",
      "use": "@now/node"
    }
  ],
```
But to no avail. 
Am i doing anyting wrong? or is such a combo not possible? I dont mind downgrading to version 1 so that it works, if thats the issue

**Comment by TooTallNate** [comment]
Looks like puppeteer is failing to load. Have you tried the suggestions in the troubleshooting page that is linked in the error message? https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix

**Comment by nitish24p** [comment]
how do i check the installation inside the now container ?

**Comment by loomchild** [comment]
I raised a similar issue for prerender-spa-plugin here: https://github.com/zeit/now-builders/issues/517. Full Puppeteer is not supported - instead we should use a special serverless one. However, I can't make it work during lambda build / deployment, as Chromium is present only at runtime.

**Comment by styfle** [comment]
We added the necessary dependencies to run full puppeteer at build time.

I believe this will also solve the `react-snap` failures but I'm not sure how it works so it would be good if someone can confirm it is working now.

We'll add a test in PR #3911 to make sure `puppeteer` continues to work properly, thanks!

**Comment by HoverBaum** [comment]
I think this is still an issue.

Just tried using React-Snap for a project and got this as the error during build:

```
$ react-snap
Error: Failed to launch chrome!
[0509/143556.521569:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
    at onClose (/zeit/1d9a009a/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/zeit/1d9a009a/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:228:7)
    at Interface.close (readline.js:402:8)
    at Socket.onend (readline.js:180:10)
    at Socket.emit (events.js:228:7)  
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
error Command failed with exit code 1.
```

**Comment by styfle** [comment]
You'll need to add a couple flags in package.json like PR #3911 describes:

```json
{
  "reactSnap": {
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox"
    ]
  }
}
```

**Comment by HoverBaum** [comment]
Thanks for pointing that out again. Could have been more thorough in going through the comments.

You above code fixed it for me 👍

**Comment by tiarebalbi** [comment]
Yes, the approach mentioned above fixes the issue!  (https://github.com/vercel/vercel/issues/2357#issuecomment-626236409)

**Comment by noshor** [comment]
> You'll need to add a couple flags in package.json like PR #3911 describes:
> 
> ```json
> {
>   "reactSnap": {
>     "puppeteerArgs": [
>       "--no-sandbox",
>       "--disable-setuid-sandbox"
>     ]
>   }
> }
> ```

This worked, we searched for hours trying to fix this issue, big thank you!

**Comment by BrunoQuaresma** [comment]
Interesting, this worked for me when I did `yarn vercel deploy` but does not work when I do `yarn vercel deploy --prod`
