### ISSUE TITLE
now dev on 15.2.1-canary.1 runs different node version which causes issues with sass bindings

### ISSUE THREAD

**Issue by tom2strobl** [vercel/vercel#2359]
I updated the now cli to 15.2.1-canary.1 to get the fix with the now routes, but then `now dev` errors:

```
Error: Missing binding /Users/thomas/dev/mediaapparat/node_modules/node-sass/vendor/darwin-x64-57/binding.node
Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 12.x
```

I have node 12.x installed and node-sass bindings are obviously set up for that version. For some reason it asks for 8.x bindings which is weird, I can confirm that it has been working with v15.2 (but the routes fix is not live at 15.2).

I also tried to delete caches at /Library/Cache/co.zeit.now as I thought after switching to canary there might be leftovers, but that didn't help.

**Comment by christopher-kiss** [comment]
I'm getting the same issue using 15.2.1-canary.2, trying to static-build an angular application.

Node 11 installed for me on Windows 10.

**Comment by tom2strobl** [comment]
Not bumping, but while looking through other issues I found this which may or may not be related: https://github.com/zeit/now-cli/issues/2353

**Comment by arjunu** [comment]
Issue exists on v15.3.0. Direct webpack build works while `now dev` fails.

**Comment by farebecca** [comment]
I'm having the same issue

**Comment by DawTaylor** [comment]
I'm having the same issue

**Comment by LucasArthur94** [comment]
I'm having the same issue

**Comment by danieltr10** [comment]
Same here

**Comment by bandreetto** [comment]
+1

**Comment by manelet** [comment]
Same problem, using nvm (10.5) `now dev` says I'm using node 8.
osx 64bit aswell

**Comment by caioquinta** [comment]
I'm having the same issue

**Comment by texmex44** [comment]
Same issue here

**Comment by cibulka** [comment]
Same issue here, Now CLI 15.8.0. After I've downgraded from Node 10.1.0 to Node 8.11.1 (and installed the appropriate bindings with `npm rebuild node-sass`), `now dev` started working.

**Comment by leo** [comment]
Thank you for reporting this!

We are now using the installed Node.js version, so this problem is avoided.
