### ISSUE TITLE
Cannot use a the cli anymore: killed now

### ISSUE THREAD

**Issue by roelvan** [vercel/vercel#236]
This is what I see when I try to use `now` in my terminal.
![screen shot 2017-01-22 at 18 50 27](https://cloud.githubusercontent.com/assets/2583837/22182272/d39d2cfc-e0d3-11e6-90bc-688f7ba7df13.jpg)
I deployed 3 projects successfully and suddenly when I tried a 4th time I saw the above notification.

**Comment by jamo** [comment]
Updating the issue base on live debugging session in zeit.chat:

It seems that for some reason autoupdate by `now.app` installed a only partially downloaded binary. Which lead to this error. Redownloading `now` with now.app seems to have fixed it
