### ISSUE TITLE
How to deploy on zeit version 2 using cli

### ISSUE THREAD

**Issue by fnLog0** [vercel/vercel#2364]
```{  "engines": {
    "node": "^10.13.0",
    "yarn": "^1.9.4"
  },
  "scripts": {
    "start": "node dist/index.js",
    "build": "babel src --out-dir dist",
    "serve": "npx babel-node src/index.js",
    "dev": "nodemon --exec babel-node src/index.js",
    "lint": "eslint --fix --ext .jsx,.js src/*.js src/**/*.js src/**/**/*.js",
    "deploy": "./deploy.sh"
  },
  "dependencies": {
    "@babel/polyfill": "^7.2.5",
    "apollo-server": "^2.4.8",
    "axios": "^0.18.0",
    "bcryptjs": "^2.4.3",
    "convict": "^4.4.1",
    "dotenv": "^6.2.0",
    "graphql": "^14.1.1",
    "jsonwebtoken": "^8.5.0",
    "lodash": "^4.17.11",
    "merge-graphql-schemas": "^1.5.8",
    "mongoose": "^5.4.17",
    "mongoose-fill": "^1.7.0",
    "mongoose-float": "^1.0.4",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.3.4",
    "@babel/node": "^7.2.2",
    "@babel/preset-env": "^7.3.4",
    "eslint": "^4.18.2",
    "eslint-config-airbnb-base": "^12.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-import": "^2.9.0",
    "eslint-plugin-prettier": "^2.6.0",
    "nodemon": "^1.18.10",
    "prettier": "^1.11.1"
  }
}```

folder structure 
src/package.json
now.json

**Comment by mtt87** [comment]
You just need to specify in your `now.json` the version.
```json
{
  "version": 2,
  "name": "my-project"
  ...stuff
}
```
Then run `now`

**Comment by fnLog0** [comment]
> You just need to specify in your `now.json` the version.
> 
> ```json
> {
>   "version": 2,
>   "name": "my-project"
>   ...stuff
> }
> ```
> 
> Then run `now`

@mtt87 can you please explain bit more? ```...stuff```

**Comment by mtt87** [comment]
Sorry with `...stuff` I meant everything else that is in your current configuration.
If your question is
> How to deploy on zeit version 2 using cli?

The answer is add `"version": 2` to your existing `now.json` and then check if your configuration is correct. 
Documentation: https://zeit.co/docs/v2/deployments/configuration/

If all is good run `now` and it should deploy to the cloud.

**Comment by fnLog0** [comment]
> Sorry with `...stuff` I meant everything else that is in your current configuration.
> If your question is
> 
> > How to deploy on zeit version 2 using cli?
> 
> The answer is add `"version": 2` to your existing `now.json` and then check if your configuration is correct.
> Documentation: https://zeit.co/docs/v2/deployments/configuration/
> 
> If all is good run `now` and it should deploy to the cloud.

@mtt87 what configuration need for package,json "build" and start? Please help!

**Comment by fnLog0** [comment]
my current configuration is:-
```{
  "name": "demo",
  "alias": ["demo"],
  
    "version": 2,
    "builds": [
      { "src": "src/index.js", "use": "@now/node" }
    ],
    "routes": [
      { "src": "/(.*)", "dest": "/index.js" }
    ]
  
}
```

**Comment by mtt87** [comment]
I don't know it depends on your use case, that's not something I can help with.
You can ask for more specific help here https://spectrum.chat/zeit but you need to include more info otherwise it's impossible to help you

**Comment by TooTallNate** [comment]
The release of zero-config sounds like it would be helpful for you: https://zeit.co/blog/zero-config

Closing because Spectrum should be used for help, this issue tracker is for bug reports.
