### ISSUE TITLE
now dev not working with `@now/static-build` when target is one level down

### ISSUE THREAD

**Issue by toddgeist** [vercel/vercel#2366]
Here is a repo with a now.json setup to a static builder to serve a react app that is nested inside a "front" folder.

https://github.com/toddgeist/now-dev-cra-nested-issue

I think this should work but now dev fails with an error suggesting it can't find a package.json file.

It works fine of now.json is at the same level as the app.

**Comment by TooTallNate** [comment]
Closing because I just tried it with the latest Now CLI and `now dev` is working as expected.
