### ISSUE TITLE
[now dev] GitHub dependencies not supported

### ISSUE THREAD

**Issue by denkristoffer** [vercel/vercel#2381]
With https://github.com/zeit/now-builders/issues/49 we can use GitHub dependencies in now v2 deployments, but they don't currently work with the `now dev` command.

**Comment by TooTallNate** [comment]
Hey @denkristoffer. What kind of error do you see? Would you be able to create a GitHub repo demonstrating the issue? Thanks in advance!

**Comment by denkristoffer** [comment]
My apologies @TooTallNate, I didn't think of this as a bug report, I thought you simply hadn't gotten around to supporting it for `now dev` yet 🙂 I'll see if I can put together a reproduction.

**Comment by TooTallNate** [comment]
Closing because I just tested this with the latest Now CLI and it works with `now dev` as expected. Demonstration repo is here: https://github.com/TooTallNate/now-cli-2381
