### ISSUE TITLE
Subdirectory pages don't work on `now dev` with @now/next

### ISSUE THREAD

**Issue by PullJosh** [vercel/vercel#2385]
If I serve a Next.js project using `now dev` and it contains directories within `pages`, all sub-pages throw 404 errors. The exact same configuration works correctly on Now proper, but not in the development environment.

For example, in the following setup:
```
pages/
  a/
    index.js
    b.js
  c.js
next.config.js
now.json
```

After running `now dev`, `http://localhost:3000/c` will load correctly but `/a` and `/a/b` will both 404.

**Comment by mcsdevv** [comment]
Hello @PullJosh, could you share with us your `now.json` file please?

**Comment by PullJosh** [comment]
Here's a quick demo: https://github.com/PullJosh/next-subfolder-struggles

The site works great when hosted on Now, but some pages fail to load in `now dev` (at least for me on Windows 10).

**Comment by Inch4Tk** [comment]
Running into the exact same problem on Windows 10.
It will show the sites when navigating to them via the clientside along nextjs links. If I then refresh the page I will get a 404.

**Comment by TooTallNate** [comment]
Hmmm, I can't seem to reproduce, on macOS at least. I'll try it on Windows when I get access to a box running it.

<img width="1007" alt="Screen Shot 2019-06-12 at 6 27 33 PM" src="https://user-images.githubusercontent.com/71256/59396973-cb03f100-8d3f-11e9-9d53-dea16801b40e.png">

**Comment by PullJosh** [comment]
Looks great on your machine! 😛

For reference, here's that same setup on mine:
![image](https://user-images.githubusercontent.com/5458180/59437892-6fc61300-8dc0-11e9-8868-51d1c7f6086f.png)

**Comment by TooTallNate** [comment]
Ok so definitely related to Windows then (backslash vs. forward slash issue I'm assuming). We will fix this soon!

**Comment by PullJosh** [comment]
Any luck with this one?

**Comment by Erik-Sovereign** [comment]
This is also an issue for the new Next.js Api Route features. I can access mypage.come/api/hello when hosted with now. But I can't access it with now dev on localhost.
