### ISSUE TITLE
Installing globally with yarn does not seem to be working

### ISSUE THREAD

**Issue by tomsseisums** [vercel/vercel#2386]
Installing with `yarn global add now` ends up with the same issue as here: https://github.com/zeit/now-cli/issues/1923 (Running `now` produces no output at all)

Installing with `npm install -g now` works.

The problem happens due to:
  - `<yarn>/.bin/now.cmd` points to `<yarn>/Data/global/node_modules/.bin/now.cmd`
  - `<yarn>/Data/global/node_modules/.bin/now.cmd` attempting to execute `node <cwd>/../now/download/dist/now`
  - which actually is empty, looking to be generated by: https://github.com/zeit/now-cli/blob/15178f0332cf5d71b153bbaa880329ad88c53db7/download/src/index.js#L152

Which is different behavior from `npm`, where `<npm>/now.cmd` executes `<npm>/node_modules/now/download/dist/now.exe` (**exe**) directly with no `node` wrapper.

The same empty file is also generated for `npm` install, just that it's not used at all [or npm internally uses it?].

Same happens for generated bash wrappers, `npm` points to `exe`, while `yarn` is looking to execute `node` with the empty file.

---

Since there is explicit patching for `npm`, that generates the proper `now.exe` wrappers: https://github.com/zeit/now-cli/blob/15178f0332cf5d71b153bbaa880329ad88c53db7/download/src/index.js#L154

The fix probably lies in detecting if installation is being made with `yarn` and patching accordingly.

---

Actually, currently there is unexpected behavior when installing with `yarn`.

Since `npm` comes by default with `node` nowadays on Windows, the fix is ran for `yarn` also, generating the two files in `<npm>` directory.
  
That actually caused a conflict, because I had some packages installed globally with `npm` (which didn't error out the patch) and on my system, `<npm>` PATH had higher priority over `<yarn>/bin` PATH and therefore `now` global binary was called from the patched`<npm>/now.cmd` trying to explicitly call `<npm>/node_modules/now/download/dist/now.exe` which, obviously, did not exist when installed with `yarn` that resulted in CMD error: `The system cannot find the path specified.`

While that was an error on my part, it goes to show how _package manager unaware_ the current patch is.

---

I'd be glad to help out, but I can't seem to find out how to set up installation scenario locally.

**Comment by Skaronator** [comment]
I run in the same issue. Installing Now 13 and everything works again.

`yarn global add now@13`

**Comment by leo** [comment]
Thank you for the investigation!

This week, we'll be publishing a drastic change to our (currently) very complicated installation mechanism for Now CLI. After that, it will be installing itself like any other npm library out there, which will get rid of the problem.

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!
