### ISSUE TITLE
now dev: "Error: Body exceeded 1mb limit" when GETting a 780KB JSON response

### ISSUE THREAD

**Issue by dhruvio** [vercel/vercel#2387]
When running `now dev`, a HTTP GET request to my local server that responds with a ~780kb JSON body fails with a run-time exception stating: "Error: Body exceeded 1mb limit". I do not receive this error in production.

**Comment by dhruvio** [comment]
See the related Spectrum thread: https://spectrum.chat/zeit/now/error-body-exceeded-1mb-limit~69845eac-55c7-412e-b4e5-deba469cfe26

**Comment by TooTallNate** [comment]
Closing because this has been fixed in the latest version of Now CLI. See https://github.com/zeit/fun/pull/21 for the details.

**Comment by manoharreddyporeddy** [comment]
This issue reproduced today.
