### ISSUE TITLE
Running now dev at Alpine linux error with node bin

### ISSUE THREAD

**Issue by arvati** [vercel/vercel#2394]
to run now dev using alpine linux i had to overwrite node bin with node bin from my install:
```sh
ln -sf /usr/bin/node ~/.cache/co.zeit.fun/runtimes/nodejs8.10/bin/
```
Error message before overwriting:
```sh
> Building @now/node:example.js
Error: spawn ~/.cache/co.zeit.fun/runtimes/nodejs8.10/bin/node ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Probably ~/.cache/co.zeit.fun/runtimes/nodejs8.10/bin/node depends on modules not compiled correctly with musl compiler or needs some package to be installed with apk add, hard to tell, need help to how to trace more.

My system node version is v10.15.3
My now version is 15.3.0 and using binary from now-alpine download releases.

**Comment by TooTallNate** [comment]
Thanks for the report. This is indeed an issue related to MUSL builds.

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!
