### ISSUE TITLE
now dev with api route throwing error `TypeError: Path must be a string. Received 558`

### ISSUE THREAD

**Issue by ruscandino** [vercel/vercel#2395]
I have a simple Next.js + Now app that is working if I don't do `getInitialProps` with a `fetch` using `isomorphic-fetch`. If I _do_ use `fetch('http://localhost:3000/api/foo')`, it results in this in the terminal:

    > GET /foo
    [ event ] build page: /
    [ wait ]  compiling ...
    > GET /api/foo
    > Building @now/node:api/index.js
    downloading user files...
    installing dependencies for user's code...
    installing to /Users/me/dev/test-now/api
    running user script...
    running "npm run now-build"

    > next-news@ now-build /Users/me/dev/test-now
    > next build

    Creating an optimized production build ...

    Compiled with warnings.

    ./node_modules/encoding/lib/iconv-loader.js
    Critical dependency: the request of a dependency is an expression

     ┌ /
     ├ /_app
     ├ /_document
     └ /_error

    compiling entrypoint with ncc...
    ncc: Version 0.18.5
    ncc: Compiling file index.js
    > Built @now/node:api/index.js [21s]
    TypeError: Path must be a string. Received 558
        at assertPath (path.js:28:11)
        at Object.dirname (path.js:1349:5)
        at Object.module.exports.module.exports.out (/private/var/folders/rj/_7gm1nf956b5bfg49lhs4s8r0000gn/T/zeit-fun-1f0210dfa9069/api/index.js:117599:36)
        at __webpack_require__ (/webpack/bootstrap:19:1)
        at Object.module.exports.Object.defineProperty.value (/private/var/folders/rj/_7gm1nf956b5bfg49lhs4s8r0000gn/T/zeit-fun-1f0210dfa9069/api/index.js:66034:25)
        at __webpack_require__ (/webpack/bootstrap:19:1)
        at Object.module.exports.Object.defineProperty.value (/private/var/folders/rj/_7gm1nf956b5bfg49lhs4s8r0000gn/T/zeit-fun-1f0210dfa9069/api/index.js:65950:16)
        at __webpack_require__ (/webpack/bootstrap:19:1)
        at Object.module.exports.exports.Store (/private/var/folders/rj/_7gm1nf956b5bfg49lhs4s8r0000gn/T/zeit-fun-1f0210dfa9069/api/index.js:39450:22)
        at __webpack_require__ (/webpack/bootstrap:19:1)

It doesn't even reach the `api/index.js` code, it throws a weird error `Path must be a string. Received 558`, which is from here (the `558`):

    exports.loadSync = loadSync;
    // Load Google's well-known proto files that aren't exposed by Protobuf.js.
    {
        // Protobuf.js exposes: any, duration, empty, field_mask, struct, timestamp,
        // and wrappers. compiler/plugin is excluded in Protobuf.js and here.
        var wellKnownProtos = ['api', 'descriptor', 'source_context', 'type'];
        var sourceDir = path.join(path.dirname(/*require.resolve*/(558)), 'google', 'protobuf');
        for (var _i = 0, wellKnownProtos_1 = wellKnownProtos; _i < wellKnownProtos_1.length; _i++) {
            var proto = wellKnownProtos_1[_i];
            var file = path.join(sourceDir, proto + ".proto");
            var descriptor_1 = Protobuf.loadSync(file).toJSON();
            // @ts-ignore
            Protobuf.common(proto, descriptor_1.nested.google.nested);
        }
    }
    //# sourceMappingURL=index.js.map

Not really sure what's going wrong.

My now.json looks like this:

    {
      "version": 2,
      "public": false,
      "builds": [
        { "src": "api/*.js", "use": "@now/node" },
        { "src": "package.json", "use": "@now/next" },
        { "src": "/static/*", "use": "@now/static" }
      ],
      "routes": [
        { "src": "/_next/(.*)", "dest": "/_next/$1" },
        { "src": "/static/(.*)", "dest": "/static/$1" },
        {
          "src": "/api/(?<slug>.+)",
          "dest": "api/index.js?slug=$slug"
        },
        { "src": "/(.*)", "dest": "/index?slug=$1" }
      ]
    }

My package.json like this:

    {
      "name": "next-news",
      "license": "MIT",
      "dependencies": {
        "@google-cloud/datastore": "^4.0.0",
        "@google-cloud/storage": "^2.5.0",
        "isomorphic-fetch": "^2.2.1",
        "ms": "^2.1.1",
        "next": "^8.0.0",
        "nprogress": "^0.2.0",
        "react": "^16.7.0",
        "react-dom": "^16.7.0",
        "request": "^2.88.0",
        "url-parse": "^1.4.4"
      },
      "scripts": {
        "dev": "now dev",
        "build": "next build",
        "start": "next start",
        "now-build": "next build"
      }
    }

My api/index.js like this:

```js
const { Datastore } = require('@google-cloud/datastore')

const datastore = new Datastore({
  projectId: 'myrepo123',
})

module.exports = (req, res) => {
  console.log("HERE", req.url)
  req.url.match(/\?slug=([^\&]+)/)
  const slug = RegExp.$1

  if (!slug) return

  const pageKey = datastore.key([ 'Page', slug ])

  datastore.get(key, function(err, entity){
    console.log('here', entity)
    res.writeHead(200, { 'Content-Type': 'application/json' })
    res.end(JSON.stringify(entity))
  })
}
```

The page/index.js is like this:

```js
module.exports = class Page extends React.Component {
  static async getInitialProps({ query, res }) {
    const { slug } = query
    if (slug) {
      let x = await fetch(`http://localhost:3000/api/${slug}`)
      let json = await x.json()
      return json
    } else {
      return {}
    }
  }

  render() {
    return <div>foo</div>
  }
}
```

**Comment by shaunmolloy** [comment]
Hi @ruscandino,

Let me know if the following makes a difference.

### now.json

> before

```
 "dest": "api/index.js?slug=$slug"
```

> after
```
 "dest": "/api/index.js?slug=$slug"
```

### pages/index.js

Also the `if (slug)` probably wouldn't account for undefined and should be:
`if (typeof slug !== 'undefined' && slug !== null)`

**Comment by leo** [comment]
No response. Closing.
