### ISSUE TITLE
`stale-while-revalidate` header is missing on Now 2.0

### ISSUE THREAD

**Issue by amio** [vercel/vercel#2396]
For this Now 2.0 deployment https://v2.badgen.net/badge/color/orange/orange

The cache control header should be
```
public, max-age=30, s-maxage=10800, stale-while-revalidate=604800, stale-if-error=604800
```

While it actually is
```
public, max-age=30, stale-if-error=604800
```

The header is set by code
```javascript
  const staleControl = `stale-while-revalidate=604800, stale-if-error=604800`
  const cacheControl = `public, max-age=30, s-maxage=${sMaxAge}, ${staleControl}`
  res.setHeader('Cache-Control', cacheControl)
```

Headers set with `now.json` is fine.
This header is untouched on Now 1.0.

**Comment by leo** [comment]
Closing in favor of https://github.com/zeit/now-cli/issues/2608
