### ISSUE TITLE
Prevent automatic aliasing for staging

### ISSUE THREAD

**Issue by StefMa** [vercel/vercel#2397]
Is it possible to prevent the automatic aliasing for staging which you introduced [here](https://zeit.co/blog/automatic-aliasing)?
I would love to see something like `now --target unique` or something which **don't** override the current staging url.

I mean given the following scenario:
I build a product which has a `production` url.
It has also a `staging` url for our QA.

When we do changes we don't want to override the current `staging` URL because our QA don't want to be surprised with new features which are likely to break the build...

**Comment by wiiiimm** [comment]
You can run the deployment without a `target`. Then it won’t receive the staging alias

**Comment by StefMa** [comment]
Um.. that is not true.
At least not for the docs and my current CLI 😳 

> Every new deployment, whether it is from Now CLI, Now for GitHub, or Now for GitLab, will receive both a unique deployment URL and a staging alias for the deployment that updates with every deployment you personally make from the project.

Each `now` will create both. A unique url **and** a staging alias. Therefore it will **override** the existing staging alias.
Which is what I want to avoid. I want the unique url **only**.
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/10229883/59248682-63f11a00-8c23-11e9-96bc-9e41b7fd9b08.gif)

**Comment by wiiiimm** [comment]
@StefMa sorry my bad. 

For now, if you use a team instead of personal account, you have a `team staging URL` when you run `now --target staging`, and without it, your deployments will only get a unique URL and a personal staging URL.

https://zeit.co/docs/v2/domains-and-aliases/aliasing-a-deployment/#staging-environment-aliases-for-a-team's-project

**Comment by wiiiimm** [comment]
related to: https://github.com/zeit/now-cli/issues/2010

**Comment by wiiiimm** [comment]
@StefMa FYI https://github.com/zeit/now-cli/issues/2192#issuecomment-497372244

Our team will be releasing a new feature soon that might help with this issue.

**Comment by StefMa** [comment]
Thank you @williamli.
Also thank for the given workaround :)

I think my request is the same as #2010 :)
I will close this for now 👍
