### ISSUE TITLE
`now --login` fails on windows git bash

### ISSUE THREAD

**Issue by leo** [vercel/vercel#24]
> > Enter your email: > Error! Authentication error – process.stdin.setRawMode is not a function

@yangg

**Comment by rauchg** [comment]
@leo what version of Node?

**Comment by leo** [comment]
@rauchg :trollface: Hmm... No idea. @yangg?

**Comment by nkzawa** [comment]
I investigated this bug a bit in the past, and could reproduce it by Node v6 and Git Bash.

Basically, it's because `setRawMode` method doesn't exist when environment is not TTY.
so we can do `if (process.stdin.setRawMode) ...`, but, since `email-prompt` module requires `setRawMode`, we would have to fix the module a lot.

**Comment by rauchg** [comment]
I see. Why wouldn't git bash give us a TTY :O ?

**Comment by aranajhonny** [comment]
Todavía no funciona en esta terminal. @rauchg 
![screenshot](https://cloud.githubusercontent.com/assets/9091881/18818952/0a0261a6-835d-11e6-815d-20d8ae6dcd67.png)

**Comment by mreinstein** [comment]
I've run into this issue as well. Would you accept a PR to check for lack of `process.stdin.setRawMode` in various places and `process.exit(1)` with a friendly error?

**Comment by leo** [comment]
@mreinstein Would it be possible to rewrite [email-prompt](https://github.com/zeit/email-prompt) to support his instead of breaking right away?

**Comment by mreinstein** [comment]
> Would it be possible to rewrite email-prompt to support this

@leo it might be possible, but there several places where `process.stdin.setRawMode` is used directly:

https://github.com/zeit/now-cli/search?utf8=%E2%9C%93&q=setRawMode

Another issue that adds complexity: most `now-cli` commands don't accept input; only a handful do. The ideal solution would only prevent usage of this program when running a subcommand that relies on `setRawMode`, so the rest of the prog would still work.

I'm happy to do the grunt work on this and add the checks, but I don't want to waste my time if this is not something zeit/now folks want to solve, or if you want to solve this a different way. :)

**Comment by davemcorwin** [comment]
I'm experiencing the same issue when providing my auth token on deploy:
```
+ now deploy -n foobarbaz -t <auth token> -C
https://foobarbaz-btuzviaycb.now.sh+ now
> Error! Unexpected error. Please try later. (Authentication error – stdin lacks setRawMode support)
```

**Comment by leo** [comment]
We're happy to accept a PR for this!

**Comment by davemcorwin** [comment]
Of course! Let me make sure I understand the issue.

In my case, i'm running the `now` cli commands in a CI environment/shell that is not a tty. So there won't be any interactive input to read and I can probably just skip all calls to `process.stdin.setRawMode` if `process.stdin.isTTY === false` ([Node TTY](https://nodejs.org/api/tty.html))

Are there other situations where this would cause an issue?

**Comment by leo** [comment]
https://twitter.com/zeithq/status/930180257864437760
