### ISSUE TITLE
now dev logging is very noisy

### ISSUE THREAD

**Issue by mxstbr** [vercel/vercel#2400]
The `now dev` logs are very noisy, with lots of `ncc` logs that are not useful.

I would love for those logs to be cleaned up and be more like the Next.js or create-react-app one (auto-clearing terminal on rebuild, clear indicator of rebuild progression and status).

**Comment by leo** [comment]
Thanks for reporting. We'll solve this problem here: https://github.com/zeit/now-builders/issues/815!
