### ISSUE TITLE
Running `now dev` locally inside Docker container

### ISSUE THREAD

**Issue by wilsonpage** [vercel/vercel#2401]
When I develop locally I use docker-compose to compose all the services/databases that make-up my app. I'm attempting to migrate to Now V2, but need to be able to run now dev inside a docker container.

I'm running into an error:

/code/node_modules/.bin/now: 1: /code/node_modules/.bin/now: �����8: not found
/code/node_modules/.bin/now: 2: /code/node_modules/.bin/now: Syntax error: ")" unexpected

Is this possible … ?

**Comment by cryptiklemur** [comment]
What OS is the docker container running on?
Whats your dockerfile look like?

**Comment by wilsonpage** [comment]
OS: MacOS using Docker Mac Version 2.0.0.3 (31259)

```
FROM node:8.7

COPY package.json /tmp/package.json
RUN cd /tmp && yarn
RUN mkdir -p /code && cp -a /tmp/node_modules /code

WORKDIR /code/
COPY . /code/

CMD ["now", "dev"]
```

**Comment by leo** [comment]
We've gotten rid of the old installation mechanism. Please try `now@canary`. We'll soon push this to the stable channel too!

**Comment by ajhool** [comment]
That Dockerfile needs to be built and run each time a file changes, right?

`now dev` isn't working on Windows for me so a docker image is appealing, but I'm not too familiar with Docker for servers, my guess is that you would need to mount the local file system to the docker container?
