### ISSUE TITLE
Warn if a deployment is reaching the file count limit.

### ISSUE THREAD

**Issue by paulogdm** [vercel/vercel#2408]
Maybe the CLI could warn when a deployment is near the limit of 10000 files? Something like:
> Warning! Your deployment is generating 9000 files and it is close to the limit of 10000 files per deployment.

**Comment by barbalex** [comment]
Please do this. And thanks @paulogdm for great help in the community.

For more info on why this is important see here: https://github.com/gatsbyjs/gatsby/issues/10457#issuecomment-499671372
or here: https://spectrum.chat/zeit/general/help-i-just-hit-a-deployment-limit-during-a-critical-deployment~6c7c0fb2-4822-4a54-9a20-fd9abb3d1f21

**Comment by paulogdm** [comment]
This limit has been lifted and the CLI does not error out anymore.

**Comment by vladmarica** [comment]
Has the limit truly been lifted? It's still listed on the Vercel website: https://vercel.com/docs/v2/platform/limits/#files
