### ISSUE TITLE
[now dev] .env in tandem with next env?

### ISSUE THREAD

**Issue by nonnontrivial** [vercel/vercel#2414]
With `now dev` and `next`, when using env variables in a `.env` file and running `now dev`, I can only see the env variables on the server; they are `undefined` on the client.

The `env` field in `next.config.js` sees `process.env.MY_VARIABLE` as undefined.

How is a `.env` file intended to work in tandem with `next.config.js`?

`now dev` `15.4.0`,
`next` `8.1.0`

**Comment by khrome83** [comment]
This same thing is happening for `nuxt.config.js` (notice nuxt not next).

Using `.env.build` does not solve the issue either. Nuxt uses webpack plugin to replace `process.env.*` during build phase. But the `nuxt.config.js` is used to pass them through to webpack. But without that file recongizing them, it does not help.

So for me this seems broken for both next and nuxt.

**Comment by paulogdm** [comment]
@nonnontrivial Did you try `.env.build`?

**Comment by nonnontrivial** [comment]
@paulogdm tried, same issue.

**Comment by iamstarkov** [comment]
@paulogdm `.env.build` is afaik for building step. `now dev` doesnt require building.

**Comment by iamstarkov** [comment]
I think we need instead something like `.env.dev`

**Comment by iamstarkov** [comment]
in my side project I solved it by this [workaround](https://github.com/iamstarkov/topics-manager/blob/6e2c40de09c0536247feef3f946438547cef85cc/auth/github/index.js#L1-L4):
```js
if (process.env.NOW_REGION === "dev1") {
   // eslint-disable-next-line global-require
   require("dotenv/config");
 }
```

**Comment by khrome83** [comment]
If my experience, now dev should run the builders but locally. It’s true you can run a alternate command like “next dev”, but I would expect the same environment variables to be passed.

Including a library In production code to pull in the files on development seems like a bad practice. I want this to mirror ideal production state as much as possible. Having to maintain lab env files in more than one place is bad.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iamstarkov** [comment]
to note in my example I run `now dev` for both lambdas and next

**Comment by mattjennings** [comment]
I was able to solve this by creating a `.env.build` and then adding this to my next.config.js:

```
const webpack = require('webpack')

const nextConfig = {
  webpack(config) {
    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env.MY_CLIENT_VARIABLE': JSON.stringify(
          process.env.MY_CLIENT_VARIABLE
        )
    )

    return config
  }
}

module.exports = nextConfig
```

**Comment by paulogdm** [comment]
We have a few ideas in the pipeline at this very moment with the Next.js team cooperation and the `now dev` reboot. So I am happy to announce this will finally be resolved.

My apologies for the delay and let us know if you have any feedback: zeit.co/feedback
