### ISSUE TITLE
Cloudflare CDN is disabled somehow

### ISSUE THREAD

**Issue by amio** [vercel/vercel#2415]
We start supporting Cloudflare CDN since [last year](https://zeit.co/blog/now-cdn), it's a great feature. [Badgen](https://badgen.net) has been benefited from it since the beginning, however this feature is turned off recently somehow, is it a bug or we plan to sunset cloudflare support?

`Cloudflare Enabled` is `false` on the domain inspection panel.

![image](https://user-images.githubusercontent.com/215282/59154337-ffa74c80-8aa2-11e9-87e2-05d34507b1ed.png)

**Comment by paulogdm** [comment]
Hey @amio.
Cloudflare CDN is disabled since we've implemented our own solution: https://zeit.co/smart-cdn
We plan to reintroduce CF support as a paid add-on in the future.

Are you having issues with CDN?

**Comment by amio** [comment]
Seems the smart cdn only apply to Now v2

**Comment by leo** [comment]
The Cloudflare CDN does not exist anymore. Closing.
