### ISSUE TITLE
[now dev] 15.4.0 local server not running after compilation

### ISSUE THREAD

**Issue by coetry** [vercel/vercel#2416]
After running `now dev` from project root, no local server is started upon successful compilation. Previous talks with @TooTallNate have suggested `chokidar` to be a possible culprit (compilation completion event not firing properly for certain machines). 

<img width="698" alt="Screen Shot 2019-06-09 at 11 22 19 PM" src="https://user-images.githubusercontent.com/10926503/59172433-80029780-8b0d-11e9-902d-9c84d4feaab9.png">
<img width="1026" alt="Screen Shot 2019-06-09 at 11 22 34 PM" src="https://user-images.githubusercontent.com/10926503/59172435-81cc5b00-8b0d-11e9-94c4-634cdc54ec82.png">

**Comment by coetry** [comment]
I upgraded to `15.4.0-canary.3 dev` and the problem persists

<img width="1026" alt="Screen Shot 2019-06-09 at 11 28 46 PM" src="https://user-images.githubusercontent.com/10926503/59172565-69107500-8b0e-11e9-89ca-5fa8d26bed81.png">

**Comment by michelalbers** [comment]
same here! Tried a next.js app with Typescript, Images and CSS Plugin with 15.4.0 and 15.3.0

Stuck at

```
    Success! Builder setup complete
```

**15.2.0 works!**

@coetry try ```yarn global add now@15.2.0``` for now.

**Comment by coetry** [comment]
@michelalbers yeah `15.2.0` works for me as well. I believe its that last version that doesn't use the new file watcher.

**Comment by michelalbers** [comment]
@rauchg @coetry Issue persists with 15.5.0. on both Mac OS X Mojave and Ubuntu 19.10.

**Comment by michelalbers** [comment]
I have the feeling this has something to do with amount of files. In a smaller project everythings works just fine with 15.5.0.

**Edit:**
It is chokidar. The ready event does not fire. If you comment out this line https://github.com/zeit/now-cli/blob/c368f98dedd53a1dd978c549b6a9efbba70a0aa2/src/util/dev/server.ts#L448 it works.

Updating chokidar to @^3.0.0 does not help.

**Comment by coetry** [comment]
@michelalbers 15.5.0 seems to be working fine for me as well. Are you still experiencing problems with a particular repo? If so, can you share a link here?

**Comment by leo** [comment]
Closing. Seems to be working fine.
