### ISSUE TITLE
Now does not respect engines.npm

### ISSUE THREAD

**Issue by jutxle** [vercel/vercel#242]
I am currently attempting to deploy a vue-cli project built with the Webpack template.  By default the package.json specifies : 
```
"engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  }
```
However during the build process provided by vue-cli a version check returns the following error 
```
To use this template, you must update following to modules:
npm: 2.15.11 should be >= 3.0.0
```

I was able to get around this issue by bumping up the npm version in my package.json to
```
  "engines": {
    "node": ">= 7.0.0",
    "npm":">= 3.10.9"
  }
```

But it would be nice if ">= 3.0.0" resolved to a version of npm 3+ not 2.15.11

**Comment by leo** [comment]
If this problem still occurs, please move it over to [this repo](https://github.com/zeit/now-cloud). That's where we'll collect the bugs of the platform from now on (separate space, easier to work on)! 😊
