### ISSUE TITLE
works on now-dev but not on now.sh

### ISSUE THREAD

**Issue by conarwelsh** [vercel/vercel#2421]
I have an example that works fine using now-cli dev, but not on production.  It has to do with yarn workspaces and the now/next builder, long story short the builder is not finding a local scoped workspace package after searching the yarn registry.

That being said this problem only arose because I had to restructure the app to be able to assign aliases to the different web apps so let me try to recap as best I can:

I have a directory structure similar to this:

```
\approot
  @myscope
     shared-ui
     shared-lib
     another-shared-lib
  www
     clientWebApp
     adminWebApp
     anotherWebApp
```

originally I had a single `now.json` file in the `approot` and I could deploy OK and the monorepo structure worked fine... however there were a handful of drawbacks, the most important being that I **could not set different aliases for each web app** (clientWebApp, adminWebApp, anotherWebApp)

OK fine... I can't have a single `now.json` file in the route to handle the deploy... I will have to create a single `now.json` file for each app in the `www` folder I guess, so that I can apply a different alias to each one.  Not the worse thing in the world except for I now lose the super awesome GitHub integration you guys made with the commenting on the PR's, providing deployment links along with each commit, etc (it will be greatly missed).  

So now I have to manually kick off a deploy from my CI integration, which is actually not the worst thing in the world because now I can prevent a now-deployment from occuring according to pre-requisites such as the test suites passing.  

HOWEVER... the now/next builder is reporting   something like `unexpected error: registry.yarnpkg.com/@myscop not found` which best I can tell is because it doesn't have the symlink, or is more likely not downloading the parent folder where the symlink is pointed for the workspace.  This functionality does however work perfectly using `now dev`, it is only when I deploy from CI does it bark.

Frankly my main concern is adding a different alias to each of the apps in the `www` folder, so if there is a better way to handle that using the single `approot` level `now.json` then I will be a very happy camper and we can forget this whole issue.  However it should maybe be noted that now dev and production are not mimicking each other.

Thanks for the awesome work!  I can provide any more info needed.

**Comment by tsaiDavid** [comment]
My goodness - this is super similar to what my team and I struggled with the last couple days... tagging @dmi3y for visibility. Long story short, we weren't getting great parity that we had come to experience with using `now dev` and the actual builds - and wish that there is better support and orchestration of monorepos!

Summary of our experiences:
- Have a Lerna + Yarn Workspaces monorepo (shared libs, several NextJS apps)
- Each web app has its own `now.json` file as mentioned by @conarwelsh 
- Local usage of `now dev` "worked", and we could deploy from our respective machines using the `now` CLI (canary and non)
- Problem: CircleCI had been working just fine, but the builds on Zeit would just hang after we introduced a new app

**Comment by rauchg** [comment]
@tsaiDavid thanks for re-surfacing this. We'll do a deep dive on this issue soon.

**Comment by tsaiDavid** [comment]
@rauchg - No problem, happy to provide more details if needed!

**Comment by TooTallNate** [comment]
> best I can tell is because it doesn't have the symlink, or is more likely not downloading the parent folder where the symlink is pointed for the workspace

This is exactly what is happening. Since the `now.json` files are within the `www` subdirectories, only those files are uploaded to the deployment. I suggest you move those `now.json` files to the `approot` and give them a unique name, per-app (so like `clientWebApp-now.json` or similar). Then you can invoke `now --local-config=clientWebApp-now.json` from the `approot` directory in order to have all the files from `@myscope` be uploaded as well.

> This functionality does however work perfectly using `now dev`, it is only when I deploy from CI does it bark.

The fact that `now dev` works is basically just an unfortunate side effect of the fact that `now dev` utilizes the existing working directory for running your application, as opposed to copying the relevant files to a scratch space. In fact, `now dev` originally did do this copying and so you would have run into the same issue, but we decided to make this tradeoff for performance reasons (i.e. very close to production behavior with a good developer experience outweighs 100% replication of production environment).

Let me know if makes sense, or if I can explain anything else!

**Comment by dmi3y** [comment]
@TooTallNate this is setup we have on our end which is working fine 👍 We do had operational missing step that threw us for a while, but it also surfaced details you might be interested in. I'm going link [spectrum](https://spectrum.chat/zeit/now/now-nextjs-monorepo-deploy-suddenly-stoped-working~7f23d944-f649-4c56-9e49-035e1e32e8db) message of details what @tsaiDavid described above. Let me know if you will need additional information or tests on my end. Thank you guys!
