### ISSUE TITLE
now logs with --since and --until not working

### ISSUE THREAD

**Issue by eAi** [vercel/vercel#2424]
When specifying a time with now logs using `--since` or `--until`, neither produce the result I expect.

This has the same effect as if --since isn't specified, showing the most recent logs
`now logs --since=2019-06-11T01:00:00.000Z <alias> `

This has no effect - no logs are shown:
`now logs --until=2019-06-11T01:00:00.000Z <alias>`

Quotes around the time make no difference. 

This bug makes working backwards through logs to find something effectively impossible.

Additionally, specifying the number of lines to output produces incorrect results in my current state:
`-n 200` returns 199 results 
`-n 1000` returns 990 results
`-n 990` returns 980 results
`-n <any number over 1000>` returns 990 results

**Comment by eAi** [comment]
No response to this? Should I contact support@ instead?

**Comment by eAi** [comment]
Additionally, --query doesn't appear to do anything - it always returns the most recent log entries.

**Comment by paulogdm** [comment]
Hello @eAi ,

Yes, reaching out to us at support is always the best approach. My apologies for the delay.
Regarding logs, I believe [log drains](https://zeit.co/blog/log-drains) is the best alternative for what you need to achieve.

If you have any further questions, please ask them on zeit.co/support
