### ISSUE TITLE
now deploy hangs forever on travis-ci

### ISSUE THREAD

**Issue by dsifford** [vercel/vercel#243]
Hi there, Pro subscriber here! 🙌 

I'm having some trouble getting a `now` deploy script to exit on Travis-CI. Running the script locally works just fine, but on travis, it consistently will not finish.

[On this line](https://github.com/zeit/now-cli/blob/cb8403174b2807ff5884ac6b64630c6e7d44f393/bin/now-deploy.js#L150) it states that you've had some issues with stdout not flushing and it looks like that function [isn't being used here](https://github.com/zeit/now-cli/blob/cb8403174b2807ff5884ac6b64630c6e7d44f393/bin/now-deploy.js#L613), where I think the issue might be originating.

Here's one of the failed builds for reference: https://travis-ci.org/aliemteam/aliemcards/builds/195055148#L347

Here's the deploy script that I'd like to use: https://github.com/aliemteam/aliemcards/blob/master/deploy
(Side Note: I'm aware of your node library, but the cli tool is way easier to use for my purposes)

Thanks so much for the help and all you've done for the OSS community! Let me know if there's anything I might be able to assist with.

**Comment by dsifford** [comment]
Disregard. The issue came down to being me forgetting to feed in the `-t TOKEN` to one of the now calls. 😖

**Comment by matheuss** [comment]
Great to know @dsifford 🙌 🎉

**Comment by dsifford** [comment]
Yep.. just noticed it a few minutes ago and facepalmed pretty hard! 

There was no message printed to stdout for the "failure" because there really was never any failure happening, but rather the program was just running as a background process waiting to receive an email address.

For purposes of helping someone in the future who may have made the same mistake I did, you can find the issue on [this line specifically](https://github.com/aliemteam/aliemcards/blob/be4bc2a126dc0642cf9cac7b60bfd0508850c0f6/deploy#L19).

But, had that mistake not been made on that line, it would have been made again on line 27. 😝

**Comment by kristianmandrup** [comment]
Any idea about this #548 ??
