### ISSUE TITLE
[now dev]  can't reach API lambdas on server render

### ISSUE THREAD

**Issue by johnbrett** [vercel/vercel#2431]
I have create a small repo to replicate the issue I'm having: https://github.com/johnbrett/next-serverless-monorepo

When I use `now dev` to run my monorepo, the nextjs server render can't locate the API lambda, giving an error of `connect EHOSTUNREACH 0.0.11.184:80 - Local (192.168.1.66:50818)`

I think the issue is the url I'm using, is there some token or env var I should be using here: https://github.com/johnbrett/next-serverless-monorepo/blob/master/www/pages/index.js#L6

e.g. `const res = await axios('${LAMBDA_LOCATION}/api/test.js');`

I've tried:
- `/api/test.js` // expected to fail
- `localhost:3000/api/test.js` // expected to work as it's a valid url

Screenshot:
![image](https://user-images.githubusercontent.com/4015939/59556608-d9127580-8fbc-11e9-8c47-4fa698933707.png)

I think this may be related to: https://github.com/zeit/now-cli/issues/2371

**Comment by leo** [comment]
Related: https://twitter.com/notquiteleo/status/1143306376896233472

**Comment by johnbrett** [comment]
My issue was not prefixing with `http://` 🤦‍♂, browsers can handle this, but not server requests, thank you @leo!!
