### ISSUE TITLE
[request] allow local builder, without publish it to npm

### ISSUE THREAD

**Issue by bluelovers** [vercel/vercel#2435]
[request] allow local builder, without publish it to npm

this help if we wanna make a new builder or fork a exists one

without publish for test work

**Comment by styfle** [comment]
The builders don't have any code preventing local development. This change would need to be made in the CLI to support something equivalent to `npm link` so that `use: @now/node` would be symlinked.

Maybe something like `now dev --link '@now/node' '/Users/foo/code/now-node'`

**Comment by kevva** [comment]
You can do `"use": "file:/path/to/my-builder"` since it uses Yarn under the hood.

**Comment by TooTallNate** [comment]
I confirmed that @kevva's recommendation of using a `file:` URI works as expected.
