### ISSUE TITLE
'now dev' doesn't work properly for Next.js

### ISSUE THREAD

**Issue by PabloSzx** [vercel/vercel#2442]
`now dev` doesn't seem to work properly for Next.js, tested in two Windows machines with this basic code https://github.com/PabloSzx/Next.js-Now-TypeScript and on production (cloud deployment) (https://nextjs.pablosz.now.sh/) works perfectly fine.
![Hyper_uNinQjfHqf](https://user-images.githubusercontent.com/8672915/59750664-21e05d80-924d-11e9-8c01-2cdd722108c9.png)

It seems to be an internal proxy problem, because when i run it debug mode `now dev -d`:

This is when the local server says 404: The page could not be found
![Hyper_efK24T9EBx](https://user-images.githubusercontent.com/8672915/59751005-c367af00-924d-11e9-92e2-6758553338dd.png)

This is when the local server makes the proxy to the Next.js server properly
![Hyper_MNnLW7tajw](https://user-images.githubusercontent.com/8672915/59751105-f3af4d80-924d-11e9-9980-748d4f2577d4.png)

**Comment by PabloSzx** [comment]
I needed a workaround for local development, so i made a second version of `now.json` where all the routes destinations have `http://localhost:5000` before.

But before deployment i switch both versions of `now.json`

```javascript
"routes": [
    ...
    { "src": "/(.*)", "dest": "http://localhost:5000/$1" }
  ]
```

**Comment by PullJosh** [comment]
Possibly related to #2385? 😉

**Comment by PabloSzx** [comment]
It seems to be the same reason it doesn't work, but i discovered it using the routes configuration in now.json 😅
A workaround is using windows subsystem for Linux and running `now dev` there

**Comment by PabloSzx** [comment]
It works fine in Windows now, at least in Now CLI 16.1.1
