### ISSUE TITLE
Track correspondence between a Now deployment and git commit hash

### ISSUE THREAD

**Issue by sedubois** [vercel/vercel#245]
While I'm troubleshooting a Now deployment by deploying various versions from my Git history (kind of doing git bisect), I find it difficult to track which Now URL corresponds to which software version.

It could be very helpful to keep track of and display this information e.g in the `now ls` command and somewhere in the source code available at `/_src`.

**Comment by matheuss** [comment]
@sedubois you're talking about git tags? If yes, then maybe you could use some ugly hack like this one:
```
▲ test at master ✔ git tag
1.0.0
▲ test at master ✔ now --name "$(basename $(pwd))-$(git describe --tags)"
> Deploying ~/dev/zeit/tmp/test
> Using Node.js 7.0.0 (default)
> Ready! https://test-100-qkbrqmizbr.now.sh (copied to clipboard) [1s]
```
😅

**Comment by jamo** [comment]
one idea could be to use the `git sha` in part of the autogenerated cryptographically strong section of the unique url. it could be a neat opt-in feature 🤔

**Comment by sedubois** [comment]
How about simply taking the git sha (and whatever else Now uses to uniquely identify a build) and put it in the manifest or some location where it can easily be browsed? In a subsequent feature it could then also be nicely displayed in now ls.

But sure it would be even cooler if the URL simply contained the git SHA (at least for those cases where there is no conflict)!

**Comment by leo** [comment]
There are various way of versioning code. Of course `git` is the best atm, but definitely not the only one. Also what about the dir not being a repo at all? The list would look very cluttered.

**Comment by steida** [comment]
Something like this:

`process.env.appVersion = execSync('git rev-parse HEAD').toString().trim();`

**Comment by sedubois** [comment]
@steida agreed. And if not defined Now could fallback to `require('./package.json).version` (or users could even combine these things in a string themselves).

Then Now can simply display this string for each deployment in the dashboard (and make it available through API/CLI).

@leo could we reopen and discuss this? Right now there's just no way to keep track of what code version is deployed.

**Comment by steida** [comment]
I think it should be passed through env variable.

**Comment by steida** [comment]
`now -e NODE_ENV=production -e appVersion=3d225ebc8b7e993311dbb6bd070a61516caffbc4`

**Comment by sedubois** [comment]
Yes although there should be a simple way so that people don't have to type a long command every time.

How about adding something like this to `package.json`?

```
"now": {
    "appVersion": "git rev-parse HEAD"
  },
```

**Comment by matheuss** [comment]
@steida passing the version as an env variable to the deployment doesn't makes sense in this context – unless your app will use the version.
Something like `now --deploymentVersion=stuff` would make more sense, like @sedubois suggested (although I don't like `appVersion` nor `deploymentVersion` 😓)

**Comment by sedubois** [comment]
`codeVersion`, `releaseVersion`?

**Comment by steida** [comment]
@matheuss It uses it, for errors and crashes reporting.

**Comment by jamo** [comment]
I think adding support for arbitrary tags/labels would be more effective and scalable solution. + neat helper to automatically add tags/labels based on common VCS systems.

**Comment by sedubois** [comment]
> support for arbitrary tags/labels

I like that idea

**Comment by sedubois** [comment]
```
  "now": {
    "labels": {
      "appVersion": "git rev-parse HEAD"
    }
  }
```

**Comment by leo** [comment]
IMO, you should increment the version tag in `package.json` and load it from there. If you don't have that file, simply create another JSON file.

**Comment by jamo** [comment]
It doesn't scale, like us prototyping zeit.co... you don't all the time edit package.json...

**Comment by leo** [comment]
@jamo I don't get it. Works just fine for us internally (see the console on zeit.co)? 😄

**Comment by leo** [comment]
With our [GitHub integration](https://zeit.co/blog/easier-now-github), this is now possible. You can also use [Deployment metadata](https://zeit.co/blog/deployment-metadata)! 😊

**Comment by danoc** [comment]
Here is the direct link to the environment variables relevant to this topic:
https://zeit.co/docs/v2/integrations/now-for-github/#included-environment-variables

**Comment by dgattey** [comment]
@Leo / @danoc sorry to revive this old thread - my question is specific to tags. Is there any way to put `git describe --tags` or some variation thereof into a system environment variable?
![image](https://user-images.githubusercontent.com/982182/116324695-6d32f380-a775-11eb-83b9-5abc8e4fdeb5.png)

Right now I only see commit SHA/message/etc, not the latest tag. My guess is this is done for performance reasons, but it makes my "pulling in the version" workflow a lot harder. If there's a way or a way for that to be built, I'd love to hear about it! Thanks.
