### ISSUE TITLE
Add support for now.js files

### ISSUE THREAD

**Issue by lededje** [vercel/vercel#2451]
I would like to be able to specify my configuration as multiple json files, and the best way I can think of doing this is to allow configuration files to be js files.

I realise this is a similar to #1673 but with the specific intention to allow you to split up you configuration into different files. My use case is to have now configurations in separate directories of a monorepo and each be run with in a docker container with docker compose, but when they are ready to go into production, those configs be smooshed into one with a root config js file.

**Comment by paulogdm** [comment]
We are working on something like this. I will close this issue when we release it...

**Comment by leo** [comment]
Thanks for the effort you've put into researching this, but I think the project is already way too complex. In turn, I don't think it's good idea to support such an edge case.

I hope you understand that! 😊

**Comment by olistic** [comment]
Hello @leo, one question: I have many customers sharing the same codebase, and I chose Now for deploying my app. Right now I have multiple `now.<customer_id>.json` files that share a lot of stuff, which I was hoping to consolidate in a JS config.

If you're not going to implement this, should I resume my efforts of creating a script to generate a `now.json` file dynamically? Or is there something in the roadmap targeting my (IMO not that edgy) case.
