### ISSUE TITLE
Custom 404 error page; dest not working if status is set

### ISSUE THREAD

**Issue by thomasjsn** [vercel/vercel#2453]
I'm trying to define a custom 404 error page with the following routes in `now.json`:

```
"routes": [
  { "handle": "filesystem" },
  { "src": "/.*", "dest": "/404.html", "status": 404 }
]
```

But it doesn't work as expected.

* If `status` is set, the `dest` page is not shown.
* If `status` is **not** set; the `dest` page is shown, but with a status code of 200. Which is no good for a 404 error page.

It seems that the behaviour when having both `dest` and `status` has recently changed — previously I wasn't allowed, receiving the follow error message: `Cannot use both status and dest`.

Use usage of both `dest` and `status` is used in this documentation example: https://zeit.co/docs/v2/routing/directory-listing/

**Comment by paulogdm** [comment]
We just fixed this. Thanks for the report @thomasjsn
