### ISSUE TITLE
[now dev] Add ability to clear cache

### ISSUE THREAD

**Issue by kevva** [vercel/vercel#2459]
When developing builders locally, I use `file:/path/to/my-builder` in the `use` field of `now.json`. However, after removing/renaming the folder it still references the old path in `package.json` in the builder cache directory which causes `now dev` to fail even if the builder isn't used.

To resolve this, it'd be nice to have a flag that'd clear the `package.json` and remove the `node_modules` directory in the builder cache.

**Comment by TooTallNate** [comment]
I can't seem to reproduce this. To wit:

1. ```
    $ cat now.json | grep index
    { "src": "index.js", "use": "file:/path/to/now-node" }
    ```
1. Boot up `now dev --debug`
1. Go to http://localhost:3000 to build the lambda, see:
    ```
    > Built file:/path/to/now-node:index.js [2s]
    ```
1. Check cached builder's `package.json`:
    ```
    $ cat ~/Library/Caches/co.zeit.now/dev/builders/package.json | grep now/node
    "@now/node": "file:/path/to/now-node",
    ```
1. Change the builder to another file path:
    ```
    $ cat now.json | grep index
    { "src": "index.js", "use": "file:/path/to/now-node2" }
    ```
1. Reload the browser page to re-build the lambda with the new builder. See:
    ```
    > Built file:/path/to/now-node2:index.js [2s]
    ```
1. Check cached builder's `package.json` again:
    ```
    $ cat ~/Library/Caches/co.zeit.now/dev/builders/package.json | grep now/node
    "@now/node": "file:/path/to/now-node2",
    ```

All good, ya? Open a new issue if I'm missing something.

**Comment by kevva** [comment]
What if you rename/remove the builder directory while stile referencing the old path in the `use` field? That's what caused the error for me.
