### ISSUE TITLE
Now doesn't always deploy the same code to the same URL

### ISSUE THREAD

**Issue by sedubois** [vercel/vercel#246]
I'm troubleshooting an issue in my code or deployment, and therefore checking out various Git versions then deploying them with `now`. However I was surprised that when coming back to the same revision and deploying again, it redeployed completely instead of detecting it was the same as previously deployed.

- checked out 36775df, deployed at https://relate-opqnyxoqdv.now.sh/
- checked out and deployed two other revisions
- checked out 36775df again, got deployed at https://relate-ygwmpihxux.now.sh (different from URL above)

(code: https://github.com/relatenow/relate)

**Comment by pablopunk** [comment]
Just a question

Why would you want to deploy again the same commit? Should be the same code 🤔

**Comment by sedubois** [comment]
Exactly, it is the same code, so it should be the same URL 😄 I was trying to deploy the same commit several times because I was troubleshooting some weird bug in Now (been discussing with jamo about that).

**Comment by matheuss** [comment]
@sedubois I see (`/_src`) that you have `.idea` there. Maybe something changed there? 😄

**Comment by sedubois** [comment]
Ah good point! I just recently understood that Now doesn't read .gitignore when there's an .npmignore. That's fixed so will reopen if happens again 😊
