### ISSUE TITLE
[now dev] webpack build failing missing deps?

### ISSUE THREAD

**Issue by remy** [vercel/vercel#2465]
I've been converting an express app (by pulling out the routes separately) - but there's a route that explodes in a strange way with `now dev` - yet builds fine in production.

<details>
<summary>This is the error</summary>
<div><pre><code>
Hash: 289aa8f677ba4bf90c6d
Version: webpack 5.0.0-alpha.9
Time: 6754ms
Built at: 2019-06-26 17:59:49
          Asset      Size  Chunks  Chunk Names
code-points.mem   410 KiB
       index.js  3.65 MiB   {404}  main
   index.js.map   630 KiB   {404}  main
Entrypoint main = index.js index.js.map
 [39] ./node_modules/passport/lib/sessionmanager.js 867 bytes {404}
 [64] external "util" 42 bytes {404}
 [68] ./node_modules/passport-strategy/lib/index.js 223 bytes {404}
[273] ./node_modules/request/index.js 3.88 KiB {404}
[443] ./node_modules/cookie/index.js 3.88 KiB {404}
[455] ./node_modules/passport/lib/authenticator.js 13.1 KiB {404}
[472] ./node_modules/lodash.get/index.js 22.8 KiB {404}
[484] ./node_modules/passport-strategy/lib/strategy.js 567 bytes {404}
[591] ./lib/routes/auth/github.js 729 bytes {404} [built]
[612] ./node_modules/pause/index.js 595 bytes {404}
[872] ./node_modules/passport/lib/index.js 474 bytes {404}
[885] ./lib/strategy.js 1.25 KiB {404} [built]
[894] ./node_modules/passport/lib/strategies/session.js 2.04 KiB {404}
[898] ./lib/db/user.js 5.11 KiB {404} [built]
[988] ./node_modules/passport-github2/lib/index.js 223 bytes {404}
    + 518 hidden modules

ERROR in ./node_modules/ajv/lib/ajv.js 10:22-40
Module not found: Error: Can't resolve './$data' in '/Users/remy/Sites/jsonbin/node_modules/ajv/lib'
 @ ./node_modules/har-validator/lib/promise.js 1:10-24
 @ ./node_modules/request/lib/har.js 5:15-39
 @ ./node_modules/request/request.js 23:10-30
 @ ./node_modules/request/index.js 143:18-38
 @ ./lib/strategy.js 4:16-34
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/ajv/lib/ajv.js 11:20-46
Module not found: Error: Can't resolve './patternGroups' in '/Users/remy/Sites/jsonbin/node_modules/ajv/lib'
 @ ./node_modules/har-validator/lib/promise.js 1:10-24
 @ ./node_modules/request/lib/har.js 5:15-39
 @ ./node_modules/request/request.js 23:10-30
 @ ./node_modules/request/index.js 143:18-38
 @ ./lib/strategy.js 4:16-34
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/ajv/lib/ajv.js 448:18-46
Module not found: Error: Can't resolve './refs/$data.json' in '/Users/remy/Sites/jsonbin/node_modules/ajv/lib'
 @ ./node_modules/har-validator/lib/promise.js 1:10-24
 @ ./node_modules/request/lib/har.js 5:15-39
 @ ./node_modules/request/request.js 23:10-30
 @ ./node_modules/request/index.js 143:18-38
 @ ./lib/strategy.js 4:16-34
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/ajv/lib/compile/rules.js 3:18-37
Module not found: Error: Can't resolve './_rules' in '/Users/remy/Sites/jsonbin/node_modules/ajv/lib/compile'
 @ ./node_modules/ajv/lib/ajv.js 9:12-38
 @ ./node_modules/har-validator/lib/promise.js 1:10-24
 @ ./node_modules/request/lib/har.js 5:15-39
 @ ./node_modules/request/request.js 23:10-30
 @ ./node_modules/request/index.js 143:18-38
 @ ./lib/strategy.js 4:16-34
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js 4:12-33
Module not found: Error: Can't resolve './defer.js' in '/Users/remy/Sites/jsonbin/node_modules/form-data/node_modules/combined-stream/lib'
 @ ./node_modules/form-data/lib/form_data.js 1:21-47
 @ ./node_modules/request/request.js 15:15-35
 @ ./node_modules/request/index.js 143:18-38
 @ ./lib/strategy.js 4:16-34
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/aggregate.js 8:16-54
Module not found: Error: Can't resolve './services/cursor/eachAsync' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 23:16-38
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/cursor/QueryCursor.js 7:16-55
Module not found: Error: Can't resolve '../services/cursor/eachAsync' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib/cursor'
 @ ./node_modules/mongoose/lib/query.js 8:18-49
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/document.js 19:28-80
Module not found: Error: Can't resolve './services/document/cleanModifiedSubpaths' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 14:15-36
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/document.js 20:14-52
Module not found: Error: Can't resolve './services/document/compile' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 14:15-36
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/document.js 28:14-42
Module not found: Error: Can't resolve './services/common' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 14:15-36
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/model.js 16:17-55
Module not found: Error: Can't resolve './services/model/applyHooks' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 13:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/model.js 17:19-59
Module not found: Error: Can't resolve './services/model/applyMethods' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 13:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/model.js 18:19-59
Module not found: Error: Can't resolve './services/model/applyStatics' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 13:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/model.js 20:17-55
Module not found: Error: Can't resolve './services/query/castUpdate' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 13:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/model.js 21:20-61
Module not found: Error: Can't resolve './services/model/discriminator' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 13:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/model.js 22:30-86
Module not found: Error: Can't resolve './services/projection/isPathSelectedInclusive' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 13:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/model.js 27:26-67
Module not found: Error: Can't resolve './services/setDefaultsOnInsert' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 13:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/promise_provider.js 5:15-35
Module not found: Error: Can't resolve './promise' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 24:22-51
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/promise_provider.js 36:21-44
Module not found: Error: Can't resolve './ES6Promise' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 24:22-51
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/query.js 9:18-42
Module not found: Error: Can't resolve './querystream' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/query.js 11:17-55
Module not found: Error: Can't resolve './services/query/castUpdate' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/query.js 12:20-61
Module not found: Error: Can't resolve './services/query/hasDollarKeys' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/query.js 14:18-62
Module not found: Error: Can't resolve './services/projection/isInclusive' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/query.js 16:15-35
Module not found: Error: Can't resolve './drivers' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/query.js 17:28-77
Module not found: Error: Can't resolve './services/query/selectPopulatedFields' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/query.js 18:26-67
Module not found: Error: Can't resolve './services/setDefaultsOnInsert' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/query.js 20:23-61
Module not found: Error: Can't resolve './services/updateValidators' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 12:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/schema.js 5:15-35
Module not found: Error: Can't resolve './drivers' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib'
 @ ./node_modules/mongoose/lib/index.js 7:13-32
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/schema/documentarray.js 14:20-62
Module not found: Error: Can't resolve '../services/model/discriminator' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib/schema'
 @ ./node_modules/mongoose/lib/schema/index.js 12:24-50
 @ ./node_modules/mongoose/lib/schema.js 1922:31-56
 @ ./node_modules/mongoose/lib/index.js 7:13-32
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/schema/embedded.js 12:20-62
Module not found: Error: Can't resolve '../services/model/discriminator' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib/schema'
 @ ./node_modules/mongoose/lib/schema/index.js 14:19-40
 @ ./node_modules/mongoose/lib/schema.js 1922:31-56
 @ ./node_modules/mongoose/lib/index.js 7:13-32
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/types/array.js 8:28-81
Module not found: Error: Can't resolve '../services/document/cleanModifiedSubpaths' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib/types'
 @ ./node_modules/mongoose/lib/document.js 886:38-62
 @ ./node_modules/mongoose/lib/index.js 14:15-36
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/types/buffer.js 5:13-34
Module not found: Error: Can't resolve '../drivers' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib/types'
 @ ./node_modules/mongoose/lib/types/index.js 7:17-36
 @ ./node_modules/mongoose/lib/index.js 11:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/lib/types/objectid.js 11:15-36
Module not found: Error: Can't resolve '../drivers' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/lib/types'
 @ ./node_modules/mongoose/lib/utils.js 6:15-42
 @ ./node_modules/mongoose/lib/index.js 15:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/mongoose/node_modules/async/internal/parallel.js 16:12-29
Module not found: Error: Can't resolve './rest' in '/Users/remy/Sites/jsonbin/node_modules/mongoose/node_modules/async/internal'
 @ ./node_modules/mongoose/node_modules/async/parallel.js 12:16-46
 @ ./node_modules/mongoose/lib/model.js 25:15-40
 @ ./node_modules/mongoose/lib/index.js 13:12-30
 @ ./node_modules/mongoose/index.js 7:17-34
 @ ./lib/db/index.js 1:17-36
 @ ./lib/db/user.js 1:17-35
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/shortid/lib/build.js 3:13-32
Module not found: Error: Can't resolve './encode' in '/Users/remy/Sites/jsonbin/node_modules/shortid/lib'
 @ ./node_modules/shortid/lib/index.js 6:12-30
 @ ./node_modules/shortid/index.js 2:17-39
 @ ./lib/db/user.js 5:16-34
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/shortid/lib/index.js 4:13-32
Module not found: Error: Can't resolve './encode' in '/Users/remy/Sites/jsonbin/node_modules/shortid/lib'
 @ ./node_modules/shortid/index.js 2:17-39
 @ ./lib/db/user.js 5:16-34
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48

ERROR in ./node_modules/shortid/lib/index.js 5:13-32
Module not found: Error: Can't resolve './decode' in '/Users/remy/Sites/jsonbin/node_modules/shortid/lib'
 @ ./node_modules/shortid/index.js 2:17-39
 @ ./lib/db/user.js 5:16-34
 @ ./lib/strategy.js 2:13-33
 @ ./lib/routes/auth/github.js 4:23-48
</code></pre></div>
</details>

This happens with now@15.6.0-canary.3 and my repo at this commit: https://github.com/remy/jsonbin/commit/b88273ebb45de0bb4423a716e745c3d9c6e7794a

To replicate - clone the repo above, checkout the serverless branch and that commit #b88273ebb45de0bb4423a716e745c3d9c6e7794a and run `now dev`. Then visit http://localhost:3000/_/auth/github

I'm testing with node@8.10.0 (also tried node@10 - same issue).

**Comment by styfle** [comment]
Hi @remy 

I tried this out with the latest Now CLI and I get a different error message in both `now dev` and production deployment: 

```
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
```

Are you still having issues with this one?

**Comment by paulogdm** [comment]
This issue has been closed due to inactivity. If you need further assistance, please get in touch with support: zeit.co/support
