### ISSUE TITLE
this project is die ?

### ISSUE THREAD

**Issue by fdciabdul** [vercel/vercel#2469]
ding Now CLI 15.6.1 [                    ] 0%
Error: Not Found https://github.com/zeit/now-cli/releases/download/15.6.1/undefined.gz
    at dist_default.retries 
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by paulogdm** [comment]
Can you give us the following:
1- `now update --debug`.
2- Your OS with version.

**Comment by fdciabdul** [comment]
i can't install it , my OS Debian 5.0.7

**Comment by paulogdm** [comment]
How are you trying to install it?

**Comment by fdciabdul** [comment]
just npm install -g now

and stuck in 

Now CLI 15.6.1 [ ] 0%
Error: Not Found https://github.com/zeit/now-cli/releases/download/15.6.1/undefined.gz

Or my os is broken ?

**Comment by paulogdm** [comment]
Can you do `npm i -g standard`?

**Comment by paulogdm** [comment]
Did you try `curl -sfLS https://zeit.co/download.sh | sh`?

**Comment by fdciabdul** [comment]
thank you  this is work now ,
