### ISSUE TITLE
`now` works but `now dev` doesn't

### ISSUE THREAD

**Issue by projeffboy** [vercel/vercel#2476]
Hey, I have this simple project, that contains `index.html`, `folder/`, and `folder/index.html`.
When I run `now` to deploy it to the cloud, everything works.
But when I run `now dev` to deploy it locally, accessing `folder/` or `folder/index.html` gives me this error:
```
404: The page could not be found
Code: FILE_NOT_FOUND
```

I don't have a now.json, so everything is served statically.

**Comment by TooTallNate** [comment]
Thanks for the report @projeffboy. I can reproduce.

**Comment by maitham1** [comment]
Also getting this error : FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory

**Comment by TooTallNate** [comment]
This was fixed by https://github.com/zeit/now-cli/pull/2528.
