### ISSUE TITLE
[request] allow trigger a new build by target project id

### ISSUE THREAD

**Issue by bluelovers** [vercel/vercel#2481]
allow trigger a new build by target project id

current `now deploy` require we inside a project root or set path

but i hope can have a cmd, is `now build project_id` and can use in any where

this is help if we just wanna trigger a new build and didn't change source
or something make build is fail, but we not stand near our project source
or we wanna do some task/schedule for trigger re-build

and hope can do this in oauth way too

**Comment by paulogdm** [comment]
Hello,

You can now achieve this with "deploy hooks": https://zeit.co/blog/introducing-deploy-hooks.
If you are not using the GitHub integration,  however, then I am afraid this is not possible.

If you have any questions, reach out to us on support@zeit.co
