### ISSUE TITLE
Is libvips present?

### ISSUE THREAD

**Issue by ramiel** [vercel/vercel#2484]
On now v1 libvips is available and so we can use libraries like [sharp](https://sharp.pixelplumbing.com). On now v2 I get this error instead:

```
Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory
```

which make me think the library is not available. Is there a way to fix this?

**Comment by styfle** [comment]
I can confirm that `sharp` works now and we have a test fixture here: https://github.com/zeit/now/tree/master/packages/now-node/test/fixtures/30-sharp
