### ISSUE TITLE
running npm install in container is failing

### ISSUE THREAD

**Issue by kuldeepkeshwar** [vercel/vercel#2486]
I have an endpoint which runs `npm install` in a temp directory when hit. 

It is failing with below error 
``` 
2019-07-01T11:35:30.964Z	c7913fa3-e4dc-4fe5-8571-29b24d5f209c	INFO	running npm install in temp dir
npm ERR! path /home/sbx_user1051
npm ERR! code EROFS
npm ERR! errno -30
npm ERR! syscall mkdir
npm ERR! rofs EROFS: read-only file system, mkdir '/home/sbx_user1051'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.
2019-07-01T11:35:32.896Z	c7913fa3-e4dc-4fe5-8571-29b24d5f209c	ERROR	{ Error: Command failed: /bin/sh -c npm install --no-bin-links
    at makeError (/var/task/index.js:55152:9)
    at Promise.all.then.arr (/var/task/index.js:55256:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 226,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: '/bin/sh -c npm install --no-bin-links',
  timedOut: false,
  killed: false }
```

The error says `don't support symlinks`. can anyone help? 
I even tried running `npm install` with `--no-bin-links` flag. Same result.

**Comment by TooTallNate** [comment]
Inside the Lambda environment, only the `/tmp` directory is writable. But it appears that you are trying to write to the home directory (`/home/sbx_user1051`) instead.

Please create your temporary directory inside of the `/tmp` directory and run `npm install` within that location.

**Comment by kuldeepkeshwar** [comment]
@TooTallNate i think I was trying to run `npm install` inside the `tmp` only
