### ISSUE TITLE
Custom dotenv file

### ISSUE THREAD

**Issue by jerrygreen** [vercel/vercel#2487]
I've seen [this message](https://github.com/zeit/now-cli/issues/362#issuecomment-283752470), and I've tried to use a custom dotenv file - but it doesn't work.

**AND**, actually, I think it should be array of strings, so I may do it like this:

```json
{
  "dotenv": [".env.default", ".env"]
}
```

**Comment by markozxuu** [comment]
Hi @JerryGreen  👋, the use of `dotenv` is not recommended. if you want to use **Environment Variables** the idea would be to make the following adjustment in your `now.json`

```
{
  "env": {
    "DATABASE_NAME": "test"
  }
}
```

more info [here](https://zeit.co/docs/v2/development/environment-variables/) :)

**Comment by 59023g** [comment]
However, `now dev` uses `.env` See: https://zeit.co/docs/v2/development/basics

**Comment by jerrygreen** [comment]
Yea, after a while I got this working with `now dev`:

```
{
  "dotenv": ".env.default"
}
```

But the point is that I want to pass two of them:

```
{
  "dotenv": [".env.default", ".env"]
}
```

1. `.env.default` - some vars to get repo working out of the box, to minimize setup (it lives in repo code)
2. `.env` - some personal values for each dev, it's in `.gitignore`

Btw, why `dotenv` is not recommended?

**Comment by jerrygreen** [comment]
Closing this bc it's better formulated here: https://github.com/zeit/now-cli/issues/2531
