### ISSUE TITLE
`now ls` should only show deployments of current app

### ISSUE THREAD

**Issue by leo** [vercel/vercel#249]
`--all` for all

**Comment by jamo** [comment]
`now ls app-name` works atm...
and I guess if there is no apps for that project name (app haven't been deployed) it should just show all?

**Comment by leo** [comment]
@jamo Let's default to that. Also:

> And I guess if there is no apps for that project name (app haven't been deployed) it should just show all?

> Yep. But not without telling the user. Otherwise he might be confused about seeing deployments for an app that doesn't have deployments yet.

**Comment by leo** [comment]
https://github.com/zeit/now-cli/issues/249#issuecomment-275193844
