### ISSUE TITLE
Can't deploy static javascript `.js` files

### ISSUE THREAD

**Issue by pablopunk** [vercel/vercel#2494]
`15.7.0-canary.7`

Hi, let's say I have a project like:

```
+- index.js
|
+- files/
        |
        +- index.js
        |
        +- foo.ts
        |
        +- bar.js
```

and I deploy it with the following config (now.json):

```json
{
  "version": 2,
  "builds": [
     { "src": "index.js", "use": "@now/node" },
     { "src": "files/**", "use": "@now/static" }
 ],
  "routes": [
     { "src": "/.*", "dest": "/index.js" }
 ]
}
```

But as far I can see (confirmed with `now dev`), it will only deploy "statically" the typescript files. If I try to find my files from the code in `index.js` I can see the typescript files there but not the javascript files, they just dissapear (don't get deployed I guess). If I rename them like `bar.ts` they do get deployed.

Notice I do not want to access them via http (see `routes` config). I just want to load them with `fs` from `index.js`

**Comment by TooTallNate** [comment]
Could you share the contents of your `index.js` file (or better yet, create a GH repo to show the issue)?

**Comment by pablopunk** [comment]
@TooTallNate sure, I made this example just now https://now-issue-2494.pablopunk.now.sh/_src (deployed with `now --public`)

**Comment by pablopunk** [comment]
Notice that when you visit https://now-issue-2494.pablopunk.now.sh with any url (that doesn't contain `secret`) it will show you the contents of `default.ts`. But if you visit  https://now-issue-2494.pablopunk.now.sh/secret, you get a 404

**Comment by TooTallNate** [comment]
Ok so it seems like you want those `files` to be _inside_ of your lambda function. Therefore, the `@now/static` usage in your builds configuration is not necessary.

Our JavaScript bundler is usually smart enough to include static assets like you are doing, but it has trouble when you're referencing the file paths dynamically like that. You can fix that by referencing those files more "directly". For example:

```js
const defaultPath = path.join(__dirname, 'files', 'default.ts')
const secretPath = path.join(__dirname, 'files', 'secret.js')
```

The other option is to use the `includeFiles` config option on your `@now/node` build. See the documentation for an example: https://zeit.co/docs/v2/deployments/builders/overview#including-additional-files

Let me know if that gets things working for you!

**Comment by pablopunk** [comment]
@TooTallNate ok, the problem with the first option is that I need the names to be calculated in runtime, so they are unknown in compile time. But I didn't know about `includeFiles` option, that worked! Thanks for your time @TooTallNate 

I included an example here https://now-issue-2494.pablopunk.now.sh/_src for anyone having this issue. Basically `/` will show you the list of files and you can access any file by `/filename.js`

https://now-issue-2494.pablopunk.now.sh/
https://now-issue-2494.pablopunk.now.sh/main.ts
https://now-issue-2494.pablopunk.now.sh/main.js
