### ISSUE TITLE
Why do you enforce .env removal?

### ISSUE THREAD

**Issue by varna** [vercel/vercel#2527]
##  It seems that Now is trying to kill `.env` files and enforce users to use `secrets`

This is most common response form support, github issues and spectrum. This is an offered solutions because of assumption that `.env` contains keys, passwords etc.

Examples:
```> Error! The property "dotenv" is not allowed in now.json when using Now 2.0 – please remove it.```
```> WARN! The "now alias" command was deprecated in favour of "now --target production".```

## `.env !== secret`

There are many cases when .env file does not contain secrets, but an actual environment variables as it name implies:
- baseUrl;
- API/DB address;
- client side only app (SPA);
- deploying staging version that uses `dev` variables;

## `.env` removal

I think that it's nonsense  to remove `.env` for "security" while deploying with `now` command. It's a lot more dangerous to leave `.env.production` used in projects like  [create-react-app](https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables#adding-development-environment-variables-in-env), [vue-cli](https://cli.vuejs.org/guide/mode-and-env.html#modes) and  [gatsby](https://www.gatsbyjs.org/docs/environment-variables/#defining-environment-variables). You also need to know that this feature of `.env` removal while using `now`. It works "differently" compared to other providers. Couldn't you simple use some sort of warning while deploying? `> WARN! Found files whose name include ".env", these files will be deployed to server. If you want to avoid exposing your secrets, use "now secrets -h"`

## `now -e, --env`

Zeit allows adding env variables via CLI arguments `now -e SECRET=secret`. Cool. But _I think_ that it is more common to use `.env` file (`now -e .env`). Why? Because `now` command is probably part of `package.json` `scripts`. And `.env` is probably part of `.gitignore`.

I suggest adding CLI option for env files. Which would _remove_ targeted file and add its contents as secrets to project being deployed. Or something like that?

## Expose `--target` argument to ENV

Docs for [environment-variables-and-secrets](https://zeit.co/docs/v2/deployments/environment-variables-and-secrets) and [aliasing-a-deployment](https://zeit.co/docs/v2/domains-and-aliases/aliasing-a-deployment) has nothing about figuring out which `now --target` are you currently in.

**Comment by varna** [comment]
Multiple environments: #2531 #2466 #2452 #2423

**Comment by leo** [comment]
Thank you for your suggestion!

We'll re-visit our env strategy. You can follow along in https://github.com/zeit/now-cli/issues/2613.
