### ISSUE TITLE
Delete a deployment by URL

### ISSUE THREAD

**Issue by anatrajkovska** [vercel/vercel#2529]
There is a new way to delete a deployment by its URL. See https://github.com/zeit/docs/pull/988.

Previously, a deployment could only be deleted by using its `id`.

We should incorporate this endpoint in the CLI where a deployment needs to be deleted by URL.

**Comment by TooTallNate** [comment]
Closing because `now rm` does indeed work with URLs. It might go through a more roundabout way by invoking more API calls to resolve the URL than necessary, but we'll accept a PR for further optimizations.
