### ISSUE TITLE
Multiple dotenv files

### ISSUE THREAD

**Issue by jerrygreen** [vercel/vercel#2531]
In `now.json` config there's a possible setting:

```
{
  "dotenv": "some.custom.env"
}
```

But it could be cool to pass an array there:

```
{
  "dotenv": [".env.default", ".env"]
}
```

**Comment by leo** [comment]
Thank you for your suggestion. We'll consider this as part of https://github.com/zeit/now-cli/issues/2613.

**Comment by vadistic** [comment]
I did not feel like retyping secrets this morning... **I present you [`now-dotenv`](https://github.com/vadistic/now-dotenv)** It use Now API to sync your Now Secrets with .env files.

**Comment by agrohs** [comment]
https://www.npmjs.com/package/dotenv-flow
