### ISSUE TITLE
The page was not found in the hosted application

### ISSUE THREAD

**Issue by zababurinsv** [vercel/vercel#2532]
hi.
I am deploy this simple server for rss.
{
    "version": 2,
    "name": "mongo",
    "builds": [ { "src": "index.mjs", "use": "@now/node" } ]
}

express

app.get('/feed', (req, res) => {
    feed.find()
        .exec()
        .then(news => {
            res.type('rss');
            res.send(news[0]['feed']['rss']);
        })
})

but i'm response this error

404: NOT_FOUND
Code: FILE_NOT_FOUND
ID: hel1:fbl7g-1562881985901-d45b70d4dd9a

**Comment by leo** [comment]
As per your configuration, only `<deployment>/` will work. Please create a [route](https://zeit.co/docs/v2/advanced/routes/#) to rewrite the other requets to that URL as well.
