### ISSUE TITLE
`now dev` doesn't work as expected with gatsby

### ISSUE THREAD

**Issue by moroshko** [vercel/vercel#2536]
Repro [here](https://github.com/moroshko/gatsby-now-dev-issue).

**Comment by AndyBitz** [comment]
Hi @moroshko,

please update Now CLI, we just released a new version which fixes the routing bug for `@now/static-build`. I've tested your example locally with it and `/api/endpoint` worked fine, if that was your problem.

Let me know after you could verify, so I can close this issue.

**Comment by moroshko** [comment]
Thanks @AndyBitz!
I can confirm that the issue is fixed in 15.8.0

**Comment by AndyBitz** [comment]
@yoiang I can't reproduce your issue with `gatsby-starter-default` and Now CLI 16.2.0 or 16.1.4-canary.8.

Does it still happen for you? Posting the logs would help.
