### ISSUE TITLE
Is it possible to run a build script before now.json is read

### ISSUE THREAD

**Issue by ryankauk** [vercel/vercel#2540]
Hey, I need multiple environment variables setup, and read some places there's a supposedly new format for the config using now.js. However I don't see anywhere a time estimate, and is something that I currently need, is there at least a build step that can be ran before now does anything, I know you can configure the build in now.json for a static build but that's after the file is read. I'm looking to on the build step to build the now.json file for the different environments. Please let me know, thanks.

**Comment by paulogdm** [comment]
Would `now -A dev.now.json` work for you?

**Comment by leo** [comment]
Closing, as we have not seen a reply in two weeks.
