### ISSUE TITLE
 Error! The `dev` script in `package.json` must not contain `now dev`

### ISSUE THREAD

**Issue by Pushplaybang** [vercel/vercel#2546]
The changes in #2507 seem to break common conventions for JS development

- Why can users not specify whatever they want in their projects `package,json`
- what is the expected alternative approach?
- given the size of your user-base, would it not be beneficial to document changes like this, when they're made, explaining the motivation, and what one should do instead?
  - Having this as a simple policy for  the acceptance of Pull requests would certainly reduce the pain of changes like this.

**Comment by leo** [comment]
Thank you for reporting this. This error is not intentional for your use case!

We're in the process of deploying a fix.

**Comment by Pushplaybang** [comment]
@leo thanks for the feedback and an absolute pleasure, and I'm glad this was legitimate, and not being an idiot.  Looking forward to the fix. Cheers.

**Comment by leo** [comment]
@Pushplaybang This should be solved. Can you confirm?

**Comment by AndyBitz** [comment]
Has been fixed in https://github.com/zeit/now-cli/pull/2559

**Comment by Vash47** [comment]
@AndyBitz  I still seem to get the error in v17.1.1.

**Comment by ifyour** [comment]
@AndyBitz 

Same problem !🤷‍♂️
Version v17.1.1

**Comment by ifyour** [comment]
@Huskyhunter 

```
...
"scripts": {
   "dev": "./dev.sh"
},
...
```

```bash
chmod +x ./dev.sh
```

```
npm run dev
```

I've found a temporary solution.
