### ISSUE TITLE
[now dev] can't find node when installed with asdf

### ISSUE THREAD

**Issue by ijsnow** [vercel/vercel#2549]
When using a global installation of `now`, the `@now/node` fails to build endpoints because it can't find node when it's installed with [asdf.](https://asdf-vm.com/) I get a log saying

> unknown command: node. Perhaps you have to reshim?

However, everything is set up correctly with `asdf` (as far as I know). Additionally, if I install now as a dev dependency, everything works fine.

### Repro steps:

1. [Install asdf](https://asdf-vm.com/#/core-manage-asdf-vm) and the [nodejs plugin.](https://github.com/asdf-vm/asdf-nodejs#install)
2. Install now globally (`npm i -g now`).
3. Set up project:
```json
// package.json
{
  "name": "now-node-test",
  "version": "1.0.0",
  "main": "server.js",
  "license": "MIT"
}

```
```javascript
// server.js
module.exports = (req, res) => {
  res.end('Hello, World');
}
```
```json
// now.json
{
  "version": 2,
  "builds": [
    { "src": "./server.js", "use": "@now/node" }
  ]
}
```
4. Run `now dev`
5. Invoke the endpoint: `curl http://localhost:3000/server.js`
I get the following output and then it hangs forever:
> Building @now/node:server.js
downloading user files...
installing dependencies for user's code...
missing `engines` in `package.json`, using default range: 8.10.x
installing to /Users/isaac/src/gitlab.com/jago-eng/jago-new
yarn install v1.17.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.07s.
running user script...
compiling entrypoint with ncc...
ncc: Version 0.18.5
ncc: Compiling file index.js
> Built @now/node:server.js [1s]
unknown command: node. Perhaps you have to reshim?

### Workaround

Install `now` as a dev dependency and everything works as expected. Ideally, it would work with the global install as well since that is what the cli's install steps say to do.

**Comment by gavriguy** [comment]
I have the same problem

**Comment by leo** [comment]
This should be working now, as we're using system-Node. Can you confirm?

**Comment by mcmillion** [comment]
I'm having the same issue with 15.8.5, and no matter what I do, upgrading to 15.8.7 doesn't actually stick.

**Comment by ijsnow** [comment]
I'm seeing the same thing as @mcmillion 

![Screenshot 2019-07-26 11 46 13](https://user-images.githubusercontent.com/11557758/61974383-41308000-af9b-11e9-9f09-d759c680c292.png)

Same issue as before. Not sure what the fact that it says it's going to update to 15.8.7 and then updates to 15.8.5 suggests. May or may not be related.

**Comment by mcmillion** [comment]
I got this to work: I had to remove the Now desktop app I installed via homebrew and clean all of that out and then install via npm. Even though the homebrew app says it's updating the cli it doesn't appear to.

**Comment by ijsnow** [comment]
It worked once I uninstalled now desktop from homebrew and reinstalled with npm as well.
