### ISSUE TITLE
now dev / builder will crash if interval between saves is too short

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2555]
Tested with the `@now/next` builder, the site will crash (no error shown in `now-cli`) if changes were made (and saved) too quickly.

Video: https://d.bbi.io/R0vDP6+

**Comment by TooTallNate** [comment]
Ok I can reproduce. Taking a closer look now…

**Comment by TooTallNate** [comment]
@williamli Could you give `now-cli` **v15.9.0-canary.6** a try, and let me know if that fixes the issue for you?

**Comment by wiiiimm** [comment]
@TooTallNate it seems better but I can still crash the server if I do super quick changes + saves (like if I really have to try hard to crash it).

Video: https://d.bbi.io/lvRHT0 (it takes some doing to crash it, sometimes it is easier, sometimes it is harder)

**Comment by paulogdm** [comment]
@williamli Closing since we hope to get this sorted with the reboot of "now dev", as you may know.
