### ISSUE TITLE
Unable to deploy through CodeShip

### ISSUE THREAD

**Issue by vladejs** [vercel/vercel#256]
Hello, I have this custom deployment on codeship where I install now and try to deploy using following command:
```
now --token thetoken
```
It tells me I am not authorized on codeship's console. I think this have to do with the fact that codeship servers are on different country than I am, that's because I do now on my machine with same token and it works.

Any idea on how to correctly authenticate from codeship?

**Comment by jamo** [comment]
You can generate a separate accessToken for codeship at: https://zeit.co/account#api-tokens
But any token you have should work.

A link to a failing codeship build / full log how it fails would be great help for troubleshooting this more

**Comment by vladejs** [comment]
Well, there isn't much on logs:
```
> scrap@1.0.0 build /home/rof/src/github.com/vladejs/scrapao
> now --token FiKDg5gDJ89PzBBX4gfslhzg

> Deploying ~/src/github.com/vladejs/scrapao
> Error! Not authorized
```

What I have in my custom script is this:
```
npm -v
nvm install 6.3.1
npm i -dd -g now
now --token zWSR86jAXABEfFhBARYtjlLm
```

**Comment by vladejs** [comment]
mmm.. I just generated a new token and it worked fine!

**Comment by vladejs** [comment]
Hi @jamo . Again with this issue.

I am trying to deploy a meteor app through `meteor-now` using CodeShip, but before using `meteor-now` command, I need to authenticate first with `now` service. If I type: `now -L -t my_token` it ask me my email, and the Codeship build fails because I can't enter the email manually.

How do I avoid now to ask me for an email? Or provide it silently?

**Comment by matheuss** [comment]
@vladejs you can just `now --token <token>` – no need for `-L`

**Comment by vladejs** [comment]
@matheuss , problem is, that command uses now directly and therefore tries to deploy the project.
I am using `meteor-now`, which asumes that I have logged in using   `now`  previously. See:

![codeship_now](https://user-images.githubusercontent.com/12637186/28892689-cd27baf8-779c-11e7-800c-787e870c8b0f.png)

**Comment by vladejs** [comment]
Well, it looks like I can pass `--token` param to `meteor-now`, so I am correctly authenticated.
I will close this for good (I hope)
