### ISSUE TITLE
Option for disabling scaling when deploying?

### ISSUE THREAD

**Issue by purplecones** [vercel/vercel#257]
Is there a way to deploy a Dockerfile project and disable scaling?

**Comment by vladejs** [comment]
Why would you want to do that? `Scale by default` is one of now's killer feature

**Comment by purplecones** [comment]
@vladejs I'm working on a [project](https://github.com/mazlix/meteor-now) that uses **now** to deploy Meteor apps. The tool deploys a Meteor project with a local MongoDB instance in the Dockerfile if the user does not specify a MONGO_URL. This is great for demos, mvps and beginners. In this case, we would not want the deployment to scale.

I've been told in the slack channel that scaling customization is coming soon so I'll close this.

**Comment by purplecones** [comment]
Adding slack message for reference: https://zeit-community.slack.com/archives/now/p1485485758010835
