### ISSUE TITLE
[now dev] Add timing information for each step of a build 

### ISSUE THREAD

**Issue by ywg-jean** [vercel/vercel#2573]
At the moment the build output in dev looks like : 
```
downloading user files...
installing dependencies for user's code...
Found `engines` in `package.json`, selecting range: 10.x
installing to /Users/jean/dev/startups/yupwego/src/yupwego/api/src
yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.95s.
running user script...
tracing input files...
> Built @now/node@0.7.4-canary.43:api/src/index.js [11s]
```

I think it would be interesting to have a break down of the timing for the main steps which would look like this: (the values are obviously fake) 
```
downloading user files... [1s]
installing dependencies for user's code... [1.5s]
Found `engines` in `package.json`, selecting range: 10.x
installing to /Users/jean/dev/startups/yupwego/src/yupwego/api/src
> GET /_next/on-demand-entries-ping?page=/error
yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.95s.
running user script... [2s]
tracing input files... [5s]
> Built @now/node@0.7.4-canary.43:api/src/index.js [11s]
```

I'm not sure my timings add up to 11 seconds but this should convey the idea :)

**Comment by ywg-jean** [comment]
This could be used to confirm the value of #2574

**Comment by styfle** [comment]
I created a PR for the node builder which was missing a couple steps https://github.com/zeit/now-builders/pull/786

The CLI will need to be updated to include any steps that happen after the build step.

**Comment by ywg-jean** [comment]
The update on now-builder is pretty nice here is what it looks like on my health check endpoint today: 
```
> GET /api/
> Building @now/node@0.7.4-canary.44:api/src/index.js
downloading user files...
download complete [1ms]
installing dependencies for user's code...
Found `engines` in `package.json`, selecting range: 10.x
installing to /Users/jean/dev/startups/yupwego/src/yupwego/api/src
yarn install v1.15.2
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.80s.
install complete [1171ms]
running user script...
script complete [0ms]
tracing input files...
trace complete [5561ms]
> Built @now/node@0.7.4-canary.44:api/src/index.js [9s]
```
it looks like the missing cli steps amount to about 2500ms (~25% of the total)

**Comment by styfle** [comment]
Is this a TypeScript project? The slowest step is the file trace which is also including TS compilation. Perhaps you could compare the time to run [node-file-trace](https://github.com/zeit/node-file-trace) standalone and see how it compares to the 5561ms here.

**Comment by ywg-jean** [comment]
It is indeed a project with some pieces written in typescript. however running node-file-trace alone seems to indicate it is indeed the slow link in the chain :
```
>time node run.js
[...]
node run.js  6,85s user 0,33s system 141% cpu 5,062 total
```
I of course ran the trace on the same entrypoint that generated the build trace I quoted above :)

**Comment by TooTallNate** [comment]
Closing because more timing information has already landed on the `@now/node` builder.
