### ISSUE TITLE
[now dev] Skip runNpmInstall when rebuilding if package.json is unchanged

### ISSUE THREAD

**Issue by ywg-jean** [vercel/vercel#2574]
Rebuilding an endpoint in now dev can be pretty long which is not an enjoyable developper experience.

To give an example, my worst case at the moment is an endpoint with dependencies to firebase-admin and typescript yarn workspace which used to rebuild in 60seconds whatever the change I did in the code. 
I gained a lot from the recent updates in now-node builder (the switch to node-file-trace in particular) as it divided the build time by almost 3  from 60 to 22 seconds per build. 

However 20 seconds is still a long time to wait after adding a single console.log to the corresponding point. 

Discussing this with @styfle, he mentionned that the file watcher could   indicate if package.json was changed or not. if it was not changed the runNpmInstall step could be skipped to shave some time off of the rebuilds.

**Comment by rauchg** [comment]
Just chiming in to say thank you for the very nicely detailed report @ywg-jean – we are looking into improving the experience significantly here.

**Comment by leo** [comment]
Thank you for the report. Closing in favor of https://github.com/zeit/now-cli/issues/2605.

**Comment by ywg-jean** [comment]
thanks for the notice :)
