### ISSUE TITLE
Next.js dynamic routes 404'ing when using $1 on Now

### ISSUE THREAD

**Issue by SpaceK33z** [vercel/vercel#2583]
Let me preface this by saying I don't know for sure whether it's a Next.js or Now bug, but I'm thinking Now.

I have a repository that has a Next.js app in a `frontend/` folder, and a `now.json` file in the root.

In `now.json` I redirect all Next.js pages from `frontend/` to `/` with `{ "src": "/(.*)", "dest": "/frontend/$1" }`, so they are available in the root of the website.

You can find a [**reproducible example here**](https://github.com/Volst/now-next-dynamic-paths-issue). As you can see the main page works perfectly: https://now-next-dynamic-paths-issue.volst1.now.sh

However now comes the interesting part: I'm using a dynamic route, which should be available on https://now-next-dynamic-paths-issue.volst1.now.sh/event/asdf (*asdf* is just a random parameter). However, this gives a 404!

Maybe this isn't a bug (I think so though), **but** with `now dev` this does not happen and everything works fine!

**Comment by eugrdn** [comment]
I'm facing the same issue.
I expected that it should work with routes config like that
```
[
    {"src": "/event/(?<id>[^/]+)", "dest": "/frontend/event/slug=[slug]" },
    {"src": "/(.*)", "dest": "/frontend/$1" }
]
```

**Comment by IvanGrimes** [comment]
I am facing the same issue, too :(

**Comment by indiejoseph** [comment]
+1

**Comment by indiejoseph** [comment]
@SpaceK33z have you solved the problem? I tried specifying each dynamic routes in now.config.json as @eugrdn mentioned, but still got 404 of the client-side script file.

**Comment by eugrdn** [comment]
Probably this issue should be moved to next.js or wherever next-server package is situated

**Comment by SpaceK33z** [comment]
@indiejoseph no, but I do have a workaround based on @eugrdn's solution:

```js
[
  { "src": "/event/([^/]+)", "dest": "/frontend/event/[slug]?slug=$1" },
  { "src": "/(.*)", "dest": "/frontend/$1" }
]
```

Note: `/frontend/event/[slug].js` is a real file.

@eugrdn: but is it a problem with the next server? With `next build && next start` this works correctly.

**Comment by SpaceK33z** [comment]
Okay I think this has to do with the `@now/next` builder, so I'm moving this to https://github.com/zeit/now-builders/issues/811.
