### ISSUE TITLE
Rate limit exceeded error on deploy

### ISSUE THREAD

**Issue by danb235** [vercel/vercel#2585]
We are hitting a rate limit error on deploy using version 15.8.1...

```
Error! Upload failed
Error! Rate limit exceeded error. Try again in 48 minutes, or upgrade your plan here: https://zeit.co/account/plan
```

Our team is on the Unlimited plan. Should we not be getting this error? Does anyone have information on what this rate limit is?

There is a related issue #1514 but it is closed.  Since this is still happening I created a new issue.  We reached out to support and haven't yet received a response.

**Comment by rauchg** [comment]
@tkdan235 on behalf of the ZEIT team I want to apologize for this bad experience. We are working on a few takeaways from this:

- Improving the error mesasge
- Improve the documentation about rate limits
- Reviewing whether the rate limits are currently appropriate for paid members
- We are working on reviewing why your outreach to support was unsuccessful so far

I appreciate you following up and we are working on a definitive resolution!

**Comment by danb235** [comment]
Thanks for the reply.  I should also note that right after I created this issue we did receive a response from the support team.

Thanks for being proactive, we'll be waiting for an update.

**Comment by danb235** [comment]
We found information in the Now docs regarding rate limits: https://zeit.co/docs/v2/deployments/builds/?origin_team=T4CTXFNBB#build-sources-limit

>- On the Free plan, there is a limit of 32 build sources per hour and 100 build sources per day.
>- On the Unlimited plan, there is a limit of 512 build sources per hour and 3000 build sources per day.

I'm thinking that while we have a team setup, that is on the Unlimited plan, the token I am using for deployment is a personal token, and thus we are limited to 32 builds per hour.  I can't find any way to generate a team token.

It appears this has been asked about for some time: #856.

After reviewing the docs we shouldn't be using a token for our paid team Unlimited plan, but instead use scope?
https://zeit.co/docs/v2/platform/users-and-teams/#selecting-a-scope-for-api-requests
https://zeit.co/blog/introducing-scope

**Comment by danb235** [comment]
Another update for anyone else running into this issue, we have been using scope with our team and still have the same rate limit issue.  At this point I'm not quite sure how to utilize our team Unlimited plan for increased deployment capacity.  We'll continue waiting for support to respond with a solution.

**Comment by danb235** [comment]
It's been a week at this point and I haven't heard back from the support team.  Is there any update on this?  We have had to limit deployment to only a couple times a day to mitigate this.  Meanwhile we are paying customers.

**Comment by developius** [comment]
Seeing this too on a personal plan. I basically can't interact with Now without hitting rate limits. My repo in GitLab is linked for automatic deployments and I get loads of comments from Now on the PRs saying "You are pushing commits at a very fast pace (accross the whole organization)" which isn't true...

**Comment by w33ble** [comment]
Started hitting this yesterday, on the Unlimited plan. The message "Try again in X hours" comes along with it, where X just keeps going up. It's unclear to us why we've started exceeding whatever limits are in place.

**Comment by Polyhistor** [comment]
Same issue here! 

I've received an error  

`Error! Rate limit exceeded error. Try again in 22 hours, or upgrade your plan here: https://zeit.co/account/plan`

So I went ahead to that page, looked at the pricing and still found no information about the rate limit that I've exceeded. But I went ahead and updated my plan to unlimited anyways, trying to deploying again and the same error occurred!  

This is frustrating as I was really keen to deploy our Gatsby website on Now.sh and have it served with Brotli compression algorithm ..

**Comment by joecohens** [comment]
I’m really sorry about the bad experience, we are still actively working to improve this situation. We already have a fix in progress for the erroneous message.

I will personally update this thread as soon as possible, thank you for your patience!

@Polyhistor it sounds like that could be related to caching (which we will also improve by actively invalidating as soon as you upgrade). Can you let me know if it’s still happening? Thank you!

**Comment by Polyhistor** [comment]
I have updated my account and the error still persists

**Comment by j-mendez** [comment]
experiencing this issue as well on a free account after upgrading to `now@16.1.1`. I have not used the service for quite some time and my projects have not hit the rate limit.

**Comment by w33ble** [comment]
To follow up, I learned about another rate limit that hasn't been mentioned here. From the [Spectrum chat](https://spectrum.chat/zeit/now):

> At the moment, we allow 10K files per 24 hours. if you go above that, you will be unable to deploy.

In our case, we had a misconfiguration that was causing our coverage results to be sent along. Simple fix via `.nowignore`, hopefully that information is helpful to others. Once we got one of the employees to reset out rate limit, everything is working again.

**Comment by Polyhistor** [comment]
@w33ble  thanks for the info but this is our first deploy... actually our first touch with Now.sh.....

**Comment by joecohens** [comment]
Hi all, 

We have made a few improvements to our rate limiting system ensuring that the `retry-after` sliding window is correctly set making the rate limits reset on time.

As next steps we are making the CLI display more accurate information about the rate limit being hit https://github.com/zeit/now-cli/issues/2738 as well as documenting the limits on our website.

Thank you for the feedback @w33ble, we will add this as a note on the documentation about limits!

@Polyhistor can you help us sending information regarding your account/project to support@zeit.co so that we can take a closer look?

**Comment by Polyhistor** [comment]
@joecohens  I've sent an email with our team name.. Cheers.

**Comment by Polyhistor** [comment]
@joecohens Any luck with support team? Monday fresh and still stuck on 75%... if we can't make it work quickly, we must sadly move on with an alternative....

**Comment by wiiiimm** [comment]
@joecohens internal ZD ticket https://zeit-team.zendesk.com/agent/tickets/19073

**Comment by jeffreymendez1993** [comment]
issue is fixed on my end. I added a `.nowignore` file with `/coverage` being a path.

**Comment by 422158** [comment]
hello fellas,
what is the status? this is hindering my deployment. My upload just fails with more than 50% to go.
Thanks and keep up the good job.

**Comment by j-mendez** [comment]
@422158 add `./coverage` to .nowignore to fix the issue. You need to wait until your rate limit resets to re-test or contact a zeit employee to reset your limits.

**Comment by maiertech** [comment]
I am also running into this issue on a team on a free plan in a project with occasional deployments. It is not clear to me what limits I am hitting an why.

**Comment by leo** [comment]
Thank you for your reports!

We're currently working on https://github.com/zeit/now-cli/issues/2738 and will soon be releasing an update with it, which will render the rate limits in a much better more readable way. Like this, it will be easier to grasp what needs to be done to prevent the rate limit from occurring again.

**Comment by TooTallNate** [comment]
Hey all, could you try out Now CLI `16.1.2-canary.3` and let us know if that displays a different error message now?

**Comment by Polyhistor** [comment]
Hey fellas, 

Upgrading to unlimited plan solved my issue. Along the line make sure few things are in place: 

#1 you've added node-modules into now.ignore
#2 you've switched to your unlimited account 

And it should work just okay..

**Comment by joecohens** [comment]
Hi all, 

Aside from the changes to output useful rate limit messages on the CLI (already landed on the stable version), we have shipped a new improved section to our docs listing each of the limits https://zeit.co/docs/v2/advanced/platform/limits/

Any feedback is appreciated!

**Comment by leo** [comment]
Is everyone in here now seeing a proper error message?

As of Now CLI 16.1.2, we're now rendering the full error message from the API, which contains more details. No more client-side overwriting.

**Comment by nlakshmirajasekharnune** [comment]
i am getting build issue in vercel
Error: Request failed with status code 429
--


<span>    at endReadableNT (node:internal/streams/readable:1359:12)</span>
