### ISSUE TITLE
unclear how to do monorepo deployment of create-react-app

### ISSUE THREAD

**Issue by helios1138** [vercel/vercel#2593]
CRA deployment guide on Now website just says something like `cd` into app directory and hit `now`. This does indeed work, but then it is unclear how to replicate the same behavior when doing full configuration in a monorepo scenario. Like, which builder to use, how to define routes for single-page apps etc.

I assume there is nothing like `"use": "@now/auto"` to replicate the behavior of just using `now` command in some folder?

**Comment by HerbCaudill** [comment]
Hey, I was just looking for the same thing and came across this, which works perfectly. 
https://github.com/ctrlplusb/cra-monorepo

Here's the `now.json` from that repo. Some of the routes could probably be consolidated to simplify this, but I know this works. 

```json
{
  "version": 2,
  "name": "cra-monorepo",
  "builds": [
    { "src": "node/api/**/*.ts", "use": "@now/node" },
    {
      "src": "www/package.json",
      "use": "@now/static-build",
      "config": { "distDir": "build" }
    }
  ],
  "routes": [
    {
      "src": "/api/(.*)",
      "dest": "/node/api/$1.ts"
    },
    {
      "src": "/static/(.*)",
      "headers": { "cache-control": "s-maxage=31536000,immutable" },
      "dest": "/www/static/$1"
    },
    { "src": "/favicon.ico", "dest": "/www/favicon.ico" },
    {
      "src": "/asset-manifest.json",
      "dest": "/www/asset-manifest.json"
    },
    { "src": "/manifest.json", "dest": "/www/manifest.json" },
    {
      "src": "/precache-manifest.(.*)",
      "dest": "/www/precache-manifest.$1"
    },
    {
      "src": "/service-worker.js",
      "headers": { "cache-control": "s-maxage=0" },
      "dest": "/www/service-worker.js"
    },
    {
      "src": "/(.*)",
      "headers": { "cache-control": "s-maxage=0" },
      "dest": "/www/index.html"
    }
  ]
}
```

**Comment by helios1138** [comment]
@HerbCaudill thanks, that did indeed work for me. It's still weird that `now` CLI clearly can do the right thing automatically, but then you can't invoke that behavior when you need it in a more complex config.

**Comment by HerbCaudill** [comment]
@helios1138 I had the same thought. 

FWIW here's a simpler `now.json` that also works.

```json
{
  "version": 2,
  "name": "cra-monorepo",
  "builds": [
    { "src": "node/api/**/*.ts", "use": "@now/node" },
    {
      "src": "www/package.json",
      "use": "@now/static-build",
      "config": { "distDir": "build" }
    }
  ],
  "routes": [
    { "src": "/api/(.*)", "dest": "/node/api/$1.ts" },
    { "src": "/(.+)", "dest": "/www/$1" },
    { "src": "/", "dest": "/www/index.html" }
  ]
}
```

**Comment by helios1138** [comment]
@HerbCaudill that one didn't work for me, when I navigate somewhere and then refresh the page - I get 404 error.

I can assume that `{ "src": "/(.+)", "dest": "/www/$1" }` does not skip "files/paths that do not actually exist", so it never goes to the `{ "src": "/", "dest": "/www/index.html" }` route

**Comment by TooTallNate** [comment]
If you're looking for less configuration, and for Now do to the right thing "automatically", then I suggest taking a look at our recently announced [Zero Config Deployments](https://zeit.co/blog/zero-config) blog post.

Also, support questions like this could be better answered at https://zeit.co/chat.

**Comment by HerbCaudill** [comment]
@TooTallNate 

> If you're looking for less configuration, and for Now do to the right thing "automatically", then I suggest taking a look at our recently announced [Zero Config Deployments](https://zeit.co/blog/zero-config) blog post.

Now doesn't "do the right thing" in this situation. And in fact the zero-config black-box thing makes it much harder to know what to do when you run into any setup that is slightly different from what Now handles automatically, because there's not a visible default config to take as a starting point. 

> Also, support questions like this could be better answered at https://zeit.co/chat.

Noted

**Comment by leo** [comment]
Thanks a lot for this report, @helios1138 and @HerbCaudill.

I understand that a lot of developers would like to extend our "zero config defaults" with some custom behaviour (like putting the frontend into a sub directory).

We are currently actively working on creating the specification for making these scenarios possible.

In the near future, you'll be able to "extend" the defaults we provide for you, which will allow for what you suggested above.

Thanks again for the feedback. Keep it coming!

**Comment by bionicles** [comment]
@leo facing this issue right now -- how do I point 'now' at a subdirectory?

**Comment by scottfits** [comment]
Same issue

**Comment by slgauravsharma** [comment]
I ma facing issue in monorepo in create react app always serve home route only, how to render client side routing without using next.js.

"builds": [{
      "src": "static-build-example-react/package.json",
      "use": "@now/static-build",
      "config": {
        "distDir": "build"
      }
    },
    {
      "src": "node-server-express-example/src/index.js",
      "use": "@now/node-server"
    }
  ],
  "routes": [{
      "src": "/",
      "dest": "/static-build-example-react/index.html"
    },
    {
      "src": "/(.+)",
      "dest": "/static-build-example-react/$1"
    },
    {
      "src": "/api/(.*)",
      "dest": "node-server-express-example/src/index.js"
    }
  ]
