### ISSUE TITLE
Now fails with ENOENT when using shopify-api-node

### ISSUE THREAD

**Issue by diogoviannaaraujo** [vercel/vercel#2600]
Hi,

When i try to deploy (or use with 'now dev') a node service using shopify-api-node module i get a ENOENT error on a 'shopify-api-node/resources' folder.
If I check shopify-api-node in my node_modules the folder 'resources' is there, but if I check now dev tmp folder it looks like now ignored the 'resources' folder

There is an issue on shopify-api-node tracker about that since feburary but I found no solution to it.

https://github.com/MONEI/Shopify-api-node/issues/244

**Comment by TooTallNate** [comment]
Looks like this was fixed in `shopify-api-node@2.22.0`. See https://github.com/MONEI/Shopify-api-node/issues/244.
