### ISSUE TITLE
We show a weird error when the auth token is expired

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2606]
This error is useless:

![image](https://user-images.githubusercontent.com/6170607/61789604-68f5db80-ae15-11e9-9124-fa6783740837.png)

Instead, we want to tell the user:

> You don't have access to this deployment. Please log in:

(and then we auto-trigger the login)

**Comment by TooTallNate** [comment]
FYI, not only `now logs`, but basically any command that requires authentication:

```
$ now
> Error! The specified token is not valid

$ now ls
> Error! The specified token is not valid

$ now alias
> Error! The specified token is not valid
```

**Comment by zdne** [comment]
FWIW, I am still getting this strange message

```
$ now ls
Now CLI 19.2.0
Error! The specified token is not valid
```

**Comment by ghost** [comment]
I too am getting the error @zdne reported. I had to do a `vercel login` to be able to deploy again.

**Comment by wokejacqueline** [comment]
same on my project, not sure why.  the old way to fix it used to be

`now logout` & `now login` which has of course changed to `vercel logout` & `vercel login`

**Comment by barbalex** [comment]
@jeremiahlee thanks for pointing out the fact that this has something to do with auth and how to solve it. The Error message is not helpful
