### ISSUE TITLE
Specify CPU/Mem restrictions in different plans

### ISSUE THREAD

**Issue by sedubois** [vercel/vercel#261]
I discovered the hard way that the resources are much more limited in OSS plan (my `next build` was silently failing for this project: https://github.com/relatenow/relate, and @jamo realized it was an out of memory issue). I think this should be mentioned in the plan descriptions, otherwise people might think that there is the same limitation in the paid plan.

<img width="908" alt="screen shot 2017-01-28 at 11 13 14" src="https://cloud.githubusercontent.com/assets/4217871/22395570/0b5b4e0a-e54b-11e6-9e63-fa182aa0e619.png">

**Comment by rustanacexd** [comment]
agree

**Comment by bvaughn** [comment]
Running into this myself now, trying to deploy [bvaughn/personal-logger](https://github.com/bvaughn/personal-logger/). Were you able to work around this by upgrading to a paid plan?

**Comment by sergiodxa** [comment]
Any paid plan has up to 1GB of RAM and the OSS plan has the half, if you don't have enough RAM you can try to upgrade.

I'm closing this since it's not related to now-cli but to [zeit/now-cloud](https://github.com/zeit/now-cloud).
