### ISSUE TITLE
Improve error when there is no node installed for now dev

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2611]
Currently, this is what we're exiting with (we need to render a much better error):

![Untitled-9](https://user-images.githubusercontent.com/6170607/61795711-559e3c80-ae24-11e9-8fe9-ba4d26a97713.png)

**Comment by TooTallNate** [comment]
I don't think this one is valid anymore now that we aren't using `pkg` binaries, so the user will _always_ have `node` installed.
