### ISSUE TITLE
Add `now build` command

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2614]
This command will allow replicating the production behaviour 100% for testing. No testing, no development watching interface, just production.

**Comment by jaydenseric** [comment]
Really desperate for this feature; I'm experiencing Next.js and styled-jsx issues that only happen in production deployments. It is very cumbersome trying to poke around a deployment to debug, and I would like to get a friend to take a look but he is not a team member and can't make deployments. Ideally we could replicate the issue locally on his machine.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

In the case of your specific feature recommendation, you can rest assured that we're already tracking it on our roadmap and you can expect to see an update on our [Twitter account](https://twitter.com/zeithq) or [Blog](https://zeit.co/blog) soon.
