### ISSUE TITLE
[now dev] Support WS proxy passthrough

### ISSUE THREAD

**Issue by ctrlplusb** [vercel/vercel#2615]
I have set up a basic monorepo example of CRA along with a few Node lambda endpoints.

Whilst developing I have noted that the hot reloading experience of the CRA dev server is not working as expected. 

I added additional routes to support the requests made by the hot reloading process. This improved the experience slightly in that a change would cause a page refresh, however, it would be far better to support the full in-place hot reloading experience. I suspect the blocker on this is that the `now dev` proxy server does not support/passthrough websocket connections.

I understand that lambda's don't/won't support WS, but in terms of the dev server this would go a long way in improving DX.

To reproduce you can clone and run the minimal [monorepo example](https://github.com/ctrlplusb/cra-monorepo) I created. Run `now dev` and then edit one of the components and note the full page refresh. Note the console log errors about WS connection failing too.

**Comment by ctrlplusb** [comment]
Works fine via the "new" dev script. 👍

https://github.com/ctrlplusb/cra-monorepo

Thanks so much team zeit! ❤️

**Comment by mcmillion** [comment]
How did you get this working? I'm running into the same issue with a vanilla CRA app on 15.8.7 and while I do get "reloads" after changes, I'm still getting spammed with errors connecting to the hot reloading and it's not actually hot reloading.

**Comment by ctrlplusb** [comment]
Hey @mcmillion - check out my repo linked above. I updated it again last night to have explicit now.json config as I wanted my UI under a subfolder. You need to copy the additional routes that I put in to handle sockjs-node and hot-update requests. 👍

**Comment by callain** [comment]
This was exactly what I was looking for ! Thanks @ctrlplusb :)
Had to replace `sockjs-backend` by `sockjs-node` thought.
