### ISSUE TITLE
Potentially get rid of "Preparing x for build" in now dev

### ISSUE THREAD

**Issue by AndyBitz** [vercel/vercel#2616]
We might want to hide this log (as it's mainly for installing yarn dependencies):

![Untitled](https://user-images.githubusercontent.com/6170607/61796811-79628200-ae26-11e9-9215-14927032e6e5.png)

Up for discussion though.

> Initially created by @leo

**Comment by leo** [comment]
We'll be tackling this with the upcoming `now dev` revamp.
