### ISSUE TITLE
How to export an existing project from now.sh to a local computer

### ISSUE THREAD

**Issue by aret1nol** [vercel/vercel#2628]
How to export an existing project from now.sh to a local computer. Or how to download an existing project to a computer (for example, in a zip archive like on github). Or at worst, copy the existing project from now.sh to github. What should I do if I have lost my local copy of the project?
![image](https://user-images.githubusercontent.com/52865070/61869206-c48e9a80-aee3-11e9-874d-e8f389474a00.png)

**Comment by leo** [comment]
Currently, we don't offer such a feature. However, you can send us your deployment URL at `support@zeit.co` and we will send you a ZIP of the source code.

**Comment by aret1nol** [comment]
Thank you!

**Comment by mininaim** [comment]
Hello I contacted your support to get sources files, and they claimed they are no longer doing it due to your new privacy policy?!

**Comment by paulogdm** [comment]
We are unable to provide source-code to our users due to privacy concerns and also how our platform evolved. We no longer keep the source-code easily available, unfortunately.

**Comment by lmf-git** [comment]
Absolute cop out. I thought this was ridiculous at the time, then when it happened to me it was infuriating.

I went from recommending Vercel to everyone to being unwilling to recommend it to anyone.

**Comment by paulogdm** [comment]
@lmf-git Using a source-control tool is the best option. We are not keeping the source-code easily available anymore.

**Comment by sarmadgardezi** [comment]
To export an existing project from Now.sh to a local computer, you can follow these steps:

Install Now CLI: If you don't have Now CLI installed on your computer, you can install it by running the following command in your terminal: npm install -g now

Log in to Now CLI: Log in to your Now CLI account by running the command now login and following the prompts.

List your projects: Run the command now ls to list all your projects on Now.sh. Find the project that you want to export and note down its name or ID.

Export the project: Run the command now export <project-name> or now export <project-id> to export the project to your local computer. Replace <project-name> or <project-id> with the actual name or ID of your project.

Wait for the export to finish: The export process may take a few minutes, depending on the size of your project. You can track the progress of the export in your terminal.

Download the export file: Once the export process is complete, Now CLI will generate a ZIP file containing the exported project. You can download this file by running the command now dl <file-url> and replacing <file-url> with the URL of the export file that was displayed in the terminal after the export was completed.

Extract the ZIP archive: Extract the ZIP archive to a local directory on your computer. The extracted files will include your project's code, configuration files, and other assets.

You can now work on your exported project locally and deploy it to a new hosting platform or server. Note that the exported project may need to be modified to work with a new hosting platform or server, depending on the specific requirements of the platform or server.
