### ISSUE TITLE
Redirect to subdomain

### ISSUE THREAD

**Issue by janicduplessis** [vercel/vercel#263]
Is there a convenient way to redirect a subdomain to another one? I would like to redirect `appandflow.com` to `www.appandflow.com`. Right now I'm just aliasing to both domains but it would be nice if I could do something like `now alias www.appandflow.com appandflow.com`.

**Comment by OlliV** [comment]
https://github.com/vdanchenkov/now-redirect

**Comment by timneutkens** [comment]
@OlliV Since we can deploy from github I created a similar package without cli, which has the minimal code needed to do a redirect. https://github.com/timneutkens/now-redirect

**Comment by leo** [comment]
^

**Comment by kristojorg** [comment]
Tim, it looks like you only enter one domain there but don't you need a from and a to URL?

**Comment by timneutkens** [comment]
@kristojorg, only the to adress is Needed. You can alias any domain to the deployed service using now alias And it Will redirect to the provided url 😁

**Comment by kristojorg** [comment]
very cool! I love that you can deploy from github... seems like there are lots of cool things you can do with this I haven't thought of.  Thanks!

**Comment by timneutkens** [comment]
👍

**Comment by purplecones** [comment]
Is there a way to do this without dedicating an active instance?

**Comment by purplecones** [comment]
@sergiodxa you mean alias my main app to all the subdomains I want to redirect from in addition to the main domain?

**Comment by sergiodxa** [comment]
Yes, then in your app code check the domain to do the redirect.

**Comment by purplecones** [comment]
That makes sense, thanks.
