### ISSUE TITLE
[now dev] Assertion failed Windows pipe

### ISSUE THREAD

**Issue by szul** [vercel/vercel#2631]
Getting the following error while attempting to run `now dev` on a simple static build:

```
Assertion failed: handle->pipe.conn.remaining_ipc_rawdata_bytes >= bytes, file c:\pkg-fetch\precompile\node\deps\uv\src\win\pipe.c, line 1666
```

Windows 10
Node v10.6.0
Now 15.8.5

**Comment by leo** [comment]
Thanks for reporting this. Does `now@canary` work? We've removed the entire installation mechanism with binaries that we had before in favor of a regular npm package.

**Comment by szul** [comment]
@leo I'm upgrading my Node now to see if that changes anything. If not, I'll try canary. Is that just a `npm install now@canary -g` to get up on it?

**Comment by leo** [comment]
@szul Correct, `npm install now@canary -g`.

**Comment by szul** [comment]
@leo The upgrade to Node v10.16.0 seems to have resolved this.
