### ISSUE TITLE
15.8.6 breaks builds because of the `engines` field

### ISSUE THREAD

**Issue by mrm007** [vercel/vercel#2636]
15.8.6 was released with #2603, as a patch version. Our builds now break because we are still using Node 8. Node 8 → 10 is a breaking change and should have been tagged as such.
If 15.8.6 is truly a patch then the breaking change should have been flagged a long time ago.

**Comment by rauchg** [comment]
@mrm007 thanks for the heads-up. We are looking into this.

**Comment by TooTallNate** [comment]
Hey @mrm007, thanks for the report. There was an internal miscommunication about the fact that 15.8.6 should have in reality been 16.0.0. I've reset the `latest` dist-tag on npm back to version 15.8.5 so the error should not be happening any longer.

**Comment by rauchg** [comment]
Also we'll be looking into bringing back support for Node 8 if possible. Thanks for your patience!

**Comment by mrm007** [comment]
Thanks guys, amazing turnaround!
