### ISSUE TITLE
inconsistent behaviour for 404 handling in now.json for NextJS v9

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2638]
With NextJS 9, it is possible to make custom 404 pages by setting the following when deployed to ZEIT (cloud).

1. `/pages/error.js`
2. use the following routes in `now.json`
```
"routes": [
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error.html", "status": 404}
]
````

In `now dev`, a different set of `now.json` rules is required

1. `/pages/error.js`
2. use the following routes in `now.json`
```
"routes": [
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error"}
]
````

Note:
1. "status": 404 cannot be set in `now dev`
2. "dest" needs to point to "error" instead of "error.html" because the page has not been statically generated

**Comment by wiiiimm** [comment]
In `now dev` the following doesn't work:
```
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error.html", "status": 404}
````

```
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error", "status": 404}
````

```
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error.html"}
````

Only the following works

```
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error"}
````

**Comment by wiiiimm** [comment]
As of Next v9.0.3 on `now dev v16.0.0`

The following will result in serving all request (valid and invalid) to the `now proxy` error page. I am guessing it is trying to fetch error.html but there is only an error.js file, so it fall through and `now dev / now proxy` kicks in and serve its own default error page.
```
"routes": [
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error.html", "status": 404}
  ]
```
<img width="870" alt="image" src="https://user-images.githubusercontent.com/179761/62595087-70d27700-b90f-11e9-9a23-2f6e974ce14d.png">

The following will result in serving all request (valid and invalid) to the `error.js` custom error page, but static files cannot be loaded (because the too are served with `error.js`.
```
"routes": [
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error", "status": 404}
  ]
```
<img width="782" alt="image" src="https://user-images.githubusercontent.com/179761/62595128-a70ff680-b90f-11e9-9225-2dbf4c1656ab.png">

**Comment by wiiiimm** [comment]
I think it is also related to  `{ "handle": "filesystem"}` not being smart enough to figure out when to use .html and when to look for the lambda function.

```
"routes": [
    { "src": "\/(.*)\/", "headers": { "Location": "/$1" }, "status": 301},
    { "src": "/guide/(?<category>[^/]*)/(?<slug>[^/]*)", "dest": "guide/[category]/[slug].html"},
    { "handle": "filesystem"},
    { "src": "/(.*)", "dest": "error.html", "status": 404}
  ]
```

**Comment by trek** [comment]
Hi @williamli,

Thank you for the bug report. We're closing out older issues that have probably been addressed by now.
