### ISSUE TITLE
now --alias does not use specified config

### ISSUE THREAD

**Issue by djhi** [vercel/vercel#264]
Hi!

Thanks for this awesome product, love it :)

I tried to combine the `config` and `alias` options with `now --config=custom.json --alias` but it seems that the code which check the `--alias` arg and apply it does not read its settings from the configuration file specified with `--config`.

Most probably [here](https://github.com/zeit/now-cli/blob/master/bin/now-deploy.js#L596) but I haven't fully explored the code yet. It looks like the custom configuration should be passed to [readMetadata](https://github.com/zeit/now-cli/blob/master/lib/read-metadata.js)

**Comment by leo** [comment]
`--config` is meant to be used for the user-configfile that holds the token. Not the one that holds the config for your deployment... :blush:

**Comment by djhi** [comment]
oh right, so there's no way for specifying an alternative `now.json` file currently ? Use case: I'd like to have one for `staging` and another for `production`.
