### ISSUE TITLE
Startup can't find index.js if "files" configuration is used

### ISSUE THREAD

**Issue by taromero** [vercel/vercel#265]
I have the following now.json config:

```json
{
  "name": "sample-name",
  "files": [
    "bundle.js"
  ],
  "type": "npm",
  "engines": {
    "node": "7.0.0"
  }
}
```

Here I want to include the webpack bundle.js file, which I have listed within .gitignore.

If I try to deploy with this configuration, I get an `Error: Cannot find module '/home/nowuser/src/index'` error. When I remove the "files" section at the now.json file, I can deploy without problems, but the bundle.js file is not available.

I think the expectation would be that this configuration would *add* the listed files to the set of files already being uploaded, rather than just uploading that file.

**Comment by iaincollins** [comment]
I also ran into this problem trying to use "files" as it's [implied on the blog](https://zeit.co/blog/now-json) that it would add to the list, but when I attempted to include a '.env' file the build step on now.sh failed because it couldn't find the 'pages' directory.

**Comment by mike-engel** [comment]
I ran into this problem because I had a static deployment, but it was looking for the file in the `main` key in my package.json. I'd check to make sure that your `main` key is correct

**Comment by leo** [comment]
If this problem still occurs, please move it over to [this repo](https://github.com/zeit/now-cloud). That's where we'll collect the bugs of the platform from now on (separate space, easier to work on)! 😊
