### ISSUE TITLE
Show file name every time one is uploaded

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2651]
Currently, we're showing this:

![image](https://user-images.githubusercontent.com/6170607/61999580-c82d4780-b0c4-11e9-904b-405e2ddbb390.png)

Ideally, we want to instead show the file name every time we upload one.

**Comment by AndyBitz** [comment]
Currently we upload multiple files at the same time, so we'd have to show all of them. Maybe in some sort of list, but we can upload up to ~50 files concurrently. I'd imagine that would be quite messy for 700+ files.

**Comment by AndyBitz** [comment]
@leo I think with the implementation of now-client we won't have access to which files are currently uploaded as well, except if we add callbacks etc. to it

**Comment by leo** [comment]
@rdev Can you make sure this ☝️is made possible via an event. I think it might already be, not 100% sure though.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.
