### ISSUE TITLE
Maximum call stack size exceeded when routing

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2652]
As you can read [in this comment](https://github.com/zeit/docs/issues/1006#issuecomment-515689338), various people are currently running into [this Sentry error](https://sentry.io/organizations/zeithq/issues/1126251453/?referrer=slack):

<img width="676" alt="image" src="https://user-images.githubusercontent.com/6170607/61999626-f1020c80-b0c5-11e9-949e-c0e3e57862b1.png">

It seems like we are endlessly routing.

**Comment by Bartvelp** [comment]
Yes I am able to reproduce this if needed
