### ISSUE TITLE
Ship sourcemaps with Now CLI

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2653]
As you can see [here](https://github.com/zeit/api/issues/296), errors are currently very unreadable. We need to ship sourcemaps and try throwing an error, which should then result in a beautiful stack trace in Sentry.

**Comment by AndyBitz** [comment]
This is already the case for the canary channel. "Unfortunately" there were no reported errors for the latest releases to check this in Sentry.

**Comment by AndyBitz** [comment]
Can be tested on canary since #2567
