### ISSUE TITLE
inconsistent behaviour for Next v9's automatic-prerendering when routes are defined now.json

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2654]
PS: If the new zero-config is used, the following won't be an issue.

In the production ZEIT cloud, some of the NextJS v9 pages are prerendered into `.html` files. If they are used in part of the `now.json`'s `routes` definitions, they have to be declared explicitly as a `.html` file, eg: `{ "src": "/hello", "dest": "hello.html"}`

This configuration fails when used in `now dev` environment as the html file was never prerendered, hence `{ "src": "/hello", "dest": "hello"}`

This is partially why an inconsistent behaviour is also observed in https://github.com/zeit/now-cli/issues/2638

**Comment by indiejoseph** [comment]
https://github.com/zeit/now-builders/issues/811
I think this problem has been reported over and over in these two weeks, and Zeit team replied they're noticed and working on it, the only thing we can do it wait for them since no one call tell is it caused by CLI or builders.

**Comment by leo** [comment]
This issue is being solved by making production support `continue: true` for regular routes. This will allow routes to "filter down" and depend on each other, thus allowing for this to work.

**Comment by ywg-jean** [comment]
Note that in [my specific case](https://github.com/zeit/now-builders/issues/825) which seems to closely mirror the one mentionned in the initial report of this issue, I was able to make the app work by applying the following configuration 
```
"routes": [        
    {
      "src": "/(.*)",
      "dest": "/public/$1",
      "headers": {
        "x-request-path": "$1"
      }
    },
    { "handle": "filesystem" },
    {
      "src": "/(.*)",
      "dest": "/public/$1.html",
      "headers": {
        "x-request-path": "$1"
      }      
    }  
   ]  
```
I assume that something like
```
"routes": [        
  { "src": "/hello", "dest": "hello"},
  { "handle": "filesystem" },
  { "src": "/hello", "dest": "hello.html"}
]
```
might just work for @williamli 's case... even though I am not clear on how to interpret this syntax which was mentionned on [spectrum](https://spectrum.chat/zeit/now/custom-next-js-404-error-page-in-monorepo-deployment~fc329387-e24e-4d87-967c-a6672c6be46f?m=MTU2NDQyMDc3NzQ3Ng==) :)

**Comment by wiiiimm** [comment]
I think it is also related to `{ "handle": "filesystem"}` not being smart enough to figure out when to use .html and when to look for the lambda function.

**Comment by asherccohen** [comment]
Hi. Is there still no solution to this problem?this is highly affecting monorepos as we are forced to deploy an exported/built folder and can't rely on zero conf.
