### ISSUE TITLE
Less prominent upgrade message

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2656]
When an upgrade is needed, the user sees the following message:

<img width="642" alt="image" src="https://user-images.githubusercontent.com/6170607/62044711-e3eb3780-b203-11e9-86d8-f42f9c70dd6c.png">

Now that we're not auto-updating the client anymore, this message is really disturbing to some users, as we're constantly publishing patch updates.

Let's make it a one-liner instead:

> UPDATE AVAILABLE Run `npm install -g now@canary` to install Now CLI 15.9.0-canary.21

**Comment by ctrlplusb** [comment]
It would also be great to document how to avoid this check completely. It can be really annoying if something like a proxy doesn't play nicely with the network request. The `now` CLI simply hangs in this case.
