### ISSUE TITLE
Remove logs from the console v1

### ISSUE THREAD

**Issue by crallan** [vercel/vercel#2658]
Is there a way to clear the logs from a deployment? I don't want to create a new deployment but the logs are huge so I'm not able to read logs anymore. Is there a command or way to clear them?

**Comment by leo** [comment]
We're currently working on a way to filter them. Very soon, it should be possible for you to only see what you want to see.

**Comment by mcsdevv** [comment]
Closing this as no further functionality will be added to 1.0 given the deprecation notice.
