### ISSUE TITLE
4xx API errors should not go to sentry

### ISSUE THREAD

**Issue by TooTallNate** [vercel/vercel#2668]
4xx errors imply user error (i.e. not authorized to access deployment, or deployment not found). There's no "fix" we can do in the now-cli codebase to prevent that kind of error from happening, so they should not be going to Sentry.

**Comment by styfle** [comment]
There are some cases where 400 errors are helpful.

I was able to detect #4340 due to 404 sentry errors and fix it by printing a warning instead.

I'm going to close this issue because it seems too broad.
