### ISSUE TITLE
!@localhost: event not found when adding secrets with special characters like !@

### ISSUE THREAD

**Issue by cayasso** [vercel/vercel#267]
I am executing this command

```bash
$ now secrets add mongo-url "mongodb://user:pass!@localhost:27017/pin?authSource=admin"
```

And the output is
```bash
-bash: !@localhost: event not found
```

I am also unable to set secrets with `!`, the `!` is being replaced with empty string so for example:

```bash
$ now secrets add mongo-pass "pass!"
```
The value of `mongo-pass` is saved as only `pass` however if I remove the quotes then the value is the expected `pass!`

**Comment by danreeves** [comment]
Hi @cayasso, in bash `!` and `@` can have special meanings when inside double quotes (`"`). Do you get the same issue if you use single quotes?

e.g. `now secrets add mongo-pass 'pass!'`

**Comment by cayasso** [comment]
@danreeves You are absolutely right, both cases work when using single quotes.
It would be worthy to mention this in the docs.

**Comment by danreeves** [comment]
Glad to be of help

**Comment by clementoriol** [comment]
Just experienced this, didn't know. Same thing happen with the `$` char. Single quotes are safer :)
