### ISSUE TITLE
now --alias doesn't work

### ISSUE THREAD

**Issue by luisrudge** [vercel/vercel#268]
```
now -v
𝚫 now 4.0.1
```

<img width="1884" alt="screen shot 2017-01-31 at 18 15 59" src="https://cloud.githubusercontent.com/assets/941075/22482959/60a8b412-e7e2-11e6-8d47-561ed0f1f27b.png">

I don't have a package.json file. Maybe that's the issue?

**Comment by hugomd** [comment]
@luisrudge The command is `now alias`, which should be run after `now`, and will point the alias to the latest deployment. More information is available [here](https://zeit.co/blog/now-json#`alias`-(string|array)). 

Additionally, `--alias` is being deprecated.

**Comment by leo** [comment]
https://zeit.co/blog/easy-aliasing
