### ISSUE TITLE
Provide helpful message for new users and fix local installation messages

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2683]
For new users that don't have correct permissions set and want to install Now CLI, we want to provide a really good error message:

```
Error! ZEIT Now failed to place `now` in a directory in your executable path ($PATH).

To solve it, you have two options.

Option A)

Run this command to adjust permissions of the npm global directory and re-install `now`:

> sudo chown $(whoami) /usr/local/{bin,lib/node_modules} && npm i -g now@canary

Option B)

Follow this npm guide to create a different directory into which you can install `now` and
add it to your $PATH

> url to npm guide
```

These are the necessary items in total:

- [x] 1. Test local installation (and make sure the update message looks correct)
- [x] 2. Implement the message shared above
- [x] 3. Write integration tests for testing the message from #2 + local/global installation

**Comment by rauchg** [comment]
I also think a page we can link to at the end that summarizes this in the docs would be quite helpful

**Comment by AndyBitz** [comment]
No. 1 + tests for it has just been merged #2688

**Comment by leo** [comment]
#2 will be replaced by https://github.com/zeit/front/issues/4451

**Comment by AndyBitz** [comment]
Now CLI already has integration tests for the local/global update message since #2688, so I'll close this issue.

**Comment by leo** [comment]
We had to revert the local message.

**Comment by leo** [comment]
Re-opening, so we can merge the PR after the zero config release.

**Comment by leo** [comment]
Works!

![image](https://user-images.githubusercontent.com/6170607/63429030-460d1600-c419-11e9-8987-42e79cf722ab.png)

NOTE: We detect npm/yarn based on how Now CLI was installed. So if you're using `npm run` to test and you installed with `yarn`, it will tell you to upgrade with `yarn` too. That's intentional though.
