### ISSUE TITLE
Deploy from a docker image

### ISSUE THREAD

**Issue by LightningK0ala** [vercel/vercel#269]
Hi, 

Is it possible to get **now** to deploy an image pulled from a registry instead of building a Dockerfile from scratch? This would be useful for CI pipelines which push successful builds and **now** could reuse them to speed up the deployment step.

At the moment I'm thinking the only way to achieve this is to create another Dockerfile with a specific `FROM company:image`.

Thanks!

**Comment by jamo** [comment]
Currently a single line `Dockerfile` is needed with the `FROM` line pointing to public Docker hub. 
Also, it would make it to a nice addition to go along whit the "deploy from GitHub" cc/ @leo

**Comment by LightningK0ala** [comment]
Thanks @jamo! I realised this afterwards... I was trying to be cheeky and deploy a DB then I realised now doesn't support that. All good 😄
