### ISSUE TITLE
now dev triggers rebuild from the build output

### ISSUE THREAD

**Issue by AndyBitz** [vercel/vercel#2692]
When `now dev` uses `@now/static-build` with just a `build` command it can happen that the `build` command will change files that will cause `now dev` to execute the `build` command again.

#### Reproduce

1. Download `now-examples/create-react-app`
2. Execute `now dev`
3. Change a file to trigger a rebuild

**Comment by ezakto** [comment]
Getting the same behavior, I'm using `"build": "gulp"` to clean the `public` folder and compile files. Changing one file triggers an infinite rebuild loop.

**Comment by leo** [comment]
We need to ignore the output directory.
