### ISSUE TITLE
Serving a broken `index.html` file and then fixing it doesn't work

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2697]
Check out the following video. You'll notice that:

1. Adding a `index.html` file with a broken name
2. Fixing the name

Fails to recover in `now dev`.

[index html file.mp4.zip](https://github.com/zeit/now-cli/files/3467126/index.html.file.mp4.zip)

**Comment by TooTallNate** [comment]
This is a caching issue, which is strange to me because `now dev` is setting `cache-control: public, max-age=0, must-revalidate`. If I use `curl` or open a private browser session, the request is "revalidated" as expected since there's a fresh cache.

Will dig deeper.

**Comment by TooTallNate** [comment]
Looks like it has to do with the fact that the `etag` response header is identical even though the filename is different.

**Comment by TooTallNate** [comment]
**Note:** This issue happens in production as well.

**Comment by TooTallNate** [comment]
https://github.com/zeit/serve-handler/pull/101 fixes this for `now dev`.

**Comment by leo** [comment]
Works again!
