### ISSUE TITLE
Prompt to accept incoming connections on Mac OS when running `now dev`

### ISSUE THREAD

**Issue by lucleray** [vercel/vercel#2704]
When activating the firewall on MacOS, I start getting these prompts **each time** running `now dev` (sorry for the french):
<img width="448" alt="Capture d’écran 2019-08-05 à 21 24 33" src="https://user-images.githubusercontent.com/6616955/62489690-ae2bed00-b7c7-11e9-986f-ed2007decfbf.png">

I would expect to accept it only once the first time I run `now dev`, or not at all because I'm not trying to access "internet" or expose a server to the outside world with `now dev`.

One possible root cause for this is that the `now dev` server is listening on `0.0.0.0` instead of `localhost`. Listening on `localhost` wouldn't prompt this message.

Also worth noting that I'm not getting these prompts when running other servers in dev mode (for example, `yarn run next`).

**Comment by leo** [comment]
Re-opened so we can ship it after zero config: https://github.com/zeit/now-cli/pull/2720

**Comment by TooTallNate** [comment]
To avoid the firewall prompt, you can now do `now dev --listen 127.0.0.1`
