### ISSUE TITLE
Add release notes or changelog 🙏👼

### ISSUE THREAD

**Issue by gr2m** [vercel/vercel#2706]
Congratulations on the v16 Release!

Like others we learned about it from a Greenkeeper pull request: https://github.com/search?q=%22Update+now+to+the+latest+version%22&type=Issues

Could you maybe create a GitHub Release for v16 and add some release notes? We use the now CLI only for deployments (Integration does not work us) and I'd feel more confident updating to the latest release if I knew if the changes are relevant to us or not

**Comment by TooTallNate** [comment]
Hey there @gr2m, thanks for the kind words!

Release notes can be found here: https://github.com/zeit/now-cli/releases/tag/16.0.0

**Comment by gr2m** [comment]
Fabulous, thank you!
