### ISSUE TITLE
now --docker hitting lstat error

### ISSUE THREAD

**Issue by brandonmp** [vercel/vercel#271]
ETA: 
- now version 4.0.1
- node 7.1.0
- docker version 1.13.0
- ubuntu 16.10

My project has compiled src in `./dist`. I build a `docker` to run it w/ `pm2` w/ this `Dockerfile`:

````
FROM node:7-alpine
# add git so we can add npm packages from repos
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh

# create dir and copy relevant files
RUN mkdir -p /usr/src/app

COPY ./index.js /usr/src/app/
COPY ./package.json /usr/src/app/
COPY dist usr/src/app/dist

WORKDIR /usr/src/app

RUN npm install --production
RUN npm install pm2 -g
EXPOSE 8080

CMD ["pm2-docker", "index.js"]

````

This `Dockerfile` works with `now` in another of my projects (or did, the last time i tried it last month), and it builds fine with regular `docker build .`. 

However, when running `now --docker` in the project root (where the `Dockerfile` is), I'm hitting a loop in the build process with repeated errors of `lstat dist: no such file or directory`. Here's a sample:  

````
>  ---> Using cache
> Step 4 : RUN mkdir -p /usr/src/app/dist
>  ---> Running in ea73b512a4bd
>  ---> 05fee9b99a01
> Removing intermediate container ea73b512a4bd
> Step 5 : COPY ./index.js /usr/src/app/
>  ---> 334750f94400
> Removing intermediate container 5f5967a6b719
> Step 6 : COPY ./package.json /usr/src/app/
> Step 7 : COPY dist usr/src/app/dist/
> lstat dist: no such file or directory
>  ---> c726069ecc8b
> Removing intermediate container 5d9831a66cf9
> ▲ Storing image
> ▲ docker build
Sending build context to Docker daemon   215 kBkB
> lstat dist: no such file or directory
> Step 4 : RUN mkdir -p /usr/src/app/dist
>  ---> Using cache
>  ---> 05fee9b99a01
> Step 5 : COPY ./index.js /usr/src/app/
>  ---> Using cache
>  ---> 334750f94400
> Step 6 : COPY ./package.json /usr/src/app/
>  ---> Using cache
>  ---> c726069ecc8b
> Step 7 : COPY dist usr/src/app/dist/
> ▲ Storing image
````

Any tips? Googled the issue, and none of the fixes apply (I have no `.dockerignore`, and the `dist` folder is in the `Dockerfile`'s context)

**Comment by jamo** [comment]
Try running `now` with the `-d` flag to see which files it ignores. IIRC it uses `.gitignore` and possibly `.npmignore` in addition to always ignoring files like `.git` and `node_modules`

**Comment by guns2410** [comment]
I am having exactly same issues here.

**Comment by jamo** [comment]
The lstat basically means that the file it tries to `ADD/COPY` is not anywhere to be found.
So it's probably not being pushed to `now` when deploying. 
`now -d` should show which files it uploads/ignores

**Comment by leo** [comment]
^

**Comment by guns2410** [comment]
@jamo I do not see any files. Here is the output.

```console
$ now --docker -d -f
> Deploying ~/Work/Development/app
> [debug] Forcing `deploymentType` = `docker`
> [debug] locating files /Users/gunjansoni/Work/Development/app 31.444ms
> [debug] Getting files: 37.441ms
> [debug] Computing hashes: 29.742ms
> [debug] /now/create: 4974.676ms
> Ready! https://<someurl>.now.sh (copied to clipboard) [5s]
> Initializing…
> [debug] closing agent
> Building
> ▲ docker build
> Status: Downloaded newer image for ubuntu:latest
> 2508cbcde94b: Pull complete
```
