### ISSUE TITLE
`files` in `now.json` does not work correctly with `.gitignore`

### ISSUE THREAD

**Issue by JounQin** [vercel/vercel#273]
According to document in https://zeit.co/blog/now-json#`files`-(array), when I add `dist/*` to `files` field, the whole dist directory should be include into deployment, but in fact they didn't.

https://vue-ssr-vdelbmeqct.now.sh/_src/?f=now.json

Only if I remove `dist` from *.gitignore* they will be include.

https://vue-ssr-hvhscynevo.now.sh/_src

Is there anything wrong in my *now.json*?

**Comment by leo** [comment]
Should work with "dist" or "./dist" instead of "dist/*".

**Comment by revolunet** [comment]
Similar issue here .

Project structure :

- config
     - production.json
- src
     - index.js
- now.json
- package.json

Having this in `.gitgnore` 

```sh
$ cat .gitignore
config/production.json
now.json
```

in `now.json` :

```json
{
  "files": [
    "src",
    "config/production.json"
  ],
  "env": {
    "NODE_ENV": "production"
  }
}
```

The `config/production.json` doesnt get uploaded

**Comment by revolunet** [comment]
see also : https://github.com/zeit/now-cli/issues/717

**Comment by imevro** [comment]
Same issue with @revolunet
