### ISSUE TITLE
TypeErrorf.ref(now.dist:index)

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2732]
Check out [this error](https://sentry.io/organizations/zeithq/issues/1134197735/?referrer=slack):

![image](https://user-images.githubusercontent.com/6170607/62769939-48c34f00-ba9a-11e9-87c2-8aafa669727f.png)

**Comment by TooTallNate** [comment]
This is a duplicate of #2711, and has already been fixed.

**Comment by leo** [comment]
Amazing!
