### ISSUE TITLE
Provide a way to deploy canary builds with zero config

### ISSUE THREAD

**Issue by styfle** [vercel/vercel#2734]
It looks like canary builders are shipped with the CLI in #2641.

However, these are not used for zero config in `now dev` or `now` deploys.

We need a way to use canary builders with zero config in both `now dev` and `now` production deployments.

1. Provide a flag `now --builders=canary` or `now --canary`. This is my preferred method because it allows easy debugging to determine if a bug is in the CLI or the Builder, much like today changing now.json.
2. Always use canary builders with `now@canary` CLI. This could work for most cases and would make it easier for the user to comprehend. We would probably want to start syncing releases of canary builders and canary cli.

**Comment by leo** [comment]
This should already work with `now dev`. For `now`, we need to let the platform know that Now CLI canary sent the request.

**Comment by AndyBitz** [comment]
@leo It does **not** work for `now dev`. It only bundles the canary builders, but it doesn't use them, but this can be an easy fix.

For the API we could check the user agent I think.

**Comment by leo** [comment]
> It only bundles the canary builders, but it doesn't use them

😮 

Okay, let's make that work.

> For the API we could check the user agent I think.

Agreed.

**Comment by leo** [comment]
We had to revert this.
