### ISSUE TITLE
Error loading shared library ld-linux-x86-64.so.2: No such file or directory

### ISSUE THREAD

**Issue by appodeepa** [vercel/vercel#274]
Hi. 

My deployment has[ google-cloud](https://github.com/GoogleCloudPlatform/google-cloud-node) as a dependency and is failing with this message:

`Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /home/nowuser/src/node_modules/40daee308a4cb349df8d6cf5a749dfb86d2a7524/src/node/extension_binary/grpc_node.node)`

Searching in the google-cloud repo I saw this as a possible explanation: 

> The line that's failing, process.dlopen, is the mechanism that Node uses to load native extensions. It looks like your system doesn't support that, and without it, gRPC on Node simply will not work.

https://github.com/grpc/grpc/issues/8528

Does this apply here, and does that mean I can't use google-cloud with now? 

Node version 6.9.4
now version 4.0.1

**Comment by leo** [comment]
Fixed. Shipping!

**Comment by apichatpunkaew** [comment]
apk update
apk install libc6-compat
