### ISSUE TITLE
`now domains move` should reiterate where you're moving the domain

### ISSUE THREAD

**Issue by timneutkens** [vercel/vercel#2746]
Eg I typed in `zeit` and the text field disappears, however it doesn't reiterate on that you're moving to `zeit`.

<img width="615" alt="screenshot_2019-08-11_at_15 00 27" src="https://user-images.githubusercontent.com/6324199/62855095-94bc0100-bcf1-11e9-9905-a2387ece60e7.png">

**Comment by leo** [comment]
Thanks for sharing!

**Comment by timneutkens** [comment]
Going to close this as it's been solved afaik.
