### ISSUE TITLE
Not displaying an error when user sign up with an address that cannot be validated.

### ISSUE THREAD

**Issue by wiiiimm** [vercel/vercel#2752]
When user sign up with an email address that cannot be validated, the `now-cli` told the user to wait for the verification email.

It should return the same error message as `front`.

<img width="1615" alt="image" src="https://user-images.githubusercontent.com/179761/62913229-e205a480-bdbd-11e9-875f-6248a1c79404.png">

**Comment by TooTallNate** [comment]
Closing in favor of #1558.
