### ISSUE TITLE
"More information" URL in config is outdated

### ISSUE THREAD

**Issue by DHainzl** [vercel/vercel#2754]
After running `now login` both the generated user settings files (~/.now/(auth,config).json) contain a comment:

```
{
  "_": "[ ... ] More: https://bit.ly/2qAK8bb"
}
```

The link used here (https://bit.ly/2qAK8bb) is outdated and returns a 404: https://zeit.co/docs/v2/advanced/platform/global-configuration

The code defining the URL seems to be here:
https://github.com/zeit/now-cli/blob/2777ec3e2cba5035585b2f463ec2b5103b82557f/src/util/config/get-default.js#L6
https://github.com/zeit/now-cli/blob/2777ec3e2cba5035585b2f463ec2b5103b82557f/src/util/config/get-default.js#L69

However I'm not sure what the best solution to this is (nor what the link should point to). The best solution might be to update the bit.ly link but I don't know if that is possible.

**Comment by leo** [comment]
Thanks for reporting this! We'll fix it.

They need to point to https://zeit.co/docs/v2/advanced/global-configuration/
