### ISSUE TITLE
[now dev] next.js HMR and on demand pings caught by wildcard route

### ISSUE THREAD

**Issue by chrstphrknwtn** [vercel/vercel#2764]
I have outlined the problem on spectrum: https://spectrum.chat/zeit/now/next-routes-not-handled-correctly-with-now-dev~5aeeed41-17e7-4f3a-bbd9-b9e3d1a1166b

I have also reproduced the bug in https://github.com/chrstphrknwtn/now-dev-next-hmr-issue

Basically I have a route something like `example.com/person/project` that is defined last in `now.json`. This was working fine in development using `"handle": "filesystem"` in `now.json#routes` however in `now` version 16 this is causing the HMR and on-demand pings to hit the `dest` for that route.

**Comment by trek** [comment]
Hi @chrstphrknwtn,

Thank you for the bug report. We're closing out older issues that have probably been addressed by now.
