### ISSUE TITLE
Error: Invalid tag name "latest@latest@latest@latest....

### ISSUE THREAD

**Issue by nickredmark** [vercel/vercel#2765]
when deploying I get this error:

```
> Error! Your deployment failed. Please retry later. More: https://err.sh/now-cli/deployment-error
```

link is broken, which is handled in this issue: https://github.com/zeit/now-cli/issues/1732

logs exposed this:

```
{ Error: Invalid tag name "latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest@latest": Tags may not have any characters that encodeURIComponent encodes.
```

what caused is was either

* I added now*.json to .gitignore
* I tried to deploy with a different now.json file (under a different project name)
* ?

**Comment by nickredmark** [comment]
Perhaps related: I'm using multiple now(.*).json files in the same folder to deploy to different subdomains with different configs. Is that not the intended usage?

**Comment by leo** [comment]
Sorry for the inconvenience we might have caused. This problem is now fixed!
