### ISSUE TITLE
Invalidate app cache on deploy

### ISSUE THREAD

**Issue by yantakus** [vercel/vercel#2771]
When I do a new deployment of my app, I have to invalidate client cache (stored in localStorage) because most probably backend schema has been changed and it causes problems.

So my idea is to write an environment variable during build and then check it at client-side and invalidate cache if the variable has been changed.

The only appropriate thing I could find is using `GITLAB_COMMIT_SHA` (documented here: https://zeit.co/docs/v2/advanced/now-for-gitlab/#included-environment-variables). But the problem is it doesn't work when I deploy the app manually from CLI.

Is there a way to write commit sha when deploying from CLI as well? Or maybe a more simple way - just write a random string with every new deployment to `.env` file?

**Comment by leo** [comment]
Hey! Have you tried checking `process.env` inside the deployment? We do provide other ways for accomplishing this - `NOW_URL` is one of them.

**Comment by yantakus** [comment]
@leo what do you mean by "inside deployment"? Just tried to do the following:
`yarn build` then `yarn start` and `console.log(process.env)`. It's an empty object.

**Comment by yantakus** [comment]
@leo what do you mean by 'inside the deployment'? Just deployed the app and `console.log(process.env)` - empty object.

**Comment by TooTallNate** [comment]
How are you getting the `GITLAB_COMMIT_SHA`? You should be able to get the `NOW_URL` env var the same way.

> Just deployed the app and `console.log(process.env)` - empty object.

Is this on the client-side or server-side?

**Comment by TooTallNate** [comment]
Actually, the `NOW_URL` env var is only available on Now v1, see https://github.com/zeit/now-builders/issues/55 for details.

For Now v2, the best way to determine the unique deployment URL is to check the `x-now-deployment-url` request header when handling an HTTP request.

Also, support questions this could be better answered at https://zeit.co/chat.

**Comment by yantakus** [comment]
Thanks for you comments. Ended up using this solution: https://github.com/nexdrew/next-build-id/issues/14
