### ISSUE TITLE
Redirect 404

### ISSUE THREAD

**Issue by abraaobuenotype** [vercel/vercel#2773]
I have a project made with next.js with a structure like this:

pages
- folder
- - [mypage].ts

/folder/mypage works but /folder return 404

I want to be able to redirect /folder to /folder/mypage

I tried using now.json like this:

`{
    "routes": [
        {"src": "/folder", "dist": "/folder/mypage"}
    ]
}`

and

`{
    "routes": [
        {"src": "/folder", "status": 404, "headers": {"Location": "/folder/mypage"}}
    ]
}`

but it did not work

thanks for help

**Comment by TooTallNate** [comment]
Hi there @abraaobuenotype. Could you please create a repository demonstrating what you are trying to achieve so that we can understand better?

Also, this is probably the kind of question that could be better answered at https://zeit.co/chat

**Comment by abraaobuenotype** [comment]
hi @TooTallNate thanks for answering and your help

basically i have this structure: 

![image](https://user-images.githubusercontent.com/25363790/63135760-649c8880-bfa5-11e9-8432-40ec86926d0e.png)

where index is the main page (route: "/")
and [tech] another page (route: "/for-you/tech")

I call this page (tech) using the next/link component
![image](https://user-images.githubusercontent.com/25363790/63135948-31a6c480-bfa6-11e9-8886-72f4ec756b83.png)

this is working, even when I reload the page, the "/for-you/tech" url works

but when I type in the browser url "/for-you" the answer is 404

so what I need is:

if the user enters the "/for-you" route in the browser, the server redirects the route to "/for-you/tech" instead of returning 404

I tried to do it like in the other message, editing the file now.json, sure I'm doing something wrong because it didn't work

**Comment by TooTallNate** [comment]
The first example you showed should be working:

```
{ "routes": [ {"src": "/folder", "dest": "/folder/mypage"} ] }
```

Note that it's `dest`, not `dist`. Not sure if that was how your code actually was or just a typo in this issue.

**Comment by abraaobuenotype** [comment]
no ... this really isn't working...

![image](https://user-images.githubusercontent.com/25363790/63163184-13b77f00-bffb-11e9-9e98-153f1511b860.png)

here is the project url:

https://pismoio.abraaoas3.now.sh/for-you/tech

**Comment by abraaobuenotype** [comment]
hey @TooTallNate 

I managed to make it work this way:

![image](https://user-images.githubusercontent.com/25363790/63163901-16b36f00-bffd-11e9-9a03-d9a61f8c3d2f.png)

this worked better: 

![image](https://user-images.githubusercontent.com/25363790/63165985-6bf27f00-c003-11e9-8d4a-4d0b63cf69b3.png)

thanks for your time and your help
