### ISSUE TITLE
[bug] deployed to unintended region by "now for Github" 

### ISSUE THREAD

**Issue by jjangga0214** [vercel/vercel#2774]
While I specified region "icn1"(Seoul, South Korea) on now.json, now for Github actually deploys the app to USA (AWS). I believe this is a bug, isn't it?

```json
{
  "version": 2,
  "name": "<name>",
  "builds": [{ "src": "index.js", "use": "@now/node" }],
  "routes": [{ "src": "/(.*)", "dest": "index.js" }],
  "regions": ["icn1"]
}
```

**Comment by leo** [comment]
This seems like a bug indeed. We do support [icn1](https://zeit.co/smart-cdn).

**Comment by jjangga0214** [comment]
@arunoda May I ask when (unless already) this would be fixed?
