### ISSUE TITLE
Builder help for Now.json with now version 2, nextjs and tsx files

### ISSUE THREAD

**Issue by Dashue** [vercel/vercel#2775]
Hello everyone!

I'm really struggling with something I feel should be quite trivial and I'm sure I'm missing something simple.

Now.json

```json
{
    "name": "redacted",
    "version": 2,
    "alias": ["redacted"],
    "builds": [{
        "src": "package.json",
        "use": "@now/next"
    }]
}
```

Package.json:

```json
{
  "name": "lunaink",
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "9.0.3",
    "react": "16.9.0",
    "react-dom": "16.9.0",
    "reactstrap": "^8.0.1"
  },
  "devDependencies": {
    "@types/jquery": "^3.3.30",
    "@types/node": "^12.6.6",
    "@types/react": "^16.8.23",
    "@types/reactstrap": "^8.0.1",
    "typescript": "^3.5.3"
  }
}
```

And I'm using a standard index.tsx file.

When running now dev all I'm getting is
> Now CLI 16.1.1 dev (beta) — https://zeit.co/feedback/dev
> Creating initial build

When trying the example in the blog post for now dev
Step 1: now init nextjs
Step 2: now dev
I'm getting the exact same output as above.

I have both the windows client installed as well as installed now globally through npm.

I'd love to be on version 2 instead of 2 for now, but until I can figure this builder out I can't migrate, I've struggled with the builder documentation as well as it doesn't seem to cover it from a now dev /now.json aspect or I'm just missreading it.

Thanks in advance to anyone that can shine some light on this

**Comment by TooTallNate** [comment]
Hey @Dashue, sorry that you are having difficulties. I would like to understand more what you are experiencing. Would you be able to share a repo that demonstrates the issue you are having so that we can take a closer look?

**Comment by Dashue** [comment]
PS C:\dev> now init nextjs
> Success! Initialized "nextjs" example in C:\dev\nextjs.
- To deploy, `cd nextjs` and run `now`.
PS C:\dev> cd .\nextjs\
PS C:\dev\nextjs> npm i
PS C:\dev\nextjs> npm run dev
npm WARN lifecycle The node binary used for scripts is C:\Program Files (x86)\Nodist\bin\node.exe but npm is using C:\Program Files (x86)\Nodist\v-x64\11.13.0\node.exe itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> create-next-example-app@ dev C:\dev\nextjs
> next

[ wait ]  starting the development server ...
[ info ]  waiting on http://localhost:3000 ...
[ ready ] compiled successfully - ready on http://localhost:3000
[ wait ]  compiling ...
[ ready ] compiled successfully - ready on http://localhost:3000
PS C:\dev\nextjs> now dev
> Now CLI 16.1.1 dev (beta) — https://zeit.co/feedback/dev
> Creating initial build
PS C:\dev\nextjs>

I think it starts with now dev not doing anything on a newly created project, then once I've got that working I want to be able to switch index.js to index.tsx

I'm guessing I need to possibly add a now.json manually to set up the builder and possibly install a builder dependency through npm for now/nextjs?

Thanks for your time

**Comment by Dashue** [comment]
PS C:\dev\nextjs> now -v
16.1.1

Also there seems to be an issue with the windows client, as it seems to downgrade my now cli to v 15.x constantly, is it not supposed to pick up v16 releases?

**Comment by leo** [comment]
Thanks for reporting this! @TooTallNate will be helping you get started with a working implementation of your project.

**Comment by Dashue** [comment]
Bump?

**Comment by styfle** [comment]
@Dashue The `vercel dev` command has been changed to use `process.execPath` mentioned in #3407.

Do you still have this issue with the latest version of Vercel CLI?

https://github.com/vercel/vercel/blob/0d4be3f5f223bbaf6602b8754127326d323b00ad/packages/now-cli/src/util/dev/builder.ts#L64

Also note that you can remove `now.json` file since Next.js is autodetected.
