### ISSUE TITLE
`now dev` gives EADDRINUSE for ::::5000

### ISSUE THREAD

**Issue by hbjydev** [vercel/vercel#2785]
Specifically this error: `Error: listen EADDRINUSE: address already in use :::5000`. I'm not sure what to do.

Literally all I've done is this:
```sh
yarn global add now
now init next .
now dev
```

Edit: I'm on macOS

**Comment by hbjydev** [comment]
This seems to have fixed itself. Closing.

**Comment by judewang** [comment]
@haydennyyy Hi, I met the same issue, how did you fix it?? I'm using now@16.2.0 and nextjs@9

**Comment by judewang** [comment]
The issue only happened when using with Docker.

**Comment by zcsongor** [comment]
same as @judewang. any hints?

**Comment by hbjydev** [comment]
@judewang @zcsongor Sorry about that. Honestly, I have no clue how I fixed it, it just sort of... fixed itself.

**Comment by zcsongor** [comment]
Thanks @haydennyyy. I've downgraded to 15.4.0 and it works for now.

**Comment by N0xFF** [comment]
It comes from `get-port` which used in:
https://github.com/zeit/now/blob/22bded50b664d0b41a10ce3e094e15e0393f12a9/packages/now-next/src/dev-server.ts#L18-L20

Probably related issue https://github.com/sindresorhus/get-port/issues/31
