### ISSUE TITLE
More than 100 certificates are not displayed with `now certs ls`

### ISSUE THREAD

**Issue by nkzawa** [vercel/vercel#2786]
And it doesn't indicate the result is truncated to 100.

<img width="296" alt="Screen Shot 2019-08-19 at 14 36 33" src="https://user-images.githubusercontent.com/775227/63250605-fa3a5f80-c2a6-11e9-8aa9-2f9aebcf0ae0.png">

**Comment by leo** [comment]
Thanks for reporting!
