### ISSUE TITLE
unable to build next.js app

### ISSUE THREAD

**Issue by tgoldenberg** [vercel/vercel#279]
My `now` command fails at `next build`. It never really fails, just keep trying again and again endlessly....
<img width="871" alt="screen shot 2017-02-03 at 3 19 23 pm" src="https://cloud.githubusercontent.com/assets/10930134/22607073/4cdc6598-ea24-11e6-8db5-770e6c6e903e.png">

**Comment by jamo** [comment]
This makes me think it's eating tons of memory and exceeding the ~500M memory limit of the OSS plan.
