### ISSUE TITLE
Now cannot find module "index.js"

### ISSUE THREAD

**Issue by alexofob** [vercel/vercel#281]
Hi there,

I am trying to deploy my next.js app on 'now' but I get this error:

> Error! Unexpected error. Please try later. (Cannot find module '/Users/alex/Labs/Nextjs/patient/index.js').

And for sure there is not index.js in the root directory of my next.js app

Below is my package.json config:

```json
{
  "name": "patient",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "material-ui": "^0.16.7",
    "mobx": "^3.0.2",
    "mobx-react": "^4.1.0",
    "next": "2.0.0-beta.18",
    "react-icons": "^2.2.3",
    "react-slick": "^0.14.5",
    "react-tap-event-plugin": "^2.0.1"
  },
  "scripts": {
    "dev": "next",
    "build": "next build",
    "flow": "flow",
    "start": "next start",
    "test": "jest --watch --env=jsdom"
  },
```

I will appreciate help on how to resolve this.

Thanks.

BR
Alex

**Comment by leo** [comment]
Please remove the `main` property. That should fix it! 😊

**Comment by alexofob** [comment]
Many thanks. That fixed it

**Comment by steveodom** [comment]
It got me too.

**Comment by matheuss** [comment]
I'm reopening this since it's something we'd like to fix – it's a _wrong_ behavior, since you can be using a `main` file that's only created when the application is built 🕵️

**Comment by hchoriq** [comment]
This needs to be handled better than a message that needs to be googled. It got me too. This WILL happen again to many more. What's worse? When I did a deployment through the desktop app, all it said was 502 deployment error. I almost gave up before I ran now on CLI.
