### ISSUE TITLE
Support for the browser

### ISSUE THREAD

**Issue by mdaverde** [vercel/vercel#2817]
Right now the current library is built just for a Node.js environment. It would be neat if we built a version of the library that would be compatible with browsers.

The changes required seems to be removal of `process.env` for browser builds (or at least stubbing it in the build process) and possibly changing out the `request-promise-native` library depending on which browsers we intend to support. 

I have a local version that I can push that I have working just for browser builds, but since this change requires both build and code changes, I wanted to see if any concerns I'm not acknowledging would be brought up or if this is even worth integrating with this library. 

Thanks!

**Comment by leo** [comment]
@mdaverde Thanks for reporting this!

At the moment, ZEIT is not looking to use `now-client` in the browser, which means that – if we decide to add browser support – we wouldn't actually be dogfooding it (which drastically hurts the quality of the library).

However, if we decide to offer deployments via the browser, we'll definitely look into supporting it.

In the meantime, we welcome any forks that can work in the browser! 👍

**Comment by leo** [comment]
I'm going to close this issue now, but let me know if there's anything I can do to help with information about how such a fork could look like. 😊
