### ISSUE TITLE
[now-client] Create Static Deployment

### ISSUE THREAD

**Issue by mattphillips** [vercel/vercel#2818]
Is there going to be support for static deployments? Either in the `now-client` or in the private API and detect the deployment type?

When I try to deploy without a package in the body it returns the following error:
```
StatusCodeError: 500 - {"err":{"code":"internal_server_error","url":"https://zeit.co/errors/internal_server_error","message":"An unexpected error occurred"}}
```

What I would like to be able to do is something like:
```js
const NowClient = require('now-client')

const now = new NowClient();

const create = async () => {
  try {
    const body = {
      'index.html': 'Hello World!',
    };
    const deployment = await now.createDeployment(body);
    console.log(deployment);
  } catch(e) {
    console.log(e);
  }
};

create();
```

**Comment by styfle** [comment]
This has been implemented, however the API has changed a lot since 2017.

Take a look at the [now-client](https://www.npmjs.com/package/now-client) npm package to see example usage.

Thanks!
