### ISSUE TITLE
Different behavior for local build and the deployed build

### ISSUE THREAD

**Issue by jerrygreen** [vercel/vercel#2823]
> BTW, I'm not sure if it's `now-cli` exactly, maybe it's related to the platform itself and I should send the feedback via some Zeit contact form instead. Then just redirect me and sorry for bothering

## Local one (it's successfully built):

![image](https://user-images.githubusercontent.com/13215662/63592127-4862a200-c5ca-11e9-8317-0a1317163992.png)

## On the now.sh (build failed):

![image](https://user-images.githubusercontent.com/13215662/63592433-08e88580-c5cb-11e9-9353-872aaee6f083.png)

**Comment by jerrygreen** [comment]
Whoops, my bad. This were some necessery files that by mistake were added to `.nowignore`

Particularly, it was `typings` folder with some declarations :)

By some reason it was working with Next v8 + `withTypescript` plugin. But with build-in typescript support on Next v9 it works in a bit different way. Shouldn't ignore typings for deployments.

Particularly, I've experienced problems because I've ignored file with this:

```
declare module '*.svg' {
  const content: any
  export default content
}
```

**Comment by JerryGreen** [comment]
Particularly, it was `types` folder, with, well... types :)

By some reason it was working with Next v8 + `withTypescript` plugin. But with build-in typescript support on Next v9 it works in a bit different way. Shouldn't ignore `types` for deployments.
