### ISSUE TITLE
Make `libssl` version match in build and production

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2824]
Currently, Lambdas are using a different version of `libssl` than the one we offer in our build environment. Instead, they should match precisely.

**Comment by styfle** [comment]
This was shipped 10 minutes ago and tested with `prisma2`.

Related to https://github.com/zeit/now-builders/issues/848

**Comment by momakes3** [comment]
@styfle The error with `prisma2` has reappeared on the latest version: `prisma@alpha` where binaries seem to have changed:
```
'linux-glibc-libssl1.0.1' -> 'debian-openssl-1.0.x'
'linux-glibc-libssl1.0.2' -> 'debian-openssl-1.0.x'
'linux-glibc-libssl1.1.0' -> 'debian-openssl-1.1.x'
'linux-glibc-libssl1.1.1' -> 'debian-openssl-1.1.x'
if you use rhel-based systems (fedora, centos, etc.), replace `debian` with `rhel`, e.g. 'rhel-openssl-1.1.x'
```

**Comment by styfle** [comment]
@momakes I don't think this is the same issue.

The error message was one of the following:
- `Photon could not resolve the needed binary for the current platform linux-glibc-libssl1.0.2.`
- `Error: Photon binary for current platform linux-glibc-libssl1.0.2 could not be found.`

See the original issue here: https://github.com/prisma/prisma2/issues/394

Perhaps its best to create an issue with the Prisma team if this is indeed a bug with their alpha version.

The latest version does include breaking changes per the [Prisma Release Notes](https://github.com/prisma/prisma2/releases/tag/2.0.0-preview017).

**Comment by momakes3** [comment]
@styfle I had managed to pin down with the Prisma team but forgot to update here 🙌

(FWIW: The error was exactly what you quoted, but it was because of a version mismatch between involved packages, where one generated `debian-openssl-1.0.x` and the other package was looking for `linux-glibc-libssl1.0.2`, correctly upgrading all solved it)
