### ISSUE TITLE
Now deployment don't works with mongoose

### ISSUE THREAD

**Issue by MatteoGauthier** [vercel/vercel#2825]
```
{ MongoNetworkError: failed to connect to server [mydatabse-cluster-atlas:27017] on first connect [MongoNetworkError: connection 5 to mydatabse-cluster-atlas:27017:27017 closed]

```

now version : 16.1.2
"mongoose": "^5.6.10",

**Comment by kyrcha** [comment]
Did you make sure that the cluster has [whitelisted connections from anywhere](https://docs.atlas.mongodb.com/tutorial/whitelist-connection-ip-address/) as described [here](https://zeit.co/guides/deploying-a-mongodb-powered-api-with-node-and-now)?
