### ISSUE TITLE
Feature Request: MarkoJS Builder

### ISSUE THREAD

**Issue by balupton** [vercel/vercel#2827]
Not sure where the best place is to request a now builder, but here seems to be it.

I think @marko-js https://markojs.com is the ideal candidate for a serverless and static platform such as now. As it allows for streaming rendering on the server side (superior to react's approach), and on the client side realtime vdom updates (its implementation makes it faster than react).

Making this issue merely to track this progress. I don't particularly have time to implement such a thing, and don't have any spare finances (I am a broke open-sourcer) to fund it either, but am very interesting in seeing this happen, as Marko from my evaluations seems [so damn nifty](https://markojs.com/docs/why-is-marko-fast/).

For those wishing to implement, these seem to be needed resources:

- marko starter (the equivalent of react's next.js)
    - https://github.com/marko-js/marko-starter
- marko server side rendering via streaming
    - https://markojs.com/docs/installing/#serving-a-simple-page
- now.sh builder docs
    - https://zeit.co/docs/v2/deployments/builders/developer-guide/
- existing now.sh builders
    - https://github.com/zeit/now-builders/tree/master/packages

My guess is:

1. if `config.data` exists in the build, send that to the marko render function
2. if `config.dynamic` is true, then export a lambda that renders to the response stream (option for the use case if the template needs to fetch realtime data before render), and if `config.dynamic` is falsey, then render to a static file

/cross-posted on [zeit's feature requests spectrum](https://spectrum.chat/zeit/feature-requests/markojs-builder-for-now-v2~4364860b-a281-4578-b086-136f0b937336)

**Comment by styfle** [comment]
Thanks for the suggestion!

We are not looking to maintain additional builders at this time but please feel free to make your own builder in a separate repository.
