### ISSUE TITLE
First-class support for `async` signature in `@now/node`

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#2828]
Right now, if the user uses `module.exports = async (req, res) => {}` and the promise rejects, it will result in an unhandled promise rejection.

Instead of receiving a 500, the user will get a 502 and wait for a long time.

**Comment by tim-phillips** [comment]
@styfle When using the `@now/node` runtime, you'll need to catch the error yourself and respond from there. I use something like this `handleErrors` higher order function: 

```js
const { send } = require('micro')

const sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms));

const sleepHandler = async (req, res) => {
  await sleep(5000)
  throw new Error('an unhandled async error')
}

const handleErrors = fn => async (req, res) => {
  try {
    return await fn(req, res)
  } catch (err) {
    console.error(err)

    const statusCode = err.statusCode || 500
    const message = err.message || 'Internal Server Error'

    send(res, statusCode, message)
  }
}

module.exports = handleErrors(sleepHandler)
```

If you want to set the status code when you throw the error, you can use `createError` from `micro`:

```js
const { createError } = require('micro')

const sleepHandler = async (req, res) => {
  await sleep(5000)
  throw createError(500, 'an unhandled async error')
}
```

Note, I'm using `micro` for the `send` and `createError` functions __only__. The runtime will tree shake with [`zeit/ncc`](https://github.com/zeit/ncc) and remove unused code.

https://github.com/zeit/micro/blob/ceaf102e7e6177e4028fde48f52362791fda3fc1/packages/micro/lib/index.js#L40-L90

https://github.com/zeit/micro/blob/ceaf102e7e6177e4028fde48f52362791fda3fc1/packages/micro/lib/index.js#L31-L38

**Comment by Ethan-Arrowood** [comment]
Fixed!
