### ISSUE TITLE
[now-python] The lambda function size exceeds the maximum size limit (50mb)

### ISSUE THREAD

**Issue by 422158** [vercel/vercel#2830]
Hello fellas. 
I have problem with deploying my project using now. Deployment of static parts of page goes well, but I have problem with deploying lambda. 

**I was very suprised that after build the lambda has ridiculous size (246mb)**. Here is the code of the lambda: https://pastebin.com/8SPRxz6y. 
Any idea what am I doing wrong and how to reduce lambda size?
Anyway I am great fan of now and pretty much all zeit projects. Keep it up.
Thanks

```import smtplib
from email.message import EmailMessage
from http.server import BaseHTTPRequestHandler
from urllib.parse import urlparse, parse_qs
import json

class calculationRequestHandler(BaseHTTPRequestHandler):
    
    gmail_user = 'xxxxxxx@gmail.com'  
    gmail_password = 'xxxxxxxxx'
    mail_recipient = 'xxxxxx@gmail.com'
    
    def sendGmail(self, sender, sender_pass, recipient, subject, content):
        msg = EmailMessage()
        msg['Subject'] = subject
        msg['From'] = sender
        msg['To'] = recipient
        msg.set_content(content)

        try:
            server = smtplib.SMTP_SSL('smtp.gmail.com', 465)
            server.ehlo()
            server.login(sender, sender_pass)
            server.sendmail(sender, recipient, msg.as_string())
        except Exception as err:
            print(err)
            return False
        
        return True

    def end_headers(self):
        self.send_header('Content-type','text/plain')
        # comment this line out before deployment
        # self.send_header('Access-Control-Allow-Origin', '*')
        BaseHTTPRequestHandler.end_headers(self)

    def parse_product(self, product):
        product_dict = json.loads(product)
        del product_dict["productImgSrc"]
        del product_dict["productHref"]
        return product_dict

    def generate_content(self, my_query):
        parsed_products = []
        for product in my_query['productList[]']:
            parsed_products.append(self.parse_product(product))
        return json.dumps({
            'email': my_query['email'][0],
            'produkty': parsed_products
        }, ensure_ascii=False, indent=2)

    def do_GET(self):
        parsed_url = urlparse(self.path)
        my_query = parse_qs(parsed_url.query)
        content = self.generate_content(my_query)
        subject = 'ziadost o kalkulaciu - ' + my_query['email'][0]
        self.sendGmail(self.gmail_user, self.gmail_password, self.mail_recipient, subject, content)
        self.send_response(200)
        self.end_headers()
        return
```

**Comment by transitive-bullshit** [comment]
I ran into a very similar issue using `pipenv` to manage my dependencies.

When I deployed with my `Pipfile` and `Pipfile.lock`, the resulting lambda was too large, but when I simply deleted the `Pipfile.lock`, the resulting lambda was significantly smaller.

This definitely seems like a bug to me because the `Pipfile.lock` was up-to-date with the `Pipfile`.

**Comment by styfle** [comment]
We added a configuration option for python in #3712 for `excludeFiles`.

For example , the following `vercel.json` will exclude all html files from being included in the serverless function.

```json
{
  "functions": {
    "api/**/*.py": {
      "excludeFiles": "**/*.html"
    }
  }
}
```

Or maybe you have a public directory with large assets, you could exclude it with the following:

```json
{
  "functions": {
    "api/**/*.py": {
      "excludeFiles": "public/**"
    }
  }
}
```

**Comment by benfwalla** [comment]
I am having the same issue. I tried leveraging `excludeFiles` in `now.json` as @styfle mentioned, but it still gave me a Lambda overload. It's disappointing that I cannot see the python build in the logs, even when I'm in debug mode.

**Comment by styfle** [comment]
@benfwalla Can your share the source code or the failing deployment url?

**Comment by wenerme** [comment]
Same error here https://zeit.co/wener/apis/3d3v24cah

```
02:35:37.320
Traced Next.js serverless functions for external files in: 17220.472ms
02:36:33.303
Compressed shared serverless function files: 55982.144ms
02:36:36.614
All serverless functions created in: 3308.763ms
02:36:36.640
The Serverless Function "packages/server/_error" is 74.89mb which exceeds the maximum size limit of 50mb. 
02:36:37.098
worker exited with code 20 and signal null
02:36:39.405
Done with "packages/server/next.config.js"
```

**Comment by benfwalla** [comment]
@styfle I wish I could help- but I switched everything over to node.js and got it working. From what I remember, including the `excludeFiles` had no impact on the python build... it continued to stall out once the build hit "Installing Dependencies".

**Comment by AleXoundOS** [comment]
I do confirm that `"excludeFiles": "**/*.ogg"` solves the issue in case of big `ogg` audio files (close to 50 MiB) which are present in the source tree including subdirectories.
Caution! If you set to exclude all files like this `"excludeFiles": "**/*.*"` python is not able to operate.

**Comment by talaikis** [comment]
+1 for Node.js, tried a lot things and this seems pretty random. For example, removing getServerSideProps from pages - works, then enabling them back - works for exactly one deployment, and then again - insane image size.

**Comment by franciscorubin** [comment]
I'm having the same issue. My public folder is quite big, and I have an api endpoint that seems to include all its content into its lambda function. 

I've tried this config but the error persists:
```
{
  "functions": {
    "pages/**": {
      "excludeFiles": "public/**"
    },
    "src/pages/**": {
        "excludeFiles": "public/**"
    },
  }
}
```

Also tried this ones:
```
{
  "functions": {
    "api/**": {
      "excludeFiles": "public/**"
    },
    "src/api/**": {
      "excludeFiles": "public/**"
    }
  }
}
```
But I'm getting the following error message:
```
Error: The pattern "src/api/**" defined in `functions` doesn't match any Serverless Functions. Learn More: https://vercel.link/unmatched-function-pattern
```

Other errors I've gotten on my tests:
```
Error: The Serverless Function "_error" is 165.1mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
```

```
Error: The Serverless Function "index" is 165.1mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size
```

```

21:03:55.575 | Error: Required lambda files exceed max lambda size of 50000000 bytes
-- | --
21:03:55.575 | at Object.module.exports.178.exports.build (/vercel/130cf4c7c099fac6/.build-utils/.builder/node_modules/@vercel/next/dist/index.js:6976:23)
21:03:55.575 | at async buildStep (/var/task/sandbox-worker.js:21364:20)
21:03:55.575 | at async mainSub (/var/task/sandbox-worker.js:21101:9)
21:03:55.575 | at async main (/var/task/sandbox-worker.js:20966:5)


```


UPDATE:
if I remove the api endpoint, the error goes away

**Comment by GoulartNogueira** [comment]
I'm facing the same problem.

When I try to `excludeFiles` from the python api, I no longer get the lambda maximum size error, but it seems to affect the `.js` from my Nuxt.js project.

    FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
    1: 0xa04200 node::Abort() [/node14/bin/node]
    2: 0x94e4e9 node::FatalError(char const*, char const*) [/node14/bin/node]
    3: 0xb7978e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/node14/bin/node]
    
     ... (a bunch of those)
    
    14: 0xdcfb3a v8::internal::Runtime_KeyedStoreIC_Slow(int, unsigned long*, v8::internal::Isolate*) [/node14/bin/node]
    15: 0x1401219  [/node14/bin/node]
    Sandbox exited with code null and signal SIGABRT

In another project, I had to split my project in two. One for python API's, the other for Nuxt.js.
It's a workaround, but it adds unnecessary integration complexity, CORS problems and harder maintainability. I really wish to make it the right way this time.

It's a Nuxt.js project, with python files, inside `root/api` folder.

Please help

**Comment by alicescfernandes** [comment]
@GoulartNogueira i'm having a similar issue, and for me its either related with the dependencies sizes or vercel's own build cache. As a workaround,  i've been able to deploy a python project with `vercel --force` command without any issues

**Comment by leerob** [comment]
Replaced by https://github.com/vercel/vercel/discussions/6516, please continue the discussion there 🙏
