### ISSUE TITLE
Make sure `@now/node` and friends crash (not 500) upon `TypeError`

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#2833]
This is important because we want to let the developer know about errors that stem from programming failures as opposed to e.g.: `fetch()` throwing due to a network error.

In practical terms, it would mean that a `TypeError` in a serverless Node.js function would result in `503` or similar as opposed to `500`.

**Comment by TooTallNate** [comment]
Closing because Now responds with a 502 status for `NO_STATUS_CODE_FROM_LAMBDA` error code (i.e. when a Lambda function exits before the function finishes invoking).
