### ISSUE TITLE
@now/next Issue with SignalR Library - 502 Error

### ISSUE THREAD

**Issue by johnnietirado** [vercel/vercel#2836]
When building application that makes use of SignalR with Now I am getting a 502 response, but when the code using SignalR is uncommented the issue is gone.

I have created an extremely simple repo. Instructions on how to reproduce are there.

[Repo](https://github.com/johnnietirado/signarlr-next)

As far as I can tell there is an issue specifically with SignalR's package, however, importing it into the file works fine, but once you are going to use it, then you get the 502 error.

Here is the Spectrum Thread: https://spectrum.chat/zeit/general/502-server-error-with-signalr-on-deployment~d9a239a3-afae-4f48-92a5-d0d889ff1fac

**Comment by Toumash** [comment]
Any ideas?

**Comment by dus4nstojanovic** [comment]
Any update? I have the same issue when I use `@microsoft/signalr`. I guess that implementation is the same.
