### ISSUE TITLE
[python] Trouble deploying functions with modules that depend on C based implementations

### ISSUE THREAD

**Issue by femi** [vercel/vercel#2839]
Wild guess here, I think `google-cloud-firestore` may depend on a C based implementation of grpc which I believe may be causing a deployment to fail. I'm not sure how you deal with lambda stuff under the hood, any assistance with this issue would be much appreciated.

I get this error when running my code using `now dev`:

```python 
ImportError: cannot import name 'cygrpc'
```
I get this error in the logs when I deploy the code with `now`:
```
Unable to import module 'now__handler__python': No module named 'google.cloud'
```
---

**To reproduce, here's a small application that imports `google-cloud-firestore`. Run `now dev` or `now` reproduce results.**

_requirements.txt_
```
Flask==1.0.3
google-cloud-firestore==1.2.0
```
_now.json_
```json
{
    "version": 2,
    "builds": [
      { "src": "**/*.py", "use": "@now/python", 
        "config": { "maxLambdaSize": "10mb" }
      }
    ]
} 
```

_index.py_
```python
from flask import Flask
from google.cloud import firestore

app = Flask(__name__)

@app.route("/", defaults={"path": ""})
@app.route("/<path:path>")
def catch_all(path):
    return "Hi Zeit", 200
```

**Comment by msdinit** [comment]
Hi, @styfle @TooTallNate 
Experimenting some more, it looks like the issue lies in builder not including all files installed by pip into final lambda, rather than native binary incompatibility:
```
from flask import Flask
import os
import logging

app = Flask(__name__)

@app.route("/", defaults={"path": ""})
@app.route("/<path:path>")
def catch_all(path):
    try:
        from google.cloud import firestore
    except Exception as e:
        logging.error(f"Google dir contents: {os.listdir('google')}")
        raise e
    return "Hi Zeit", 200
```
Modifying the handler to display contents of `google` directory shows that it only contains `protobuf` directory:
`Google dir contents: ['protobuf']`

**Comment by styfle** [comment]
Hi @msdinit 

Indeed, the contents of the google directory is only a `/google/protobuf/` directory.

I confirmed this by running the linux image locally and performing the same steps as the builder:

```
pip3 install --target . --upgrade werkzeug
pip3 install --target . --upgrade requests
pip3 install --target . --upgrade -r requirements.txt
```

When I run the same steps on macOS I see many subdirectories:

```
/google/api/
/google/api_core/
/google/auth/
/google/cloud/
/google/logging/
/google/longrunning/
/google/oauth2/
/google/protobuf/
/google/rpc/
/google/type/
```

When I compared the contents of the `/grpc` directory, they were (mostly) the same between Linux and macOS.

**Comment by msdinit** [comment]
@styfle 
Thanks for the reply. Could you tell me which Linux image are you using to run the commands? Running
```
pip3 install --target . --upgrade werkzeug
pip3 install --target . --upgrade requests
pip3 install --target . --upgrade -r requirements.txt
```
on my Ubuntu gives me `google` directory with following contents:
```
google/api
google/api_core
google/auth
google/cloud
google/logging
google/longrunning
google/oauth2
google/protobuf
google/rpc
google/type
```

**Comment by styfle** [comment]
We use `amazonlinux` with a few modifications. But this is enough to reproduce the behavior:

```Dockerfile
FROM amazonlinux
COPY requirements.txt requirements.txt
RUN yum install python3 && \
pip3 install --target . --upgrade werkzeug && \
pip3 install --target . --upgrade requests && \
pip3 install --target . --upgrade -r requirements.txt && \
ls -lA google
```

**Comment by ChristianDavis** [comment]
AWS has had support for python 3.8 for some time now, and it bumps the env up to Amazon Linux 2, which solves a ton of compiler issues. Not sure why you all have stayed on 3.6 but it's so far behind that it causes lots of little issues. #2979

**Comment by mike-wax** [comment]
@styfle is it possible to control the Python version with `pipenv`?

**Comment by styfle** [comment]
You can try out Python 3.9 today by setting an environment variable `FORCE_RUNTIME_TAG=canary`.

If you're still using legacy [`builds`](https://vercel.com/docs/cli#project-configuration/builds), then you'll need to use `@vercel/python@canary`.

**Comment by styfle** [comment]
Python 3.9 is available to all deployments today 🎉 

https://vercel.com/changelog/python-3-9-is-now-available
