### ISSUE TITLE
[now@python] 'now__handler__python': No module named 'google.auth'

### ISSUE THREAD

**Issue by maitham** [vercel/vercel#2841]
Hi, I'm trying to use firebase-admin in python. It works locally, with now dev I get a Error: pool is draining and cannot accept work. When deployed using now I get a  [now@python] 'now__handler__python': No module named 'google.auth' . 

Requirements.txt
```
slackclient==2.0.0
flask==1.0.2
requests
annoy
nltk
google-api-core[grpc] >= 1.7.0
google-api-python-client >= 1.7.8
google-cloud-firestore >= 0.31.0;
google-cloud-storage >= 1.13.0
firebase-admin
```

user.py
```
import os
import base64
import json
from flask import Flask, __version__, request, jsonify
import firebase_admin
from firebase_admin import credentials
from firebase_admin import firestore

app = Flask(__name__)


# Use a service account
certificate = json.loads(base64.decode(os.environ["GCLOUD_CREDENTIALS"])))
cred = credentials.Certificate(certificate)
firebase_admin.initialize_app(cred)
db = firestore.client()

@app.route("/profile", methods=["GET"])
def get_profile():
    user_id = request.args.get("user_id")
    doc_ref = db.collection(u'users').document(f"{user_id}")
    user_details = doc_ref.get()
    return jsonify(user_details.to_dict())

if __name__ == "__main__":
    app.run("0.0.0.0", port=5000, debug=True)
```

**Comment by styfle** [comment]
Hi @maitham 

A lot has changed and we now have support for Python 3.9 which might solve this issue.

Please try it out by setting an environment variable `FORCE_RUNTIME_TAG=canary`.

If you're still using legacy [`builds`](https://vercel.com/docs/cli#project-configuration/builds), then you'll need to use `@vercel/python@canary`.

Let me know if that solves this issue, thanks!

**Comment by styfle** [comment]
Python 3.9 is available to all deployments today 🎉 

https://vercel.com/changelog/python-3-9-is-now-available
