### ISSUE TITLE
CDN, compression, caching, throttling, SSL, etc

### ISSUE THREAD

**Issue by sedubois** [vercel/vercel#285]
I asked the question on Next.js' side but didn't get any luck (https://github.com/zeit/next.js/issues/985) so am asking here again 🙂 

I'm building a Next.js + Now (+ GraphQL etc) prototype app and recently upgraded to a paid Now account: https://github.com/relatenow/relate

The initial "advertising" I got of using Now is that you "just" run `now` and that's it 😉 But of course I understand if there is still more to it than just running this one-liner to get ready for production, and steps probably need to be taken to set up these things "in front" of the webapp:
1. SSL
2. fast DNS resolution
3. HTTP/2
4. load-balancing
5. compression
6. CDN (don't know where are Zeit data centers, compared e.g to Cloudflare's 102 data centers)
7. caching, cache storage optimization, localStorage caching
8. accelerated mobile page links (AMP)
9. mobile image optimization
10. throttling, DDOS protection
11. WAF

My understanding is that Now currently provides 1, 2, 3, 4, 5 in some form of another. It would be awesome to know:
1. where is Now currently at, what does it want to provide or not provide in the future, what's the roadmap?
2. what configuration does the user need to provide for each of these features to work, if any?
3. how performant are each of these functionalities compared to competition? (e.g DNS resolution speed, perf across different world regions)
4. what does Now recommend to use in conjunction with it, for the things it does not support?
5. Where can people go to learn to take care of the rest? Is there some better "checklist" than listed above?
6. Are there any examples or documentation to answer these questions or if not, could some documentation be created?

Thanks!

EDIT: restructured and enumerated the questions.

**Comment by mikeroelens** [comment]
+1

**Comment by jamo** [comment]
The short answer to a long question; now takes care of:
- provisioning SSL certificates (external can be added with `now cert`)
- compression when client supports/requests it
- DDoS protection on some scale in case it's a real concern, e.g., CloudFlare can easily be used in front of `now`
- audit logging 🤔 not sure if I misunderstood this point but audit logging afaik needs to be done in app itself (given you want to trace who does what and when)

**Comment by sedubois** [comment]
Thanks a lot. I restructured and enumerated the questions in the OP for more clarity, please have a look :-) For auditing, thanks I'll have a look on my side and asked for the feature on Graphcool side: https://github.com/graphcool/feature-requests/issues/93

**Comment by leo** [comment]
This repo is not meant to be used for such feature requests. As @jamo mentioned it, we already support many [of them](https://github.com/zeit/now-cli/issues/285#issuecomment-278745570). More is coming, but we'll keep our feature roadmap private! 😊
