### ISSUE TITLE
`libjpeg` and `libpng` are not installed with `@now/node`

### ISSUE THREAD

**Issue by sto3psl** [vercel/vercel#2857]
Hi everyone and thank you for this amazing project! I use `now` since some time but am now running into a small issue with `now/node`.

I'm building a service that optimizes and converts images on the fly and am using [imagemin](https://github.com/imagemin/imagemin) and [imagemin-webp](https://github.com/imagemin/imagemin-webp). Deployment to now.sh works just fine as seen here (https://imagemin-webp-now-d5mnaefey.now.sh/img/sto3psl.png).

The code I'm deploying can be found in this repository -> https://github.com/sto3psl/imagemin-webp-now

Locally everything works but after deploying to now.sh, I get the following errors for `jpg` and `png` source files respectively:

```
curl 'https://imagemin-webp-now-d5mnaefey.now.sh/?img=https://imagemin-webp-now-d5mnaefey.now.sh/img/sto3psl.jpeg'

JPEG support not compiled. Please install the libjpeg development package before building.
Error! Could not process file /tmp/355075bf-32c8-41b0-b701-34b2e8bb8b01
Error! Cannot read input picture file '/tmp/355075bf-32c8-41b0-b701-34b2e8bb8b01'
```

```
curl 'https://imagemin-webp-now-d5mnaefey.now.sh/?img=https://imagemin-webp-now-d5mnaefey.now.sh/img/sto3psl.png'

PNG support not compiled. Please install the libpng development package before building.
Error! Could not process file /tmp/5b9e21e7-e9f8-494d-8668-feaf45a69a7f
Error! Cannot read input picture file '/tmp/5b9e21e7-e9f8-494d-8668-feaf45a69a7f'
```

`webp` input files work just fine and serve the `webp image`.

```
curl 'https://imagemin-webp-now-d5mnaefey.now.sh/?img=https://imagemin-webp-now-d5mnaefey.now.sh/img/sto3psl.webp'
```

It seems like the lambda doesn't have `libpng` and `libjpeg` installed. Is there anything I can do to fix that? I have seen similar issues with a dependency on `sharp` but couldn't figure out what to do there. It would be super nice to have `imagemin-webp` supported with `@now/node`.

Let me know if you need more information and thank you in advance!

**Comment by sto3psl** [comment]
Thanks @styfle, I will try that. Is it documented somewhere which package managers are available (or what the lambdas distro is)?

**Comment by sto3psl** [comment]
> You could try adding `now-build` to your package.json to install the native dependencies.

This worked for `libpng-devel` but the error about jpeg support persists. 

I tried adding `libjpeg-turbo` or `libjpeg-turbo-devel` but `imagemin-webp` still complains about no jpeg support (`yum` doesn't find `libjpeg-devel`).  
Any ideas what I need to do to get this working?

**Comment by alexandersch** [comment]
I'm having the same issues using `next-optimized-images`. Tried to install through yum and the packages installed successfully.

```
Installed:
--
libpng-devel.x86_64 2:1.2.49-2.14.amzn1
Dependency Installed:
libpng.x86_64 2:1.2.49-2.14.amzn1
```

But the error `PNG/JPEG support not compiled. Please install ...` still persists.

Any updates on this?

**Comment by alopes** [comment]
@paulogdm, as discussed, I've written a simple example that reproduces this problem.

https://github.com/alopes/libpng-next

**Comment by styfle** [comment]
I realized that the script was running after dependencies were installed in my [previous comment](https://github.com/zeit/now/issues/2857#issuecomment-521015657).

I updated that comment to use a `preinstall` script which works with your example.

**Comment by styfle** [comment]
Starting today, you will no longer need to add the [yum install script](https://github.com/zeit/now/issues/2857#issuecomment-521015657) because those dependencies will be available at build time.

Please be aware that these binaries are **not** available at runtime.

**Comment by sto3psl** [comment]
> Please be aware that these binaries are not available at runtime.

It's great that these dependencies will be available at build time but that wasn't the problem of this issue. My service optimises images on the fly for every request, which means I need `libjpeg` and `libpng` **at runtime**.

**Comment by styfle** [comment]
Hi @sto3psl 

You're right, the comments here are different problems then what you described in the issue description.

I'm closing this issue because we do not plan to modify runtimes. We want the runtime to be as small as possible for fast cold-starts.

A solution for you might be changing your build script to copy necessary dependencies into the runtime. You could also file an issue with imagemin or sharp like we did with [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda/issues/37#issuecomment-541415653) which was able to add the necessary dependencies into the npm package.

In the future, we might add support for user-defined Layers for runtimes but I can't give an ETA at this time.
