### ISSUE TITLE
env variables set with now secrets are undefined

### ISSUE THREAD

**Issue by Richifg** [vercel/vercel#2867]
Hello! I'm having difficulties deploying with now and having the secrets I defined using CLI be anything other than undefined on the final build.

I've set several secrets for testing purposes and all of them return undefined

```console.log(process.env.APIKEY);
console.log(process.env.TEST);
console.log(process.env.MY_VARIABLE);
console.log(process.env.NODE_ENV);
```

only NODE_ENV returns production as it should.
This is my now.json file:

```{
  "name": "MyTube",
  "version": 2,
  "build": {
    "env": {
      "APIKEY": "@api-key",
      "TEST": "@test",
      "MY_VARIABLE": "@acme-api-key"
    }
  },
  "env": {
    "APIKEY": "@api-key",
    "TEST": "@test",
    "MY_VARIABLE": "@acme-api-key"
  }
}
```

When I deploy using ```now``` my project is built without any issues.

I see in the log the now is correctly running the build script in my package.json
``` "scripts": 
    "build": "webpack --mode production",

```

Any idea what could be the problem here?

You can check the deploy-env-config branch at my repository [here](https://github.com/Richifg/MyTube/tree/deploy-env-config)

**Comment by leo** [comment]
It appears like you are not passing the environment variables on to Webpack.

ccing @timneutkens, who might be able to help with this.
