### ISSUE TITLE
now dev return spawn E2BIG

### ISSUE THREAD

**Issue by michel-p** [vercel/vercel#2878]
# Bug report

Suddenly after a couple weeks of development, my now dev command line doesn't work anymore. It started when I closed the terminal where it was running and opened a new one.

Now, it does the same even with a basic nextjs project
![image](https://user-images.githubusercontent.com/9078109/63739652-8e688000-c8c0-11e9-8c19-b7aac913e48f.png)

And even with the now init nextjs command line
![image](https://user-images.githubusercontent.com/9078109/63739719-db4c5680-c8c0-11e9-811d-0cae92f37176.png)

## To Reproduce

now init nextjs
cd nextjs
now dev

## Expected behavior

The now dev server is properly launched and I can debug my code.

## System information
- OS : macOS 10.14.6 - Memory: 16 GB
- Node : v10.16.0 (but tested with 8.x.x also)
- yarn 1.16.0 (but tested with 1.14 and 1.15 also)
- Version of Next.js: 9.0.5

## Additional context

It happened to my collegues too. After a while, the command line just doesn't work anymore.
We have tried : 
 - Reinstall node, update node, downgrade node
 - Reinstall yarn, update yarn, downgrade yarn
 - Uninstall / Reinstall now
 - rm -rf /Users/....../Library/Caches/co.zeit.now/ 

Nothing works. The command line throw the error directly after the yarn command, just like if it was a problem with the size of a file (maybe logs ?) or the number of arguments in a function?

Anyone can help ? 
Thank you very much

**Comment by leo** [comment]
Thank you for reporting this. We'll take a look!

**Comment by michel-p** [comment]
@leo Any news on this problem ? Have you at least been able to reproduce ?

**Comment by leo** [comment]
@michel-p Not yet, unfortunately. We'll prfioritize it!

**Comment by TooTallNate** [comment]
@michel-p Can you give us some insight about how many environment variables you have configured on your system? We believe that is related to the issue in this case.

**Comment by isweir** [comment]
vercel dev
Vercel CLI 28.5.3
> Creating initial build
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: spawn cmd.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)      
Emitted 'error' event on ChildProcess instance at:
    at cp.emit (C:\Users\IsWei\AppData\Roaming\npm\node_modules\vercel\node_modules\@ver
cel\build-utils\dist\index.js:17051:29)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {    
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn cmd.exe',
  path: 'cmd.exe',
  spawnargs: [ '/C', 'yarn run dev' ]
}

Node.js v19.1.0
Error: Builder exited with 1 before sending build result

I got the same issue when i use vercel dev, it doesn't work, so i will not use vercel, i got a clean windows, if i get this error it must be everybody have this error.

**Comment by cookieJarYum** [comment]
hello, ~2 years later I get the exact same crash as the user above. And similarly, my setup is easy to reproduce - fresh install of Windows 11 with Node LTS installed using NVM (Node Version Manager)

**Comment by EndangeredMassa** [comment]
> fresh install of Windows 11 with Node LTS installed using NVM (Node Version Manager)

I tried this and it worked for me.

@cookieJarYum Can you share more details about your project? Are you using a lot of environment variables? What does your `buildCommand` look like? If you can share source code, that'd be even more helpful.

**Comment by EndangeredMassa** [comment]
Closing this for now. Open a new issue with more details if this is still an issue. Thanks!
