### ISSUE TITLE
Throw error if "api" + "pages/api" is used in @now/next

### ISSUE THREAD

**Issue by adamgruber** [vercel/vercel#2887]
Stumbled upon something interesting with [now's zero-config api](https://zeit.co/guides/upgrade-to-zero-configuration#with-zero-configuration) and [Next's API routes](https://nextjs.org/docs#api-routes). I had a Next 9 project with the following folder structure (truncated for readability):

```
.
├── api
│   └── index.js <--- API Utility Helper
├── pages
│   ├── api
│   └── users.js <--- Next API Route
└── static
```

I was not aware of the zero-config API feature and was using the top-level `/api` folder to organize api-related utilities. I ran the app locally with `now dev` and everything worked as expected. The problem, however, came when I deployed this with `now`. The calls to `/api/users` no longer succeeded and instead would return a `404` response code. Strangely though, the expected data was also returned.

After reading through the docs and learning about now's zero-config API feature, I realized that  the top-level `api` folder was causing a conflict with Next's API routes. The solution seems to be use one or the other and not both, however I still don't understand what causes the `404` response with data.

I have an [example repo](https://github.com/adamgruber/now-api-test) deployed to `https://now-api-test.adamgruber.now.sh` with two endpoints. One using the zero-config now API and one using Next API routes. When hitting these endpoints, I get the following responses:

```
❯ http https://now-api-test.adamgruber.now.sh/api/next
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Type: application/json; charset=utf-8
cache-control: public, max-age=0, must-revalidate
content-length: 13
date: Tue, 27 Aug 2019 14:26:22 GMT
server: now
strict-transport-security: max-age=63072000
x-now-cache: MISS
x-now-id: iad1:sfo1:pdrjv-1566915981899-88066e99a277
x-now-trace: iad1

{
    "next": true
}

❯ http https://now-api-test.adamgruber.now.sh/api/now
HTTP/1.1 200 OK
Connection: keep-alive
Content-Type: application/json; charset=utf-8
cache-control: public, max-age=0, must-revalidate
content-length: 12
date: Tue, 27 Aug 2019 14:27:37 GMT
etag: W/"c-yfKwHQSNx6jM3PPrBNeiUcNYTfQ"
server: now
strict-transport-security: max-age=63072000
x-now-cache: MISS
x-now-id: iad1:sfo1:pdrjv-1566916057438-ebb579b76baa
x-now-trace: iad1

{
    "now": true
}

```

I'm really curious to know what causes this odd behavior and why it didn't manifest when using `now dev`.

**Comment by leo** [comment]
Thanks for reporting this!

In general, if you're using a framework that introduces API support on its own (like Next.js), we advise against using the Now-native `api` directory.

In turn, we should render a error message if you're trying to use both.

----

However, I'd love to understand what motivated you to use both?

**Comment by leo** [comment]
Got it. Thanks for clarification, @adamgruber.

I've updated the issue title to reflect what changes are needed.

**Comment by leo** [comment]
@adamgruber Behind the curtains, `api` is actually enabled by us providing default `routes`. In your case, those are – therefore – overwritten by the default `routes` Next.js provides when being deployed. In turn, only one of the APIs succeeds to be served.

**Comment by six7** [comment]
Been hitting this as well - an error when running now dev or when deploying would be great! My use case for a root-level api route involved the puppeteer example, which doesn't run on node 12 as it's unable to launch chrome (works with 8-9 though)

that's why I tried to set the engine to 8>9 in api/screenshot package.json - I'm unable to do that in next's routing i'm afraid.
