### ISSUE TITLE
Invalid API version being used

### ISSUE THREAD

**Issue by leo** [vercel/vercel#2889]
As you can see [here](https://sentry.io/organizations/zeithq/issues/1190835209/?referrer=slack), there's a case in which we throw an "Invalid API version" error:

![image](https://user-images.githubusercontent.com/6170607/63791282-79f5a900-c8fb-11e9-8da5-335d3746834f.png)

![image](https://user-images.githubusercontent.com/6170607/63791291-7e21c680-c8fb-11e9-8fbf-7b5fad811c76.png)

**Comment by AndyBitz** [comment]
This is because `https://api.zeit.co/v5/now/deployments/%2F` is forwarded to the wrong endpoint.

https://zeit.slack.com/archives/CLDDX2Y0G/p1566984698001600
