### ISSUE TITLE
failed to deploy single index.html file

### ISSUE THREAD

**Issue by endziu** [vercel/vercel#290]
trying to deploy a folder with single html file.
it failed on windows and on ubuntu.
I'm using now 4.2.0.

and I get this error:

> Deploying C:\dev\testing
> Using Node.js 7.0.0 (default)
> Ready! https://testing-qstggvtrzz.now.sh (copied to clipboard) [2s]
> Initializing…
> Building
> ▲ npm install
> ⧗ Installing:
>  ‣ serve@^3.2.3
> ✓ Installed 167 modules [13s]
> ▲ npm start
> > testing@ start /home/nowuser/src
> > serve ./content
> /home/nowuser/src/node_modules/serve/lib/listening.js:7
> const copyToClipboard = async text => {
>                               ^^^^
> SyntaxError: Unexpected identifier
>     at Object.exports.runInThisContext (vm.js:76:16)
>     at Module._compile (module.js:545:28)
>     at Module._extensions..js (module.js:582:10)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/nowuser/src/node_modules/async-to-gen/register.js:42:5)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/nowuser/src/node_modules/serve/lib/index.js:11:19)
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
> npm ERR! node v7.0.0
> npm ERR! Exit status 1
> npm ERR! code ELIFECYCLE
> npm ERR! Failed at the testing@ start script 'serve ./content'.
> npm ERR! testing@ start: `serve ./content`
> npm ERR! If you do, this is most likely a problem with the testing package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR!     serve ./content
> npm ERR!     npm bugs testing
> npm ERR! There is likely additional logging output above.
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls testing
> npm ERR! Linux 4.7.0-coreos
> npm ERR! node v7.0.0
> npm ERR! code EACCES
> npm ERR! syscall open
> npm ERR! 
> npm ERR! Please try running this command again as root/Administrator.
> npm ERR! Please include the following file with any support request:
> npm ERR!   errno: -13,
> npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.2464837890'
> npm ERR!   code: 'EACCES',
> npm ERR!   path: 'npm-debug.log.2464837890' }
> npm ERR!     /home/nowuser/src/npm-debug.log
> npm ERR! Linux 4.7.0-coreos
> npm ERR! npm  v3.10.9
> npm ERR! 
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR! npm  v3.10.9
> npm ERR! path npm-debug.log.2464837890
> npm ERR! errno -13
> npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.2464837890'
> npm ERR!   syscall: 'open',

a bug? or did I miss something?

**Comment by MikaFima** [comment]
Same here

**Comment by shouze** [comment]
same here

**Comment by shouze** [comment]
And... it's the case since about at least 2 days

**Comment by matheuss** [comment]
@endziu @MikaFima @shouze what's the output of `node --version`?

**Comment by leo** [comment]
[Fixed!](https://github.com/zeit/now-cli/releases/tag/4.2.2) 😊

**Comment by pulkitnandan** [comment]
saw it again today with latest nuxt and following package json.

{
  "name": "dbs",
  "version": "1.0.0",
  "description": "Dbs hackathon frontend team 9",
  "author": "Rohit Nandan <pulkitnandan@gmail.com>",
  "private": true,
  "scripts": {
    "dev": "nodemon -w server.js -w nuxt.config.js -w api/ --exec babel-node server.js  --presets es2015",
    "build": "npm run clean && npm run build-server && npm run build-client",
    "start": "npm run deploy",
    "precommit": "npm run lint",
    "lint": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "clean": "rm -rf build",
    "build-client": "nuxt build && cp -R .nuxt build/",
    "build-server": "babel -s -D . --ignore node_modules --presets es2015 --plugins babel-plugin-transform-runtime -d build/",
    "prod": "NODE_ENV=production node build/server.js",
    "pm2-delete": "pm2 delete all",
    "pm2-status": "pm2 status",
    "pm2-logs": "pm2 logs",
    "pm2-run": "NODE_ENV=production node build/server.js --env production",
    "pm2-rerun": "pm2 restart dbs",
    "deploy": "npm install && npm run build && npm run pm2-run",
    "redeploy": "npm install && npm run build && npm run pm2-rerun",
    "play": "vbuild -c play.config.js -d",
    "build:play": "vbuild -c play.config.js"
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-2"
    ]
  },
  "dependencies": {
    "axios": "^0.15.3",
    "cross-env": "^3.1.4",
    "express": "^4.14.0",
    "logatim": "^0.9.0",
    "nuxt": "latest"
  },
  "devDependencies": {
    "babel-cli": "^6.22.2",
    "babel-eslint": "^7.1.1",
    "babel-preset-es2015": "^6.22.0",
    "babel-preset-stage-2": "^6.22.0",
    "eslint": "^3.13.1",
    "eslint-config-standard": "^6.2.1",
    "eslint-plugin-html": "^1.7.0",
    "eslint-plugin-promise": "^3.4.0",
    "eslint-plugin-standard": "^2.0.1",
    "nodemon": "^1.11.0",
    "pm2": "^2.4.0",
    "vbuild": "^6.24.13",
    "vue-play": "^3.1.3"
  }
}
