### ISSUE TITLE
Deployment continues even in case of failure

### ISSUE THREAD

**Issue by sedubois** [vercel/vercel#291]
I have an issue with my postinstall hook that I still need to understand, and which led to this error when deploying (https://relate-wpkhzqfgrz.now.sh/):
`Error: `npm run-script postinstall` failed for relate@0.0.7 (exit code 1)`

But the install proceeded anyway instead of stopping:
```
npm install
Installing package apollo-client@^0.8.2
Installing package auth0-lock@^10.11.0
Installing package body-parser@^1.16.0
...
```

This is my project: https://github.com/relatenow/relate

**Comment by leo** [comment]
In that "postInstall" script, you're trying to write to disk. That's not possible outside the build step (like stated [here](https://zeit.co/docs/deployment-types/node#file-system-specifications)).

**Comment by sedubois** [comment]
@leo yes I understood that, but still, even with the postinstall failing, the install was continuing regardless. Install should not happen if postinstall fails.

**Comment by sedubois** [comment]
I think recently you made changes to error handling, so I'll just retry and report back if more issues.

**Comment by leo** [comment]
@sedubois I think that was just a matter of the logs being streamed in the wrong order (which was [fixed](https://github.com/zeit/now-cli/commit/ea35eb19ee0ee2d6a177f91473abca811acfaaf3) already). `postinstall` always runs after the installation of the packages, so the platform installing deps afterwards just isn't possible/doesn't make sense. In turn, I think it's related to the logs, like I said. 😊
