### ISSUE TITLE
--no-clipboard is ignored when using now.json

### ISSUE THREAD

**Issue by gajus** [vercel/vercel#292]
Starting a command:

```bash
now --docker --alias applaudience-showtime-data-sources-worker --no-clipboard --debug

```

Ends with:

```
> Success! Alias created (...):
https://applaudience-showtime-data-sources-worker.now.sh now points to https://applaudienceshowtime-data-sources-worker-ryhbkahjqh.now.sh (...) [copied to clipboard]
> Deployment complete!

```

I am suspecting this is because options are not correctly merged with now.json.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
