### ISSUE TITLE
Typo in error message: "occurres"

### ISSUE THREAD

**Issue by foundryspatial-duncan** [vercel/vercel#2931]
The current stable version of now cli has an error message when you're messing with URL routes that says:

> The segment "[something]" **occurres** more than one time in your path

"occurs" is spelled wrong [in detect-routes.ts](https://github.com/zeit/now/blob/236f5f4159fb15891233aa38c389d6443dbdcf91/packages/now-build-utils/src/detect-routes.ts#L229) (and also in a [comment](https://github.com/zeit/now/blob/236f5f4159fb15891233aa38c389d6443dbdcf91/packages/now-build-utils/src/detect-routes.ts#L121) elsewhere in that file)

This is kinda related to #2761 :)

**Comment by styfle** [comment]
Thanks for creating this issue! Would you like to submit a PR to fix it?
