### ISSUE TITLE
Automatic redirect mapping of www

### ISSUE THREAD

**Issue by plug-n-play** [vercel/vercel#2939]
Currently, in order to create a www mapping for a domain, we need to create a new ZEIT Now project with just now.json and the configuration of this redirect.

Feature request:
1. It would be ideal if the platform is smart enough to create this automatically in the background.
2. If due to any reason a user wants to remove this mapping (not sure why would this be done), there can be setting in admin panel to remove that

2 above can be ignored until there are enough user requests to do so.

**Comment by mcsdevv** [comment]
Transferring as this is a feature request rather than a documentation request.

**Comment by leo** [comment]
We will provide a feature for this. Here's the internal tracking link: https://github.com/zeit/front/issues/4195

**Comment by styfle** [comment]
This feature has been implemented!

Read more on the blog post: https://zeit.co/blog/redirecting-domains
