### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by dbpolito** [vercel/vercel#294]
`Dockerfile` support is really nice, thanks for that :+1: but would be even nicer if we have `docker-compose.yml` support...

❤️❤️❤️❤️❤️❤️❤️

**Comment by tercerapersona** [comment]
is it in Now plans?

**Comment by pjhenning** [comment]
Would love to see this feature added!

**Comment by kuldeepkeshwar** [comment]
@rauchg any update on this? this would make things more easy

**Comment by mtheoryx** [comment]
Compose is where the magic is, and I'd really appreciate support for this. Any updates at all?

**Comment by arashsa** [comment]
Yes, would love updates on this.

**Comment by 0xjjpa** [comment]
Honestly it would be pretty neat 👌

**Comment by jjant** [comment]
Any updates on this?

**Comment by rauchg** [comment]
@jjant we're on it, along with many other improvements to Docker deployments :)

**Comment by aaayushsingh** [comment]
This issue is closed, does zeit support docker-compose now?

**Comment by styfle** [comment]
@aaayushsingh It's not closed. Maybe you are looking at the linked issues that got closed?

See the "Open" badge at the top:

![open](https://user-images.githubusercontent.com/229881/37674817-1374caca-2c4a-11e8-9c3f-631104a850d5.png)

Also note that you can achieve the links feature of docker-compose by using [path alias](https://zeit.co/blog/path-alias).

But of course we are all still waiting for proper docker-compose support 😄

**Comment by Frondor** [comment]
Come on Zeir! You can do eet! :muscle:

**Comment by dannav** [comment]
Hey all! I went ahead and built a library that brings docker compose support to now: https://github.com/dannav/now-compose

Enjoy!

**Comment by phil-lgr** [comment]
In the meantime, is it possible to specify the path to the Dockerfile? e.g. I want to deploy 2 dockerized app from one repo 😄

**Comment by phil-lgr** [comment]
ok, found #507

**Comment by YarivGilad** [comment]
> @jjant we're on it, along with many other improvements to Docker deployments :)

@rauchg - Any updates since?
This could be a game-changer...
:)

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2

**Comment by tmigone** [comment]
Looks like they pulled the plug on supporting Docker, but were very quiet on the 2.0 announcement.
A shame really.

**Comment by dannav** [comment]
It looks like they are looking to compete directly with netlify. Nothing wrong with that, they may have a better market there. In regards to docker-compose support it doesn't look like it's necessary anymore as now 2.0 has a significantly different development workflow. We'll see what comes. Hopefully zeit can give us a bit more feedback on the roadmap

**Comment by dohomi** [comment]
You can follow the discussion here: https://spectrum.chat/zeit/now?thread=96985341-e17f-4af4-a330-c726774ed436

**Comment by tapsboy** [comment]
https://spectrum.chat/?t=96985341-e17f-4af4-a330-c726774ed436 might be a more appropriate forum for carrying on with the product discussion

**Comment by wiiiimm** [comment]
For projects that required `docker-compose.yml`, I have built my own Kubernetes cluster over in Google Cloud and all my projects requiring this are running happily on that cluster of 5 servers.
