### ISSUE TITLE
Builder for Clojure

### ISSUE THREAD

**Issue by gunar** [vercel/vercel#2949]
Would it be possible we get a builder for clojure? e.g. `@now/clojure`.

How much work would that entail?

Thanks for `now`, I *love* the DX. Really great work gents.

**Comment by TooTallNate** [comment]
At this time, we are focusing on maintaining the [core builders](https://zeit.co/docs/v2/advanced/builders/#official-builders) listed in our documentation. However it's definitely be possible to write a custom builder and publish it to `npm` for you and others to use.

Please see the ["Developing Your Own Builder"](https://zeit.co/docs/v2/advanced/builders/#developing-your-own-builder) documentation for instructions on how to do that.
