### ISSUE TITLE
Error response from daemon: network brddepl not found

### ISSUE THREAD

**Issue by purplecones** [vercel/vercel#295]
I deployed a Dockerfile project and got the following error

https://mantra-accounts-test-skfrjivapf.now.sh/
```
Successfully built 9263a3c93c2c
Storing image
Deploying image
Container started
Error response from daemon: network brddepl not found
```

Redeploying without any changes was successful, not sure why it failed first time.
https://mantra-accounts-test-fntitbpsdt.now.sh/

**Comment by OlliV** [comment]
Sorry, that shouldn't be shown to the user. It's completely normal and expected error.
Did the first deployment work despite the error?

**Comment by purplecones** [comment]
@OlliV The first deployment did not work. As you can see by following the link, it is stuck at that error. However, deploying a second time worked fine.

**Comment by OlliV** [comment]
ok, thanks. Debugging...

**Comment by OlliV** [comment]
Thanks, we found a very rare error path where the deployment provisioning will keep waiting indefinitely in case of a failure.
