### ISSUE TITLE
[now dev] Empty variable 'process.title'

### ISSUE THREAD

**Issue by menberg** [vercel/vercel#2950]
When running `now dev` locally, the expected value of _process.title_ should contain "node". On NOW CLI v16.1.3, it returns an empty string instead.

Probably related to this issue: https://github.com/zeit/now/issues/2503

**Comment by TooTallNate** [comment]
Thanks for the report. However, I can not seem to reproduce this. Can you share some more details about your setup (operating system, etc.) and/or share the code that you are trying to execute?

```
$ now -v
16.1.3

$ cat api/index.js 
module.exports = (req, res) => {
  console.log(process.title);
  res.end(process.title);
};

$ curl localhost:3000/api/index
node

**Comment by styfle** [comment]
Confirmed this is working correctly.
