### ISSUE TITLE
Important failure in alias

### ISSUE THREAD

**Issue by menduz** [vercel/vercel#296]
We have automated deployments, today we had a billing problem, and our account was downgraded. The deployment don't allow files higher than 1MB but it doesn't fail.

Although we were able to reassign the alias to the new _malformed_ new deployment and for obvious reasons it doesn't work anymore in the new aliased release.

Proposal:

If the account doesn't support aliases, or the alias have a paid deployment and we are assigning an OSS one; throw an error when trying to reassign the alias.

**Comment by leo** [comment]
There's no such thing as "paid deployments". The plan is always related to your account, not your deployments. If you're account was downgraded, you won't be able to upload files bigger than allowed anymore.
