### ISSUE TITLE
Failure running now alias with no arguments produces error

### ISSUE THREAD

**Issue by sammdec** [vercel/vercel#297]
I have a now.json file with the following in it 
```json
{
  "aliases": ["mysite.com"]
}
```

and I used to be able to run `now alias` and that would then assign my alias to the latest deployment. However, now when trying to run it I get given
```bash
Error! Please specify a valid subcommand: ls | set | rm
...
```

This has been able to be reproduced by @matheuss

**Comment by rauchg** [comment]
Thanks for the issue report @samjbmason

**Comment by hugomd** [comment]
@samjbmason I believe `now.json` specifies the use of `alias` rather than `aliases`, even if multiple aliases are in use.

**Comment by leo** [comment]
[Correct](https://zeit.co/blog/easy-aliasing) 😊
