### ISSUE TITLE
Cannot find module '.' 

### ISSUE THREAD

**Issue by joshleblanc** [vercel/vercel#2978]
I'm fairly sure this is a now dev problem because I ran into this error converting a previously working endpoint to a now serverless function.

The build is failing on `export * from '.'`, inside a library import.

I've created a MVCE here: https://github.com/HorizonShadow/now-error-mcve

Running `now dev`, and navigating to `localhost:3000/api/test` will produce

```
> Built @now/node@latest:api/test.ts [8s]
Cannot find module '.'
Did you forget to add it to "dependencies" in `package.json`?
```

**Comment by styfle** [comment]
Hi @HorizonShadow 

Thanks for reporting this issue.

I've identified the root cause and created an issue here: https://github.com/zeit/node-file-trace/issues/66

**Comment by capaj** [comment]
@styfle when does this get out to an NPM release?

**Comment by styfle** [comment]
It's available in the canary channel today. `npm i -g now@canary` or if you are using builders you can change now.json to `@now/node@canary`.

It will be available soon on the stable channel.

**Comment by capaj** [comment]
@styfle thanks. Canary works nicely.
