### ISSUE TITLE
Python3.7 support

### ISSUE THREAD

**Issue by zhammer** [vercel/vercel#2979]
Is it possible to a deploy a python lambda using python3.7 runtime? I've been looking at a few posts (https://github.com/zeit/now/issues/2849, https://spectrum.chat/zeit/now/issue-with-now-json-on-a-monorepo-with-python-3-7-and-flask~7e566987-b4d5-4134-af13-a1c1672925d6) which seem to suggest it should be possible (both in `dev` and deployed).

But the python/build code suggests that only 3.6 is supported in deployment.
https://github.com/zeit/now/blob/db1a2e6482e134a2956a1fa6b2dddda5861e2eea/packages/now-python/src/index.ts#L178-L185

**Comment by styfle** [comment]
Hi @zhammer 

We only support Python 3.6 at this time.

**Comment by zhammer** [comment]
understood! would love to see 3.7 runtime added.

**Comment by styfle** [comment]
Thanks for the feedback! I marked this as a feature request 👍

**Comment by remorses** [comment]
I also would like to use 3.7, many new packages depend on new features like `dataclasses` and new typing features

**Comment by styfle** [comment]
We would probably want to add support for Python 3.8 since that is available today.

The problem that needs to be solved is running multiple versions of python side-by-side in the same build environment, since today it is installed as `yum install python3`.

A cursory look at the docs makes me think we could build it from source with the `altinstall` option:

```
curl -L -o Python-3.8.0.tgz https://www.python.org/ftp/python/3.8.0/Python-3.8.0.tgz
tar xzf Python-3.8.0..tgz
cd Python-3.8.0
./configure --enable-optimizations
make altinstall
python3.8 --version
```

We plan to make our build environment open source so perhaps multiple python versions could be added after that is complete.

**Comment by remorses** [comment]
Also check out [`pyenv`](https://github.com/pyenv/pyenv), you can install different python versions like `python3.6` and `python3.8`
Install pyenv using [this](https://github.com/pyenv/pyenv-installer)
Then run
```
pyenv install 3.8.0
pyenv install 3.7.4
pyenv install 3.6.6
pyenv global 3.6.6 3.7.4 3.8.0
```
Then the default `python` command will use 3.6 and other version are accessible via `python3.6` and `python3.7`.
The same for `pip`.

**Comment by remorses** [comment]
Then we should release a new version of the runtime that uses another python version or instead add a way to configure runtimes with function specific env variables like suggested here #3356 (imo a lot better) to change python version (this requires changing the building process code so i suggest doing it together with the python bump)

**Comment by styfle** [comment]
We use package.json [engines](https://docs.npmjs.com/files/package.json#engines) to select the Node.js version.

Is there an equivalent for `requirements.txt` or `Pipfile` that could be used to select the Python version?

**Comment by remorses** [comment]
Not an universal way but if you use pyenv you can create a file called `.python-version` with the version number and the local shell will use that version.

**Comment by zhammer** [comment]
`Pipefile` can also be a bit confusing as it often specifies the intended python version

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by dnk8n** [comment]
The biggest advantage for me (might as well work on python 3.8 though) is the ability to use [convenient new sqlite3 options](https://docs.python.org/3/library/sqlite3.html#sqlite3.Connection.backup).

e.g.

```
import sqlite3

source = sqlite3.connect('db.sqlite3')
conn = sqlite3.connect(':memory:')
source.backup(conn)
```

Having the ability to continue with a small in-memory database connection would have a great performance bonus when deployed on Zeit.

Until we get this, I have to [follow one of these solutions](https://stackoverflow.com/questions/3850022/how-to-load-existing-db-file-to-memory-in-python-sqlite3) to get the same outcome

**Comment by tedmiston** [comment]
Bumping for support of Python 3.7 and/or 3.8.  [I used `dataclasses` a lot.]

**Comment by leo** [comment]
Thank you for sharing this! We're tracking this internally and we'll be updating new Deployments to the most recent version of Python soon.

**Comment by edalongeville** [comment]
Hello,

Any update on this issue please @leo ?
We're currently evaluating Vercel, we would like to run serverless python functions, but some dependencies require python 3.7 or higher (such as this one: https://pypi.org/project/strawberry-graphql/)

**Comment by tedmiston** [comment]
Python 3.9 is out now as well if we could just skip to that.

**Comment by illvart** [comment]
I'm and maybe you guys really need Python 3.9+ 😭

**Comment by FalseDev** [comment]
Anything new (updates) on this?

**Comment by amr3k** [comment]
I'm using fastapi and couldn't get it running well because of 3.6
Would much love 3.8+ (at least) support.

**Comment by leach-mrt** [comment]
> I'm using fastapi and couldn't get it running well because of 3.6 Would much love 3.8+ (at least) support.

Me too. I really need Python3.9 support

**Comment by sisp** [comment]
Python 3.6 is reaching EOL in December this year. I think this issue should become a priority now.

**Comment by styfle** [comment]
You can try out Python 3.9 today by setting an environment variable `FORCE_RUNTIME_TAG=canary`.

If you're still using legacy [`builds`](https://vercel.com/docs/cli#project-configuration/builds), then you'll need to use `@vercel/python@canary`.

**Comment by styfle** [comment]
Python 3.9 is available to all deployments today 🎉 

https://vercel.com/changelog/python-3-9-is-now-available
