### ISSUE TITLE
Multi-Port Access

### ISSUE THREAD

**Issue by hhsnopek** [vercel/vercel#298]
I noticed in #149 that only a single port is accessible right now. As feature request I'd like to be able to expose multiple ports in my docker containers... This could be done by mapping the `EXPOSE` ports to the public facing ports

**Comment by leo** [comment]
If this problem still occurs, please move it over to [this repo](https://github.com/zeit/now-cloud). That's where we'll collect the bugs of the platform from now on (separate space, easier to work on)! 😊

**Comment by jamo** [comment]
Currently, our approach is that there is a single port for a single deployment, after all, if you need multiple ports, those maybe should be separate deployments.

**Comment by leo** [comment]
:+1:
