### ISSUE TITLE
now for github Is it possible to enable conditionally in monorepo

### ISSUE THREAD

**Issue by shKwonRiiid** [vercel/vercel#2983]
`now for github` executed every push or PR in monorepo.

I want to deploy specific directory.

Is it possible?

Could I know how to do this. If it can.

**Comment by styfle** [comment]
Yes, you can use `now.json` to configure the input.

Here's an example [now.json](
https://github.com/markedjs/marked/blob/bbc4576d3282be8d8e9762bb3308497b47fce7b5/now.json#L8).

Read more about [Advanced Builder Usage](https://zeit.co/docs/v2/advanced/builders#advanced-builders-usage).
