### ISSUE TITLE
Feature: Extend `now rm` to accept full URLs

### ISSUE THREAD

**Issue by oskarrough** [vercel/vercel#299]
Hi, since the full URL is copied to clipboard after deploying

`https://my-project-rvvatdsaa.now.sh/`

it would be handy if `now rm` accepted the full URL, with ending slash, and not just `my-project-rvvatdsaa.now.sh`.

**Comment by rauchg** [comment]
+1

**Comment by rauchg** [comment]
wait, I thought it did

**Comment by matheuss** [comment]
It works for me 🤔 
![screen shot 2017-02-10 at 4 03 16 pm](https://cloud.githubusercontent.com/assets/4721750/22839983/7ddc3372-efaa-11e6-9cf7-f431267d3a8a.png)

**Comment by oskarrough** [comment]
I believe it's the trailing slash. When removed it works, but the URL copied to clipboard does include it.

![screenshot from 2017-02-10 20-56-17](https://cloud.githubusercontent.com/assets/184567/22841879/86115f8a-efd3-11e6-8ac6-b64d5cb75628.png)
