### ISSUE TITLE
cachePath is now prepareCachePath 

### ISSUE THREAD

**Issue by danielroe** [vercel/vercel#2992]
Builders are now being called with `prepareCachePath` set to the cache directory, rather than `cachePath`.

This can cause caching to fail. See https://github.com/nuxt/now-builder/issues/111 for an example builder issue.

**Comment by styfle** [comment]
Hi @danielroe 

Thanks for reporting this issue!

The name will change back to `cachePath` tomorrow. And since it was already changed in the nuxt builder, we'll pass both `cachePath` and `prepareCachePath`.

**Comment by danielroe** [comment]
Thanks @styfle - good to know.

**Comment by TooTallNate** [comment]
Closing due to @styfle's comment.
