### ISSUE TITLE
Now's incorrect behavior on updating

### ISSUE THREAD

**Issue by sergeyfilimonov** [vercel/vercel#2996]
On every now command, in the console I see:

```
Run `yarn add now@latest` to install Now CLI 16.2.0...
Now CLI 16.1.2 dev (beta) — https://zeit.co/feedback/dev
```

After running `yarn add now@latest` the message won't disappear. Only `npm i -g now` helps.

**Comment by TooTallNate** [comment]
Thanks for the report @sergeyfilimonov. Can I ask which version of Now CLI you were previously using? There's a chance that this has already been fixed.

**Comment by sergeyfilimonov** [comment]
@TooTallNate I think it was 16.1.2

I have also created a [post](https://spectrum.chat/zeit/now/now-wont-update~658c8cc8-1f6b-44ff-8b65-5ac7530b002d) in Spectrum and got a reply:

> I had this problem as well. I think it's because ZEIT used to recommend a bash script to install Now, whereas now they recommend the yarn global add now@latest method. If you run which now in your Terminal (assuming UNIX system), it will tell you which Now executable is being used. If it's /usr/local/bin/now that's possibly the old copy.

So it seems that there are a few issues with installing Now. When running a `now` command you recommend installing Now CLI with `yarn add now@latest` but:
1. Here https://zeit.co/docs you recommend install it with `npm`. 
2. Why not `yarn global add now@latest`? `yarn add now@latest` adds Now as a dependency to a current project.

So it seems here https://zeit.co/docs that you should fix the recommended way from `npm i -g now` to `yarn global add now` if you recommend using `yarn` when updating. I just forgot how I installed Now for the first time — I thought it was yarn. 

By the way, `which now` displays `/usr/local/bin/now` with Now installed with `yarn`. I'm on a Mac if it's important.

**Comment by arnklint** [comment]
I ended up in a weird state, where the [desktop app](https://www.electronjs.org/apps/now) - installed via `brew` seemed to re-add the bin file whenever I removed it from `/usr/local/bin/now`, or some time after I'd use yarn or npm to install it. 

`which now` returned `/usr/local/bin/now` and it was not a symlink.

I uninstalled the desktop app and reran `yarn global add now` once again and now I get a (persistent) symlink towards node_modules.

**Comment by paulogdm** [comment]
@arnklint The Desktop App is deprecated. Please do not use it.

We are porting all functionalities to either the CLI or the UI itself.

We are closing this issue as it seems related to the environment rather than the CLI. If you still face this issue, please reach out to support@zeit.co
