### ISSUE TITLE
Add option to specify .env file in now.json

### ISSUE THREAD

**Issue by iaincollins** [vercel/vercel#300]
I use 'now -E' to deploy a .env file when deploying Next.js projects to now, which is a really great feature. Sometimes, I irritatingly forget to specify the '-E' flag when running 'now' and have to redeploy.

It would great if I could specify the option to also deploy a .env file in in now.json so I don't need to remember to specify '-E' each time - perhaps by file name, for those than might want to have different .env files for different environments.

Tagging in @timneutkens after discussing on Slack

**Comment by timneutkens** [comment]
@iaincollins see PR 👍
