### ISSUE TITLE
Gem install fails due to obsolete arguments

### ISSUE THREAD

**Issue by AnthonyMastrean** [vercel/vercel#3004]
I'm doing my 1st Zeit/now [deployment](https://zeit.co/anthonymastrean/mastreandev/c24jse26i) of a static Jekyll site and the first build following the repository init had an error.

```
$ yum install ruby23-devel.x86_64 && gem install bundler --no-ri --no-rdoc && bundle install
...

ERROR:  While executing gem ... (OptionParser::InvalidOption)
--
Sep 12 2019 10:28:14:686 | invalid option: --no-ri
Sep 12 2019 10:28:14:702 | error Command failed with exit code 1.
```

The correct argument is now `--no-doc`

> You can disable documentation generation using the `--no-doc` argument when installing gems.

https://guides.rubygems.org/rubygems-basics/#installing-gems

**Comment by styfle** [comment]
Hi Anthony,

The script you are looking for is likely in your `package.json` file.

We are going to simplify this step in the next release so that all you will need is `jekyll build`.

**Comment by AnthonyMastrean** [comment]
I created this repo from your Jekyll template (I just clicked on the website). And you're right, it's in the *package.json*!

> "install": "yum install ruby23-devel.x86_64 && gem install bundler --no-ri --no-rdoc && bundle install",

https://github.com/AnthonyMastrean/mastrean.dev/blob/master/package.json#L4

I guess my concern is that your repo/site template for Jekyll doesn't work out-of-the-box.

**Comment by styfle** [comment]
Thanks for confirming!

> I guess my concern is that your repo/site template for Jekyll doesn't work out-of-the-box.

Agreed, we will have a much better jekyll deployment experience in our next stable release (shipping very soon).

If you want to try it out now, you can install the canary channel CLI with `npm i -g now@canary` and use the package.json from the now-examples repo here: https://github.com/zeit/now-examples/blob/master/jekyll/package.json

**Comment by styfle** [comment]
This has been fixed, thanks!

https://zeit.co/new/jekyll
