### ISSUE TITLE
How get get real user IP address?

### ISSUE THREAD

**Issue by michael-land** [vercel/vercel#3012]
My real IP address is  73.136.1xx.xx, but I got 3.80.179.110 from the node request header. I use nextjs api routes and now v2.

Log from zeit
```
2019-09-13T05:54:04.266Z	eb8b0f71-dd4f-4bf8-ac2f-322b5fa46576	INFO	{ 
  'content-type': 'application/json',
  'x-real-ip': '3.80.179.110',
  'x-forwarded-port': '443',
  'connect-time': '1',
  'x-request-start': '1568354042852',
  'x-request-id': '40b598e0-cde3-4d52-8469-ead468e98d9a',
  'x-forwarded-for': '3.80.179.110',
  'x-now-trace': 'iad1',
  'x-now-id': 'hxprr-1568354043150-08138a9585f0',
  'x-zeit-co-forwarded-for': '
  'x-forwarded-proto': 'https',
  'content-length': '205',
  'accept-encoding': 'gzip',
  via: '1.1 vegur',
  'total-route-time': '0',
  connection: 'close' }
```

**Comment by styfle** [comment]
I verified that correct header is `x-forwarded-for` as documented. https://zeit.co/docs/v2/network/headers#x-forwarded-for 

When you visit the logs, a screenshot is taken of the deployment so this log you posted above is likely the request from our screenshot service, not the request that came from your browser. If you scroll up in the logs, you should see your IP in a previous request.

If not, you might be using a VPN or Proxy that is masking your IP.

**Comment by michael-land** [comment]
Thanks. I will try it.

**Comment by eric-burel** [comment]
Hello from the future. I've read the up to date doc: https://vercel.com/docs/concepts/edge-network/headers#x-forwarded-for
It says "If you are trying to use Vercel behind a proxy, we currently overwrite the 
[X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)
 header and do not forward external IPs. This restriction is in place to prevent IP spoofing."
 What does it imply? If I just host my website on Vercel, will I be able to get the real user IP?
 
 I am trying to build a rate limiter but Is suspect that relying on the IP is not the best approach.

**Comment by psud** [comment]
@styfle
yes, both the x-vercel-forwarded-for as well as the x-real-ip work when simply using the NextJS rewrites.

What doesn't work is when the page is being server-side-rendered as the API call then is triggered from a server (e.g. 3.82.112.93 in my case) and all correlation with the original IP is lost.

How can I get the original users IP address from the server-side-rendered page?

**Comment by gani-lw** [comment]
@psud Where you able to find anything on this?

We are also facing the same issue, we have a NodeJS + ExpressJS backend and for the server side, we are getting Vercel IP.

Rate Limiter is creating an issue in this.

**Comment by eric-burel** [comment]
@styfle small up, this is still quite unclear how you can access the client IP in Vercel reliably to setup a rate limiter. Upstash rate limiter demonstrates a few implementations using `request.ip` in Next.js but I can't find any doc telling if it's reliable or not
https://github.com/upstash/ratelimit-js/tree/main/examples/nextjs-middleware

This is documented more clearly in [Next.js documentation](https://github.com/vercel/next.js/pull/59719)
