### ISSUE TITLE
now alias ls $app_name doesn't work

### ISSUE THREAD

**Issue by matheuss** [vercel/vercel#3013]
If you run `now ls --help`, you can see that it says `now alias ls $app_name` would list aliases per app:
```
▲ (pear-vm) ~ {cdg1} now alias --help

  𝚫 now alias [options] <command>

  Commands:

    ls    [app]                  Show all aliases (or per app name)
[...]
```

I have an app called `gifs`, aliased to https://g.now.sh. When I run `now alias ls gifs`, I get the following:
```
▲ (pear-vm) ~ {sfo1} now alias ls gifs
> Error! Could not match path alias for: gifs
▲ (pear-vm) ~ {sfo1}
```

**Comment by andymckay** [comment]
I think that this functionality has been removed. It's no longer a documented option in the help: 

```
➜  status-via-edge git:(main) ✗ vc alias ls --help | grep ls
Vercel CLI 28.4.12
    ls                           Show all aliases
```

If this isn't the case, my apologies and we can re-open this issue. Thank you for the issue 🙇🏾
