### ISSUE TITLE
now.json `routes.status` not working as expected?

### ISSUE THREAD

**Issue by hormesiel** [vercel/vercel#3015]
I have this simple `now.json` file :

```ts
{
  "version": 2,
  "builds": [
    { "src": "foo.ts",
      "use": "@now/node" }
  ],
  "routes": [
    { "src": "/.*",
      "methods": ["OPTIONS"],
      "headers": {
        "Access-Control-Allow-Headers": "*",
        "Access-Control-Allow-Origin": "*"
      },
      "status": 200,
      "continue": false }
  ]
}
```

and `foo.ts` :

```ts
export default async function(req, res) {
  return res.send("You shouldn't see this when request's method is OPTIONS");
}
```

My problem is that when I send an `OPTIONS` request to `/foo.ts` the CORS headers are correctly set on the response but the route handler in `foo.ts` is called too, while I expect now to stop **before** and automatically return a `200`.

The idea behind this is to avoid having to manually answer `OPTIONS` requests with a `200` in every route my API exposes because that's very redundant, so I'd like Now to do it automatically.

**Comment by styfle** [comment]
Hi @flawyte 

I think the missing piece is that without a `dest`, the route is not overridden so the function is still invoked.

You could create an `options.ts` file that sets the status code and returns with an empty body. Then change now.json to include `"dest": "/options.ts"` for this route.

```json
{
  "version": 2,
  "builds": [
    { "src": "**/*.ts",
      "use": "@now/node" }
  ],
  "routes": [
    { "src": "/.*",
      "methods": ["OPTIONS"],
      "headers": {
        "Access-Control-Allow-Headers": "*",
        "Access-Control-Allow-Origin": "*"
      },
      "dest": "/options.ts" }
  ]
}
```

**Comment by styfle** [comment]
Alternatively, you could create an empty file called `options.txt` and then you wouldn't need another function.

```json
{
  "version": 2,
  "builds": [
    { "src": "**/*.ts", "use": "@now/node" },
    { "src": "options.txt", "use": "@now/static" }
  ],
  "routes": [
    { "src": "/.*",
      "methods": ["OPTIONS"],
      "headers": {
        "Access-Control-Allow-Headers": "*",
        "Access-Control-Allow-Origin": "*"
      },
      "dest": "/options.txt" }
  ]
}
```

**Comment by hormesiel** [comment]
Hi @styfle :)
Thanks for your answer.

Actually I ended up doing exactly what you describe in your first message :

```json
{
  "routes": [
    { "src": "/.*",
      "headers": {
        "Access-Control-Allow-Headers": "*",
        "Access-Control-Allow-Methods": "*",
        "Access-Control-Allow-Origin": "*"
      },
      "continue": true },
    { "src": "/.*",
      "methods": ["OPTIONS"],
      "dest": "/src/routes/cors-handler.ts" },

    "... my API endpoints"
  ]
}
```

The first route adds CORS headers to every request made to the API, and the second route simply responds to all `OPTIONS` requests :

```ts
// cors-handler.ts

export default async function(req, res) {
  // There's nothing to do here except to end the response since CORS headers
  // are automatically added for all routes using the `now.json` file.

  return res.status(204).send();
}
```

I just misunderstood the [`status` docs](https://zeit.co/docs/v2/advanced/routes/#status) when it says  Now will respond with this code when a matching path is requested. I thought it would also automatically end the response. Maybe this should be clarified, and `continue: false`'s behavior too.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.

**Comment by crock** [comment]
@flawyte Thank you so much, that solved my issue perfectly! The docs were very unclear about setting the cors headers in the `now.json`. I was doing `res.setHeader` in the actual function.
