### ISSUE TITLE
Unable to build vue-cli-3 application with puppeteer

### ISSUE THREAD

**Issue by johnleider** [vercel/vercel#3022]
I'm currently using v2 with a vue-cli-3 application with automatically works by just typing `now`. The problem arises when using a pre-render solution (I'm using https://github.com/chrisvfritz/prerender-spa-plugin), the build process never finishes.

![image](https://user-images.githubusercontent.com/9064066/64925495-e48d5c80-d7b6-11e9-9317-1df6a6d1bfd4.png)

Essentially I'd like to be able to build locally and upload my vue application to v2 which I can only do with v1 atm.

The problem with v1 is that it doesn't actually respect the project structure when serving pages for crawling bots, so it always returns the home page even though an actual file exists:

This is the config used for v1:

![image](https://user-images.githubusercontent.com/9064066/64925545-a6dd0380-d7b7-11e9-8457-bafe9baa0bc0.png)

This is the file that is used:
![image](https://user-images.githubusercontent.com/9064066/64925531-74330b00-d7b7-11e9-9a49-060cd28b70a1.png)

This is the file contents showing the title:
![image](https://user-images.githubusercontent.com/9064066/64925540-9593f700-d7b7-11e9-9c33-104339b2a91b.png)

This is what actually returns from the server for that page:
![image](https://user-images.githubusercontent.com/9064066/64925560-fc191500-d7b7-11e9-9a3e-affd7cf3ebb3.png)

Any solution for v1 or v2?

Here is an example deployment: https://store-beta-neauninowv.now.sh/

**Comment by styfle** [comment]
This has been fixed in #3911
