### ISSUE TITLE
error when adding new secret on now beta

### ISSUE THREAD

**Issue by bukinoshita** [vercel/vercel#3032]
By running on **now@16.1.4-canary.7**:

```
$ now secret add my-secret my-value
```

It throws an error `> Error! Invalid JSON` (it works on other versions tho)

**Comment by leo** [comment]
Thanks for reporting. We'll take a look!

**Comment by styfle** [comment]
This was fixed in PR #3030 and released as `now@16.1.4-canary.8`.

Running `now i -g now@canary` will install the fix, thanks!
