### ISSUE TITLE
Read files in the `static` folder

### ISSUE THREAD

**Issue by lcswillems** [vercel/vercel#3033]
Hi,

I would like to read a file in the `static` folder using `fs.readFileSync`. It works locally using `process.cwd()` but it doesn't work on Zeit server when I do `now`.

Lucas Willems

**Comment by styfle** [comment]
Hi @lcswillems 

Try using `__dirname`. Something like the following should work:

```js
const fs = require('fs');
const path = require('path');
const file = fs.readFileSync(path.join(__dirname, 'static', 'file.txt'), 'utf8');
```

**Comment by styfle** [comment]
That being said, if these are static assets such as html or css that you want to serve publicly, you can instead rename `static` to `public` because anything from the `public` directory is published a static files.

See for example https://github.com/zeit/og-image/blob/master/public/style.css

**Comment by lcswillems** [comment]
Thank you for the answer!
