### ISSUE TITLE
 Error: No output directory named "public" found.

### ISSUE THREAD

**Issue by Polyhistor** [vercel/vercel#3044]
I'm trying to deploy a monorepo to Now and I constantly get the error "No output directory named "public" found.", I've read the mentioned FAQ, tried "--output-dir public", edited "now.json", but nothing seems to work!

Here is my build script in package.json:

"build": "npm run bootstrap && npm install && cd packages/wildkiwi && gatsby build --output-dir public"

What am I missing?

**Comment by styfle** [comment]
Hi @Polyhistor 

It looks like you are using `cd` to change directory which means that gatsby is going to create a public sub-directory. You could try moving the output up to the root like this:

```
"build": "npm run bootstrap && cd packages/wildkiwi && gatsby build && mv public ../../"
```

I also removed `npm install` since that will run before your build step so no need to do it twice.

**Comment by Polyhistor** [comment]
Well, the problem solved. The build still fails due to network errors on fetching posts from Wordpress, but I've had a few succesful builds. 

Thanks mate.
