### ISSUE TITLE
A random build was incorrectly promoted to production

### ISSUE THREAD

**Issue by foundryspatial-duncan** [vercel/vercel#3049]
I was experimenting with putting non-string values for `env` vars in now.json; I made a variable called `VUE_APP_FOO` under the `build` env vars, and tried to give it an array value like:
```
"VUE_APP_FOO": ["foobar", 123]
```
When trying to deploy with the `now` command, it predictably failed with this error:

> Error! The property `build.env['VUE_APP_FOO']` in now.json can only be of type `String`.

I changed the value to a number instead of an array, and it failed again with the same error. After those two experiments, I made the value a string (actually, it was the array again, but JSON-encoded) and ran `now` one more time. This time, I unexpectedly got this warning:

> WARN! This is the first deployment in the [my project name] project. It will be promoted to production.

Sure enough, it became the new production build on the domain after it finished building. It definitely wasn't the first build for the project, and I didn't change the name or anything, only that environment var. Was it because the previous two builds failed? Or was it totally random?

**Comment by leo** [comment]
Thanks for reporting!

If your previous two deployments failed with a similar error, that means no deployment or build was ever created. They are only created once you get past a "verification" phase where we – for example – verify your environment variables.

Since your deployments didn't pass that test, no build or deployment was ever created. In turn, your deployment was the first deployment in the project.

Am I correct that all your previous deployments failed in that project?

**Comment by foundryspatial-duncan** [comment]
Oops, to be clear, we've had **dozens** of successful builds in this project, although it's been a week or so since we've explicitly done a build with `--production`. That's why this one successful build being promoted to production without the flag was a surprise.

**Comment by leo** [comment]
@foundryspatial-duncan I see! Did you only see the warning or was the deployment actually promoted to production (with production domains assigned to it)?

**Comment by foundryspatial-duncan** [comment]
It was indeed, I checked the dashboard and it shows the production domains on that one build from an hour or so ago, while our last actual production build was on the 12th.

**Comment by leo** [comment]
Gotcha. Thanks for the details! We'll take a look why this is happening.

It should not be.

**Comment by AndyBitz** [comment]
Hi @foundryspatial-duncan thanks for reporting.

Could you provide us a deployment URL to investigate this further? You can email it to andy@zeit.co if you don't want to post it here.

**Comment by foundryspatial-duncan** [comment]
Sure thing. Sent!
