### ISSUE TITLE
Django login is broken only with `now dev`

### ISSUE THREAD

**Issue by mo3rfan** [vercel/vercel#3051]
Django admin login does not work when `now dev` is used, but the same code works if it is run normally. 

Here are the steps to reproduce inside a container:

1. Pull the latest now-test image and open up a bash terminal on the container
```bash
$ docker run -p 3000:3000 -it 3rfan/now-test:latest bash
```
2. Install the dependencies.
```bash
$ pip3 install -r requirements.txt
```
3. Run Django migrate and create superuser using the default sqlite DB:
```bash
$ python3 manage.py migrate && python3 manage.py createsuperuser
```
4. Run `now dev` and log in at `http://localhost:3000/admin` using credentials created from step 3. The page refreshes back to the login page after entering username/password.
---
However, login works if Django app is run via Gunicorn instead. (but not `now dev`)
```bash
$ pip3 install gunicorn && gunicorn now.wsgi -b 0.0.0.0:3000
```

**Comment by styfle** [comment]
Thanks for the repo steps!

It looks like the root cause is that the `@now/python` builder is only using the first header value for a given key. Since this response assigns two `Set-Cookie` values, only the first (csrftoken) is assigned and the second (sessionid) cookie is ignored.

**Comment by styfle** [comment]
This has been fixed in the latest canary.

I confirmed your projects works with the following script:

```sh
docker run -p 3000:3000 -it 3rfan/now-test:latest bash
pip3 install -r requirements.txt
python3 manage.py migrate && python3 manage.py createsuperuser
npm i -g now@canary
sed -i 's/@now\/python/@now\/python@canary/g' now.json
now dev
# visit http://localhost:3000/admin and login
```
