### ISSUE TITLE
DNS A record not working as expected

### ISSUE THREAD

**Issue by lukehedger** [vercel/vercel#3052]
Hoping someone can help me out! Have tried ZEIT's Twitter support but they were not able to help 😞 

I have a domain registered with Now - `tread.fyi`. There is a static website hosted at the root of this domain https://tread.fyi/. And I have a Node.js server running in a DigitalOcean droplet.

I want to route requests for https://realtime.tread.fyi/ to the DO droplet. I have added an A record to Now's DNS records, which can be [verified here](https://www.whatsmydns.net/#A/realtime.tread.fyi). But pinging the URL shows the requests are routed to `alias.now.co` instead of the droplet's IP address.

```
→ ping https://realtime.tread.fyi
PING alias.zeit.co (3.9.28.56): 56 data bytes
Request timeout for icmp_seq 0
```

I'm guessing that the default CNAME/ALIAS records on Now's DNS are intercepting the requests to my subdomain. Here are the DNS records:
```
         ALIAS http://alias.zeit.co.
*        CNAME http://alias.zeit.co.
realtime A     157.245.38.176
```

How can I solve this so that the subdomain correctly points to the droplet's IP?

**Comment by zdunecki** [comment]
Hey @lukehedger, 

Do you have any updates? I'm facing the same problem. I would like to point my blog on DO droplet from zeit.

EDIT:
Did you try `now dns <domain> <sub_domain> A <droplet_ip_adress>`?

**Comment by jgillich** [comment]
I had the same issue because I did this: `now dns add foo.com sub.foo.com A 1.2.3.4` 

It works if I do: `now dns add foo.com sub A 1.2.3.4` 

(Don't include the main domain in the subdomain or you will end up with `sub.foo.com.foo.com`)

**Comment by RodolfoSilva** [comment]
Check the documentation, https://zeit.co/blog/now-dns#examples

**Comment by mcsdevv** [comment]
Closing this as both @jgillich and @RodolfoSilva have pointed out the correct answer and resources to answer this.

**Comment by connorhvnsen** [comment]
I'm attempting to point a subdomain to the IP of a droplet on Digital Ocean but even after successfully adding the A record I get the following error when pinging: **Ping request could not find ghost.hvnsen.com. Please check the name and try again.** A record can be verified [here](https://www.whatsmydns.net/#A/ghost.hvnsen.com)

**Comment by cauldyclark15** [comment]
this issue still persists https://github.com/vercel/vercel/issues/3118

**Comment by vicmars5** [comment]
Have same Issues here
