### ISSUE TITLE
Subdomain routing to a /docs catalog

### ISSUE THREAD

**Issue by Cholewka** [vercel/vercel#3054]
Hi! I want to my own subdomain (https://docs.silvestris.org) connected to Zeit redirect to https://silvestris.org/docs catalog. Can I?

**Comment by styfle** [comment]
Hi @Cholewka 

You can achieve this be creating two deployments:

1. silvestris.org
2. docs.silvestris.org

I'll assume you have already created number 1 so here's how you can setup number 2 with a `now.json` file:

```json
{
  "version": 2,
  "alias": ["docs.silvestris.org"],
  "routes": [
    {
      "src": "/(.*)",
      "status": 301,
      "headers": { "Location": "https://silvestris.org/docs/$1" }
    }
  ]
}
```

This is similar to the [redirect from www](https://zeit.co/guides/redirect-from-www) guide.

**Comment by Cholewka** [comment]
Alright, thank you!
