### ISSUE TITLE
Overriding a secret, or --force option to remove

### ISSUE THREAD

**Issue by verekia** [vercel/vercel#3056]
Hi,

I am setting a secret in a deployment script, because it has a dynamic value that I cannot hard-code in `now.json`.

In `now` version `16.2.0`, it doesn't seem possible to override an existing secret (it stops with an error). My workaround is to remove the secret before recreating it, but there is still a prompt of confirmation about the removal that makes it impossible to run that script without manual input.

This problem would be solved by either of these 2 options:
- Adding a `-f` or `--force` flag (or something else) to `now secrets rm`
- Adding a `-f` or `--force` flag (or something else) to `now secrets add`, which would override any existing secret

**Comment by styfle** [comment]
Hi @verekia 

There is a `-y` option that can be used for any y/n questions.

For example:

```
now secrets add hello world
now secrets rm hello -y
```

**Comment by verekia** [comment]
I... don't think so?

<img width="377" alt="Screenshot 2019-09-23 22 01 19" src="https://user-images.githubusercontent.com/522007/65427653-bd392e00-de4d-11e9-97b9-87f703382fe8.png">

If there is, it is not documented in the `--help` manual of `16.2.0`.

**Comment by styfle** [comment]
It looks like this is only working on the canary channel and hasn't made its way to the stable channel.

Try updating with `npm i -g now@canary`, thanks!

**Comment by styfle** [comment]
The fix shipped to the stable channel and I confirmed it is working properly, thanks!

```
npm i -g now@latest
```

**Comment by verekia** [comment]
Thank you for the update! 👍
