### ISSUE TITLE
Deploy & aliasing with Now 1.0

### ISSUE THREAD

**Issue by cristoforo** [vercel/vercel#3061]
I'm with Now 1.0, what's the supposed workflow to deploy & alias with a single command?

In other words, how can I automate the deploy and aliasing like I used to do with `now && now alias` without the need to manually copy and paste the deployment URL?

(btw, a simple warning on the command line about the `--prod` flag not supported in v1 would be very welcomed... I spent 2h trying that out before realizing it was simply not supported in v1 :) )

**Comment by cristoforo** [comment]
With now cli v16.2.0, the command `now alias` is not working anymore without the deployment url.
What I get is: `> Error! The provided argument "undefined" is not a valid deployment`

**Comment by tedmiston** [comment]
I believe the `alias` command is now deprecated from the CLI (https://zeit.co/docs).

You can make a second config file - `now-foo.json` which has your alternate alias in it, say `foo.example.com` vs `www.example.com` in your regular prod `now.json` file.

Then run this to deploy the version aliased to `foo.example.com`:

```
now --prod --local-config=now-foo.json
```

And run this to deploy the version aliased to `www.example.com`:

```
now --prod
```

I agree this workflow has becoming confusing.  My sites go through more than 2 stages via CI/CD pipelines, so the simple "stage" and "prod" setup doesn't work for me.  With alias, I could do this much more easily.  The attempt to simplify the CLI has made a non-default setup a bit more awkward to achieve.

It would be nice if the docs at https://zeit.co/docs/v2/custom-domains/#deploying-with-your-domain could be updated to reflect this as the process I described doesn't seem to be documented today.

Note that if you are using the brand new 16.3.0 release there is a bug breaking the `--local-config` feature (see #3099).  It is still working normally in 16.2.0 for me.

**Comment by abathellier** [comment]
"alias" and  "dotenv" props from now.json don't work anymore with now v1. Impossible to push a new version of my app... My staging env is broken too. Now v1 no longer seems to be maintained at all... @cristoforo have you found a workaround ?

**Comment by mcsdevv** [comment]
Hello @cristoforo, @durdenx, are you still experiencing this issue with the latest Now CLI release?

**Comment by paulogdm** [comment]
Hello everyone,

Since we are deprecating Now 1.0, we recommend that you either upgrade to Now 2.0 or to a platform that supports serverful/containers.

If you have any questions, please reach out to support@zeit.co
