### ISSUE TITLE
now-cli: releases without assets

### ISSUE THREAD

**Issue by StefMa** [vercel/vercel#3074]
On my CI I downloaded the now-alpine from the github release package in version 15.4.0.
I've done this with 
```
wget -q https://github.com/zeit/now-cli/releases/download/15.4.0/now-alpine.gz
```

Today I wanted to update it to the latest version and found out that since 15.8.7 (explcuded) no pre compiled now assets are attached to the releases anymore.

Is this an issue or expected?
From where can I get the alpine now cli now?

**Comment by StefMa** [comment]
I just found this: https://github.com/zeit/latest-now-cli

Thanks and have a nice day 😂

**Comment by StefMa** [comment]
Reopened. Because the repo I mentioned does not work... :/

**Comment by styfle** [comment]
Hi @StefMa 

We no longer ship Now CLI as a binary.

Instead, it requires node.js and npm to be installed first and then you can run `npm i -g now`.

https://zeit.co/download

**Comment by StefMa** [comment]
But then my builds on the CI aren't exactly the same because it may happen
that you publish a new version which is incomatiple with my code...

Or can I specify the version to download with npm?

**Comment by leo** [comment]
@StefMa You can, indeed!

Like this: `npm install -g now@<version>`

**Comment by StefMa** [comment]
Ah okay. Thank you 👍
Will close it because it's answered.
