### ISSUE TITLE
RFC: Restructure config file usage

### ISSUE THREAD

**Issue by mike-engel** [vercel/vercel#308]
It seems like there are several issues that some parts of the configuration from `now.json` or `package.json` are being ignored or overridden. I'd like to propose a change (before I do the work and have it rejected) to restructure the `deploy` command.

#### Changes
- allow `package.json` and `now.json` to configure all options and arguments (for `now deploy`) available through the CLI
- load data from `process.argv`, `package.json`, and `now.json` as soon as possible
- store the options as an immutable object that simply gets passed down into functions. The metadata never gets read after the first read
- having both `package.json` and `now.json` configured still throws
- options passed in through the CLI have precedence over `package.json` and `now.json`
  - e.g. `Object.assign({}, fileOptions, cliOptions)`
- `static` would be available as a top-level type, as opposed to only supporting `npm` and `docker`

If you think this would be a good idea, I'll take a stab at throwing a PR together

**Comment by mike-engel** [comment]
Seeing as how the docs have improved over time, the first change here isn't as necessary, and would probably lead to confusion if it needed to support all cli arguments.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
