### ISSUE TITLE
Build freezes with a message "done" 

### ISSUE THREAD

**Issue by Polyhistor** [vercel/vercel#3084]
Our build has been happening for the last 40 minutes and still going! it seems like the system has frozen and stuck on a certain phase.... 

All we see at the end of the log is a message "done"!, checkout the screenshot;

```
[now] a file for "workbox-v3.6.3/workbox-routing.prod.js.br" is already uploaded. not uploading
--
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-routing.prod.js.map" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-strategies.dev.js" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-strategies.dev.js.br" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-strategies.dev.js.map" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-strategies.prod.js" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-strategies.prod.js.br" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-strategies.prod.js.map" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-streams.dev.js" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-streams.dev.js.br" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-streams.dev.js.map" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-streams.prod.js" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-streams.prod.js.br" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-streams.prod.js.map" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-sw.js" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-sw.js.br" is already uploaded. not uploading
11:00:26 AM | [now] a file for "workbox-v3.6.3/workbox-sw.js.map" is already uploaded. not uploading
11:01:03 AM | done
```

**Comment by styfle** [comment]
Hi @Polyhistor 

Is this still an issue?

If so, can you provide the deployment URL that is hanging?

Feel free to contact support@zeit.co if you prefer to discuss privately.

**Comment by Polyhistor** [comment]
Well, the fact of the matter was that if you try to fetch lots of media and posts from a remote Wordpress server ( we are using wpengine ) your build most likely fails ( 8 out of 10 )....... 

Sometimes the server request fails to fetch the data, some other times the terminal freezes in source and transform.... 

You can reproduce this by setting a gatsby website, and make it source from our website -> https://www.wildkiwi.com/. We are using the official gatsby-source-wordpress plugin. (Make sure your concurrent requests are not anything more than 4)

Currently, we've deactivated our Wordpress blog....

**Comment by styfle** [comment]
I tried cloning the [using-wordpress](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-wordpress) example and changing [gatsby-config.js#L19](https://github.com/gatsbyjs/gatsby/blob/c78338912f93495734d60a2b355c592291e7e60b/examples/using-wordpress/gatsby-config.js#L19) to use baseUrl `www.wildkiwi.com` like you said.

But I see an error after a few minutes:

```
AAG
--
05:01:22 PM | success Processing types - 0.217 s
05:01:22 PM | ⠹ building schema
05:01:22 PM | ⠙ Processing types
05:01:22 PM | AAG⠹ building schema
05:01:22 PM | AG
05:01:22 PM | success building schema - 0.629 s
05:01:22 PM | ⠹ building schema
05:01:22 PM | AG
05:01:22 PM | AG⠋ createPages
05:01:22 PM | AG
05:01:22 PM | ERROR #85901  GRAPHQL
05:01:22 PM | There was an error in your GraphQL query:
05:01:22 PM | Cannot query field "allWordpressPost" on type "Query". Did you mean "allWordpressPage", "allWordpressTag", "allWordpressWpUsers", "allWordpressWpTypes", or "wordpressPage"?
05:01:22 PM | File: gatsby-node.js:17:24
05:01:22 PM | ⠋ createPages
05:01:22 PM | error Command failed with exit code 1.
```

**Comment by Polyhistor** [comment]
that means you could not fetch Wordpress posts from our WPengine as stated above.... so your query can't read null or undefined.... 

Sometimes the servers fail to communicate... if you're running on zeit, there is more likely that this fails,,, 

This is however true only between zeit and wpengine servers...

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.
