### ISSUE TITLE
Next.js public files are a 404 with now dev

### ISSUE THREAD

**Issue by lfades** [vercel/vercel#3085]
When using the `public` folder `now dev` is not able to return the files inside of it using the router

**Comment by TooTallNate** [comment]
Isn't the directory supposed to be called `static`?

**Comment by lfades** [comment]
@TooTallNate The `public` directory also handles static files, but it goes from the root (e.g `/favicon.ico` can be in `public/favicon.ico`). The `static` directory will be deprecated in favor of `public`.

**Comment by TooTallNate** [comment]
So in that case this is a `@now/next` builder issue, it likely isn't including the dev `routes` for the new `public` dir.

**Comment by yahmad** [comment]
Any way to currently get this working locally, whilst the bug is being resolved?

**Comment by lfades** [comment]
@yahmad I think it's working right now, I'll check again and update the issue 🕵

**Comment by lfades** [comment]
After a test, I can confirm this is no longer an issue 😌
