### ISSUE TITLE
Make double slash redirection optional

### ISSUE THREAD

**Issue by plibither8** [vercel/vercel#3086]
Hi! One of my APIs that I would like to host on Now requires support for double slashes in the URL. Currently, Now forces redirection which is not ideal for me (https://github.com/zeit/now/pull/2645). I propose that route changes like these be optional (enabled by default but can be disabled) and not done so implicitly. Thanks :)

**Comment by plibither8** [comment]
Hi! Any updates on this?

**Comment by TooTallNate** [comment]
Hi there @plibither8. At this time, there is no configuration option for the double slash redirection, however we are tracking this feature request internally. We will update here if/when there is any movement on that front.

**Comment by plibither8** [comment]
Thanks for the quick response! Will be waiting :)

**Comment by pke** [comment]
Any particular reason why it was decided to this in the first place? @TooTallNate

**Comment by pke** [comment]
So it seems I can only find the code that does the rewrite in the dev server https://github.com/zeit/now/blob/67a80d6b830b3c3a80a389902c9a8308c7c20708/packages/now-cli/src/util/dev/server.ts#L1143

I guess the code for the now hosted solutions is not in a public repo?

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by pke** [comment]
> Hi there @plibither8. At this time, there is no configuration option for the double slash redirection, however we are tracking this feature request internally. We will update here if/when there is any movement on that front.

So its already tracked internally or do we need to contact support@zeit.co? 

I still consider that behaviour of URLs a bug (at least its totally unexpected), so its something that warrants an issue here, that you can act upon.

Why do you have "feature request" labels here, when issues are not for feature requests?

**Comment by pke** [comment]
Until this is fixed this is a workaround:

In your `index.js` handler:

```js
req.url = req.url.substr(1).replace(/(\/https?:\/{1})([\w+])/i, "$1/$2")
```

In your `now.json`:

```json
"rewrites": [
  { "source": "/(.*)", "destination": "api/index.js" }
]
```

**Comment by blokhin** [comment]
Dear @leo @TooTallNate, indeed, a corresponding option would be still very much appreciated (see also [#1114](https://github.com/zeit/docs/issues/1114)).

**Comment by xieyuheng** [comment]
Please consider add this feature for routes like this: https://github.com/vercel/vercel/issues/3429

**Comment by xieyuheng** [comment]
A poll about adding this feature: https://github.com/vercel/vercel/discussions/9522
