### ISSUE TITLE
[now dev] fails with @now/python on Debian/Ubuntu

### ISSUE THREAD

**Issue by numrut** [vercel/vercel#3089]
Ubuntu, since Xenial, contains the patched version of `pip` with `--user` and `--ignore-installed` flag active by default. In combination with the `--prefix` option, from the `@now/python` runtime, this always raises an error `distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base`.

This can be solved by running `now dev` as a superuser or using the non-system version of `pip`.

For solving this in the runtime either `--system` or `--no-user` (depends on `pip` version) option must be provided. However, `export PIP_USER=0 PIP_IGNORE_INSTALLED=0` seems more applicable.

There are also similar issues: #3023 and #2853

**Comment by styfle** [comment]
Hi @numrut 

We shipped the change to the stable channel today.

Can you try `npm i -g now@latest` to see if this fixes the issue for you? Thanks!

**Comment by numrut** [comment]
Are you sure? There are no changes in the `now-python` package in the last few days.

Howbeit, i've tried and nothing changed, the error remained.

**Comment by styfle** [comment]
The command that is currently executed is the following:

```
pip3 install --disable-pip-version-check --target . --upgrade -r requirements.txt
```

https://github.com/zeit/now/blob/32aa94bf3d186bbe88546643b5bb5688b97f8d0e/packages/now-python/src/index.ts#L25

I believe this was changed recently by @nathancahill to avoid the user flag although the [`PYTHONPATH`](https://github.com/zeit/now/blob/32aa94bf3d186bbe88546643b5bb5688b97f8d0e/packages/now-python/src/index.ts#L136) is assigned.

The linked issue claims that upgrading pip works without changing flags https://github.com/zeit/now/issues/3023#issuecomment-531642383

Did you try `pip3 install --upgrade pip`?

**Comment by styfle** [comment]
Upon further investigation, it might be this `setup.cfg` causing an issue:

https://github.com/zeit/now/blob/32aa94bf3d186bbe88546643b5bb5688b97f8d0e/packages/now-python/src/index.ts#L99

**Comment by numrut** [comment]
It forcibly sets the `--user` parameter under the hood. https://github.com/pypa/pip/issues/4222#issuecomment-417646535

```
default_user = True
if running_under_virtualenv():
    default_user = False
if os.geteuid() == 0:
    default_user = False
```
The python runtime runs system-wide instance of `pip`, thus it doesn't detect virtualenv. So `default_user` is always `True` unless command has been run with superuser privileges.

> The linked issue claims that upgrading pip works without changing flags #3023 (comment)

It's not the upgrading fixed that issue. The trick is in using non-system `pip` which is version `19.2` or so and doesn't contain that patch. Version of system packaged `pip` is much lower - `9.0.1` (https://packages.ubuntu.com/bionic/python3-pip).

**Comment by numrut** [comment]
FYI, the properly set `PIP_USER` [environment variable](https://pip.pypa.io/en/stable/user_guide/#environment-variables) solves this.

**Comment by thasophearak** [comment]
@numrut If I'm understand this correctly, this problem is platform specific (Debian/Ubuntu) with  `pip` that contain this patch https://github.com/pypa/pip/issues/4222#issuecomment-417646535

Do you think it's alright to set `PIP_USER` in [build environment](https://zeit.co/docs/v2/environment-variables-and-secrets/#accessing-environment-variables)?

**Comment by numrut** [comment]
@sophearak yes, you're right, this is related only to Debian and its derivatives (unless those provide some custom builds of `pip`). Though, accordingly to distrowatch.org, 7 of 10 most popular Linux distros are deb-based so this issue is pretty important.

Setting the variable in a build environment somewhat complicates the overall development process because requires additional steps from the user. It seems to me this this contradicts the ideа of the zero configuration nature, doesn't it?

**Comment by styfle** [comment]
I was unable to reproduce this bug with ubuntu xenial.

Here's what I tried:

```Dockerfile
FROM ubuntu:xenial
RUN apt-get update && \
  apt-get install python3 python3-pip && \
  pip3 --version &&
  echo 'Flask==1.0.3' > requirements.txt && \
  pip3 install --disable-pip-version-check --target . --upgrade -r requirements.txt
```

 The pip version was 8.1.1

**Comment by numrut** [comment]
Please try this:
```dockerfile
FROM ubuntu:latest

RUN apt-get update && apt-get install -y python3-pip

RUN useradd -m user && \
  su - user -c "pip3 install --disable-pip-version-check --target . --upgrade Flask"
```
