### ISSUE TITLE
Latest `now@16.3.0` broke `--local-config`

### ISSUE THREAD

**Issue by davidroman0O** [vercel/vercel#3099]
Hi!

Maybe someone already posted this but the last version of `now` broke deployments.

It searching for a `build` in `package.json` but I think it's confusing the `package.json` from the workspace and doesn't think about the `package.json` for the actual builder.

```
> Error! Your `package.json` file is missing a `build` property inside the `script` property.
More details: https://zeit.co/docs/v2/advanced/platform/frequently-asked-questions#missing-build-script
error Command failed with exit code 1.
```

I use a `json` file for `now --local-config` who specify the correct package. I didn't made a deployment since last week. And yes, there is a `build` into the `package.json` of the package. 

Everything were working perfectly fine during the last few months (even my last deployment last week), since this morning it's impossible with the latest version of `now`.

I just updated this morning and now it's impossible to deploy. Even simple simples boilerplates from github. :/ 

Hope you'll fix it soon!

Thx a lot for everything 😄 

EDIT:
Right now, I've downgrade to the 16.2.0 version to be able to deploy
I've tested the 16.3.0 and there definitely an issue there :) 
Good luck to the team to fix it!

**Comment by tedmiston** [comment]
I have experienced that `--local-config` (pointing to a non-default config file) is definitely broken in 16.3.0 across all deploys where I use now as well.

It appears to be ignoring the custom config file and deploying with the default one... aka pushing my non-prod builds straight to prod ☠️.

Pinning to 16.2.0 for now also worked as a stopgap for me.

**Comment by styfle** [comment]
Thank you for the bug report!

We released a fix for `--local-config` on the canary channel.

Can you try running `npm i -g now@canary` to confirm this version works for you? Thanks!

**Comment by davidroman0O** [comment]
Hi!

I have few tickets to do BUT I'll test it today as soon as possible! 😄

**Comment by Vadorequest** [comment]
Was a fix released in a non-canary branch?
