### ISSUE TITLE
Expired SSL certificate

### ISSUE THREAD

**Issue by jimpick** [vercel/vercel#31]
The following site has an expired SSL certificate:

https://now-test.v6z.me/

I think I may have provisioned it a few months ago when zeit.world was announced.

**Comment by OlliV** [comment]
We don't run certificate auto-renew for inactive aliases, maybe that domain wasn't linked to an alias?

**Comment by jimpick** [comment]
I think the domain must have been inactive, but then I used it again, and
it used the expired certificate.

Cheers,
- Jim

**Comment by OlliV** [comment]
I removed the old cert.
