### ISSUE TITLE
svelte/sapper js support for serverless page splitting

### ISSUE THREAD

**Issue by skdigital** [vercel/vercel#3102]
Please help provide native support for serverless per page splitting functionality for Sapper/svelte. Quite a popular feature request within the Sapper/svelte community??

Here is fix template from the Sapper/svelte community:

https://github.com/beyonk-adventures/now-sapper-demo

Caveats for the current template

Though serverless, your Sapper application will still run all routes from a single endpoint /*. It does not (yet) support route splitting/differential bundling. I have tried this with a hefty Sapper application, and have not found this to be an issue, though it would be optimal to add this feature

It would be great to get first-class support for Sapper (which is heavily influenced by Nextjs but runs on Svelte instead of React).

**Comment by styfle** [comment]
The ZEIT Now platform supports zero config front-end deployments.

If you need more advanced features such as code splitting serverless functions, you'll need to [develop a custom builder](https://github.com/zeit/now/blob/canary/DEVELOPING_A_BUILDER.md).

It looks like a Community Builder already exists called [`now-sapper`](https://github.com/thgh/now-sapper).

I would suggest creating an issue in that repository so the author can implement your feature request.

**Comment by skdigital** [comment]
It would be much nicer if Zeit Now created the custom builder necessary to use their product to the maximum potential rather than rely on community builds. The more advanced features are what I like using Zeit for (Nextjs). But like many developers, we are moving away from React for simpler (more advanced, lighter) frameworks.

**Comment by rauchg** [comment]
@skdigital We plan to do this very soon, after we share some improvements we are working on for Next.js that should act as the base for other frameworks like Sapper and Nuxt :)

**Comment by skdigital** [comment]
@rauchg That's exciting and good news. I really want to stay on one platform with SSR frameworks and use the latest and greatest features already delivered to Nextjs. It would be great to have that quality no config serverless setup available on more frameworks. It would mean not having to switch to another host or to export to static for example. Do you have a timeline in mind as to when we can see solid support for Sapper?

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.
