### ISSUE TITLE
[now dev] not rendering custom error page

### ISSUE THREAD

**Issue by bitjson** [vercel/vercel#3103]
Error handling using `now dev` doesn't seem to be consistent with production. 

Repo to reproduce: https://github.com/bitjson/now-dev-custom-errors-bug

When running `next` or in production (`now`): the expected error page is rendered.
When testing with `now dev`, a **different** error page is rendered.

**Comment by styfle** [comment]
Thanks for the bug report!

This must have regressed recently when the now dev error page was updated to look like production. cc @TooTallNate 

I confirmed this bug only affects `now dev`.
Cloud deployments are working properly with custom error pages.

**Comment by TooTallNate** [comment]
@bitjson Thanks for including the excellent repro instructions and repository. We are taking a look.

**Comment by styfle** [comment]
I tested with Now CLI 17.0.4 and it works the same in `now dev` and a production deployment of `now`.

They both show the same 404 page and they both log `Error rendered: 404; Url: /asdf;`.

Closing as fixed.
