### ISSUE TITLE
[now-cli] Error after upgrading to 16.3.0

### ISSUE THREAD

**Issue by Avevrr** [vercel/vercel#3104]
Receive an error message/unable to deploy after upgrading now-cli to version 16.3.0.

Works okay when reverting back to 16.2.0

Details:
1. Upgrade to 16.3.0 with
`npm i -g now@latest`

2. In console, run "now" command
`now`

3. Get this error:
> Error! ENOENT: no such file or directory, stat 'LOCAL_PATH/mobile/node_modules/.bin/detect-libc'

The 'LOCAL_PATH/mobile' is the directory for a react-native version in the same repo.

4. Revert back to 16.2.0
`npm i -g now@16.2.0`

5. In console, run "now" command
`now`

6. Runs and deploys correctly without errors

I was able to recreate these steps several times.

**Comment by kaYcee** [comment]
got the same error with the `docz` package:

```
Error! ENOENT: no such file or directory, stat '<LOCAL_PATH>/reusecore/node_modules/.bin/docz'
```

No issue though with `now@16.2.0`.

**Comment by styfle** [comment]
Thanks for reporting this bug!

We released [16.3.1](https://github.com/zeit/now/releases/tag/now%4016.3.1) with several bug fixes.

Can you see if that fixes the issue for you?

If not, could you provide more details or a failing deployment URL? Thanks!

**Comment by Avevrr** [comment]
Thanks so much for all you do and the prompt response.

I am getting the same error with 16.3.1.

If I revert back to 16.2.0, it deploys without error (I do notice some red warning messages in the web dashboard build console output). I am PMing you a deployment URL.

Let me know if you need anything else.

**Comment by styfle** [comment]
Thanks for the update! It seems this is only affecting some machines because I was unable to reproduce but @sophearak was able to reproduce.

We released a fix to the canary channel that should resolve this problem.

Can you try `npm i -g now@canary` to confirm this this solves your issue? Thanks!

**Comment by Avevrr** [comment]
Hi, it worked! Was able to do one deployment with the canary version.

I should have mentioned that my client environment is Ubuntu 16.04 LTS, so probably not the norm. Thanks!!!
