### ISSUE TITLE
[now-cli] Upgrading to 16.3.0 breaks custom builders

### ISSUE THREAD

**Issue by danielroe** [vercel/vercel#3114]
Custom builders fail silently after upgrading to 16.3.0, if `--local-config` is specified.

**Comment by leo** [comment]
Thanks your report! We've issued a fix and it will be released today.

**Comment by danielroe** [comment]
> Thanks your report! We've issued a fix and it will be released today.

Great! And my apologies for the too-brief issue. I was in the middle of editing it and creating a repro, which I take it is now not needed. :smile:
