### ISSUE TITLE
Browser reload causes a 404 error (Using dynamic routes with next-routes)

### ISSUE THREAD

**Issue by AjayRawat001** [vercel/vercel#3126]
## we have a root repository that has next.js app inside /web folder and a now.json file in the root.
# now.json
```
{
   "name": "App-Name",
   "version": 2,
   "builds": [{ "src": "/web/next.config.js", "use": "@now/next" }],
   "routes": [
   {
     "src": "/static/(.*)",
     "headers": { "cache-control": "s-maxage=604800" },
     "dest": "/web/static/$1"
   },
  {
     "src": "(.*)",
     "dest": "/web$1",
     "continue": true
  }
  ]
}
```
Desired behavior-
Reload any dynamic route, should load the related content.
Actual behavior-
Reload any page other than the home page, getting an error of 404

**Comment by styfle** [comment]
It looks like you forgot the asterisk for the wildcard regex.

`(.)` should probably be `(.*)`

**Comment by AjayRawat001** [comment]
Thanks Steven,
it's added but still the same error.

**Comment by styfle** [comment]
Are you on the latest Next.js and React?

Can you provide the code to reproduce this issue? Thanks!

**Comment by chrisdrackett** [comment]
I'm pretty sure I'm running into this same thing. I'll try and get an example repo up

**Comment by chrisdrackett** [comment]
I was actually able to get this running using the above code as a guide. my issue was that I was missing the `continue`, I'm still confused as to why that helps in this case.
