### ISSUE TITLE
Problem with GitLab dependency

### ISSUE THREAD

**Issue by amytych** [vercel/vercel#313]
Hi,

I'm trying to specify GitLab repository as a dependency of my project but it fails when `npm install` runs on now deployment.

I tried putting  `"wsdm-tooltip": "gitlab:lapidusinteractive/wsdm-tooltip"` in my package.json. It works perfectly on my local machine.

On now it seems that it tries to fetch this repo from github as indicated by this part of the log

```
Error { HTTPError
    at EventEmitter.<anonymous> (/usr/lib/node_modules/@zeit/ace/node_modules/got/index.js:187:24)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:188:7)
    at Immediate.<anonymous> (/usr/lib/node_modules/@zeit/ace/node_modules/got/index.js:55:8)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
  message: 'Response code 404 (Not Found)',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/lapidusinteractive/wsdm-tooltip/raw/archive/master.tar.gz',
  statusCode: 404,
  statusMessage: 'Not Found' }
```

I tried different ways of specifying the repo in the package.json, like suggested in the npm docs.
I also tried the suggested ways from this blog post https://zeit.co/blog/package-installation-improvements, , including the full repo url:
`"wsdm-tooltip": "https://gitlab.com/lapidusinteractive/wsdm-tooltip"

No matter what I try, the host in this log shows up as github.com
I'd really appreciate any help, thank you!

**Comment by hugomd** [comment]
@amytych I think this is server-side and not directly related to `now-cli`, and I suspect that GitLab isn't yet supported. In the meantime, I'd suggest making a feature request, and making do with forking `LapidusInteractive/wsdm-tooltip` locally.

**Comment by leo** [comment]
If this problem still occurs, please move it over to [this repo](https://github.com/zeit/now-cloud). That's where we'll collect the bugs of the platform from now on (separate space, easier to work on)! 😊
