### ISSUE TITLE
[now-next] now dev does not work with the new src directory

### ISSUE THREAD

**Issue by hoangvvo** [vercel/vercel#3133]
Running `now dev` while having everything the `src` directory does not work. `next build` still works.

Next.js `v9.1.0`.
No `now.json`.

![Screenshot from 2019-10-07 20-37-27](https://user-images.githubusercontent.com/40987398/66358765-5a15c400-e942-11e9-8ca1-e3a68b753f11.png)

Thanks!

**Comment by ahonn** [comment]
Please as soon as possible release a new version to support src directory

**Comment by rudeayelo** [comment]
@ahonn it's already available in `now@canary`

**Comment by einaralex** [comment]
Nice! Works out of the box in now@canary without a `now.json`, but if you're using a `now.json` then you'll have to specify `:src`.

```
{
  "version": 2,
  "builds": [
    {
      "src": "next.config.js",
      "use": "@now/next:src"
    }
  ]
}
```

**Comment by einaralex** [comment]
Nice! If you're using a `now.json` you have to add `@now/next@canary` as src.
```
{
  "version": 2,
  "builds": [
    {
      "src": "package.json",
      "use": "@now/next@canary"
    }
  ]
}

```

**Comment by rudeayelo** [comment]
@einaralex is that so? It worked for me out of the box in all environments just by upgrading to `now@canary`.

**Comment by einaralex** [comment]
Yeah, with `now dev` when I remove my now.json, it logs the builder name when initializing.
Without a now.json, it outputs `@now/next@canary` and works.
If it's built with `@now/next` it doesn't work, just get an index page with a package.json.

![image](https://user-images.githubusercontent.com/2564144/67164174-18841080-f367-11e9-916b-670c82fca60b.png)
