### ISSUE TITLE
Color-coded terminal output from Next.js not included in 'now dev' output

### ISSUE THREAD

**Issue by trymbill** [vercel/vercel#3135]
<img width="579" alt="Screen Shot 2019-10-08 at 11 03 50 AM" src="https://user-images.githubusercontent.com/658727/66424620-cf28de00-e9c2-11e9-83b3-3199f560f210.png">

It would be really nice having the color-coded terminal output coming from Next.js included in the terminal output of `now dev`. Would make for a more easily scannable terminal and a better developer experience.

**Comment by TooTallNate** [comment]
Thanks for the report. This will be fixed by https://github.com/zeit/now/pull/3113.
