### ISSUE TITLE
The specified token is not valid immediately after installing

### ISSUE THREAD

**Issue by imyjimmy** [vercel/vercel#3143]
I ran the following:
```
npm i -g now
now
```
and got:
```
> Error! The specified token is not valid
```

now version 16.3.1

Disclaimer: I had previously tried and uninstalled now.

**Comment by styfle** [comment]
Hi @imyjimmy 

This error message could be improved.

You probably need to run `now logout` and then `now login` to generate a new token.

**Comment by Roeck** [comment]
Did you solve it?
I'm having the same problem and running 'now logout' returns me the same error...

**Comment by ronderins** [comment]
@imyjimmy  Did you solve it?
I'm having the same problem and running 'now logout' returns me the same error...

**Comment by maru0014** [comment]
An error occurred no matter how many times I logged out, but disabling Kaspersky and restarting solved it.

**Comment by styfle** [comment]
Please try `npm i -g now@canary` and then `now logout`.

**Comment by markybry** [comment]
> Hi @imyjimmy
> 
> This error message could be improved.
> 
> You probably need to run `now logout` and then `now login` to generate a new token.

Better still it could ask you to login again or use refresh tokens

**Comment by WilliamConnatser** [comment]
Yes, the UX on this error could be much better. I found this via Google, but simply logging me out and re-initiating the log in process would have been a much better experience than some cryptic error message.

**Comment by iMrihan** [comment]
How to resolve this issue?

Error! The specified token is not valid. Use `vercel login` to generate a new token.
