### ISSUE TITLE
Deploying to unverified domain results in unhelpful error

### ISSUE THREAD

**Issue by unitof** [vercel/vercel#3150]
1. Add domain to your account but *do not* verify it (meaning, you'll have to add a domain currently registered to someone else). `example.com` is a perfect test case.
```
now domains add example.com
```
2. Create a v2 project with the `alias` of the domain you added above.
```
{
  "version": 2,
  "name": "example.com",
  "alias": "example.com"
}
```
3. Run `now --prod`. If it is the first time you are deploying, simply running `now` will also cause this behavior.
4. Eventually you'll receive the error:
```
> Error! Cannot read property 'indexOf' of undefined
```

`now --prod --debug` reveals the following (truncating to last few seemingly relevant lines):
```
[now-client-debug] 2019-10-10T16:35:07.480Z Creating the deployment and starting upload...
[now-client-debug] 2019-10-10T16:35:07.480Z Determining necessary files for upload...
[now-client-debug] 2019-10-10T16:35:07.481Z Creating deployment
[now-client-debug] 2019-10-10T16:35:07.481Z Sending deployment creation API request
[now-client-debug] 2019-10-10T16:35:08.010Z Deployment response: {"error":{"code":"domain_not_verified","message":"The domain example.com is not verfied and cannot be used as an alias"}}
[now-client-debug] 2019-10-10T16:35:08.010Z Error: Deployment request status is 400
[now-client-debug] 2019-10-10T16:35:08.010Z Yielding a 'error' event
> [debug] [2019-10-10T16:35:08.306Z] Error: TypeError: Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at /usr/local/lib/node_modules/now/dist/index.js:2:1125385
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/now/dist/index.js:2:1125072
    at new Promise (<anonymous>)
    at r (/usr/local/lib/node_modules/now/dist/index.js:2:1124804)
    at getDeploymentByIdOrHost (/usr/local/lib/node_modules/now/dist/index.js:2:1125326)
    at Module.main (/usr/local/lib/node_modules/now/dist/index.js:2:2580834)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at xe (/usr/local/lib/node_modules/now/dist/index.js:2:1518400)
> Error! Cannot read property 'indexOf' of undefined
```

**Comment by unitof** [comment]
I'm not gonna be fast to work on this and will probably need plenty of code review but unless anybody else objects I'd love to take it on as part of my [Hacktoberfest](https://hacktoberfest.digitalocean.com) challenge.

**Comment by unitof** [comment]
Clearly it's aware of the relevant error in this case, (`[now-client-debug] 2019-10-10T16:35:08.010Z Deployment response: {"error":{"code":"domain_not_verified","message":"The domain example.com is not verfied and cannot be used as an alias"}}
`) but somewhere along the line of passing that to the user it hits and presents this `indexOf` error instead.

**Comment by styfle** [comment]
Hi @unitof 

Thanks for reporting this bug!

If you would like to submit a PR to fix this for Hacktoberfest, that would be wonderful!
