### ISSUE TITLE
I can run my node website on my line with "start server.js"

### ISSUE THREAD

**Issue by SkySibe** [vercel/vercel#3151]
(*can run on my LAN)
But then when i've tried to use now I needed to add a "build script",
so I added ' "build": "node server.js" ' to the scripts section inside the package.json file,
and I ran the command "now" and waited 30 minutes untill I've got an error with this log:

Installing build runtime...
--
08:53:58 PM | Build runtime installed: 735.786ms
08:53:59 PM | Looking up build cache...
08:53:59 PM | Installing dependencies...
08:53:59 PM | yarn install v1.17.3
08:53:59 PM | info No lockfile found.
08:53:59 PM | [1/4] Resolving packages...
08:54:04 PM | [2/4] Fetching packages...
08:54:10 PM | [3/4] Linking dependencies...
08:54:10 PM | warning "firebase > @firebase/storage@0.2.15" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/functions@0.4.6" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/messaging@0.3.19" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/database@0.3.20" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/firestore@1.2.2" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/auth > @firebase/auth-types@0.6.1" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/auth > @firebase/auth-types@0.6.1" has unmet peer dependency "@firebase/util@0.x".
08:54:10 PM | warning "firebase > @firebase/performance@0.2.1" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/storage > @firebase/storage-types@0.2.11" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/storage > @firebase/storage-types@0.2.11" has unmet peer dependency "@firebase/util@0.x".
08:54:10 PM | warning "firebase > @firebase/functions > @firebase/messaging-types@0.2.11" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/database > @firebase/database-types@0.3.11" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/firestore > @firebase/firestore-types@1.2.1" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/performance > @firebase/installations@0.1.0" has unmet peer dependency "@firebase/app-types@0.x".
08:54:10 PM | warning "firebase > @firebase/performance > @firebase/installations > @firebase/installations-types@0.1.0" has unmet peer dependency "@firebase/app-types@0.x".
08:54:11 PM | [4/4] Building fresh packages...
08:54:12 PM | success Saved lockfile.
08:54:12 PM | Done in 12.53s.
08:54:12 PM | Running "yarn run build"
08:54:12 PM | yarn run v1.17.3
08:54:12 PM | $ node server.js
08:54:12 PM | Server running on: 169.254.172.42:80

can someone figure this out?
(sorry if i've used bad English)

**Comment by styfle** [comment]
Indeed, this will never build because you are invoking node to listen instead of build.

It sounds like you probably don't need a build step. So instead you can create an api folder with an index file like this: `/api/index.js`.

See an example introduction here: https://zeit.co/docs/v2/serverless-functions/introduction

Also read about migrating an existing app to ZEIT Now here: https://zeit.co/guides/migrate-to-zeit-now
