### ISSUE TITLE
Routes regex inconsistency between now dev and production.

### ISSUE THREAD

**Issue by emielta** [vercel/vercel#3156]
When using a route that looks like this:
```json
{
  "routes": [
    {
      "src": "/resource/([0-9a-f]{2})([0-9a-f]{38})",
      "status": 302,
      "headers": { "Location": "https://example.com/resource/$1/$1$2.dat" }
    }
  ]
}
```
Everything works as expected in `now dev` mode. But when running in production users are redirected 
from: `https://example.now.sh/resources/2ef7bde608ce5404e97d5f042f95f89f1c232871`
to: `https://example.com/resource/2e/$1f7bde608ce5404e97d5f042f95f89f1c232871.dat`
  
It seems the production implementation doesn't replace all instances of `$1` and thus repetitive use of match groups for substitution only works in dev mode.

**Comment by dav-is** [comment]
This issue was fixed in production and closed by an internal pull request :+1:
