### ISSUE TITLE
[now-dev] "Invalid `builds` property" when property not set

### ISSUE THREAD

**Issue by hormesiel** [vercel/vercel#3159]
I get the following error when running `now dev` in a directory where there's a `build/` directory alongside the `now.json` file :

```bash
> Error! Invalid `builds` property:  should NOT have more than 128 items
```

I don't have any `builds` property defined in my `now.json` :

```json
{
  "version": 2,
  "name": "my-website",
  "routes": [
    { "src": "/catalogue",
      "dest": "index.html" },
    { "src": "/contactez-nous",
      "dest": "index.html" },
    { "src": "/qui-sommes-nous",
      "dest": "index.html" }
  ]
}
```

But the `build/` directory indeed contains more than 128 files, and `now dev` is confusing it with a `builds` property.

Unfortunately I can't change the name of this directory because it's automatically generated by [Stencil.js](https://github.com/ionic-team/stencil).

**Comment by styfle** [comment]
Hi @flawyte 

I was unable to reproduce this error using both `now@latest` and `now@canary`.

Here's what I tried:

```
npm init stencil
# selected app and named it app
cd app
npm install
now dev
```

With now@latest, I get an error that there is no `public` directory which is expected since the output goes to `www` instead of `public`. Adding a `mv www public` can fix that or using now@canary which automatically uses `www` when it detects stencil since PR #3158.

**Comment by hormesiel** [comment]
Hi @styfle 

My project setup is a little bit different from the starter project. I have a `now.json` file at my project's root and I use a [copy task](https://stenciljs.com/docs/copy-tasks) to copy it to the `www/` build directory. Then I run `now dev` from **inside** the `www/` directory, not from the project's root.

I've created a [reprod repo](https://github.com/flawyte/issue-now-stencil-build) :

```bash
git clone https://github.com/flawyte/issue-now-stencil-build.git
cd issue-now-stencil-build/
npm install
npm start
npm run serve # There's the error
```

Now if you remove the `api/` dir from `www/` and run `npm run serve` again you'll see that the problem is gone. So it seems that the problem isn't related to the `build/` dir but `api/`.

Now maybe the PR you mentioned would fix the problem if I change my project's structure a little bit. I'll try it once it's released.

Also, I'm using the `ionic-pwa` starter, not `app` (though I don't think it makes a difference).

**Comment by styfle** [comment]
Fixed in #3167, Thanks for the bug report! 

This will be available in the canary channel and make its way to the stable channel soon.

**Comment by vincentriemer** [comment]
I started a migration from `builds` to `functions` and I'm experiencing this same issue in both the `latest` and `canary` tags.

**Comment by styfle** [comment]
Hi @vincentriemer 

Can you create a new issue with the steps to reproduce? 

What's in now.json? What dependencies do you have in package.json? etc

Thanks!
