### ISSUE TITLE
Can't install via npm -> 404 Not Found

### ISSUE THREAD

**Issue by c0nscience** [vercel/vercel#316]
Hi,

I struggle to install the cli with npm. When I run
`npm install -g now` (in my case with sudo)
It failes with:

```
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
npm ERR! <html><head>
npm ERR! <title>404 Not Found</title>
npm ERR! </head><body>
npm ERR! <h1>Not Found</h1>
npm ERR! <p>The requested URL /@google/maps was not found on this server.</p>
npm ERR! </body></html>
```

Environment:
OS: OS X El Capita 10.11.6
Node: 7.5.0
NPM: 4.1.2

**Comment by matheuss** [comment]
@c0nscience I can't reproduce that 🤔 Looks like a network error. It's still happening?

**Comment by c0nscience** [comment]
Hi thanks for answering :) Yeah it seams that I have overwritten the registry config -.- I was not aware of the fact. After removing the entry it works. Sorry for bothering. I'll close the issue.

**Comment by matheuss** [comment]
Glad to know! Don't worry 🙌
