### ISSUE TITLE
`now dev` sometimes runs `now-build` undesirably

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#3163]
`now dev` runs `package.json`'s `now-build`. 

This is desirable for certain types of builds and when one wants to closely recreate the production environment. But it can be undesirable, at least, in the case of linting or testing. 

It's unncessary to lint and run tests before the development server starts. And doing so delays its start and restart, slowing the feedback loop. 

A workaround would be to use `per-env`:

```
{ 
  "now-build": "per-env",
  "now-build:development": "",
  "now-build:production": "npm run lint && npm test"
}
```

However, this would mean setting `NODE_ENV=production`, which would cause `now-build` to fail because of missing packages. 

A workaround to this workaround would be to set `NODE_ENV=production` and run `npm install production=false`. But Now doesn't provide a mechanism for passing flags to `npm install`.

**Comment by styfle** [comment]
Hi @rhucle 

It sounds like your lint and tests should not be part of the `now-build` script. Instead, you could use a `test` script. This would also speed up your production deployments.

https://docs.npmjs.com/cli/test.html

**Comment by ghost** [comment]
I'm using `npm test`. You're saying I should just remove `npm test` from `now-build`? How, then, can I ensure that Now builds fails when tests fail?

**Comment by styfle** [comment]
Typically, you would use a separate service to run tests such as GitHub Actions / Circle CI / Travis CI / etc.

Then your PRs can have two checks, CI and CD.

These can run concurrently and block the PR from being merged if one fails.

![image](https://user-images.githubusercontent.com/229881/67038220-fda66780-f0ec-11e9-99eb-19b57659bd91.png)

I'll pass your feedback to the team and see if there is a better solution for your use case. Thanks!
