### ISSUE TITLE
File permissions are not preserved with now@16.3.0 and up

### ISSUE THREAD

**Issue by StefMa** [vercel/vercel#3172]
I using the following config to upload a executable file in my `now.json`:
```json
  "builds": [
    {
      "src": "index.go",
      "use": "@now/go",
      "config": {
        "includeFiles": [
          "domain/files/myExec"
        ]
      }
    }]
```
..and using it with this code:
```go
cmd := exec.Command("./domain/files/myExec")
err := cmd.Run()
```

This worked fine with `16.2.0`.
Today I updated to `16.3.1` (and also testet `16.3.0` - same issue) and for some reasons I get this error:
> Error: fork/exec ./domain/files/myExec: permission denied ()

From my naiv point of view it looks like that the permission of that file aren't set in 16.3.+ anymore.
But could be also totally wrong 😂 

For now I will stick at `16.2.0`. So not a very important fix required for me  but maybe for others.

**Comment by styfle** [comment]
Hi @StefMa 

Thanks for reporting this bug.

Would you mind sharing the permissions you are expecting for the `domain/files/myExec` file?

```sh
ls -l domain/files/myExec # this should print permissions
```

**Comment by StefMa** [comment]
Yeah, sure.
<img width="429" alt="Bildschirmfoto 2019-10-20 um 19 04 35" src="https://user-images.githubusercontent.com/10229883/67163206-79faae00-f36c-11e9-8680-e8fcfa7014f1.png">

**Comment by StefMa** [comment]
Does this failing test in #3180 means you can reproduce it?

**Comment by styfle** [comment]
@StefMa Yes, thanks! A cursory look did not turn up anything so @rdev is looking at the root cause.

**Comment by StefMa** [comment]
Awesome 🎉.
In which version can I expect a fix?
16.5 or is there a 16.4.5 planned?

**Comment by styfle** [comment]
Hi @StefMa 

This fix is available in the canary channel and will be available in the next stable release.

Run `npm i -g now@canary` to get the latest canary version.
