### ISSUE TITLE
@now/node and @now/node-server isn't working for me!!!

### ISSUE THREAD

**Issue by kumarabhirup** [vercel/vercel#3175]
I am using a monorepo like this 👇
https://github.com/iqubex-technologies/adify/tree/backend-integration

The backend is equipped with Express.js and TypeScript while the frontend is based on `Next.js`...

I succesfully deployed my frontend at https://adify.tech, but the backend at the `api` route still isn't functioning as expected.

Here's my `now.json`:

```
{
  "version": 2,
  "name": "adify",
  "public": true,
  "alias": ["adify", "adify.tech", "www.adify.tech"],
  "scope": "iqubex-technologies",
  "build": {
    "env": {
      "ADIFY_GA_TRACKING_ID": "@adifygatrackingid",
      "ADIFY_STEIN_API_KEY": "@adifysteinapikey",
      "ADIFY_STEIN_API_USERNAME": "@adifysteinapiusername",
      "ADIFY_STEIN_API_PASSWORD": "@adifysteinapipassword"
    }
  },
  "builds": [{
    "src": "packages/web/package.json",
    "use": "@now/next"
  }, {
    "src": "packages/backend/src/index.ts",
    "use": "@now/node-server@canary"
  }],
  "routes": [{
    "src": "/api/(.*)",
    "dest": "packages/backend/src/$1"
  }, {
    "src": "(.*)",
    "dest": "packages/web$1",
    "continue": true
  }]
}
```

You can check out the complete repository branch here: https://github.com/iqubex-technologies/adify/tree/backend-integration

I searched throughout StackOverflow and the Internet but found nothing that works. I tried using both `@now/node` and `@now/node-server`. Also tried the canary versions of it. I tried altering the `dest` and `src` in `builds` and `routes`... Nothing deployed my backend at the `api` route!

**Thanks in advance!**

**Comment by styfle** [comment]
Hi @KumarAbhirup 

The `@now/node-server` builder has been replaced with `@now/node`.

Can you explain what "isn't functioning as expected" when using `@now/node`?

What did you try and what did you expect to happen? Thanks!

**Comment by kumarabhirup** [comment]
**What I expect to happen:**
At the `/api` route, the `/packages/backend/src/index.ts` should start. But it gives me a 404 error.

**What I tried:**
I tried altering the `dest` and `src` in builds and routes... Nothing deployed my backend at the API route!

Please check this branch, here see all the commits starting with the prefix `TRY`... That is all that I've tried.
https://github.com/iqubex-technologies/adify/tree/backend-integration

**Comment by styfle** [comment]
The error message says `TypeError: express_1.default is not a function`

Try setting `esModuleInterop: true` in `tsconfig.json`.

Also, I would recommend avoiding `routes` and use Next.js api middleware like this: https://nextjs.org/docs#api-middlewares

**Comment by kumarabhirup** [comment]
Found the solution here: https://spectrum.chat/zeit/now/cant-seem-to-get-routing-to-work-on-monorepo~7057d6b7-e663-4bae-a0dc-fe7936ee8213

Thank you so much for the help ❤️
