### ISSUE TITLE
Can't add CNAME to apex domain in now-cli (now dns).

### ISSUE THREAD

**Issue by r00dY** [vercel/vercel#3176]
Hi

I bought a domain via Now. I want subdomains to be run via Now (demo projects), but main domain (www and apex) should be directed to Netlify.

`now dns add commerce-ui.com www CNAME commerce-ui.netlify.com`

Works OK.

`now dns add commerce-ui.com '@' CNAME commerce-ui.netlify.com`
> Error! Invalid `name` parameter (can't be empty) (400)

It seems I can't add CNAME for apex domain. How can I do this?

**Comment by styfle** [comment]
Hi @r00dY 

I think you should use ALIAS instead of CNAME for the apex domain

```
now dns add commerce-ui.com '@' ALIAS commerce-ui.netlify.com
```

That being said, is there a reason why you are adding a DNS record instead of deploying your `commerce-ui` website to ZEIT Now?

**Comment by r00dY** [comment]
Thanks, trying this out!

@styfle I'd prefer to use Now. But Netlify have built-in forms for static sites. Not a huge feature, but if you want get sth done super fast then it seemed like the best solution.

EDIT: ALIAS works, thank you! 👍💪

**Comment by mcsdevv** [comment]
Hey @r00dY, just to give you some other options here, StaticKit have a [great integration](https://statickit.com/zeit) with ZEIT Now that makes managing forms on a static site super easy!

Along with this, we have guides on using [StaticKit](https://zeit.co/guides/deploying-statickit-with-zeit-now/) and [Formspree](https://zeit.co/guides/deploying-react-forms-using-formspree-with-zeit-now/). Getting started with Formspree on ZEIT is also really easy, there's even a [dedicated page](https://formspree.io/create/zeit) to help you do so.

**Comment by r00dY** [comment]
Ah, okay, that's easier. In this case we'll probably migrate soon, thanks! 👍

**Comment by mcsdevv** [comment]
We're always looking to make things easier! If there's ever anything you feel could be more straightforward or quicker to achieve then please let us know.
