### ISSUE TITLE
"now alias" without package.json

### ISSUE THREAD

**Issue by raneio** [vercel/vercel#318]
I want use now.json with static website.

```
now alias
> Error! Failed to read JSON in "/Users/me/project/package.json"
```

**Comment by rauchg** [comment]
You can set up `now.json` as well.
https://zeit.co/blog/now-json

**Comment by rauchg** [comment]
Oh, you're using `now.json`

**Comment by leo** [comment]
@RaneIO I just tried to reproduce this and it looks like your deployment type is set to "npm" (that's the default one). However, there's no `package.json`...

So please either set the "type" property in your `now.json` to "docker" or use `now --docker` if your project is not node-based.

**Comment by raneio** [comment]
Then I can't deploy without Dockerfile.

```
now
> Deploying ~/myProject
> Error! Unknown error: Error: Failed to parse "/Users/me/myProject/Dockerfile"
Error: Failed to parse "/Users/me/myProject/Dockerfile"
    at Error (native)
    at /usr/local/lib/node_modules/now/build/lib/read-metadata.js:93:17
    at throw (native)
    at c (/usr/local/lib/node_modules/now/build/lib/read-metadata.js:172:99)
    at d (/usr/local/lib/node_modules/now/build/lib/read-metadata.js:172:191)
```

And type can't be "static".

**Comment by leo** [comment]
@RaneIO Have you tried `--static`?

**Comment by raneio** [comment]
Yeah, I try --static, but it still want package.json.

Type "static" is not supported.
`Unsupported "deploymentType": static`

**Comment by leo** [comment]
@RaneIO That should work now! https://github.com/zeit/now-cli/releases/tag/4.5.5

**Comment by raneio** [comment]
I try to update, but it's still in version 4.5.4 and deploying not found "retry".

```
npm i -g now
/usr/local/bin/now -> /usr/local/lib/node_modules/now/build/bin/now.js
/usr/local/lib
└── now@4.5.5
```

```
now -v
4.5.4
```

```
now
> Deploying ~/myProject
> Error! Unexpected error. Please try later. (retry is not a function)
```

**Comment by leo** [comment]
[Fixed!](https://github.com/zeit/now-cli/releases/tag/4.5.6)
