### ISSUE TITLE
NextJS with golang functions

### ISSUE THREAD

**Issue by tylerwray** [vercel/vercel#3185]
I'm trying to get NextJS and Zeit working with Go functions, but it doesn't seem to work. I can't find anything that says they do or don't work.

I've tried a myriad of different things to get it working, but I would expect to be able to put the basic `date.go` function in the `pages/api` directory and it just work. 

My [Repo](https://github.com/tylerwray/starcourt)
My [Zeit Project](https://zeit.co/tylerwray/starcourt)
My [Expected api endpoint](https://wealthyment.com/api/date)

**Comment by styfle** [comment]
The `/pages/api` directory is for [Next.js APIs](https://nextjs.org/docs#api-routes).

If you want write serverless functions another [supported language](https://zeit.co/docs/v2/serverless-functions/supported-languages), then you will need to use the root `/api` directory.

**Comment by tylerwray** [comment]
That worked haha thank you! I'm going to update the documentation a little bit because the way it is phrased makes me think that with NextJS you can ONLY add serverless functions under `pages/api`

**Comment by daveteu** [comment]
@tylerwray did you manage to set it up in a single deployment or does it have to split in to separate deployments?

I have a `/api` in root directory which runs flawlessly on it's own, but if I install nextjs in the same root directory, the golang api doesn't work any more with the same vercel conf.

```
{
  "rewrites": [{ "source": "/api/(.*)", "destination": "./api/index.go" }],
}
```
