### ISSUE TITLE
Determine deployment type automatically

### ISSUE THREAD

**Issue by leo** [vercel/vercel#319]
- package.json and dockerfile => docker
- dockerfile => docker
- package.json => npm
- no meta file => static
- item is a file, not a folder => static

It will never prompt and just let the user define with "--docker", "--static" and "--npm" and to the remaining determination part (if no flag defined) automatically by itself.

**Comment by hugomd** [comment]
@leo I've partially done this in #321 — it determines deployment type as `static` if `type` isn't defined in `now.json`.

**Comment by leo** [comment]
https://github.com/zeit/now-cli/pull/589
