### ISSUE TITLE
`config/.env` file not uploaded

### ISSUE THREAD

**Issue by mrm007** [vercel/vercel#3199]
We have a `config/.env` file that stores our environment variables. After upgrading from Now 16.2 to Now 16.3+ the file is no longer uploaded on deploy. [This is the relevant change](https://github.com/zeit/now/pull/3092/files#diff-013ad7a3fc0ddbdfea94def4f3772fdaR60-R100). The module [`ignore`](https://github.com/kaelzhang/node-ignore) is introduced in that PR which changes the behavior of the `.nowignore` file. Now the entry `.env` matches `config/.env` as well as a `.env` in the root.

**Comment by eyaleizenberg** [comment]
@mrm007 Same here. Did you find a workaround for using .env file?

It looks like locally the .env file is not loading up anymore...

**Comment by mrm007** [comment]
Downgrade to 16.2 or rename the file. In the meantime we are looking at alternatives since v2 is not working for us.

**Comment by airjp73** [comment]
Also having the same problem. It works if I use 16.3.1, but not if I use a later version.

**Comment by LoicMahieu** [comment]
We are also using a `.env.js` file at the root of our project. Since 16.7, the files is not being uploaded to Now.
We downgrade to 16.6 and it works.

**Comment by kaleabmelkie** [comment]
Same problem here

**Comment by mirshko** [comment]
Seem to be having an issue with .env in latest v17 as well.

For local development specifically. Doesn't pick them up anymore.

**Comment by styfle** [comment]
The `.env` file typically has secrets so it is intentionally not uploaded.

The best way to use secrets is with [`now secrets`](https://zeit.co/docs/v2/serverless-functions/env-and-secrets) and soon `now env` (#3999).

**Comment by styfle** [comment]
Since [Now 18.0.0](https://github.com/zeit/now/releases/tag/now%4018.0.0) you can manage environment variables with `now env` or on the dashboard and then use `now env pull` to write a `.env` file that will be read by `now dev`.
