### ISSUE TITLE
API for getting the log / stdout / console out

### ISSUE THREAD

**Issue by martinheidegger** [vercel/vercel#32]
Currently now is hard to work with because it is not visible if something breaks (to my knowledge). 
It would be mighty helpful to get the log output of container.

**Comment by winneon** [comment]
+1

**Comment by tlvenn** [comment]
Hopefully the logs can be streamed to the now cli using a `now logs ...` command or similar

**Comment by gmaliandi** [comment]
+1

**Comment by berzniz** [comment]
I've created an unofficial `now-logs` utility to stream realtime output to your terminal (https://logs.now.sh). It's open source of course and uses the `now` tools to operate.

(Updated with correct link - thanks @juanpabloaj)

**Comment by martinheidegger** [comment]
@berzniz while this is neat, it actually is not logging the output before the statup (i.e. docker build output)

**Comment by juanpabloaj** [comment]
@berzniz is the url fine? ...maybe is https://logs.now.sh/ ?

**Comment by win0na** [comment]
@juanpabloaj It is.

**Comment by adrianmcli** [comment]
Is there still no officially supported way of seeing the console output?

**Comment by matheuss** [comment]
I'm happy to inform that we currently have a member of the team working on this feature 🚀 Make sure to keep an 👁 out on our Twitter ([@zeithq](https://twitter.com/zeithq) for news on that 😄

**Comment by Cynaraa** [comment]
Is there any update here?

**Comment by matheuss** [comment]
🔜

**Comment by alexpriceco** [comment]
@matheuss, any updates?  😏🔜

**Comment by leo** [comment]
We'll announce updates on [Twitter](https://twitter.com/zeithq)! 😊

**Comment by leo** [comment]
Check [this](https://twitter.com/zeithq/status/858374346015817728) out. The team is currently relaxing a bit from the conf, but we'll release the update for the CLI very soon! 😏

**Comment by nth-chile** [comment]
> Check [this](https://twitter.com/zeithq/status/858374346015817728) out. The team is currently relaxing a bit from the conf, but we'll release the update for the CLI very soon! 😏

It seems like `$ now logs` shows logs written by some Now process during the deployment's build process, but is not Node stderr/stdout. Meaning, developers still cannot debug their `index.js`. Unless there is a way to log to the output produced by `$ now logs` from `index.js`?

Thanks
