### ISSUE TITLE
bug: CLI uses folder name instead of `name` property specified in custom config

### ISSUE THREAD

**Issue by NoNameProvided** [vercel/vercel#3209]
When running the following command: 

```bash
now ./dist/myproject-dashboard --local-config ./now-staging.json --token ${NOW_TOKEN}
```

With the following `now-staging.json`:

```json
{
  "name": "myproject-dashboard-preview",
  "scope": "myorg",
  "version": 2,
  "alias": "dashboard.preview.myproject.com",
  "routes": [{ "handle": "filesystem" }, { "src": "/.*", "dest": "/index.html" }]
}
```

The CLI will upload the code to a project matching the folder name (`myproject-dashboard`) instead of correctly using the specified `name` in the custom config.

CLI version:
```
❯ now -v 
16.4.3
```

**Comment by styfle** [comment]
Thanks for reporting this bug!

The workaround is to move `now-staging.json` into the deployment directory.

```bash
cp now-staging.json ./dist/myproject-dashboard/ && \
cd ./dist/myproject-dashboard && \
now --local-config ./now-staging.json --token ${NOW_TOKEN}
```

I'll add a test fixture for your usage in PR #3293, thanks!

**Comment by styfle** [comment]
This has been fixed in the canary channel, thanks! `npm i -g now@canary`
