### ISSUE TITLE
FAAS no cors headers

### ISSUE THREAD

**Issue by negati-ve** [vercel/vercel#3210]
Hi, 

I'm using "now" cli to deploy a function as a service which is consumed as an api from another domain

The problem is my function does not have any cors header

How do I add Access-Control-Allow-Origin: * header ?

Thanks in advance,
Cheers!

**Comment by negati-ve** [comment]
figured it out.. 

added 
`res.setHeader('Access-Control-Allow-Origin', '*')
`in my module.exports = (req, res) => {}

**Comment by martiuh** [comment]
I added 

```
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'Origin, X-Requested-With, Content-Type, Accept'
  );
```

And it worked
