### ISSUE TITLE
Inconsistent CLI DNS results

### ISSUE THREAD

**Issue by estevanmaito** [vercel/vercel#3236]
It took me some hours of testing until I decided to remove the problematic DNS record, just to realize that the Now DNS CLI command shows different results depending on what command you use.

It happened while configuring DKIM record of my Zoho email, but it has nothing to do with Zoho.

**Step 1**

`now dns add example.com example._domainkey.example.com TXT "v=DKIM1; k=rsa; p=<long string>"`

"Oh, my record isn't working" (checked [here](https://dkimcore.org/tools/keycheck.html))

**Step 2**

Let's see if it's everything ok with the record I've added

`now dns ls`

`rec_<long string> example._domainkey.example.com   TXT   v=DKIM1; k=rsa; p=<long string>  4m ago`

"Looks good to me"

**Step 3**

Problem persists and I decide to remove the record

`now dns rm rec_<long string>`

```sh
The following record will be removed permanently
rec_<long string> example._domainkey.example.com.example.com TXT v=DKIM1; k=rsa; p=<long string>
```

"Oh..."

It happens that, even though the record is shown as `example._domainkey.example.com` using `now dns ls`, it's stored as `example._domainkey.example.com.example.com`.

Actually, this is the second issue I've had with this behaviour, and now it's pretty obvious that Now adds the domain to the subdomain automatically.

This could be solved, obviously, showing the exact record, but it also could be stated in the docs that this is the default behaviour (adding the domain automatically).

Also, much time searching for examples (mostly on spectrum) could be saved with some common examples in the docs like MX, TXT, DKIM, SPF, simply adding a subdomain. Like, for example:

Hey, you need to add this MX record? `@ mx.zoho.com 10`

Do this! `now dns add '@' mx.zoho.com 10`

**Comment by sanderfish** [comment]
Ran into the same issue twice this week (yes, bad short term memory).

**Comment by mcsdevv** [comment]
Closing this as `now dns` is now fully documented: https://zeit.co/docs/now-cli#commands/dns
