### ISSUE TITLE
“Unexpected error. Please try again later. ()”

### ISSUE THREAD

**Issue by tomsoderlund** [vercel/vercel#3237]
This is an Next.js + API app. Running locally works, deploying fails:

	$ now dev --listen 3101
	> Now CLI 16.4.4 dev (beta) — https://zeit.co/feedback/dev
	> Creating initial build
	[ ready ] compiled successfully
	[ wait ]  compiling ...
	> Success! Build completed
	> Ready! Available at http://localhost:3101
	[ ready ] compiled successfully
	^C
	> Stopping `now dev` server

	$ now
	> Deploying ~/MyProjects/proj1 under tomsoderlund
	> Using project proj1
	> Error! Unexpected error. Please try again later. ()

package.json:

    {
      "name": "proj1",
      "version": "0.1.0",
      "author": "Tom Söderlund <tom@tomsoderlund.com>",
      "scripts": {
        "test": "echo 'Running Standard.js and Jasmine unit tests...\n' && yarn lint && yarn unit",
        "unit": "jasmine",
        "lint": "standard",
        "fix": "standard --fix",
        "build": "next build"
      },
      "standard": {
        "parser": "babel-eslint",
        "ignore": [
          ".next/",
          "next.config.js"
        ],
        "globals": [
          "describe",
          "expect",
          "it"
        ]
      },
      "engines": {
        "node": "^10.13.0",
        "yarn": "^1.3.2"
      },
      "dependencies": {
        "@apollo/react-hooks": "^3.1.2",
        "@apollo/react-ssr": "^3.1.2",
        "apollo-cache-inmemory": "1.6.3",
        "apollo-client": "2.6.4",
        "apollo-link-http": "1.5.15",
        "apollo-server-micro": "^2.9.7",
        "body-parser": "^1.18.3",
        "dotenv": "^6.2.0",
        "express": "^4.16.4",
        "glob": "^7.1.3",
        "graphql": "^14.4.1",
        "graphql-tag": "2.10.1",
        "heroku-ssl-redirect": "^0.0.4",
        "isomorphic-unfetch": "^3.0.0",
        "marked": "^0.7.0",
        "next": "latest",
        "next-offline": "^4.0.6",
        "pg": "^7.8.1",
        "prop-types": "^15.6.2",
        "react": "^16.8.3",
        "react-dom": "^16.8.3",
        "react-svg-inline": "^2.1.1",
        "sql-wizard": "^1.0.11",
        "svg-inline-loader": "^0.8.0",
        "use-debounce": "^3.1.0"
      },
      "devDependencies": {
        "babel-eslint": "^10.0.1",
        "jasmine": "^3.3.1",
        "nodemon": "^1.12.1",
        "standard": "^12.0.1"
      }
    }

now.json:

    {
      "version":2,
      "alias": ["proj1"],
      "regions":[
        "arn1"
      ]
    }

**Comment by tomsoderlund** [comment]
Received feedback on email - my domain was missing. Closing.

**Comment by antoniojps** [comment]
Hey, I'm having the same issue, what do you mean you were missing a domain?

**Comment by HP8585** [comment]
I also do have the same issue and is bugging me a lot at this point, what really do you mean by "missing your domain"??!!

**Comment by nitzanpap** [comment]
I had the same issue inside my github actions, but in my case it happened because my build just failed (I discovered that in the project deployment build).

So whoever encounters that, run you build locally again just to make sure.
