### ISSUE TITLE
404 status for api even status had been set if `/api` and `pages/api` folders both exist

### ISSUE THREAD

**Issue by happylolonly** [vercel/vercel#3241]
Hi, I had both `api` and `pages/api` folders, and even I got responce and data from api request status was 404.

I fixed it by renaming `api` folder.

**Comment by styfle** [comment]
Thanks for reporting this bug. We should probably show an error or a warning when both `/api` and `/pages/api` are present since this is not supported.

**Comment by styfle** [comment]
We are now showing a warning, thanks!
