### ISSUE TITLE
Now Dev Not Handling Next.js Errors Properly

### ISSUE THREAD

**Issue by laugharn** [vercel/vercel#3242]
Repo to reproduce with instructions: https://github.com/laugharn/repro

This might be related to #3103 but I am seeing two bits of weird behavior when I run a Next.js app in `now dev`:

* If a repo doesn't have a pages/index.js file, http://localhost:3000 serves up an empty static directory page instead of an error page
* If a repo _does_ have a pages/index.js file, it uses that file as the error page

This all works as expected when just running `yarn dev` and in production.

**Comment by leerob** [comment]
Hey! This issue has gone stale. If you're still having issues here, could you please open a new issue? 

Thank you so much 🙏
