### ISSUE TITLE
Ruby serverless API are not working anymore

### ISSUE THREAD

**Issue by zaratan** [vercel/vercel#3246]
Hi,

First of all, thanks for the ruby support.

I published some code ~7 days ago that was working just fine: https://github.com/denispasin/thp-landing
That's a simple API possible for a test, using a gem.

> Installing build runtime...
> --
> 09:01:22 PM | Build runtime installed: 2219.847ms
> 09:01:22 PM | Looking up build cache...
> 09:01:23 PM | downloading files...
> 09:01:23 PM | installing ruby...
> 09:01:23 PM | installing bundler...
> 09:01:23 PM | checking for existing vendor directory at "vendor/bundle/ruby/2.5.0"
> 09:01:23 PM | did not find a vendor directory but found a Gemfile, bundling gems...
> 09:01:23 PM | running "bundle install --deployment"...
> 09:01:56 PM | entrypoint is api/to_google_doc.rb
> 09:02:04 PM | done

It's not anymore. It seems to not detect and install gems as it did before.

> Installing build runtime...
> --
> 11:00:21 PM | Build runtime installed: 2210.095ms
> 11:00:21 PM | Looking up build cache...
> 11:01:05 PM | done

It's probably from this commit (the only one with ruby in it and between now and 7 days ago): https://github.com/zeit/now/commit/e36f3d355e58495d0356934f2ff26f7c3d8ba915

I'll try to understand the commit. Tell me if you need more things from me!

**Comment by zaratan** [comment]
Forgot to attach the error log:
```
START RequestId: 1978739a-d472-4a5d-84ad-6ecc8fc037eb Version: $LATEST
Ignoring nokogiri-1.10.5 because its extensions are not built. Try: gem pristine nokogiri --version 1.10.5
Critical exception from handler
{
  "errorMessage": "libruby.so.2.5: cannot open shared object file: No such file or directory - /var/task/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.5/lib/nokogiri/nokogiri.so",
  "errorType": "Function<LoadError>",
  "stackTrace": [
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.5/lib/nokogiri.rb:32:in `rescue in <top (required)>'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.5/lib/nokogiri.rb:28:in `<top (required)>'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/google_drive-3.0.3/lib/google_drive/session.rb:8:in `<top (required)>'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
    "/var/task/vendor/bundle/ruby/2.5.0/gems/google_drive-3.0.3/lib/google_drive.rb:7:in `<top (required)>'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'",
    "/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'",
    "/var/task/api/to_google_doc.rb:3:in `<top (required)>'",
    "/var/task/now__handler__ruby.rb:29:in `require_relative'",
    "/var/task/now__handler__ruby.rb:29:in `webrick_handler'",
    "/var/task/now__handler__ruby.rb:86:in `now__handler'"
  ]
}
END RequestId: 1978739a-d472-4a5d-84ad-6ecc8fc037eb
REPORT RequestId: 1978739a-d472-4a5d-84ad-6ecc8fc037eb	Duration: 254.13 ms	Billed Duration: 300 ms	Memory Size: 3008 MB	Max Memory Used: 74 MB	Init Duration: 160.66 ms	
Unknown application error occurred
Function<LoadError>
```

It's like nokogiri wasn't built.

**Comment by styfle** [comment]
Thanks for reporting this bug!

We are investigating the root cause of why extensions are not being built.

**Comment by igorklopov** [comment]
I think https://github.com/zeit/now/commit/e36f3d355e58495d0356934f2ff26f7c3d8ba915 is not included in stable `build-utils` (that are used if you deploy the repo as is).

**Comment by zaratan** [comment]
You are very right. Can I help in any way? If you give me a few pointers on where/when to look at. I may be able to do the fix by myself :)

**Comment by styfle** [comment]
Thanks for offering to help!

I was able to track the issue down to [ruby-build](https://github.com/rbenv/ruby-build) which is used to install the version of Ruby used in `@now/ruby`. It started using an older (possible broken) version of `bundler`. I will pin `ruby-build` to a previous version so that deployments continue working.

Eventually, we'll have to identify the root cause and get a proper fix [upstream](https://github.com/rbenv/ruby-build).

**Comment by zaratan** [comment]
This is still not working here (I just ran `now` on the broken test project). I think that the `nokogiri` gem is broken in a way (It might also be because of the fact that's it's a native extension and it just need to be rebuilt)

How do you do the gem/bundler caching? Could you force the reinstall of all of them?

**Comment by zaratan** [comment]
Error message being: 
```
"errorMessage": "libruby.so.2.5: cannot open shared object file: No such file or directory - /var/task/vendor/bundle/ruby/2.5.0/gems/nokogiri-1.10.3/lib/nokogiri/nokogiri.so",
```

**Comment by zaratan** [comment]
I renamed the main directory and redid a `now` to get the experience of a "new" project.

Still failing but the error is different:
```
[2019-11-08 22:55:44] INFO  WEBrick 1.4.2
[2019-11-08 22:55:44] INFO  ruby 2.5.7 (2019-10-01) [x86_64-linux]
[2019-11-08 22:55:44] INFO  WEBrick::HTTPServer#start: pid=9 port=3000
[2019-11-08 22:55:45] ERROR Signet::AuthorizationError: Authorization failed.  Server message:\n{\n  "error": "invalid_grant",\n  "error_description": "Invalid JWT Signature."\n}
```

**Comment by styfle** [comment]
Hi Denis,

"Invalid JWT Signature" sounds like an error from Google Auth, not Now.

Perhaps your token expired?
