### ISSUE TITLE
Saving Gatsby cache between builds

### ISSUE THREAD

**Issue by axelekwall** [vercel/vercel#3247]
I have a Gatsby site deployed with Now and I have noticed that it takes a long time to generate image thumbnails on every build. This could be improved by adding the `.cache` folder Gatsby generates to the cache that Now creates after each build. Is there a way to do this today? If not, are you planning on adding a way to do this manually or even automatically in the future?

**Comment by bardaxx** [comment]
follow!

**Comment by leo** [comment]
Thanks for the suggestion! We'll look into caching the directory by default.
