### ISSUE TITLE
now secrets are case insensitive

### ISSUE THREAD

**Issue by Kiel-H-Byrne** [vercel/vercel#3248]
when trying to use `now secret add REACT_APP_API_KEY s0mearbitraryKeyId` 
i don't get the same case sensitivity when listing with `now secrets list`

when trying to rename the lowercase `react_app_api_key` to uppercase, it says the key exists already for this user. 

is there any way to keep the case sensitivity of variables? Obviously not a dealbreaker, just a minor inconvenience if i can't call my env variables as `ALL_CAPS_SNAKECASE` in my app

**Comment by darknoon** [comment]
you can call your env variables ALL_UPPER_CASE, but your secrets are @lower_case.

when you alias them in now.json, it then is clear which is which:
```
  "env": {
    "ENV_ACCESS_KEY_ID": "@secret_access_key_id",
  },

```

**Comment by Kiel-H-Byrne** [comment]
AHA! interesting so you actually answered another question I had; 
so this keeps them actually secret since i'm only referencing the alias to the `now secret` vs putting the raw key as a string in my `now.json` file. 

So then does my now app once deployed reference the UPPERCASE key as it lives in `now.json` ? awesome!
Thanks!

**Comment by Kiel-H-Byrne** [comment]
works like a charm! appreciate the info here.
