### ISSUE TITLE
Zeit world without now hosting service

### ISSUE THREAD

**Issue by renatorib** [vercel/vercel#325]
Hello, I have a doubt not directly (but indirectly) reated to now. It's about zeit.world. I haven't technical knowledge about DNS.

Can I use zeit world without zeit now hosting service?
*For example*, point my domain name to Github Pages using world DNS services? https://help.github.com/articles/quick-start-setting-up-a-custom-domain/

Thanks in advance.

**Comment by leo** [comment]
Not recommended, no! 😊
