### ISSUE TITLE
Documentation about usefulness of @now/node package

### ISSUE THREAD

**Issue by Vadorequest** [vercel/vercel#3253]
I have the @now/node package installed as devDependency but I don't know what it's supposed to do. Is it useful? https://www.npmjs.com/package/@now/node

I was confused about whether that package is the Now CLI for node, but it doesn't seem so. 
Regardless, could some README be added to the NPM package? 

Also, there is no changelog about that package and I don't know what's changed between 1.0.0 and the latest 1.0.2.

**Comment by styfle** [comment]
Hi @Vadorequest 

The only reason to use `@now/node` as a dev dependency is for typescript support.

It provides the types of request and response to make typescript happy.

```ts
import { NowRequest, NowResponse } from '@now/node'

export default (request: NowRequest, response: NowResponse) => {
  const { name = 'World' } = request.query
  response.status(200).send(`Hello ${name}!`)
}
```

If you don't use typescript, you don't need this dependency.

See the documentation here: https://zeit.co/docs/runtimes#official-runtimes/node-js/using-typescript-with-the-node-js-runtime

**Comment by Vadorequest** [comment]
Thanks! Could that be made obvious in the plugin doc? Indeed I use those typings.

**Comment by styfle** [comment]
I'll update the home page so that npm links to the relevant documentation, thanks! #3265
