### ISSUE TITLE
@now/node Typescript 3.7

### ISSUE THREAD

**Issue by Zdend** [vercel/vercel#3258]
Now that the long expected Typescript 3.7 is out, can @now/node's typescript dependency be upgraded to the latest version?

Or perhaps, there is a way to specify the version of TS that is used in the project?

**Comment by styfle** [comment]
Hi @Zdend 

You can specify the version in package json.

Run `yarn add --dev typescript@3.7.2` or `npm i -D typescript@3.7.2`.

**Comment by Zdend** [comment]
Hi @styfle ,

I have tried that but with no luck. Maybe it's due to my folder structure which is following

```
├───backend
│   ├───package.json
│   ├───tsconfig.json
├───frontend
│   ├───package.json
│   ├───tsconfig.json
├───now.json
```

```
{
  "version": 2,
  "builds": [
    {
      "src": "frontend/next.config.js",
      "use": "@now/next"
    },
    {
      "src": "backend/src/index.ts",
      "use": "@now/node",
      "config": { 
        "maxLambdaSize": "20mb",
        "includeFiles": [
          "backend/src/schema.graphql"
        ]
      }
    }
  ]
}
```

I have tried to hoist tsconfig.json to the root level and install typescript@3.7.2 there as well but the build runtime still shows me that it uses internal version
```Using TypeScript 3.5.2 (now internal)```

Interestingly enough, @now/next that compiles frontend doesn't have the same problem, although it might be due to the custom .babelrc that contains plugins to compile optional chaining rather than letting typescript do so.

Thanks

**Comment by dan-turner** [comment]
You will need a `package.json` at the root level (next to the `now.json`) containing Typescript 3.7.

**EDIT**

The below problem was caused by me having `target: esnext` in my tsconfig which basically says don't transpile newer language features.  Changing it to `ES2018` all is well!

> That will get you a little further, but if like me you were hoping to leverage optional chaining, you will be disappointed for now :(
> 
> ```
> › yarn dev
> yarn run v1.17.3
> $ now dev
> > Now CLI 16.4.4 dev (beta) — https://zeit.co/feedback/dev
> > Creating initial build
> > Using external babel configuration
> > Location: "<snipped>/now/web/.babelrc"
> [ info ]  bundled successfully, waiting for typecheck results...
> [ wait ]  compiling ...
> > Success! Build completed
> [ info ]  bundled successfully, waiting for typecheck results...
> > Ready! Available at http://localhost:3000
> [ event ] build page: /next/dist/pages/_error
> [ wait ]  compiling ...
> [ info ]  bundled successfully, waiting for typecheck results...
> [ ready ] compiled successfully
> > Building @now/node:api/src/routes/auth/login/index.ts
> Installing dependencies...
> Using TypeScript 3.7.2 (local user-provided)
> > Built @now/node:api/src/routes/auth/login/index.ts [4s]
> /private/var/folders/m6/1fn9pd3x6j568fffgksl71jr0000gn/T/zeit-fun-ca509de1e78d2/api/src/koa.js:24
>         domain: config_1.default.auth0?.tennant,
>                                        ^
> 
> SyntaxError: Unexpected token .
>     at Module._compile (internal/modules/cjs/loader.js:723:23)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
>     at Module.load (internal/modules/cjs/loader.js:653:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
>     at Module.require (internal/modules/cjs/loader.js:692:17)
>     at require (internal/modules/cjs/helpers.js:25:18)
>     at Object.<anonymous> (<snipped>/now/api/src/routes/auth/login/index.ts:2:1)
>     at Module._compile (internal/modules/cjs/loader.js:778:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
> LambdaError: RequestId: 1af5da18-3041-4c1d-a287-41004d362bfa Process exited before completing request
>     at Lambda.<anonymous> (<snipped>/now/node_modules/now/dist/index.js:2:3106637)
>     at Generator.next (<anonymous>)
>     at fulfilled (<snipped>/now/node_modules/now/dist/index.js:2:3104508)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> ```
> 
> I have also tried `@now/node@canary` and still no luck.

**Comment by Zdend** [comment]
Hey @dan-turner, 
I'm glad that it solved it for you! I tried the same thing both having typescript in the root package.json and having proper target version in the tsconfig. When I run `now dev` it actually picks up the right version of typescript! 
However when I deploy to prod (`now deploy -f`), it picks up the old version. There seem to be differences in typescript resolution between dev and prod - at least with my setup.

**Comment by styfle** [comment]
This has been fixed in the canary channel.

You can try it out with `npm i -g now@canary`, thanks!

**Comment by Zdend** [comment]
Awesome, confirming it works! Thank you

**Comment by flybayer** [comment]
For anyone else who still runs into this problem, make sure `tsconfig.json` isn't ignored by `.nowignore` like it was for me.

**Comment by tsujp** [comment]
This isn't working for me including all attempted solves here.

**Comment by glennreyes** [comment]
I just ran into the same problem, following steps helped me solving this:

1. `yarn add --dev typescript`
2. Create a `tsconfig.json`:

```json
{
  "compilerOptions": {
    "target": "ES2018"
  }
}
```

Hope this will help others! cc @tsujp

**Comment by dborstelmann** [comment]
None of these solve it for me.  I have a structure like this:

api/index.ts (graphql server)
web/ (react frontend)

Graphql server won't run when using anything from 3.7 and above.  Frontend works fine because there is a build step

Now.json: 
```
{
  "version": 2,
  "env": {
    "DATABASE_URL": "@database_url",
    "NODE_ENV": "production"
  },
  "build": {
    "env": {
      "DATABASE_URL": "@database_url",
      "NODE_ENV": "production"
    }
  },
  "builds": [
    { "src": "api/index.ts", "use": "@now/node@canary" },
    {
      "src": "web/package.json",
      "use": "@now/static-build",
      "config": {
        "distDir": "build"
      }
    }
  ],
  "routes": [
    { "src": "/api", "dest": "api/index.ts" },
    { "src": "^/static/(.*)", "dest": "web/static/$1" },
    { "src": "/(.*)", "dest": "web/index.html" }
  ]
}

```
