### ISSUE TITLE
How to debug deployment?

### ISSUE THREAD

**Issue by lematt1991** [vercel/vercel#326]
I'm deploying an application with Docker.  I've had a couple successful deploys, but now all of the sudden, I'm getting a cryptic "502: An error occured with your deployment." error.  Is there anyway to debug this?  I'm not sure what's causing this error, but the docker container works perfectly fine on my local machine.  I'm relatively new to `now` and I've been burning through my 20 deploys very quickly with these failures.  Any help would be much appreciated.

**Comment by hugomd** [comment]
This is an error with deployments on Zeit's end, you'll have to wait for the team to fix it, I'm afraid.

**Comment by mohammad-rahchamani** [comment]
Same here.
I was trying to deploy a very simple express project to see how "now" works. I'm getting 'Deployment complete!' message from now-cli but when I visit the url for my project, it says '502: An error occured with your deployment'.

**Comment by lematt1991** [comment]
This seems like a pretty serious bug.  Any ETA on a fix?

**Comment by gwendall** [comment]
Same here

**Comment by leo** [comment]
This shouldn't occur anymore. You can use [this](https://logs.now.sh) for getting the logs of your deployment and try to debug it with them.

If something like this still occurs in the future, please let us know at support@zeit.co! 😊

**Comment by lematt1991** [comment]
`now-logs` is great for debugging a running application.  The problem that we've been running into here is that `now` crashes before the app starts running, so logging in our application doesn't really help.  Instead. it would be good to get some additional logging info from `now` itself on the deployment.

**Comment by leo** [comment]
@ml9951 We're already working on a better solution for this... :blush: 🔜 

(sorry, forgot to mention)

**Comment by MaksimKlepikov** [comment]
Same here. Deploy logs is nice.

> 502 An error occured with your deployment.

https://hateit-qhjbpafwap.now.sh

**Comment by tejasmanohar** [comment]
I also think some sort of `docker logs` proxy (like Heroku's `heroku logs`) would be excellent. Not all of use Node, too 😄

**Comment by Bnjmn83** [comment]
Well, it just happened to me. Dockerfile builds on hub, locally and on codefresh without any issues. 
"502
An error occured with your deployment."
Any idea?

**Comment by lematt1991** [comment]
For me it turned out to be a really dumb mistake.  I forgot to `EXPOSE` a port in my Dockerfile.  It ended up starting up, failing to bind to a port, and restart.  After restarting `x` number of times, it failed and gave a 502.
