### ISSUE TITLE
Zeit 404 in Runtime log but 200 returned to browser.

### ISSUE THREAD

**Issue by hutber** [vercel/vercel#3262]
I am experiencing very odd behavior in as much that it does not make sense, nor can I find it looking through issues/stackoverflow etc. 

- I am using version 2
- I have no `now.json` file
- In the log, I get a 404, but the page returns a 200 and renders correctly.
- The page on initial page load does **not** show any error in the build log. Nor using navigation to move around the app.

``` bash
2019-11-07T14:36:18.288Z 
     INFO
        {
          error: {
             message: "Page not found",
             slug: "charts",
             statusCode: 404,
          }
       }
Duration: 1153.35 ms Billed Duration: 1200 ms Memory Size: 3008 MB Max Memory Used: 140 MB
```

However the page's headers returns a `200`

![image](https://user-images.githubusercontent.com/1344898/68402937-0e8a4c00-0174-11ea-91f7-21a28d11b8f3.png)

# Next.config.js

```javascript
const webpack = require('webpack')
const withCSS = require('@zeit/next-css')

module.exports = withCSS({
  target: 'serverless',
  webpack: (config, {}) => {
    const originalEntry = config.entry
    config.entry = async () => {
      const entries = await originalEntry()
      if (entries['main.js'] && !entries['main.js'].includes('./polyfills.js')) {
        entries['main.js'].unshift('./polyfills.js')
      }
      return entries
    }
    return config
  },
  env: { env: process.env.NODE_ENV },
})

```

Its worth noting I believe that it made little difference if I included the `now.json` or not, but here is my `now.json`

```json
{
  "version": 2,
  "builds": [
    { "src": "next.config.js", "use": "@now/next" }
  ],
  "routes": [
    {"src": "/index", "dest": "/" },
    {"src": "/charts", "dest": "/charts" }
  ]
}
```

**Comment by mcsdevv** [comment]
Hey @hutber, apologies for the delayed response here - are you still experiencing this issue?
