### ISSUE TITLE
Question: Is there a way to change now dev to use start instead of build command?

### ISSUE THREAD

**Issue by BrunoQuaresma** [vercel/vercel#3269]
I'm using create-react-app and when I tried to use `now dev` it is using the default build command. Is there a way to change it to use the start command with the development server instead of doing production builds on each change?

Thanks.

**Comment by styfle** [comment]
Hi Bruno,

You can add a `dev` script to `package.json` which will be used with `now dev` instead of the `build` script.

https://zeit.co/docs/v2/serverless-functions/introduction#local-development

**Comment by BrunoQuaresma** [comment]
Thanks @styfle. After rename the `start` command to `dev` I had to add `BROWSER=none`. Final version: `"dev": "BROWSER=none react-scripts start"`
