### ISSUE TITLE
iOS browsers (Chrome & Safari) "This site can’t be reached"

### ISSUE THREAD

**Issue by dallen4** [vercel/vercel#3270]
After deploying and configuring subdomains for a domain via CNAMEs, iOS devices appear to be rendering a "This site can't be reached" (Chrome v78.0.3904.84) or nothing at all and clearing the URL text input field (Safari). These web applications operate perfectly fine on `*.now.sh` subdomains, but when we try to access on our custom domain, we run into these issues.

This happened pretty suddenly after we got pretty deep into development and were deploying regularly. It happened on my iPhone (Xr iOS 13.1.3) and thought it was a caching issue isolated to my device, but since then has occurred on another device as well which indicates to me it could be an issue as we move into future release cycles and on-board more users. _No other devices are affected thus far._

We run different local configurations to allow us to dynamically configure our deployments based off of different environment variables. This approach was based off of [a comment](https://github.com/zeit/now/issues/2452#issuecomment-505098132) on issue #2452. We use different `now.*.json` configurations to implement different environment variables. An example of one of these (specifics ommited) is below:

```
{
    "name": "auth-bouncer",
    "version": 2,
    "env": {
        ...
    },
    "build": {
        "env": {
            ...
        }
    },
    "builds": [
        {
            "src": "package.json",
            "use": "@now/next",
            "config": { "maxLambdaSize": "10mb" }
        }
    ],
    "routes": [
        {
            "src": "/static/.+",
            "headers": { "cache-control": "maxage=604800" }
        }
    ]
}
```

I was originally only configuring the `env` within `builds` but realized that could be causing issues so I copied necessary variables over to the root `env` in the config. This had no affect upon re-deployment. 

When I view site info in my iPhone's browser, it mentions certificate validation and says the site cannot be trusted. I'm wondering if this is because I configured subdomains with CNAME records as opposed to NS records or there is something wrong with my configuration. 

For context, here is my `package.json` structure (these deployments are done via `yarn run deploy:prod`:

```
{
    "name": "**",
    "version": "1.0.0",
    "scripts": {
        "start": "now dev --local-config now.development.json",
        "build": "next build",
        "now-build": "next build",
        "deploy:test": "now --local-config now.testing.json --target staging",
        "deploy:prod": "now --prod --local-config now.production.json"
    },
    "license": "UNLICENSED",
    "dependencies": {
        ...
    },
    "devDependencies": {
        ...
    },
    "engines": {
        "node": "10.x"
    }
}

```

I saw in the [legacy documentation](https://github.com/zeit/now-builders/blob/master/errors/now-next-legacy-mode.md) that you are supposed to have `now-build` configured as a script so I tried adding that as well, to no avail. 

For further context, here is my `next.config.js`:
```
const withCSS = require('@zeit/next-css');

const env = {
    ... // assign env vars from now values
};

module.exports = withCSS({
    target: 'serverless',
    env,
});

```

To clarify, I have tried:
- clearing browser caches,
- disconnecting and re-connecting subdomains for the project(s) (this issue is across three apps using different subdomains on same root domain),
- updating `now` CLI versions,
- add `now-build` in addition to `build` scripts to `package.json`,
- checking to make sure now reserved env vars were being implemented, 
- and have just recently tried going to NS route for DNS configuration as I mentioned was a concern above. 

Any help, guidance, or advice would be appreciated. I'm not sure why its only happening on iOS devices, but after seeing the info on the domain cert in my Chrome browser, I'm more confident it has to do with DNS configuration than deployment mishaps.

**Comment by paulogdm** [comment]
This is being handled in the support email.

For future readers: This repository is aimed for library issues and you should email support@zeit.co for any formal assistance.

**Comment by fgeierst** [comment]
I recently (2019-12-13) run into a similar problem. "This site can't be reached" on macOS, while it worked as excpected on iOS, Win and Android devices. 

Could you post more details here?

**Comment by dallen4** [comment]
@fgeierst what browser(s) are you experiencing this on? Are you using an libraries that use local browser storage (local storage, cookies, etc.)?

**Comment by fgeierst** [comment]
@dallen4 It's using only a single library (VanillaQR.js), no local storage, no cookies.

![Download](https://user-images.githubusercontent.com/22551442/71076426-fbf92e80-2185-11ea-8675-e45715e49373.png)

**Comment by procarrera** [comment]
Hi guys

i have some projects hosted at Zeit/Vercel and i realized none of them is opening property in Safari/MacOS due to "bad secure connection", just like this image above.

Would you have any solution for this?

https://esther-bonder.vercel.app
https://share-me.now.sh
https://flordecaramelogourmet.com.br/

**Comment by AgainstLightning** [comment]
Did this ever get handled? I cannot access apps from vercel on my iphone?
