### ISSUE TITLE
Deployments should be served over http/2 instead of http/1.1

### ISSUE THREAD

**Issue by NateRadebaugh** [vercel/vercel#3272]
When running chrome audit on my site, the best I can get is 93 for "Best Practices" since the site is being served over http/1.1 instead of http/2.

![image](https://user-images.githubusercontent.com/130445/68477134-3b7d4400-01f2-11ea-9003-d88f5107f42c.png)

Is there some setting I'm missing? These deployments are automatic via Github.

My `now.json` config:
```json
{
  "version": 2,
  "name": "xxx",
  "alias": "xxx.now.sh",
  "builds": [{ "src": "package.json", "use": "@now/next" }],

  "routes": [
    {
      "src": "^/service-worker.js$",
      "dest": "/_next/static/service-worker.js",
      "headers": {
        "cache-control": "public, max-age=43200, immutable",
        "Service-Worker-Allowed": "/"
      }
    }
  ]
}
```

**Comment by NateRadebaugh** [comment]
Note: I am using nextjs for this site. Is http/2 not supported out of the box for nextjs?

This is the only example I see on that repo, but I'd like to avoid using a custom server.
https://github.com/zeit/next.js/tree/canary/examples/with-http2

**Comment by styfle** [comment]
Hi Nate,

All requests served from Now use HTTP/2.

Perhaps your service worker is serving the HTTP/1.1 requests?

Can you share the deployment URL that you are testing? Thanks!

**Comment by NateRadebaugh** [comment]
The plot thickens. Here's the example I'm using for the next-offline: https://github.com/zeit/next.js/tree/canary/examples/with-next-offline

Here's my repo:
https://github.com/NateRadebaugh/nateradebaugh.github.com/blob/master/next.config.js

https://naterad.com

**Comment by styfle** [comment]
Using chrome dev tools, you can see that the h1 responses are from your service worker.

The h2 responses are from Now.

![image](https://user-images.githubusercontent.com/229881/68596111-b0f24a00-0468-11ea-9833-1da28a4d6742.png)

**Comment by NateRadebaugh** [comment]
Cool thanks, I'll close this and investigate with the next-offline plugin to see how to properly configure the service worker for http2.
