### ISSUE TITLE
Now dev doesn't install all packages I specified in package.json

### ISSUE THREAD

**Issue by ThewBear** [vercel/vercel#3280]
I am getting core-js module not found error when using zero-config now/node api. I already have specified it in package.json. But the `zeit-fun-hash/node_modules` directory doesn't have it.

The core-js module is required by `@vue/cli-plugin-babel/preset` in project root babel.config.js

**Comment by ThewBear** [comment]
After digging, I found that core-js and other packages that aren't explicitly required in source code are filtered out by `@zeit/node-file-trace`
https://github.com/zeit/now/blob/147c703cce4c0102d70cd8ecc884e36baef9e07a/packages/now-node/src/index.ts#L164

And the `core-js` is added by Babel
https://github.com/zeit/now/blob/147c703cce4c0102d70cd8ecc884e36baef9e07a/packages/now-node/src/index.ts#L258

So my proposed solution is to make this babel compilation ignores project's root `babel.config.js` as it already ignores `.babelrc`

https://github.com/zeit/now/blob/147c703cce4c0102d70cd8ecc884e36baef9e07a/packages/now-node/src/babel.ts#L10

So current `@now/node` shouldn't read `babel.config.js` as it will cause problems with `@zeit/node-file-trace`. See https://github.com/zeit/now/issues/2851#issuecomment-525438982

**Comment by styfle** [comment]
Nice find! We only use babel to transform ESM import/export to CJS require statements so it sounds like it would be best to disable reading any configuration from the user. I also commented on your PR 👍

**Comment by styfle** [comment]
Hi Thew,

The fix has been shipped to the canary channel. Can you confirm this fixes the issue?

Thanks!

**Comment by ThewBear** [comment]
I confirm that this issue is fixed in `now@16.5.3-canary.0`. 🎉
