### ISSUE TITLE
Now dev not serving vue js/css from `/dist`

### ISSUE THREAD

**Issue by ThewBear** [vercel/vercel#3282]
I'm using vue-cli with zero-config which build to `/dist` directory. When I run `now dev`, the dev server serve all js/css files with `/index.html`.

```cmd
> GET /
> Using cached `now.json` config
> Checking build result's 4 `routes` to match /
> Serving asset: [FileFsRef] index.html
> GET /css/chunk-vendors.1e8b74d7.css
> Using cached `now.json` config
> GET /js/app.b56d3369.js
> Using cached `now.json` config
> GET /js/chunk-vendors.47769027.js
> Using cached `now.json` config
> Checking build result's 4 `routes` to match /js/chunk-vendors.47769027.js
> Found matching route /index.html for /js/chunk-vendors.47769027.js
> Checking build result's 4 `routes` to match /css/chunk-vendors.1e8b74d7.css
> Found matching route /index.html for /css/chunk-vendors.1e8b74d7.css
> Checking build result's 4 `routes` to match /js/app.b56d3369.js
> Found matching route /index.html for /js/app.b56d3369.js
> Checking build result's 4 `routes` to match /index.html
> Serving asset: [FileFsRef] index.html
> Checking build result's 4 `routes` to match /index.html
> Serving asset: [FileFsRef] index.html
> Checking build result's 4 `routes` to match /index.html
> Serving asset: [FileFsRef] index.html
> GET /favicon.ico
> Using cached `now.json` config
> Checking build result's 4 `routes` to match /favicon.ico
> Serving asset: [FileFsRef] favicon.ico
```

Expected behavior: handle `filesystem` correctly from `/dist`

I don't want to use `dev` in package.json as it will start another dev server.

**Comment by styfle** [comment]
Can you provide steps to reproduce? In particular, what does your package.json file look like?

If you have a `@vue/cli-service` dependency, it should prefer the filesystem over the index.html catch-all route.

https://github.com/zeit/now/blob/c9572c352aff7f63aac26f510297358d466aeaba/packages/now-static-build/src/frameworks.ts#L100

**Comment by ThewBear** [comment]
My package.json already has `@vue/cli-service`.

OS: Windows 10

### Steps to reproduce:
1. Create project by `npx @vue/cli create hello-world` using `default (babel, eslint)`
1. `cd hello-world`
1. `now dev`
1. Visit `localhost:3000` and inspect all assets which are served by content of dist/index.html

**Comment by styfle** [comment]
Thanks for the repro steps!

I tried with macOS using `now@16.5.0` and it seems to work fine.

```
> Ready! Available at http://localhost:3000
> [debug] [2019-11-12T20:55:25.639Z] GET /
> [debug] [2019-11-12T20:55:25.684Z] Checking build result's 4 `routes` to match /
> [debug] [2019-11-12T20:55:25.686Z] Serving asset: [FileFsRef] index.html
> [debug] [2019-11-12T20:55:25.906Z] GET /css/app.e2713bb0.css
> [debug] [2019-11-12T20:55:25.908Z] Checking build result's 4 `routes` to match /css/app.e2713bb0.css
> [debug] [2019-11-12T20:55:25.909Z] Serving asset: [FileFsRef] css/app.e2713bb0.css
> [debug] [2019-11-12T20:55:25.913Z] GET /js/app.fa39d2bc.js
> [debug] [2019-11-12T20:55:25.914Z] GET /js/chunk-vendors.763c0f03.js
> [debug] [2019-11-12T20:55:25.918Z] Checking build result's 4 `routes` to match /js/app.fa39d2bc.js
> [debug] [2019-11-12T20:55:25.920Z] Serving asset: [FileFsRef] js/app.fa39d2bc.js
> [debug] [2019-11-12T20:55:25.921Z] Checking build result's 4 `routes` to match /js/chunk-vendors.763c0f03.js
> [debug] [2019-11-12T20:55:25.922Z] Serving asset: [FileFsRef] js/chunk-vendors.763c0f03.js
> [debug] [2019-11-12T20:55:26.123Z] GET /img/logo.82b9c7a5.png
> [debug] [2019-11-12T20:55:26.124Z] Checking build result's 4 `routes` to match /img/logo.82b9c7a5.png
> [debug] [2019-11-12T20:55:26.125Z] Serving asset: [FileFsRef] img/logo.82b9c7a5.png
```

This bug is likely affecting Windows only.

**Comment by ThewBear** [comment]
I think the bug is in how `now dev` handle a `filesystem` route but I don't have time to find out.

**Comment by ThewBear** [comment]
I found that `now-build-utils` has `entrypoint` modification for windows compatibility
https://github.com/zeit/now/blob/2a59db3029b811f1acfd17481c5b7bfca556bd3b/packages/now-build-utils/src/should-serve.ts#L11

But `now dev` static-builder and server doesn't have it.
https://github.com/zeit/now/blob/2a59db3029b811f1acfd17481c5b7bfca556bd3b/packages/now-cli/src/util/dev/static-builder.ts#L15-L27

I'm not sure where should I fix this bug as it involves many functions in `util/dev/server.ts` and `util/dev/static-builder.ts`

**Comment by styfle** [comment]
I think you're onto something here.

Most builders/runtimes export `shouldServe()` however, `@now/static-build` does not 🤔 

@TooTallNate Is this a miss or was this intentionally left out?

**Comment by ThewBear** [comment]
This issue is resolved with `now dev` 17 since it automatically uses `vue-cli-service serve --port $PORT`.
