### ISSUE TITLE
[now-client] Missing dist files

### ISSUE THREAD

**Issue by PierreAndreis** [vercel/vercel#3310]
The published version of `now-client` is missing its distribution files. It started happening after 5.2.1 update.
https://unpkg.com/now-client@5.2.1
https://unpkg.com/now-client@5.2.2
https://unpkg.com/now-client@5.2.3

**Comment by styfle** [comment]
This is strange indeed.

Most of the packages in this monorepo use the `files` key to publish their dist directory and nothing else.

https://github.com/zeit/now/blob/8e293dd633ed249f969417cf137abd17ae7653ed/packages/now-client/package.json#L8

Perhaps there is a bug in npm 🤔

**Comment by styfle** [comment]
This has been fixed in `now-client@canary`, thanks!

https://unpkg.com/browse/now-client@5.2.4-canary.1/dist/
