### ISSUE TITLE
Now Deployment Error

### ISSUE THREAD

**Issue by koficypher** [vercel/vercel#3314]
Node - 10.15.3
Npm - 6.13.0
Now version - 16.5.2

I have a mono repo app with svelte and @now/node backend in the api folder. Development with now dev works fine but deploying with now doesnt and the deplyment fails.
Here are what the logs says....
```bash
 

03:09:36 PM | Installing build runtime...
-- | --
03:09:37 PM | Build runtime installed: 922.221ms
03:09:38 PM | Installing build runtime...
03:09:38 PM | Looking up build cache...
03:09:39 PM | Build cache found [10.53 MB, 11610 files]
03:09:39 PM | Build cache unpacked: 736.131ms
03:09:39 PM | Build runtime installed: 835.653ms
03:09:39 PM | Installing dependencies...
03:09:39 PM | Installing build runtime...
03:09:39 PM | Looking up build cache...
03:09:40 PM | Build cache found [10.53 MB, 11610 files]
03:09:40 PM | Build cache unpacked: 884.162ms
03:09:40 PM | Build runtime installed: 1065.469ms
03:09:41 PM | Installing build runtime...
03:09:41 PM | Installing dependencies...
03:09:41 PM | Looking up build cache...
03:09:42 PM | Build cache found [10.53 MB, 11565 files]
03:09:42 PM | Build cache unpacked: 890.959ms
03:09:42 PM | Build runtime installed: 1082.285ms
03:09:43 PM | Installing build runtime...
03:09:43 PM | Installing dependencies...
03:09:43 PM | Looking up build cache...
03:09:44 PM | Build runtime installed: 1039.344ms
03:09:44 PM | npm ERR! path /zeit/304efe5c/node_modules/sequelize
03:09:44 PM | npm ERR! code EISGIT
03:09:44 PM | npm ERR! git /zeit/304efe5c/node_modules/sequelize: Appears to be a git repo or submodule.
03:09:44 PM | npm ERR! git     /zeit/304efe5c/node_modules/sequelize
03:09:44 PM | npm ERR! git Refusing to remove it. Update manually,
03:09:44 PM | npm ERR! git or move it out of the way first.
```
Ideally if am able to locate the /zeit folder in question, i will be able to remove all the sub git folders. Where is it located ?

**Comment by styfle** [comment]
Hi Kofi,

This looks like a bug with `sequelize` according to https://github.com/sequelize/sequelize/issues/11143

Can you try updating that dependency? `npm i sequelize@latest`

**Comment by koficypher** [comment]
@styfle Thanks for the response. However doing that still give me the same error 
```bash

Installing build runtime...
--
03:48:52 PM | Build runtime installed: 1129.107ms
03:48:52 PM | Looking up build cache...
03:48:53 PM | Installing build runtime...
03:48:53 PM | Build cache found [10.70 MB, 11780 files]
03:48:53 PM | Build cache unpacked: 755.945ms
03:48:54 PM | Installing dependencies...
03:48:58 PM | npm ERR! path /zeit/775ed094/node_modules/sequelize
03:48:58 PM | npm ERR! code EISGIT
03:48:58 PM | npm ERR! git /zeit/775ed094/node_modules/sequelize: Appears to be a git repo or submodule.
03:48:58 PM | npm ERR! git     /zeit/775ed094/node_modules/sequelize
03:48:58 PM | npm ERR! git Refusing to remove it. Update manually,
03:48:58 PM | npm ERR! git or move it out of the way first.
03:48:58 PM | npm ERR! A complete log of this run can be found in:
03:48:58 PM | npm ERR!     /zeit/.npm/_logs/2019-11-14T15_48_58_817Z-debug.log
03:48:58 PM | Error: Exited with 1
03:48:58 PM | at ChildProcess.child.on (/zeit/9ad14beef95a56a0/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:23760:24)
03:48:58 PM | at emitTwo (events.js:126:13)
03:48:58 PM | at ChildProcess.emit (events.js:214:7)
03:48:58 PM | at maybeClose (internal/child_process.js:925:16)
03:48:58 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
03:48:58 PM | worker exited with code 20 and signal null


```

**Comment by styfle** [comment]
Can you post the contents of `package.json`?

**Comment by koficypher** [comment]
@styfle sure
```bash
{
  "name": "svelte-app",
  "version": "1.0.0",
  "devDependencies": {
    "rollup": "^1.12.0",
    "rollup-plugin-commonjs": "^10.0.0",
    "rollup-plugin-livereload": "^1.0.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-svelte": "^5.0.3",
    "rollup-plugin-terser": "^5.1.2",
    "svelte": "^3.0.0"
  },
  "dependencies": {
    "@beyonk/svelte-notifications": "^2.0.3",
    "bulma": "^0.8.0",
    "node-sass": "^4.13.0",
    "pg": "^7.12.1",
    "pg-hstore": "^2.3.3",
    "rollup-plugin-postcss": "^2.0.3",
    "sequelize": "4.44.2",
    "sequelize-cli": "^5.5.1",
    "sirv-cli": "^0.4.4"
  },
  "scripts": {
    "build": "rollup -c",
    "dev": "rollup -c -w",
    "start": "sirv public --single",
    "start:dev": "sirv public --single --dev"
  }
}

```

**Comment by styfle** [comment]
That looks correct 🤔 

You could try to delete `node_modules` and `package-lock.json` and then run `npm install` again to regenerate the lock file.

If that doesn't work, there is an even newer version of sequelize 4.44.3 you could try.

**Comment by koficypher** [comment]
Okay @styfle will try that and see.

**Comment by koficypher** [comment]
> That looks correct 🤔
> 
> You could try to delete `node_modules` and `package-lock.json` and then run `npm install` again to regenerate the lock file.
> 
> If that doesn't work, there is an even newer version of sequelize 4.44.3 you could try.

Still the same error result. Error still persist for higher versions of Sequelize like 5. I feel its the way the dependencies are being pulled in or perhaps there's a build cache where zeit is pulling sequelize  and the other dependencies from.

**Comment by styfle** [comment]
You're right, there is a build cache for the `node_modules` directory.

You can skip the cache by using the `now --force` flag or renaming your project.

**Comment by koficypher** [comment]
@styfle Yes it worked!!. But one small problem my lamda functions are not working or perhaps i need to reference them fully now ?

> You're right, there is a build cache for the `node_modules` directory.
> 
> You can skip the cache by using the `now --force` flag or renaming your project.

**Comment by styfle** [comment]
Are your lambda functions in the `/api` folder? What is not working?

**Comment by koficypher** [comment]
@styfle yes they are. My svelte app cant access them but when i use the zeit dashboard to invoke the lamdas i get the response in the browser correctly

**Comment by styfle** [comment]
If it works when visiting the function url directly `/api/users` for example, then it sounds like your fetch/xhr URL is incorrect. If you open up chrome dev tools, and visit the network tab you'll see the request urls.

**Comment by koficypher** [comment]
@styfle i cant even view it directly in the browser unless i view source and invoke the lambda on the zeit dashboard. When i view chrome dev tools i see the 404 response being returned on fetch invocation. preview the response further i see 
```bash
 The page could not be found.

RESOURCE_NOT_FOUND
```

**Comment by styfle** [comment]
> unless i view source and invoke the lambda on the zeit dashboard

What does this mean? Can you provide the URL your are invoking?

**Comment by koficypher** [comment]
> > unless i view source and invoke the lambda on the zeit dashboard
> 
> What does this mean? Can you provide the URL your are invoking?

This is the url https://dekspoll-8yprknzt7.now.sh/
You can try and access it and click on any of the buttons and inspect the page via dev tools  in chrome to see the error.

**Comment by koficypher** [comment]
@styfle At this point i feel my now.json file is the culprit. Please have a look
```javascript
{
    "version": 2,
    "builds": [
        {"src": "api/*.js", "use": "@now/node"},
        {"src": "package.json", "use": "@now/static-build"}
    ],
    "routes" : [
        {"src": "api/","dest":"api/controllers/index.js"},
        {"src": "api/positions","dest":"api/positions.js"},
        {"src": "api/candidates","dest":"api/candidates.js"},
        {"src": "api/vote", "dest":"api/save-vote.js"},
        {"src": "api/results", "dest":"api/get-polls.js"}
    ],
    "env": {
        "db_host": "@db_host",
        "db_port": "@db_port",
        "db_user": "@db_user",
        "db_pass": "@db_pass",
        "db_data": "@db_data"
    }
}
```

**Comment by styfle** [comment]
I don't see a `/api/results` there defined.

I think you should remove the `builds` key and simplify your routes:

```json
{
    "version": 2,
    "routes" : [
        {"src": "api/","dest":"api/controllers/index.js"},
        {"src": "api/vote", "dest":"api/save-vote.js"},
        {"src": "api/results", "dest":"api/get-polls.js"}
    ],
    "env": {
        "db_host": "@db_host",
        "db_port": "@db_port",
        "db_user": "@db_user",
        "db_pass": "@db_pass",
        "db_data": "@db_data"
    }
}
```

You could even rename those files so that you have `/api/index.js`, `/api/vote.js`, `/api/results.js` and then you wouldn't need any routes at all.

**Comment by koficypher** [comment]
@styfle  Thanks soo much for your help. That worked as well.
