### ISSUE TITLE
Default Gatsby configuration provides no cache options

### ISSUE THREAD

**Issue by darkowic** [vercel/vercel#3331]
Hello!

I have just deployed a static gatsby page using your service and basically none of the static content is cached.
Video `mp4` cache: `cache-control: s-maxage=0`
images etc
```
cache-control: public, max-age=0, must-revalidate
```

I see this MR probably breaks it - https://github.com/zeit/now/pull/3212

I will use for now https://github.com/universse/gatsby-plugin-zeit-now

**Comment by cryptiklemur** [comment]
This happens for non-gatsby deploys too, eg: Next.

**Comment by styfle** [comment]
Thanks, we'll take a look 👍
