### ISSUE TITLE
Support for MJS files? 

### ISSUE THREAD

**Issue by swilgosz** [vercel/vercel#3337]
### Short Overview

It now does not support `mjs` files. 

When I tried to deploy the application with named imports, I got an error: 

> Can't import the named export 'TextSelection' from non EcmaScript module (only default export is available)

### More details to reproduce the problem.

The application I tried to deploy is a Nuxt.js application with a [tiptap](https://github.com/scrumpy/tiptap) WYSYWIG editor integrated.

When I tried to deploy that application, I got an error:

> ERROR in ./node_modules_dev/prosemirror-commands/dist/index.mjs 270:20-33 Can't import the named export 'TextSelection' from non EcmaScript module (only default export is available)

**Comment by markozxuu** [comment]
Hi @swilgosz ,  support will be implemented once the ECMAScript Module is stable on the node : )

**Comment by styfle** [comment]
Agreed with @MAPESO 

Also see my answer here: https://github.com/zeit/now/issues/2854#issuecomment-520053188

Upstream issue here: https://github.com/zeit/node-file-trace/issues/80

**Comment by swilgosz** [comment]
Thanks, should I close it then?

**Comment by styfle** [comment]
No, this issue is good because it will increase visibility 👍 

Surely someone else will have the same question 😄 

Thanks!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by swilgosz** [comment]
But this doesn't seem to be a feature request but rather a bug - as the projects/libraries using MJS files can't be built using zeit. Also, it seems we already have an upstream issue as mentioned above - should it be closed too?

When you look on the upstream issue, you definitely can see that this is more like a bug than a feature, as there is already a condition to recognize mjs files but it's not working properly.

**Comment by davedoesdev** [comment]
Are `.mjs` files supported? I'm getting an error.

Here's my `now.json`:

```javascript
{
  "version": 2,
  "builds": [{
    "src": "foo.mjs",
    "use": "@now/node"
  }],
  "routes": [
    { "src": "/", "dest": "/foo.mjs" }
  ]
}
```

Here's `foo.mjs`:

```
import micro from 'micro';
const { send } = micro;
export default (req, res) => {
    res.setHeader('Content-Type', 'text/plain');
    send(res, 200, 'hello');
}
```

I'm getting this error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /tmp/zeit-fun-c36d9923b17de/foo.mjs
    at Module.load (internal/modules/cjs/loader.js:991:11)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/tmp/zeit-fun-c36d9923b17de/___now_launcher.js:21:18)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19) {
  code: 'ERR_REQUIRE_ESM'
```

**Comment by davedoesdev** [comment]
Is the upstream issue https://github.com/zeit/node-file-trace/issues/80 ? It seems to have been closed as can't repro.

**Comment by slowdownitsfine** [comment]
Same issue here, I think zeit/node-file-trace#80 should be reopened or ES module usage should be looked at.
