### ISSUE TITLE
now dev, fails error when running Next.js

### ISSUE THREAD

**Issue by hallojoe** [vercel/vercel#3338]
OS: Windows 10 Pro
Node: v12.13.1

We can't get things to run on my Windows machine. We get the following error when running `yarn now dev`

It happens on existing projects, and on fresh installs as well.

Steps to reproduce:

```
npm init next-app my-next-project
```

then 

```
yarn now dev
``` 

Result:

```
$ yarn now dev
yarn run v1.19.1
$ C:\BitBucket\my-next-project\node_modules\.bin\now dev
> Now CLI 16.5.2 dev (beta) — https://zeit.co/feedback/dev
> Creating initial build
child_process.js:114
  p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Object._forkChild (child_process.js:114:5)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:328:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:49:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -4083,
  code: 'EBADF',
  syscall: 'uv_pipe_open'
}
Done in 5.53s.
```

**Comment by thebuilder** [comment]
To clarify a bit - it's failing on a clean Next.js project, built from `next-app`. We also tried to create the new project using `npx create-next-app`, seeing the samme error
Running `next dev` or `next build` works fine, but once it's piped through `@now/next` it fails.

* We've tried it on two different Windows machines, getting the same error.
* `now dev` works if we are just hosting a static dir using `@now/static` - haven't tried other builders.

**Comment by betimer** [comment]
Experience same error with my environment. But also notice:

`yarn dev` has the problem

`npm run dev` can work without that error

**Comment by bluelovers** [comment]
@betimer omg, it is real, what the stupid bug

**Comment by styfle** [comment]
The `vercel dev` command has been changed to use `process.execPath` mentioned in #3407.

Do you still have this issue with the latest version of Vercel CLI?

https://github.com/vercel/vercel/blob/0d4be3f5f223bbaf6602b8754127326d323b00ad/packages/now-cli/src/util/dev/builder.ts#L64
