### ISSUE TITLE
Use local package as Runtime

### ISSUE THREAD

**Issue by remorses** [vercel/vercel#3349]
I am buikding a custom runtime and i want to test it locally, 
i tried using something like this
```json

{
    "functions": {
        "api/mongoke.yml": {
            "runtime": "../"
        }
    }
}
```
But the package must contain a version and i can't provide a version to a local package,
How do you guys test your runtimes locally?

**Comment by remorses** [comment]
Got it working using `now.json`
```json
{
    "version": 2,
    "builds": [
        {
            "src": "api/mongoke.yml",
            "use": "file:/absolutePath"
        }
    ]
}
```
I still don't understand if configs with version 2 are newer or not, the documentation show the `functions` usage but tests use `builds`.
Is there a better way?

**Comment by styfle** [comment]
The `functions` property has deprecated the `builds` property.

If you are developing a [Custom Runtime](https://zeit.co/docs/runtimes#advanced-usage/community-runtimes), you can use the file syntax you have above for `now dev` however this won't work for `now` cloud deployments.

Typically, I'll run `npm pack` to get a tarball, then `now *.tgz` to upload the tarball and get a url, then I'll use that URL in `now.json`.

Also see the [DEVELOPING_A_RUNTIME.md](https://github.com/zeit/now/blob/master/DEVELOPING_A_RUNTIME.md) docs.

**Comment by remorses** [comment]
thank you, I will use npm pack and use the file path as package
