### ISSUE TITLE
Regex with a backslash in now.json results in an error

### ISSUE THREAD

**Issue by edkv** [vercel/vercel#3350]
On https://zeit.co/docs/configuration#routes/headers page the following example of regex is shown denoting a literal dot character: `{ "src": "/test/file\.json", "status": 404, "dest": "/404" }`.

I'm trying it in my `now.json`:
```
{
    "name": "my-project-name",
    "version": 2,
    "routes": [
        { "src": "/test/file\.json", "status": 404, "dest": "/404" }
    ]
}
```
This results in an error:
```
$ npx now build --prod
> Error! Couldn't parse JSON file /path/to/my/project/now.json
```
If I remove the backslash here `"/test/file\.json"`, it works.

**Comment by styfle** [comment]
You need two backslashes followed by a dot to match a literal dot.

This can be tested with `new RegExp("/test/file\\.json").test('/test/file.json')`

**Comment by edkv** [comment]
It works with two backslashes, thank you. But the docs at https://zeit.co/docs/configuration#routes/headers need to be updated.

**Comment by styfle** [comment]
Oh good point!

It was written as a double backslash but it renders as a single backlash.

<a href="https://raw.githubusercontent.com/zeit/docs/54d6b19db4a304b58a9dd103506c2de22a098b9b/components/references-mdx/configuration/routes/routes.mdx"><img src="https://user-images.githubusercontent.com/229881/69660536-8bf7fc80-104e-11ea-82d8-c316a96e008b.png" height=100 /></a>

I'll fix it 👍
