### ISSUE TITLE
Deploying serverless functions to several regions

### ISSUE THREAD

**Issue by TAnas0** [vercel/vercel#3357]
Hey Zeit team,
I have been having a blast working with your platform.

I have a few serverless functions developed on NodeJS that I am successfully deploying to Zeit.
I can see Zeit has a very wide support of regions and I wanted to leverage that. I configured my deployment to be on several regions, and it is working fine.
My deployment is still on the same unique URL and I have no idea how to explicitly call a version of my function from, let's say for example, Tokyo.

This matters for my functions since I would like to measure latencies and times of responses from different location, and was under the impression that Now CLI would give an endpoint for each region.

From the documentation in here https://zeit.co/docs/v2/network/regions-and-providers/ :
> Serverless functions will execute in the nearest Origin Region to the developer by default. The developer can choose which Origin Regions to deploy to by using --regions in the CLI or the regions key in the now.json file.

- Are serverless functions called depending on the nearest one to the caller? or nearest one to the developer (when he was deploying?)?
- Should I be wrapping/calling my serverless functions from other serverless functions located in the region I want the request to be treated?
- Or should I separate the project into several ones, one by each region, in order to get different endpoints?

I come from AWS and GCP, where a different endpoint is offered for each region. 
I am a bit confused and would appreciate any kind of clarification

**Comment by styfle** [comment]
Hi @TAnas0 

> Are serverless functions called depending on the nearest one to the caller? or nearest one to the developer (when he was deploying?)?

If your deployment does _not_ specify the [`regions`](https://zeit.co/docs/configuration#project/regions) property, then the function is deployed to the closest region to the geographical location of the deployment, or if using a Now for Git integration, SFO is used. Your closes region can be seen on [Smart CDN](https://zeit.co/smart-cdn) page. If the function sets the `Cache-Control` header, the cached response will be available in _all_ regions without any additional configuration.

Note that static files (not serverless functions) are always served from the CDN in all regions without any configuration.

The client making requests to the serverless function will automatically be routed to the closes region that the deployment was made available to (see my first paragraph).

> Or should I separate the project into several ones, one by each region, in order to get different endpoints?

If you need this granularity, then yes. I don't think you will need to do this however.

Does that answer your question?

**Comment by TAnas0** [comment]
Thank you for your answer @styfle 

In fact I do need that, because the latency tests mentioned above vary depending on their origins.
Basically what I am after is testing the responsiveness of a website from Tokyo, Europe and USA, then compare them.

Anyways, I have asked the same question on Zeit's [Spectrum chat](https://spectrum.chat/zeit/) and found another one under the title "How to create region aware deployments ?"

@paulogdm answered the following:

> This is really not the focus of our platform at all. I remain unconvinced that we shouldn't have a way to evoke a function in a given region.
You can do this:
> 1. Create a new project called myapp-sfo1
> 2. Assign a production domain sfo1.domain.com to this project
> 3. Use --regions to deploy to a single region

I will simply have 3 projects in my case, with 3 different subdomains.

Cheers
