### ISSUE TITLE
`now dev` does not work on Windows (/src/pages)

### ISSUE THREAD

**Issue by betimer** [vercel/vercel#3359]
`now dev` command does not work on Windows. 

Personally thinking, it should be related to the feature of support `/src/pages`

It does not build the pages properly.

The only fix is to `mklink` oot path for the /pages pointing to /src/pages

`mklink /D pages .\src\pages\`

**Comment by betimer** [comment]
It should be windows file path issue.
I am using node 12 and now 16.6.0

**Comment by styfle** [comment]
The `vercel dev` command has been changed to use `process.execPath` mentioned in #3407.

Do you still have this issue with the latest version of Vercel CLI?

https://github.com/vercel/vercel/blob/0d4be3f5f223bbaf6602b8754127326d323b00ad/packages/now-cli/src/util/dev/builder.ts#L64
