### ISSUE TITLE
Question for Included Environment Variables

### ISSUE THREAD

**Issue by VadymBoguslavsky** [vercel/vercel#3360]
How can i use it in now json? I need to see NOW_GITHUB_COMMIT_REF after deployment? I am using it now as
```
"build": { 
   "env": { 
       "TEST": `NOW_GITHUB_COMMIT_REF` 
     } 
}
```
but it`s not working. What is the right way to do it?
I need it in my project to see branch after deployed to now.
Any help appreciated !

**Comment by styfle** [comment]
Hi @VadymBoguslavsky 

The `NOW_GITHUB_COMMIT_REF` is an environment variable that can be accessed in your code. You don't need to add any configuration to `now.json`.

Environment variables can be read using your serverless function language of choice.

For example, Node.js can use `var test = process.env.NOW_GITHUB_COMMIT_REF`. 

https://nodejs.org/dist/latest-v12.x/docs/api/process.html#process_process_env

**Comment by VadymBoguslavsky** [comment]
@styfle Sorry but i`ve tried this already, i am trying to let bugsnag know from which branch errors coming  and in my code for test i wanted to show branch name so i did it like 
```<h1>{process.env.NOW_GITHUB_COMMIT_REF}</h1>``` 
and the same in console.
But after deploy to now its empty, so it seems that we do not have this NOW_GITHUB_COMMIT_REF

**Comment by styfle** [comment]
@VadymBoguslavsky I tested this just now and it worked https://github.com/styfle/packagephobia/pull/472

The `NOW_GITHUB_` environment variables are only visible if your deployment was automatically deployed with the GitHub integration. https://zeit.co/docs/v2/more/now-for-github

**Comment by VadymBoguslavsky** [comment]
@styfle ,  thank you, but it seems that its missing elsewhere, i try to do the same but all i can see is 'Env Vars', after page reloading for a second they appear and then hide away again

**Comment by styfle** [comment]
@VadymBoguslavsky It sounds like you are using a framework that is doing SSR and then CSR in which the server has the environment variable and the client does not.

If you're using Next.js, you'll need to add some configuration to pass this data through to the client.

https://nextjs.org/docs#exposing-configuration-to-the-server--client-side

**Comment by flavienrako** [comment]
**test**
