### ISSUE TITLE
`Cache-Control` header is modified

### ISSUE THREAD

**Issue by amio** [vercel/vercel#3362]
Made a demo:
- src https://zeit.co/badgen/test-stale/8gss13bmh/source
- test https://test-stale-amio.badgen.now.sh/api

Expect `Cache-Control` header to be:

```
public, max-age=60, s-maxage=10800, stale-while-revalidate=604800, stale-if-error=604800
```

Actual:

```
public, max-age=60, stale-if-error=604800
```

**Comment by styfle** [comment]
It looks like `stale-if-error` is not supported yet.

I'll let the team know, thanks!

Updated: This is being tracked internally as Story 14471.

**Comment by sergeevabc** [comment]
@styfle, any news about ```stale-if-error``` support? People ask here and [there][1].

[1]: https://spectrum.chat/zeit/now/stale-if-error-support~5ece4989-d75c-43cd-8360-82f81e2ca9f9

**Comment by leo** [comment]
Our edge currently takes care of supporting these features, so we're stripping `stale-while-revalidate` away.

The fact that `stale-if-error` is not stripped is a bug that's now being resolved internally. We'll let you know here once it is.
