### ISSUE TITLE
Support node 12.x

### ISSUE THREAD

**Issue by fbjork** [vercel/vercel#3363]
Please add support for Node engine 12.x in `now dev`.

I currently get this error:

```
> Error! found `engines` in `package.json` with an unsupported node range: 12.x
please use `10.x` or `8.10.x` instead
```

**Comment by styfle** [comment]
Hi @fbjork 

This feature was added in the [latest](https://github.com/zeit/now/releases/tag/now%4016.6.0) Now CLI release.

Can you share the output of the following two?

```sh
now --version
cat ~/Library/Caches/co.zeit.now/dev/builders/package.json
```

**Comment by fbjork** [comment]
@styfle I'm on 16.6.0. It happened the first time I ran `now dev`, but not anymore. Really strange.

Here are the full logs:

```
> Now CLI 16.6.0 dev (beta) — https://zeit.co/feedback/dev
> Creating initial build
> Error! found `engines` in `package.json` with an unsupported node range: 12.x
please use `10.x` or `8.10.x` instead
```

**Comment by styfle** [comment]
When you start `now dev`, the cached copy of `@now/node` and `@now/build-utils` is used to build your code while the latest version is fetched in the background to speed up the initial build. So it sounds like this working for you now? Can you reproduce the issue again?
