### ISSUE TITLE
Now.json routes not working

### ISSUE THREAD

**Issue by SavedByZero** [vercel/vercel#3369]
I have a client build (entire project, really) inside a client folder and a server outside of it with its own index.js back end. I was initially getting this to happen by writing app.use(express.static(__dirname + "/client/build")); inside my server file. However, I’ve read that it’s preferable to use now.json for this kind of thing.
But my code seems to completely ignore anything I put inside there. I have: 
"routes": [
        {
          "src": "/(.*)",
          "dest": "/client/build/",
          "methods":["GET"]
        }
]

But that doesn’t do anything when I run the server or deploy. Is this an issue or am I just misunderstanding how it works?
(Also, my initial app.use only seems to work locally — when I deploy that whole setup, I get 404s across the board)

**Comment by mcsdevv** [comment]
Hello @SavedByZero, are you still experiencing this issue? If so, please provide a minimal reproducible example so that we can investigate.
