### ISSUE TITLE
[now-cli] trips on dangling symlinks, even when ignored

### ISSUE THREAD

**Issue by agriffis** [vercel/vercel#3370]
now version 16.6.0

Here's an example:

```
✸ ln -s foo bar
✸ now
> Deploying ~/src/ss/arongriffis.com under scampersand
> Using project arongriffis
> Error! ENOENT: no such file or directory, stat '/home/aron/src/ss/arongriffis.com/bar'
```

Adding the symlink to `.nowignore` doesn't help.

You might wonder why a dangling symlink. Because my site builds in a container where the symlink is valid, but deploys from outside the container. (The actual symlinks are more complicated than the foo bar example above.)

This used to work in some older version, probably 15.x. It just broke for me today when I upgraded to 16.6.0

Working around the bug is not easy.

**Comment by styfle** [comment]
Thanks for reporting this bug, great description!

I confirmed this behavior changed in [now@16.3.0](https://github.com/zeit/now/releases/tag/now%4016.3.0) with the introduction of `now-client`.

**Comment by leo** [comment]
We'll take a look at this very soon! Internally, it's being tracked [here](https://zeit.atlassian.net/browse/PRODUCT-830?atlOrigin=eyJpIjoiNzFjMjgxNzMzZDdjNDgzYWE1ZTUwZmYyMTRhZDE3NmIiLCJwIjoiaiJ9).

**Comment by Aleksion** [comment]
@leo any updates on this?

**Comment by leo** [comment]
We'll publish an update for this today.

**Comment by leo** [comment]
We'll be taking a look at this very soon. We'll keep you updated in this thread!

[Internal Link](https://app.clubhouse.io/vercel/story/5752/)

**Comment by nscarlson** [comment]
I'm experiencing the exact same problems.  These kinds of known, low-level bugs lurking around for a year without being addressed are unacceptable considering that many developers like me are considering becoming paying customers.
