### ISSUE TITLE
Slow rebuild with "now dev" when there are large nested node_modules

### ISSUE THREAD

**Issue by mattjennings** [vercel/vercel#3371]
Since now 16.4.0, monorepo projects with large node_modules suffer from significantly longer HMR (or rebuild time) on nextjs apps.

I've made an example repo at https://github.com/mattjennings/slow-now-dev-example. This seems to have been a problem since now@16.4.0. There are steps to reproduce in the repo's README, but I'll paste it below:

1. From the project root, run `yarn --production`

2. Run `now dev`

3. Make some changes in apps/test/pages/index.js and notice that every change is quick to reload.

4. Now, from the project root, run `yarn`. This will install a bunch of extra modules from apps/test/package.json's devDependencies. None of these are used.

5. Run `now dev` and make some changes to apps/test/pages/index.js again. You should notice that most changes take much longer to reload. (I found sometimes consecutive changes were quick, but most of the time it took 5~ seconds to show)

Scenarios where the rebuild is quick when node_modules is large:

- Running `next dev` from apps/test

- Running `now dev` from apps/test

- Running `now dev` from project root with now@16.3.0

**Comment by Gmulti** [comment]
I have the same problem with an API Node.
As soon as you start to have a "normal" project (even a small one...), `now dev` can't keep up with it.

**Comment by b3nab** [comment]
Same here.
I ended up with a bash script like this:
```sh
cd server
yarn dev &
cd ../web
yarn dev
```

Now I have quick rebuilds and HMR on web pages (with Next.js). 
Actually the vercel-dev is useless or even worsen the situation.

**Comment by styfle** [comment]
I just tried this example on the latest version of Vercel CLI (20.1.0) and it seems to take about 1 second from saving the file to it showing up in the browser.

Does this version fix the issue for you?

**Comment by mattjennings** [comment]
Yes, it is definitely fixed with 20.1.0! I'll close this.
