### ISSUE TITLE
`now dev` seems to handle `continue` differently

### ISSUE THREAD

**Issue by denkristoffer** [vercel/vercel#3375]
I'm building multiple apps in a monorepo and deploying them with Now. I was trying to get my routes working with Next.js static HTML pages as mentioned in https://github.com/zeit/next.js/issues/9213#issuecomment-548732391 and ended up with something like the following:

```json
{
  "name": "reproduction",
  "version": 2,
  "builds": [
    { "src": "packages/workspace/next.config.js", "use": "@now/next" }
  ],
  "routes": [
    { "src": "/(.*)", "dest": "packages/workspace/$1", "continue": true },
    {
      "src": "/_next/static/(?:[^/]+/pages|chunks|runtime|css|media)/.+",
      "headers": { "cache-control": "public,max-age=31536000,immutable" },
      "continue": true
    },
    { "handle": "filesystem" },
    { "src": "packages/workspace/(.*)", "dest": "packages/workspace/$1.html" }
  ]
}
```

This works when I deploy to Now, but with `now dev` the index page returns a 404. I've made a small reproduction here: https://github.com/denkristoffer/now-reproduction – try running `yarn now dev --local-config=./packages/workspace/now.json` from the root.

If I change the routes to this it works with `now dev`, but then the redirection to `.html` is lost:

```json
{
  ...

  "routes": [
    {
      "src": "/_next/static/(?:[^/]+/pages|chunks|runtime|css|media)/.+",
      "headers": { "cache-control": "public,max-age=31536000,immutable" },
      "continue": true
    },
    { "handle": "filesystem" },
    { "src": "/(.*)", "dest": "packages/workspace/$1" }
  ]
}
```

**Comment by leerob** [comment]
Hey! This issue has gone stale. If you're still having issues here, could you please open a new issue? 

Thank you so much 🙏
