### ISSUE TITLE
Feedback form doesn't work

### ISSUE THREAD

**Issue by e102** [vercel/vercel#3377]
When you build using `now dev`, there's a link to a feedback form at https://zeit.typeform.com/to/JMdFYu?product=now-dev
This feedback form is currently marked as private, meaning it's not possible to give feedback,

**Comment by leo** [comment]
Thank you for reporting this! We'll take a look.

In the meantime, feel free to report feedback directly on the [dashboard](https://zeit.co) (on the top right).
