### ISSUE TITLE
500 Internal Server Error nginx

### ISSUE THREAD

**Issue by lematt1991** [vercel/vercel#338]
I have a deployment that was at one point working, but I'm now getting a "500 Internal Server Error nginx" error.  This was a Docker container that I deployed that just contains a simple Node.js application that makes use of a few R scripts (via [node-rio](https://github.com/albertosantini/node-rio)).  My Dockerfile doesn't mention nginx at all, so I'd assume it isn't anything on my end causing this issue.  Any ideas?

**Comment by matheuss** [comment]
@ml9951 could you share the URL of the deployment? 

If you'd like to share privately, go to [zeit.chat](https://zeit.chat) and send me a DM 🙌

**Comment by lematt1991** [comment]
@matheuss, just sent you a message on Slack.

**Comment by leo** [comment]
If this problem still occurs, please move it over to [this repo](https://github.com/zeit/now-cloud). That's where we'll collect the bugs of the platform from now on (separate space, easier to work on)! 😊
