### ISSUE TITLE
property `github` is not allowed in now.json when using Now 2.0

### ISSUE THREAD

**Issue by miteyema** [vercel/vercel#3387]
Hi

Everything was working fine with Now CLI 16.6.0 dev (beta).
I got a notification there was an update available, so I now (pardon the pun) have Now CLI 16.6.1 dev (beta).
However, when I run `now`, I get the following error:
````
> Error! The property `github` is not allowed in now.json when using Now 2.0 – please remove it.
````
But the documentation clearly specificies these properties, please see https://zeit.co/docs/configuration#git-integrations

**Comment by styfle** [comment]
Hi @miteyema 

This was fixed in [version 16.6.2](https://github.com/zeit/now/releases/tag/now%4016.6.2).

Thanks!
