### ISSUE TITLE
Code splitting with Now static build and CRA (Long response time)

### ISSUE THREAD

**Issue by ahmadatallah** [vercel/vercel#3396]
I am using code splitting to lazy load my pages(routes) in a static website built using Create React App (CRA) managing the deployment with nowjs. What's happening is that js chunks' response time is too long making the lazy loading fallback to get rendered for too long. this is happening on the production build only!

**Comment by styfle** [comment]
Hi @syncatallah 

What do you mean the "js chunks' response time is too long"?
Can you share the slow URL here?

Thanks!

**Comment by ahmadatallah** [comment]
> Hi @syncatallah
> 
> What do you mean the "js chunks' response time is too long"?
> Can you share the slow URL here?
> 
> Thanks!

as you see, the chunk status is `Pending`! 
this will stay forever the first time I load the page, after any updates being deployed.

![Screenshot from 2019-12-11 14-17-40](https://user-images.githubusercontent.com/12163399/70620915-14ff5e00-1c21-11ea-969b-2f4aac1d0215.png)

you can get it using `curl`
```
curl 'https://syncatallah.cc/static/js/10.438bd524.chunk.js' -
H 'Referer: https://syncatallah.cc/others' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit
/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36' --compressed
```

**Comment by styfle** [comment]
Hi @syncatallah 

Thanks for the URL!

From my location, it seems to serve this file quite fast: 0.143s

Can you try again with `time` and also the `-I` flag to see the headers?

```
time curl -I --compressed https://syncatallah.cc/static/js/10.438bd524.chunk.js
```

In particular, I would like to know the values of the following headers:

* x-now-cache
* x-now-trace
* x-now-id

The trace will show you which [cdn edge](https://zeit.co/smart-cdn) is being used to serve the response.

This will help us narrow down the problem.

If you don't see any headers, please visit [Smart CDN](https://zeit.co/smart-cdn) and let me know the closest region.

Thanks!

**Comment by ahmadatallah** [comment]
Thanks @styfle  for your reply

The smart CDN is serving my content from Zurich, Switzerland with latency range 60-80 ms and distance of 2735 km from my location as shown when opening [smart CDN](https://zeit.co/smart-cdn) link!
![Screenshot from 2019-12-11 20-42-29](https://user-images.githubusercontent.com/12163399/70650228-5dd20980-1c57-11ea-8ed1-4460f0513801.png)


the headers you asked for which shows the same results: 

```
x-now-cache: MISS
x-now-trace: zrh1
x-now-id: zrh1:5bj4t-1576088364887-9d775b89147a
```

**Note**: 
if I do `time curl -I`, it serves the chunk in 0.949s total, but it's not the case from the browser!

**Comment by styfle** [comment]
If `curl` is behaving differently than your browser, it sounds like it could be a service worker issue.

Try disabling the service worker or clearing the site data.

![image](https://user-images.githubusercontent.com/229881/70725576-a70f7100-1cca-11ea-954f-60b50b1732b5.png)

**Comment by ahmadatallah** [comment]
I unregistered service worker and the pages load normally. It solves the problem but, what if I want to keep it!. do you have any ideas?

Thanks!

**Comment by styfle** [comment]
Hi @syncatallah 

If you want to use a service worker, you have to ensure it works properly and serves the correct content because it is is acting as an intermediary between the client/browser and ZEIT Now.

I would suggested reading the section [Updating Your Service Worker](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers#Updating_your_service_worker) on MDN. This explains versioning your SW in the case you need to release an update when you find a bug.
