### ISSUE TITLE
What does FROZEN deployment status mean?

### ISSUE THREAD

**Issue by bahmutov** [vercel/vercel#34]
I am getting sometimes FROZEN deployment status (deploying via API), for example

```
FROZEN express-sessions-tutorial-holgtyuece.now.sh
```

and was wondering if the process should just wait, or if FROZEN deploys should be aborted?

**Comment by OlliV** [comment]
Which function is returning that status code?

**Comment by leo** [comment]
@OlliV This endpoint: https://zeit.co/api#get-endpoint

**Comment by bahmutov** [comment]
yeah, I am deploying via API and then polling the get-endpoint. READY is good,
and if DEPLOYING or BOOTED I am waiting more, but FROZEN is considered an error, and I am not sure if this is correct assumption.

https://github.com/bahmutov/now-pipeline/blob/master/src/index.js#L67

**Comment by rase-** [comment]
`FROZEN` means that the deployment hasn't receiven traffic for a really long time, and has been temporarily hibernated. Do you get this while deploying? :thinking:

**Comment by bahmutov** [comment]
I was getting this for new deploys, and I think there were code changes in each,

**Comment by OlliV** [comment]
I had completely forgot this issue. We have since made a ton of improvements to the logic determining if the deployment is idling. Have you still seen this issue during the last weeks?

**Comment by bahmutov** [comment]
I will close the issue then for now and if I see it ever again will reopen.

**Comment by chrisvire** [comment]
I deployed something, and then had to go do something for an hour.  The deployment had already frozen.  What is the expected age of the deployment before being frozen?

**Comment by mixn** [comment]
@OlliV I’ve had a 1,5 day old deployment freeze when I sent it to a client for review. Will this be happening if I `alias` it to a real domain (and it doesn’t get much traffic), too? 

If so, that would be kinda bad.

Thank you in advance!

**Comment by jwahdatehagh** [comment]
It's happening to me even with an aliased custom domain bought through now... How do i prevent this? Do i have to set up a ping bot?! Super annoying for small websites that don't get much traffic...

**Comment by leo** [comment]
To prevent a deployment from sleeping, you can `now scale` it.

**Comment by jwahdatehagh** [comment]
Which i can't do on the Pro plan... ?

Edit: Aw, i can, thanks... (Tried to autoscale)

**Comment by irisSchaffer** [comment]
My deploy (which was aliased to a real domain) froze only an hour after deploying though... Surely that can't be right?

**Comment by TooTallNate** [comment]
@irisSchaffer It's possible, especially if the deployment isn't receiving any traffic. You can `now scale <url> 1` though like @leo mentioned to prevent the sleeping.

**Comment by irisSchaffer** [comment]
I guess this is tightly connected to https://github.com/zeit/now-cli/issues/511? Will comment there instead!

**Comment by sholtomaud** [comment]
@TooTallNate @leo if I run now scale <url> 1 

1. Do I get extra charges?
2. Why doesn't the new  Scaled to 1 instance: [1s] URL not list when I run ```now list```?
