### ISSUE TITLE
Error: EISDIR: illegal operation on a directory when deploying on Now

### ISSUE THREAD

**Issue by darknoon** [vercel/vercel#3400]
A couple issues with now + next.js seem to be caused by this module when run with yarn workspaces and tracing out of the workspace root.

Running locally is not an issue, but it fails on zeit now.

- https://spectrum.chat/zeit/now/deployment-failed-error-eisdir-illegal-operation-on-a-directory~1610db37-38fa-4ac8-ab9f-dc25888ef18b
- https://spectrum.chat/zeit/now/error-deploying-next-js-monorepo-on-now~99acb8f4-1648-4422-91ea-ca243195fbc4

[My log](https://gist.github.com/darknoon/bfa10f31b0f9054ce735a784fe12f10f)

**Comment by styfle** [comment]
This has been fixed in the canary channel: `npm i -g now@canary`.

If you are using `builds` in `now.json`, you must also change the use statement to `@now/next@canary`.

Thanks!

**Comment by louisremi** [comment]
I'm using nuxtjs/now-builder and I'm having the same EISDIR error when trying to run `now dev` locally, despite having installed `"now": "^17.0.0-canary.17",`

**Comment by styfle** [comment]
Hi @louisremi 

This issue has been fixed in `@now/next`.

However, we don't control `nuxtjs/now-builder` so I suggest creating an issue in their repository.

Thanks!
