### ISSUE TITLE
execPath is not been configured correctly on windows

### ISSUE THREAD

**Issue by betimer** [vercel/vercel#3407]
Environment: Windows 10, Node 12

Now is working under `npm run devEnv`, not on `yarn devEnv`

And I have checked that, the execPath  is different between and npm and yarn

On npm the execPath is `C:\\Program Files\\nodejs\\node.EXE`
On yarn the execPath is `C:\\Users\\betim\\AppData\\Local\\Temp\\yarn--1576022236171-0.22385290594043217\\node.CMD`

So yarn shows the problem:

```
child_process.js:114
  p.open(fd);
    ^

Error: EBADF: bad file descriptor, uv_pipe_open
    at Object._forkChild (child_process.js:114:5)
    at setupChildProcessIpcChannel (internal/bootstrap/pre_execution.js:328:30)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:49:3)
    at internal/main/run_main_module.js:7:1 {
  errno: -4083,
  code: 'EBADF',
  syscall: 'uv_pipe_open'
}
> [debug] [2019-12-11T00:06:40.139Z] Build process for next.config.js exited with 1
> [debug] [2019-12-11T00:06:42.838Z] No builders were updated
```

The code I have debuged is: https://github.com/zeit/now/blob/5be9f297de001609ce5363325e7e4a97fd7b2998/packages/now-cli/src/util/dev/builder.ts#L66

**Comment by styfle** [comment]
Thanks, this looks similar to the issue reported in #3338

**Comment by betimer** [comment]
I think so, it shows similar error output, and reproduce every time. @styfle

**Comment by styfle** [comment]
@betimer This has been changed to `process.execPath`. Do you still have this issue with the latest version of Vercel CLI?

https://github.com/vercel/vercel/blob/0d4be3f5f223bbaf6602b8754127326d323b00ad/packages/now-cli/src/util/dev/builder.ts#L64
