### ISSUE TITLE
 Github Zeit Some checks have not been complete yet

### ISSUE THREAD

**Issue by Muaykhao86** [vercel/vercel#3412]
Hi all,
One of my deployments has been stuck on pending for hours and is Now ignoring all other commits.

On github:
I have tried to go back a couple of commits and according to git my branch is up to date, I can now push to github but the Now app isn't doing anything with it as its still showing pending a few commits below.
When I click on the status, there is no link to reset.

On Zeit Now:
I have the last deployment that was successful
I have uninstalled the app from github and reinstalled it, both Zeit and github say that they are connected successfully and the project does have continuous deployment set up.

Can someone please help!? The repository is private but I can change it if anyone wants to look or wants screen shots.

**Comment by styfle** [comment]
Hi @Muaykhao86 

If you are using the Free plan, deployments will become queued. So if you push your code multiple times in a row, you might have to wait longer than normal.

If it has been more than an hour and a deployment is still stuck, please share the deployment URL (and if you don't mind making it public, that would be helpful too).

**Comment by Muaykhao86** [comment]
Hi @styfle, 

Thanks for your reply, it deployed around 5 minutes after I raised the issue! Good to know that it can be queued for a while on the free plan though.

All the best.
