### ISSUE TITLE
Local path support for dependencies

### ISSUE THREAD

**Issue by LightningK0ala** [vercel/vercel#343]
My project has a dependency which is included as a local path as per this [npm implementation](https://docs.npmjs.com/files/package.json#local-paths).

I tried running a deployment and got the following error:
```
> (node:72) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unknown package spec: local on mypackage@file:./mypackage
```

Any plans for ace to support this?

**Comment by TooTallNate** [comment]
> Any plans for ace to support this?

Yes there are, hang tight! 🔜

As a workaround might I suggest to change the relevant `require()` calls to be relative paths to that package instead of the package name (so change `require('mypackage')` to `require('./mypackage')`).

**Comment by TooTallNate** [comment]
User request: https://github.com/zeit/now-cli/issues/343

**Comment by LightningK0ala** [comment]
Awesome! Thanks for the tip!

**Comment by ctrlplusb** [comment]
@TooTallNate 👋

Sorry, I know this isn't a particularly helpful post, but any update on progress with this one?  It has me massively stuck in a rut with a project I am working on.

No worries if you don't think it's gonna land soon.  Just trying to set my own expectations and avoid creating some magical babel plugins if I can avoid it.

**Comment by TooTallNate** [comment]
@ctrlplusb Can you explain your situation a bit more? Are you trying to deploy a monorepo or something?

**Comment by sco** [comment]
Any update on this issue @TooTallNate? Like @jcsmesquita, my project has a local dependency (because it's hosted on a private NPM server). Here's my stack trace:

```
> Error Error: Unknown package spec: local on airbnb-dls-web@file:vendor/airbnb-dls-web
>     at resolve (/usr/lib/node_modules/@zeit/cace/build/lib/resolve.js:1:729)
>     at /usr/lib/node_modules/@zeit/cace/build/lib/install.js:1:4642
>     at tryCatch (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/regenerator/runtime.js:88:40)
>     at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/regenerator/runtime.js:341:22)
>     at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/regenerator/runtime.js:121:21)
>     at step (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
>     at /usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
>     at Promise (<anonymous>)
>     at F (/usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/node_modules/core-js/library/modules/_export.js:35:28)
>     at /usr/lib/node_modules/@zeit/cace/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12
> (node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Unknown package spec: local on airbnb-dls-web@file:vendor/airbnb-dls-web
> (node:80) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): HTTPError: Response code 404 (Not Found)
> (node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): HTTPError: Response code 404 (Not Found)
> (node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 25): Error: ENOENT: no such file or directory, readlink '/home/nowuser/src/node_modules/.tmp/7329591b-ee12-47c5-aa32-13ddc0ebfe75/node_modules/node-pre-gyp'
> (node:80) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 26): Error: ENOENT: no such file or directory, readlink '/home/nowuser/src/node_modules/.tmp/dd3ecded-c7e5-48a9-872f-83026b66b120/node_modules/node-pre-gyp'
```

**Comment by TooTallNate** [comment]
@sco Still working on it. But could you do the same workaround as suggested to @jcsmesquita? That is, change `require('airbnb-dls-web')` calls to relative ones like `require('../vendor/airbnb-dls-web')` (be sure to get the correct relative prefix to the file path).

**Comment by simonexmachina** [comment]
The problem with the workaround is that the local module isn't installed properly. I've had to:
- change the `require` statements to be relative
- remove the local `file:` module
- move all of the dependencies of the local module into the top-level package.json

**Comment by parweb** [comment]
any news on be able to have local dependencies working with now ?

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), this is working as expected.
