### ISSUE TITLE
Multiple yarn install during deploy because of static-build

### ISSUE THREAD

**Issue by Akryum** [vercel/vercel#3432]
static-build is doing an unecessary install of dependencies in my mono-repo, wasting 20 s. every deployments:

```
Installing build runtime...
Build runtime installed: 565.261ms
Installing dependencies...
yarn install v1.17.3
Done in 18.44s.
```

Reproduction: https://github.com/Akryum/awesomejs.dev/blob/dev/now.json

**Comment by styfle** [comment]
Your `now.json` defined two builds using two different builders, so it is expected that `yarn install` will run twice.

**Comment by Akryum** [comment]
I don't think this should happen in any mono-repo. Is there a workaround?

**Comment by styfle** [comment]
You have two different package.json files so both must be installed (backend and frontend).

https://github.com/Akryum/awesomejs.dev/blob/dev/packages/backend/package.json

https://github.com/Akryum/awesomejs.dev/blob/dev/packages/frontend/package.json

**Comment by Akryum** [comment]
A single install at the root would suffice, this is a mono-repo using yarn workspaces (which is very common in mono-repos).

**Comment by styfle** [comment]
Thanks, I'll forward your suggestion to the team.

**Comment by Akryum** [comment]
Thanks!

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each support request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize and track the progress.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs in any part of our system, that we can immediately act on.

For detailed support requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that our team can help you out directly.

**Comment by Akryum** [comment]
Still a bug to me... Welp, if you don't want to improve your service...

**Comment by leo** [comment]
This issue was wrongly flagged as "question", but it is actually a bug report. In turn, we're re-opening it so that customers that are running into the same problem will be able to easily find an existing report.

**Comment by styfle** [comment]
This is not a bug, the feature is working as intended.

Your [now.json](https://github.com/Akryum/awesomejs.dev/blob/dev/now.json) file has two `builds` defined, one for static-build and one for node. Each of those builds will run `yarn install`. If the `src` is a regex and matches multiple files, then `yarn install` will run for each matched file.

See my answer here: https://github.com/vercel/vercel/discussions/4995#discussioncomment-47844

**Comment by Akryum** [comment]
Running `yarn install` multiple times in a mono-repo that is using yarn workspaces doesn't make sense and is just a waste of time because all the install commands will download and install the same packages at the same location (the root of the mono-repo). This is indeed a bug.

**Comment by Akryum** [comment]
Learn more about yarn workspaces [here](https://classic.yarnpkg.com/en/docs/workspaces).
