### ISSUE TITLE
[now dev] Reloading not supported on CRA project

### ISSUE THREAD

**Issue by ctrlplusb** [vercel/vercel#3451]
`now dev` then spins up it's own server and proxies request to the underlying CRA dev server. 

I have noticed that the `/sockjs-node` websocket requests never get proxied correctly, and therefore we can't support auto page reload, or react hot loader / react fast refresh (via react app rewired).

---

**Observations**

It appears that when running `now dev` it actually makes the underlying CRA dev server run on a random port, for e.g 49426. The actual `now dev` server runs on the typical port that CRA would normally run on, i.e. 3000. This confused me a bit but I eventually figured out what was going on.

That all being said, if I load the CRA dev server directly (i.e. utilising the random port, e.g. 49426) then I notice the `/sockjs-node` requests resolving correctly.  It's only when I use the `now dev` proxy server (i.e. 3000) that the requests do not resolve.

---

**Steps to reproduce**

1. Create a new black CRA project
2. Add the script:
    ```
    "dev": "BROWSER=none react-scripts start"
    ```
3. Run `now dev`
4. Open browser on http://localhost:3000
5. Open dev tools and note the `/sockjs-node` request never resolving

---

Without this request proxying correctly we can never get hot reloading working as rad as it could. With the new React Fast Refresh around the corner it would be great to get the `now dev` server ready to support this.

**Comment by ctrlplusb** [comment]
Actually... on further investigation, it's the introduction of `BROWSER=none` prefixed environment variable on the "dev" script which seems to cause this. This appears to be the recommendation when utilising functions. Even without any functions in existence.

**Steps to reproduce**

1. Create a new create-react-app project
2. Add the following dev script to package.json scripts:
    ```
   "dev": "BROWSER=none react-scripts start",
    ```
3. Run `now dev`

Note that the `/sockjs-node` never resolves.

Removing the `BROWSER=none` and running `now dev` again shows it proxying correctly.

**Comment by ctrlplusb** [comment]
🙇 😇 💜

**Comment by ctrlplusb** [comment]
FYI...

@rauchg reached out on twitter and said the team is fully aware of this. ⭐️

**Comment by styfle** [comment]
Hi @ctrlplusb 

I just tried this with the Now CLI Canary and it worked correctly. I believe this was fixed in Now 17.

![image](https://user-images.githubusercontent.com/229881/76460699-de1e1d00-63b4-11ea-9bb8-449f553ac8f5.png)

The canary channel has another fix (#3903) that makes the url/port a little more clear.

```
npm i -g now@canary
```

Does this fix your issue?

**Comment by ctrlplusb** [comment]
Oh my gosh, great news. Shall, try later and report back.

**Comment by hamstu** [comment]
@styfle Thanks for letting us know. I tried in my own local setup and it doesn't seem to be working... the ws connection timed out:

![image](https://user-images.githubusercontent.com/809093/76568567-51d03080-646e-11ea-96e3-718fc97e4b20.png)

```
webpackHotDevClient.js:60 WebSocket connection to 'ws://localhost:3000/sockjs-node' failed: WebSocket opening handshake timed out
```

It' just a standard create-react-app setup with an api folder for a few cloud functions. Anything I can do to fix/debug?

**Comment by styfle** [comment]
Interesting, it looks like the the `/sockjs-node/821/qtqlwiuf/xhr_streaming?t=1584126247319` request is what updated on save for me. It had the same affect of hot-reloading but it wasn't actually using a WebSocket.

**Comment by BrunoQuaresma** [comment]
Auto reloading is not working for me as well on `Now CLI 17.0.4 dev (beta)`.

Currently, `now dev` is starting the app on two ports. 3000 and a random one. The random one works with the auto reloading but does not work with API functions. The 3000, works good with API functions but, does not work with auto reloading.

**Comment by matchu** [comment]
Hi hi, I'm having this issue but it's even worse in Firefox (76)! The sixth time I load the page, the whole proxy server stops responding to requests and requires two Ctrl-Cs to kill instead of one 😬

My hypothesis is that this is because Firefox handles the socket issues differently, and keeps the problematic sockets open, whereas perhaps Chrome hangs them up? And so then we hit Node's default limit of 5 open sockets for a given host.

I can work around it for now by switching to Chrome, but just fyi that this was a pretty disruptive newcomer experience for me, and might be worth increasing the priority for that reason! It took me a while to learn enough to find this issue or to consider that changing my browser could do anything 😅

**Comment by ctrlplusb** [comment]
I tried to locate the proxy code myself to see if I could contribute a patch, but wasn't entirely sure I had the right area of code.

**Comment by styfle** [comment]
@ctrlplusb Thanks for looking at this one! Here's the relevant code: https://github.com/zeit/now/blob/282127e3f9983e542da21fb75d3db78459e31dca/packages/now-cli/src/util/dev/server.ts#L1849-L1855

**Comment by matchu** [comment]
For what it's worth, the only suspicious thing I noticed in my scan of the code (it looks like it's mostly a straightforward library call?) is that it seems like we maybe create a new instance of the proxy server for every request, which isn't what matches the usage examples for the library. I wonder if that e.g. shuts down the proxy server early, while it's still trying to negotiate the socket upgrade? Could refactoring it to use one shared longer-lived proxy server instance maybe fix it?

No guarantees on this, and it wasn't a very deep debug, that's just the one thing that came to mind as a thing that might be worth trying!

**Comment by TooTallNate** [comment]
Having a cache of the http proxy instances sounds like it could do the trick!

**Comment by ctrlplusb** [comment]
@styfle @TooTallNate 

Is there a contributors guide for how one may make a change and then test the results locally?

**Comment by styfle** [comment]
Yes we have a contributing doc here: https://github.com/zeit/now/blob/master/.github/CONTRIBUTING.md

Looks like it needs to be updated. For your purposes, this should work:

```
git clone https://github.com/zeit/now
cd now
yarn install
yarn build
cd ./packages/now-cli
yarn test-integration-dev
```

The cli bin is located at `./packages/now-cli/dist/index.js`.

**Comment by matchu** [comment]
I think I got this one! My theory wasn't actually true; the multiple instances of the proxy server weren't the culprit! Instead, it's just that we were missing a step for WebSocket support: `{ws: true}` by itself isn't enough!

**Comment by hamstu** [comment]
@matchu That's awesome to hear! Lmk if you have a dev branch to test out somewhere.

**Comment by matchu** [comment]
@hamstu yep it's on my fork, in review as PR #4241!
