### ISSUE TITLE
[error] gastby build fails when there are md edits 

### ISSUE THREAD

**Issue by wunnle** [vercel/vercel#3453]
Hi,

I'm consistently getting build error with Gastby on Now using auto deploys from Github commits. Curious thing is, when redeploy or manually deploy using now cli, this error does not happen _never_ happens.  This issue only happens if I edit an .md file. 

There are no build issues on local.

Here is the relevant part of the log:

```

info bootstrap finished - 3.893 s
--
08:52:08 AM | ⠀
08:52:10 AM | success Generating image thumbnails - 1.709s - 6/6 3.51/s
08:52:16 AM | failed Building production JavaScript and CSS bundles - 7.849s
08:52:16 AM | ERROR #98123  WEBPACK
08:52:16 AM | Generating JavaScript bundles failed
08:52:16 AM | Can't resolve '../../public/static/d/856328897.json' in '/zeit/3b2a2619/src/components'
08:52:16 AM | File: src/components/layout.js
08:52:16 AM | not finished run queries - 7.949s
08:52:16 AM | error Command failed with exit code 1.
08:52:16 AM | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
08:52:16 AM | Error: Exited with 1
08:52:16 AM | at ChildProcess.child.on (/zeit/f51a0a4251865668/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:34567:24)
08:52:16 AM | at emitTwo (events.js:126:13)
08:52:16 AM | at ChildProcess.emit (events.js:214:7)
08:52:16 AM | at maybeClose (internal/child_process.js:925:16)
08:52:16 AM | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
08:52:17 AM | worker exited with code 20 and signal null
08:52:19 AM | done

```

I'm attaching the [full log](https://github.com/zeit/now/files/3986926/log.txt) Here is the repo: https://github.com/wunnle/mostly-indie

**Comment by mcsdevv** [comment]
Hey @wunnle, apologies for the delay in getting to you on this. Are you still experiencing the issue?

**Comment by wunnle** [comment]
Hey @mcsdevv , no worries! I resolved the issue a few months ago. As far as I remember it was not about Now, it was about an Gatsby issue.

**Comment by mcsdevv** [comment]
Hey @wunnle, thanks for letting me know - have a great day!
