### ISSUE TITLE
Now won't deploy my gatsby site anymore

### ISSUE THREAD

**Issue by assentorp** [vercel/vercel#3462]
I'm trying to deploy a **gatsby** site using now. It's worked great in the past and I've had no issues with deployment what so ever. Yesterday I made a small change in my code, where I basically changed a few css properties.

When I deploy to now I start getting this error:
`"Error: Invariant Violation: Encountered an error trying to infer a GraphQL typ  e for: `pluginCreator___NODE`. "`

As I only made a css change this doesn't make any sense to me. The project works fine when I build and serve it locally so I assume it most be a problem with Now?

Below is the deployment log. Any help is appreciate it:

Downloading 188 deployment files...
--
12:17:11 PM | Installing build runtime...
12:17:11 PM | Build runtime installed: 505.067ms
12:17:12 PM | Looking up build cache...
12:17:13 PM | Build cache found [31.96 MB, 31370 files]
12:17:13 PM | Build cache unpacked: 1448.570ms
12:17:14 PM | Installing dependencies...
12:17:20 PM | npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 \|\| >= 3.2.0-dev \|\| >= 3.3.0-dev \|\| >= 3.4.0-dev \|\| >= 3.5.0-dev \|\| >= 3.6.0-dev \|\| >= 3.6.0-beta \|\| >= 3.7.0-dev \|\| >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
12:17:20 PM | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/chokidar/node_modules/fsevents):
12:17:20 PM | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:17:20 PM | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
12:17:20 PM | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
12:17:20 PM | up to date in 6.183s
12:17:20 PM | Running "npm run build"
12:17:20 PM | > gatsby-starter-hello-world@0.1.0 build /zeit/66b14ee2
12:17:20 PM | > gatsby build
12:17:21 PM | ╔════════════════════════════════════════════════════════════════════════╗
12:17:21 PM | ║                                                                        ║
12:17:21 PM | ║   Gatsby collects anonymous usage analytics                            ║
12:17:21 PM | ║   to help improve Gatsby for all users.                                ║
12:17:21 PM | ║                                                                        ║
12:17:21 PM | ║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
12:17:21 PM | ║   To learn more, checkout https://gatsby.dev/telemetry                 ║
12:17:21 PM | ║                                                                        ║
12:17:21 PM | ╚════════════════════════════════════════════════════════════════════════╝
12:17:22 PM | success open and validate gatsby-configs - 0.015s
12:17:23 PM | success load plugins - 0.030s
12:17:23 PM | success onPreInit - 0.002s
12:17:23 PM | success delete html and css files from previous builds - 0.011s
12:17:23 PM | success initialize cache - 0.005s
12:17:23 PM | success copy gatsby files - 0.019s
12:17:23 PM | success onPreBootstrap - 0.006s
12:17:23 PM | success createSchemaCustomization - 0.001s
12:17:23 PM | success source and transform nodes - 0.031s
12:17:23 PM | success building schema - 0.127s
12:17:23 PM | success createPages - 0.001s
12:17:23 PM | success createPagesStatefully - 0.059s
12:17:23 PM | success onPreExtractQueries - 0.001s
12:17:23 PM | ERROR
12:17:23 PM | Encountered an error trying to infer a GraphQL type for: `pluginCreator___NODE`. There is no corresponding node with the `id` field matching: "8a50951f-fdbc-5298-9f59-0f92d6a845c5".
12:17:23 PM |  
12:17:23 PM | Error: Invariant Violation: Encountered an error trying to infer a GraphQL typ  e for: `pluginCreator___NODE`. There is no corresponding node with the `id` fi  eld matching: "8a50951f-fdbc-5298-9f59-0f92d6a845c5".
12:17:23 PM |  
12:17:23 PM | - invariant.js:40 invariant
12:17:23 PM | [66b14ee2]/[invariant]/invariant.js:40:15
12:17:23 PM |  
12:17:23 PM | - add-inferred-fields.js:266 getFieldConfigFromFieldNameConvention
12:17:23 PM | [66b14ee2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:266:3
12:17:23 PM |  
12:17:23 PM | - add-inferred-fields.js:171 getFieldConfig
12:17:23 PM | [66b14ee2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:171:19
12:17:23 PM |  
12:17:23 PM | - add-inferred-fields.js:95 Object.keys.forEach.key
12:17:23 PM | [66b14ee2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:95:25
12:17:23 PM |  
12:17:23 PM | - Array.forEach
12:17:23 PM |  
12:17:23 PM | - add-inferred-fields.js:82 addInferredFieldsImpl
12:17:23 PM | [66b14ee2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:82:28
12:17:23 PM |  
12:17:23 PM | - add-inferred-fields.js:46 addInferredFields
12:17:23 PM | [66b14ee2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:46:3
12:17:23 PM |  
12:17:23 PM | - index.js:102 addInferredType
12:17:23 PM | [66b14ee2]/[gatsby]/dist/schema/infer/index.js:102:3
12:17:23 PM |  
12:17:23 PM | - schema.js:132 rebuildSchemaWithSitePage
12:17:23 PM | [66b14ee2]/[gatsby]/dist/schema/schema.js:132:5
12:17:23 PM |  
12:17:23 PM | - index.js:103 Object.rebuildWithSitePage
12:17:23 PM | [66b14ee2]/[gatsby]/dist/schema/index.js:103:24
12:17:23 PM |  
12:17:23 PM | - index.js:469 module.exports
12:17:23 PM | [66b14ee2]/[gatsby]/dist/bootstrap/index.js:469:30
12:17:23 PM |  
12:17:23 PM |  
12:17:23 PM | not finished update schema - 0.059s
12:17:23 PM | npm ERR! code ELIFECYCLE
12:17:23 PM | npm ERR! errno 1
12:17:23 PM | npm ERR! gatsby-starter-hello-world@0.1.0 build: `gatsby build`
12:17:23 PM | npm ERR! Exit status 1
12:17:23 PM | npm ERR!
12:17:23 PM | npm ERR! Failed at the gatsby-starter-hello-world@0.1.0 build script.
12:17:23 PM | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
12:17:23 PM | npm ERR! A complete log of this run can be found in:
12:17:23 PM | npm ERR!     /zeit/.npm/_logs/2019-12-23T11_17_23_505Z-debug.log
12:17:23 PM | Error: Exited with 1
12:17:23 PM | at ChildProcess.child.on (/zeit/f51a0a4251865668/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:34567:24)
12:17:23 PM | at emitTwo (events.js:126:13)
12:17:23 PM | at ChildProcess.emit (events.js:214:7)
12:17:23 PM | at maybeClose (internal/child_process.js:925:16)
12:17:23 PM | at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
12:17:23 PM | worker exited with code 20 and signal null
12:17:25 PM | done

**Comment by styfle** [comment]
This sounds like a gatsby plugin issue, not a ZEIT Now issue.

Take a look at this: https://github.com/gatsbyjs/gatsby/issues/14193
