### ISSUE TITLE
EACCES: permission denied

### ISSUE THREAD

**Issue by MentalGear** [vercel/vercel#347]
I get the EACCES: permission denied message when my app is trying to access style.css.

I have defined a middleware in my express app to automatically generate the style.css from a style.sass. It works fine locally, but the server seems to block the access to the generated file.

> app.use(
>     sassMiddleware({
>         /* Options */
>         root: __dirname + "/public/stylesheets",
>         src: "/sass",
>         dest: "/css_compiled",
>         // src: path.join(__dirname, 'public/stylesheets'),
>         // dest: path.join(__dirname, 'public/stylesheets'),
>         debug: true,
>         outputStyle: 'compressed',
>         prefix:  '/stylesheets',    // Where prefix is at <link rel="stylesheets" href="prefix/style.css"/>
>         response: false,            // to write as files instead of into var
>         indentedSyntax: true    // to use sass
>     })
> );

**Comment by jamo** [comment]
The filesystem should be only modified in the install and build steps.
And in `npm run start` or `npm run now-start` the filesystem is read only -- afterall, the deployments are immutable.

**Comment by MrLoh** [comment]
I also ran into this problem. I want to enable uploading image files to an api and serving them back, is that possible at all?

**Comment by spences10** [comment]
@MrLoh I need to know this too, doing the same, getting an error when trying to open the `*.jpg` file

**Comment by jamo** [comment]
After `npm run build` phase has completed, everything but `/tmp` is read only.

**Comment by morgs32** [comment]
@jamo Trying to access some logs in `/tmp` isn't working for me. Any clue?
https://zeit.co/morgs32/morganatwork/bdgzvuhtit/logs

**Comment by jamo** [comment]
`/tmp/` or `tmp/` - the first should work while opening files for writing in the latter (`tmp/`) won't work.
One option would be to use `os.tmpdir()`
