### ISSUE TITLE
[bug] Issue with GitHub SSO authentication

### ISSUE THREAD

**Issue by ssong** [vercel/vercel#3472]
The reproduction steps are slightly tricky but I had a GitHub account with the handle of `ssong-eu`. I used this account to sign up for a zeit.co account using the GitHub SSO.

Recently I changed my GitHub handle to `ssong`. I can no longer sign in to zeit.co with my GitHub account as it doesn't recognise the change.

If I try to open a new account using GitHub SSO the following error appears and it doesn't seem to be properly handled.

<img width="1680" alt="Screenshot 2019-12-24 at 23 12 35" src="https://user-images.githubusercontent.com/20317665/71426587-d39c9300-26a3-11ea-95f0-b57828fcd1eb.png">

P.S. Happy holidays!

**Comment by ssong** [comment]
Issue can be fixed by user by signing in with an email and then reconnecting the GitHub account

**Comment by mcsdevv** [comment]
The issue has been resolved with login improvements made previously - thanks for reporting!
