### ISSUE TITLE
Domain aliases aren't released after the project is deleted

### ISSUE THREAD

**Issue by ivan-kleshnin** [vercel/vercel#3492]
Hi. I deleted my project to start everything from scratch. Zeit Admin displays "No Projects". I also removed all domains. Zeit Admin displays "No domains".

Now I'm trying to push my project with the same alias and I'm getting a message "The alias is already in use". I'm pretty sure it conflicts with that previously deleted stuff somehow – so it wasn't really deleted. The same happens if I'm trying to add that domain from the UI.

I double checked personal and company accounts. Both of them are free of "Used domains".
The possibility that someone else captured that domain in that few seconds I performed the transition is negligible. I think this is a bug at Zeit platform.

**Comment by samcx** [comment]
This is the intended behavior at the moment. First use the command `now alias list`. The alias you're trying to use is still owned by the account you originally used it with. To remove the alias and use it in the account you need it, use the `now alias rm` command.

**Comment by ivan-kleshnin** [comment]
Ok, thank you for the clarification!
