### ISSUE TITLE
Moving Regex Routes to Rewrites

### ISSUE THREAD

**Issue by stuartmemo** [vercel/vercel#3495]
I noticed that the routes property in now.json has been deprecated, so thought I should move my routes to the rewrites property instead. I make heavy use of regexs, but these now return an error stating that `Error! Pattern cannot start with "?"`.

How best should I change the following to get it to work? I very much require the regex to match at the root level and fall through to others if not matched. Any pointers would be very much appreciated.

```
{
  "source": "/(?<username>[a-zA-Z0-9_]{3,15})",
  "destination": "/user?username=$username"
}
```

**Comment by styfle** [comment]
Hi @stuartmemo 

You should be able to use a path segment instead of regex like the following:

```json
{
  "rewrites": [
    { "source": "/:username", "destination": "/user" }
  ]
}
```

**Comment by stuartmemo** [comment]
Thanks for the reply! Sorry, I should've been a bit clearer with my example. Your code works great for one route level path, but what if you need more than one? So something like...

```
{
  "rewrites": [
    { "source": "/:username", "destination": "/user" },
    { "source": "/:pageId", "destination": "/page" },
    { "source": "/hello", "destination": "hello.html" }
  ]
}
```
The first route will never fall-through to the second route, which the old regex method allowed. To be honest though now that I'm typing it out, it's probably very bad url practice! 😆 I can easily move the specific non-path segment routes before the one that was regexed too, so they match first.

What I did like however with the regex method though was that if the route didn't match exactly, then it would throw a 404. So if someone visited `/hi`, my `:username` path wouldn't match as my regex stated that it had to be at least 3 characters long. Using path segments, `/hi` will now match. I assume I just handle this in the individual page component and try throw from there?

**Comment by styfle** [comment]
Hi @stuartmemo 

Those are good questions!

You are correct with your example "The first route will never fall-through to the second route".

However, one of the changes with `rewrites` is that files take precedence before any rewrites. So you no longer need to define `{ "source": "/hello", "destination": "hello.html" }`.

Instead, use [cleanUrls: true](https://zeit.co/docs/configuration/#project/cleanurls) so that your html files will be renamed and visiting `/hello` will return the contents of `hello.html`.

Let me know if that solves your problem, thanks!

**Comment by stuartmemo** [comment]
Amazing, that's really helpful, thanks.

I'm actually having trouble with path segments working altogether. I have file `pages/tags.js` which gets picked up automatically by `tags/radiohead`, but not `tags/:tag`.

Do I need to do anything to turn this feature on? I'm on Now `16.7.1` so should be good I think. Don't suppose you have a working example with this new redirect format so I can have a dig through?

Thanks again, really appreciate your help & work on this project.

**Comment by styfle** [comment]
It sounds like you're using Next.js for your framework, so I would recommend using `next.config.js` instead of `now.json` per the RFC here https://github.com/zeit/next.js/issues/9081

You will need to use `next@canary` in your dependencies.

**Comment by stuartmemo** [comment]
Thanks for that, have removed my `now.json` and added the 'experimental' routes to `next.js` but with the same effect - the file-based routes win every time and overwrite any custom ones. I'm using `now dev` if that has any influence?

I'll probably have to wait until the feature is stable and documented. Thanks again!

**Comment by styfle** [comment]
Oh I think I misunderstood your example.

Yes, this is intended behavior. When using `rewrites`, the file system will always take precedence.

**Comment by stuartmemo** [comment]
A-ha! Got it working. Just renamed my file to `/pages/tags/[tag].js` and removed all the routes in my config altogether.

That's a cool way of handling it. Thanks for all your help!
