### ISSUE TITLE
All my projects working on Nuxt currently not deploing

### ISSUE THREAD

**Issue by vanhock** [vercel/vercel#3499]
Builds failed with error:

Error: No output directory named "dist" found.
--
11:02:29 PM | More details: https://zeit.co/docs/v2/platform/frequently-asked-questions#missing-public-directory
11:02:29 PM | at validateDistDir (/zeit/69d347bcc38c1970/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:132:15)
11:02:29 PM | at Object.build (/zeit/69d347bcc38c1970/.build-utils/.builder/node_modules/@now/static-build/dist/index.js:371:13)
11:02:29 PM | at <anonymous>
11:02:29 PM | at process._tickDomainCallback (internal/process/next_tick.js:228:7)

And two days ago, all build was succesfull, I didn't change anything in nuxt.config.js and now.json.
Nuxt generate configured correctly:
![image](https://user-images.githubusercontent.com/8645120/71771183-4d583a80-2f48-11ea-8284-ff0d32918c3d.png)

**Comment by wallslide** [comment]
@vanhock It seems like their latest `now` release is detecting nuxt projects automatically, and assuming that the output directory should be the default `dist` instead of `public`. I used to have to set this is the `nuxt.config.js` file:
```
 generate: {
    dir: 'public'
  }
```
But you can remove that now

**Comment by vanhock** [comment]
It works. Thank you for help, @wallslide! 
I hope they will fix package.json build scripts support soon.

**Comment by janwillemwilmsen** [comment]
encountered the same problem with deploying Nuxt on Vercel. This solved it : https://vercel.com/guides/deploying-nuxtjs-with-vercel
