### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by leo** [vercel/vercel#350]
Things like `now open` could be split out into plugins and installed:

```bash
npm install -g now-open
```

**Comment by matheuss** [comment]
![amazing](https://cloud.githubusercontent.com/assets/4721750/23257336/1abf1dac-f9a2-11e6-826c-152f31081490.png)

**Comment by leo** [comment]
This could be problematic for the bundled binary, because we would have to automatically update the plugins as well (otherwise it could break).

But we can't just do that, since we're not the authors. IMO.

**Comment by leo** [comment]
We have decided against this.
