### ISSUE TITLE
Keeping verifying email during login

### ISSUE THREAD

**Issue by enzeberg** [vercel/vercel#3501]
![now_verifying](https://user-images.githubusercontent.com/18072932/71793478-01a4ae80-3078-11ea-9897-4941f5f2576d.PNG)

**Comment by styfle** [comment]
Hi @enzeberg 

Are you still experiencing this issue? Does it happen every time?

**Comment by enzeberg** [comment]
@styfle 
It seems that `Now` has been upgraded. I remember that before we could use local command to deploy (and this issue often happened), but now it needs to import project from GitHub. I tried to deploy a project with one of my repositories and succeeded.
`Now` is so cool~

**Comment by styfle** [comment]
Glad it’s working!

Indeed, you can avoid Now CLI and instead connect your Git project to ZEIT Now which allows you to use “git push” to deploy!
