### ISSUE TITLE
Now and Next.js don't work with spawning an executable

### ISSUE THREAD

**Issue by timsuchanek** [vercel/vercel#3503]
If you build a Next.js application, which spawns a process in a Next api page, it seems like either Next.js or Now is not correctly copying over the executable file to be spawned. Concretely, it's not keeping the executable access permission (which can be obtained with `chmod +x filename`.

The resulting error is
`Error: spawn /var/task/node_modules/dummy-executable-package/executable EACCES`

This issue blocks the usage of Photon.js together with Next.js deployed to Now. 
It's tracked here: https://github.com/prisma/prisma2/issues/1170

I created a minimal reproduction without Photon.js and just a simple package spawning a Node.js shebang executable here: https://github.com/timsuchanek/p2-1170

This is the example package including the executable: https://github.com/timsuchanek/dummy-executable-package

**Comment by leo** [comment]
Thanks for reporting! We'll take a look this week.

**Comment by ghost** [comment]
any progress in this?

**Comment by AndyBitz** [comment]
Thank you for reporting this issue, we'll release a canary of `@now/next` in the next minutes which will fix this issue and then later on a stable version.

**Comment by kvnwolf** [comment]
> Thank you for reporting this issue, we'll release a canary of `@now/next` in the next minutes which will fix this issue and then later on a stable version.

Thanks! Is there a way to specify which `@now/next` builder to use if I'm using zero-config?

**Comment by styfle** [comment]
Yes, using the canary CLI will use canary `@now/next`.

```
npm i -g now@canary
```

However we just shipped [stable](https://github.com/zeit/now/commit/e09a41842317c6a25ad79dd367f30c4596adbcc1) so no need to 👍

**Comment by EranSch** [comment]
This appears to have resolved my issue perfectly, thank you Zeit team—you
guys are doing the Lord's work!

**Comment by timsuchanek** [comment]
Thanks a lot @AndyBitz !
