### ISSUE TITLE
Setup proxy configuration for now cmd

### ISSUE THREAD

**Issue by SaadRegal** [vercel/vercel#3519]
I'm trying to use `now login` behind a corporate proxy, is there any way to configure it ?

error  :

> Error! request to https://api.zeit.co/now/registration?mode=login failed, reason: connect ETIMEDOUT 52.9.164.177:443

**Comment by styfle** [comment]
It sounds like your corporation is blocking `*.zeit.co`. You'll probably need to contact your IT department to allow traffic to that domain.
