### ISSUE TITLE
Is there a way to see quota usage?

### ISSUE THREAD

**Issue by kertof** [vercel/vercel#3527]
Hi,
I'm currently running with a Free plan, I was wondering where I was regarding the quotas that I have, specifically the number of build-minutes used this month, the number of daily deploys, and the used Bandwidth.
It would allow me to get a better sense of my usage, and see if switching to A Pro account is the right thing to do.

Thanks!

**Comment by styfle** [comment]
Hi @kertof 

Your usage can be viewed here: https://vercel.com/dashboard/usage

**Comment by mattvb91** [comment]
@styfle how do we view this page on free plans?

**Comment by brijesh-rohilla** [comment]
yes, I have the same problem. The maintainer of this project should think about free quota users. Please update soon as possible...

**Comment by styfle** [comment]
We are planning to enable the new Usage page for Hobby plans in the near future, thanks!

**Comment by dizys** [comment]
Please make it happen for Hobby plan. A lot of thanks!
