### ISSUE TITLE
now.json "rewrites" with named params have strange value once deployed

### ISSUE THREAD

**Issue by wilsonpage** [vercel/vercel#3540]
### Reduced test case

https://github.com/wilsonpage/zeit-now-next-rewrites-bug

### Steps:

1. Deploy with `now` (or use [this deploy](https://tmp-nextjs-example.wilsonpage.now.sh))
2. Visit https://tmp-nextjs-example.wilsonpage.now.sh/hello
3. Observe `world` `200` response ✅
4. Visit https://tmp-nextjs-example.wilsonpage.now.sh/hello-regex/john
5. Observe `{"name":"john","query":{"name":"john"}}` response ✅
6. Visit https://tmp-nextjs-example.wilsonpage.now.sh/hello-param/john
7. Observe `{"name":":name?name=john","query":{"name":":name?name=john"}}` response ❌

**Comment by styfle** [comment]
Thanks for reporting!

This issue was fixed in #3640 and I confirmed by making another deployment.
