### ISSUE TITLE
mdx-deck example should be in SPA mode

### ISSUE THREAD

**Issue by rohit-gohri** [vercel/vercel#3546]
Currently refreshing when on any slide other than title leads to a 404: https://mdx-deck.now-examples.now.sh/2

Will be fixed by adding a simple now.json:

```json
{
  "version": 2,
  "routes": [
    { "handle": "filesystem" },
    { "src": "/.*", "dest": "/" }
  ]
}
```

**Comment by styfle** [comment]
We no longer have the mdx-deck example so I'm closing this issue.
