### ISSUE TITLE
Add minimal Sinatra example

### ISSUE THREAD

**Issue by eterps** [vercel/vercel#3548]
It doesn't seem to be working if I follow the documentation, I suppose every file and directory has to be carefully named to work? I understand .rb file itself needs to be in an 'api' directory, does the 'config.ru' file also go there? Or does it have to be named 'index.ru' specifically?

**Comment by m5o** [comment]
Hey @eterps 👋 
check out: https://github.com/zeit/docs/pull/1587

**Comment by mcsdevv** [comment]
As the ZEIT Now platform is focused on static frontends, we will not be adding a Sinatra example. As @m5o has shown, it is technically possible to do so but is not recommended.
