### ISSUE TITLE
Jekyll blog posts not working on production

### ISSUE THREAD

**Issue by baristaGeek** [vercel/vercel#3550]
Hello. When deploying a Jekyll project to know, despite the project being deployed successfully, the blog posts return a 404 error on production 

I've tried different things to make this work, and it's even working on Netlify, but not on Now. 

Removing bower.json and/or package-lock.json seems to be what solves the issue. Other things that I've been suggested around the web include making the blog posts' extension .md instead of .markdown, and having the necessary scripts in the package.json. I've already tried these things.

**Comment by jaikoo** [comment]
So while this isn't the perfect fix in that you won't have pretty urls, I've found that in my _config.yml appending the .html extension to all my permalinks means that when you build your site the correct links to my blog posts get generated. I was previously using Netlify though where it "just worked" and must of been configured to fallback to looking for a file with the .html extension.

**Comment by mcsdevv** [comment]
@baristaGeek apologies for the delay in getting to you on this - are you still experiencing this issue?

**Comment by styfle** [comment]
We don't use `bower.json` but it might be a problem with `package-lock.json` if the dependencies are corrupt. Typically you wouldn't have npm dependencies if you were using jekyll, you would instead have a `Gemfile.lock`.

Please [contact support](https://vercel.com/support/request) if you are still experiencing this issue so we can look at your specific deployment. Thanks!

**Comment by tristone13th** [comment]
I have the same problem, may be you can add a .html suffix on the url of the 404 page, then it will appear. I suggest it maybe a jekyll version issue?

**Comment by ZeldOcarina** [comment]
I have the same problem here, did anyone ever find a solution?

**Comment by tristone13th** [comment]
> I have the same problem here, did anyone ever find a solution?

you can workaround by add following line to the `_config.yaml`

```yaml
permalink: /:year/:month/:day/:slug:output_ext
```

note the `output_ext`, it is necessary and the key to resolve this problem.

**Comment by ZeldOcarina** [comment]
Yeah I actually resolved by prepending a frontmatter with the permalink to the HTML page.
Thanks a lot!
