### ISSUE TITLE
Build breaks when switching to a "--scripts-version" create-react-app fork

### ISSUE THREAD

**Issue by bitjson** [vercel/vercel#3551]
I'm using the `--scripts-version` option for `create-react-app` – it's a way to customize the webpack configuration without "ejecting". E.g. this will create a new project which supports [`react-monaco-editor`](https://github.com/react-monaco-editor/react-monaco-editor/issues/235) without requiring you to eject from `create-react-app` altogether:

```
npx create-react-app --scripts-version=@bitauth/react-scripts-bitauth-ide my-app
```

You can see what the [package.json looks like here](https://github.com/bitauth/bitauth-ide/blob/master/package.json#L6). Note it's exactly like the latest default for `create-react-app`, but the `react-scripts` dependency has been replaced by `@bitauth/react-scripts-bitauth-ide`.

Looking at [`frameworks.ts`](https://github.com/zeit/now/blob/b295ba83159713d5b16a28ee6478dbab7e43b84e/packages/now-static-build/src/frameworks.ts#L149-L205), Zeit Now only recognizes `create-react-app` if the user has `react-scripts` or `react-dev-utils`. One potential solution is to detect that one of my direct dependencies itself depends on `react-dev-utils`. Other than that, it would have saved me a lot of time if this repo included `now.json` examples for users who are having trouble with the project detection.

---

It took me a while to figure out [how to specify the output directory name in `now.json`](https://zeit.co/docs/runtimes#advanced-usage/advanced-static-builds-usage/configuring-the-build-output-directory-with-static-builds-runtime), so in case anyone else is searching, here's a working `create-react-app` config that doesn't rely on Zeit Now detecting your project:
```json
{
  "version": 2,
  "alias": ["example.com"],
  "builds": [
    {
      "src": "package.json",
      "use": "@now/static-build",
      "config": { "distDir": "build" }
    }
  ],
  "routes": [
    {
      "src": "/static/(.*)",
      "headers": { "cache-control": "s-maxage=31536000, immutable" },
      "continue": true
    },
    {
      "src": "/service-worker.js",
      "headers": { "cache-control": "s-maxage=0" },
      "continue": true
    },
    {
      "src": "/sockjs-node/(.*)",
      "dest": "/sockjs-node/$1"
    },
    {
      "handle": "filesystem"
    },
    {
      "src": "/(.*)",
      "headers": { "cache-control": "s-maxage=0" },
      "dest": "/index.html"
    }
  ]
}

```

**Comment by styfle** [comment]
When you create a new Project with Now CLI 17 or the GitHub Import, you'll be asked if the framework detect is correct and have the opportunity to change it.

You can also customize the Build Command and Output Directory.

See this blog post for more: https://zeit.co/blog/advanced-project-settings
