### ISSUE TITLE
Request: Add back minimal typescript example

### ISSUE THREAD

**Issue by Flaque** [vercel/vercel#3552]
There's no longer a minimal typescript example. Which, you'd think would be fine since typescript is almost entirely zero-config with @now/node, but that's not explicitly stated anywhere.

Without a minimal example, it's unclear how TS is being built. Since the only example is Gatsby, I assumed Gatsby was building the TS somehow.

**Comment by mcsdevv** [comment]
Closing as there are no longer any plans to implement this example. Instead, more complete, fully working applications will be created.
