### ISSUE TITLE
URL shorter using next.js / node.js / static builders and a simple custom routes configuration

### ISSUE THREAD

**Issue by delta-9** [vercel/vercel#3553]
Everything is in the title.
https://github.com/delta-9/shorturl

**Comment by mcsdevv** [comment]
Hey @delta-9, as the focus of the platform is on frontend development, with Serverless Functions being used to enhance functionality, we will not be adding this example. In the coming months, you can expect to see the examples reworked into fully functioning apps that will provide greater value.
