### ISSUE TITLE
Go date time is not coming up with an error

### ISSUE THREAD

**Issue by edineu** [vercel/vercel#3554]
Does anyone knows why this is coming up with an error:

![image](https://user-images.githubusercontent.com/5111209/65683936-ce0cbe00-e05e-11e9-9530-e2a6f169c263.png)

Need help to get the timer to show properly.

**Comment by styfle** [comment]
We fixed the wrong port being displayed for CRA in #3903.

You can try this out on the canary channel by installing `npm i -g now@canary`.
