### ISSUE TITLE
Sapper SSR Example

### ISSUE THREAD

**Issue by mcsdevv** [vercel/vercel#3555]
Currently, we only have an example for `sapper export`, that uses a static build. Ideally we would also show an example for a regular Sapper application as per zeit/now-examples#193 

This is not possible currently, however it will be once Sapper is able to generate serverless functions.

**Comment by janzheng** [comment]
Seems like the repo https://www.npmjs.com/package/now-sapper doesn't work to build Vercel anymore — could we get an official Vercel example on how to deploy Sapper SSR please?

**Comment by mcsdevv** [comment]
Hey @janzheng, thanks for raising this.

We now recommend using SvelteKit for SSR Svelte on Vercel, you can find an example of that [here](https://vercel.com/new/vercel/templates/svelte/sveltekit-boilerplate).

**Comment by janzheng** [comment]
Thanks! What should we do with legacy projects that we're sunsetting, but still need to be bumped or fixed to hum along, but we don't want to do a complete rewrite into SvelteKit?

**Comment by mcsdevv** [comment]
Hey @janzheng, we don't have any guidance as we do not maintain the `now-sapper` package.

With that said, and I do appreciate you are asking about projects you're not looking to perform a complete rewrite, we do provide a [migration guide](https://kit.svelte.dev/docs/migrating) which I'd hope wouldn't be too much work to make those changes.
