### ISSUE TITLE
Improvements on nuxt-static example

### ISSUE THREAD

**Issue by rlindskog** [vercel/vercel#3558]
- Right now, the `nuxt-static` example is using `nuxt generate` with `mode: 'spa'`. This makes every generated page just a normal spa, without any generated HTML.

- Also, there is an error where dynamic routes aren't handled properly on hard refreshes (because non-generated dynamic routes are supposed to [fallback to `spa`](https://nuxtjs.org/guide/routing#spa-fallback)). This can be solved by adding routes to `now.json` like so:

```
"builds": [
  { "src": "package.json", "use": "@now/static-build" }
],
"routes": [
  { "handle": "filesystem" },
  { "src": "/.*", "dest": "200.html" }
]
```
Without added routes (broken): https://rlindskog-static-4kkk80h0r.now.sh/posts/1
With added routes (solution): - https://rlindskog-static.now.sh/posts/1

**Comment by flozero** [comment]
i have dynamics routes generate on the generate but it's currently not working even with your configs...

**Comment by thibaultvanc** [comment]
Workink for me thanks !!
