### ISSUE TITLE
Not possible to set multiple Set-Cookie headers using flask

### ISSUE THREAD

**Issue by nbk2000** [vercel/vercel#3559]
Using the `zeit/now-examples/python-flask`
 project I added two cookies via `set_cookie()`. The result is only the first `Set-Cookie` header is sent by the server, the second is not. In the local Python environment both Set-Cookie headers are sent.

This code reproduces the bug.
```
from flask import Flask, Response, __version__
app = Flask(__name__)
@app.route('/', defaults={'path': ''})
@app.route('/<path:path>')
def catch_all(path):
    resp = Response()
    resp.set_cookie('COOKIE_1=1; Max-Age=3600; path=/; secure')
    resp.set_cookie('COOKIE_2=6; Max-Age=3600; path=/; secure; HttpOnly')
    return resp
```

Thanks

**Comment by mcsdevv** [comment]
Closing as this example has been removed due to the focus on static frontends.

**Comment by urmichm** [comment]
What is the solution to the problem?

**Comment by Dawe-SE** [comment]
This is still an issue

`@app.route("/authorize")
def authorize():
  steam_id_of_user =  "".join(d for d in request.args["openid.claimed_id"] if d.isdigit())
  res = make_response(render_template("index.html"))
  res.set_cookie("steamID", steam_id_of_user)
  url = f'https://steamcommunity.com/profiles/{steam_id_of_user}/inventory/json/730/2'
  #https://steamcommunity-a.akamaihd.net/economy/image/-bla bla

  response = requests.get(url)
  data = json.loads(response.text)
  if data['success'] == "true":
    items = data['rgDescriptions']
    i = 0
    for item in items:
      res.set_cookie(f"itemNr{i}", item["market_name"], item["classid"], item["icon_url"])
      i += 1

  return res`
