### ISSUE TITLE
Next.js with server-side URL routing

### ISSUE THREAD

**Issue by friedjoff** [vercel/vercel#3560]
Right now it is not possible to implement server-side URL routing based on @now/next builder. This [simple example](https://gist.github.com/friedjoff/7171860fd38dcbb68f8bfc5139ab45a3) shows how it would be implemented on Zeit Now v1 and this [Spectrum conversation](https://spectrum.chat/zeit/now/next-js-with-server-side-url-routing~563de104-b6a6-45d9-9348-b8bb9b92cbf2) has more details.

Relying on routes like "/w/*" should not be required, because this would leak implementation details to the user.

**Comment by coetry** [comment]
Next.js handles server-side routing in development as well as production now via `next dev`. Even if you are using `now dev`, it will invoke the native `next dev` command.
