### ISSUE TITLE
dotnetcore v2

### ISSUE THREAD

**Issue by wahmedswl** [vercel/vercel#3561]
Hi, it would be great to include dotnetcore example for v2.

Thanks

**Comment by mcsdevv** [comment]
I'm closing this issue as there are currently no plans to add support for the .NET runtime.

**Comment by betsegaw** [comment]
> @hotyes Docker is not supported on Now 2.0; correct.
> 
> Newer accounts will not be able to use Now 1.0, either. But we are working on .NET for Now 2.0. Stay tuned.

Anything new on this front @timothyis ?

**Comment by mcsdevv** [comment]
Hey @betsegaw, I'm afraid there are no plans for a .NET Builder on ZEIT Now 2.0 currently. However, you can always take a look at creating a [Community Runtime](https://zeit.co/docs/runtimes#advanced-usage/community-runtimes), you can find more information on this [here](https://github.com/zeit/now/blob/master/DEVELOPING_A_RUNTIME.md). @Timer mentioned recently he'd be interested in helping someone get started creating it.

**Comment by styfle** [comment]
There was mention of a Community Runtime in #2831 but it looks like it hasn't been updated in a year.

The relevant comment is https://github.com/zeit/now/issues/2831#issuecomment-516562604
