### ISSUE TITLE
Probot Example

### ISSUE THREAD

**Issue by tunnckoCore** [vercel/vercel#3563]
I thought it would be just `src: index.js` which index `module.exports` a function that gets a Probot instance.

But it's not exactly that way. I also switched to `src: package.json` where I have `now-start` which runs the probot, but seems to not work.

**Comment by styfle** [comment]
This was fixed in https://github.com/probot/probot/pull/1130

Documentation is here: https://probot.github.io/docs/deployment/#zeit-now

**Comment by boredland** [comment]
Hi there! There doesn't seem to be a documentation for vercel inside the probot docs. Is this still supported?
