### ISSUE TITLE
Flask example not found

### ISSUE THREAD

**Issue by dnk8n** [vercel/vercel#3586]
Hi.

In another PR, there as this comment - https://github.com/zeit/now-examples/issues/163#issuecomment-500421522

It seems that things have moved around, now the flask examples are not found. Where can I find them?

**Comment by styfle** [comment]
Hi @dnk8n 

There is an example in the documentation here: 

https://zeit.co/docs/runtimes#advanced-usage/advanced-python-usage/web-server-gateway-interface

**Comment by dnk8n** [comment]
Thanks so much.

I think I eventually found it. I got confused by a message in the docs
saying that builders in now.json was getting deprecated...

Anyway, I made this commit and it worked like a charm -
https://gitlab.com/dnk8n/any_roman/commit/72f6b2cbdfc216e4377670a443310a0845b10a81

In case anyone cares for a basic example.

Example of it live: http://api.dnk8n.dev/int_to_roman/12345 where 12345 can
be any positive int.

**Comment by styfle** [comment]
Indeed the [`builds`](https://zeit.co/docs/configuration/#project/builds) property is deprecated.

Instead you should create an `/api` directory and then you don't need to define `builds` in now.json.

Each file in `/api` will create a serverless function similar to `"builds": "api/**/*.py"`.

**Comment by dnk8n** [comment]
Seems more complicated than a json definition. Your library now dictates my
repo's file structure. What is the benefit of this?

If not the correct channel, please forgive. I am just passing by and don't
have major time to invest in discussing such architecture. I trust there is
good reason (and that it is documented?).

Anyway, impressed with the service as defined by the commit pasted above.
Simple, explicit and understandable even without looking anywhere else for
explanation.

Appreciate your feedback and links provided.

**Comment by styfle** [comment]
I think you'll find the best use case is static files such as `index.html` with serverless functions as your API. Each file is a separate function that scales independently. You don't need Flask at all because ZEIT Now does routing for you.

https://zeit.co/docs/runtimes#official-runtimes/python

You visit `/api/user` or `/api/login` and those will map to `/api/user.py` and `/api/login.py`.

I would suggest reading the general introduction here: https://zeit.co/docs/v2/introduction
Also read the serverless functions introduction here: https://zeit.co/docs/v2/serverless-functions/introduction

**Comment by dnk8n** [comment]
Much appreciated. Will make my way through docs and try apply it to my
little toy example linked before.

My aim for it was to supply some basic infrastructure as code to
demonstrate the function (for anyone else who might want to deploy it).

What you describe sounds like a good idea if entire API is defined in one
repo. But I stand to be corrected. Will post comment on adjustments made
(as exams to future readers, just in case it could help illustrate the
difference).
