### ISSUE TITLE
disable automatic static file deployment

### ISSUE THREAD

**Issue by devsnek** [vercel/vercel#3595]
I am trying to deploy an application to zeit which only should be using files in the `api` directory. There are other files in the directory which are deployed separately (to github pages), and ideally they would be ignored by zeit. Unfortunately, zeit automatically packages them up and serves a second version of my site, which is not ideal.

I have tried routing everything except my api files to a 404 with `{ "src": "/.*", "status" 404, "continue": false }`, but this rule appears to do nothing.

**Comment by styfle** [comment]
Hi @devsnek 

The route you wrote is a wildcard so it would match everything. I don't think you want to do that if you need your APIs to continue working.

Instead, you could add a build script to your package.json file to generate static files in a public directory. The public directory will automatically be used instead of the files in the root directory.

Try this package.json:

```json
{
  "private": true,
  "scripts": {
    "build": "mkdir public && echo 'Hello World' > public/index.html"
  }
}
```

**Comment by devsnek** [comment]
@styfle i routed it last:

```json
{
  "name": "engine262-api",
  "scope": "engine262",
  "version": 2,
  "routes": [
    {
      "src": "/gist",
      "dest": "/api/gist.js",
      "headers": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "*"
      }
    },
    {
      "src": "/download",
      "dest": "/api/download.js"
    },
    {
      "src": "/.*",
      "status": 404,
      "continue": false
    }
  ],
  "env": {
    "GH_TOKEN": "@gh_token"
  }
}
```

i want literally everything else to be a 404.

**Comment by styfle** [comment]
There is no `continue: false`.

You'll need to set a `dest` on the 404 route like the docs show here: https://zeit.co/docs/configuration/#routes/advanced/custom-404

**Comment by styfle** [comment]
Probably a better way to handle this is to add a `.nowignore` file to specify the files that should not be uploaded. See this guide https://zeit.co/guides/prevent-uploading-sourcepaths-with-nowignore

**Comment by devsnek** [comment]
I will try a nowignore, but I'm curiously why putting status: 404 doesn't work. Is it a bug in the routing?

**Comment by styfle** [comment]
@devsnek No it is working correctly.

The status code was set to 404 but you didn't rewrite to a different destination so the static file was still served as the contents.

You can set arbitrary status codes on any page using `routes`.

![image](https://user-images.githubusercontent.com/229881/72469035-901ddc00-37ac-11ea-8f06-08a4b2e713b4.png)

**Comment by devsnek** [comment]
@styfle this doesn't work either

```json
{
  "name": "engine262-api",
  "scope": "engine262",
  "version": 2,
  "routes": [
    {
      "src": "/gist",
      "dest": "/api/gist.js",
      "headers": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "*"
      }
    },
    {
      "src": "/download",
      "dest": "/api/download.js"
    },
    {
      "src": "/.*",
      "dest": "/does-not-exist"
    }
  ],
  "env": {
    "GH_TOKEN": "@gh_token"
  }
}

```

**Comment by devsnek** [comment]
actually to be more precise, it works with `now dev` but does not work in production.

**Comment by devsnek** [comment]
using `.nowignore` removes all the static files but results in the home page being a file browser.

![](https://gc.gy/46827826.png)

**Comment by styfle** [comment]
It looks like you removed the 404 status code.

```json
{
  "name": "engine262-api",
  "scope": "engine262",
  "version": 2,
  "routes": [
    {
      "src": "/gist",
      "dest": "/api/gist.js",
      "headers": {
        "Access-Control-Allow-Origin": "*",
        "Access-Control-Allow-Headers": "*"
      }
    },
    {
      "src": "/download",
      "dest": "/api/download.js"
    },
    {
      "src": "/.*",
      "status": 404,
      "dest": "/does-not-exist"
    }
  ],
  "env": {
    "GH_TOKEN": "@gh_token"
  }
}
```

Please see the documentation https://zeit.co/docs/configuration/#routes/advanced/custom-404

**Comment by styfle** [comment]
> using .nowignore removes all the static files but results in the home page being a file browser.

This is the directory listing https://zeit.co/docs/directory-listing

You'll see that when a directory doesn't contain an index file.

That's why my first comment suggested generating the index.html file in a build script.

**Comment by devsnek** [comment]
alright adding `status: 404` finally works. But why do I need to add `status: 404` if `/does-not-exist` already does not exist? `now dev` seems to do the right thing, so I guess there's a bug in your production routing logic?

Also your documentation that you keep linking to is incredibly terse, and relies on examples instead of actually explaining how your system behaves. You should start by explaining what the behaviour actually is, and then add examples as needed.

**Comment by styfle** [comment]
Thanks for the feedback! I'll forward it to the team.

**Comment by styfle** [comment]
Is there a specific documentation page you find confusing?

What information would have been better to help you solve this problem?

Thanks!
