### ISSUE TITLE
Zeit deploy hooks for gatsby are not using build cache

### ISSUE THREAD

**Issue by dmerckx** [vercel/vercel#3600]
Whenever I make a new deployment by means of a git commit or via the now cli the build process will take the gatsby .cache folder into account.

At the start of the build process it will show something like this:
Build runtime installed: 412.484ms
Build cache found [44.40 MB, 34674 files]
Build cache unpacked: 1856.891ms
Installing dependencies...

However, when I use a deploy hook the cache is not taken into account. The lines 'build cache found' and 'build cache unpacked' are never printed.

I reproduced this behaviour by creating a [new gatsby repository](https://github.com/dmerckx/Now-gatsby-caching-test/commits/master) following the 2 steps described in the [docs](https://zeit.co/guides/deploying-gatsby-with-now). 

Whenever I made a regular commit (simply modifying the README file) the cache was used, when I used a deploy hook the cache was not used. 

Side note: for some reason the build actually failed when making a new commit, but that is unrelated to this issue (I noticed the same behaviour in other projects without failing builds).

**Comment by styfle** [comment]
Hi @dmerckx 

Thanks for reporting this issue!

Indeed, the cache is not used for deploy hooks. We'll get this fixed, thanks!

**Comment by akrock** [comment]
Looking to use the web-hooks to trigger deployments for a new project I'm working on, and this will certainly cause worse performance when we have to deploy from web-hook. 

Looking forward to this being fixed.

**Comment by wezzle** [comment]
@styfle any update on this? I just noticed this myself and we have a website with a lot of images that needs to be triggered from a webhook by the CMS. Currently every build takes 20+ minutes.

In the mean time: is there a folder we can write to that is always cached? I'm fine with copying the Gatsby .cache folder to a different folder post build and copying from that folder back into .cache pre-build.

**Comment by styfle** [comment]
This is being worked on by @rdev in #3953 and #3966 and will be available in the next stable release.

**Comment by styfle** [comment]
This has been fixed, thanks!
