### ISSUE TITLE
How to handle SPA fallback with API

### ISSUE THREAD

**Issue by mistakenelf** [vercel/vercel#3602]
Developing this app in svelte using parceljs for bundling. Also have serverless functions running, `now dev` works fine with routing, but once deployed and reload on a route other than / I get a 404 page and not entirely sure what the now.json should look like. 

https://github.com/knipferrc/plate-app

**Comment by tehpsalmist** [comment]
I too have this problem, and I'm curious to know if the Now team is aware of this issue and discussing a solution. This seems like a very desirable "feature" (supporting SPA routing in zero config), so I'm hopeful that this is on the roadmap somewhere. At the very least, where can I go to see what progress (if any) there is on this feature?

**Comment by AndyBitz** [comment]
@knipferrc @tehpsalmist Thanks for reporting. You can add something like this to your `now.json` file to make sure all non-api requests are going to `/` but all existing files are still served. Please try and let me know if everything works as intended.

```json
{
  "routes": [
    {
      "handle": "filesystem"
    },
    {
      "src": "^(?!\\/api).*",
      "dest": "/"
    }
  ]
}
```

Usually we are detecting the default routes for svelte, however, that's only in combination with `sirv-cli`. We'll look into further improvements.

**Comment by mistakenelf** [comment]
@AndyBitz, gave that a try, unfortunately when running `now dev` with this, nothing loads.

**Comment by tehpsalmist** [comment]
yes, I found that unless you program every api route and a full SPA routing configuration, you can't have both `now dev` and a working SPA in production. I'm using parcel + react for my setup btw.

**Comment by mistakenelf** [comment]
@tehpsalmist I also use parcel for my app. So your saying explicitly add each route to the config and it should work? Any example as to what that looks like with the api routes?

**Comment by tehpsalmist** [comment]
yeah, here's an api route example:

```
"routes": [
    {
      "src": "/api/inspire/(?<index>[^/]+)",
      "dest": "api/inspire/[index].ts?index=$index",
      "headers": {
        "Access-Control-Allow-Origin": "*"
      }
    },
    ...
]
```

Obviously this is all documented elsewhere, but it's allowing for the directory structure and file naming to create the endpoint and query param of `index` (could be any name though, index is my example). endpoint code would be in /api/inspire/[index].ts (brackets are actual filename characters).

Of course, as clever as this is, it's not very fun to configure for _every_ endpoint I want to offer, so this SPA issue is turning out to have very invasive consequences in my workflow.

**Comment by mistakenelf** [comment]
Just to close the loop here, ended up switching to hash routing for now until there is a better solution.

**Comment by AndyBitz** [comment]
@knipferrc we've just launched [Advanced Project Settings](https://zeit.co/blog/advanced-project-settings), you can now go to the dashboard and choose the framework that you are using for your project. Once you've saved them and linked your project locally by deploying you can use `now dev` with those settings.

I think this should work for you:

![image](https://user-images.githubusercontent.com/16088670/73992849-b3255100-4950-11ea-9dea-95c0298be4b3.png)

Please let me know if that works for you.

**Comment by tehpsalmist** [comment]
@AndyBitz would it be "good practice" to provide `npm start` as the Development Command? Will that achieve the experience I'm looking for if my npm start script is the parcel command you depicted above? Thanks for rolling out this feature!

**Comment by AndyBitz** [comment]
@tehpsalmist there shouldn't be any issues with using `npm start` as your dev command. However, you'll need to make sure that the `$PORT` part is passed on correctly, otherwise `now dev` wouldn't know where to rewrite to.

**Comment by devotox** [comment]
i think this should work using the new [negative lookahead syntax](https://vercel.com/docs/errors/error-list#invalid-route-source-pattern)

```
  "rewrites": [
    {
      "source": "/((?!api).*)",
      "destination": "/index.html"
    }
  ],


  "headers": [
    {
      "source": "/((?!api).*)",
      "headers": [
        {
          "key": "Cache-Control",
          "value": "public, max-age=86400, s-maxage=86400, stale-while-revalidate"
        }
      ]
    }
  ]
```
