### ISSUE TITLE
Nuxt.js Universal / SSR example

### ISSUE THREAD

**Issue by homerjam** [vercel/vercel#3608]
Please could you create (or modify the existing) a Nuxt.js example that supports `universal` mode with SSR.

Thanks

**Comment by jake-101** [comment]
check out this repo, it also has CDN-based pre-rendering or no pre-rendering set up.
https://github.com/jake-101/vuejs-la-zeit-nuxt

**Comment by bigsee** [comment]
@jake-101 seems to return 502? Opened an issue [here](https://github.com/jake-101/vuejs-la-zeit-nuxt/issues/1).

**Comment by homerjam** [comment]
Thanks @jake-101 this example uses a builder (now deprecated) is there an example anywhere that won't break in future?

**Comment by styfle** [comment]
There is no official Nuxt.js builder but there is a Community builder here:

https://github.com/nuxt/now-builder
