### ISSUE TITLE
Clarification on builds deprecation

### ISSUE THREAD

**Issue by homerjam** [vercel/vercel#3610]
Hi

Could you elaborate on your plans to deprecate `builds` in the `now.json` config file?

What will happen to existing projects with complex monorepo style setups?

Thanks

**Comment by styfle** [comment]
Hi @homerjam 

Indeed, [`builds` is deprecated](https://zeit.co/docs/configuration#project/builds). We are working on improving monorepo support for zero config deployments, such that you could connect a single GitHub repo to multiple ZEIT Projects.

**Comment by paulogdm** [comment]
Just to be clear, feel free to use `builds` if you need to. Even as a deprecated property, it should work for monorepos. As @styfle said, however, we do plan to deliver a better experience directly in our UI with the same ease of deployments that [Zero Config](https://zeit.co/blog/zero-config) can provide.
