### ISSUE TITLE
Example for express?

### ISSUE THREAD

**Issue by ninest** [vercel/vercel#3619]
How do I deploy an app that uses express? None of the tutorials online work. Whenever I try deploying an express app, it gets stuck at the "Queued" step.

**Comment by styfle** [comment]
Hi @themindstorm 

You don't need express because ZEIT Now already adds [Node.js Helpers](https://zeit.co/docs/runtimes#official-runtimes/node-js/node-js-request-and-response-objects) to the serverless functions in your `/api` directory.
