### ISSUE TITLE
Use .env when available by default

### ISSUE THREAD

**Issue by glennreyes** [vercel/vercel#362]
It would be useful if we could just run `now` and now would detect and use `.env` automatically. Right now, we have to run `now -E` to include it by default.

Any thoughts?

**Comment by jamo** [comment]
I'm a bit hesitant for reading and sending over the secrets over with no or little warning to users.
Maybe we could use `now.json` to automatically always the .env file 🤔

**Comment by timneutkens** [comment]
In `now.json` add this:
```
{
  "dotenv": true
}
```

alternatively:
```
{
  "dotenv": ".prod.env"
}
```

**Comment by glennreyes** [comment]
Thanks @timneutkens! That's really helpful

**Comment by jerrygreen** [comment]
@timneutkens this looks cool but does it still work? I don't see it in [documentation](https://zeit.co/docs/v2/deployments/environment-variables-and-secrets), I've tried it – my build fails after I add this line
