### ISSUE TITLE
Module not found cannot resolve `@/components/App`, TypeScript > 3.7 within the last month

### ISSUE THREAD

**Issue by tsujp** [vercel/vercel#3620]
I cannot use `now dev` or `now` to run my application anymore as it doesn't seem to respect a previously working tspath setting which aliases `@` to `src` for a create-react-app.

Is there an example of a working setup anywhere for Now's current environment?

```
/usr/lib
├── now@16.7.3
├── npm@6.13.6
├── ts-node@8.6.2
├── typescript@3.7.5
└── typescript-language-server@0.4.0
```

```
"@now/node": "^1.3.5"
```

**Comment by mcsdevv** [comment]
Hey @tsujp, sorry for the delay in getting to this. Are you still having issues with this? If so, please provide a reproducible example and we will investigate.

**Comment by mcsdevv** [comment]
Closing due to no reply within 7 days.
