### ISSUE TITLE
Custom domain without HTTPS?

### ISSUE THREAD

**Issue by debugpoint136** [vercel/vercel#363]
Is it possible to now deployment aliased to a custom domain without https?
Inside node.js app I invoke another API request, which is HTTP, so getting this error -

```
**Mixed Content:** The page at 'https://repeatbrowser.org/consensus' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://blahblah.com'. **This request has been blocked; the content must be served over HTTPS.**
```

**Comment by hugomd** [comment]
@debugpoint136 It sounds like you have a frontend and backend? If that's the case, you could proxy your frontend request via your backend, which would HTTPS.

From the information you've given, it sounds like this is what you currently have:
```
frontend -> non-https site
```

What you'd want is:
```
frontend -> backend -> non-https site
```

Does that make sense? If you have any questions, or if I've interpreted the situation wrongly, let me know ✌️

**Comment by debugpoint136** [comment]
Thanks @hugomd ..! This really helped. Makes total sense. I implemented exactly what you advised and it fixes the issue. 

Cheers!

**Comment by hugomd** [comment]
@debugpoint136 Glad I could help ✌️

**Comment by AlexandreBonaventure** [comment]
Is there a easy way to setup a proxy for this use-case(request insecure api) using serve package ?
