### ISSUE TITLE
Jekyll example seems outdated

### ISSUE THREAD

**Issue by kertof** [vercel/vercel#3634]
In the Jekyll example (https://github.com/zeit/now/tree/master/examples/jekyll) the readme mentions a `package.json` file which doesn't exist, with a build rule to adapt jekyll to the defaults of Zeit.
What build command does Zeit run for Jekyll sites?

Thanks!

**Comment by styfle** [comment]
Hi @kertof 

The package.json is no longer needed. The default build command is `jekyll build`.

I'll make sure to update the readme, thanks!
