### ISSUE TITLE
No native build was found for runtime - ABI=72

### ISSUE THREAD

**Issue by leonardoleenen** [vercel/vercel#3635]
Hi Guys, I working on a app with Firebase + NextJS + Redux (simple). But when I try to deploy get this error: 

`2020-01-22T09:27:43.850Z	undefined	ERROR	Uncaught Exception 	{"errorType":"Error","errorMessage":"No native build was found for runtime=node abi=72 platform=linuxglibc arch=x64","stack":["Error: No native build was found for runtime=node abi=72 platform=linuxglibc arch=x64","    at Function.load.path (/var/task/node_modules/node-gyp-build/index.js:56:9)","    at load (/var/task/node_modules/node-gyp-build/index.js:18:30)","    at Object.<anonymous> (/var/task/node_modules/leveldown/binding.js:1:43)","    at Module._compile (internal/modules/cjs/loader.js:956:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)","    at Module.load (internal/modules/cjs/loader.js:812:32)","    at Function.Module._load (internal/modules/cjs/loader.js:724:14)","    at Module.require (internal/modules/cjs/loader.js:849:19)","    at require (internal/modules/cjs/helpers.js:74:18)","    at Object.<anonymous> (/var/task/node_modules/leveldown/leveldown.js:3:17)"]}END RequestId: ae110934-9e18-4cac-939d-931971d71a0b
Duration: 490.02 ms  Billed Duration: 500 ms  Memory Size: 1024 MB  Max Memory Used: 31 MB	
Unknown application error occurred`

This is my packege.json 

```javascript
{
  "name": "outtripper-app",
  "version": "0.1.0",
  "private": true,
  "jest": {
    "transform": {
      "^.+\\.ts?$": "babel-jest"
    }
  },
  "scripts": {
    "tailwind:main": "tailwind build statics/style/style.src.scss -c  statics/style/tailwind.js -o statics/style/style.css",
    "tailwind:customer": "tailwind build statics/style/customerapp.src.scss -c  statics/style/tailwind.js -o statics/style/customer.css",
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "export": "next export",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:coverage": "jest --coverage"
  },
  "dependencies": {
    "@babel/preset-typescript": "^7.8.0",
    "@zeit/next-css": "^1.0.1",
    "@zeit/next-sass": "^1.0.1",
    "axios": "^0.19.0",
    "dotenv": "^8.2.0",
    "firebase": "^7.5.0",
    "firebase-admin": "^8.9.0",
    "lunr": "^2.3.8",
    "moment": "^2.24.0",
    "next": "9.1.3",
    "next-compose-plugins": "^2.2.0",
    "next-redux-wrapper": "^4.0.1",
    "next-runtime-dotenv": "^1.2.0",
    "node-sass": "^4.13.0",
    "pouchdb": "^7.1.1",
    "pouchdb-find": "^7.1.1",
    "react": "16.11.0",
    "react-dom": "16.11.0",
    "react-hook-form": "^3.27.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "tailwindcss": "^1.1.3",
    "underscore": "^1.9.1",
    "uuid4": "^1.1.4",
    "voucher-code-generator": "^1.1.1"
  },
  "devDependencies": {
    "@babel/plugin-transform-modules-commonjs": "^7.8.0",
    "@types/enzyme": "^3.10.4",
    "@types/enzyme-adapter-react-16": "^1.0.5",
    "@types/jest": "^24.0.25",
    "@types/node": "^12.12.7",
    "@types/react": "^16.9.11",
    "@typescript-eslint/eslint-plugin": "^2.6.1",
    "@typescript-eslint/parser": "^2.6.1",
    "babel-core": "^6.26.3",
    "babel-jest": "^24.9.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "eslint": "^6.6.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.16.0",
    "eslint-plugin-react-hooks": "^1.7.0",
    "jest": "^24.9.0",
    "ts-jest": "^24.3.0",
    "typescript": "^3.7.4"
  }
}
```
I google it but cannot find this error. I got one clue  ABI=72 and leveldown.. sorry. After spent many hours only find this.

**Comment by styfle** [comment]
Hi @leonardoleenen 

You probably have a dependency that doesn't work with the latest Node version.

You can try pinning to a specific version of Node like `10.x`.

See the following documentation: https://zeit.co/docs/runtimes#official-runtimes/node-js/node-js-version

**Comment by leonardoleenen** [comment]
Yes, I do that. If I remove firebase Lib from my project, works fine. In localhost / dev working fine indeed, but when I try to deploy y zeit I got this error. I still working on fix that (9 days)

**Comment by leonardoleenen** [comment]
After a lot of work, I realized that the problem was with PouchDB Library and not with Firebase. PouchDB has issues in some versions of  Node 10.x. 

The recommendation is to use pouchdb-brower BUT( a big but) when I do that a got this error: ReferenceError: fetch is not defined in build runtime. 

nextJS and PouchDB are not good friends. My Solution? I let use PouchDB  :-(

**Comment by styfle** [comment]
I haven't tried PouchDB but it looks like its a browser-only database.

So you could add a script to the page:

```html
<script src="https://cdn.jsdelivr.net/npm/pouchdb@7.1.1/dist/pouchdb.min.js"></script>
```
