### ISSUE TITLE
Cannot Deploy Python Runtime

### ISSUE THREAD

**Issue by ANPULI** [vercel/vercel#3638]
Hi,

I wanted to set up a simple Python crawler so I resorted to the **Python runtime**. When I tried to run the demo from the [official documentation](https://zeit.co/docs/runtimes#official-runtimes/python), it turned out that the demos all failed.

I followed exactly the same procedure, and used `now dev` to build locally. When I attempted to visit http://localhost:3000/api/, it gave me a `502` error as follows. I tried all three examples and none of them worked.

![image](https://user-images.githubusercontent.com/26131764/72917564-08713800-3d7f-11ea-841e-0faa2531d57a.png)

There went the second problem when I tried to `now` it to check if it was a local error, but it seemed zeit was inaccessible.

![image](https://user-images.githubusercontent.com/26131764/72917706-4a9a7980-3d7f-11ea-977b-bea3b2580e93.png)

Thank you very much!

**Comment by styfle** [comment]
Hi @ANPULI 

I tried the example myself and was able to deploy to production with `now`.

- Deployment: https://py-example.now.sh/api
- Source Code: https://py-example.now.sh/_src

But you're right, it is failing with `now dev`. I get the following

> ModuleNotFoundError: No module named 'api.index'

Thanks for reporting this issue!

**Comment by ANPULI** [comment]
Thank you very much! I deployed it with Github and it worked now.
