### ISSUE TITLE
Upload completion percentage never hits 100%

### ISSUE THREAD

**Issue by hormesiel** [vercel/vercel#3645]
It's a minor issue, but it's been here for several releases already and hasn't been fixed yet so I guess it hasn't been reported yet.

When creating a new deployment the `Upload` step never hits 100% even when it's done :
![image](https://user-images.githubusercontent.com/1585006/72972051-01701700-3dcb-11ea-9bab-061f28008418.png)

**Comment by styfle** [comment]
We removed the progress bar for 2.0 uploads since it is only used for uploading modified files.

Did this fix the issue for you?

**Comment by hormesiel** [comment]
Yep, closing this issue since it's no longer relevant. Thanks @styfle
