### ISSUE TITLE
Tor and IPFS Support

### ISSUE THREAD

**Issue by AlicanC** [vercel/vercel#3649]
Would be cool if deployed websites were accessible on [Tor](https://2019.www.torproject.org/docs/onion-services.html.en) (with random or user-provided v2/v3 .onion domains) and on [IPFS](https://ipfs.io/) (using [ipfs addresses](https://github.com/ipfs/in-web-browsers/blob/master/ADDRESSING.md)).

**Comment by styfle** [comment]
Thanks for the suggestion! Let's move this discussion to https://github.com/orgs/vercel/discussions/80

**Comment by ghost** [comment]
I am interested in the Tor onion server support—and not IPFS, which is what the mentioned issue is about. This Tor campaign piqued my interest: https://blog.torproject.org/more-onions-porfavor

**Comment by arnav-kr** [comment]
Any further updates?

**Comment by janoschp** [comment]
> Thanks for the suggestion! Let's move this discussion to #4349.

Any updates on this? Issue 4349 doesn't exist @styfle

**Comment by solanarapist** [comment]
No updates.
