### ISSUE TITLE
Deployment under wrong name when using `now`

### ISSUE THREAD

**Issue by tavurth** [vercel/vercel#3656]
First, now is awesome, I'm loving it so far!
Thank you for making such a helpful product.

**The issue**
I'm running a Next.js deployment, and in my `now.json` file I have the following:
```js
{
  "functions": {
    "pages/**/*.js": {
      "memory": 128,
      "maxDuration": 5
    }
  }
  ...
}
```

I want  to restrict memory usage of all pages to 128MB.

However, now when I run `now --prod` I get a project named `pages` created in my now account, rather than the project using the `package.json` or even `now.json` name.

`now.json`
```js
{
  "name": "my-name",
  ...
}
```

Unfortunately still deploys under the project name "Pages"
I'm having to use github to deploy any changes because of this.

Hope we can find a solution!

**Comment by styfle** [comment]
Hi @tavurth 

I was unable to reproduce this issue. My deployment used the `name` property defined in `now.json`.

Can you share which version of Now CLI you're using with  `now --version`?

Also try `npm i -g now@latest` to see if that fixes it.

Thanks!

**Comment by tavurth** [comment]
Hi @styfle, thanks for the fast feedback. I'm running
```bash
now --version
16.7.3
```

After leaving my project for a few hours and after trying to create a minimal example everything seems to be working again. I'll close this issue but will post here if I run into the same issue again in future.

**Comment by msdinit** [comment]
If anybody stumbles upon this issue from google, `name` property seems to have been deprecated:
https://github.com/zeit/now/pull/3690
