### ISSUE TITLE
Now dev caches public folder

### ISSUE THREAD

**Issue by ivan-kleshnin** [vercel/vercel#3659]
# Bug report

## Describe the bug

Now Dev server doesn't pick up changes in `public` after `$ now dev` was run.

#### Step-1

1. `create-next-app sandbox`
2. `sandbox $ now dev`
3. Access `localhost:3000/favicon.ico`
4. It works

#### Step-2

1. Now copy `public/favicon.ico` file to `public/favicon2.ico` 
2. Access `localhost:3000/favicon2.ico`
3. See `404 Not Found` NextJS error instead of a file!

#### Step-3

1. Stop and run server again
2. Access `localhost:3000/favicon2.ico` 
3. It works again

## Expected behavior

It looks like `$ now dev` caches what's exist in `public` at startup and ignores all filesystem changes after that. I don't think it's an appropriated behavior for a static server though I assume it may be some part of serverless-specific optimizations of `now dev`. Some clarification would be helpful.

## System information

- OS: maOs
- Browser: Chrome
- Version of Next.js: 9.2.1
- Version of Now: 16.7.3

## Notes

1. `$ next dev` command does not share this behavior (changes in FS are shown immediately).

2. `static` folder does not share this behavior (changes in FS are shown immediately).

**Comment by alexander-r-jaimy** [comment]
I'm experiencing same behavior. Renaming images inside some nested folder in /public results in Not found by server

**Comment by codingbeans** [comment]
Same thing happens when you switch from `next dev` to `next start`.
This is very confusing especially when you are dynamically creating files to the `public` folder and some pages are accessing them. Everything works fine in dev mode but fail in production mode

**Comment by itcastzm** [comment]
> Same thing happens when you switch from `next dev` to `next start`.
> This is very confusing especially when you are dynamically creating files to the `public` folder and some pages are accessing them. Everything works fine in dev mode but fail in production mode

I have the same problem. 
Do you have a solution？

**Comment by codingbeans** [comment]
> > Same thing happens when you switch from `next dev` to `next start`.
> > This is very confusing especially when you are dynamically creating files to the `public` folder and some pages are accessing them. Everything works fine in dev mode but fail in production mode
> 
> I have the same problem.
> Do you have a solution？

Using `next: 9.2.1` with `static` folder works for me. But it's just a workaround.

**Comment by lobnico** [comment]
bump.. :'(

**Comment by gomcodoctor** [comment]
same issue here, my cpanel SSL fail to install because nextjs return validation file not found

**Comment by styfle** [comment]
Thanks @ivan-kleshnin for the repros steps!

I tried with the latest versions and this is working as expected with both `vercel dev` and `next dev`.

- OS: macOS
- Browser: Chrome
- Version of Next.js: 10.0.3
- Version of Vercel: 21.0.1

Try `npm i -g vercel@latest`, thanks!
