### ISSUE TITLE
Improve UX/DX of `now alias`

### ISSUE THREAD

**Issue by timneutkens** [vercel/vercel#366]
After discussing on slack I had the following idea:

Right now we do a client side DNS check only. Because DNS is not propagated right away it usually shows a message saying something like: records not verified, please try again later.

What we want to do is this:

1. We check local DNS (same as we do at the moment)
2. We check the records on a specific nameserver

And then show a message is they are out of sync,

We should still fail it, just show why it fails.
And if it was configured correctly on ZEIT.world or not, say, failed propagation because of dns caching would be transparent to the user this way.

cc @jamo @OlliV

**Comment by OlliV** [comment]
😍

**Comment by OlliV** [comment]
If the user is using zeit.world and the domain is verified already then you know it's a propagation issue. Though if we'd always do both of these checks we could tell if it's a propagation issue even if the user is not using zeit.world.

**Comment by Dids** [comment]
While #530 is technically a duplicate, it's more about the verification messages themselves, as not everyone knows how DNS propagation works, or even what it is. It should be made very clear that it usually just takes time (especially with newly added domains), and that they should simply try again later.

**Comment by codeofsumit** [comment]
aha!
So this:
```
now alias https://dist-ntosjmcxvw.now.sh medaku.io
> medaku.io is a custom domain.
> Verifying the DNS settings for medaku.io (see https://zeit.world for help)
> Detected zeit.world nameservers! Configuring records.
> DNS Configured! Verifying propagation…
> Error! > We configured the DNS settings for your alias, but we were unable to verify that they've propagated. Please try the alias again later.
```

is no error I should spend an hour researching?

**Comment by mineiro** [comment]
I'm experiencing the same issue here. The domain is using zeit.world and is already verified.

```
▲ ~/C/iar-ghost at (instituto*) now alias
> Assigning alias blog.iar.org.br to deployment...
> blog.iar.org.br is a custom domain.
> Verifying the DNS settings for blog.iar.org.br (see https://zeit.world for help)
> Detected zeit.world nameservers! Configuring records.
> DNS Configured! Verifying propagation…
> Error! > We configured the DNS settings for your alias, but we were unable to verify that they've propagated. Please try the alias again later.
```

Haven't had this issue a few days ago for the same subdomain.

**Comment by mineiro** [comment]
Hey guys! Just to give you an update, I have managed a workaround to my issue.

Explicitly adding a CNAME DNS record to `blog` solved the issue.

```
now dns add iar.org.br blog CNAME "alias.zeit.co"
```

After that, `now alias` DNS propagation test succeeded.

<img width="757" alt="screen shot 2017-08-08 at 16 48 38" src="https://user-images.githubusercontent.com/3123/29095007-cedbad96-7c65-11e7-8fee-72e02c5e796f.png">

Don't know why ` * ` DNS record stopped working as it was a few days ago.

**Comment by philcockfield** [comment]
+1

**Comment by OlliV** [comment]
We have made some improvements and I don't think we have a clear consensus under this issue about how to make it any more better for the end-user.
