### ISSUE TITLE
Running multiple instances of the same next.js app

### ISSUE THREAD

**Issue by Janpot** [vercel/vercel#3666]
Use case: I'd like to be able to run multiple versions of the same next.js app at the same time. Each one of those instances configured with a different `basePath` (experimental). The configuration  happens in `next.config.js` with environment variables. It also configures other things based on these variables, to make a reusable application that can run under path prefixes.
Currently I'm able to do it by starting the next.js app 3 times, each with different environment variables. Then proxying traffic to the right instance based on the path prefix. I have an example setup in [this repo](https://github.com/Janpot/nymus/tree/master/examples/next.js) for an internationalized next.js app.

I'd love `now` to be able to run a setup like that, and I've been experimenting with it. Right now I'm able to make a single instance work (by "work" I really mean just `now dev` for now) with the following config:

```json
{
  "build": {
    "env": { "LOCALE": "en", "LOCALES": "en,nl,fr" }
  },
  "rewrites": [
    { "source": "/en", "destination": "/" },
    { "source": "/en/(.*)", "destination": "/$1" }
  ]
}
```

But I'm getting stuck on expressing this for multiple instances. I'm also not sure how the routing would/should work. The following fails to run because `env` is not allowed:

```json
{
  "builds": [{
    "src": "next.config.js",
    "use": "@now/next",
    "env": { "LOCALE": "en", "LOCALES": "en,nl,fr" }
  },{
    "src": "next.config.js",
    "use": "@now/next",
    "env": { "LOCALE": "nl", "LOCALES": "en,nl,fr" }
  },{
    "src": "next.config.js",
    "use": "@now/next",
    "env": { "LOCALE": "fr", "LOCALES": "en,nl,fr" }
  }]
}
```

Is this the sort of use case `now` + `next` would be interested to support? It feels to me like it's quite close already.

**Comment by ivan-kleshnin** [comment]
@Janpot FYI I asked devs in Spectrum about multiple now/nextjs `dev` calls. They confirmed they are going to implement that. Still, I wouldn't cross my fingers for the nearest future, given the amount of issues with all the stuff added recently...

**Comment by Janpot** [comment]
Taken into account that the `builds` option is deprecated, I'm gonna assume this ticket is never gonna be followed up on. I'm having some new insights on how this could be done. I will work on a new example.
