### ISSUE TITLE
[github] not support use organization

### ISSUE THREAD

**Issue by bluelovers** [vercel/vercel#3672]
can't use exists project in organization
https://zeit.co/docs/v2/git-integrations

**Comment by styfle** [comment]
Hi @bluelovers 

You can [create a team](https://zeit.co/docs/v2/platform/users-and-teams) and link the GitHub Org to that new team.

Does that solve your problem?

**Comment by bluelovers** [comment]
hmm it work, but...

i can't use my old one for import organization?

i see gitlab can import from group repo

---


and some other github app can allow choose orig when auth

**Comment by paulogdm** [comment]
We are having a little bit of trouble understanding you... Can you elaborate?

**Comment by paulogdm** [comment]
If you want to connect a team with a git organization (GitLab, GitHub or BitBucket), check the team's settings and you should be able to do so. For additional support, please reach out to support@zeit.co

**Comment by bluelovers** [comment]
i mean other github app can request this

![Screenshot_20200204-063554_Chrome](https://user-images.githubusercontent.com/167966/73697154-d5348e80-4718-11ea-9ad7-ffe5caf29cfc.jpg)

**Comment by natecartwright** [comment]
I have, what I think is the same problem. When I connect Vercel to my github, it automatically chooses the first organization I am a part of, and does not give me an option to choose the other organization. Organizations aren't exactly primary/secondary in Github, in fact the primary org is a client. There's no way to re-order them in Github besides disconnecting them, so I think it should give the option in Vercel to choose which org to attach.

**Comment by aunncodes** [comment]
Any update on this?
