### ISSUE TITLE
Doesn't parse Dockerfile LABEL correctly

### ISSUE THREAD

**Issue by onbjerg** [vercel/vercel#368]
In the announcement blog post about Docker support for now, the example uses

```
LABEL name abc
```

However, this is not (AFAIK) correct, as the Docker documentation states the syntax is

```
LABEL <key>=<value> <key>=<value> <key>=<value> ...
```
>[Source](https://docs.docker.com/engine/reference/builder/#label)

Another issue is that the first syntax doesn't even work for ``now-cli``, the only thing that worked was:

```
LABEL name="website"
```

Note the quotes are required for ``now-cli``, whereas the Docker documentation states quotes only need to be used if there's a space in the label key or value.

**Comment by onbjerg** [comment]
After a bit of digging, it seems like it is because unquoted strings are not valid JSON, and ``now-cli`` tries to parse the label value with ``JSON.parse`` [here](https://github.com/zeit/now-cli/blob/e5babe0c7c4d056c228856706fbcf647fa302b3e/lib/read-metadata.js#L122).

**Comment by leo** [comment]
@jamo Could you take a look at this? You seem to have a lot of experience with Docker.

**Comment by nevotheless** [comment]
Yea this is still bugged. And since `Maintainer` is deprecated and `label` is supposed to be the intended way to go now, this should be fixed quite soon. (please)
