### ISSUE TITLE
[Feature Request]: Allow AWS VPC Peering

### ISSUE THREAD

**Issue by dnk8n** [vercel/vercel#3684]
Certain AWS features are protected with private only endpoints that can only be accessed when application is coming from same VPC.

Are there plans to peer with Amazon VPC, to unlock these features?

For example, Amazon Serverless Postgress (Aurora) does not provide the ability to use a public IP. Connections have to come from within the same AWS VPC.

It would be great to unlock its use by providing a mechanism to interact with AWS so that such connections are possible.

**Comment by bionicles** [comment]
I second this request — it’s incredibly risky for Zeit customers to secure production databases with only a password and no firewall. Even if the password remains secure, public databases **will** get DDOS’d on big sites, and there are many big sites using NextJS now, and many of these sites probably use Zeit, but without knowing IP ranges to whitelist, these big sites pretty much have to whitelist the whole interwebs. It’s well established now that DDOS can take down major swaths of the net, like what happened with Dyn DNS

At least give us a CLI command to lookup IP ranges to whitelist or let us grab those with Terraform outputs or something. You’re already managing global nameservers and could set up proxies to be whitelisted

**Comment by bionicles** [comment]
This is the number one reason I’d go to the trouble to use AWS over Zeit — Zeit has no easy way to connect the host servers to the database servers.
You want to use Zeit because it’s easy but this forces you to expose your databases. Not a good idea for the long run...

**Comment by dnk8n** [comment]
One idea I am going to test out is Flask, using SQL Alchemy, with Data API backend (I presume boto3 correctly setup in the Zeit Python runtime).

Found these libraries to do with accessing the RDS Data API (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html) via SqlAlchemy:

- https://github.com/koxudaxi/py-data-api
- https://github.com/rizidoro/camus
- https://github.com/chanzuckerberg/sqlalchemy-aurora-data-api

**Comment by ShanonJackson** [comment]
(I'll caveat with i don't work for zeit) But in my talks with them to achieve VPC peering with our NextJS stuff it sounds like this is offered under enterprise pricing tier.

If anyone lands here from google hope this helps.

**Comment by mjurincic** [comment]
Any news about this, what about creating proxy ec2 instance in meantime to get around this limitation like here: https://medium.com/@griggheo/accessing-a-private-rds-instance-via-an-ssh-tunnel-4be098b128ef. This is quite a blocker for us since we cant have DB-s with public ip-s.

**Comment by phritz** [comment]
+1, this would be great. Seems like the only choices now are either to use the AWS RDS SDK in which case one can't use any standard ORM/db/etc packages that assume standard sql drivers, or have the endpoint public, which entails the DOS and cracking risks, and creates an attack surface where administration can happen from anywhere.

FWIW enabling lambda to access a vpc is a matter of passing the `vpc-config` flag to `lambda create-function`, see "Create the lambda function" at this link: https://docs.aws.amazon.com/lambda/latest/dg/services-rds-tutorial.html

**Comment by r03** [comment]
I think a downside is that the start of a lambda is slower. Maybe this could be solved with provisioned concurrency?

**Comment by ivoreis** [comment]
> ... VPC peering with our NextJS stuff it sounds like this is offered under enterprise pricing tier.

Is there any documentation around this? @rauchg / @leo
