### ISSUE TITLE
Serverless functions not running on gatsby develop

### ISSUE THREAD

**Issue by sanderfish** [vercel/vercel#3694]
I have a Gatsby site hosted on Zeit Now and have added a serverless function to submit a contact form. When developing locally with `now develop` the serverless function's API endpoint runs perfectly, but when I run the development server with the `gatsby develop` command I'm unable to reach the endpoint – the response is the index.html which seems to mean that Gatsby is rendering it as a route instead of as an api endpoint.

In [the example here](https://github.com/zeit/now/tree/master/examples/gatsby) the `gatsby develop` command is being used, so it seems like I've set something up incorrectly.

Any ideas?

**Comment by styfle** [comment]
Since Gatsby doesn't support Serverless Functions, you can't use `gatsby develop`. You'll need to use `now dev` to develop locally. This will proxy requests from Now to Gatsby and is typically available under `http://localhost:3000`.

**Comment by ZeldOcarina** [comment]
This does not work. Gatsby will show a 404 page and suggest you should create a Gatsby function.
It works in production but it's quite hard to test that way.
