### ISSUE TITLE
[CLI] > Error! queryA ECONNREFUSED api.zeit.co

### ISSUE THREAD

**Issue by AdsonCicilioti** [vercel/vercel#3705]
I cant deploy with cli. Wherever i'm using github integration for deploy. `now dev` also works fine, but `deploy` no.

![image](https://user-images.githubusercontent.com/6278398/73518697-d050a180-43dd-11ea-9ad1-e8bd2a5537e0.png)

**Comment by peadrakw** [comment]
`${chalk.red('Error!')} To provided path ${chalk.cyan(
 `${chalk.red('Error!')} The provided path ${chalk.cyan(

**Comment by AdsonCicilioti** [comment]
> `${chalk.red('Error!')} To provided path ${chalk.cyan( `${chalk.red('Error!')} The provided path ${chalk.cyan(

??

**Comment by vuphan365** [comment]
@AdsonCicilioti  Have you resolved it yet?

**Comment by AdsonCicilioti** [comment]
@vuphan365, I reinstalled all the golbais packages, including now, cleared the npm / yarn cache, and everything worked again.
