### ISSUE TITLE
Improve errors in zeit's build console

### ISSUE THREAD

**Issue by erhankaradeniz** [vercel/vercel#3718]
Currently I'm facing an issue where I receive the following error on build:

```

{"error":{"code":"\"output\" field exceeds document size limit"}}
--
12:26:02 PM | Error: patchBuild: 400 Bad Request
12:26:02 PM | at retry.factor (/var/task/sandbox-worker.js:23338:21)
12:26:02 PM | at runMicrotasks (<anonymous>)
12:26:02 PM | at processTicksAndRejections (internal/process/task_queues.js:93:5)
12:26:02 PM | at async patchBuild (/var/task/sandbox-worker.js:23323:10)
12:26:02 PM | at async patchBuildToUploading (/var/task/sandbox-worker.js:20439:26)
12:26:02 PM | at async mainSub (/var/task/sandbox-worker.js:20057:32)
12:26:02 PM | at async main (/var/task/sandbox-worker.js:19975:5) {
12:26:02 PM | statusCodeFromFetch: 400,
12:26:02 PM | statusTextFromFetch: 'Bad Request'
12:26:02 PM | }

```

I'm not sure where to look for more information regarding this error, it would be better to link to some kind of documentation page. Not sure if it excists, I couldn't find anything regarding this problem. I'm also not able to see what the "size" is of the message.. 

My situation:
I'm trying to build a hybrid project, I have around 8-10K pages which are generated with SSG and a few SSR pages.

**Comment by erhankaradeniz** [comment]
I lowered the amount of pages being generated to ~3k and this seems to work. I'm guessing I'm hitting the 10k limit per deploy.. are there any future plans to override this?

**Comment by styfle** [comment]
Hi @erhankaradeniz 

You're right, that error message is confusing.

It usually means you have too many SSG pages like you mentioned (10K).

The error message has since been updated and we are working on increasing the limit, thanks!

**Comment by ironvale0** [comment]
I have the same problem, 1700 pages.

**Comment by styfle** [comment]
We improved the error message description. Also, the message will show up at the top so it will be the first thing you see when visiting the deployment inspector. Clicking "Learn More" links to the docs.

![image](https://user-images.githubusercontent.com/229881/77913106-b1498100-7261-11ea-83d5-175eff2ef76c.png)
