### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by Vadorequest** [vercel/vercel#3719]
Is there a changelog available?

If not, is it planned?

**Comment by styfle** [comment]
Hi @Vadorequest 

There is a high level changelog posted to the zeit.co/blog each month such as https://zeit.co/blog/changelog-january-2020

We also have a low level changlog posted to GitHub Releases for each Now CLI release such as https://github.com/zeit/now/releases/tag/now%4016.7.2

You can subscribe to GitHub Releases in the top of this repository:

<img src="https://user-images.githubusercontent.com/229881/73679472-6f002b00-4688-11ea-96d5-00dd2c391eee.png" width=230 />

**Comment by Vadorequest** [comment]
@styfle I'm trying to understand what happened with https://github.com/zeit/now/releases/tag/%40now%2Fnode%401.5.0

Basically, I see a 1.5.0 version is available. I found this tag, but no information.
Then, I found the closest release at https://github.com/zeit/now/releases/tag/now%4017.1.0 for 17.1.0

The only thing related to node is:
> [now-node] Use url.parse() for req.query helper (#3863) [@TooTallNate]

So, is that the only thing that was released with now-node 1.5.0? It's definitely hard to understand what happens when updating the @now/node package.

**Comment by styfle** [comment]
> is that the only thing that was released with now-node 1.5.0

No, we also shipped all the implicit dependencies such as `@now/build-utils` and `now` (CLI).

The release [now@17.1.0](https://github.com/zeit/now/releases/tag/now%4017.1.0) shows all the affected packages. You could also look at the [git logs](https://github.com/zeit/now/commits/master) which is basically the same information.

**Comment by Vadorequest** [comment]
Thank you, but I forgot to make it obvious that I meant about `@now/node` package.

Indeed https://github.com/zeit/now/releases/tag/now%4017.1.0 provides a proper list of all affected packages, but what about packages such as `@now/node`? (updated from `1.4.0` to `1.5.0`)

If I understand correctly, the only thing that was shipped with `@now/node@1.5.0` is: 
> [now-node] Use url.parse() for req.query helper (#3863) [@TooTallNate]

**Comment by styfle** [comment]
Yes that is the only change to that package, but the system as a whole relies on many packages so if you experience a change in behavior, it may not be from `@now/node`.
