### ISSUE TITLE
To secure the database, how do you get a range of IP addresses to whitelist?

### ISSUE THREAD

**Issue by bionicles** [vercel/vercel#3723]
We just want to make sure the only stuff which can talk to our databases, are the API routes in NextJS pages/api/*

Would it be a ton of trouble to figure out a way to get a list of IP addresses to whitelist for the database servers?

Then Zeit Now users could use databases with better security, for example, IBM Compose has autoscaling PostgreSQL and you can whitelist IP addresses. Yes, we can obscure the DB endpoint by keeping that environment variable on the server side but we’d rather not rely on “security by obscurity” and rather would prefer to explicitly deny all traffic to the database except that which comes from the Serverless functions in Zeit. 

Please holler if there’s a workaround for this so we can dodge a few days of Terraform because the current alternative solution is to make a VPC and host NextJS on AWS instead of Zeit

**Comment by bionicles** [comment]
Does it work to whitelist example.com/api/* ?

**Comment by bionicles** [comment]
update: i'm talking to AWS folks about the idea of domain whitelisting, it might be possible to handle this with WAF, and could almost certainly be handled with an Apache webserver using .htaccess file, or with ALB, but ALB can't target Aurora. This requires an IP lookup from the web server and also to verify the CA certificates but then the IPs could be cached. 

Not sure there's a great solution possible if Zeit doesn't take charge and think of something.

Ideally Zeit could handle this as it's a fairly common feature request in github issues and the forum, but I realize it's a complicated problem to solve... any ideas?

Just takes 1 Zeit customer to get a data breach and your business is pretty boned

**Comment by styfle** [comment]
Hi @bionicles 

There is no static list of IPs because we are not allocating an entire server for each Serverless Function.

As concurrent traffic increases, more instances of the function are automatically started and then stopped to handle the traffic seamlessly.

The recommended solution is to add a [secret](https://zeit.co/docs/v2/serverless-functions/env-and-secrets) with the credentials for your database which will be exposed as an environment variable in your Serverless Function.

If you need a VPC or other Enterprise features, please contact `enterprise@zeit.co` and the team will work with you to find a solution that works best for your organization.

Thanks!

**Comment by bionicles** [comment]
Hi @styfle i’m wary of unknown hidden “enterprise” costs so just switched to AWS. Anyone else who needs to not expose their database to the whole world can refer to my terraform template here (WIP) https://github.com/bionicles/bp/blob/master/_cloud/_terraform/main.tf

The goal is for users to talk to Next and Next to talk to Postgres. Even if someone knew the password they couldn’t execute arbitrary SQL. The user data is encrypted in transit and at rest and protected by row level security 

I’d like to use Zeit but IMHO end-user Privacy being an “enterprise” feature is not a policy I can agree with

**Comment by styfle** [comment]
Enterprise agreements are not unknown or hidden. Its a transparent agreement between your enterprise and ours to create a custom solution that meets your specific needs.

It sounds like you already solved your problem so I'll close this issue, thanks!

**Comment by sunderipranata** [comment]
Upvoting @bionicles 's question, by not providing a static IP list whitelist rule, even though it is protected by a strong password (while it is still risky). It may also introduce the DB service to the DDOS attack

Hopefully you will address this request. Thanks

**Comment by bionicles** [comment]
I didn't solve the issue, I switched to a different solution... AWS with Terraform.

Just wanted to use Vercel, because it's way easier.

Who's gonna prototype something where they need an enterprise agreement to use more than a password for the database?

**Comment by leerob** [comment]
Hello! I wanted to give an update here. VPC peering is now on our roadmap. Feel free to [contact us](https://vercel.com/contact/sales) if this is something your team needs. Thank you 👍

**Comment by jonrcrowell** [comment]
Is VPC peering specific to AWS, or will it also work with Azure?

**Comment by dg-eparizzi** [comment]
Any updates on getting a list of IP addresses or integrating it with an Azure VNET?

**Comment by daviddavid** [comment]
This issue pertains to other third-party solutions, such as mail servers that require an IP to be whitelisted, as well.
