### ISSUE TITLE
Force rebuild of lambda

### ISSUE THREAD

**Issue by dbauszus-glx** [vercel/vercel#3725]
Having the capability to cache configurations outside the handler is crucial in order to prevent calls to a backend on every execution of the lambda. However, if the configuration changes it must be possible to rebuild all serverless functions. Or at least destroy all frozen lambdas in order to force a rebuild on the next call. Currently not even deploying to production will clear frozen lambdas and it is necessary to call each and every endpoint with a chache-control (no-cache) in order to force rebuilding the lambda and re-caching the changed configuration.

**Comment by styfle** [comment]
You can use the "Rebuild" button on the dashboard to rebuild and deploy.
Alternatively you can use Now CLI with the [`--force`](https://zeit.co/docs/now-cli#options/global-options/force) flag to rebuild without the build cache.

If you want to disable cached responses from serverless functions, you can utilize the [`Cache-Control`](https://zeit.co/docs/v2/network/caching#serverless-functions-(lambdas)) header with a max age of 0.

You might also be interested in [Next.js 9.3](https://nextjs.org/blog/next-9-3) which has better support for missing SSR and SSG and introduced [Preview Mode](https://nextjs.org/blog/next-9-3#preview-mode).
