### ISSUE TITLE
Fails install on macOS Catalina (may if NVM is used)

### ISSUE THREAD

**Issue by AndyOGo** [vercel/vercel#3726]
Downloading and installing **now** by `npm i -g now` as described [here](https://zeit.co/download), does not take effect.

Try running `now --version` yields:

```sh
-bash: /usr/local/bin/now: No such file or directory
```

Btw. I use Node Version Manager.

**Comment by styfle** [comment]
It sounds like a bug with nvm.

Can you try `which now` to see if it finds anything?

What about other globally installed packages? Do those work or is `now` the only one failing to install?

**Comment by AndyOGo** [comment]
`which now` yields nothing 😞 

Yeah thought so too.
But before Catalina, I was able to use `now` in combination with `nvm`.

I don't know if it could be related to the switch to zsh, I really have no idea why it stopped working.

**Comment by styfle** [comment]
How about `which npm` or `which node`?

If you have yarn you could try `yarn global add now`.

**Comment by AndyOGo** [comment]
Works for npm and node as expected:

```sh
$> which npm
/Users/andy/.nvm/versions/node/v10.15.0/bin/npm
$> which node
/Users/andy/.nvm/versions/node/v10.15.0/bin/node
```

I don't use yarn.

**Comment by friedhelmensch** [comment]
@AndyOGo I had the same problem. Unfortunately I can not give you exact steps to fix it. I ended up uninstalling and deleting anything related to node and nvm. After reinstalling, now started working again.

**Comment by AndyOGo** [comment]
@friedhelmensch 
Thanks for your message.
Glad I'm not the only one with this experience.

Alright, guess it's time to resort to `killall` ^^

**Comment by styfle** [comment]
Can you try `PREINSTALL_DEBUG=1 npm i -g now` and see if there is any additional logging?

**Comment by AndyOGo** [comment]
I completely uninstalled nvm on all users.
I removed a prefix from nvm in my local npmrc file.

And I installed n, then installed now and it was working.
In the next days I will uninstall n, and install nvm at each user again.

So far I cant tell how to reproduce nor whats the cause 🤷‍♂️

**Comment by styfle** [comment]
I tried with nvm and it worked. Here's what I tried:

```sh
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
# Downloading nvm from git
nvm install 12.16.1
# Now using node v12.16.1 (npm v6.13.4)
which node
# ~/.nvm/versions/node/v12.16.1/bin/node
which npm
# ~/.nvm/versions/node/v12.16.1/bin/npm
npm i -g now
# added 1 package in 1.623s
which now
# ~/.nvm/versions/node/v12.16.1/bin/now
now --version
# Now CLI 17.0.4
```

I'll close this for now since it seems to be working correctly, thanks!
