### ISSUE TITLE
only deploy pull requests on files change

### ISSUE THREAD

**Issue by UziTech** [vercel/vercel#3744]
Is there a way the only deploy on a pull request if certain files change?

We have a `/docs/` folder that gets deployed but if no files inside that folder get changed there is no reason to deploy.

**Comment by styfle** [comment]
Yes, this can be achieved with a `.nowignore` file.

https://zeit.co/guides/prevent-uploading-sourcepaths-with-nowignore

**Comment by UziTech** [comment]
The `.nowignore` file seems to be used to prevent certain files from being deployed but zeit will still deploy the `docs` folder and comment on every PR even if it wasn't changed in the PR.

**Comment by styfle** [comment]
It won't actually deploy because of the [deduplication algorithm](https://zeit.co/docs/v2/platform/deployments#deduplication). 

You will still get a unique URL for the PR but it will point to the previous deployment (the one with matching source code).

**Comment by UziTech** [comment]
could we prevent the comment on the PR in that case?

**Comment by styfle** [comment]
GitHub comments can be disabled by setting the [silent](https://zeit.co/docs/configuration#git-integrations/github-silent) flag to true.

This is all-or-nothing and doesn't have anything to do with which files are changed.

The checks at the bottom next to the merge button will still show up, even when `silent` is true.

**Comment by UziTech** [comment]
thanks
