### ISSUE TITLE
Can't unignore default ignored paths

### ISSUE THREAD

**Issue by jacobmischka** [vercel/vercel#3747]
There currently does not seem to be a way to un-ignore any of the [default ignored file path specs](https://zeit.co/docs/v2/build-step/#ignored-files-and-folders), attempting to do so via `.nowignore` like the following does not work:

```
!.env.json
```

**Comment by sunopar** [comment]
I have the same need.
My project hopes not to ignore `.git` files, but it doesn't work

**Comment by skydr** [comment]
same thing with static framer x files. i need 1 more folder from node_modules (ignores by default)

**Comment by trusktr** [comment]
For reference this is the current Vercel file ignore list: https://vercel.com/docs/builds/build-features#ignored-files-and-folders

I also made a feature request in the community forums to allow unignoring Vercel's ignored files:

https://community.vercel.com/t/unignoring-files-for-static-deployments-feature-request/10513
