### ISSUE TITLE
Unknown or unexpected option: --confirm

### ISSUE THREAD

**Issue by Uninen** [vercel/vercel#3757]
I just updated to now@17.0.1 (from 16.something) and I'm now getting these errors in my pull requests:

<img width="773" alt="Screenshot 2020-02-06 at 5 31 33" src="https://user-images.githubusercontent.com/43100/73903645-4a7f9b00-48a2-11ea-8169-e64cecff622b.png">

Manual deployments still work ok and the PR deployed ok as well. I don't have `--confirm` anywhere in my repo or settings so I assume the problem is with the bot itself.

The PR: https://github.com/Uninen/og-image-builder/pull/5
One error: https://github.com/Uninen/og-image-builder/commit/831edb201449ae2dcfc0212ccce2767dad9197bb

Reported because the errors also give me an unnecessary notification that pings me.

**Comment by Cellane** [comment]
Experiencing the same issue, and I haven’t even updated to `now@17.0.1` – it just started happening randomly between two PRs.

**Comment by Cellane** [comment]
Just pushed another commit, I think this was now fixed on Zeit’s side because my deployment went through.

**Comment by styfle** [comment]
Thanks for reporting this issue!

It has since been fixed. See [this related thread](https://twitter.com/notquiteleo/status/1225258399807438848).
