### ISSUE TITLE
Now dev uses start script instead of build script

### ISSUE THREAD

**Issue by vajajak** [vercel/vercel#3761]
Hey,
I have recently stumbled upon an issue where now dev runs the start script defined inside package.json (which is "react-scripts start" from CRA) instead of the build script. This causes to start the default CRA development server which prevents the actual start of now dev.
I'm not sure when this originally started happening (I'm pretty sure it's not more than 14 days), but I've observed similar behavior happening in all projects I've tried so far (including CRA and Next apps). It makes now dev unusable for me.
![Screenshot 2020-02-06 at 18 00 05](https://user-images.githubusercontent.com/52152407/73966629-af74d880-4916-11ea-9296-3df187f44345.jpeg)
<img width="464" alt="Screenshot 2020-02-06 at 18 00 14" src="https://user-images.githubusercontent.com/52152407/73966632-b0a60580-4916-11ea-842f-02fb59fce684.png">
![Screenshot 2020-02-06 at 19 30 40](https://user-images.githubusercontent.com/52152407/73966904-31650180-4917-11ea-8583-2126b77e7563.png)
I've already tried reinstalling the CLI but that unfortunately didn't seem to make any effect.
I've also tried reverting to the last commit that I was sure it was working, but that didn't help either, supporting my conclusion that this isn't a project related issue.
Is there any way I can make now dev command use the build script again?
(Started on cli version 16.7.3, current version 17.0.1).
I'd be thankful for any help. Thank you!

**Comment by styfle** [comment]
Hi @vajajak 

Now CLI 17.x.x changed the behavior of `build` and `dev` scripts to use [Project Settings](https://zeit.co/blog/advanced-project-settings) that can override in the dashboard.

However, there seems to be an issue with this transition because the dev script from our example was [`BROWSER=none react-scripts start`](https://github.com/zeit/now/blob/53eb71f26dbfadfacc7f10fa7c615fd7798bbc06/examples/create-react-app/package.json#L11) and this has the same issue that you described.

Thanks for reporting this bug! We'll make sure it gets fixed!

As a workaround, you should be able to install `npm i -g now@16.7.3` for development.

**Comment by vajajak** [comment]
Hello @styfle and thanks for your prompt response.
Downgrading unfortunately didn't fix my problem, as I've mentioned earlier, the problem appeared already on version 16.7.3.
The only difference is that on 16.7.3, CLI runs `react-scripts start` right away without giving the "Running Dev Command" notice.
Perhaps there were some other changes to the now dev behavior?
Thanks!

**Comment by styfle** [comment]
This has been fixed in [17.0.3](https://github.com/zeit/now/releases/tag/now%4017.0.3), thanks!

Let me know if you're still having issues.

**Comment by vajajak** [comment]
Hey @styfle,
I'm unfortunately still having the same issue :/
![image](https://user-images.githubusercontent.com/52152407/74110010-10a3e280-4b89-11ea-9b91-5cb7cfcf85f9.png)
With debug mode on:
![image](https://user-images.githubusercontent.com/52152407/74110282-83ae5880-4b8b-11ea-86bb-6c2441854dac.png)
I've also noticed the "No runtimes need to be installed" line in the debug log, even though I'm using the now-php@0.0.8 runtime.
Please note that all of this is working perfectly once deployed on Now platform.

**Comment by styfle** [comment]
The logs look correct. A random port was assigned properly to CRA so that it can be proxied through now dev.

How about when you run `BROWSER=none now dev`?
Are you able to visit http://localhost:3000 and see the CRA app?

**Comment by vajajak** [comment]
Got it. http://localhost:3000 does the thing.
And I can now confirm that the bug is fixed, in 17.0.2 this wasn't working.
I've also changed the development script back to build in the dashboard as it better suits my needs.

Thank you, I really appreciate your help and bug fix!

**Comment by gragland** [comment]
I think I'm running into this issue on 17.0.3. My dev script is `BROWSER=none react-scripts start`, but `now dev` is just running `react-scripts start`. In my project settings override is disabled for the development command, but it appears it is in fact overriding my local value with the CRA default.
