### ISSUE TITLE
Light sleep pauses requests to DB

### ISSUE THREAD

**Issue by ErAz7** [vercel/vercel#3763]
Hey guys
thanks for this great service 
there is a big problem with zeit now nodeJS : process gets paused (light sleep) right after response sent to client even when there are promises not fulfilled
for example when I call mongoDB to get some info, it does not fulfill because process is paused by sleep
this is making my app completely useless
one work around is to delay sending response until all tasks done but this is not always possible (or the best way possible)
hope there is a solution

**Comment by paulogdm** [comment]
Hello @ErAz7 ,
This is not a bug or a problem of the platform. By default, we can only process work between the time of a request and a response. Therefore, "background tasks running in the serverless function" is not a good fit for our environment. How would you track if a task has failed, for example?

A better alternative for you would be to work with queues and async processing:
- You receive a request. Heavy work will need to be done.
- Put the work in a queue to be processed.
- Reply to the client with `res.end()` terminating the request.
- Let the queue and another process handle the work.

So you need to follow this structure:
```
module.exports = (req, res) => {
  await work();
  // OR
  await insertInQueue()
  res.end().
}
```

**Comment by ErAz7** [comment]
thanks

**Comment by sdwvit** [comment]
just my 2 cents here: sometimes you don't need a status of completion. And sometimes waiting for work to be done can be so long that user may switch pages in the meanwhile, so the execution result is lost anyway.
