### ISSUE TITLE
machine readable output for the now list command

### ISSUE THREAD

**Issue by Janpot** [vercel/vercel#3766]
I would like to be able to more easily parse the output of the `now list` command to help automate deployment workflows. Would it be possible to add a `--json` parameter that makes the output of that command parseable with `JSON.parse`?

**edit:**

Actually, parseable output for the deploy command would also be very helpful.

**Comment by styfle** [comment]
Hi @Janpot 

You can get a json response from the ZEIT API.

- Get Projects: https://zeit.co/docs/api#endpoints/projects/get-all-projects
- Get Deployments: https://zeit.co/docs/api#endpoints/deployments/list-deployments

**Comment by Janpot** [comment]
@styfle  I noticed that when `stdout` is not a tty, the deploy command [prints the deployment url](https://github.com/zeit/now/blob/bdd4953d62421d9993cd670a28a28403fdf9293e/packages/now-cli/src/util/deploy/process-deployment.ts#L184). Which turns out to be exactly what I was looking for. Is this a stable feature?

**Comment by styfle** [comment]
Yes, in fact the CI tests depend on this behavior.

**Comment by Janpot** [comment]
ok, thanks :+1:
