### ISSUE TITLE
Deploy keep restarting the start script

### ISSUE THREAD

**Issue by apertureless** [vercel/vercel#377]
Hey there.

Not sure if it's a bug or related to my code.
However I wrote a small node script, that should periodically scrape a page and then send a slack notification.

I did it with `setInterval()`

```javascript

function watch() {
    console.log('👀 Watching you... ')
    
   setInterval(() => {
        scapePage().then(...)
    }, refreshInterval)
}

watch()

```

In the start script I simply have a `node index.js &`.

But if I try to deploy it start the script

```bash
> > node index.js &
> 👀 Watching you...
```

But then after some time, it re-runs the npm install, build and start scripts.

**Comment by matheuss** [comment]
@apertureless you aren't exposing an HTTP port, right? You have to! 😅

**Comment by apertureless** [comment]
Oh okay... no I am not exposing an port.. because I actually don't really need to. The script should only run in the background with no interaction of mine...

**Comment by matheuss** [comment]
Currently we're focusing on HTTP servers – so for now I'd suggest that you fire up a very simple node server that just prints `ok` or something 🙏

**Comment by apertureless** [comment]
Works now thanks! 😍
