### ISSUE TITLE
Route Manifest Definition

### ISSUE THREAD

**Issue by tiarebalbi** [vercel/vercel#3774]
Hi,

Having an issue with one of my repositories, **github.com/tiarebalbi/tiarebalbi-website** which is using **create-react-app** but once I try to deploy I'm seeing the following error:

```
Error: A routes-manifest.json couldn't be found. This could be due to a failure during the build
--
10:38:27 PM | at Object.getRoutesManifest (/zeit/e0f2cd85419bbae1/.build-utils/.builder/node_modules/@now/next/dist/index.js:6057:15)
10:38:27 PM | at async Object.module.exports.178.exports.build (/zeit/e0f2cd85419bbae1/.build-utils/.builder/node_modules/@now/next/dist/index.js:3823:28)
10:38:27 PM | at async buildStep (/var/task/sandbox-worker.js:20292:20)
10:38:27 PM | at async mainSub (/var/task/sandbox-worker.js:20047:9)
10:38:27 PM | at async main (/var/task/sandbox-worker.js:19975:5)
```

Where can I find the details about this file?

**Comment by guilherme-vp** [comment]
Hello, can you tell us how did you solve it?

**Comment by tiarebalbi** [comment]
Hi,

Yes! Had to remove the .now settings, node dependencies and install all
over again.

After that the error message didn’t show again.

**Comment by guilherme-vp** [comment]
Okay, thanks for the help!! Happy codding.

**Comment by reginpv** [comment]
Im having this issue and removing .now and re-installing dependencies doest solve it for me :(

**Comment by txbrown** [comment]
Having this issue for a good while now and nothing I do solves it.

**Comment by willTastyMakers** [comment]
I am having this issue as well and I do not have a .now directory.  I have spent the past 2 days trying to deploy  with vercel. It used to be fairly straight forward now I can't make heads or tells of why I am getting this 

```
Error: A routes-manifest.json couldn't be found. This could be due to a failure during the build
13:04:35.457  
    at Object.getRoutesManifest (/zeit/1bc6bc026129a8fb/.build-utils/.builder/node_modules/@now/next/dist/index.js:6113:15)
13:04:35.457  
    at async Object.module.exports.178.exports.build (/zeit/1bc6bc026129a8fb/.build-utils/.builder/node_modules/@now/next/dist/index.js:3764:28)
13:04:35.457  
    at async buildStep (/var/task/sandbox-worker.js:20373:20)
13:04:35.457  
    at async mainSub (/var/task/sandbox-worker.js:20118:9)
13:04:35.457  
    at async main (/var/task/sandbox-worker.js:20023:5)
```

Reviewing similar issues on github...
- don't have .now directory
- do have a public directory
- searched your docs  for Routes Manifest Definition 

This is very frustrating..

**Comment by thomaszdxsn** [comment]
same error when i deploy next.js project with storybook site in same repo.

it take my storybook as a next.js project

**Comment by rahrang** [comment]
hey yall -- if you're trying to deploy a next.js static site to vercel and you're getting the "missing `routes-manifest.json`" error message, check out the docs here: https://github.com/zeit/now/blob/master/errors/now-next-routes-manifest.md

essentially you just need to make sure your project settings are as such
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/13807007/81896810-3666cc00-956a-11ea-8377-4c528d420df1.png">

this assumes you have `scripts` in your `package.json` for:
* "build": "next build"
* "export": "next export"

hope this helps!

**Comment by vishwasnavadak** [comment]
I got the same error today while deploying Storybook using the custom build command. 
Even though the build command is not of Next and Framework is explicitly selected as other, it seems to through this error. 

![image](https://user-images.githubusercontent.com/13111030/83159676-dce2cd80-a123-11ea-9704-d9e578bd94e4.png)

![Screenshot 2020-05-28 at 8 40 26 PM](https://user-images.githubusercontent.com/13111030/83159553-bae94b00-a123-11ea-89ea-d6a7694f273d.png)

**Comment by srib1997** [comment]
@vishwasnavadak 

create a now.json or vercel.json in your floder
---
<img width="588" alt="Screenshot 2020-06-04 at 7 08 38 PM" src="https://user-images.githubusercontent.com/9974673/83749836-eecdee80-a696-11ea-8b23-a1c40c3f1286.png">

---
and then clear your setting and save will solve your problem
---

<img width="741" alt="Screenshot 2020-06-04 at 7 09 00 PM" src="https://user-images.githubusercontent.com/9974673/83749886-04dbaf00-a697-11ea-854e-3c51bebc67c0.png">

**Comment by srib1997** [comment]
@vishwasnavadak 
vercel.json
<img width="588" alt="Screenshot 2020-06-04 at 7 08 38 PM" src="https://user-images.githubusercontent.com/9974673/83751238-145bf780-a699-11ea-89c9-9e42b9a34cf6.png">
<img width="741" alt="Screenshot 2020-06-04 at 7 09 00 PM" src="https://user-images.githubusercontent.com/9974673/83751246-1756e800-a699-11ea-88a2-cb5d6b429ebf.png">

**Comment by vishwasnavadak** [comment]
Hey @srib1997 thanks for the answer. I'm not sure why though. 

Is this a bug or this is how it should be done?

**Comment by SpainTrain** [comment]
> Is this a bug or this is how it should be done?

It is a bug.  

Project linking has been the idiomatic approach to Vercel project config since v17. Using the suggested approach results in:

> Due to `builds` existing in your configuration file, the Build and Development Settings defined in your Project Settings will not apply. Learn More: https://vercel.link/unused-build-settings

I do not think it is controversial to say that a basic static site deployment ought to work with project linking.  It may require a new GH issue to get eyes on this problem, and I am also discussing with support.

**Comment by PascalPixel** [comment]
Same thing, 'Custom framework' set, running `yarn build-storybook` and setting output folder to `static-storybook`, keeps trying to find a `next` routes manifest because `next` is am (unused) dependency.

**Comment by SpainTrain** [comment]
Update: I have confirmed with Vercel support that this is a bug.  Support has forwarded it to the engineering team.  Their support has been awesome in my experience :+1:.  Here is to hoping it is a quick fix 🥂

**Comment by styfle** [comment]
This has been fixed in PR #5009, thanks!

**Comment by jamesryan-dev** [comment]
do we have to do anything like run upgrade to resolve this?
just ran into it randomly upon deploying..

**Comment by styfle** [comment]
@jimmynames No, nothing you need to do besides deploy. The fix is available for all new deployments.

If you are still seeing this error, please submit a [Support Request](https://vercel.com/support/request) so we can look at your deployment and see what the problem is, thanks!

**Comment by emgoto** [comment]
FYI I just experienced this issue when attempting to set up using the Blitz.js template.

**Comment by castra-neon** [comment]
@PascalPixel were you able to fix it?

**Comment by castra-neon** [comment]
@PascalPixel i fixed the issue when i set Framework to "Other"
thanks @styfle

✅ this works guys: 
<img width="948" alt="image" src="https://user-images.githubusercontent.com/105371852/179726384-6e5d0f14-09ce-4e2c-8c3a-b60cc1323e60.png">
