### ISSUE TITLE
[now dev] Being able to run in production mode locally

### ISSUE THREAD

**Issue by verekia** [vercel/vercel#3776]
Testing an app locally in production mode, to fix any discrepancies between development and production builds seems to me like an essential step that is currently missing with Zeit Now if I'm not mistaken.

I am using Gatsby, and currently the only option is to upload a new deployment to Zeit, or to only build the front-end of the app without `now dev`, with `gatsby build && gatsby serve` for instance.

It could maybe be `localProdCommand` field next to: https://github.com/zeit/now/blob/01d5a10ebde48c2d05b96f5c4712a39b43616167/packages/frameworks/frameworks.json#L50-L52

Is there any workaround in the meantime?

Now CLI 17.0.3

**Comment by zgmrvn** [comment]
that's what `now` (without the `--prod`) does if I'm not mistaken, it creates a new deployment using the `production` environment, it just doesn't proxy your production domain.

**Comment by verekia** [comment]
Thanks @zgmrvn, but I was referring to running in production locally, without deploying to Zeit. I updated the title to make it clearer.

**Comment by styfle** [comment]
Hi @verekia 

You can change the Development Command by visiting your [Project Settings](https://zeit.co/blog/advanced-project-settings) in the dashboard.

**Comment by verekia** [comment]
Thank you @styfle.

I confirm that this works and completely solves the issue :)

Now with that being said, it feels very awkward to me that build and development options are only available online. And well, now dev being only available online in general. How is this "zero config" if the config is in a form online instead of a local file?

I'm sure there is some solid reasoning behind this and I would gladly read about it if there is some public discussion available somewhere.

I'm very happy with Zeit and I'm not even concerned about the forced lock-in that this implies, but it just feels like a weird direction to be heading to.

**Comment by styfle** [comment]
There's some discussion in #3767 

The tl;dr is "Root Directory" can't be configured in `now.json` because you are telling the the project which directory to look for `now.json`. However, we're looking at how to best support Build Command and Dev Command in local configuration.
