### ISSUE TITLE
Provide an example using "next export" to build and serve static HTML on Now

### ISSUE THREAD

**Issue by callumlocke** [vercel/vercel#3783]
I'm serving my site with `next` in development (for hot reloading etc.), but I don't need Node at runtime in production, so I want to export a static site with `next export` at build time.

By default, `next export` writes to `out`. But in order for Now to serve the generated static files, they need to be in `public`, so my `package.json` contains something like this:

```json
  "scripts": {
	"dev": "next",
    "build": "next build && next export public"
  }
```

The problem is, I'm exporting to `public`, but `public` also has special meaning for Next: Next uses `public` a _source_ of static files for the build and export. So doing `next export public` doesn't make sense, because we're trying to use `public` as both a source and target for the export. It's unclear how this can work.

Please provide an example showing how to use `next export` to build and host a static site on Now.

**Comment by paulogdm** [comment]
Please use https://zeit.co/blog/advanced-project-settings
![Screenshot from 2020-02-19 18-46-58](https://user-images.githubusercontent.com/7690649/75030210-64b0a000-5482-11ea-8438-3d593af02cd6.png)
