### ISSUE TITLE
Can't create project from github

### ISSUE THREAD

**Issue by boehs** [vercel/vercel#3792]
it pops up, but when I click on it it says ERROR: The repository either does not exist or is not publicly accessible. this happens for all projects, how can I fix

**Comment by styfle** [comment]
Hi @Scaledish 

It sounds like there was a problem linking your GitHub account to your ZEIT account.

Please submit a support request with your username, email, github account, etc and we'll get it sorted out here: https://zeit.co/support/request

Thanks!
