### ISSUE TITLE
What Zsh/Vim themes are shown in the marketing screenshots?

### ISSUE THREAD

**Issue by jdsimcoe** [vercel/vercel#380]
I love the minimal white `.zsh` and Vim themes I've seen on the website and in casts. Any pointers as to what setup you guys are using?

![screen shot 2017-03-13 at 10 07 39 am](https://cloud.githubusercontent.com/assets/275617/23866257/8229ecba-07d5-11e7-94a7-ae976492e055.png)
![screen shot 2017-03-13 at 10 07 50 am](https://cloud.githubusercontent.com/assets/275617/23866258/822b7ba2-07d5-11e7-86dd-45f31d83c844.png)

**Comment by jdsimcoe** [comment]
@matheuss Created this: https://github.com/zeit/zeit.zsh-theme.

**Comment by matheuss** [comment]
![pizzaparrot](https://cloud.githubusercontent.com/assets/4721750/23869991/c3564eb2-0803-11e7-9a30-86f4b805fa94.gif)
