### ISSUE TITLE
[now dev] Please do not neglect local development use cases

### ISSUE THREAD

**Issue by rfgamaral** [vercel/vercel#3803]
It has come to my attention that "`now dev` is moving towards the use of frameworks and other libraries since this is the most common usage". These were the exact words from @paulogdm in a support ticket. I'm not sure if I'm the only one that sees `now dev` differently but I'm here to explain my use case for `now dev`, as requested by Paulo.

I currently have my home page deployed to ZEIT Now and I'm not using any framework; it's a basic website built with Gulp.js and I use [Browsersync](https://browsersync.io/) for local development. My website is built with `yarn build` and there's nothing I need to do to deploy this to ZEIT, Yarn is detected and it uses the `build` task in `package.json` with zero configuration.

However, I have a custom [`now.json`](https://github.com/rfgamaral/ricardoamaral.net/blob/master/now.json) configuration file where I have some security headers specified. Now, how do I test this configuration and make sure the headers are properly configured? I could run `now` and have a preview version deployed and test the headers online, but `now dev` allows me to do that locally without deploying anything. Currently, I just have to run `now dev` on the root of my project and a local HTTP server will be available to me, replicating everything as if I were to deploy to ZEIT Now, but without deploying anything.

This feature is awesome and I'm hereby requesting that you don't remove it. Please keep supporting `now dev` for framework-less projects. I can't be alone using ZEIT Now and `now dev` without a framework, can I?

As an extension of the above, I have a feature request to improve local development based on `now dev`. You might have noticed the following in my `now.json` file above:

```json
"builds": [
  {
    "use": "@now/static-build",
    "src": "package.json",
    "config": {
      "zeroConfig": true,
      "outputDirectory": "dist"
    }
  }
],
```

I understand that the above [is deprecated](https://zeit.co/docs/configuration#project/builds), however, `now dev` - on framework-less/custom projects - is defaulting to `public` and the above was the only way I found that allowed me to change the output directory (I use `dist` by convention and I really would like to keep it that way).

The same way you allow the `BUILD COMMAND`, `OUTPUT DIRECTORY` and `DEVELOPMENT COMMAND` to be overridden for deployments to ZEIT Now:

![image](https://user-images.githubusercontent.com/96476/74761940-d1eee600-5274-11ea-9666-21b068ae0745.png)

I propose that `now.json` allows one to configure/override those 3 options to be read by `now dev` at least, if overridden, of course.

What I meant with "at least" above is that these options could also be read by `now` (or `now --prod`) and be used to override the UI options in "Build & Development Settings" above. And the UI could reflect that by displaying the overridden option value and changing the toggle to blue (as if it was overridden directly in the UI). However, to avoid having the UI overrides out-of-sync with the `now.json` options, the input fields and the blue toggles should be disabled (slightly faded out perhaps) not allowing changes in the UI with a little message saying something like "this is overridden in `now.json` please remove/change it there".

What does everyone think about this?

**Comment by styfle** [comment]
Hi @rfgamaral There is a similar discussion in #3767. Thanks for the feedback!
