### ISSUE TITLE
Running now from bitbucket fails

### ISSUE THREAD

**Issue by DanielMichaelEdwards** [vercel/vercel#3806]
I had a working deployment from bitbucket to my now deployment which has stopped working. I have been getting this error which is related to a package installed when the script runs:

`+ now --token=$NOW_TOKEN --prod
/var/lang/lib/node_modules/now/dist/index.js:2
require('./sourcemap-register.js');module.exports=function(e,t){"use strict";var n={};function __webpack_require__(t){if(n[t]){return n[t].exports}var r=n[t]={i:t,l:false,exports:{}};e[t].call(r.exports,r,r.exports,__webpack_require__);r.l=true;return r.exports}__webpack_require__.c=n;function startup(){return __webpack_require__(4165)}t(__webpack_require__);return startup()}([,,,,,,,,,,,,,,,,function(e,t,n){"use strict";var r=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:true});const i=r(n(4859));function arrayMove(e,t,n,r,i){for(let o=0;o<i;++o){n[o+r]=e[o+t];e[o+t]=void 0}}function pow2AtLeast(e){e=e>>>0;e=e-1;e=e|e>>1;e=e|e>>2;e=e|e>>4;e=e|e>>8;e=e|e>>16;return e+1}function getCapacity(e){return pow2AtLeast(Math.min(Math.max(16,e),1073741824))}class Deque{constructor(e){this._capacity=getCapacity(e);this._length=0;this._front=0;this.arr=[]}push(e){const t=this._length;this.checkCapa
SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
`

If there is any help or someone who knows a way around this, please let me know.

**Comment by DanielMichaelEdwards** [comment]
The main error is:

`SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3`

**Comment by paulogdm** [comment]
What is your Node version?

**Comment by DanielMichaelEdwards** [comment]
Node8.10,

I am using the following image in my pipeline script:

image: lambci/lambda:build-nodejs8.10

**Comment by styfle** [comment]
Now CLI requires Node 10 or newer as defined in the [engines](https://github.com/zeit/now/blob/master/packages/now-cli/package.json#L62) field.

Consider using the [BitBucket integration](https://zeit.co/bitbucket) instead so that you can use `git push` to deploy.

**Comment by styfle** [comment]
We'll have a better error message in the upcoming release of Now CLI 18.x.

See #3869 for more details, thanks!
