### ISSUE TITLE
Feature request: deploy already built static folder

### ISSUE THREAD

**Issue by Uninen** [vercel/vercel#3813]
I'd love to see a way to push an already built directory with now, the same way [netlify deploy](https://cli.netlify.com/commands/deploy) works. This is allows both faster deploys and more control over the build environment as you can do it from anywhere.

My spesific use case / issue that would be solved by this:

I have a [VuePress](https://github.com/vuejs/vuepress) site that uses timestamps from git files to write out `Last edited` information to each page. Problem is, this doesn't work with ZEIT as it ignores .git folder (apparently before the build starts) and I currently see no way of sending the built from my CI pipeline instead. (Or maybe there is a way?)

It would be easy to add a deploy step to my CI-pipeline which would also mean less build work for ZEIT.

**Comment by monojack** [comment]
Now just uses the build script defined in your `package.json` to build the project, I haven't tried it yet, but I guess you could [define a `now-build` script](https://zeit.co/docs/v2/build-step#defining-a-build-script) that does nothing and make sure you also upload the build directory (which by default is `public`) and now will serve everything from that folder. 

P.S. If you don't like the defaults, you can always change them from the project settings once you've created it.

**Comment by styfle** [comment]
You can override the "Build Command" in the project settings.

https://zeit.co/blog/advanced-project-settings

If no framework is detected, then the deployment is assumed to be static (for example no package.json).

**Comment by coetry** [comment]
@Uninen as already mentioned above, you can modify the build script from your project settings and if you'd like to build your project locally or in a CI environment, you can definitely upload the built static folder by entering the folder and running `now`. We don't have a separate command and the default `now` command will get you what you're looking for. 

However it should be known that if you are deploying with the CLI, you will be prompted with project linking questions which you can skip by adding the `--confirm` [flag](https://zeit.co/docs/now-cli#commands/now/unique-options/confirm). 

You will need to also add the `NOW_ORG_ID` and `NOW_PROJECT_ID` env variables so your project information can be detected automatically without human intervention. 

You can find your org id, by hitting the [teams endpoint](https://zeit.co/docs/api#endpoints/teams/get-single-team-information) with an authorized token and you can find your project id by hitting the [projects endpoint](https://zeit.co/docs/api#endpoints/projects/get-a-single-project) with an authorized token.

I'll close this issue for now. If you have any follow up questions, we can re-open it.

**Comment by EvanLovely** [comment]
> You can find your org id, by hitting the [teams endpoint](https://zeit.co/docs/api#endpoints/teams/get-single-team-information) with an authorized token and you can find your project id by hitting the [projects endpoint](https://zeit.co/docs/api#endpoints/projects/get-a-single-project) with an authorized token.

Seems a little easier to get your `NOW_ORG_ID` & `NOW_PROJECT_ID` values by deploying locally first, setting up the project linking, and then looking at `.vercel/project.json` which contains them both! 👍
