### ISSUE TITLE
 The rate limit of 5000 exceeded for `api-upload-free`. Try again in 15 hours

### ISSUE THREAD

**Issue by bluelovers** [vercel/vercel#3826]
when have this error

it will not show message by github bot
and will not show log in https://zeit.co/dashboard

this error message only display by use now cli

## expected

show message by github bot
show log in https://zeit.co/dashboard

**Comment by styfle** [comment]
Hi @bluelovers 

This means you have exceeded 5000 uploads in 1 day. You'll have to wait until the next day to upload more or upgrade to a paid account.

See the [limits](https://zeit.co/docs/v2/platform/limits#username-update) documentation for more.

**Comment by bluelovers** [comment]
i know what is this error mean

i mean should show error message in github bot and https://zeit.co/dashboard

if i didn't check cli , i will never know why error

**Comment by styfle** [comment]
What did the GitHub Integration do if it didn't display an error?

**Comment by bluelovers** [comment]
show a error on commit log, but no leave a message on commit

https://github.com/demonovel/opds/commit/804994ae4c4c107b3bc566a92a96c6e582856a41#comments

![image](https://user-images.githubusercontent.com/167966/75617889-27de5a80-5ba0-11ea-8523-914dd93bb198.png)

![image](https://user-images.githubusercontent.com/167966/75617891-32005900-5ba0-11ea-96c6-90ce802e66dd.png)

**Comment by styfle** [comment]
What happens when you click "Details" in your first screenshot?
Does it show more details?

**Comment by bluelovers** [comment]
What happens when you click "Details" in your first screenshot?

> pic2

**Comment by styfle** [comment]
I understand now. Clicking "details" scrolls down to the comments and there is no comment.

This looks like the error message is the catch-all so it will need to account for rate-limit errors and add the appropriate comment like you saw in the CLI.

I'll let the team know, thanks!

**Comment by coetry** [comment]
@bluelovers Thanks for reporting this. We've fixed the issue and rate limit errors should now be visible in commit messages :tada:  If you have any similar problems in the future, please let us know and we can re-open the issue.
