### ISSUE TITLE
[Feature Request] Access to the PR Target Branch

### ISSUE THREAD

**Issue by aequasi** [vercel/vercel#3828]
If I create a PR from:

`git@github.com:aequasi/www.discordservers.com.git` `feature/foo` branch

to

`git@github.com:discordservers/www.discordservers.com.git` `master`  branch

I would like to have a build env variable that contains `discordservers/www.discordservers.com` and `master`

Right now, we don't get that

commit message would be nice too

**Comment by coetry** [comment]
Hi @aequasi , can you help me better understand how this workflow would help you? Is it mainly an issue of taking different actions based on the environment you're in?

**Comment by aequasi** [comment]
Pretty much, yes. We run a script to fetch secrets from AWS Secrets Manager during the build, and right now, if we create a PR from `development` into `master`, it builds the app using `development` secrets, and then when it merges, it gets deployed with the development secrets

**Comment by styfle** [comment]
Since [Now 18.0.0](https://github.com/zeit/now/releases/tag/now%4018.0.0) you can manage environment variables with `now env` or on the dashboard.

Does this solve your problem?

**Comment by aequasi** [comment]
Unfortunately not. We have two "production" environments: `development` and `master`.

**Comment by styfle** [comment]
> We have two "production" (as far as ZEIT is concerned) environments

Can you elaborate? Are you referring to two different [branch domains](https://zeit.co/blog/branch-domains)?

**Comment by aequasi** [comment]
Yes,

We run everything using the fork model (upstream repo is the org repo, every developer has their own fork).

The upstream org repo has two branches: `development` (the default branch, to make sure devs are PRing against development instead of master), and `master`. `development` is our staging environment. We run tests against this, and use this to make sure that everything is good before going to production. Not all users of this are developers. `master` is *our* production environment. 

Both of these have `production` URLs set up in ZEIT, to ensure that they are getting the domain (these two both have specific (sub)domains that they need to use) aliased properly after a deploy.
