### ISSUE TITLE
[now dev] Follow directory symlinks

### ISSUE THREAD

**Issue by michaellopez** [vercel/vercel#3831]
Would you be willing to accept a PR for adding `options.follow = true` for the globbing? https://github.com/zeit/now/blob/340f7db68ac4dc7734d08211e93b734e7945a40d/packages/now-build-utils/src/fs/glob.ts#L40-L45

The idea is that it would cause `getAllProjectFiles` to also find files inside symlinked directories.
https://github.com/zeit/now/blob/55c73b68bb03396f41849426b52e82bc8be0520d/packages/now-cli/src/util/dev/server.ts#L527

I haven't tested this yet, might be more code needed to get it to work as expected. But I thought I'd check if you'd be willing to merge such a feature (possibly behind an config/option?) before investing more time in it.

Our main use case is for `now dev` to pick up lambdas i symlinked directories inside `/api` folder. 

https://github.com/zeit/now-builders/pull/359 fixed symlink handling for files, so we can symlink individual lambda files and they get picked up properly. This is a question regarding symlinked directories. Currently they get ignored.

In the cloud we'd just copy all the files into `/api` for the build step. Our use case is mainly for development purposes only.

**Comment by styfle** [comment]
Hi @michaellopez 
Thanks for the suggestion! I'm not sure I understand the use case. Is it the same as #3521?

Can you provide an example repo that we can use for a test fixture? That might explain the problem.
