### ISSUE TITLE
How does this routes setting work?

### ISSUE THREAD

**Issue by coodoo** [vercel/vercel#3835]
Saw following settings [from the doc](https://zeit.co/docs/configuration#project/routes), seemed like it could capture all requests to `/api` and redirect those to a file named `my-api.js`, I gave that a try but ran into errors with `now` complaining about `my-api.js` did export a react component, did I put `my-api.js` in the wrong place?

```
{
  "routes": [
    { "src": "/api", "dest": "/my-api.js" },
  ]
}
```

**Comment by willemliu** [comment]
![image](https://user-images.githubusercontent.com/974906/75237766-399ab900-57c0-11ea-92e7-cd8957a3f51b.png)
This is currently recommended way to setup routing. Although I couldn't make it work with Now v17+.

**Comment by coodoo** [comment]
I tried 'redirects' but still  no dice...

**Comment by willemliu** [comment]
> I tried 'redirects' but still no dice...

If you happen to use Now CLI V17+ then maybe you can try to go back to V16.x and see if `routes` work for you then.

**Comment by coodoo** [comment]
Ended up what I wanted to do can be achieved by [`dyanamic API routes`](https://github.com/zeit/next.js/blob/master/docs/api-routes/dynamic-api-routes.md#catch-all-api-routes), thanks for helping out though! 🙌
