### ISSUE TITLE
Wildcard DNS fails

### ISSUE THREAD

**Issue by hugomd** [vercel/vercel#384]
Attempting to add an MX record for a domain with the following command:
```
now dns add my.domain * MX my.email.provider 10
```
But fails with:
```
Error! Invalid number of arguments. Usage: `now dns add <domain> <name> <type> <value> [mx_priority]
```

To my knowledge, `*` is a valid option in DNS, so this should be supported in `now-cli`.

**Comment by OlliV** [comment]
Your shell will expand `*` to a list of filenames in the current directory. Try
`now dns add my.domain '*' MX my.email.provider 10`

**Comment by hugomd** [comment]
Ah! That's what I get for doing things late at night! Sorry for wasting your time 😅
