### ISSUE TITLE
Execute different build script for different domains

### ISSUE THREAD

**Issue by mimedo** [vercel/vercel#3844]
Hi all

I'm using the free version and I have two domains - one for production and one for development.
My project is based on Angular 8 which is deployed successfully to ZEIT (Production ENV is deploying master branch and Development ENV is deploying develop branch).

My project is setup that I use in my `angular.json` file different scripts to load environment specific values (API URL's). This values are stored in `environment.dev.ts` & `environment.prod.ts` files. In ZEIT we have the power to configure a custom build command - what I did:

![Screenshot 2020-02-27 at 14 34 47](https://user-images.githubusercontent.com/16817679/75450025-5b39a300-596e-11ea-8cb3-48256c801fed.png)

But this is only possible in General section - not for specific domains.

My question is - is there a way to configure for each domain different build commands or is there another, better way to handle this problem?

**Comment by styfle** [comment]
This is not possible at this time.

We are looking at ways to support multi-environment project so you could assign different staging env vars compared to production env vars.

This new feature could solve your problem if your build script could read env vars and act accordingly.

We already have a different "Develop Command" you can specify for `now dev` but this won't be used for deployments.

**Comment by qbodart** [comment]
This is something that we would need as well as we work with Staging and Production environments.

**Comment by robertcoopercode** [comment]
Just an FYI, it is possible to deploy to different environments (e.g. staging and production) if you specify the `NOW_PROJECT_ID` and `NOW_ORG_ID` environment variables before deploying. This requires 2 ZEIT projects and then you can specify a build command for each of your projects.

I wrote up how to deploy to different environments here: https://www.robertcooper.me/deploy-app-to-multiple-environments-zeit-now

**Comment by styfle** [comment]
Multiple environments are available in [Now 18.0.0](https://github.com/zeit/now/releases/tag/now%4018.0.0) and on the dashboard today!

**Comment by VigneshVaidyanathan** [comment]
@mimedo Did you figure out a way to get that done? I am stuck at the same problem.

**Comment by mimedo** [comment]
They released a new version where it's possible to define environment variables.

**Comment by StefanFeser** [comment]
@mimedo I was wondering how your solution looks like, since I have exactly the same problem and could not come up with a solution yet.

I have two build commands for angular:

```
ng build --configuration=staging
```

```
ng build --configuration=production
```

The app is heavily relying on the angular environments, so it's not too easy to change that.

Pushing to the `staging` branch should deploy to staging.url.com and pushing to `master` should deploy to url.com. Therefore depending on what branch is pushed a different build command should be executed. But afaik this is not possible yet, right? Did you find another solution?

**Comment by mimedo** [comment]
@StefanFeser For now I can't give you a solution because I did not find a solution for now as well. As mentioned from @styfle they released a [version](https://github.com/zeit/now/releases/tag/now%4018.0.0) which should help in this situation.

See this [documentation](https://vercel.com/blog/environment-variables-ui).

In case I find a solution I'm going to write it down here.

**Comment by StefanFeser** [comment]
For everyone finding this issue and having the same problem:

I managed to find a solution by using the vercel environment variables in Angular's environment.ts & environment.prod.ts
You can find a detailed tutorial for it here: https://medium.com/@ferie/how-to-pass-environment-variables-at-building-time-in-an-angular-application-using-env-files-4ae1a80383c

This does not solve the problem if you really need to have different build commands for each environment, but in my case it works totally fine.

e.g. if you have a different API URL for each environment, here's my workaround:

1. Create the API_URL env variables in Vercels UI for production & preview
2. Follow the steps in the tutorial above
3. In the end you only need on command which works fine with Vercel's git integration

**Comment by fmmattioni** [comment]
for anyone else struggling with it, this solved the issue for me: https://www.storyblok.com/tp/different-build-commands-branch-name-vercel
