### ISSUE TITLE
Monorepo now dev not working (even with official example)

### ISSUE THREAD

**Issue by realfunkyusername** [vercel/vercel#3846]
Hello guys,

I am trying to get my monorepo running. If you use the example: https://github.com/zeit/now/tree/master/examples/gatsby

and run `now dev`, you only ever reach the frontend. 

Is that in any way solvable? I need a local dev environment.

**Comment by realfunkyusername** [comment]
So apparently there are two webservers running when using now dev, one of gatsby, one of now itself. If you use the first one, it doesn't work, so use the second one (default port 3000) and it's fine. Weird.

**Comment by mtimofiiv** [comment]
Thanks @realfunkyusername for posting the answer to this. Had the same problem. I really think they need to document this.
