### ISSUE TITLE
Error while building deployment on third party package installation

### ISSUE THREAD

**Issue by Teenterror** [vercel/vercel#3870]
Hi, I'm trying to develop a wallet for tezos using npm package (npmjs.com/package/conseiljs). I have installed the package in an existing app(which is perfectly working in Zeit) and redeployed it without any code changes. It got failed during the build (https://zeit.co/clove/clove-wallet/3ft8v0a0i?redirect=1).
Steps to reproduce the error :

    Take any working app or create-react-app
    npm i conseiljs
    deploy in Zeit

you may catch the error during deployment.
Please help me in fixing this?

**Comment by styfle** [comment]
I got an error `Failed to initialize libusb.` when I have `require('conseiljs')` in my build script.

Is there a reason you need to access a USB device?

My guess is that `conseiljs` changed recently and now requires libusb for some reason.
