### ISSUE TITLE
Remove `--no-clipboard`

### ISSUE THREAD

**Issue by leo** [vercel/vercel#388]
We should just check for TTY instead.

**Comment by jamo** [comment]
IMO we need to keep this option; I hate it so much when an app edits the clipboard automatically.

**Comment by matheuss** [comment]
I agree we need to keep it, i have `alias now='now --no-clipboard'` 😛

**Comment by jamo** [comment]
I tend to keep passwords (pg etc.) On clipboard and it's the worst when something nukes the clipboard...

Why would we even consider removing the `--no-clipboard`?

**Comment by leo** [comment]
Because options that aren't important aren't wort keeping. Our CLI is getting bigger and bigger and we need to stop it. The first step to this is [adding plugins](https://github.com/zeit/now-cli/issues/350). If we can remove more flags, that would be even prettier. 😊

**Comment by jamo** [comment]
So this would leave me with two options, removing tty and seeing no build logs, or it at random point of time destroying my clipboard?

**Comment by leo** [comment]
I think your argument is a pretty good one, I so think we should consider keeping it. I just wanted to make clear that we should carefully pick which things stay in there.

Also just out of curiosity: Why are you keeping things in there for a longer time? I mean: It's meant to be used for moving things from one place into another (c&p), but not for storing stuff. Especially when copying a password, wouldn't the solution just be to paste it to wherever you want it and then continue? Just do that after triggering a deployment or before... 😄
