### ISSUE TITLE
Cannot access application websocket

### ISSUE THREAD

**Issue by LucaAndrei** [vercel/vercel#389]
Hi all,

I have deployed a Meteor application using meteor-now package.
Now I am trying to access the websocket from an external Android application using a DDP Client.
I have tried using two different implementations of DDP clients and none of them work.

I am using the free plan from Zeit, and their generated domain (not a custom domain name).
Is there anything else I can do to access the applications websocket?
I have created an alias example.now.sh.
I have tried : 

- example.now.sh/websocket
- example.now.sh:80/websocket
- example-oevqefrifa.now.sh/websocket
- example-oevqefrifa.now.sh:80/websocket
- example-oevqefrifa.now.sh/sockjs/147/ezmyu805/websocket (I found these values in some GET calls in the Developer Tools from the browser)

* For deploy I have used : meteor-now -e MONGO_URL=...
I did not use the ROOT_URL if it matters

**Comment by matheuss** [comment]
I'm not sure how this can be an issue on our side – we do support websockets and they should work flawlessly.

Seems like you're confused about where the socket is being _served_ have you checked `meteor-now`'s docs?

**Comment by LucaAndrei** [comment]
I asked the same question on the Slack chat and they've said that I should create an issue in case somebody is in the same situation. But I agree, this isn't an issue.
But still, isn't this issue that I'm seeing related to `now` package? `meteor-now` is just a wrapper, right?
I believe that `now` serves the socket, right?

*Later edit : I have created an issue in the `meteor-now` package as well : https://github.com/jkrup/meteor-now/issues/36

**Comment by jamo** [comment]
The protocol should be `wss` and it's in the port 443.

Also, keep in mind, that Java doesn't fully like let's encrypt as a CA so it might not work for non *.now.sh domains...

**Comment by purplecones** [comment]
@jamo @matheuss  Was troubleshooting with @LucaAndrei and it appears to be an issue with the Android client or some config setting. I was able to successfully connect to his app via websocket using https://www.npmjs.com/package/ddp-client

**Comment by leo** [comment]
@purplecones Nice! 😊 Great to hear.

**Comment by theshook** [comment]
Hi! how did you solve the problem?

I'm facing the same problem I have a meteor app and android app...
but the data doesn't change

**Comment by perrosnk** [comment]
I am facing the same issue.
I am developing with react-native, and when I test on older Android versions (API < 20) I cannot connect to the server. It works fine on newer android versions.
The most weird thing is that I can connect to a graphcool endpoint (wss) even when I use older android versions, but I cannot connect to my server which is hosted on zeit.now.
Has anyone found a solution?

**Comment by jamo** [comment]
How did the connection fail? What's the error you get?

Some older java versions didn't use to like the Lets Encrypt certificate authority. 
The solution around this is to use a custom ssl certificate.

**Comment by theshook** [comment]
I used this package to solve my problem, https://github.com/delight-im/Android-DDP/blob/master/README.md but some device couldn't connect to the websocket same issue with this guy


https://github.com/delight-im/Android-DDP/issues/146#issuecomment-367050116

**Comment by perrosnk** [comment]
The error I get is "Connection closed by peer".

**Comment by faystart** [comment]
yes, some app need websocket, such as ariaNG, it failed
