### ISSUE TITLE
Now app starts in background, starts a LOT of stuff and looks bad to Windows

### ISSUE THREAD

**Issue by shanselman** [vercel/vercel#391]
Now app starts in background, starts a LOT of stuff and looks bad to Windows.

Happy to talk about this but you might want to rethink:

- Starting it up by default
- How it shells out to a bunch of stuff

![image](https://cloud.githubusercontent.com/assets/2892/24066300/6c226440-0b2e-11e7-83a3-8f82094d20ed.png)

**Comment by leo** [comment]
Do you get the same result of apps like Slack?

**Comment by shanselman** [comment]
@leo I don't run Slack. Are you saying this is an Electron thing? I will ask the folks at Microsoft who own TaskManager to see what it THINKS is happening. And maybe @haacked can offer Electron thoughts?

**Comment by leo** [comment]
@shanselman I'm sure it's electron. This is how it looks on macOS:

<img width="815" alt="screen shot 2017-03-19 at 17 27 51" src="https://cloud.githubusercontent.com/assets/6170607/24082643/6510376c-0cc9-11e7-8d34-baf9949d917a.png">

By default, electron already spawns a few processes depending on how many resources it needs.

**Comment by matheuss** [comment]
@leo I don't think we should close it – I never saw that many processes when I was preparing the Windows version.

Why there's two (even one) `Windows Command Processor` there? Why there's two `Now` without our icon? 🤔

**Comment by leo** [comment]
@matheuss Well, we can't really do anything about this. We're not spawning any special processes by ourselves. The amount of processes depends on the resources electron needs on your machine (depending on your device's specs).

Besides of that, it shouldn't be re-opened here in any case ([now-desktop](https://github.com/zeit/now-desktop) is the repo). But like I said, completely independent from that, it's out of our control... 😄

**Comment by matheuss** [comment]
Uhhh I didn't notice it was on the wrong repo. Anyways, I do think it's under our control. 
The Command Processer, for example, we spawn upon instalation of the binary. However, it shouldn't live for more than a couple of seconds nor be spawned two times 🤔

**Comment by leo** [comment]
@matheuss An update is happening.

**Comment by shanselman** [comment]
Please note that this isn't Task Manager. I know that Electron is crazy, process-wise. This is the Task Manager STARTUP tab.
