### ISSUE TITLE
Trouble parsing now.json with CRLF line endings and/or UTF-8 BOM.

### ISSUE THREAD

**Issue by MatthewKing** [vercel/vercel#393]
I had been having some issues doing a dockerfile deploy when making use of `now.json` for extra configuration. I'm on Windows, using the Windows binary.

I was getting the following error message:
```
Error: Failed to read JSON in "C:\path\to\my\app/now.json"
    at readMetaData (C:\thebox\home\travis\build\zeit\now-cli\lib\read-metadata.js:37:17)
```

I was using `CRFL` line endings and `UTF-8 with BOM`.
Changing `now.json` to use `LF` line endings and `UTF-8` fixed my issue.

I think that supporting `CRLF` would be a good feature for Windows users.

Cheers

**Comment by leo** [comment]
@MatthewKing Do you have any idea how we can make `JSON.parse()` support this? Or is `fs.readFile()` the root of all evil?

**Comment by MatthewKing** [comment]
I'm not entirely sure, as I'm not familiar with the APIs, but I will have a poke around and send a pull request if I work it out.

Maybe documenting the work-around could be useful.

**Comment by leo** [comment]
@MatthewKing Looking forward to a PR, thank you! We currently don't have a place for documenting this special edge case and I'd rather fix it before we push people to change their code.

**Comment by MatthewKing** [comment]
Just investigated this further.

Seems that `CRLF` is actually fine - the problem was the encoding.
UTF-8 _with_ BOM causes the issue, while UTF-8 _without_ BOM works as expected.

As per http://stackoverflow.com/a/24376813/286936, it seems `readFile()` does not strip byte-order marks, but `JSON.parse()` requires input without byte-order marks.

Two workarounds are suggested in the StackOverflow answer. Of those, I think the first is the simplest -
replace the byte-order marks (`replace(/^\uFEFF/, '')`) before calling `JSON.parse()`.

I'm not really familiar with the node ecosystem so I had trouble putting together a PR with a full test suite etc. but hopefully at least this issue points someone in the right direction.

Having said that, it's not a particularly important fix, especially given that the use of a BOM is neither required nor recommended for UTF-8.

Cheers.

**Comment by leo** [comment]
> Having said that, it's not a particularly important fix, especially given that the use of a BOM is neither required nor recommended for UTF-8.

If it's not recommended, we shouldn't support it... 😊 

Thanks for the investigation!
