### ISSUE TITLE
Subtle exit when deploying

### ISSUE THREAD

**Issue by matheuss** [vercel/vercel#396]
![image](https://cloud.githubusercontent.com/assets/4721750/24230978/bcc16492-0f60-11e7-9e7e-c3fd8487e2c8.png)

I didn't make any changes between each `now` nor before the first one – so I'd guess it has something to do with it 🤔

**Comment by leo** [comment]
What? 😄 I don't get it. What's the problem?

**Comment by jamo** [comment]
Isn't it working as expected; no changes -> we return the old deployment URL?

**Comment by matheuss** [comment]
Should it just exit like that? It says `Initializing...` and then nothing 🤔 Gives the impression of being broken to me 🤔

**Comment by jamo** [comment]
agreed, the ux could be better

**Comment by leo** [comment]
Let's say:

> **Finished deploying!** No files have changed.

...in a new line prefixed with `>`.

**Comment by matheuss** [comment]
Using the `info` helper 👌👌👌

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
