### ISSUE TITLE
If remote build / start has an error code, shouldn't the cli exit with non 0?

### ISSUE THREAD

**Issue by mattapperson** [vercel/vercel#398]
When running a deployment, if something does not deploy correctly on the server due to a missing dep or npm not working right (hey, it happens)... IMHO the CLI should exit with a non zero.

Currently the log output will show npm exiting with non zero... but then things just keep going right along...

**Comment by frolic** [comment]
Just ran into this. Ran `now && now alias` and ended up deploying an app that wouldn't build and the domain ended up 404ing.

**Comment by hgascoigne** [comment]
Just started using now with CI, ran into the same issue. Would love if this could be fixed!

**Comment by leo** [comment]
@nkzawa You're the logs expert right? I think this is very important for CI so if you can tackle this, please go ahead! 🤓

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
