### ISSUE TITLE
now with xargs immediately exits

### ISSUE THREAD

**Issue by remy** [vercel/vercel#403]
To tidy up old unused deployments, I run a custom script called `now-no-alias` and I pluck the `uid` and `now rm` them.

The workflow is:

```
$ now-no-alias | json -a uid | xargs now rm
```

This used to work, and it would prompt me with `[Y/n]` to remove the deployments. Except, now it doesn't.

When I run it through a pipe from `xargs` it exits (success) without doing anything:

<img width="763" alt="screen shot 2017-03-25 at 14 14 24" src="https://cloud.githubusercontent.com/assets/13700/24322969/a1fc175e-1165-11e7-836f-7e7366bbac1d.png">

I'd love to see this fixed again…though I've no idea what `now` is looking for to make this fail the way it is.

**Comment by TooTallNate** [comment]
You need to use the `--yes` flag. i.e.

```
$ now-no-alias | json -a uid | xargs now rm --yes
```
