### ISSUE TITLE
Can't run now-cli on PC

### ISSUE THREAD

**Issue by fallen90** [vercel/vercel#406]
I installed `now` on my windows 10 pc and after an update, it always say 

![screenshot_51](https://cloud.githubusercontent.com/assets/1125255/24352826/9ecac102-131d-11e7-891f-cc09a7ff624b.png)

OS: Windows 10
Node Version: v6.9.5

> `now` is bundled from `now-desktop` for windows

**Comment by igorklopov** [comment]
Is your Windows 32 bit or 64?

**Comment by igorklopov** [comment]
Also please run `certutil -hashfile now.exe` against `now` executable that causes that error message.

**Comment by leo** [comment]
No answer for 15 days

**Comment by hutch120** [comment]
I'm also getting the message `This app can't run on your PC`. It keeps poping up every minute or so after launching the toolbar menu app.

Versions:
```
OS: Windows 10 pro 64 bit
Now: 1.2.3
Node: v6.9.5
```

Ran this: certutil -hashfile now.exe
```
SHA1 hash of file now.exe:
fb ff 64 3c 3e 46 70 a8 c7 d2 3d e5 c3 85 d9 5c df dd 29 6e
CertUtil: -hashfile command completed successfully.
```

**Comment by indcoder** [comment]
@leo Please open this issue ....I too have got the same error...I downloaded Now Desktop 2.3.5 and I'm getting the following error on my Win 10 Pro 64 bit
Node version : 7.4.0

λ certutil -hashfile now.exe
SHA1 hash of file now.exe:
d17c6509c92822121abcd37b799e675e0b32d330

Is there any way we can gets logs of now?

![image](https://user-images.githubusercontent.com/2099300/29573383-75b95638-877c-11e7-9ba0-0fb467c5d866.png)

**Comment by leo** [comment]
Have you installed the binary through Now Desktop or did you just download Now Desktop expecting it to replace the binary automatically? 😊

**Comment by indcoder** [comment]
Here's the thing @leo . As @hutch120 mentioned when we click on the Now Desktop , we get that error...no interface is even presented to us to download ....we just get  that Win10 error message.

**Comment by leo** [comment]
Oh. So Now Desktop doesn't work? Not Now CLI.

**Comment by indcoder** [comment]
Actually both....even typing cli in the terminal gives the same issue

**Comment by esslamben** [comment]
Also running into this issue.

**Comment by indcoder** [comment]
@Esslamb I had to redo npm global install of now for the problem to go away. YMMV.

**Comment by esslamben** [comment]
@indcoder I just tried to remove it, it gave me some trouble so I removed it manually and re installed but still the same. The prompt just launches and then it prints access is denied.  Any ideas ?

**Comment by indcoder** [comment]
@Esslamb  which version are you running? I have got 7.3.1 but this issue cannot be resolved till we know what the logs are saying @leo Where does now-cli log to default when initializing?

**Comment by esslamben** [comment]
I tried installing the CLI alone without the desktop app but I still run into the same smart screen issue.

**Comment by itaditya** [comment]
Same issue, can't run now from CLI 
![image](https://user-images.githubusercontent.com/15871340/31042210-2de75320-a5c0-11e7-83bb-048524348e5b.png)

I'm running Win7 32-bit

**Comment by leo** [comment]
Can someone confirm if this is still broken or fixed?

**Comment by esslamben** [comment]
I will DL the latest version and try tonight @leo I uninstalled the CLI my windows machine due to the problems and just used my mac so hopefully, it's fixed.

**Comment by esslamben** [comment]
@leo This seems fixed for me mate no more smart screen warnings. Thanks!

**Comment by Qix-** [comment]
Going to optimistically close then, then :) Thanks for the confirmation @Esslamb!

**Comment by marianadeveloper** [comment]
https://user-images.githubusercontent.com/15871340/31042210-2de75320-a5c0-11e7-83bb-048524348e5b.png
Same issue, can't run now from CLI.
I'm running Win7 32-bit.
