### ISSUE TITLE
DNS verification OK even when DNS record missing

### ISSUE THREAD

**Issue by sedubois** [vercel/vercel#411]
The now CLI won't complain even if the DNS records are completely empty (tested with CloudFlare DNS). I'd expect it complain if the DNS can't resolve the concerned domain.

<img width="958" alt="screen shot 2017-04-01 at 16 43 39" src="https://cloud.githubusercontent.com/assets/4217871/24579255/67b2dfe8-16fa-11e7-8ad8-b2b673eb84d2.png">

```
$ now alias my.domain -r rules.json 
> my.domain is a custom domain.
> Verifying the DNS settings for my.domain (see https://zeit.world for help)
> Verification OK!
```

**Comment by OlliV** [comment]
This might have been a caching issue. The whole verification is now implemented differently.
