### ISSUE TITLE
"Error: Bad request" when running "now" in a static site folder

### ISSUE THREAD

**Issue by irrigator** [vercel/vercel#413]
After turning on the debug flag, I got the following log:

```
> [debug] No manifest files found, assuming static deployment
> [debug] locating files /Users/zjy/Code/play/static: 5.129ms
> [debug] Getting files: 14.517ms
> [debug] Computing hashes: 5.093ms
> [debug] /now/create: 1332.563ms
> [debug] error: Error: Bad request.
Error: Bad request.
    at Now.<anonymous> (/usr/local/lib/node_modules/now/build/lib/index.js:208:21)
    at Generator.next (<anonymous>)
    at c (/usr/local/lib/node_modules/now/build/lib/index.js:775:99)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Looking into the related code, I found that the post request to /now/create is the source of the error. However, I was properly logged in and the setup is just a static index.html. What went wrong?

**Comment by leo** [comment]
Should be working now! Seems like a temporary error.

**Comment by irrigator** [comment]
Just tried. Not working. I've logged in again and do have a token in ~/.now.json.

**Comment by leo** [comment]
What's the content of your `index.html`?

**Comment by irrigator** [comment]
```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>

<body>
  <h1>This is pretty cool!</h1>
</body>

</html>
```

**Comment by irrigator** [comment]
I think the post params sending to /now/create might be helpful. I console.log it out before the fetch request.

> Deploying ~/Code/play/static
> [debug] No manifest files found, assuming static deployment
> [debug] locating files /Users/zjy/Code/play/static: 4.785ms
> [debug] Getting files: 14.171ms
> [debug] Computing hashes: 1.616ms
{ env: {},
  public: undefined,
  forceNew: false,
  forceSync: false,
  name: 'static',
  description: undefined,
  deploymentType: 'npm',
  registryAuthToken: undefined,
  files:
   [ { sha: 'eb652bf1935bf54c48c12fd4d70424874eb92cc1',
       size: 141,
       file: 'package.json',
       mode: 33261 },
     { sha: '318bfc8ea0adaaa59c6724ff64077afaf347be04',
       size: 285,
       file: 'content/index.html',
       mode: 33188 } ],
  engines: undefined }
> [debug] /now/create: 1470.226ms
> [debug] error: Error: Bad request.
Error: Bad request.
    at Now.<anonymous> (/usr/local/lib/node_modules/now/build/lib/index.js:212:21)
    at Generator.next (<anonymous>)
    at c (/usr/local/lib/node_modules/now/build/lib/index.js:779:99)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> Error! Bad request.

Anything wrong with the params that make it a "bad request"?

**Comment by jamo** [comment]
Could you try with another email address?

**Comment by irrigator** [comment]
Using a Gmail account and everything works! The failed attempt is using a email provider located in China ( yeah.net ) and I guess that's the problem. Thanks very much for your help.

**Comment by kabbi** [comment]
I have the same problem
```
> Deploying ~/(path here)/build under userdima@gmail.com
> [debug] Detected `deploymentType` = `static`
> [debug] locating files (path here)/build: 36.431ms
> [debug] Getting files: 46.509ms
> [debug] Computing hashes: 38.617ms
> [debug] /now/create: 3354.328ms
> [debug] error: Error: Bad request.
Error: Bad request.
    at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:413:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
> Error! Bad request.
```
I've tried re-authorizing, and now-desktop has the same error. I'm using gmail email and corporate internet.

**Comment by AHurnell** [comment]
@kabbi I have the same problem at the moment it has only just started with no changes to my project. I suspect the zeit system is down at the moment.

Using the --debug flag gives a similar result to the OP in this thread.

**Comment by MarcL** [comment]
@VolitionComponents - I've just tried at the moment too but with a Node.js server. Same thing. Feels like there might be issues at the ZeitHQ end perhaps?

**Comment by kabbi** [comment]
Yep, I found the status notification on [zeit_status](https://twitter.com/zeit_status). Sorry for the fuss, I'll always check cloud status pages when posting issues like that.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
