### ISSUE TITLE
Seems electron couldn't get correctly installed on now.sh server

### ISSUE THREAD

**Issue by amio** [vercel/vercel#417]
I have [an app](https://pageshot-giyodcosyi.now.sh/?url=https%3A%2F%2Fgoogle.com) works smoothly on my local machine, while on server it just return 502 error:
![image](https://cloud.githubusercontent.com/assets/215282/24688496/e7da19a2-19f2-11e7-825a-92e3978f2017.png)

Using `process.on('uncaughtException', () => {})` I got this:
```
Error: spawn /home/nowuser/src/node_modules/electron/dist/electron ENOENT
```

Seems electron couldn't get correctly installed on now.sh? In my case, I'm using [nightmare](https://www.npmjs.com/package/nightmare) which depends on [electron](https://www.npmjs.com/package/electron).

**Comment by jamo** [comment]
I guess the general purpose npm deployment is lacking some native dependencies; the easiest way around it would be to use a custom dockerfile

**Comment by amio** [comment]
@jamo Thanks for the hint!

I'm trying with the dockerfile way, it feels harder to debug though >. <

Is there any plan on fixing these native dependencies? It's delightful working with nodejs on now.sh 😭

**Comment by jamo** [comment]
I think electron is rare dependency for a web server so I don't think we see native support for it in our npm images...

Once the Dockerfile is running locally, and it exposes only one port, it's really likely to work as a now deployment w/o any issues

**Comment by amio** [comment]
If it's because "the general purpose npm deployment is lacking some native dependencies", then it would be a problem for all native module IMHO, not just electron. There's many package for web server would requires native dependencies.

Besides, I think a node app would consume less platform resource in nodejs than launching a container.

BTW, is the supported native dependencies picked up by hands?

**Comment by amio** [comment]
I've found the problem, electron was installed correctly while lacking some runtime dependencies:
https://github.com/electron/electron/issues/6945

Indeed it's not a good idea to run electron on server :(

**Comment by upupming** [comment]
Same issue here and this is my [repo](https://github.com/upupming/hit-gpa) which is using Nightmare, I have to give up it now.
