### ISSUE TITLE
Cannot deploy apps, can't fix because I can't see the logs either

### ISSUE THREAD

**Issue by nriesco** [vercel/vercel#420]
Apps are getting stucked while deployed and no logs are shown, so it is virtually impossible to fix any (possible) errors.

After trying to add https://github.com/berzniz/now-logs the app couldn't deploy so I blindfolded here and can't use the service.

Please help.

https://zeit.co/nriesco/legal-bot/kgthjywkey?redirect=1

**Comment by jacobmischka** [comment]
I also can't seem to successfully deploy a docker app. https://last-end-yjorwewqww.now.sh

Source: https://github.com/jacobmischka/last-end

It's using [tiangolo/uwsgi-nginx-flask:flask-python3.5-index-upload](https://github.com/tiangolo/uwsgi-nginx-flask-docker/blob/master/flask-python3.5-index-upload/Dockerfile) which is mostly just a wrapper over [tiangolo/uwsgi-nginx-docker](https://github.com/tiangolo/uwsgi-nginx-docker/blob/master/python3.5/Dockerfile).

**Comment by jamo** [comment]
Looks like the last-end exports multiple ports; we pick the first port reported by docker -- which in this case seems not to be the intended one - as it just returns an "empty response"

**Comment by jamo** [comment]
That other deployment doesn't anymore exist and hence I can't look into it. logs support will eventually come - but for now we are suggesting use of third party logging solutions: like papertrail...

**Comment by jacobmischka** [comment]
Ah, I thought that was the problem, but I thought my EXPOSE was supposed to override the parent Dockerfile EXPOSE. I see now that that's not how that works.

Thanks for your help!

**Comment by jacobmischka** [comment]
Confirming that that was it. A bit of a pain that docker doesn't provide any way to override EXPOSE from a child container, but forking the upstream containers to only expose 80 worked.

Thanks again!

**Comment by jamo** [comment]
Great to hear you got it working. Indeed that behavior from docker is unexpected...
