### ISSUE TITLE
404 on dynamic routes in monorepo with now dev

### ISSUE THREAD

**Issue by baukevanderlaan** [vercel/vercel#4239]
# Bug report

## Describe the bug

When running Next.js in a subfolder of a monorepo, dynamic routes trigger a 404 when running `now dev`. This only happens when the route is directly loaded (using the url or refreshing the page). It does not happen when you navigate clientside using `<Link>`. Redirects are specified in the now.json to make it work with a monorepo.

## To Reproduce

Repo: https://github.com/baukevanderlaan/now-next-dynamic-404

1. `npm install` in the `web` folder
2. `now dev` in the root
3. Click a link to a dynamic page
4. Refresh the page to get a 404

## Expected behavior

No 404.

## System information

- OS: macOS
- Next.js: 9.3.4
- Now CLI: 17.1.1

**Comment by takexii** [comment]
hello,

i got same problem. and could be resolved without `rewrites` at `now.json`

1. open vercel console.
2. change configration `other => Next.js` at `Setting => Project Settings => General => Build & Development Settings => Framework Preset`
3. `npm run dev`

```
// package.json

"scripts": {
  "dev": "vercel dev"
},
```

i hope this helps you.
thank you

**Comment by baukevanderlaan** [comment]
Thanks your input Takeshi! 

If I’m not mistaken, that would work only if the repository contains nothing but a Next.js app. In my case I have a monorepo with different apps that I’d like to deploy all at once.

**Comment by gustavlrsn** [comment]
I'm having the same issue with dynamic routes 404'ing in a monorepo setup.
This is my now.json, which has been working fine up until recently. Wondering if I'm missing some crucial "routes" config, but can't figure it out from the docs.

```
{
  "version": 2,
  "builds": [
    { "src": "ui/next.config.js", "use": "@now/next" },
    { "src": "api/index.js", "use": "@now/node" }
  ],
  "routes": [
    { "src": "/api", "dest": "/api/index.js" },
    { "src": "/(.*)", "dest": "/ui/$1", "continue": true }
  ],
}
```

**Comment by stevez86** [comment]
@paulogdm Could this be the issue? 

https://github.com/zeit/next.js/issues/12851#issuecomment-628854147

I wasn't having 404s but was getting unexpected params when I switched to getStaticProps for nextjs. I'm setup similiarily to @gustavlrsn 

Issue includes a repro and a link to the params.

**Comment by baukevanderlaan** [comment]
I think I encountered a related problem which makes an error occur in _production_ as well:

- I have a monorepo with a Sanity studio and a Next.js app with a now.json that's similar to the one in the reproducible repo I made in the initial post.
- The Next.js app uses the new Preview Mode (`pages/api/preview.js`) to redirect a preview request from the Sanity studio to the correct dynamic route.
- Using the Preview functionality within `now dev` results in a `404` which I kind of expected since I'm directly accessing the dynamic route, see also my initial post.
- But using the Preview functionality in production now results in a `500 internal server error`, which is new for me, since I didn't had any problems in production until I implemented the Preview Mode.

I hope the above is of any help.

**Comment by stevez86** [comment]
@baukevanderlaan Could you check the value of the dynamic params in getStaticProps at runtime? 

I was getting 500 errors whenever the page tried to render at runtime because the dynamic parameter was an array instead of a string, but this didn't happen at build time. Here's an example: https://my-app-l93z01gn0.now.sh/abc/a (repro code: https://github.com/stevez86/next-repro) There appears to be a routing issue with now / next especially when the page is an `index.js` file inside of a dynamic folder `[slug]`

**Comment by baukevanderlaan** [comment]
@stevez86 Thanks for your input! Do you mean running getStaticProps in `now dev` when you say getStaticProps at runtime? If I try that, I get a string like I expected. I’m not sure if your issue is the same as this one.

**Comment by stevez86** [comment]
@baukevanderlaan I mean running getStaticProps at runtime when `fallback: true` and/or `unstable_revalidate: 1`. I think the feature is still being ironed out and appears to be unrelated, apologies if this off topic / unhelpful.

**Comment by iameli** [comment]
We're encountering this as well. Something's not playing well with monorepos.

My static pages render fine, but any dynamic or server-side rendered pages 404 immediately.

Our now.json file is right here: https://github.com/livepeer/livepeerjs/blob/master/now.json

**Comment by jeantil** [comment]
I was checking out the next.js examples when I stumbled on [`with-zone`](https://github.com/vercel/next.js/tree/canary/examples/with-zones). 

This example is very interesting,it sports : 
- a `vercel.json`
- 2 nested nextjs apps  (`/blog` and `/home`)
- a dynamic route in `/blog`
- it uses `routes` instead of the more recent `rewrites` 

Where it becomes really intriguing : 
- the dynamic route in `/blog` works just fine
- adding a dynamic route in `/home` triggers the 404 
- switching from routes to rewrites totally breaks `/blog` (dynamic and fixed routes both)

Thats with the latest vercel release which includes https://github.com/vercel/vercel/pull/4644

**Comment by baukevanderlaan** [comment]
@jeantil @styfle

Looks like you worked a lot on this, thanks!

Unfortunately when I installed `now@19.1.2-canary.3` just now, I found no improvements when running `now dev` in the repo from my first post. Should we reopen this?

**Comment by jeantil** [comment]
@baukevanderlaan I understand the confusion, the issue was in the `@vercel/next` builder. by installing  `now@19.1.2-canary-3` you upgraded the `cli` package but by default it is still going to pull normal releases of the builders. 
change your `{now,vercel}.json` to use `@{now,vercel}/next@canary` instead of `@{now,vercel}/next` for your next js build and the issue should be resolved.

**Comment by baukevanderlaan** [comment]
@jeantil Of course, thanks! That resolves the `now dev` issue!

Do you think it's also connected to this similar thing I found in production? https://github.com/vercel/vercel/issues/4239#issuecomment-629129343

I don’t have the time at the moment to set up a small repo and test it myself, but if you think it's unrelated or #4510 doesn't resolve it, I'll create a seperate issue so we can keep this closed.

Thanks again!

**Comment by jeantil** [comment]
#4510 doesn't touch anything with regards to production behaviour and clearly there are issues which remain, see https://github.com/vercel/vercel/pull/4510#issuecomment-645978269 and I think are related to https://github.com/vercel/next.js/issues/12851

I am not sure it would be related to your preview issue though : we use preview too with prismic and haven't encountered any such issues.

**Comment by liamdanielduffy** [comment]
For anyone finding this thread, modeling their monorepo after this example:
https://github.com/vercel/next.js/tree/canary/examples/with-zones

I replaced `blog` and `home` with the folders `old` and `new`

I was able to get dynamic routes working by adding `"continue": true` to my `vercel.json` `"routes"` config, like so:

```
    { "src": "/new/_next(.*)", "dest": "new/_next$1" },
    { "src": "/login(.*)", "dest": "new/login$1" },
    { "src": "/(.*)", "dest": "old/$1", "continue": true }
```

**Comment by moelashmawy** [comment]
> 
> 
> For anyone finding this thread, modeling their monorepo after this example:
> https://github.com/vercel/next.js/tree/canary/examples/with-zones
> 
> I replaced `blog` and `home` with the folders `old` and `new`
> 
> I was able to get dynamic routes working by adding `"continue": true` to my `vercel.json` `"routes"` config, like so:
> 
> ```
>     { "src": "/new/_next(.*)", "dest": "new/_next$1" },
>     { "src": "/login(.*)", "dest": "new/login$1" },
>     { "src": "/(.*)", "dest": "old/$1", "continue": true }
> ```

Thank you so much, it took me long time solving this issue
