### ISSUE TITLE
Show a meaningful message when trying to add an external subdomain

### ISSUE THREAD

**Issue by matheuss** [vercel/vercel#427]
Currently we have:

```
▲ ~ now domains add --external something.google.com
> Error! Not authorized to access domain something.google.com
```

We should have:

```
▲ ~ now domains add --external something.google.com
> Some message that tells you to not add the subdomain, but the actual domain instead
```

**Comment by hawkins** [comment]
I'd be happy to take this on as my first contribution to `now` :smile:

**Comment by melvin0008** [comment]
I think this was resolved in commit https://github.com/zeit/now-cli/commit/2a50c2bd7f6247bddb1df3bee420573d26f05560#diff-d7b946ada4331cbb4103ebc18442f52aR300

**Comment by Qix-** [comment]
Thank you @melvin0008, looks great :)
