### ISSUE TITLE
DNS service/CLI does not support multiple TXT records on a single domain

### ISSUE THREAD

**Issue by colinbate** [vercel/vercel#429]
If I try to add multiple TXT records for the same name under a domain (`@` for example), it just overwrites the old value with the new. You should be able to add multiple TXT records as long as the values are different.

**Comment by leo** [comment]
@OlliV ^

**Comment by OlliV** [comment]
Oh github closed it automatically 🤔 Well, anyway it should be fixed by now.

**Comment by leo** [comment]
Sweet! ☺️
