### ISSUE TITLE
`now alias` hangs when finishing

### ISSUE THREAD

**Issue by jacobmischka** [vercel/vercel#430]
Running `now alias` does work correctly, but it never seems to return me to my shell, I always need to `^C` after the command finishes. It happens both with custom domains and with now.sh aliases.

It *does* return me to my shell correctly if the alias fails, but not when it succeeds.

I thought an issue existed for this already, but I just checked and couldn't find it. Apologies if I missed it.

- Arch Linux x64
- Bash shell
- now 4.10.3

```
> Success! Alias created ... [copied to clipboard]
> [debug] closing agent
^C
$
```

```
> [debug] #1 POST /domains: 26636.216ms
> Error! Verification required: Please add the following TXT record on the external DNS server: ...
$
```

Please let me know if there's anything else I can provide!

**Comment by floatdrop** [comment]
@jacobmischka can you check `5.1.0` version? It should fix this issue.

**Comment by jacobmischka** [comment]
It is fixed indeed! Thanks, and really great work with everything else in v5 zeit team! 🎉

**Comment by kristianmandrup** [comment]
I have the same problem. No matter what command I issue, now just hangs and won't complete any command. #548 

```
$ npm i -g now
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated isarray@2.0.1: Just use Array.isArray directly
/usr/local/bin/now -> /usr/local/lib/node_modules/now/build/bin/now.js
/usr/local/lib
└── now@5.3.0 

✔ ~ 
20:25 $ now help
> 
✘-1 ~ 
20:25 $ 
```
