### ISSUE TITLE
Feature Request: Restarting a deployed app

### ISSUE THREAD

**Issue by mjsisley** [vercel/vercel#433]
There doesn't appear to be a way to restart a deployed process (similar to `heroku restart`).

**Comment by leo** [comment]
Deployments are immutable. You need to deploy again! 😊

**Comment by xdamman** [comment]
Mmmm... how is the fact that deployments are immutable related to not being able to restart?
Am I missing something?

It's quite annoying especially when you have memory leaks in the app.
(Also deploying can take a long time.)

**Comment by cdcv** [comment]
I agree that a restart function is important.

**Comment by larafale** [comment]
what happen in a case of a crash ?  any best practices ?

**Comment by sergiodxa** [comment]
@larafale Now will automatically restart your deployment if it crashed

**Comment by hirako2000** [comment]
it doesn't seem to automatically restart on crash/hangs.
Today I observed two scenarios, the app could not get hold of a port, kept trying. I had to redeploy (no restart feature)
Now I see it hanging after getting unfrozen, trying to pull deps. it hang like this for 45mins

```
...
Installing package pm2@^2.6.1
08/10 12:46 AM (15m)
Installing package supertest@^3.0.0
08/10 12:46 AM (15m)
Installing package xo@^0.18.2
```

**Comment by OlliV** [comment]
Are you sure you are not listening on multiple ports? You can DM me (hbp) in slack.

**Comment by grumpygary** [comment]
I know this is closed, but the feature is important!  I load certain settings from a remote DB.  If I change (rarely, but it happens) those I need to to recycle the deployment (in which nothing has changed).  I can add an endpoint to exit and let now restart it, but that's dangerous.

Strange to me that you find this to either be unimportant or too difficult to implement -- seems like just a kill cmd.

**Comment by OlliV** [comment]
the closest you can do right now is:

```
now scale <url> 0
now scale <url> <origMin> <origMax>
```

**Comment by grumpygary** [comment]
Yeah, I figured that out.  I still think "now.sh restart deployment | url"
is simpler and more obvious.  That said; I can use "scale" to accomplish it.
