### ISSUE TITLE
Attempted to require @now/next@latest, but it is not installed

### ISSUE THREAD

**Issue by Vadorequest** [vercel/vercel#4332]
# Bug report

## Describe the bug

Running `yarn start` fails.

```
yarn start
yarn run v1.22.0
$ now dev --listen 9999
> UPDATE AVAILABLE Run `yarn add now@latest` to install Now CLI 19.0.0
> Changelog: https://github.com/zeit/now/releases/tag/now@19.0.0
> Now CLI 16.7.3 dev (beta) — https://zeit.co/feedback

Nothing happens (hangs)
```

I can't start my app since yesterday. I thought there was something blocking the port, but killing processes running on that port had no effect.

I don't understand why this is failing now, it used to work fine and the app's source code itself has not changed much.

## To Reproduce

Run `yarn start`

`yarn start` is bound to `now dev --listen 8888`

## Expected behavior

Should start the local server.

## System information

- OS: MacOS

**Comment by Vadorequest** [comment]
Thanks timer, FYI I also sent a support request to Vercel.

**Comment by styfle** [comment]
Thanks! This was fixed in [19.0.1](https://github.com/zeit/now/releases/tag/vercel%4019.0.1)

**Comment by Vadorequest** [comment]
Thanks @styfle, is it planned to bring the fix to `16.x`?

We don't want to use v17 due to NBC changes, because it requires to be auth to Zeit since this major version and I don't want that for my developers. (it's a security matter for us)

Also, I don't understand how it affected v16 without us upgrading it in the first place.

**Comment by styfle** [comment]
`@now/next` and other Runtimes fetch the latest version each time you deploy or run `now dev`. So any fixes to Runtimes will also be applied to all dev and prod deployments unless the user specifically pinned version in `builds` property.

What security matter is there with version 17? You have control to add or remove members from your team regardless of projects that are linked.

**Comment by Vadorequest** [comment]
@styfle Here is my discussion with Vercel support (Samuel Ko)

>I'm not exactly sure how connecting to their Vercel account means that they have access to make a change on there own, if they are not you (assuming your project is on a Vercel personal account), or if they are not part of the Vercel team with your project?
>
>"The now CLI v17 forces all users to link their local project to a Vercel project." -> This is true, but they can't link up to somebody else's Vercel personal projects, or a Vercel team if they have not been invited.
>
>Proposal:
>
>If you don't want users to have access to anything Vercel related, then have them relegated to only be pushing changes to GitHub. Only a sole person needs to be initiating deploys locally. 

---

> "The now CLI v17 forces all users to link their local project to a Vercel project." -> This is true, but they can't link up to somebody else's Vercel personal projects, or a Vercel team if they have not been invited.

So, I have to invite them to my Vercel team (we are a Team) so that they can link their local project to the Vercel project.
Once they've been invited to my Vercel team, they have many permissions on that team, including manual deployment and domain configuration (through GUI), right? So, once they're on the team, I lose control over what they can do.

On v17, they didn't need to be on the Vercel team at all, and they couldn't change domain config and production deployments. But now that I have to invite them, they can. And that's what I can't allow. 

Just to clarify, they don't deploy anything locally, and I rarely do. But running `now dev --listen 8888` requires to link the project beforehand and they can't work locally anymore without linking.

I don't understand your proposal, that's what we already do, they can push on github, that's it.

I feel like you're missing the fact that they can't work locally without linking, and that linking would automatically grant them too many permissions because they'd be part of the Vercel team. Am I misunderstanding something here?

**Comment by samcx** [comment]
@Vadorequest I sent a response in the support ticket.

**Comment by Vadorequest** [comment]
Thanks for the answer @samsisle. I'll post your answer below so that other people can benefit from it too and I'll answer both by email and here.

![image](https://user-images.githubusercontent.com/3807458/82085903-fb8da100-96ed-11ea-916e-fa2983530245.png)


---

I believe that's a (very) complicated/painful setup, and it also doesn't really match our needs.

The main problem I can foresee with this, is that it'll be necessary for those team members to use a different "scope", because we hardcode the scope in our now.json files for our CI to work properly. See https://github.com/UnlyEd/next-right-now/blob/v1-hyb-mst-aptd-gcms-lcz-sty/now.customer1.staging.json

So, that'd be necessary for them to ignore such changes and not commit/push them, and we both know this is meant to happen, and it'll break CI and deployments when it does. 

Those "team members" I'm mentioning are not experienced developers, they're designers, they're not git gurus like you and I. I want to keep it as simple as possible for them, and for me.

Proper permissions for team members is one way to go, but it's a long reach.

If nothing can be done to fix the issue properly, is it possible to fix the v16 CLI so that it doesn't crash when running the app locally? 
That's maybe the easiest way to go, and we'll keep using v16 until something better comes around.

Also, I'd like to mention that forcing linking has a bad side effect for "quick start" when using OSS especially, because before anybody could just clone and run it, now there is an intermediary step of creating an account and configuring local now/vercel credentials before running the app. 
It's not a great developer experience overall. (I can guess why you made that choice, just want to share the undesirable side effects)

**Comment by samcx** [comment]
I'm not familiar with why you need to hardcode the scope in your `now.json` files — is it because you have 2 different Vercel teams? Is it possible to have separate GitHub repos, so you don't need to use a scope option?

I don't think it will be possible for the team to go back and fix v16. I agree it is not the most pleasant experience that your case has made you stick with v16. I believe there were conversations on this linking topic before, such as this https://github.com/zeit/now/issues/3767.

**Comment by Vadorequest** [comment]
I do have different Vercel teams, and hardcoding the teamId in the scope ensures they get deployed where they're supposed to, even if I haven't selected the right account locally.

Also, it's necessary for Github Action, it needs to know which team it should deploy against.
