### ISSUE TITLE
Deploying doesn't read alias from *.json files

### ISSUE THREAD

**Issue by Dids** [vercel/vercel#434]
Either I'm doing something wrong, or the current version of `now-cli` doesn't read `alias` entries from either `package.json` or `now.json`.

Here's a `now.json` example:
```
{
	"name": "sli.ng",
	"alias":
	[
		"sli.ng"
	],
	"public": "false",
	"env":
	{
		"NODE_ENV": "production"
	}
}
```

Note that it does work when using the `--alias` flag for the cli, eg. `now --alias sli.ng`.
It also seems to be reading the rest of the values fine, so it's just the alias that's broken.

My end goal here is to have an automated way of pushing out a new deployment, then updating the alias/custom domain afterwards, without having to manually mess with anything.

**Comment by Dids** [comment]
Turns out I was just doing it wrong. Since `now -a` is deprecated, we now need to run `now alias` after running `now`.

**Comment by leo** [comment]
Correct!

https://zeit.co/docs/features/aliases
