### ISSUE TITLE
`--config` should be used for the local `now.json`, not the global `.now.json`

### ISSUE THREAD

**Issue by leo** [vercel/vercel#436]
In my opinion, we don't need to introduce another flag again for the global `.now.json` file (`--config` is being used for that at the moment) because we already have `-t` for specifying the token...

**Comment by jonscottclark** [comment]
Nice :) Looking forward to this as I build two different versions of my project and want to deploy them to different endpoints.

**Comment by jamo** [comment]
Who not to introduce a new flag for the project configuration containing `now.json`
Anyways, we should support flags for defining both `now.json` files. The one with auth and the one with project preferences.

**Comment by leo** [comment]
The question is: Why for the global one? Having two flags for setting config files will be really confusion, no matter how we'll call them.
