### ISSUE TITLE
Cannot deploy getting started example from next.js

### ISSUE THREAD

**Issue by inspiraller** [vercel/vercel#438]
**When using a getting started example from next.js**
This is literally an example from the getting started guide for next.js
I run the command from the root of where my package.json file sits:
$ now
> Error! Unexpected error. Please try later. (Cannot find module 'c:\projects\nextjs_gettingstarted\index.js')

**When I try running this also from the pages/ directory**
This does successfully publish but there is no root page. It's simply a directory reference to the index.js file.
here:
example: https://pages-apvnboahjx.now.sh

This is what my file dir looks like:
folders
```
nextjs_gettingstarted/
   node_modules/
   pages/
      index.js

   .gitignore
   package.json
   README.md
```
**.gitignore:**

.next/
node_modules/

**package.json**

{
  "name": "nextjs_gettingstarted",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "next": "^2.1.1",
    "react": "^15.5.4",
    "react-dom": "^15.5.4"
  }
}
**pages/index.js**

export default () => (
  <div>Welcome to next.js!</div>
)

**Comment by inspiraller** [comment]
**I've added it here for reproducing:**

https://github.com/inspiraller/nextjs_not_working

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
