### ISSUE TITLE
Show different OSS prompts based on the context

### ISSUE THREAD

**Issue by matheuss** [vercel/vercel#444]
1) User is on the OSS plan
2) User in on the OSS plan and uses `--public`
3) User in on the Premium plan and uses `--public`

Note that we should **always** ask for confirmation, no matter what context 👌

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
