### ISSUE TITLE
Warning! Requested node version 7.9.0 is not available 7.7.3

### ISSUE THREAD

**Issue by ciocan** [vercel/vercel#447]
Express does not support async. I was trying to do something like:
`server.post('/api/getApi', async (req, res) => {...`
The current version installed 7.7.3 does not support it, but with 7.9.0 it works.

Will you update node to the last one?

**Comment by leo** [comment]
7.9.0 is [not supported](https://zeit.co/docs/features/configuration#%60engines%60-(object)) at the moment!

But coming!

**Comment by jamo** [comment]
We just added support for 7.10.0 (also skipping 7.9.0)
