### ISSUE TITLE
[Question] Access fs before install

### ISSUE THREAD

**Issue by Kikobeats** [vercel/vercel#453]
I'm trying to deploy a project that uses [node-pre-gyp](https://www.npmjs.com/package/node-pre-gyp) as subdependency.

Because it needs compilate binaries, It tries to write in a folder called `.tmp` inside `node_modules`. Because this folder is no writable, the process fails:

```bash
(node:73) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, readlink '/home/nowuser/src/node_modules/.tmp/d0c1b86d-54c0-4291-ba5f-0f07a1cf1ea1/node_modules/node-pre-gyp'
> prebuild-install info begin Prebuild-install version 2.1.2
> prebuild-install info install installing inside prebuild-install directory, skipping download.
> sh: node-gyp: not found
> Error: Command prebuild-install || node-gyp rebuild ended with code 127
>     at ChildProcess.<anonymous> (/usr/lib/node_modules/@zeit/cace/build/lib/run.js:1:599)
>     at emitTwo (events.js:106:13)
>     at ChildProcess.emit (events.js:191:7)
>     at maybeClose (internal/child_process.js:877:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

I read documentation about setup `build` command for access to fs, something like:

```bash
"build": "ln -s /tmp node_modules/.tmp",
```

but because `build` command is executed after `install`, the error still exist.

How to handle this?

**Comment by albinekb** [comment]
I guess you could install during build? :joy: 
```json
"build": "ln -s /tmp node_modules/.tmp && npm install dep-that-needs-tmp",
```
? @Kikobeats @TooTallNate

**Comment by Kikobeats** [comment]
I suppose it could be works,  but sounds weeeeeeeeeeeird

**Comment by albinekb** [comment]
Maybe `preinstall` works? see https://docs.npmjs.com/misc/scripts

**Comment by Kikobeats** [comment]
@albinekb I think this depends of zeit/now limitations, not npm

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
