### ISSUE TITLE
[Question] - Relying on now stdout for aliasing

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#455]
I'm finding that I'm missing the deprecated `now --alias` functionality. For small projects without CI, I'd often have several package.json script for deploying to different unique URLs, such as:

```
{
  "name": "micro-auth",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "micro",
    "deploy-demo": "now --alias micro-auth-demo",
    "deploy-qa": "now --alias micro-auth-qa"
  }
}
```

Since the above no longer works, as an alternative I'm using the output stream from the `now` command, which is in fact the deployment URL, to accomplish the same by nesting the deployment within the new `now alias` command using backticks:

```
  "scripts": {
    "start": "micro",
    "deploy-demo": "now alias `now` micro-auth-demo",
    "deploy-qa": "now alias `now` micro-auth-qa"
  }
```

This wouldn't work on Windows, but is working fine in OSX as a simple solution for me.

Is there a better alternative available than this to accomplish the scenario above? Using `alias` config key(s) within `now.json` isn't ideal for me, because I often just want to deploy/alias one of the above environments.

**Comment by jamo** [comment]
I've myself ended up doing

```
cat package.json | jq '.now.alias[0] = .name + "-" + $SHA + ".now.sh"' --arg SHA `git rev-parse --short=5 HEAD` > package.json
```
in CI in order to include part of git sha to the alias
the sample relies on the `package.json` containing `.now.alias` in the array from but it may be easily modified...

**Comment by leo** [comment]
With our [GitHub Integration](https://zeit.co/blog/easier-now-github), this is not an issue anymore. Please try it out!
