### ISSUE TITLE
now alias failed for domain with external DNS (GoDaddy)

### ISSUE THREAD

**Issue by AndreyNikiforov** [vercel/vercel#459]
I am trying to setup alias for custom domain (serviced by GoDaddy). I am following [zeit doc](https://zeit.co/blog/domain-verification):

1. Created `CNAME` for `www` and pointed to `alias.zeit.co`
1. Removed `A` which was pointing to old hosting
1. Added `TXT` record with key from `now domain add --external` run

Now I am trying to alias my deployment to custom domain (id and domain obfuscated):

> C:\src\sample>now alias abcdefg0123456789 example.com
> example.com is a custom domain.
> Verifying the DNS settings for example.com (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for example.com
> Error! Unknown error: Error: Invalid challenge response for example.com. Make
 sure the DNS records are correct.
Error: Invalid challenge response for example.com. Make sure the DNS records ar
e correct.
    at retry (C:\thebox\home\travis\build\zeit\now-cli\lib\index.js:635:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

What am I missing?

**Comment by albinekb** [comment]
Yes you should not use `now domains` if you're not dealing with zeit.world domains.
Just do: `now alias <deployment> www.example.com``

:ok_hand: @AndreyNikiforov

**Comment by AndreyNikiforov** [comment]
@albinekb thanks for suggestion. I did the following (whole picture):

1. Setup forwarding on GoDaddy side for my domain to point to `https://www.example.com`
1. Add `CNAME www alias.zeit.co` on GoDaddy side
1. Use `now alias <id> www.example.com`

Testing four scenarios in browser:
1. Enter `http://example.com` redirects to `httpS://www.example.com` with 301 response and serves site - Good
1. Enter `http://www.example.com` redirects to `httpS://www.example.com` with 301 and serves site - Good
1. Enter `httpS://example.com` request timeout - Bad; should redirect to `httpS://www.example.com`
1. Enter `httpS://www.example.com` serves site - Good

It is much better than original situation. How to fix 3 from the list above?

**Comment by OlliV** [comment]
I would either alias both with `now alias` or use https://github.com/vdanchenkov/now-redirect

**Comment by AndreyNikiforov** [comment]
@OlliV Thanks for `now-redirect` link. That may be a good solution as I prefer not have naked/apex domain working other than for redirects.

I still don't understand why redirecting from `http://example.com` works out of the box, while redirecting `httpS://example.com` requires special treatment (e.g. `now-redirect`)

**Comment by OlliV** [comment]
I'm not familiar with GoDaddy but technically their redirect service is probably similar to `now-redirect`.

**Comment by AndreyNikiforov** [comment]
@OlliV How should I configure DNS (GoDaddy) to use `now-redirect` instead of their Forwarding service for apex domain?

For `www` it was easy - just add `CNAME www alias.zeit.co`.

**Comment by farookisonfire** [comment]
@AndreyNikiforov did you figure this out? I am running into a similar problem, trying to use Zeit w/ GoDaddy.

I want users hitting my root domain to be pointed to my Zeit deployment. Updating the CNAME record in GoDaddy only allows me to point users hitting a subdomain to my Zeit deployment.

In order to get users visiting the root domain to my Zeit deployment, I added domain forwarding with GoDaddy. But navigating to root domain goes to http: instead of https:

**Comment by OlliV** [comment]
That won't work. You'll need a DNS provider that supports ALIAS/ANAME records, I can't recall if GoDaddy supports that.

**Comment by farookisonfire** [comment]
Thanks for following up, Olli. I see... your right that as far as I can tell, ALIAS/ANAME is not supported. 

Is there another way you know of to get users visiting the root domain to be pointed to the Zeit deployment? 

I attempted this first by changing my domains name servers to Zeits. This actually worked great, but then I was getting an error when I later tried to add an MX record via the Now cli.

**Comment by 0xpatrickdev** [comment]
@farookkhan I was able to get it working with https by following this: https://www.godaddy.com/help/update-my-domains-ip-address-for-forwarding-5289

- add `CNAME` record for `alias.zeit.co`
- add `A` record for `50.63.202.1` (GoDaddy's forwarding service)
- add a forwarding record for the naked domain to `www.yourdomain.com`

**Comment by zequnyu** [comment]
@pcooney10 Can you specify how did you 'add a forwarding record for the naked domain to www.yourdomain.com'? Thanks.

**Comment by zequnyu** [comment]
I found it right under the 'Records' section in Godaddy's dashboard. And this blog is helpful: https://www.godaddy.com/help/manually-forwarding-or-masking-your-domain-or-subdomain-422.
