### ISSUE TITLE
Feature request: Add ability to adjust cache control

### ISSUE THREAD

**Issue by ro-savage** [vercel/vercel#465]
At the moment there doesn't appear to be a way to set the `cache-control` `max-age`.

It would be nice if there was an option to set a default `cache-control` `max-age`, and an option to pass filenames that should have no caching.

This way people deploying SPA can have index.html with `no-cache`, and all other files with longer caches. 

Currently it appears the cache is set to 3second by default?

There is a semi work around, if you use `now` to build an SPA and then in the `package.json` `now-start` use `serve`  you can add `--cache [time in ms]" option. However this will also apply automatically to index.html.

**Comment by jonikorpi** [comment]
Related: some way to pull off immutable assets would be super cool. Would make this a great way to host apps built with `next export`. :)

I'm currently using `serve ./out --cache 600000` to host an exported next app and it's working pretty nicely. Turning the generated assets immutable, as well as having a separate cache time for static assets and .html files would be a huge improvement though.

**Comment by leo** [comment]
Thank you for your suggestions, but we won't introduce any options for configuring static deployments. Like we mentioned it [earlier](https://zeit.co/blog/unlimited-static#no-limits-on-extensibility), you need to use [serve](https://github.com/zeit/serve) inside an npm deployment, if you want to configure such things! 😊
