### ISSUE TITLE
Route rewrite using pattern ($1) redirects to /$1

### ISSUE THREAD

**Issue by Vadorequest** [vercel/vercel#4692]
# Bug report

## Describe the bug

```
  "routes": [
    {
      "src": "/robots.txt",
      "dest": "/robots/!production.txt"
    },
    {
      "src": "/gem",
      "dest": "/",
      "status": 308
    },
    {
      "src": "/gem/(.*)",
      "dest": "/$1",
      "status": 308
    }
  ],
```

Using the following redirects `/gem/test` to `/$1` instead of `/test`.

I had tested the behaviour on an older version of Next.js and it did work properly at that time.
It failed me today, and the regression wasn't detected until the customers complained.

Using Next `9.2.1`. Deployed on Vercel.

I believe it used to work on v9.1. How should it be done nowadays?

**Comment by Vadorequest** [comment]
I thought it was a Next.js feature, my bad.

Did it got replaced by Next.js own experimental rewrites/redirects?

**Comment by paulogdm** [comment]
We recommend using rewrites, redirects, and headers instead of routes: https://vercel.com/docs/configuration#project/redirects.

However, Next.js is indeed implementing some routing features: https://github.com/vercel/next.js/discussions/9081

**Comment by Vadorequest** [comment]
Those Next.js features are still experimental. Also, it doesn't explain why it doesn't work on Vercel as it used to.

And, that project is running on Next.js 9.1 where those experimental features aren't available.
I fixed the issue by changing the routes rules, feel free to close this if you don't intend to fix it.
