### ISSUE TITLE
`now -t <token> domain buy myco.com` is not working

### ISSUE THREAD

**Issue by vinaypuppal** [vercel/vercel#474]
I tried `now -t <token> domain buy myco.com` but its falling back to my default now account and not respecting provided token account.

using now@5.0.0

**Comment by dsifford** [comment]
Same with `now -t $TOKEN ls` or `now -t $TOKEN deploy` etc.

Looks like the CLI still is expecting a username.

Below was ran while logged out, where `$TOKEN` is a valid API key.

```sh
$ now -t $TOKEN ls
> Error! Unknown error: TypeError: Cannot read property 'username' of undefined
TypeError: Cannot read property 'username' of undefined
    at /home/dsifford/.config/yarn/global/node_modules/now/build/bin/now-list.js:148:145
    at Generator.next (<anonymous>)
    at c (/home/dsifford/.config/yarn/global/node_modules/now/build/bin/now-list.js:254:99)
```
Of note, `now -t $TOKEN rm <deployment-id>` still seems to work fine.

**Comment by dsifford** [comment]
Looks like #484 partially addresses this. That same fix will have to be applied to the other commands as well.

@matheuss If you need a hand tackling this, I'd be glad to send a PR.
