### ISSUE TITLE
Error when attempting to alias a custom domain on `pro` plan

### ISSUE THREAD

**Issue by kidGodzilla** [vercel/vercel#477]
Not blocking for me (I just downgraded to the Premium plan), but the `pro` plan does not support custom domain aliasing (d'oh!). 

`Error! Custom domains are only enabled for premium accounts. Please upgrade by running 'now upgrade'.`

**Comment by jamo** [comment]
This should have been fixed yesterday, if it still keeps on happening please reopen the issue
