### ISSUE TITLE
[Feature Request] Deployment to a specific domain

### ISSUE THREAD

**Issue by quorth0n** [vercel/vercel#4774]
Inspired by #4622

This is absolutely necessary for preview deployments done through CI. For instance in my case I need to generate some files at build time by AWS Amplify and push them to Vercel as part of a GitHub action. I have no way to deploy to a specific domain through Vercel CLI as it currently stands.

**Comment by paulogdm** [comment]
Hello,

You can use [this article](https://vercel.com/knowledge/using-vercel-cli-for-custom-workflows) to deploy to multiple projects. Using `vercel --prod` to assign a deployment to a domain is the recommended approach.

Also, the command `vercel alias --help` can give you the functionality you are looking for.
