### ISSUE TITLE
Alias to custom domain fails when we can't get price for the domain

### ISSUE THREAD

**Issue by leo** [vercel/vercel#479]
Started getting an error today when attempting to alias custom domains: `⠋ Fetching domain info> Error! Unknown error: TypeError: Cannot read property 'price' of undefined`

And:

```
⠋ Fetching domain info> Error! Unknown error: TypeError: Cannot read property 'price' of undefined
TypeError: Cannot read property 'price' of undefined
    at Alias.maybeSetUpDomain (/thebox/home/travis/build/zeit/now-cli/lib/alias.js:543:35)
    at Alias.set (/thebox/home/travis/build/zeit/now-cli/lib/alias.js:326:24)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
Probably the same error, but reported by another user

**Comment by saimeunt** [comment]
Same here 🤔 (started breaking with now@5.1, everything was ok with now@5.0)

**Comment by revolunet** [comment]
same here on 5.0.0

**Comment by ajoslin** [comment]
Same here (5.1.0, fails on OSX and Linux).

**Comment by tylersnyder** [comment]
I was experiencing this issue as well. It appears to be fixed in 5.1.2. 👍

**Comment by leo** [comment]
@saimeunt @revolunet @ajoslin Can you confirm that it works for you now?

**Comment by revolunet** [comment]
i can confirm it now works properly. thanks, you're the best 👍

**Comment by saimeunt** [comment]
@leo worked like a charm after upgrading, thanks!

**Comment by leo** [comment]
Sweet!
