### ISSUE TITLE
Commands `teams ls` and `teams rm` not recognized

### ISSUE THREAD

**Issue by romuloalves** [vercel/vercel#483]
When trying to run `now teams ls` or `now teams rm`, the cli shows an error of not valid command:

```
▲ ~ now teams ls          
> Error! Please specify a valid subcommand: ls | add | rm | set-default

  𝚫 now teams <add | ls | rm | invite>

  Options:

...
```

```
▲ ~ now teams rm          
> Error! Please specify a valid subcommand: ls | add | rm | set-default

  𝚫 now teams <add | ls | rm | invite>

...
```

**Comment by micahbrich** [comment]
I'm seeing this too!

**Comment by renatorib** [comment]
Same problem with `now teams rm` here! I've created a fake team (for testing how it works) and now I can't delete it.

**Comment by hessnd** [comment]
I'm also having this issue

**Comment by leo** [comment]
Please run `now teams -h` in the latest Now CLI. We fixed this!
