### ISSUE TITLE
[cli] Supporting a js module as the --local-config( -A ) option to vercel cli

### ISSUE THREAD

**Issue by sentientnibble** [vercel/vercel#4844]
Hi there, not sure if this is already documented somewhere, I have been trying to search for this and seems like this isn't that much of a common use case. So here is my scenario, I am using Gitlab CI/CD pipelines and using the vercel cli to deploy my application. All my environment variables are stored in the Gitlab runner configuration as my use case was that I needed environment variables associated with a particular branch. So what I needed was that I needed to pass through my variables from Gitlab to vercel cli's  `--build-env`  option. 

I have figured out a workaround for that which looks something like this
`vercel --build-env REACT_APP_BASE_URL=$REACT_APP_BASE_URL`

This takes the variables from gitlab and passes it through to vercel cli. Now this works fairly well for 2-3 variables but gets pretty tedious as I have more than 10-15 variables that need to be injected and writing them inline like this wouldn't be maintainable.

Is there a way to access process.env variables in the vercel.json configuration file? If not, is there a use case where we could allow a js module file which would export an object to be passed to the cli instead of just a json file?

**Comment by trek** [comment]
Hi @sentientnibble,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
