### ISSUE TITLE
Feature Request:  Old Deployments Pruning

### ISSUE THREAD

**Issue by mojo5000** [vercel/vercel#490]
There is a lot of 'pruning' that one has to do for past deployments.  I'm not sure if its just because of being in testing mode, but there is a lot of deleting going on and I've deleted instances unintentionally.

I don't know what the answer is, but finding ways to manage this a better would be helpful, particularly for dev envs.

**Comment by redloro** [comment]
Agree... you could always script your own or use now-clean:
https://www.npmjs.com/package/now-clean

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), there's no reason to delete old deployments anymore. In turn, I'm closing this issue.
