### ISSUE TITLE
Feature Request: 'Lock' an Instance

### ISSUE THREAD

**Issue by mojo5000** [vercel/vercel#491]
Provide a way to 'lock' an instance from getting deleted or re-aliased by other folks on a team.

I assume this gets into team roles and permissions, not sure where this is on your roadmap.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
