### ISSUE TITLE
Feature Request:  Selectable UI Elements

### ISSUE THREAD

**Issue by mojo5000** [vercel/vercel#495]
I know this is a broad request.  Great if for some tasks we could start to see some built in ui selectors, i.e. lists or options via a lib like inquirer:

https://www.npmjs.com/package/inquirer

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
