### ISSUE TITLE
SSL certificate not detected by browsers

### ISSUE THREAD

**Issue by rake5h1** [vercel/vercel#4968]
My site c7ech.xyz built in Nextjs and deployed on vercel is facing issues with SSL certificates.Browsers dont seem to detect SSL.Even test on sslchecker shows no SSL present.

**Comment by markozxuu** [comment]
Hi @rake5h1  👋  I am checking your website and I am getting a **404 error**. It would be great if you could give me more information to help. If you could share the build of your application, it would be useful to see what is happening.
<img width="766" alt="Screen Shot 2020-08-03 at 22 17 43" src="https://user-images.githubusercontent.com/16585386/89249291-74a6e100-d5d7-11ea-8d85-57ce599e173d.png">

**Comment by rake5h1** [comment]
c7ech.xyz

Vercel support they told me to set A name to 76.76.21.21

check this https://www.whatsmydns.net/#A/c7ech.xyz

SSL generation is not finished even after hours

Registrar support told me to contact hosting service provider

**Comment by rake5h1** [comment]
Alternate domains are working fine.
check this  c7ech-next.vercel.app.
custom domain is not working

**Comment by styfle** [comment]
Hi @rake5h1 

It looks like the certificate was deleted.

@mglagola is investigating why that happened, but for now the certificate has been manually restored so you should be able to visit `https://c7ech.xyz` as expected.

**Comment by mglagola** [comment]
@rake5h1 We're seeing that your account removed and re-added the domain zone multiple times which removes and creates a new SSL certificate each time. 

We've restored the deleted certificate and https://c7ech.xyz is now working.

**Comment by rake5h1** [comment]
Thank You So Much .I have been trying to solve the problem for days.
It is working fine now.
