### ISSUE TITLE
Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by AndreyNikiforov** [vercel/vercel#499]
Build failed in circleci, but works locally.

> now deploy --npm --token="${NOW_TOKEN}"
> Error! Unknown error: TypeError: Cannot read property 'username' of undefined
TypeError: Cannot read property 'username' of undefined
    at /opt/circleci/nodejs/v6.10.2/lib/node_modules/now/build/bin/now-deploy.js:316:115
    at next (native)
    at c (/opt/circleci/nodejs/v6.10.2/lib/node_modules/now/build/bin/now-deploy.js:760:99)
> now deploy --npm --token="${NOW_TOKEN}" returned exit code 1
> Action failed: now deploy --npm --token="${NOW_TOKEN}"

`now` is installed during build as well:

> npm install -g now
> /opt/circleci/nodejs/v6.10.2/bin/now -> /opt/circleci/nodejs/v6.10.2/lib/node_modules/now/build/bin/now.js
/opt/circleci/nodejs/v6.10.2/lib
└─┬ now@5.1.2 

Last successful build has different `now`:
> npm install -g now
> /opt/circleci/nodejs/v6.10.2/bin/now -> /opt/circleci/nodejs/v6.10.2/lib/node_modules/now/build/bin/now.js
/opt/circleci/nodejs/v6.10.2/lib
└─┬ now@4.11.2 

Is it confirmed/known 5.1.2 version issue or I am hitting something else?

**Comment by adambrgmn** [comment]
I get exactly the same error trying to run the same command on Travis CI.

**Comment by redloro** [comment]
Same here... looks like it's related to #474 and #484. Looks like it's been fixed but we're waiting on a build?
