### ISSUE TITLE
Support Dockerfile.prod

### ISSUE THREAD

**Issue by royalicing** [vercel/vercel#507]
If I deploy with `now` or `now --docker`, and there is no `Dockerfile`, I should be to point it at the Dockerfiles that I do have, e.g. `Dockerfile.dev` or `Dockerfile.prod`.

Something like this:

```
now --docker=Dockerfile.prod
```

**Comment by royalicing** [comment]
Or alternatively:
```
now --docker --prod
```

```
NOW_ENV=production now --docker
```

**Comment by jamo** [comment]
Maybe we could make `--docker` flag to take an optional argument defining which file to consider to the Dockerfile

**Comment by moxie** [comment]
I like @jamo's approach. This would allow different Dockerfiles to run different commands against the same codebase. For example, I'm working with deploying a Rails app. The build/run works perfectly but there's no clear way (That I've found) to run one-off tasks (e.g. migrate the database, or some other arbitrary build task) against a deployment.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2

**Comment by royalicing** [comment]
Can you please just be specific and say Dockerfiles are no longer supported? I don’t know why being vague helps with communication.

**Comment by styfle** [comment]
Instead of linking to a blog post, a better way to close all these Docker issues is to specifically explain how Now v2 solves these problems.
