### ISSUE TITLE
You reached your 20 deployments limit in the OSS plan.

### ISSUE THREAD

**Issue by ManAnRuck** [vercel/vercel#510]
I get this warning on trying to deploy 

> You reached your 20 deployments limit in the OSS plan.

but the deployments are now unlimited. 

<img width="958" alt="bildschirmfoto 2017-05-05 um 19 01 02" src="https://cloud.githubusercontent.com/assets/2183135/25755983/593dc348-31c5-11e7-845f-3aa4a5d3602a.png">

**Comment by AkiraLaine** [comment]
Same issue here.

**Comment by ghost** [comment]
same.

went digging a little through the source. this might be related? kind of an idiot when it comes to javascript.

```Javascript
 if (res.status === 429) {
        let msg = `You reached your 20 deployments limit in the OSS plan.\n`
        msg += `${chalk.gray('>')} Please run ${chalk.gray('`')}${chalk.cyan('now upgrade')}${chalk.gray('`')} to proceed`
        const err = new Error(msg)
        err.status = res.status
        err.retryAfter = 'never'
        return bail(err)
      } else if (res.status >= 400 && res.status < 500) {
        const err = new Error(body.error.message)
        err.userError = true
        return bail(err)
      } else if (res.status !== 200) {
        throw new Error(body.error.message)
      }
```

in [index.js, starting line 192](https://github.com/zeit/now-cli/blob/68a3f51dff6dff62ca9ab5db7d530c4f854be808/lib/index.js#L192).

**Comment by Hannah-goodridge** [comment]
Same here.

**Comment by Glavin001** [comment]
I found a Tweet recommending we DM the team for fix manually: https://twitter.com/zeithq/status/861660356837429248

> For now the limit is still around as we're transitioning to the new plans 😔 Please DM us – we can work around it manually for now!

**Comment by matheuss** [comment]
We were transitioning to the new plans, so the old 20 deployments limit were still in place.
Now that the process is complete, the limit is gone! 🎉 

Thank you all for your patience 🙌

**Comment by enjine** [comment]
i've just recently signed up for zeit and installed now -- i'm getting the deployment limit error.
i've got no instances running, and the pricing model i see on the site is the same as the OP's one -- unlimited.

> Error! OSS deployment capacity has been reached. Please try again later.

is there a fix?

> $ now --version
> 8.3.10

**Comment by ghost** [comment]
Same issue here

**Comment by bouiboui** [comment]
Same issue as well, guess I picked the wrong day to try it.
Apparently [they got an outage yesterday as well](https://zeit-status.co/) so this may be round 2.

Edit: I should add that I'm using Windows 10, Git bash, and typing `now --docker`

**Comment by Qix-** [comment]
Hi - OSS functionality is restored. Sorry about that :)

**Comment by CrisTowi** [comment]
Sorry guys, it says that you already restore OSS functionality but I still having the "Error! OSS deployment capacity has been reached. Please try again later." error.

**Comment by Qix-** [comment]
@CrisTowi Back up now. Going to put a better error message there.

**Comment by sohlis** [comment]
`Error! OSS deployment capacity has been reached. Please try again later.`

FYI getting this message as well

**Comment by rauchg** [comment]
We've expanded capacity, so you shouldn't be having issues @sohlis. Check https://zeit-status.co for a report.

**Comment by Qix-** [comment]
> Error! OSS deployment capacity has been reached. Please try again later.

This error happens when we've reached capacity for our OSS tier. OSS deployments are not a guarantee and are allocated on a first-come-first-serve basis.

We generally see capacity hit at times of high load - we act immediately when we get these alerts internally and increase the capacity as needed. They generally only stick around for a little while.

Upgrading to a premium plan will make them go away entirely.

Going to lock this thread since there's nothing commenting on a Github issue can do to make that error go away 😉 

Feel free to come chat in https://zeit.co/chat if you see this error and have any questions! :)
