### ISSUE TITLE
Unexpected FROZEN state

### ISSUE THREAD

**Issue by StyxUA** [vercel/vercel#511]
```
$ now ls
> 1 deployment found under *** [923ms]

*** (1 of 1 total)
 url                                      inst #    state                 age
 *************************.now.sh              0    FROZEN                 2h
```

Deployment is only 2h old and already is in the `FROZEN` state? That doesn't make sense.

**Comment by tysonxor** [comment]
Same here, whats the deal? @leo

**Comment by tysonxor** [comment]
Additionally the documentation states that a deployment in frozen state will be restarted on demand, however my application would not load today when trying to show it to people. 

```A deployment in READY or FROZENstate is set to receive traffic from the internet, while a deployment inFROZEN state isn't actually running it will never lose new connections as it's restarted on-demand.```

**Comment by jamo** [comment]
The deployments are put FROZEN based on various metrics, so 2h with no traffic traffic is indeed possible.
Have you noticed that you may also disable sleep for e.g. low traffic production sites? Just scale it to one instance.

It should wake up, which error did you get @adamtysonsmith ?

**Comment by tysonxor** [comment]
Sorry but how is this issue resolved? I have a client site in production that cannot go down because of a frozen state.  How do you 'disable sleep'? @jamo

**Comment by tysonxor** [comment]
I dont see in the documentation how you can just scale to one instance

**Comment by tysonxor** [comment]
For anyone else with this problem:

– Create an deployment that is always active and never "sleeps"
`now scale my-deployment-ntahoeato.now.sh 1`

**Comment by sehmaschine** [comment]
Solution did not work for me. I deployed a simple app (learnnextjs.com) and after 2h without any traffic the state was frozen. I tried to call the URL but the state did not change. Then I used the scale command and I got this error:

```
> Deployment is currently in 0 replicas, preparing deployment for scaling...
> Error! Unknown error: Error: Unfreeze failed. Try again later.
Error: Unfreeze failed. Try again later.
```

**Comment by OlliV** [comment]
A deployment should always go from `FROZEN` -> `READY` when you fetch the URL.

**Comment by sehmaschine** [comment]
@OlliV Well, in that case there´s definitely something wrong.

**Comment by OlliV** [comment]
It's a bit hard to say without seeing the logs.

**Comment by irisSchaffer** [comment]
Also getting the same error... Generally, how is `now scale` set up to work? With certain deploys or with the alias as well?

In other words, when aliasing a deploy, should one really do

```
$ now alias [new-deploy] [domain]
$ now scale [new-deploy] 1
$ now scale [old-deploy] 0
```

or is it possible to

```
$ now scale [domain] 1
```

and then only alias for new deploys?

**Comment by TooTallNate** [comment]
Scale settings persist at the alias level, so if you alias a new deployment you do no need to run `now scale` again.

**Comment by irisSchaffer** [comment]
That's great to hear, unfortunately still getting the error:

```
> Deployment is currently in 0 replicas, preparing deployment for scaling...
> Error! Unknown error: Error: Unfreeze failed. Try again later.
Error: Unfreeze failed. Try again later.
    at module.exports.EventEmitter.unfreeze.depl.retry (/snapshot/now-cli/dist/now.js:1080:21)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Mind you, the deployment wasn't frozen before and the alias was (and still is) accessible... Now, when trying again, I'm getting this error:

```
> Error! Deployment may only be scaled when it's READY or FROZEN, it was: BUILD_ERROR.
```

**Comment by TooTallNate** [comment]
Let me try to reproduce the issue.

**Comment by TooTallNate** [comment]
@irisSchaffer Can you share with me the command you are trying to run?

Side note: Join our Slack channel at https://zeit.chat and we could communicate a bit quicker!

**Comment by irisSchaffer** [comment]
```
now scale irisschaffer.com 1
```

Side note: I tried, but haven't received an invite e-mail :'(

**Comment by TooTallNate** [comment]
Ok I am looking into it now. I can reproduce the issue on our end.

**Comment by Fransferdy** [comment]
Same is happening with me
```
> Deployment is currently in 0 replicas, preparing deployment for scaling...
> Error! Unknown error: Error: Unfreeze failed. Try again later.
Error: Unfreeze failed. Try again later.
    at module.exports.EventEmitter.unfreeze.depl.retry (C:\snapshot\now-cli\dist\now.js:1102:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by leo** [comment]
@Fransferdy We're experiencing some problems with unfreezing right now. Will be fixed very soon!

https://zeit-status.co
