### ISSUE TITLE
Deployment sometimes fails when using Yarn 2

### ISSUE THREAD

**Issue by kidonng** [vercel/vercel#5136]
I'm playing with Yarn 2 and Vercel ([my project](http://github.com/kidonng/swiss), which [doesn't use Plug'n'Play](https://github.com/kidonng/swiss/blob/aa67475ee9bbea49fb468c8bdad8003b6cf40bf5/.yarnrc.yml#L1)). It works fine when using the Vercel CLI, but sometimes fails when using GitHub integration.

**EDIT**: looks like it may also fail even if using the Vercel CLI, so I'm changing the title to make it clear.

- An example of failed deployment (https://vercel.com/kidonng/swiss/non9mdxh5)
  Actually, most of the deployments will fail

```
20:30:20.203 | Cloning github.com/kidonng/swiss (Branch: master, Commit: aa67475)
20:30:20.849 | Cloning completed in 646ms
20:30:20.850 | Analyzing source code...
(Omitted)
20:30:46.416 | ➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
20:30:46.416 | ➤ YN0013: │ yorkie@npm:2.0.0 can't be found in the cache and will be fetched from the remote registry
20:31:48.790 | ➤ YN0000: └ Completed in 1.37m
20:31:48.956 | ➤ YN0000: ┌ Link step
20:31:49.037 | ➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.1.3#builtin<compat/fsevents>::version=2.1.3&hash=87eb42 The platform linux is incompatible with this module, linking skipped.
20:31:49.382 | ➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=87eb42 The platform linux is incompatible with this module, linking skipped.
20:31:50.230 | ➤ YN0001: │ Error: While loading /vercel/6b66e1f4/node_modules/cet-score: Manifest not found
20:31:50.230 | at Function.find (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:272112)
20:31:50.230 | at async j.cachedManifestLoad (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:154591)
20:31:50.230 | at async r.loadManifest (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:150434)
20:31:50.230 | at async baseFs (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:150323)
20:31:50.230 | at async j.finalizeInstallWithPnp (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:146882)
20:31:50.230 | at async j.finalizeInstall (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:223849)
20:31:50.230 | at async ie.linkEverything (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:321535)
20:31:50.230 | at async /vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:328208
20:31:50.230 | at async C.startTimerPromise (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:337598)
20:31:50.230 | at async ie.install (/vercel/6b66e1f4/.yarn/releases/yarn-berry.cjs:2:327992)
20:31:50.230 | ➤ YN0000: └ Completed in 1.27s
20:31:50.230 | ➤ YN0000: Failed with errors in 1.4m
20:31:50.302 | Error: Command "yarn install" exited with 1
```

- An example of success deployment (https://vercel.com/kidonng/swiss/pqwx93xs0)
  This is the same commit as the above one, I just clicked "Redeploy"

```
20:38:45.993 | Cloning github.com/kidonng/swiss (Branch: master, Commit: aa67475)
20:38:46.609 | Cloning completed in 616ms
20:38:46.611 | Analyzing source code...
(Omitted)
20:39:08.451 | ➤ YN0013: │ yn@npm:3.1.1 can't be found in the cache and will be fetched from the remote registry
20:39:08.451 | ➤ YN0013: │ yorkie@npm:2.0.0 can't be found in the cache and will be fetched from the remote registry
20:40:09.438 | ➤ YN0000: └ Completed in 1.32m
20:40:09.601 | ➤ YN0000: ┌ Link step
20:40:09.678 | ➤ YN0062: │ fsevents@patch:fsevents@npm%3A2.1.3#builtin<compat/fsevents>::version=2.1.3&hash=87eb42 The platform linux is incompatible with this module, linking skipped.
20:40:10.024 | ➤ YN0062: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=87eb42 The platform linux is incompatible with this module, linking skipped.
20:40:15.608 | ➤ YN0007: │ protobufjs@npm:6.10.1 must be built because it never did before or the last one failed
20:40:15.608 | ➤ YN0007: │ yorkie@npm:2.0.0 must be built because it never did before or the last one failed
20:40:15.608 | ➤ YN0007: │ ejs@npm:2.7.4 must be built because it never did before or the last one failed
20:40:15.851 | ➤ YN0000: └ Completed in 6.25s
20:40:15.851 | ➤ YN0000: Done with warnings in 1.44m
20:40:16.123 | Using TypeScript 3.9.7 (local user-provided)
```

---

A few other things I'd like to mention about Yarn 2:

- Yarn 2 outputs a massive amount of log in the Vercel dashboard 😅 unfortunately I didn't find an argument to silence the message. I wish the log to be hidden in the dashboard.

  **EDIT**: Vercel just rolled out a sane log limit:

  ![image](https://user-images.githubusercontent.com/44045911/94879030-a9c59780-0491-11eb-81f0-71e26b6acc09.png)

  So this issue is mostly resolved.

- Is PnP support on your roadmap? Currently the Serverless Function build will fail if using PnP I know it could be hard but I can wait 😊

**Comment by Mvaxtuan16V** [comment]
Gracias

**Comment by merceyz** [comment]
> unfortunately I didn't find an argument to silence the message. I wish the log to be hidden in the dashboard.

They are disabled when we detect that we're running under a CI, a env variable such as `CI=true` would be enough

**Comment by TooTallNate** [comment]
Hello friends. I wanted to notify you that we have added support for Yarn v2 in our official Runtimes (`@vercel/next`, `@vercel/node` and `@vercel/static-build`, specifically, see https://github.com/vercel/vercel/pull/5552). Currently the update is available on the "canary" release channel.

If you would like to try out the Yarn v2 support before it hits the stable release channel, you can run the following command if you are using the CLI:

```
$ vc -b FORCE_BUILDER_TAG=canary
```

If you are using the Git integration to trigger your deployments, then you can define the `FORCE_BUILDER_TAG` environment variable in your Project's environment variables setting on the Vercel dashboard.

Please let me know if it works for you or if you bump into any issues!

**Comment by kidonng** [comment]
@TooTallNate Hi, I just tested with my project mentioned in this issue, and it works well! Thanks for your work!
