### ISSUE TITLE
Secrets not applied from now.json

### ISSUE THREAD

**Issue by littleStudent** [vercel/vercel#516]
Looks like after https://github.com/zeit/now-cli/pull/508 the secrets are not applied. Previous version seems to work fine.
I did not test if the same applies when the config is not in `now.json` but in `package.json`.

**Comment by gabek** [comment]
I can verify downgrading to 5.2.0 resolves the problem after seeing deployments fail on 5.2.1.

**Comment by mojo5000** [comment]
Secrets also not found when on 'command line' now -e MY_SECRET=@my_secret

**Comment by littleStudent** [comment]
hmm @mojo5000 
I can not confirm this. Using `-e` works for me with the latest version

**Comment by mojo5000** [comment]
@littleStudent sry is a slightly different issue - are you using teams?  it was not seeing the secret created within my team.

**Comment by littleStudent** [comment]
no, I dont use teams. So these are different issues i think.

**Comment by littleStudent** [comment]
not sure why (server side change?). But it is working again for me with cli `5.2.1`. If it is not for you @gabek drop me a line and I will reopen the issue
