### ISSUE TITLE
Feature request: `/**` pathnames in rules.json should catch `/`

### ISSUE THREAD

**Issue by tuckerconnelly** [vercel/vercel#517]
If you have a rules.json like:

```
{
  "rules": [
    {"pathname": "/svc/users/**", "dest": "svc-users.asdf.co" },
    {"pathname": "/**", "dest": "ui.asdf.co"}
  ]
}
```

And then go to `/svc/users`, you'll get a 404. Can get around it by doing:

```
{
  "rules": [
    {"pathname": "/svc/users", "dest": "svc-users.asdf.co" },
    {"pathname": "/svc/users/**", "dest": "svc-users.asdf.co" },
    {"pathname": "/**", "dest": "ui.asdf.co"}
  ]
}
```

But would be nice to not have to add that additional rule.

**Comment by olivierlesnicki** [comment]
+1

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
