### ISSUE TITLE
Secrets missing after application sleep?

### ISSUE THREAD

**Issue by MarcL** [vercel/vercel#518]
Hello.

I've just started using `now` and it's fantastic but I have  question about secrets.
I've registered 3 secrets for a test Facebook Messenger bot and I deploy it using an `npm` script:

```json
  "scripts": {
  	"build": "babel src/ -d dist/",
  	"deploy": "now -e MESSENGER_APP_SECRET=@messenger_app_secret -e MESSENGER_PAGE_ACCESS_TOKEN=@messenger_page_access_token -e MESSENGER_VALIDATION_TOKEN=@messenger_validation_token -e SERVER_URL=https://fb-messenger-bot.now.sh/",
  	"start": "node dist/app.js",
  	"lint": "jshint --exclude node_modules .",
  	"test": "mocha"
  },
```

It works for the first deploy, after aliasing the new deployment to the expected domain (as in the command above). However, once the app sleeps and is restarted by a Facebook POST message to one of the endpoints, it appears to fail due to re-running `npm start` which subsequently gives the error message that a config value isn't set and this is due to it attempting to read from the config as the environment variable isn't set.

I'd assumed that the environment variables set with the secrets were valid for the duration of the deployment but this appears to not be the case when it restarts after sleeping. What's the expected usage for the secrets? Should I be passing them to `node` in the `start` script instead? I couldn't find anything in the documentation to show best practice here.

Thanks,
Marc

**Comment by Leopoldthecoder** [comment]
Same issue here. According to my log, this problem begins 7 hours ago.

**Comment by MarcL** [comment]
@Leopoldthecoder - Ok thanks. I thought it might have been just me misunderstanding how secrets were used.

**Comment by Leopoldthecoder** [comment]
@MarcL My app worked fine till this morning, and I didn't deploy today.

**Comment by OlliV** [comment]
I think we fixed this issues a while back.
