### ISSUE TITLE
TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by styfle** [vercel/vercel#521]
### Steps to reproduce:

1. Install `now` using `npm install -g now`.
2. Execute `now ls`
3. Enter email address
4. Click link in email
5. See console error `Cannot read property 'username' of undefined`.

```
styfle@machine MINGW64 ~
$ now ls
> Enter your email: me@example.com
> Please follow the link sent to me@example.com to log in.
> Verify that the provided security code in the email matches Lively Collared Peccary.

✔ Confirmed email address!

> Error! Unknown error: TypeError: Cannot read property 'username' of undefined
TypeError: Cannot read property 'username' of undefined
    at C:\Users\styfle\AppData\Roaming\npm\node_modules\now\build\bin\now-list.js:147:155
    at Generator.next (<anonymous>)
    at c (C:\Users\styfle\AppData\Roaming\npm\node_modules\now\build\bin\now-list.js:219:99)

styfle@machine MINGW64 ~
$ now --version
5.2.3
```

I'm using now v5.2.3 on Windows 10 with Git Bash and Hyper terminal.

**Comment by styfle** [comment]
I tried again today and it suddenly started working. I still have the same setup with same version installed, so maybe something on the server changed?

**Comment by leo** [comment]
@styfle The latest version version is [6.2.2](https://github.com/zeit/now-cli/releases/tag/6.2.2). We only provide support for the latest version. Please update! 😊

**Comment by styfle** [comment]
@leo So you don't believe its a server-side issue?

**Comment by leo** [comment]
@styfle No - it works with the latest version.

**Comment by sylvainlap** [comment]
I still got this error with now v6.3.1 :/

**Comment by igorklopov** [comment]
@leo it is same as https://github.com/zeit/now-cli/issues/633 more simple repro there

**Comment by leo** [comment]
^ Duplicate
