### ISSUE TITLE
Docker `--dotenv` loading environment inconsistently

### ISSUE THREAD

**Issue by mwildehahn** [vercel/vercel#522]
It seems like this is happening somewhere further down.

Running `now deploy --docker --dotenv .env.dev` creates a container, but none of the env variables are available.

I added logging within `now-deploy.js` right before calling `now.create`, to log the `env`, everything looks correct:
- it is parsed correctly
- any secrets that were referenced show up with values as `{ uid: 'sec_234l2k3jsdflkja' }`

Some builds have the variables, others don't

**Comment by mwildehahn** [comment]
This is also a team deployment, maybe related to: https://github.com/zeit/now-cli/issues/523?

**Comment by develomark** [comment]
I have the same issue. I cannot work out why sometimes they appear, but mostly do not.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
