### ISSUE TITLE
Secrets - Not Found from Team Deployment

### ISSUE THREAD

**Issue by mojo5000** [vercel/vercel#523]
1.  On an account vs. team , each will only list the secrets it thinks it has per account.  

2.  BUT - when doing a deploy from the team account, it only has access to those secrets it finds as part of the personal account.

3.  When trying to add a secret under account, it says is already taken by team.

So is there some pollution between account and team secrets?  Is this intended functionality or broken?

If you find otherwise, let me know.  Else this is a blocker to using team secrets.  Thanks!

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
