### ISSUE TITLE
env var cli limit

### ISSUE THREAD

**Issue by saiichihashimoto** [vercel/vercel#5248]
https://github.com/vercel/vercel/blob/378d62083c050c7a453f5cd68211f5a63783f7e1/packages/now-cli/src/util/env/get-env-records.ts#L49

It was unclear to me that `vercel env ls` has a limit of 20. Instead of having to pass in `--next` to see them all, I'd love an `--all` option or even a `--limit 30`

**Comment by styfle** [comment]
This was removed in #5345 and is available on the canary channel `npm i -g vercel@canary`, thanks!
