### ISSUE TITLE
What are those things I keep hearing about FROZEN states?

### ISSUE THREAD

**Issue by vladejs** [vercel/vercel#525]
What's the default policy to FREEZE a deployment? It doesn't make any sense to me to be paying for a service that shutdown my apps randomly, especially in my case, because I use `Meteor`, which apps  are known to take some time to boot up.

I linked a `ping` service to my `now` apps and I'm constantly receiving emails about my apps going down and up.

How I'm suppose to be taken seriously by my users if my apps are almost always failing?

Do `now` service isn't suitable for Meteor apps? I have the understanding that a Meteor app is just a NodeJS app, so what's the matter with this?

The only reason I see this service useful is for apps like Facebook, which are constantly been visited.
In my case, I have apps which are used 3 times per week, Monday, Thursday and Saturday, for example.

am I wrong?

**Comment by jamo** [comment]
The apps shouldn't be put to sleep randomly, rather, after a certain period of inactivity:
- https://zeit.co/docs/deployment-types/docker#builds
- https://zeit.co/docs/deployment-types/node#deployment-inactivity

You may also control it with `now scale`; scaling an deployment to 1 instance will disable the sleep. Keep in mind, however, that there is a limit of how many instances can be running simultaneously.

**Comment by jamo** [comment]
Also, as long as the deployment works with the convention of supporting `npm install` `npm run build` and `npm run start` it works as an npm deployment. 
See https://zeit.co/now#how-do-i-run-my-build-process and https://zeit.co/docs/deployment-types/node

**Comment by vladejs** [comment]
Thanks for the heads up @jamo . One question arises though.

Which Plans are allowed to use `now scale` command? 

Currently I am using Premium plan.

Another question. Is now service suitable for production Meteor apps? Is it better than Galaxy?

**Comment by jamo** [comment]
`now scale` to a constant number is allowed for all users, regardless of the plan. While remaining within the instance limits.

Also `now scale <url> 0 1` is also allowed for users regardless of the plan as that's the default setting and isn't really "auto scaling" as intended in the new pricing.

I don't have experience with Meteor, so I cannot really say.
However, I can tell that we have lots of meteor apps deployed with Dockerfiles with both  https://github.com/jkrup/meteor-now and with custom dockerfiles.
Due to its diversion from the 'normal npm workflow" it's not currently natively supported as our NPM deployments.

**Comment by vladejs** [comment]
So it's guaranteed that, if I scale my deployment to, let's say, 4 containers (Premium plan says I am allowed to use 10), my app won't go to sleep?

Any plans to natively support Meteor apps?

**Comment by AHurnell** [comment]
It was useful to read this discussion.

Is there any way to deliberately freeze or end all deployments of an app?

Thanks

**Comment by sergiodxa** [comment]
@VolitionComponents you could freeze a deployment with `now scale [url] 0`, but you need to do it manually for each deployment. You could also remove a deployment with `now rm [url]` and you could remove all the deployment if a same app with `now rm [app] --safe` that will remove any non aliased deployment of `[app]`.

> e.g. if your deployments are `my-app-[hash].now.sh` you could use `now rm my-app --safe` to remove any non aliased deployment of `my-app`.

**Comment by AHurnell** [comment]
Thanks @sergiodxa that is very helpful to me! I had looked on google to find this information and couldn't, so I hope your comment will help others as well.
