### ISSUE TITLE
What Means that my App is Scaled to 3 deployments

### ISSUE THREAD

**Issue by vladejs** [vercel/vercel#527]
I issued following command: `now scale myapp-123456.now.sh 3` with the following output:
```
> Scaled to 3 instances: [12s]
 - myapp-ziwounrkqh-570a6670c4bec30e82c5fbb6.now.sh
 - myapp-ziwounrkqh-4477e20b9377d2adc23514e9.now.sh
 - myapp-ziwounrkqh-08dd73d1f858d6d87ac3d7f9.now.sh
```

I have the app aliased to myapp.now.sh.

That means that now I need to create an alias for every instance? Or users are automatically redirected to any of them by visiting the current alias: `myapp.now.sh`

**Comment by timneutkens** [comment]
> Or users are automatically redirected to any of them by visiting the current alias: myapp.now.sh

This 😄 The urls are basically so you can check any particular instance of your app 👍

**Comment by vladejs** [comment]
So I don't need to set particular alias for the new instances?

**Comment by timneutkens** [comment]
Indeed 👌

**Comment by vladejs** [comment]
Do any of those instances are put to sleep?

**Comment by timneutkens** [comment]
No they are permanently scaled till you change it :)

**Comment by vladejs** [comment]
Let's pray for it :)

Thanx @timneutkens

**Comment by jamo** [comment]
Scaling to 3 means that we keep always 3 instances (copies) of that app running. And in the event of one your apps would crash/restart we would start up a new one to replace the existing one. 

Also, the instance urls will change in case an instance restarts...

**Comment by vladejs** [comment]
Do this scaling includes load balancing?

2017-05-09 13:59 GMT-04:00 Jarmo Isotalo <notifications@github.com>:

**Comment by jamo** [comment]
It does.

**Comment by vladejs** [comment]
thank you. I'm not a devops specialist. In your experience, a 3 instances
scaling, how many users it can hold?

2017-05-10 2:02 GMT-04:00 Jarmo Isotalo <notifications@github.com>:

**Comment by jamo** [comment]
It varies a lot on how well the app performs. 
For example, I've seen a single `micro` api endpoint work just fine with over 100 qps traffic. Which, for many, is way more traffic than what the app ever receives.

Most of the time 1 instance is enough, however, in case the app e.g crashes it will be unavailable for a short period of time until the app has been restarted and is again accepting traffic.
So having 2 instances of a deployment will make it less likely for both of the instances to crash at the same time...

**Comment by coreh** [comment]
Are the instances created by `now scale` placed on different fault domains in the cloud infrastructure? (Like Azure's Availability Sets or Amazon's Availability Zones)

**Comment by leo** [comment]
You can find more details [here](https://zeit.co/blog/scale).
