### ISSUE TITLE
Make DNS propagation delay more apparent when verifying a domain

### ISSUE THREAD

**Issue by Dids** [vercel/vercel#530]
I've noticed an increase in users asking why their newly added domains are showing an error when aliasing, due to DNS not propagating yet.

Since now can't verify that the alias works, there should probably be a more descriptive/apparent message given to the user. They really need to know that they need to sit tight and wait, from anywhere from a few minutes to 24 hours.

Right now  the domain verification error/message might need some love too.

**Comment by timneutkens** [comment]
Duplicate of #366

**Comment by Dids** [comment]
@timneutkens Awesome, thanks. :)
