### ISSUE TITLE
Windows - EPERM: operation not permitted (.now.json)

### ISSUE THREAD

**Issue by coreh** [vercel/vercel#531]
I'm using `now` version 5.2.3, on Windows 10.

Every so often, whenever I try to run the `now` command, I'll get the following error message:

```
(node:3636) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EPERM: operation not permitted, open 'C:\Users\coreh\.now.json'
(node:3636) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Both times I've had it happen I checked file permissions and they seemed to be normal:

<img src="https://cloud.githubusercontent.com/assets/418473/25928455/bb6cad3e-35d2-11e7-8675-8ef0bc9b9e7f.png">

I ended up using the **Home > Properties > Remove Properties** option of Explorer on `.now.json`: (Since that has fixed some permissions issues with files on Windows in the past for me)

<img src="https://cloud.githubusercontent.com/assets/418473/25928368/3d6e8ef2-35d2-11e7-9388-ec12724924a4.png" width="151" height="134">

That _seemed_ to fix the issue both times, (i.e. error is gone, `now` works normally) but I'm not entirely sure if it could be just a coincidence. (Perhaps `now-desktop` is holding the file open exclusively, and just happened to release it at the right time?)

If it happens again I'll try waiting instead and not using Remove Properties, just to be sure.

**Comment by TooTallNate** [comment]
Interesting @coreh. Your theory about `now-desktop` having the file open sounds very plausible /cc @leo.

Easiest thing to do is probably just retry reading the file a few times.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
