### ISSUE TITLE
Idea! 🤔 Include rules.json in a deployment instead of having to explicitly upload

### ISSUE THREAD

**Issue by micahbrich** [vercel/vercel#532]
After chatting with @timneutkens today, I found I had misunderstood how `rules.json` worked — I thought I could deploy just the `rules.json` to a domain or subdomain, and use that to assemble all the services. 

Based on this from [the docs](https://zeit.co/docs/features/path-aliases#alias-rules), `now alias company.com -r rules.json`, I thought I could just do that on an empty domain I'd just bought; I didn't realize that you have to have a **root deployment** _plus_ rules. Rules are like _extra_ routes.

So that's one thing, but then once I understood that you needed a root deployment, I thought a nice feature might be just including the `rules.json` in it, rather than having to explicitly called `-r rules.json` each time you want to update it.

It would be less work to update, and also could keep the rules in version control with the root deployment you have to have anyway!

**Comment by jamo** [comment]
We thought about this extensively while implementing the feature. Because it's intended to tie in multiple microservices we ruled in favour of making it a separate file that may be easily version controlled independently.

**Comment by micahbrich** [comment]
Oh @jamo, just to clarify, I just meant to suggest that maybe if that file exists in a deployment, it's recognized and used. 

I like that it's a separate file, it seemed extraneous to create a root deployment, then attach the `rules.json` file with a separate command — I'm suggesting that if that `rules.json` was already included in a deployment, it'd be used automatically.

**Comment by timneutkens** [comment]
Should be a `now.json` option don't you think @jamo

**Comment by jamo** [comment]
Maybe we could default to use`./rules.json` if present with the `-r` flag, and to make the filename optional.
