### ISSUE TITLE
`now` eagerly deploys on first run

### ISSUE THREAD

**Issue by zeke** [vercel/vercel#533]
## Problem

I just installed `now` and ran it, expecting to see some usage info. Instead, the CLI starting deploying my current working directory. This scared me a little, especially when nothing happened when I repeatedly hit `ˆC`. Seems kinda like a security risk. 😓 

<img width="632" alt="screen shot 2017-05-11 at 5 30 44 pm" src="https://cloud.githubusercontent.com/assets/2289/25977379/1e5a0e08-3670-11e7-9969-3ffdbcff39a8.png">

## A Proposed Solution

The first time I run `now` and authenticate my email, I think the CLI should say something like:

```
❯ now
> Enter your email: zeke@sikelianos.com
> Please follow the link sent to zeke@sikelianos.com to log in.
> Verify that the provided security code in the email matches Lively Squid.

✔ Confirmed email address!

Run `now` to deploy the current directory, or `now --help` for usage info.
```

**Comment by rauchg** [comment]
Totally. Thanks for the advice.

**Comment by zeke** [comment]
🙏
