### ISSUE TITLE
rules.json requires destination URL different from your deploy URL?

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#534]
Hey all, I'm having trouble understanding the behavior of rules.json. If I'm deploying to example.com, my rules.json would require this:
```
  "rules": [
    { "dest": "www.example.com" }
  ]
```
The behavior here would mean I need to deploy my project, but then also set an alias for www.example.com, right? Otherwise, the site returns a error.

Here's a few scenarios when trying to deploy to example.com:

1. `"dest": "example.com". — When using `now alias example.com -r rules.json` the CLI will return an error that your rules.json dest cannot be the same.
2. `"dest": "www.example.com". — When using `now alias example.com -r rules.json`, everything will work, but when visiting www.example.com in the browser, you'll get a deploy error because you haven't create a www alias yet.

Ultimately, I'm looking to create a 301 webforward for various aliases to land on example.com. www.example.com should 301 redirect to example.com, and I should only need to set one alias.

**Comment by hosmelq** [comment]
I have the same problem here.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
