### ISSUE TITLE
Postgres on RDS, SSL

### ISSUE THREAD

**Issue by babakness** [vercel/vercel#536]
I couldn't find this documented, how does one connect an app to Postgres over a secure connection given the need for the certificate to be on the server

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL

Step 1: "Download the public key stored at https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem."

**Comment by matheuss** [comment]
@babakness you can create a script that runs in your `build` step and downloads the public key 😄 That would be enough 👍 

You can have a `.sh` with this, for example:
`curl https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem -o aws-ca.pem`
