### ISSUE TITLE
`now pathname` overrides package.json `name` field with `pathname`

### ISSUE THREAD

**Issue by cdock1029** [vercel/vercel#549]
when I run `now deploy out` with a `package.json` that looks like:

```
"now": {
  "name": "my-prefix-name",
  "type": "static"
}
```

 the name is not being used, and my deployment is prefixed `out-xxxxx`

Is this a bug?

**Comment by TooTallNate** [comment]
Yes this is a bug.

**Comment by TooTallNate** [comment]
I can't seem to reproduce this actually. Are you sure that you're using the most up-to-date version of the Now CLI? Can you give me a zip file or repo that demonstrates the problem?

**Comment by leo** [comment]
The `package.json` file is probably on the wrong level.

**Comment by cdock1029** [comment]
```
├── README.md
├── //...
├── next.config.js
├── out
└── package.json
```
----------
`package.json`:
```
"scripts": {
    "dev": "next",
    "build": "NODE_ENV=production next build && next export",
    "deploy": "NODE_ENV=production now deploy out"
  }
```

So this doesn't work, as it's not reading the `package.json` config? If so, my bad... I'll close.

I could just do:
`"deploy": "NODE_ENV=production now deploy out --name my-prefix"`

**Comment by leo** [comment]
It will read the name from the directory that you're trying to deploy (the `package.json` within it). That's the reason why it doesn't work for you... 😊

**Comment by TooTallNate** [comment]
Correct, the `package.json` file would need to be inside the `out` dir.
