### ISSUE TITLE
CRA treating warnings as errors because process.env.CI = true

### ISSUE THREAD

**Issue by rhmndhika** [vercel/vercel#5510]
Hi, i'm new to github and tried to build my website with vercel. i had a problem with deployment in vercel.

this is my github https://github.com/rhmndhika/Personal-Web.
And this is the log from deployment with vercel : 

18:21:26 | Cloning github.com/rhmndhika/Personal-Web (Branch: main, Commit: d0a5d14)
-- | --
18:21:27 | Cloning completed in 1132ms
18:21:27 | Analyzing source code...
18:21:27 | Installing build runtime...
18:21:28 | Build runtime installed: 404.257ms
18:21:28 | Looking up build cache...
18:21:28 | Build cache not found
18:21:29 | Installing dependencies...
18:21:51 | > @fortawesome/fontawesome-common-types@0.2.32 postinstall /vercel/workpath0/node_modules/@fortawesome/fontawesome-common-types
18:21:51 | > node attribution.js
18:21:51 | Font Awesome Free 0.2.32 by @fontawesome - https://fontawesome.com
18:21:51 | License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
18:21:51 | > core-js@2.6.12 postinstall /vercel/workpath0/node_modules/babel-runtime/node_modules/core-js
18:21:51 | > node -e "try{require('./postinstall')}catch(e){}"
18:21:51 | > core-js@3.8.0 postinstall /vercel/workpath0/node_modules/core-js
18:21:51 | > node -e "try{require('./postinstall')}catch(e){}"
18:21:51 | > core-js-pure@3.8.0 postinstall /vercel/workpath0/node_modules/core-js-pure
18:21:51 | > node -e "try{require('./postinstall')}catch(e){}"
18:21:51 | > ejs@2.7.4 postinstall /vercel/workpath0/node_modules/ejs
18:21:51 | > node ./postinstall.js
18:21:52 | > @fortawesome/fontawesome-svg-core@1.2.32 postinstall /vercel/workpath0/node_modules/@fortawesome/fontawesome-svg-core
18:21:52 | > node attribution.js
18:21:52 | Font Awesome Free 1.2.32 by @fontawesome - https://fontawesome.com
18:21:52 | License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
18:21:52 | > @fortawesome/free-brands-svg-icons@5.15.1 postinstall /vercel/workpath0/node_modules/@fortawesome/free-brands-svg-icons
18:21:52 | > node attribution.js
18:21:52 | Font Awesome Free 5.15.1 by @fontawesome - https://fontawesome.com
18:21:52 | License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
18:21:53 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
18:21:53 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
18:21:53 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
18:21:53 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
18:21:53 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.2.1 (node_modules/fsevents):
18:21:53 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.2.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
18:21:53 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/chokidar/node_modules/fsevents):
18:21:53 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
18:21:53 | added 1980 packages from 819 contributors in 24.17s
18:21:54 | 124 packages are looking for funding
18:21:54 | run `npm fund` for details
18:21:55 | Running "npm run build"
18:21:55 | > aries-web@0.1.0 build /vercel/workpath0
18:21:55 | > react-scripts build
18:21:56 | Creating an optimized production build...
18:22:07 | Treating warnings as errors because process.env.CI = true.
18:22:07 | Most CI servers set it automatically.
18:22:07 | Failed to compile.
18:22:07 | src/Components/about.js
18:22:07 | Line 11:7:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text
18:22:07 | src/Components/button.js
18:22:07 | Line 2:8:  'ReactDOM' is defined but never used  no-unused-vars
18:22:07 | src/Components/home.js
18:22:07 | Line 11:8:  'Buttons' is defined but never used  no-unused-vars
18:22:07 | npm ERR! code ELIFECYCLE
18:22:07 | npm ERR! errno 1
18:22:07 | npm ERR! aries-web@0.1.0 build: `react-scripts build`
18:22:07 | npm ERR! Exit status 1
18:22:07 | npm ERR!
18:22:07 | npm ERR! Failed at the aries-web@0.1.0 build script.
18:22:07 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
18:22:07 | npm ERR! A complete log of this run can be found in:
18:22:07 | npm ERR!     /vercel/.npm/_logs/2020-12-03T11_22_07_640Z-debug.log
18:22:07 | Error: Command "npm run build" exited with 1
18:22:09 | Done with "package.json"

i dont know what to do can someone help me.

_Originally posted by @rhmndhika in https://github.com/vercel/next.js/discussions/19783_

**Comment by styfle** [comment]
Hi @rhmndhika 

Take a look at this article: https://vercel.com/knowledge/how-do-i-resolve-a-process-env-ci-true-error
