### ISSUE TITLE
`now domain buy` doesn't handle pre-orders

### ISSUE THREAD

**Issue by rpunkfu** [vercel/vercel#552]
Hi! :)

I wanted to buy a ".now" domain, currently it's pre-order only and `now` doesn't seem to handle this. Instead it shows: `Buy now for $undefined (<my_email>)?`

**Comment by TooTallNate** [comment]
This has been fixed (I believe on the server-side):

```
$ now domains buy testing.now
> Error! Unsupported TLD
```
