### ISSUE TITLE
allow deploying a different path in package.json

### ISSUE THREAD

**Issue by nlf** [vercel/vercel#555]
A pretty common pattern (at least from my perspective) seems to be using node, with a package.json, as a build system for a static site. When doing so it would be _awesome_ if we could specify a `path` property in the `package.json` for now to deploy the static site.

Imagine something like this:

package.json
```
{
  "name": "my-site",
  "now": {
    "name": "my-site"
    "type": "static",
    "path": "public"
  }
}
```

directory layout
```
package.json
views/index.pug
js/main.js
style/main.styl
Gruntfile.js
public/index.html   # .gitignored
public/js/main.js   # .gitignored
public/css/main.css # .gitignored
```

This would allow you to `npm install && grunt && now` and have your static site up and running without having to remember (or document the need) to run `now -n my-site public`.

Bonus suggestion: when using `package.json` for configuration maybe consider copying the top level `name` property to the `now` configuration if one isn't already set. It would certainly be convenient for situations like this.

**Comment by jamo** [comment]
Using the `now: {files: []}` and giving the path as an argument to now, like: `now public` might just work.

**Comment by nlf** [comment]
It might, but the advantage of the above changes would be that no arguments would be required for `now` at all, configuration would be entirely located in the `package.json`

**Comment by leo** [comment]
Thanks for the effort you've put into this, but we're not planning to support it! If you're interested in seeing this work like this, I recommend writing a package. But the already existing way of passing a path to the CLI will stay the only way to do it natively! 😊
