### ISSUE TITLE
Python ASGI bug: percentage encoded "+" symbol in querystring gets lost

### ISSUE THREAD

**Issue by simonw** [vercel/vercel#5575]
Compare this example (on Cloud Run): https://latest.datasette.io/fixtures?sql=select+date%28%27now%27%2C+%22%2B30+days%22%29

<img width="482" alt="fixtures__select_date__now_____30_days__" src="https://user-images.githubusercontent.com/9599/90698913-ce91e280-e236-11ea-8d63-6b2d5d5a88f6.png">

To this example (on Vercel): https://til.simonwillison.net/til?sql=select+date%28%27now%27%2C+%22%2B30+days%22%29&p0=2020-04-23

<img width="472" alt="til__select_date__now_____30_days__" src="https://user-images.githubusercontent.com/9599/90698935-d9e50e00-e236-11ea-9b3c-67326cbb0aeb.png">

In both cases the `+` from the form was encoded as `%2B` in the URL.

More details here: https://github.com/simonw/datasette-publish-vercel/issues/28

Another demo:

https://til.simonwillison.net/-/asgi-scope?sql=a%2Bb returns `'query_string': b'sql=a+b'`
https://til.simonwillison.net/-/asgi-scope?sql=a+b returns `'query_string': b'sql=a b'`

**Comment by simonw** [comment]
The bug is in this code: https://github.com/vercel/vercel/blob/f926d5516cba51a511fbe0bf1e1443686168c957/packages/now-python/now_init.py#L261-L280

**Comment by TooTallNate** [comment]
Hi @simonw. Can you please try out [this canary release](https://github.com/vercel/vercel/releases/tag/%40vercel%2Fpython%401.2.5-canary.0) (instructions at the bottom of the page) and let me know if that fixes your issue?

**Comment by simonw** [comment]
Thanks @TooTallNate! I just tried that out but it didn't seem to work - I added the `FORCE_BUILDER_TAG` environment variable of `canary` to my https://vercel.com/simonw/simon-til project and then deployed a new release, but I'm still seeing odd escaping behaviour.

Compare these two:

- https://til.simonwillison.net/-/asgi-scope?sql=select%201%20+%201 - running on Vercel with (I hope) the latest canary release - `'query_string': b'sql=select 1   1',`
- https://www.niche-museums.com/-/asgi-scope?sql=select%201%20+%201 - running on Google Cloud Run - `'query_string': b'sql=select%201%20+%201',` - this is correct behaviour

Both of these are running this plugin: https://github.com/simonw/datasette-debug-asgi

My concern is that I didn't deploy the canary release correctly - is there a way to tell which builder was used for a Vercel deployment? I'm happy to write some extra code to expose an additional variable or similar.

**Comment by simonw** [comment]
Here's what my environment variables look like. Did I set this up correctly?

<img width="1154" alt="Environment_Variables_-_simon-til_–_Vercel" src="https://user-images.githubusercontent.com/9599/106335051-d1aae900-6240-11eb-9287-1b033aab0bc0.png">

**Comment by simonw** [comment]
Here's what my environment variables look like. Did I set this up correctly?

<img width="1154" alt="Environment_Variables_-_simon-til_–_Vercel" src="https://user-images.githubusercontent.com/9599/106335183-23537380-6241-11eb-98e5-45c93b4d7a58.png">

**Comment by nICEnnnnnnnLee** [comment]
Did you use `builds` Field in the vercel config file?  
I tried using it when I attemped to use `FORCE_BUILDER_TAG` configured in the webpage like you, and it didn't work.  
I notice that there is a warning in the console and it seems `builds` will be soon depreciated as the [document](https://vercel.com/docs/configuration#project/builds) says.
I delete the `builds` part in `vercel.json` and it works for me; hope it will help you.

**Comment by simonw** [comment]
Yes, I'm still using `"builds"`.

**Comment by styfle** [comment]
Indeed, that env variable is for zero-config (no `builds`).

If you're using `builds`, use `@vercel/python@canary` instead.

But as mentioned above, you should avoid `builds` and use the `api` directory with `rewrites` instead.

**Comment by simonw** [comment]
Great news - that worked! I deployed https://datasette-publish-vercel-canary-6p6cb4i8x.vercel.app/ using this in `now.json`:

```json
{
    "name": "datasette-publish-vercel-canary",
    "version": 2,
    "builds": [{"src": "index.py", "use": "@vercel/python@canary"}],
    "routes": [{"src": "(.*)", "dest": "index.py"}]
}
```
And now all of these examples work correctly:

- https://datasette-publish-vercel-canary-6p6cb4i8x.vercel.app/fixtures?sql=select+date%28%27now%27%2C+%22%2B30+days%22%29 - shows the results of the SQL query `select date('now', "+30 days")`
- https://datasette-publish-vercel-canary-6p6cb4i8x.vercel.app/-/asgi-scope?sql=a%2Bb shows `query_string': b'sql=a%2Bb'` - which is correct, compared to https://til.simonwillison.net/-/asgi-scope?sql=a%2Bb which displays `'query_string': b'sql=a+b'`

Thanks very much for this fix - it looks like exactly what I needed here.

**Comment by styfle** [comment]
Great! Also note that you can rename `now.json` to `vercel.json` 👍

**Comment by styfle** [comment]
The fix is available now https://vercel.com/changelog/correcting-request-urls-with-python-serverless-functions
