### ISSUE TITLE
Python bug: error occurs when url including special charactors visited

### ISSUE THREAD

**Issue by nICEnnnnnnnLee** [vercel/vercel#5580]
The server cannot deal with url with special charactors
when the serverless function is written in python using handler that inherits from the BaseHTTPRequestHandler class.

For example, 
https://test.nicelee.vercel.app/api/date goes right, while
https://test.nicelee.vercel.app/api/date?test=%E5%93%88%E5%93%88 goes wrong, or
https://test.nicelee.vercel.app/api/date?test=哈哈 goes wrong

The serverless function follows here.
```
from http.server import BaseHTTPRequestHandler, HTTPServer
from datetime import datetime

count = 0

class handler(BaseHTTPRequestHandler):

  def do_GET(self):
    global count
    count = count + 1
    self.send_response(200)
    self.send_header('Content-type', 'text/plain')
    self.end_headers()
    self.wfile.write(str(datetime.now().strftime('%Y-%m-%d %H:%M:%S\n')).encode())
    self.wfile.write(str(count).encode())
    return
```

**Comment by nICEnnnnnnnLee** [comment]
I‘ve noticed that the `path` is `unquoted` and then proxied to the specific server.  
This means the `path` could be a string beyound `ascii`. 
It definitely causes **UnicodeEncodeError** when `http.client.HTTPConnection` trys to establish a connection in **L64** if url is ugly.
https://github.com/vercel/vercel/blob/09ff9cda9faaf0b28e863a2a06aa593fc056d6f4/packages/now-python/now_init.py#L49-L64

**Comment by TooTallNate** [comment]
Hi @nICEnnnnnnnLee. Can you please try out [this canary release](https://github.com/vercel/vercel/releases/tag/%40vercel%2Fpython%401.2.5-canary.0) (instructions at the bottom of the page) and let me know if that fixes your issue?

**Comment by nICEnnnnnnnLee** [comment]
@TooTallNate It fixes.
