### ISSUE TITLE
Issue creating external certs

### ISSUE THREAD

**Issue by abefetterman** [vercel/vercel#561]
This was working fine in 5.2, not working now in 5.3.1: 
```
now certs create xx.xxx.com -d
> [debug] /now/certs #1: 61637.077ms
> [debug] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at retry (/snapshot/home/travis/build/zeit/now-cli/lib/index.js:734:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

 (BTW, is there any way to revert to earlier now-cli version? Because this is the second time I've hit a critical bug in now alias preventing deployment)

Edit: Looks like Let's Encrypt is down, a timeout with a message might make this easier to debug for the future.

**Comment by jamo** [comment]
you can npm install a specific version `npm i -g now@<version>`
