### ISSUE TITLE
Copying url to clipboard doesn't happen on windows

### ISSUE THREAD

**Issue by dpen2000** [vercel/vercel#564]
I think this is because windows doesn't returns undefined for `process.stdout.isTTY`

**Comment by sylvainlap** [comment]
+1

**Comment by rivy** [comment]
From looking through the referred links, it looks like a simple upgrade to "clipboardy@1.2.3" fixes the issue. The resultant executable pushes the link the to clipboard correctly for me on Win10.

```
yarn upgrade clipboardy@1.2.3
```

I made a quicky PR for it (#1924).

**Comment by rivy** [comment]
This is fixed (but stalled for some reason) in PR #1924.
(cc: @leo, can you help get it merged?)
