### ISSUE TITLE
Cannot do scale/alias operations when the max number of instances is deployed

### ISSUE THREAD

**Issue by BenoitAverty** [vercel/vercel#567]
Hello,

I'm trying to migrate an alias from one deployment to a newer one. I'm on the oss plan and I have 3 instances deployed : 
```
$ now ls
unicodetool-api (2 of 2 total)
 url                                          inst #    state                 age
 unicodetool-api-kldmrnxnhn.now.sh                 1    READY                 21m
 unicodetool-api-fkvxdjaiwm.now.sh                 1    READY                  3d

unicodetool-client (1 of 1 total)
 url                                          inst #    state                 age
 unicodetool-client-dbblpejxqa.now.sh              1    READY                  3d
```

The 21m old one is the newer one and I want to change my alias from the old to the new. Here is the alias currently : 
```
$ now alias ls
> 2 aliases found [2s] under benoitaverty

  source                                         url                                   age
  https://unicodetool-api-fkvxdjaiwm.now.sh      https://unicodetool-api.now.sh         3d
  https://unicodetool-client-dbblpejxqa.now.sh   https://unicodetool-client.now.sh      3d
```

But when I try to run `now alias`, here's what happens (same thing when I use now.json or when i provide the parameters):
```
$ now alias unicodetool-api-kldmrnxnhn.now.sh https://unicodetool-api.now.sh 
> Alias unicodetool-api.now.sh points to unicodetool-api-fkvxdjaiwm.now.sh (1 instances)
> Scaling unicodetool-api-kldmrnxnhn.now.sh to 1 instances atomically
> Error! Maximum number of concurrent instances exceeded
```

Here's the scaling info : 
```
$ now scale ls
unicodetool-api (2 of 2 total)

 url                                             cur      min      max     auto      age
 unicodetool-api-kldmrnxnhn.now.sh                 1        0        1        ✔      25m
 unicodetool-api-fkvxdjaiwm.now.sh                 1        1        1        ✖       3d

unicodetool-client (1 of 1 total)

 url                                             cur      min      max     auto      age
 unicodetool-client-dbblpejxqa.now.sh              1        1        1        ✖       3d
```

So i thought I'd remove the lower limit on the old deployment, but I can't do that either ! 
```
$ now scale unicodetool-api-fkvxdjaiwm.now.sh 0 1
> Error! Maximum number of concurrent instances exceeded
```

Now the easy solution is probably to force scale the old deployment to 0 or remove it. I could do that on this project, but it doesn't always seem possible because it'd force me to have some down time.

Thanks in advance for your help.

**Comment by OrangeXC** [comment]
@BenoitAverty 
Did you find a solution now?

**Comment by BenoitAverty** [comment]
Hello,

The workaround is to scale an instance to 0 to get back to 2 deployments. I haven't found another solution. The problem was still there about 2 weeks ago (it was the last time I checked)

**Comment by OlliV** [comment]
I believe we have improved this, if you still have issues please reopen this issue.

**Comment by maks-rafalko** [comment]
@OlliV could you please what has been improved? 

I'm experiencing the same issue at the moment

```
now --version
11.4.4
```

Thank you.
