### ISSUE TITLE
DNS record value is too long (Google DKIM)

### ISSUE THREAD

**Issue by saamo** [vercel/vercel#568]
Following command

```bash
$ now dns add example.com google._domainkey TXT "v=DKIM1; k=rsa; p=<too_many_chars>"
```

returns

```bash
> Error! Unexpected error. Please try later. (Invalid `value` parameter (The maximum length is 255 characters))
```

Apparently DNS specs don't allow strings to be longer than 255 characters. According to some SO answers (see [this](https://stackoverflow.com/questions/36688278/unable-to-setup-dkim-txt-value-as-dns-record)), strings can be split. But the problem is that it seems impossible to do so with the command above.

**Comment by OlliV** [comment]
Correct. Currently we don't support splitting.

**Comment by saamo** [comment]
@OlliV, thanks for the response. And are you going to support it anytime _soon_?

**Comment by OlliV** [comment]
Not in the following few weeks.

**Comment by arturmuller** [comment]
@OlliV is there any way someone outside of Zeit could help with this?

We've moved all out stuff to Zeit World, but the above means that we have to use another domain (not managed through ZEIT) to work around the limitation.

Obviously we'd much prefer to do this properly.

If there is any way we could help, we'd be happy to do so!

**Comment by saamo** [comment]
If anybody was interested in the workaround, here it is:

1. Create TXT record (`google.domainkey.anotherdomain.com`) on another domain managed by _different provider_ (one that supports long strings) with the value `v=DKIM1; k=rsa; p=<too_many_chars>`.
2. Create CNAME record on Zeit pointing to the previously created TXT record (`$ now dns add example.com google._domainkey CNAME google.domainkey.anotherdomain.com`).
3. Voilà.

Credit goes to [Vladimir](https://www.youtube.com/watch?v=YMm7EQ3AmWw).

**Comment by OlliV** [comment]
Support for TXT record values up to 4 kiB records is now in production.
