### ISSUE TITLE
Lost Account

### ISSUE THREAD

**Issue by AkiraLaine** [vercel/vercel#575]
As the subject says, I lost access to a ‘now’ account. I used a temporary email (that i dont have access to anymore) to deploy 2 of my projects and aliased them:
https://view.now.sh/
https://mostplayed.now.sh/

I did so because my primary account had reached the maximum of 20 deployments. But since that was recently changed, is there any way you guys can unalias and remove them so that I can redeploy using my main account?

**Comment by leo** [comment]
Please send an email to support@zeit.co! 😊

**Comment by AkiraLaine** [comment]
I sent an email a few days ago, still haven't received any reply.
