### ISSUE TITLE
`now` not working on Wercker (CI)

### ISSUE THREAD

**Issue by robertvansteen** [vercel/vercel#576]
I was trying to set up `now` with my CI ([Wercker](http://www.wercker.com)) but I'm getting this error.
`Error! Unexpected error. Please try later. (Authentication error – stdin lacks setRawMode support)` 

I'm suspecting it tries to set up some kind of prompt, but I'm supplying my token with `--token` so I'm not sure where it would need a prompt for. Is this a bug or are some CI just not supported?

**Comment by Ignigena** [comment]
@rovansteen What command were you running? I had similar issues on TravisCI when using `now login` with a `--token` argument. It turns out this step isn't needed at all and I was able to just run the `now deploy` and `now alias` commands each with the `--token` without issue.

**Comment by leo** [comment]
This should be working now!
