### ISSUE TITLE
Now upload failed error, but little details

### ISSUE THREAD

**Issue by cfjedimaster** [vercel/vercel#583]
I'm using now to deploy a static web site. During the deployment, something went wrong:

![image](https://cloud.githubusercontent.com/assets/393660/26458848/1e476b8e-413a-11e7-909b-c08702a7b01e.png)

I've got little to no idea what "Response error" means here. Well, I can guess it means the CLI didn't like what it heard back from the server, but I don't know how to go forward in terms of correcting it.

**Comment by cfjedimaster** [comment]
As an FYI, I tried again, and it got a bit further (13%), but failed with the same error.

**Comment by cfjedimaster** [comment]
I bet I'm hitting an OSS plan limit - but if so - the error should detail that.

**Comment by cfjedimaster** [comment]
Any word on this? To be clear, I'm not planning on moving this particular static project, but I would like to know if now() is built to support one of this size. (It's around 5.8k files or so - you can see it at raymondcamden.com.)

**Comment by wushan** [comment]
I think I've the same issue here but the difference is I am not on OSS projects. 

I bought the PREMIUM account few days ago and deploy some side projects using nuxt.js, It works great but when I want deploy a simple pure static site, the uploading speed is super slowly and always getting the error message like this 

![screen shot 2017-09-09 at 4 09 50 pm](https://user-images.githubusercontent.com/3633628/30238388-5ce0a142-9579-11e7-966f-820c247ddd6a.png)


`(node:4389) Warning: No such label '> [debug] /sync #1 /private/var/www/jdb-report/dist/games/8021/3.png /private/var/www/jdb-report/dist/games/8021/free/3.png' for console.timeEnd()
> Error! Upload failed
> Error! Invalid file`

What does `Invalid file` exactly means ?

**Comment by ghost** [comment]
I'm on a premium account and also getting this issue with a tiny static site deploy.

**Comment by cfjedimaster** [comment]
Well this kinda lets me know I shouldn't consider paying for the service.

**Comment by jimthedev** [comment]
What version of node are you on?

**Comment by cfjedimaster** [comment]
Me? I honestly don't know what the answer was back in May.

**Comment by jimthedev** [comment]
Ok what about you node version now? Is it still happening?

**Comment by cfjedimaster** [comment]
Most likely this is addressed by what I found here (https://github.com/zeit/now-cli/issues/1038). I was testing the output of a very large static site and I don't have that sample right now. I'd say just close this. I'm using another service for static sites so I'm no longer considering Now for that purpose.

**Comment by rauchg** [comment]
@cfjedimaster I can't reproduce this issue and I uploaded a very large file. @jeremiahlee can you still reproduce this issue?

**Comment by cfjedimaster** [comment]
Ok, testing again with node 9.2.0, Windows.  There are 6046 files. 105 megs. It's been running now for about 30 minutes. Seems REAL slow. I've got a pretty beefy connection here. And it worked:

 https://public-intddyhygj.now.sh

I think this could be closed now.

**Comment by pranaygp** [comment]
@cfjedimaster what version of now are you using for this? Perhaps try using the [canary channel](https://zeit.co/blog/canary) (where we've enabled HTTP/2 for uploading) and that should make things significantly faster.

**Comment by cfjedimaster** [comment]
My now version is 9.0.1. I'll try Canary and report back.

**Comment by cfjedimaster** [comment]
Interesting - it is incredibly fast now - but I wonder if it is doing a diff? If so, that's good of course, but can you confirm that? Ie given a static site of 6K pages, is the platform smart enough to recognize nothing changed?

**Comment by cfjedimaster** [comment]
Dang - I rm'ed everything up on now to try to ensure it was 'fresh', did a deploy, and it was 40 seconds. That's a huge improvement. I'm disappointed it took this long to get feedback on the issue originally, but very pleased with the turn around.
