### ISSUE TITLE
Random response delays

### ISSUE THREAD

**Issue by debianw** [vercel/vercel#592]
Hi guys, I've been noticing slow responses in services that We have hosted in now. In order to demonstrate this I just create a small API (https://demo-api-yhqgghkgjg.now.sh/) using NodeJs, and a dummy endpoint that just sends a json object like this:

```
{
  "hello": true
}
```

Nothing to complicated, and If you start hitting this endpoint you'll see very fast response times ( 200ms average ) BUT sometimes you'll see some random delays. Attach you'll find a couple of screens using Postman. Sometimes I have to wait 3 to 4 seconds in order to get the response back.

I tried this same test using an AWS EC2 instance and all response are really fast ( no delays at all ).

Is this because `now` is a SHARE cloud service where all resources ( CPU, memory, etc ) are share between other users ?.

3129ms delay:
![screen shot 2017-05-28 at 2 58 21 pm](https://cloud.githubusercontent.com/assets/1002407/26532285/be0f8a1c-43b9-11e7-986b-0c1c5465bfef.png)

4228ms delay:
![screen shot 2017-05-28 at 3 03 35 pm](https://cloud.githubusercontent.com/assets/1002407/26532286/be320150-43b9-11e7-9b30-ff202b981983.png)

Notes: This also happens with paid accounts.

**Comment by debianw** [comment]
Checking latency benchmark:

## **Using `now` service.** -> high latency

![screen shot 2017-06-07 at 11 45 35 am](https://user-images.githubusercontent.com/1002407/26893275-157b110c-4b78-11e7-8fc5-5afe9cc5111e.png)

## **Using AWS EC2 ( using docker and deployed in ECS )** -> low latency

![screen shot 2017-06-07 at 11 50 49 am](https://user-images.githubusercontent.com/1002407/26893347-44a482ce-4b78-11e7-83dd-eb29a8c71ec3.png)

**Comment by hongymagic** [comment]
Here's an example latency test using https://latency.apex.sh

<img width="661" alt="screen shot 2017-06-08 at 9 18 20 am" src="https://user-images.githubusercontent.com/302730/26905576-7bf21d82-4c2b-11e7-8289-e7579ae5d1a2.png">

**Comment by nkzawa** [comment]
> Is this because now is a SHARE cloud service where all resources ( CPU, memory, etc ) are share between other users ?.

I think this is one of the reasons, and `3 to 4 seconds` delay can be because instance was frozen. @rase- @OlliV @jamo any thoughts?

**Comment by OlliV** [comment]
Quite likely, check your dashboard 🤔

**Comment by debianw** [comment]
Obviously before I do the latency tests I ping the service in order to wake up the api, and as soon it is available then I start testing. So I always make sure to have the service Ready and not frozen before do the tests.

**Comment by jwahdatehagh** [comment]
My instance (custom domain bought through now aliased) gets frozen every 5-7 hours. This is very annoying. Any way around it?

**Comment by sholladay** [comment]
@jwahdatehagh you can avoid frozen deploys by explicitly setting their `scale` to `1` without `auto`.

```
now scale my-app 1
```

**Comment by jwahdatehagh** [comment]
@sholladay - yeah figured that after a while 🍬
