### ISSUE TITLE
Support package-lock.json for speedy installs

### ISSUE THREAD

**Issue by jaydenseric** [vercel/vercel#593]
npm@5 is out now, introducing `package-lock.json`, which serves a similar purpose to `yarn.lock`. I'm keen to migrate back to NPM from Yarn.

Will Now take advantage of this file, [like it does with `yarn.lock`](https://zeit.co/blog/faster-javascript-deployments)?

**Comment by rauchg** [comment]
Will do

**Comment by TooTallNate** [comment]
@jaydenseric We did deploy initial support for `package-lock.json` for Now deployments the other day. Please give it a try and report any bugs!

```
npm install
✓ Using "package-lock.json"
⧗ Installing 2 main dependencies…
✓ Installed 45 modules [1s]
npm start

> @ start /home/nowuser/src
> node server.js
```

**Comment by leo** [comment]
💃
