### ISSUE TITLE
Question on Path Aliasing

### ISSUE THREAD

**Issue by saamo** [vercel/vercel#594]
When you create following rules:

```js
{
  "rules": [
    { "pathname": "/foo/**", "dest": "foo.another.com" }
  ]
}
```
Why do I still have to use `foo.example.com/foo/bar` instead of just using `foo.example.com/bar`? The problem is that the app running on foo.another.com needs to be aware of the path used in `rules.json` which makes it kinda coupled.

**Comment by nkzawa** [comment]
@jamo any thoughts ? I think it would be cool if you can rewrite paths.

**Comment by jamo** [comment]
yeah, it's coming eventually

**Comment by sedubois** [comment]
Any news @jamo on path rewriting?

**Comment by matheuss** [comment]
@sedubois it's on the roadmap. We'll post updates here as soon as we have them 👍
