### ISSUE TITLE
`files` setting doesn't work as expected

### ISSUE THREAD

**Issue by moigagoo** [vercel/vercel#596]
Consider this project:
```
$ ls -la
.gitignore
src/
foo.db
Dockerfile
now.json
```
with this .gitignore:
```
$ cat .gitignore
*.db
```
I want to start a deployment with foo.db uploaded, so I put this into my now.json:
```
$ cat now.json
{
  "files": ["foo.db"]
}
```
If I deploy that, this is what I see in the deployment source:
```
Dockerfile
now.json
```
I.e. nothing is uploaded except for Dockerfile and now.json.

If I add the current dir in now.json explicitly:
```
$ cat now.json
{
  "files": [".", "foo.db"]
}
```
this is what I get in the deployment source:
```
src/
Dockerfile
now.json
```

**Comment by chrisvire** [comment]
I am trying with this now.json file:

```
{
  "name": "render",
  "alias": "mcdurdin-render",
  "public": true,
  "files": [
    ".",
    "data"
  ]
}
```
With this repo:  https://github.com/mcdurdin/render
In my repo, I have a `.gitignore` file that excludes the data directory (so that test data is not checked in--there is one checked in as an example).

I want to include the subdirectories of the `data` directory in the deployment.  I have tried `data`, `data/*`, `data/1` and non of these has worked.  I would prefer to use just `data`.
Also, even with `"public" : true`, I still get prompted at the command line.

**Comment by moigagoo** [comment]
@chrisvire 
> Also, even with "public" : true, I still get prompted at the command line.

I was confused by this setting too. The thing is, it's a different `public`, not the one you pass with `--public`. This `public` means that your deployment exposes `/_src` path i.e. makes your app's sources public.

**Comment by chrisvire** [comment]
Looking at the source, it looks like it uses prettier globs and `data/**` should work?  It doesn't.

**Comment by chrisvire** [comment]
@moigagoo, OK.  Ignore that part.

Looking at the code, I worked around this issue by providing a `.dockerignore` (which will take precedence over the `.gitignore`).

**Comment by moigagoo** [comment]
> I worked around this issue by providing a .dockerignore

Ha! Good point! I think I'll try that too. However, I'd really rather exclude my .db files from git.

**Comment by chrisvire** [comment]
@moigagoo, you can still use your `.gitignore` file to exclude the .db file from git.  But, if you have a `.dockerignore` file, the .db file will be included in the docker image.  Realistically, you at least want `.git` and `.gitignore` in your `.dockerignore` file. :-)

**Comment by moigagoo** [comment]
@chrisvire Thanks for the tip :-)
