### ISSUE TITLE
.gitignore exclude patterns are ignored

### ISSUE THREAD

**Issue by moigagoo** [vercel/vercel#597]
Consider the following .gitignore file:
```
public/js/*.js
!public/js/foo.js
```
This should match all files except for `foo.js`, and with Git it does.

However, `now` does not upload any files from `public/js` including `foo.js`.

**Comment by chrisvire** [comment]
How can I keep now to using .gitignore file?  I have lines in the .gitignore so that data needed for the app is not checked in, but I want now to deploy the files (test data).

```
.idea
data/*
!data/.keep
```
