### ISSUE TITLE
Build logs socket doesn't reconnect / retry properly in flaky connections

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#6]
In all honesty it might, but we need to test it more.

**Comment by mreinstein** [comment]
@rauchg  https://www.npmjs.com/package/upsocket automatically handles re-connects with buffering. Might provide a reasonable solution to this. Obviously biased since I wrote it. :)

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
