### ISSUE TITLE
now's npm install excludes devDependencies

### ISSUE THREAD

**Issue by jstejada** [vercel/vercel#60]
Not sure if I missed this somewhere, but `now` seems to  _not_ install `devDependencies` when deploying. My `build` script uses webpack, which is defined as a `devDependency`, so it can't find it. Is this supported? Do I need to list all dependencies as regular dependencies?

**Comment by leo** [comment]
Are you setting `NODE_ENV` to "production" somewhere?

**Comment by jstejada** [comment]
@leo, thanks for getting back to me.
In fact it is-- I want to deploy a production build, so I set it to production so webpack builds the production build. What would be the expected workflow for this scenario?

**Comment by leo** [comment]
http://webpack.github.io/docs/cli.html#production-shortcut-p

**Comment by jstejada** [comment]
right I'm already using -p, but I want to set `NODE_ENV=production` to pass it down to React so it uses prod mode, via `DefinePlugin` (see https://facebook.github.io/react/docs/package-management.html)

In case anyone arrives here, instead of using `now -e NODE_ENV=production`, I just made my build script look like this:

```
    "build": "NODE_ENV=production webpack -p",
```

it would be nice to add some docs indicating that NODE_ENV determines what dependencies are installed. thanks @leo !
