### ISSUE TITLE
Unable to verify the first certificate

### ISSUE THREAD

**Issue by BilalDev** [vercel/vercel#6019]
Hi everyone,

I am trying to do SSR from Next.js with 2 different domain name let's say: api.com and front.com.

My front.com is hosted on Vercel and api.com is hosted on a VM that has a valid SSL certificate. I am getting this error message:

`Unhandled error during request: FetchError: request to https://api.com/api/graphql failed, reason: unable to verify the first certificate`

Any idea?

**EDIT**: maybe important note to add, we are using some port to access our API (something like api:8080.com)
**EDIT2**: I tried with 443 for https so it's https://api.com, but still same issue.

Cheers

**Comment by trek** [comment]
Hi @BilalDev,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community. For issues related to Next.js, please post to [vercel/next.js](https://github.com/vercel/next.js)
