### ISSUE TITLE
Package.json is not picking up now config when running `now deploy path`

### ISSUE THREAD

**Issue by dkouvdis** [vercel/vercel#604]
I have a package.json file that goes like this
```
"now": {
    "name": "project-name",
    "alias": "example.com",
    "type": "static",
    "public": false
 }
```

and I run `now deploy build/`, 

---
### Result
It deploys to `https://build-xxxxxxxx.now.sh` with not setting the alias.

### Expected
Deploy to `https://project-name.xxxxxxxx.now.sh` and set the alias

**Comment by TooTallNate** [comment]
@dkouvdis To clarify, is the `package.json` file in the "path" directory or in your current working directory?

**Comment by dkouvdis** [comment]
@TooTallNate package.json is sitting in the root of the working directory. 

The "build/" is the path to my dist folder meaning I am deploying my "build" folder.

I have made amend to the post to avoid confusion

**Comment by TooTallNate** [comment]
Right. [This has been brought up before](https://github.com/zeit/now-cli/issues/549), but the `package.json` file is expected to be inside your `build` directory.

This could probably use some clarification in the docs since it appears to be confusing.

**Comment by leo** [comment]
We didn't support this before - just added support for it.

**Comment by leo** [comment]
However, @TooTallNate's comment is also true: `package.json` needs to be inside the build dir.
