### ISSUE TITLE
Serve static assets with an efficient cache policy

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#6069]
I ran my site (hosted on Vercel) through google page speed and the issue it is giving me is around some images telling me to serve static assets with an efficient cache policy. Because this isn't a 'traditional' site where I can go and do things in a .htaccess file, how would I fix this? 

I am using next version 10.0.9

On this particular page I am using getStaticProps with a revalidate time of 30 seconds and I am fetching my data from a wordpress backend using GraphQL, not REST API.

**Comment by conioX** [comment]
any news on this?

**Comment by trek** [comment]
Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
