### ISSUE TITLE
Spawn multiple process of update-notifier when upgrade now-cli@6.2.3 using npm@5

### ISSUE THREAD

**Issue by gpalli** [vercel/vercel#608]
Hi!, I'm getting these process spawned automatically, it happends after running this command:

npm install -g now@latest (6.2.3)

The CPU started to raise and running ps -fA | grep now brings =>

501 23637 1 0 5:07PM ?? 0:00.50 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23643 1 0 5:07PM ?? 0:00.50 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23646 1 0 5:07PM ?? 0:00.50 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23656 1 0 5:07PM ?? 0:00.49 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23657 23656 0 5:07PM ?? 0:00.48 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23658 23657 0 5:07PM ?? 0:00.48 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23663 23658 0 5:07PM ?? 0:00.47 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23664 23663 0 5:07PM ?? 0:00.46 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23665 23664 0 5:07PM ?? 0:00.47 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23670 23665 0 5:07PM ?? 0:00.41 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23683 23670 0 5:07PM ?? 0:00.20 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}
501 23692 23683 0 5:07PM ?? 0:00.02 /usr/local/lib/node_modules/now/download/dist/now /snapshot/home/travis/build/zeit/now-cli/node_modules/update-notifier/check.js {"pkg":{"name":"now","version":"6.2.3"}}

I get rid of those with this command:

pkill -f now

It keep spawning process periodically.

**Comment by matheuss** [comment]
Fixed via #609 🙏 Thank you for reporting @gpalli
