### ISSUE TITLE
Bug: Unable to deploy static apps

### ISSUE THREAD

**Issue by mattphillips** [vercel/vercel#612]
I think you have a bug with static deployments and instance count.

I am unable to deploy any static apps when my instance limit is hit, even though static deployments do not count towards instances.

Error message:
`Error! Too many active deployment instances`

Steps:
1. Use all account instances with dynamic apps
2. Deploy a static app

![screen shot 2017-06-01 at 12 58 56](https://cloud.githubusercontent.com/assets/5610087/26678851/6f7d47d6-46ca-11e7-90b7-fa83c966e371.png)

`a`, `b` and `c` are dynamic apps
`static` and `static2` are static apps

**Comment by OlliV** [comment]
I believe this was fixed a long time ago but we'll check.

**Comment by lucasavila00** [comment]
I'm having the same issue.
Also, I can't unescale a service to be able to add one more instance.
$ node -v
v8.11.3
$ now -v
11.2.4
$ npm -v
5.6.0
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.6
BuildVersion:	17G39b

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
