### ISSUE TITLE
Rewrites get stuck with ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by styxlab** [vercel/vercel#6126]
# Description

I have 2 independent Next.js apps configured on the following subdomains/paths:

- [https://news.blogody.io/news](https://news.blogody.io/news)
- [https://landing.blogody.io/landing](https://landing.blogody.io/landing)

These 2 pages work as expected and I now want to make them available under a single domain:

- [https://www.blogody.com/news](https://www.blogody.com/news)
- [https://www.blogody.com/landing](https://www.blogody.com/landing)

For that, I made a third, ingress repository on Github [blogody-ingress](https://github.com/styxlab/blogody-ingress) with the following rewrite config in `next.config.js`:

```
{
  async rewrites() {
    return [
      {
        source: '/landing/:path*',
        destination: 'https://landing.blogody.io/landing/:path*',
      },
      {
        source: '/news/:path*',
        destination: 'https://news.blogody.io/news/:path*',
      },
    ]
  },
}
```

When I build locally, [blogody-ingress](https://github.com/styxlab/blogody-ingress) works perfectly and the 2 external pages can be visited under

- [http://localhost:3000/news](http://localhost:3000/news)
- [http://localhost:3000/landing](http://localhost:3000/landing)

as expected. However, after I have deployed [blogody-ingress](https://github.com/styxlab/blogody-ingress) to Vercel, rewrites are not working anymore and I get ERR_TOO_MANY_REDIRECTS.

# Comparison of the local (working) and Vercel (not working) builds:

The request/repsonse pattern for [http://localhost:3000/news](http://localhost:3000/news) looks as follows:

```
Request URL: http://localhost:3000/news
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:3000
Referrer Policy: strict-origin-when-cross-origin

Response:
access-control-allow-origin: *
age: 0
cache-control: s-maxage=0
content-disposition: inline; filename="index"
content-encoding: br
content-type: text/html; charset=utf-8
date: Tue, 20 Apr 2021 13:44:18 GMT
etag: W/"3e271e589d565d73b7bf1009319df865a7832290f5e60b2c3cdca620a3f2f987"
server: Vercel
strict-transport-security: max-age=63072000
Vary: Accept-Encoding
x-vercel-cache: HIT
x-vercel-id: cdg1::f7qct-1618926258668-5823d17846cc

Request:
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Host: localhost:3000
If-None-Match: W/"3e271e589d565d73b7bf1009319df865a7832290f5e60b2c3cdca620a3f2f987"
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: same-origin
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
```

wheras the Vercel deployd request/response:

```
Request URL: https://www.blogody.com/news
Request Method: GET
Status Code: 308 
Remote Address: 76.76.21.21:443
Referrer Policy: strict-origin-when-cross-origin

Response:
cache-control: s-maxage=0
content-type: text/html
date: Tue, 20 Apr 2021 13:42:20 GMT
location: /news
refresh: 0;url=/news
server: Vercel
strict-transport-security: max-age=63072000
x-vercel-id: cdg1:cdg1:cdg1::sw97z-1618926140549-e0a891a3489e

Request:
:authority: www.blogody.com
:method: GET
:path: /news
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: max-age=0
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: none
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36

```

So it looks as if the rewrite is doing a redirect to itself, leading to an infinite loop ending with ERR_TOO_MANY_REDIRECTS.

# What I tried without success

- I also changed the rewrite config from the `next.config.js` to a `vercel.json` but this didn't make any difference (same infinite loop)
- Followed instructions on https://vercel.com/support/articles/how-can-i-serve-multiple-projects-under-a-single-domain?query=rewrite#deploying-rewrite-rules

# Expectation

Rewrite rules when deplolying to Vercel should work the same way as they do when deploying the same Next.js project locally.

**Comment by styxlab** [comment]
Looks like I found a workaround, by specifying an additional route without wildcards:

```
{
  async rewrites() {
    return [
      {
        source: '/landing',
        destination: 'https://landing.blogody.io/landing',
      },
      {
        source: '/landing/:path*',
        destination: 'https://landing.blogody.io/landing/:path*',
      },
      {
        source: '/news',
        destination: 'https://news.blogody.io/news',
      },
      {
        source: '/news/:path*',
        destination: 'https://news.blogody.io/news/:path*',
      },
    ]
  },
}
```
I think this is either an error or it is an "undocumented feature". Noteworthy: This is only needed on Vercel but not on local Next.js deploys.

**Comment by styxlab** [comment]
For anyone coming across this issue: The above `basePath` config on the external domains seem superfluous but  the setup does not work without them (if you know a way to configure the same without `basePath` please let me know).

**Comment by marcinincreo** [comment]
Still an issue in 13.4.8, solution with wildcard works.

**Comment by ChitlangeSahas** [comment]
Wow. Burnt 4 hours and this is what I needed. Thank you @styxlab. 

The worst part was that it was doing fine locally, so hard to test.
