### ISSUE TITLE
Vercel deployment stuck on BUILDING

### ISSUE THREAD

**Issue by LatentM** [vercel/vercel#6233]
> @BenDiuguid for now we're focused on deployments that expose an HTTP port, so you could just fire up an HTTP server like:
> 
> ```
> const {createServer} = require('http')
> 
> const server = createServer(() => {})
> 
> server.listen(3000)
> ```
> 
> And then you should be good!
> 
> However, it shouldn't be stuck on `BUILDING` – it should timeout after a little while. We'll investigate why it's acting like that – thanks for reporting!

I am also facing this issue right now. It's stuck on BUILDING

**Comment by LatentM** [comment]
This is a serious issue. You guys at Vercel need to fix it

**Comment by trek** [comment]
Hi @mubashir2005,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
