### ISSUE TITLE
`now ls` throws after logging in

### ISSUE THREAD

**Issue by igorklopov** [vercel/vercel#633]
now 6.3.1, macos

`rm ~/.now.json`
`now ls`

I log in and see
```
Cannot read property 'username' of undefined
at list (/snapshot/home/travis/build/zeit/now-cli/bin/now-list.js:148:145)
```

**Comment by jamo** [comment]
I also run into this after trying to use now with limited network access (api.zeit.co didn't resolve)

**Comment by jamo** [comment]
uups, wrong button

**Comment by igorklopov** [comment]
GitHub should have 'are you sure?' before closing 😄 Even in-place button to make us click that place twice.

**Comment by sylvainlap** [comment]
Got the same issue.
