### ISSUE TITLE
Seems like something is missing when choosing to add an integration to my account

### ISSUE THREAD

**Issue by RivkyB** [vercel/vercel#6332]
![image](https://user-images.githubusercontent.com/59144428/120912940-6bf0c280-c661-11eb-9b27-7e9d47c4933b.png)

I am trying to add a google cloud integration and it says null before my name in the dropdown. 🤔

**Comment by trek** [comment]
Hi @RivkyB,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
