### ISSUE TITLE
Standalone external alias

### ISSUE THREAD

**Issue by Sequoia** [vercel/vercel#636]
* I have `app` on now at `app.now.sh`
* `app` is a monolith that currently has `/Foos` path to get `Foo` objects from DB
* `app` *also* needs to be able to call the `Foos` APIs internally, so if `foo-api` is split off the application it must know where it is.
* My goal is to 
  1. FIRST: Remove `foo-api` to separate application on now & passthrough alias to it from `app.now.sh` on `pathname: Foos*`
  2. LATER: Remove `foo-api` to a hosted API on bluemix (`foo-api.mybluemix.com/Foos`, and pass through to it on `pathname: Foos*` (same alias)

## What works

1. Deploying `foo-api` to `now`
2. Aliasing it on now: `now alias foo-api-o92u7oasjdfakl.now.sh foo-api`
2. Passthrough aliasing to it from `app.now.sh`:
    ```json
    { "pathname": "/Foos**", "dest" : "foo-api.now.sh" }
    ```
3. Setting `FOO_API` as an ENV far on `app.now.sh` instance so it knows where to look up `Foos` internally: `[~/app/] $ now -e FOO_API="https://foo-api.now.sh"`

## What doesn't work

Now I want to move my `foo-api` to bluemix and point `foo-api.now.sh` to bluemix so:
1. The existing pass through alias on `app.now.sh/Foos*` still works
2. **Calling the foo api via `process.env.FOO_API` within `app.now.sh` still works without me having to redeploy with new ENV vars** because `foo-api.now.sh` now points to external

Step 2 above is what I can't figure out. I would like `app` to *not* be aware of where its calls to `foo-api.now.sh` actually go so it can transparently be switched to from now-local to remote without having to redeploy `app` with new env vars. This would require *two* steps for migration:
1. Change alias
2. Change path internally

Where I would like just 1.

# Question

Is it possible to set up an alias without an instance? Example:

`now alias https://foo.mybluemix.com foo-api.now.sh`

**Comment by Sequoia** [comment]
Looks like it works, just not from the CLI. One must use a rules file:

```
$ now alias https://foo.mybluemix.net foo-api.now.sh
> Error! Deployment not found by "https://foo.mybluemix.net". Run `now ls` to see your deployments.

$ cat rules.json
{
  "rules" : [
    {"dest": "https://foo.mybluemix.net"}
  ]
}

$ now alias --rules ./rules.json foo-api.now.sh
> Success! 1 rules configured for foo-api.now.sh [1s]
```

**Comment by TooTallNate** [comment]
Closing because you can use [`routes` in your `now.json` file](https://zeit.co/docs/v2/advanced/routes) (for Now v2) or [Path Alias](https://zeit.co/blog/path-alias) (for Now v1) to accomplish this feature.
