### ISSUE TITLE
Output url only from now deploy

### ISSUE THREAD

**Issue by Sequoia** [vercel/vercel#637]
Is it possible to `now deploy` and get the new URL back as a string? i.e. *just* the URL.

## Example

```
$ now deploy --url | xargs -I% now alias % my-alias.now.sh
```

1. `now deploy --url` returns `package-name-9824ajklszdj2q5.now.sh`
2. xargs runs `now alias package-name-9824ajklszdj2q5.now.sh my-alias.now.sh`

**Comment by leo** [comment]
Doesn't `now | xargs` work?

**Comment by jamo** [comment]
or `$(now)` like `now alias $(now) my-app.now.sh`

**Comment by leo** [comment]
These two options above are possible ^ 😊
