### ISSUE TITLE
now rm $(now ls)

### ISSUE THREAD

**Issue by tercerapersona** [vercel/vercel#638]
It would be nice if `now ls` could return only deployment ids if there's no tty, to let us pipe the result to another.

Just like in docker we can do `docker rm $(docker ps -aq)`.
In now, it could be `now rm $(now ls)` 

Or explicitly tell silent mode `-s`, `now rm $(now ls -q)`

**Comment by leo** [comment]
I don't think we'll ever support this - there just aren't any valid use cases. You can use `now rm <app-name>` to remove all deployments with a specific name... 😊
