### ISSUE TITLE
Hide "vercel.app" in navigation bar

### ISSUE THREAD

**Issue by sauravgupta2800** [vercel/vercel#6407]
### Discussed in https://github.com/vercel/vercel/discussions/4809

<div type='discussions-op-text'>

<sup>Originally posted by **Okilele-newbie** July  8, 2020</sup>
I have a domain name  "my domain.com" redirected to "mydomain" project on Vercel. This works perfectly but I would like when somebody enters my domain.com in its navigator this remains as he entered it and not replaced by mydomain.vercel.com. 
Actually I think this is not acceptable for a production site.
Is there a solution?</div>

**Comment by leerob** [comment]
Answered here: https://github.com/vercel/vercel/discussions/4809#discussioncomment-34791
