### ISSUE TITLE
Now scale throws error for docker deployments in BUILDING status

### ISSUE THREAD

**Issue by vladisav** [vercel/vercel#642]
Now scale cannot be called immediately after deployment (e.g. inside a script),
if attempted the following error occurs:

now scale --debug https://upload-service-aqlyobpave.now.sh 1
> [debug] /list: 964.816ms
> Deployment is currently in 0 replicas, preparing deployment for scaling...
> [debug] #1 POST /deployments/zI5gXiMWlSkcLqMIiHtohh7G/instances: 891.363ms
> Error! An unexpected error occurred

Same thing happens if alias is called for a new instance of a pre-scaled deployment:

now alias content-service-ktesmqrzja.now.sh https://content-service.xxxxx
> Alias content-service.xxxxx points to content-service-aekxwisoip.now.sh (1 instances)
> Scaling content-service-ktesmqrzja.now.sh to 1 instances atomically
> Error! An unexpected error occurred

**Comment by leo** [comment]
@OlliV @jamo Any ideas?

**Comment by OlliV** [comment]
I'd say it's a feature. You should query it's state and scale it only after its status is set to READY.

**Comment by vladisav** [comment]
Perhaps I don't understand, but I'm curious why should this be a feature?
Wouldn't it be more sensible to let 'now' know that you want to scale, and 'now scale' deal with it internally? 

Our use case is to run the whole deployment from a script (and bunch of other stuff), and it would be much easier to simply call 'now scale' right after deployment (without waiting for deployment to finish), the same way 'now alias' works. Any thoughts on how to accomplish this?

**Comment by zgeoff** [comment]
Unless I misunderstand, this logic prevents a CI from auto-aliasing on a scaled instance, no? Running `now` immediately followed by `now alias` is always going to fail?

**Comment by zgeoff** [comment]
@OlliV is there any update on this? we've removed any scaling configuration from our staging build so that we can `now` then `now alias` in our CI service for staging builds, but knowing that our server may spin down after inactivity, can't do the same for production. is there a solution or any foreseeable changes to support this?

**Comment by OlliV** [comment]
`now alias` will probably work just fine after running `now` but why do you want to do it like that? What if the build stage fails, what's the use case for an aliased and scaled deployment that fails to even start?

**Comment by OlliV** [comment]
Currently there is no plans to change the behaviour.
