### ISSUE TITLE
Nextjs 10.0.6 rewrite error on vercel 502 `TOO_MANY_FILESYSTEM_CHECKS`

### ISSUE THREAD

**Issue by oti4me** [vercel/vercel#6450]
### Discussed in https://github.com/vercel/vercel/discussions/6444

<div type='discussions-op-text'>

<sup>Originally posted by **oti4me** July  7, 2021</sup>
I am getting a TOO_MANY_FILESYSTEM_CHECKS error on Vercel trying to make an api call using rewrite to route requests to the api. Everything works fine locally.

next.config:

```
 module.exports = {
  reactStrictMode: true,
  async rewrites() {
    return [
      {
        source: '/my-api/:path*',
        destination: `${process.env.NEXT_PUBLIC_API_URL}/:path*`,
      },
    ]
  },
}
```
Usage

```
import {GraphQLClient} from "graphql-request"
...
...
export default new GraphQLClient("/my-api/graphql")
```
The same code works fine on next@11.0.1. Any pointer, please??

</div>

**Comment by rambabusaravanan** [comment]
same for me too ...
I am facing this issue on next@11.0.1 itself.

Maybe you check on this if this workaround can fix for you https://github.com/vercel/next.js/discussions/15793#discussioncomment-45893

**Comment by leerob** [comment]
Yes, I would recommend continuing this conversation on the Next.js repo as mentioned above: https://github.com/vercel/next.js/discussions/15793
