### ISSUE TITLE
Vercel's "Usage" tab shows much higher bandwidth use than is transferred to the client

### ISSUE THREAD

**Issue by kristjanmar** [vercel/vercel#6468]
### Discussed in https://github.com/vercel/vercel/discussions/6459

I'm developing a NextJS site on Vercel and I've tested browsing my site myself and tracking the changes in Bandwidth in their "Usage" tab, which appears to update immediately after refreshing.

There is no one else visiting the site since it's just a development site, although I've added it to an actual domain on vercel. The bandwidth usage was zero before my first pageview.

The problem is that the bandwidth shown in the Usage tab is much higher than the bandwidth consumed by my browser according to Chrome Developer Tools. As in, 2-8 times higher.

**Here's an example:**

1. I have developer tools open on the "Network" tab. Cache is not disabled.
2. I go to a new page that is quite heavy, so the kB transferred goes up by 300KB. Prefetching of links is not enabled.
3. However, the bandwidth in the Usage tab goes up by 1.5MB.

I've already turned off the aggressive prefetching of links and taken steps to reduce my bundle size by 70%. But the bandwidth usage per session and pageview according to Vercel didn't budge.

I really want to find a solution to this. I am currently on the Pro plan and I would like to remain within the 1TB fair use limit while my site is in its early stages, but I don't think that's going to be an easy task if Vercel uses a number that is many times higher than the actual kilobytes sent from server to client.

**Comment by kristjanmar** [comment]
I just enabled my site on Cloudflare 24 hours ago. They report 12GB data transferred in the past 24 hours, thereof oly 7GB from the origin -- which is my Vercel hosted site.

However, Vercel is reporting 35 GB of bandwidth used, which is 5 times more than the bandwidth transferred from Vercel's servers! What is going on here?

Is Vercel then going to force me off of the Pro plan unless if I fork up thousands of dollars a month because of a fraudulent bandwidth metric?

**Comment by kristjanmar** [comment]
Last 24 hours, Cloudflare reports 2.57GB served by the Origin (Vercel). At the same time, Vercel reports 15.3GB. Vercel's number is 6 times higher.

![cloudflare-bandwidth](https://user-images.githubusercontent.com/22234692/129290281-f6d6862b-f971-47a7-a75f-122ce4b1d811.png)

![vercel-bandwidth](https://user-images.githubusercontent.com/22234692/129290252-6bbe4101-2453-4fff-9c6f-79d4b6b47ece.png)

**Comment by leerob** [comment]
https://github.com/vercel/vercel/discussions/6459#discussioncomment-1696358
