### ISSUE TITLE
Too many active deployment instances

### ISSUE THREAD

**Issue by debianw** [vercel/vercel#647]
I'm getting this error "Too many active deployment instances". But I only have 3.

![screen shot 2017-06-07 at 10 48 13 am](https://user-images.githubusercontent.com/1002407/26890524-fd74a8d8-4b6e-11e7-87a9-5ec3bf53483b.png)

**Comment by nkzawa** [comment]
What is your current plan ? If it's `OSS`, the limit of concurrent active instances is `3`.

**Comment by debianw** [comment]
Is a free plan. I updated the now-cli and tried a couple of hours later and now I can do more deploys.

**Comment by nkzawa** [comment]
@debianw I guess an instance became inactive and you could deploy more. Closed for now.

**Comment by matheuss** [comment]
@debianw you can `now rm <url>` to remove a deployment or `now scale <url> 0` to freeze one permanently 👍 With that you'll free up a spot :)

**Comment by LuisPaGarcia** [comment]
You can use  **now rm INSTANCE_URL**  to remove STATE = READY instances

https://zeit.co/blog/now-rm-is-here-and-more

**Comment by mtskf** [comment]
There's no instance when I run `now ls`, but it keeps on saying "> Error! Too many active deployment instances"... What's wrong?

**Comment by simonsisay** [comment]
@matheuss Thank you
