### ISSUE TITLE
Using `--token` to deploy as a team

### ISSUE THREAD

**Issue by richardgill** [vercel/vercel#649]
I'm looking to deploy to now automatically from CI. On the site I can only get a token for my user, not my team. When I deploy using that token (using `--token`) it deploys under my user not under my team.

Am I missing something? I was looking for a `--team` or a token for the team.

**Comment by nkzawa** [comment]
It seems there is no way to do that for now :(

**Comment by leo** [comment]
The `--token` option always holds your user key. If you want to switch the team in the CI, you need to run the command `now switch <team-name>` to set the scope.

**Comment by richardgill** [comment]
@leo for Continuous Integration you're not going to be logged in to start off with.

I'm simulating this by logging out first.

```
now logout 
now switch <team-name> --token=token
```

Gives me:
```
Fetching teams> Error! Unknown error: Error: Unauthorized
```

**Comment by leo** [comment]
I see! https://github.com/zeit/now-cli/issues/655

**Comment by chhuang** [comment]
This's probably not ideal but we are planning to pay for a new user account just to do this and stop using team.

Is there any workaround to deploy from CI using the team account?

**Comment by CalinaCristian** [comment]
Hey guys, maybe it helps, they added a --scope to now and now you can use --scope <team_name> https://zeit.co/blog/introducing-scope
