### ISSUE TITLE
git based dependencies doesn't work

### ISSUE THREAD

**Issue by remy** [vercel/vercel#65]
Example deploy: https://code-flow-svuzhcsykp.now.sh/

The problem is that `image-to-ascii` contains a git based dependency, which `now` can't install, and throws an `UnhandledPromiseRejectionWarning` from a `404 (see logs in URL above).

This is the dep tree:

```
├─┬ image-to-ascii@3.0.3
│ ├─┬ asciify-pixel-matrix@1.0.4
│ │ └─┬ asciify-pixel@1.2.4
│ │   ├─┬ couleurs@6.0.3
│ │   │ ├─┬ ansy@1.0.4
│ │   │ │ ├── ansi-styles@2.1.0 (git://github.com/chalk/ansi-styles.git#5dadc5c6333127f95dc0dc09ada4fbde8bf66e69)
```

I tried to make `ansi-styles@2.1.0` a direct dependency of my project to allow the code to still run, but the failed install process doesn't allow my project to start, so I can't work around the issue. Essentially the 404 is a total blocker for using this `image-to-ascii` project (pending a PR to _it's_ repo!).

For reference, since the source doesn't work on the deployment (not sure why), here's the `package.json` dependencies:

```
"dependencies": {
  "ansi-styles": "^2.1.0",
  "busboy": "^0.2.13",
  "express": "^4.14.0",
  "image-to-ascii": "^3.0.3",
  "multer": "^1.2.0"
}
```

**Comment by leo** [comment]
If this problem still occurs, please move it over to [this repo](https://github.com/zeit/now-cloud). That's where we'll collect the bugs of the platform from now on (separate space, easier to work on)! 😊 

@TooTallNate are they working now?

**Comment by TooTallNate** [comment]
GitHub style URLs are working now. Generic git URLs not quite yet.
