### ISSUE TITLE
Nodemailer dosen't send emails after deployment. Vercel. Zeit Now.

### ISSUE THREAD

**Issue by satinder1624** [vercel/vercel#6530]
### Discussed in https://github.com/vercel/vercel/discussions/4387

<div type='discussions-op-text'>

<sup>Originally posted by **jjjuk** May 14, 2020</sup>
I'm making reset password by email with graphql prisma. Nodemailer sendMail doesn't send email after first fire of mutation, but it sends email from first mutation after second firing. Basicaly sendMail only works if I run it twice.

Sometimes It throws error: 

`"Unexpected token A in JSON at position 0"`

Here's a piece of code inside mutation resolver:

```
const auth = {
          type: 'oauth2',
          user: [my email],
          clientId: [my client id]',
          clientSecret: [my client secret],
          refreshToken: '[my refresh token]
      };
      
const transporter = nodemailer.createTransport({         
          host: 'smtp.gmail.com',
          port: 465,
          secure: true, 
          auth
      });

```

```

const mail = {
 from: [my email],
 to: [email], 
 subject: 'Password Reset',
 html: [my html]
    };

```

      
    transporter.sendMail(mail, (err, info) => {
          if (err) {
              throw new Error(`${err}`)
          } else {
             return console.log(JSON.stringify(info));
          }
      });
</div>

**Comment by trek** [comment]
Hi @satinder1624,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
