### ISSUE TITLE
Download Environment variables

### ISSUE THREAD

**Issue by AaronLayton** [vercel/vercel#6541]
Feature request to add a 1 click button to download all the environment variables that are setup for a project.

Download it as a `.env` file with key value pairs, default the name to `.env.local`

Use case is I have my projects setup on my main PC, I quickly need to do some client changes but I am on my laptop. I now have to click edit on each entry and manually build the local env file.

Having this button to download would be an amazing time saver

**Comment by styfle** [comment]
Hi @AaronLayton 

You can download Vercel CLI:

```
npm i -g vercel
```

Then link your local project directory to your Vercel project in the cloud:

```
vercel link
```

Then pull the development environment variables:

```
vercel env pull .env.local
```

Learn more: https://vercel.com/docs/environment-variables

**Comment by Pedro-Laurenti** [comment]
Although the Vercel CLI feature, the normal user needs a front-end option too.

The **IMPORT** option already exists, why **EXPORT** dont?

Cordially.

**Comment by Ebrahim-Ramadan** [comment]
> vercel env pull .env.local

thank you that just worked

**Comment by ukane-philemon** [comment]
@styfle Please consider reopening this issue. UX >>> cli can do this

**Comment by AaronLayton** [comment]
I totally forgot I even opened this issue 😅

I would agree with everyone here, the CLI is fine and did work for my needs, but I think there should be an easy download for the environment variables.

@styfle Even something as simple as this will be fine

![Group 1 (2)](https://github.com/user-attachments/assets/30d1ecb9-4310-4922-89ed-a9689d65ec69)

**Comment by styfle** [comment]
This issue tracker is for Vercel CLI.

You can create a general feature request at https://vercel.community

**Comment by ukane-philemon** [comment]
> This issue tracker is for Vercel CLI.
> 
> You can create a general feature request at https://vercel.community

@AaronLayton please can you do the honours? 🌚

**Comment by AaronLayton** [comment]
Ok added it there 😉

The experience of using that portal though felt very disjointed and almost like I am just posting it to the ether. It feels just like a Forum and not a a correct Issue / Feature Request tracker. 

https://vercel.community/t/add-an-export-env-button-to-the-environment-variables-page/1342

**Comment by ukane-philemon** [comment]
Thanks @AaronLayton. 

>The experience of using that portal though felt very disjointed and almost like I am just posting it to the ether. It feels just like a Forum and not a correct Issue / Feature Request tracker.

And yes, I second this. It seems they are active there though.

**Comment by khanakia** [comment]
@styfle it does not downloads the Private keys it's only downloading the keys prefix with `NEXT_PUBLIC_xxx`

**Comment by CaioGiasson** [comment]
If the cli is the only way, that's sad
The project is deployed in my organization (pro plan), and still can't link it properly.
I just want my env variables without copying-pasting every one of them, and I don't want to fight the cli to make it work for me.

Error: Failed to connect the GitHub repository botpag/parcelatudo-2022.
Error: The repository "parcelatudo-2022" is private and owned by an organization, which is not supported on the Hobby plan. Upgrade to Pro to continue. (409)

That is just sad. There is no better word

**Comment by ukane-philemon** [comment]
<img width="796" height="306" alt="Image" src="https://github.com/user-attachments/assets/607b3d6e-1960-4d2b-820c-56c9fb39f0df" />

@CaioGiasson, you can import your envs on the vercel UI

**Comment by oknoorap** [comment]
@ukane-philemon what I want is exporting .env keys from vercel to local
