### ISSUE TITLE
`now switch` needs to support `--token`

### ISSUE THREAD

**Issue by leo** [vercel/vercel#655]

**Comment by jamo** [comment]
We really need to add `--team (-T)` to support doing action in team context; 
`now --token <mytoken> --team <myteam>`

also, we really need to ensure, not to modify `~/.now.json` when using `--token` as currently it updates team/current context and then `now` blows up when omitting `--token` next time

**Comment by nkzawa** [comment]
btw It seems `now switch` already supports `--token`.

**Comment by davemcorwin** [comment]
yes it does, thoughts on closing this and creating a new one to add the team option suggested by @jamo ? Then one wouldn't have to `now switch` before `now`ing ...

**Comment by leo** [comment]
https://github.com/zeit/now-cli/issues/676
