### ISSUE TITLE
Post-install always getting `UPDATE NEEDED Current: 0.34.0 – Latest 6.3.2 (released 1d ago)`

### ISSUE THREAD

**Issue by jhwheeler** [vercel/vercel#658]
Hi everyone,

Every time I run `npm install -g now`, everything looks fine until I run `now --version` and I get the following error:

`UPDATE NEEDED Current: 0.34.0 – Latest 6.3.2 (released 1d ago)`

Which is especially strange, since the terminal outputs this at the end of the install:

```
+ now@6.3.2
added 1 package in 107.084s
```

Does anyone else have this issue and/or know what exactly is going on? 

Thank you!

**Comment by igorklopov** [comment]
Please `which now && rm $(which now) && npm i -g now`

**Comment by igorklopov** [comment]
If does not help, please post here: `which now` and `which npm` results

**Comment by jhwheeler** [comment]
This worked! Fantastic, thank you very much for your prompt reply, Igor! Much appreciated.
