### ISSUE TITLE
Vercel won't deploy, or takes a LONG time to do so

### ISSUE THREAD

**Issue by AR-Student824** [vercel/vercel#6586]
Alright, so I was making a simple weather website, and earlier today I decided to fix a bug that was in it, and when I pushed, I tried reloading my weather website again and again but it wouldn't show the updated version. I then decided to go into Vercel, where I see that the latest deployment was stuck on Queued. I waited for about 5 minutes, and then I just deleted the project and added it back, but it was still doing the same thing, this time showing the 404 page on the website as well. I waited for about 30 minutes, and it decided to deploy. I thought nothing of it, and pushed another commit adding a couple more features, but again this took like 15 minutes. This keeps happening, and it gets stuck on Queued for a LONG time, then deploys, which is really annoying.

The weather website in case it's needed - https://weather.ar-dev.cf
The framework used - Next.js

**Comment by youminkim** [comment]
Hi, exactly same thing happened to me in https://take.app 
Some customers still complain 404 page issue 

I am not sure it is related but I upgraded to nextjs 11.1 and this happened. The version with 11.1 still has 404 issue https://tk-8xn9xtdtx-takeapp.vercel.app/

I had to redeploy previous version.

**Comment by RizBizKits** [comment]
Hey, I can confirm that the team is taking a closer look at this issue. @AR-Student824 are you using Next.js 11.1 by any chance? If so, did the problem occur only after updating?

We'd greatly appreciate it if you could submit a ticket through https://vercel.com/support/request so the Customer Success team can track and prioritize? It'd be very useful if you could include your `vercel.json` / `next.config.js`, as well as a minimal code reproduction!

**Comment by danilobjr** [comment]
Yeah, same issue here. I'm trying to deploy only a static website (only HTML, CSS and JS). Building process is about 15 minutes right now and nothing happens. 

EDIT:
After 17 minutes, I've canceled and deployed it from terminal using `vercel` CLI and it's alright now.

**Comment by trek** [comment]
Hi @AR-Student824,
Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
