### ISSUE TITLE
Vercel golang api

### ISSUE THREAD

**Issue by The-Code-Monkey** [vercel/vercel#6587]
So i have a deployment where i have a NextJs frontend with an api written in go for the handler, what is strange is that when vercel is trying to deploy it, it throws an error saying it cant find go.

This is my config for the app
![Screenshot from 2021-08-13 09-30-41](https://user-images.githubusercontent.com/31218527/129329375-4afd2ed2-dde6-4604-ad74-4a9b93abde6e.png)

this is the error, i dont call go get anywhere it seems to be something vercel is doing because it can find a .go file in the api directory.
![Screenshot from 2021-08-13 09-38-21](https://user-images.githubusercontent.com/31218527/129329641-f9df11d3-b835-4101-9a79-bf78abc6f85d.png)

is there any sort of help that anyone with experience setting up go can give me?

**Comment by The-Code-Monkey** [comment]
Another issue is that it just seems to sit on deploying build outputs 
![Screenshot from 2021-08-13 09-57-23](https://user-images.githubusercontent.com/31218527/129332332-3db372ef-e4d6-45be-b6f4-c49705370de3.png)

**Comment by trek** [comment]
Hi @The-Code-Monkey,

Thanks for reaching out! We use this Issue tracker for bugs in the Vercel CLI and related open source libraries. For general platform help and feedback please open a new discussion at https://vercel.community.
