### ISSUE TITLE
Tunnel an alias to your local dev machine

### ISSUE THREAD

**Issue by divmain** [vercel/vercel#659]
Hey there!

I've been working on a GitHub integration and kept feeling as though I wanted a faster iteration cycle between making changes on my dev box and testing those changes via GitHub.  To combat that, I put together [`tunnel.now`](https://github.com/divmain/tunnel.now).

It functions similarly to [localtunnel](https://localtunnel.me) or [ngrok](https://ngrok.com/), except that its a Node process deployed to the `now` cloud.  That means I can alias my GitHub webhook endpoint to this instance, and tunnel all incoming connections to my local machine.

It occurred to me, however, that this doesn't need to live as a separate project, and might find utility if integrated into the `now` cli itself.  However, I wanted to reach out and gauge interest before submitting a PR.

Let me know!

Dale

**Comment by albinekb** [comment]
Nice idea! 🎉 

I think having it separate is the better approach, the `now-cli` codebase is already pretty huge, and adding more features like this will only make it harder to maintain and update.

Maybe it could be implemented on the server-side and just a tiny client in the cli, don't know if that's what the team wants :)

my 5c

**Comment by jamo** [comment]
I don't think it's something that should be in now-cli in particular, rather in a separate module, similarly to e.g `meteor-now`.

**Comment by jamo** [comment]
Let's add it to awesome-now whenever it's ready 🚀
