### ISSUE TITLE
minimatch seems to not be used as dependency

### ISSUE THREAD

**Issue by tunnckoCore** [vercel/vercel#66]
Just reviewing the codebase and notice this one https://github.com/zeit/now/search?utf8=%E2%9C%93&q=minimatch If you wanna use some matching try out `micromatch` :P

And btw, awesome service! Excellent job! I :heart: it.

**Comment by johnjacobkenny** [comment]
Does this issue involve just deleting the line from package.json? :)

**Comment by tunnckoCore** [comment]
@kennyjacob yep, i think

**Comment by benjamine** [comment]
#hacktoberfest PR sent :),
btw you can use https://www.npmjs.com/package/npm-check to find unused dependencies.

**Comment by johnjacobkenny** [comment]
@benjamine You could have left this open for a beginner :)
