### ISSUE TITLE
Add NOW_ACTUAL_URL environment variable

### ISSUE THREAD

**Issue by mxstbr** [vercel/vercel#661]
In the documentation it says:

> **Default Env Variables**
> By default, all deployments expose these environent variables:
> - [...]
> - `NOW_URL`: Contains the unique URL of your deployment. **Even if you deployment was aliased, this variable will always contain the URL with the .now.sh suffix.**

I have a use case where I need to allow cookies on subdomains. The way to do that is to set the `Set-Cookie` header to `.domain.com`. If that isn't set, the browser assumes you mean to set it for the current domain.

The default behaviour works great, because that means I don't have to change anything and cookies will work for the `domain-asdfwett123sf.now.sh` URL and `domain.com` when I alias it, meaning I can test my deployment before I alias it.

The issue is that **when `Set-Cookie` isn't set the cookies don't work for subdomains like `bla.domain.com`, and when I set it to `.domain.com` it doesn't work for the `.now.sh` URL.**

In my code I basically want to do something like this:

```JS
cookie: {
  domain: IS_PROD && `.${process.env.NOW_URL}`
}
```

Except I need `process.env.NOW_URL` points to the aliased domain when there is one. Is there any chance you could support something like `process.env.NOW_ACTUAL_URL` or similar to allow me to do this?

**Comment by jamo** [comment]
You can btw get the hostname in `host` header. Using it makes supporting multiple aliases simultaneously way easier. 
(Also, env is usually immutable, so updating  env when aliases are changed will likely break stuff.)

**Comment by mxstbr** [comment]
> You can btw get the hostname in host header.

Maybe I'm missing something here but this isn't in a request/response cycle? I need to define this with the `express-session` middleware when the app boots up:

```JS
app.use(session({
  cookie: {
    domain: '.xyz',
  },
}));
```

How am I supposed to use the `host` header here?

**Comment by mxstbr** [comment]
I guess I create a new instance of `express-session` everytime a request comes in? That seems super wasteful though, there's gotta be a better way to do this!

```JS
app.use((req, ...args) => session({
  cookie: {
    domain: `.${req.header('host')}`,
  },
})(req, ...args));
```

**Comment by jamo** [comment]
Maybe you'd just need to set the value in env when deploying (keep in mind that when deployment is created, it's fully unaware of aliases, in fact you can't even have aliased it yet)

**Comment by mxstbr** [comment]
How'd you mean?

**Comment by sholladay** [comment]
Isn't there another problem here in that a deploy could have multiple aliases? E.g. `foo.now.sh` could be pointed to by `foo.com` and `foo2.com`. At least, I think that is possible, haven't actually tried it. One would have to be considered canonical or they would have to be comma separated.

**Comment by Qix-** [comment]
Sounds like whatever session middleware you're using needs to support the `Host` header.
