### ISSUE TITLE
Showing Invalid Configuration when added costume domain

### ISSUE THREAD

**Issue by theprasant** [vercel/vercel#6685]
### Discussed in https://github.com/vercel/vercel/discussions/6682

<div type='discussions-op-text'>

<sup>Originally posted by **prasantdev** September  6, 2021</sup>
Hello, I tried to add a costume domain. But it's showing `invalid Configuration` 

![error](https://user-images.githubusercontent.com/67827472/132244035-f4bc56c9-e32d-4df1-8243-2cbd9ad273c2.jpg)
</div>

**Comment by leerob** [comment]
Let's continue the conversation in the discussion!
