### ISSUE TITLE
[cli] dev command bug linux +11ty

### ISSUE THREAD

**Issue by cabrero** [vercel/vercel#6697]
Platform: linux
vercel cli version: 23.1.2
SSG: eleventy
Command: vercel dev
Result: Error, no site build, no server started
Expected: Site build and local server started
Output:
```
$ vercel -d dev
... [removed messages]
[debug] [2021-08-02T17:44:51.885Z] Spawning dev command: npx --no-install npx @11ty/eleventy --serve --watch --port 45081
...
npm EEE! canceled
```

The bug is in the dev command: `npx --no-install npx`
The source of the bug is in file `packages/frameworks/src/frameworks.ts`
The offending line: ` devCommand: 'npx @11ty/eleventy --serve --watch --port $PORT',`
It should read:` devCommand: '@11ty/eleventy --serve --watch --port $PORT',`

**Comment by floyedxman** [comment]
I had a similar problem with it and I couldn't find a solution

**Comment by leerob** [comment]
Hey! This issue has gone a bit stale, and we recently updated the 11ty example to 1.0. If you are still seeing this issue, please comment back. Thanks!

**Comment by mmarquez76** [comment]
Hi, I'm still having this exact issue. Here are the logs:

```
> [debug] [2022-02-01T22:30:52.566Z] Spawning dev command: npx --no-install npx @11ty/eleventy --serve --watch --port 53524
npm ERR! canceled

npm ERR! A complete log of this run can be found in:
npm ERR!     <log location>
> [debug] [2022-02-01T22:31:22.538Z] No builders were updated
```

For anyone else finding this: my solution was to go to the build & development settings online and set my development command to `@11ty/eleventy --serve --watch --port $PORT` instead of `npx @11ty/eleventy --serve --watch --port $PORT`
