### ISSUE TITLE
now rm --safe NOT safe

### ISSUE THREAD

**Issue by Sequoia** [vercel/vercel#670]
## My deployments

```
$ now ls auth
> 4 deployments found under sequoia [627ms]

auth (4 of 4 total)
 url                            inst #    state                 age
 auth-pqcfahnogz.now.sh              0    FROZEN                16h
 auth-zpkbhhzpek.now.sh              0    FROZEN                16h
 auth-smoydbqsge.now.sh              0    BUILD_ERROR           16h
 auth-yfegqjnzgp.now.sh              0    FROZEN                18h
```

## My alias

ℹ️  *note that it **does not find my alias** for `sequoia-auth` even though it exists*

```
$ now alias ls sequoia-auth.now.sh
> Error! Could not match path alias for: sequoia-auth.now.sh

$ now alias ls | grep auth
  https://auth-pqcfahnogz.now.sh    https://sequoia-auth.now.sh       16h
```

## "Safe"

```
$ now rm --safe auth
> The following deployments will be removed permanently:
oawB4gTt1vDJsSjM9UG46Fpy      https://auth-pqcfahnogz.now.sh      16h ago
ChwCH7yGqOrrgTye7f1Rhqfb      https://auth-zpkbhhzpek.now.sh      16h ago
oNwEQVcROlgg1FewwIatbovR      https://auth-smoydbqsge.now.sh      16h ago
gXD9mwabvP97A6UwP9tgmLcP      https://auth-yfegqjnzgp.now.sh      18h ago
> Are you sure? [y/N] N

> Aborted
```

# Expected

**Does not** remove my aliased deploy (`https://auth-pqcfahnogz.now.sh`)

# Actual

**Does** remove my aliased deploy. This is pretty scary for a switch labeled `--safe`!! 😱

**Comment by leo** [comment]
@Ignigena Any ideas?

**Comment by Ignigena** [comment]
I was digging into this last week. From what I was seeing it actually won’t remove the aliased deployment. The issue is that it still prints it in the list of aliases that would be removed.

I was able to fix the issue by moving the logic up one function in the stack, just didn’t have time to clean up and submit a PR.

**Comment by leo** [comment]
@Ignigena Would be wonderful if you could do that, if you have time! 😊

**Comment by sholladay** [comment]
I just hit this too. It definitely does remove all deployments, regardless of alias. Or at least `now ls` is unable to show them afterwards.

**Comment by Ignigena** [comment]
@leo PR #672 should address this issue!

**Comment by leo** [comment]
https://github.com/zeit/now-cli/pull/672
