### ISSUE TITLE
Add "requiredFiles" key to now.json

### ISSUE THREAD

**Issue by Qix-** [vercel/vercel#674]
Right now, the `"files"` key in _now.json_ allows listing files that may not exist at the time of deployment, and the absence of those files seem to be quietly ignored.

In certain cases, some files (e.g. configuration files) _must_ be present for the deployment to function properly, and not having them may be a waste of time for someone moving quickly.

It'd be nice to have either a `"requiredFiles"` key (where all files listed must be present), or alternatively (and similarly to how _package.json_ works) make all files in `"files"` required and add an `"optionalFiles"` key.

Use case: I have a repository that is meant to be cloned and then immediately deployed, but requires that _config.json.example_ be copied to _config.json_ first and manually configured prior to running `now`. It'd be nice if it failed fast if _config.json_ didn't exist (i.e. the user forgot the configuration step).

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
