### ISSUE TITLE
A `--team` flag is needed

### ISSUE THREAD

**Issue by leo** [vercel/vercel#676]
As discussed with @matheuss and @jamo

**Comment by levino** [comment]
I support this feature request. When will it be finished? Makes now.sh kinda unusable in any corporate setup...

**Comment by timneutkens** [comment]
This was already added 👌 `now --token=<token> --team=<team>`

**Comment by levino** [comment]
Where is the doc for this?

**Comment by timneutkens** [comment]
`now --help`, @sergiodxa maybe we should add it to zeit.co/docs too 🙌

**Comment by levino** [comment]
That is my point.

**Comment by leo** [comment]
We don't keep options in the docs. They get updated pretty frequently and `now --help` would hold the exact same information. 😊
