### ISSUE TITLE
Improve `alias` UX

### ISSUE THREAD

**Issue by flybayer** [vercel/vercel#68]
I know there's been some discussion in zeit.chat about this, but I thought it'd be good to open a issue for further discussion.

I'm not sure of the best solution to improve the aliases experience, but here's some ideas for consideration:
## Ability to alias multiple domains at once

I'd like to do this:

```
now alias <ID> domain.com www.domain.com
```

instead of this:

```
now alias <ID> domain.com 
now alias <ID> www.domain.com
```
## Ability to define domain aliases in package.json or some other file

I'd like to do this:

```
now alias
```

and have the latest deployment automatically aliased to one or more configured domains

Alternatively, it could be:

```
now alias <ID>
```

which would be easy to do since the deployment url is automatically copied to the clipboard.

I know [now-realias](https://github.com/remy/now-realias) does something like this, but I think this should be apart of the official client :)

**Comment by remy** [comment]
I'm making progress on this at the moment.

My focus is making `now alias` work by reading the `package.json`'s `config.alias` property, and linking it to the last deployment for the `name`.

**Comment by slorber** [comment]
+1 for linking to last deployment

Would be nice to be able to define "domain aliases" and do "now alias latest dev,staging,prod"

**Comment by lukemorton** [comment]
Seeing as we now support `now --alias a.com --alias b.com`, what should supporting multiple domains for `now alias` look like?

```
now alias <ID> domain.com www.domain.com
```

This makes their APIs a little inconsistent. Does this matter?

**Comment by slorber** [comment]
Hey, would it be possible to allow using a custom domain alias as source?


`now alias set staging.domain.com prod.domain.com`

It shouldn't be very hard, just requiring to resolve the domain alias to its deploymentId upfront, and it would be very useful for me :)

**Comment by TooTallNate** [comment]
Closing this because `now alias` and `now alias <id>` have worked for a long time. But more importantly, I think that [Automatic Aliasing](https://zeit.co/blog/automatic-aliasing) supersedes this feature request since `now alias` (with no arguments) is more or less deprecated.
