### ISSUE TITLE
Documented "files" configuration option behaves differently for static deploys 

### ISSUE THREAD

**Issue by jimpick** [vercel/vercel#684]
The documentation for now.json states:

`files` (array)
A list of files and directories to be force-uploaded to the deployment (even if they're ignored by .gitignore).

I was trying to get a bower_components directory (from a Polymer app) to deploy on a static site. I had recently added bower_components to the .gitignore. I tried using the `files` config option, but it didn't appear to force-upload.

I cloned now-cli and debugged the problem ... it appears the `files` option is used as a whitelist for static deploys, and as an override list for npm deploys.

I'm not sure if the documentation needs updating, or the behaviour for static deploys is incorrect.

Here's the documentation page:

https://zeit.co/docs/features/configuration

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
