### ISSUE TITLE
Any plan on releasing to homebrew?

### ISSUE THREAD

**Issue by amio** [vercel/vercel#688]
Github user content are blocked in china, homebrew would be a handy alternative. Is there any plan on this?

**Comment by rauchg** [comment]
I would love to. The reason we `pkg` the npm package is to enable multiple distribution channels, and `brew` is one of my favorites. Would you be up for maintaining the package?

**Comment by jamo** [comment]
We have now-desktop, that then installs now, in brew: https://github.com/caskroom/homebrew-cask/blob/master/Casks/now.rb tho I guess it won't really help...

**Comment by rauchg** [comment]
@jamo is right. To clarify:

```
brew cask install now
```

is *available today*. It will install the Desktop and CLI, and keep it up to date.

If you're only interested in the CLI, I would like to also have `brew install now` :)

**Comment by leo** [comment]
I'd love to see this come to life!

**Comment by amio** [comment]
> Would you be up for maintaining the package?

Would love to 😃

**Comment by amio** [comment]
Seems brew & cask package share namespace (["Formula name conflicts with caskroom/cask/now"](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/3420/version=yosemite/testReport/junit/brew-test-bot/yosemite/audit_now___online___new_formula/)), I submit it as `now-cli`: Homebrew/homebrew-core#14827

**Comment by leo** [comment]
Looks like this isn't possible with the current setup. Closing...
