### ISSUE TITLE
Remove old aliased deployments after replacing them

### ISSUE THREAD

**Issue by sholladay** [vercel/vercel#691]
## Goal

In CI, when I [deploy my app to staging](https://gist.github.com/sholladay/bd0d9ffeebee6dd8207766be18886503#file-deploy-staging-sh) and then alias it, I'd like to remove the deployment that is being replaced (the one that was previously at that alias). The old deployment will forever go unused from that point forward and it takes up space in the `now ls` output, adding noise and confusion to what our deployments actually represent.

## Details

The command `now remove my-app --yes --safe` comes close to what I want, except that it potentially removes deployments that weren't done in CI (e.g. experiments by my team), so it's a bit too aggressive. Additionally, it errors out if there _aren't_ any old deployments (i.e. it fails the first time), which I don't want in the case of an alias that otherwise succeeds.

As a workaround, I had an idea to run `OLD_URL=$(now ls my-alias)` as a first step before deploying, so that I know what to remove later on.

Trying that, `OLD_URL` currently becomes:

> \> 1 deployment found under my-app [1s] my-app (1 of 1 total) url inst # state age my-app-abcdefghij.now.sh 1 READY 20h

So the info I need (`my-app-abcdefghij.now.sh`) is in there, but I would have to parse it, which I'm not keen on.

My ideal solution would simply be an opt-in flag to use when aliasing, since this is a common case.

```sh
now alias set staging.my-app.com --remove-old
```

**Comment by rtsao** [comment]
I've created a PR for this: https://github.com/zeit/now-cli/pull/921

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), there's no reason for keeping around old deployments. In turn, I'm closing the issue.
