### ISSUE TITLE
Unable to remove a team

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#693]
I'm unable to remove a team from my account using `now teams rm <name>`.

```
> Error! Please specify a valid subcommand: ls | add | rm | set-default
```

**Comment by hawkins** [comment]
I've also been experiencing this for some time now. If you look at https://github.com/zeit/now-cli/blob/master/bin/now-teams.js#L128, you can see that there is not even a case (nor file) to handle `rm` or `remove` subcommands. 

Tried searching git history for a `bin/teams/remove.js` or `rm.js` etc - looks like it has never existed? 😕 Or I'm guessing at the wrong file names.

**Comment by levithomason** [comment]
@OlliV do you know the status of this?  Unable to `now teams rm` with version `7.3.0`.

**Comment by OlliV** [comment]
It's currently WIP.

**Comment by levithomason** [comment]
Great, I'll watch this issue for updates.  Thanks much.

**Comment by sergiolenza** [comment]
Hi guys. How is this going? Anyone knows?

**Comment by leo** [comment]
This functionality is not yet supported, but coming 🔜!

**Comment by agustif** [comment]
Great, because I accidentally created an innecessary and duplicated name team, I have one in minus and one Capitalized, which sucks. 

Thanks for fixing this soon @leo

**Comment by theoutlander** [comment]
Someone created 4 teams and it is hell to figure out WTF is going on. Where is this feature?

**Comment by silvio-e** [comment]
Yes, please let us remove teams!!

**Comment by harrisrobin** [comment]
Yeah also wondering here, i have a few stale teams id like to get rid of

**Comment by OlliV** [comment]
This is now possible from the dashboard.
