### ISSUE TITLE
Ability to set scale max/min in now.json

### ISSUE THREAD

**Issue by Darkle** [vercel/vercel#695]
It'd be great if you could set the scale maximum & minimum in the now.json config file so that it's applied automatically whenever you deploy.

**Comment by revolunet** [comment]
also, `scale: 1` would be great :)

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
