### ISSUE TITLE
Can we get a domain availability checker?

### ISSUE THREAD

**Issue by nkallman** [vercel/vercel#696]
Pretty simple, just a basic option to only check domain availability without buying option. Something like:

`now domains check example.com`

Which will give the same initial response as `now domains buy example.com` currently does:
\> The domain "example.com" is _available_ to buy under **yourname**!

Without the follow-up prompt of
\> Buy now for $15 (1yr)? [y|N]

**Comment by sergiodxa** [comment]
You can now check the domain availability under https://zeit.co/domains.

You can also use our API https://zeit.co/api#endpoints/domains/check-a-domain-availability

**Comment by leo** [comment]
Closing as per the comment above.
