### ISSUE TITLE
Error loading shared library ld-linux-aarch64.so

### ISSUE THREAD

**Issue by danenania** [vercel/vercel#697]
Hey all,

I'm working on an npm package that uses node-ffi to load a binary .so file. This works fine on Heroku and in a Docker container built from the `node:boron` image, but loading the lib fails on a now.sh deployment (using package.json) with the following error:

```
Dynamic Linking Error: Error loading shared library ld-linux-aarch64.so.1: No such file or directory (needed by /home/nowuser/src/node_modules/envkey/ext/envkey-linux-arm64.so)
``` 

The problem seems similar to [this issue](https://github.com/zeit/now-cli/issues/274), but with a different missing dependency. Any ideas? Thanks!

**Comment by TooTallNate** [comment]
Not sure where your `.so` file comes from, but apparently its linked to an ARMv8 ld library. It seems that the SO files is improperly compiled for x64-bit linux operating systems.

**Comment by danenania** [comment]
@TooTallNate Thanks for the reply. To add some context, I'm using a try/catch to attempt to load two different `.so` files on 64-bit linux platforms: first attempt is a `linux-amd64.so`, and then if that fails I attempt to load a `linux-arm64.so` file. 

The `linux-amd64.so` file fails with the following error:

```
 Dynamic Linking Error: Error relocating /home/nowuser/src/node_modules/envkey/ext/envkey-linux-amd64.so: __vfprintf_chk: symbol not found
```

The `linux-arm64.so` file fails with the `ld-linux-aarch64` error I posted.

Perhaps the first failing `.so` is the more relevant one? Does that error message bring anything to mind?

These `.so` files are in an `ext` directory inside my package. I'm constructing the path like this:
```
path.join(__dirname, "ext", filename)
```

**Comment by TooTallNate** [comment]
Indeed the first failing error is more relevant in this case. We use Alpine Linux for Now deployments which includes a libc compatibility layer, but it seems that `__vfprintf_chk` is not included in that.

If you have control over the native code and can figure out where that is used and remove it then that might work. Or statically compiling glibc to the SO file might work as well.

In general running binaries between Alpine (which uses MUSL) and more "common" distros (that use glibc) like Debian/Ubunutu gets pretty tricky fast.

**Comment by TooTallNate** [comment]
Another possibility is to use a [Dockerfile](https://zeit.co/docs/deployment-types/docker) using a glibc based distro as the base image for your application. That way, you would be more in control over which libc is used.
