### ISSUE TITLE
'Now cc add' doesn't work with < 16 digit credit card numbers (AMEX, some Visa, Diner's Club, etc)

### ISSUE THREAD

**Issue by ScottDavidSanders** [vercel/vercel#698]
When using https://zeit.co/account/billing American Express works at least, so it's not an issue with Stripe, and the credit-card module seems to be verifying AMEX numbers properly as well.

**Comment by Qix-** [comment]
Indeed. Just ran a number of test CC's.

<img width="201" alt="screen shot 2017-06-27 at 11 54 15 pm" src="https://user-images.githubusercontent.com/885648/27624084-14e85a84-5b94-11e7-89dc-6856e4ceaf7a.png">
<img width="218" alt="screen shot 2017-06-27 at 11 55 13 pm" src="https://user-images.githubusercontent.com/885648/27624088-1744cc72-5b94-11e7-9fb6-c32779f4af23.png">

_./cards_
```
American Express|378282246310005
American Express|371449635398431
American Express Corporate|378734493671000
Australian BankCard|5610591081018250
Diners Club|30569309025904
Diners Club|38520000023237
Discover|6011111111111117
Discover|6011000990139424
JCB|3530111333300000
JCB|3566002020360505
MasterCard|5555555555554444
MasterCard|5105105105105100
Visa|4111111111111111
Visa|4012888888881881
Visa|4222222222222
Dankort (PBS)|76009244561
Dankort (PBS)|5019717010103742
Switch/Solo (Paymentech)|6331101999990016
```

_./test-all.sh_
```shell
#!/usr/bin/env bash

set -e

while IFS='' read -r line || [[ -n "$line" ]]; do
	issuer="$(cut -d'|' -f1 <<< "$line")"
	number="$(cut -d'|' -f2 <<< "$line")"
	echo -e "\n\x1b[1;36mCard Issuer:\x1b[22;92m ${issuer}\x1b[m"
	echo -e "\x1b[1;36mCard Number:\x1b[22;93m ${number}\x1b[m"
expect <<EOF
	set send_slow {1 .01}
	set timeout 2
	
	spawn now cc add
	expect "nope"
	send -s -- "John Doe\r"
	expect "nope"
	send -s -- "${number}"
	expect "nope"
	send -s -- "\r"
	expect "nope"
EOF
done < ./cards
```

**Comment by leo** [comment]
Should not be happening!

**Comment by unitof** [comment]
Definitely still happening. Just tried with a (known legit) 15-digit Amex card and get the red `✖ Number`: 
<img width="113" alt="image" src="https://user-images.githubusercontent.com/2448782/70756646-1c9b3180-1d0b-11ea-88e3-984fd6949ccf.png">

Adding online at https://zeit.co/teams/[slug]/settings/billing works.

**Comment by TooTallNate** [comment]
The `vercel billing`/`vercel cc` command was removed in #8377, so closing this issue.
