### ISSUE TITLE
Progress bar improvements

### ISSUE THREAD

**Issue by rauchg** [vercel/vercel#7]
- [ ] Make sure progress bar renders at the beginning. When uploading a single large file it's not showing!
- [ ] Make sure progress bar tracks total size, not total files, and that each progress event updates it
- [ ] Make sure we debounce it to avoid a performance degradation from frequent repainting

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
