### ISSUE TITLE
how to clear the log console

### ISSUE THREAD

**Issue by andrealeone** [vercel/vercel#707]
Is there a command to clear the log console directly from the CLI (or from the online dashboard), in order to lighten the weight for my OSS project?

**Comment by vuchl** [comment]
CTRL + L

**Comment by OlliV** [comment]
Currently there is no way. @igorklopov does this sound like something we should support?

**Comment by brunolemos** [comment]
I logged some tokens by mistake so yeah, it would be great to be able to clean it. 
I'll try to revoke them now.

EDIT: I removed the deploy, seems to solve my case.
