### ISSUE TITLE
Can not install  now-cli on ubuntu

### ISSUE THREAD

**Issue by liadbiz** [vercel/vercel#710]
I am using ubuntu 16.04.
I run `sudo npm i -g now`, but got the following output:

```bash
/opt/node-v6.9.2-linux-x64/bin/now -> /opt/node-v6.9.2-linux-x64/lib/node_modules/now/download/dist/now

> now@7.2.0 postinstall /opt/node-v6.9.2-linux-x64/lib/node_modules/now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading now CLI 7.2.0 [                    ] 0%

```
My network has no problem, but progress stays in 0% and never changed.

**Comment by leo** [comment]
@liadbiz Is it working now? We're downloading the binaries from the GitHub API and it's sometimes pretty slow. We might consider caching in the future!

**Comment by liadbiz** [comment]
I am downloading it again, it's really slow.....

**Comment by liadbiz** [comment]
@leo Is there another way to download? it's pretty pretty slow......

**Comment by leo** [comment]
It might depend on your location. But you can also download it from [here](https://github.com/zeit/now-cli/releases).

**Comment by liadbiz** [comment]
It's faster now :+1: Thanks!
