### ISSUE TITLE
[Config] Ignore files

### ISSUE THREAD

**Issue by rileybracken** [vercel/vercel#711]
Is there any plans for Now to be able to ignore files uploaded? I know it allows to force upload `.gitignore` files, but the opposite would be rad.

Use case would be if a project has a React Storybook associated with it, but you don't want the storybook and all the assets associated with it on your `now` instance.

**Comment by nkzawa** [comment]
You can use `.npmignore` as the filter config as well, which might be suitable in your case.
Additionally, you can specify whitelist files to upload on you `package.json` or `now.json`, using the `file` field or `now.files` field.

https://zeit.co/docs/features/now-cli#selecting-files-and-directories-to-be-uploaded

```
{
  files: [...]
}
```
