### ISSUE TITLE
Deployed app stuck in BUILDING state

### ISSUE THREAD

**Issue by BenDiuguid** [vercel/vercel#716]
<img width="667" alt="screen shot 2017-07-11 at 3 06 42 pm" src="https://user-images.githubusercontent.com/7402211/28093334-b007bc64-664b-11e7-8386-8d9c37c1bab3.png">

The source code is [here](https://github.com/BenDiuguid/hobbit-intuition) I was trying to deploy a simple twitter-bot and ran `yarn deploy` for the first 2 tries, then `npm run deploy` for the 3rd attempt.

It seems like `now` is running `npm start` (which is just `node index.js`) as part of the BUILDING phase?

Also here is the `npm run deploy` command: `now --public -e CONSUMER_KEY=@hi-twit-key -e CONSUMER_SECRET=@hi-twit-secret -e ACCESS_TOKEN=@hi-twit-access  -e ACCESS_TOKEN_SECRET=@hi-twit-access-secret`

Let me know if you need any more information or if there is a better repo for this issue?

 `now` is an incredible product so thanks so much!! 😄

**Comment by OlliV** [comment]
It seems to me that your deployment isn't listening on any port.

**Comment by matheuss** [comment]
@BenDiuguid for now we're focused on deployments that expose an HTTP port, so you could just fire up an HTTP server like:

```
const {createServer} = require('http')

const server = createServer(() => {})

server.listen(3000)
```

And then you should be good!

However, it shouldn't be stuck on `BUILDING` – it should timeout after a little while. We'll investigate why it's acting like that – thanks for reporting!

**Comment by LatentM** [comment]
> @BenDiuguid for now we're focused on deployments that expose an HTTP port, so you could just fire up an HTTP server like:
> 
> ```
> const {createServer} = require('http')
> 
> const server = createServer(() => {})
> 
> server.listen(3000)
> ```
> 
> And then you should be good!
> 
> However, it shouldn't be stuck on `BUILDING` – it should timeout after a little while. We'll investigate why it's acting like that – thanks for reporting!

I am also facing this issue right now. It's stuck on BUILDING
