### ISSUE TITLE
now scale should allow you to specify a project

### ISSUE THREAD

**Issue by anaisbetts** [vercel/vercel#718]
now scale requires you to specify a full URL, but for deployment tooling, it'd be super convenient to be able to list a project instead (i.e. `mycoolapp` without `mycoolapp-xuekwpcief.sh`) and have the latest version of that project be scaled up and the others scaled down.

**Comment by sergiodxa** [comment]
You can scale an alias and if you change the aliased deployment it will scale down the old one and scale your new deployment as you configured.

**Comment by leo** [comment]
As of [Now 2.0](https://zeit.co/blog/now-2), there is no more scaling for v2 projects (still available for v1 though). In turn, I'm closing this.

**Comment by madiodio** [comment]
Hi Leo, is scaling still working in v1. Trying right now to scale up a project is hanging for me (fwiw do not know what scaled it down but scaling just hangs)

![screen shot 2018-11-13 at 16 09 59](https://user-images.githubusercontent.com/15022248/48426427-abcbc380-e75e-11e8-84a1-664ef12d5934.png)
