### ISSUE TITLE
Dockerfile LABEL name double quotes not ignored

### ISSUE THREAD

**Issue by pqvst** [vercel/vercel#719]
I have a bunch of old deployments that have this in the Dockerfile:

    LABEL name="foobar"

This used to work fine, the double quotes were removed. Now it seems that the double quotes are treated as part of the name.

Is this by design, or a bug?

**Comment by Qix-** [comment]
Well, it's both. :)

The upstream dependency claims it's as expected. However I disagree with the reasoning.

I'll take another look at the status of joyent/node-docker-file-parser#3, which would fix this issue.

**Comment by pqvst** [comment]
What's changed? Have you guys switched to a different parsing library? Because quotes were stripped before, and now they aren't 🤔

Also, I *think* the reason I included quotes in the first place was because it didn't work without them, earlier...

Edit: Perhaps this commit is the cause: https://github.com/joyent/node-docker-file-parser/commit/26b07de63c864be870e9d8f9f13f64c3bd10f0e7

**Comment by jamo** [comment]
At some point we parsed the label as JSON which probably removed the quotes, but then failed miserably on all other cases. 

@Qix- maybe we could just drop all "non valid characers" `[^a-zA-Z0-9]` from the parser output.

**Comment by pqvst** [comment]
Whether or not the docker file parser is at fault, I feel like it makes sense to strip non-alphanumeric characters from the deployment name. When quotes got in there it was a bit tricky to use the cli (for example: now ls "foobar" vs now ls foobar). Plus, it broke the previous behavior...
