### ISSUE TITLE
Create React App

### ISSUE THREAD

**Issue by 0xsven** [vercel/vercel#72]
I am not sure if this should be possible at all but I will leave it here anyways:

After deploying an app that was created with [create rect app](https://facebook.github.io/react/blog/2016/07/22/create-apps-with-no-configuration.html) I am getting this warning:
`> (node:310) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Exited with code 3`
And in the browser:

```
Failed to compile.

Error in ./src/index.js
Module build failed: Error: EACCES: permission denied, mkdir '/home/nowuser/src/node_modules/.cache'
    at Error (native)
 @ multi main
```

**Comment by OlliV** [comment]
Try this: https://github.com/xkawi/create-react-app-now

**Comment by nonnontrivial** [comment]
I was getting a similar error, @0xsven . What ended up working was running the build script in `create-react-app` and subsequently using [now serve](https://github.com/zeit/now-serve) to `ns build`.

**Comment by 0xsven** [comment]
@kevmannn 
I might be doing it wrong but `ns build .` or `ns build` are telling me: Specified path doesn't exist!

**Comment by codyzu** [comment]
Hello @0xsven. Do you have this resolved?

Here is a step-by-step for using **create-react-app** with **now-serve**. The steps assume that you have already installed **now-serve** and **create-react-app**.
1. create your react app: `create-react-app hello-world`
2. go into the created react app: `cd hello-world`
3. build your react app for production: `npm run build`
4. deploy with now serve, ignoring any warnings (see note below): `ns build`

I tested these exact steps and they worked for me. Looking at your posts, maybe you left out step 2 or 3.

Let us know if this resolves your issue so we can either close it or get your system working.

_Note: One of the files created by the create-react-app will be larger than 1MB and will not be included in the now deployment unless you have a pay plan. The good news is that this file is a `.js.map` file and will not be required for your site to function._

**Comment by 0xsven** [comment]
@codyzu 
This worked! Thank you. 
now and react. Such a powerful combination.

**Comment by codyzu** [comment]
@0xsven great! Glad to read you got this worked out and I agree... now is real game changer!

Happy deployments!!!

**Comment by stephenhowells** [comment]
According to Zeit, now-serve has been deprecated: [https://zeit.co/blog/now-static](https://zeit.co/blog/now-static)

**Comment by dangnelson** [comment]
With now-serve being deprecated, I'm trying to use the `now` command and getting the cache error noted above.

**Comment by jamo** [comment]
The error sounds like it's starting the dev server after deployed...

**Comment by dunnock** [comment]
Following helped me, actually should work for any SPA. Add serve module to package.json dev dependencies and custom "now-start" script:
```
#yarn add --dev serve

//package.json - replace ./build with your bundle root:
...
"scripts" {
    "now-start": "serve ./build --single"
    ...
```

**Comment by fredrik-sogaard** [comment]
I'm deploying the build folder like suggested above, but how do you handle a catch all route to load index.html on every route with `create-react-app` and Now?

**Comment by stephenhowells** [comment]
This comment seems like the best way to deploy CRA to Now: https://github.com/zeit/now-cli/issues/160#issuecomment-276235888

It essentially mimics what `now-serve` did.
