### ISSUE TITLE
yarn hangs when now is installed as a dev dependency

### ISSUE THREAD

**Issue by ryardley** [vercel/vercel#722]
When a project depends on `now` as a dev dependency every time any new dependency is added. yarn hangs for minutes on `now`'s behalf (presumably because the `now` package is building/compiling/downloading something?).

## package.json

```json
{
  "devDependencies": {
    "now": "~7.2.4"
  },
  "scripts": {
    "start": "node index.js",
    "deploy": "now --dotenv=.env.production"
  },
  "name": "someproject",
  "version": "1.0.0",
  "main": "index.js",
  "author": "Some author",
  "license": "MIT"
}

```

## Example output when hanging occurs
```bash
$ yarn add dotenv
yarn add v0.25.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
[1/1] ⠁ now: > For the source code, check out: https://github.com/zeit/now-cli
[-/1] ⠁ waiting...
[-/1] ⠁ waiting...
[-/1] ⠁ waiting...
[-/1] ⠁ waiting...
```

As soon as now is no longer a development dependency of the project yarn works as normal. 

## Expectation
Yarn should install packages like `dotenv` quickly. One `now` has installed it should not install again.

**Comment by leo** [comment]
This doesn't seem to be happening anymore.
