### ISSUE TITLE
staging & live alias in package.json?

### ISSUE THREAD

**Issue by Obiwarn** [vercel/vercel#723]
Right now i use two npm scripts with ```now --alias``` to deploy to staging and prod.

But I get an deprecation error, telling me to use the "alias" in package.json.

But how could I keep the distiction fro my different deployments?

**Comment by southpolesteve** [comment]
I am also curious what the official supported way of doing this is. I had added functionality that made this easy in https://github.com/zeit/now-cli/issues/361 and then it looks like it was removed?

**Comment by ankeetmaini** [comment]
Yes, I want to keep different deployments mapped to different alias, like one alias for stage and one for qa, and so on.

Currently all my alias in package.json are updated with the latest deployment. Workarounds?

**Comment by leo** [comment]
Sounds like an interesting idea!

**Comment by leo** [comment]
The workaround is to set a separate staging config using `--local-config`, which we'll prefer for now.
