### ISSUE TITLE
Can't remove a deployment by ID, name, etc

### ISSUE THREAD

**Issue by babakness** [vercel/vercel#724]
Hi, I have a domain that starts with "-". This was an error from a few months ago. Its name is like this 

-fhcisoga.now.sh 

but that's not the name, just showing how it is listed.

Anyway, I can't seem to be able to delete it using `now rm`. Please advise

I've tried removing with the full name, with just the id, etc. nothing works.

`now rm -fhcisoga.now.sh `
`now rm \-fhcisoga.now.sh`
`now rm "-fhcisoga.now.sh"`
`now rm "\-fhcisoga.now.sh"`
`now rm fhcisoga`

None of these variations work.

**Comment by matheuss** [comment]
@babakness asked you on zeit.chat, but for the record: what's the email address associated with your account so I can take a look?

**Comment by leo** [comment]
Closed because of a missing response.
