### ISSUE TITLE
HTML5 history API support

### ISSUE THREAD

**Issue by codeofsumit** [vercel/vercel#726]
hey there,

awesome, awesome tools and service! I'm switching projects and teams to zeitHQ right now but I noticed something weird.

Go to any deeper path in a single page app, refresh the browser and you'll get a 404. I get a 404 whenever I try to access a path other than the root, when using client side routing via history API.

Can you push me into the right direction how to fix this? While it would work, I'd rather not use the hashbang hack `https://myapp.io//#/path`.

**Comment by sergiodxa** [comment]
Static deployments don't support SPAs at the moment, you need to run your own custom server using either a NPM or Docker deployment (I recommend you [zeit/serve](https://github.com/zeit/serve) with the `--single` flag).

**Comment by codeofsumit** [comment]
Hm, ok thanks!
Is SPA support in the pipeline? It'd introduce quite some changes to SPA builds if they now need to come with a server and we have to deploy a node app, not a website - which destroys a little bit of the simplicity of `now`.

**Comment by codeofsumit** [comment]
ah nevermind. A simple package.json inside my `dist` folder works already 🎉 

```json
{
  "name": "myApp",
  "scripts": {
    "start": "serve --single"
  },
  "dependencies": {
    "serve": "latest"
  }
}
```

thanks!

**Comment by chrise86** [comment]
@codeofsumit this doesn't seem to work for me - how are you building / deploying?

**Comment by sergiodxa** [comment]
@chrise86 check https://zeit.co/docs/examples/create-react-app, it explain how to deploy a single page application.

**Comment by zhaoyao91** [comment]
with now 2.0, how to do this?

**Comment by alexnaidovich** [comment]
Any updates on this?
Need to know how to serve non-root routes in vue app with `history` mode routing. Because now I'm getting 404.

**Comment by nessup** [comment]
@alexnaidovich, agreed, this is broken in 2.0
