### ISSUE TITLE
Callback when build is done

### ISSUE THREAD

**Issue by kirillgroshkov** [vercel/vercel#728]
I have a problem. 

I'm trying to do the Continuous integration from our master branch to the specified URL (say abc.zeit.sh).

I need an alias (abc.zeit.sh) to be always up and working (100% uptime).

Now I have a bash script in my CI that does:

- now
- now alias

The problem is that these 2 commands exit quickly, alias is created to a deployment that currently shows html page with build progress, until the build process is done.

Expected behavior: alias is service the previous deployment until the new deployment is fully built, and then switches to new deployment.

It would be possible to solve if e.g `now` has a flag `--waitForBuildToFinish`, so CLI command doesn't exit until build has finished. Next CLI command will do `now alias` and everything will be smooth.

So now I don't know how to automate the EXACT MOMENT when I need to do `now alias`.

**Comment by piscis** [comment]
Same here I'm building a docker image with in a gitlab runner the deployment command exits within a couple of seconds and the build is always successful the exit code is 0.

My gitlab CI looks like this:
 
    - now --docker --token XXX --no-clipboard -d
    - echo $?

and this is the output:

      $ now --docker --token XXX --no-clipboard -d

       > [debug] Forcing `deploymentType` = `docker`
       > [debug] Detected `deploymentName` = "YYYY-stage"
       > [debug] ignoring "/builds/lala/foobar/site/web/app/themes/sage/.gitignore"
       > [debug] locating files /builds/lala/foobar: 83.765ms
       > [debug] Getting files: 90.248ms
       > [debug] Computing hashes: 114.923ms
       > [debug] /now/create: 3255.064ms
       https://yyyy-stage-lqgxhjdonr.now.sh> [debug] closing agent
     $ echo $?
       0
       Creating cache apt-cache...
       Created cache
       Job succeeded

on a terminal the command works and keeps running until the docker container is build and started. If I do `now` followed by `now alias` within gitlab CI the deployment is started and the alias will immediate point to the new instance that is currently building taking the current running container offline.

**Comment by kirillgroshkov** [comment]
Now I see that it's finally fixed in https://github.com/zeit/now-cli/pull/743
