### ISSUE TITLE
'files' doesn't work in config file with '-c' option

### ISSUE THREAD

**Issue by kdby-io** [vercel/vercel#731]
I use two now config files, `now.staging.json` and `now.json`, to make different alias url.

They look like...
```js
{
    "name": "name",
    "alias": "some.url",
    "type": "npm",
    "public": false,
    "engines": {
        "node": "8.1.2"
    },
    "files": [
        "dist",
        "package.json",
        "yarn.lock"
    ]
}
```

When I try to `now`, it works.
When I try to `now -c now.json`, it throw `no directory 'dist'`. 

Of course, `dist` is in `.gitignore`

**Comment by leo** [comment]
The `-c` flag is meant to be used for the global configuration file (the one that contains your token). It's located in your home directory and called `.now.json`.

https://github.com/zeit/now-cli/issues/436
