### ISSUE TITLE
NPM error executing serve -s build

### ISSUE THREAD

**Issue by bsides** [vercel/vercel#733]
Hi guys,

I'm trying to deploy a create-react-app with react routes in `now`. I added in my package.json `serve` as a dependency and a custom start (now-start) with `serve -s build`. But it fails on deploy, what appears to be an error with Chalk, and looks like theres no much I can try now. Could you take a look?

node --version
v8.2.1
npm --version
5.3.0
now --version
7.3.0

package.json (where it matters):
```
  "dependencies": {
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-router-dom": "^4.1.2",
    "react-scripts": "1.0.10",
    "serve": "^6.0.6"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "now-start": "serve -s build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "predeploy": "npm run build"
  }
```

The error after running now: https://puu.sh/x96JE/6772acf19a.png
now url: https://horizoverlay-culxvkwtif.now.sh

**Comment by Qix-** [comment]
Can you delete `package-lock.json` and `node_modules/` and re-install your dependencies?

**Comment by bsides** [comment]
Sure, I'll get back to you with it in some minutes

**Comment by bsides** [comment]
Here's the output locally:
https://puu.sh/x9auh/372adbe82f.png

And serve runs fine:
https://puu.sh/x9awD/c543443ad1.png

I'm running them all in Windows 10 by the way. Hope it helps.

**Comment by Qix-** [comment]
Are you still seeing the error?

**Comment by bsides** [comment]
Forget about that `now ls` output from above. Thats a dev deploy. A dev deploy works because it doesn't use `now-start`, it uses `react-scripts start` which isn't serve and isn't optimized. But as you can see, locally `serve` works fine.

It still doesn't work with `now-start: serve build -s`

Here's the output right after the above, same error with chalk in serve:
https://puu.sh/x9bHo/e5353d14e7.png

Edit: the deploy id is horizoverlay-kuefoazbxa.now.sh

**Comment by bsides** [comment]
Anything new here?

_Sent from my Samsung SM-A510M using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by leo** [comment]
If this still occurs, it's an error in [serve](https://github.com/zeit/serve/issues).
