### ISSUE TITLE
Broken deployment on React Universally

### ISSUE THREAD

**Issue by mb8z** [vercel/vercel#736]
`React Universally` being one of the best boilerplates for React, supports the now deployment.
afaik the feature to deploy it with `now` has been working great as it is included in the main documentation, but now all I (and several other users that I know) get is an error saying:

```
MacBook-Pro-3:react-redux-apollo NYC$ yarn run deploy
yarn run v0.27.5
$ babel-node internal/scripts/deploy
> Deploying ~/Desktop/react-redux-apollo under company_name
> Using Node.js 8.2.1 (requested: `>=6`)
> Ready! https://react-universally-hfglwbfiag.now.sh (copied to clipboard) [5s]
> You (brookstudio_co) are on the OSS plan. Your code and logs will be made public.
> NOTE: You can use `now --public` to skip this prompt
> Initializing…

> Error! The build step of your project failed. To retry, run `now --force`.
child_process.js:634
    throw err;
    ^

Error: Command failed: now
    at checkExecSyncError (child_process.js:591:13)
    at execSync (child_process.js:631:13)
    at exec (/Users/NYC/Desktop/react-redux-apollo/internal/utils.js:40:3)
    at Object.<anonymous> (/Users/NYC/Desktop/react-redux-apollo/internal/scripts/deploy.js:8:1)
    at Module._compile (module.js:569:30)
    at loader (/Users/NYC/Desktop/react-redux-apollo/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/NYC/Desktop/react-redux-apollo/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This is straight after cloning the `react universally` repo. Any ideas?

**Comment by leo** [comment]
See [this](https://zeit.co/brookstudio_co/react-universally/hfglwbfiag/logs). `babel-node` is missing. 😊 

This error is not related to Now CLI, but rather your project setup. Please ensure that the dependency gets installed on the server.

**Comment by mb8z** [comment]
@leo Would you mind giving me some more details how to execute it? Can't add `babel-node` to devDependencies as it is now deprecated. I'm reading your docs for a while and didn't find anything.

**Comment by leo** [comment]
What do you mean with "it's deprecated"? If you use it in your code, you need to add it to the dependencies. If you don't want to add it to your dependencies, you need to remove it from your code. 😊

Feel free to drop by at https://zeit.chat!

**Comment by mb8z** [comment]
I have `babel-cli` added as a dependency.
My `build` command looks like this: 
`"build": "./node_modules/babel-cli/bin/babel-node.js internal/scripts/build --optimize",` (previously it was just `babel-node` instead of the path to it).
Still getting the message that `babel-node` can't be found.

**Comment by designspin** [comment]
Hey Ancinek, did you manage to get a fix for this?
