### ISSUE TITLE
now buy domains returning `undefined` price

### ISSUE THREAD

**Issue by bukinoshita** [vercel/vercel#738]
```
➜  ~ git:(master) ✗ now buy domains domain-name.something
> The domain "domain-name.something" is available to buy under bukinoshita! [3s]
> Buy now for $undefined (undefinedyr)? [y|N] 
```

**Comment by jamo** [comment]
Thanks for the report, I'll look into it

**Comment by jamo** [comment]
Thanks again for the error report - seems that I was able to resolve the issue with the domains api. 
Please let me know if the error still happens for you.

**Comment by bukinoshita** [comment]
working just fine again! thanks
