### ISSUE TITLE
Environment variables stopped working

### ISSUE THREAD

**Issue by kshmir** [vercel/vercel#739]
We started using now for some static authenticated sites, after a couple of days we can't deploy with http auth any longer.

```
{
  "scripts": {
    "start": "serve --auth"
  },
  "dependencies": {
    "serve": "latest"
  }
}
```

We use

```now -e SERVE_USER=user -e SERVE_PASSWORD=password```

Printing the env vars show they're empty.

It happens also with .dotenv or env vars loaded in my shell.

CLI version is 7.3.0.

**Comment by matheuss** [comment]
Can you provide an example of a deployment in which the env vars are not working? I just deployed the following `index.js` with `now -e TESTING=123`:
```javascript
module.exports = () => {
  return process.env
}
```

Seems to be working fine:
```
▲ nano at master ✖ curl -sL nano-zydrdhlafi.now.sh | jq .TESTING 
"123"
```

**Comment by kshmir** [comment]
With this package JSON, I get the following logs.

```
{
  "scripts": {
    "start": "echo SERVE_USER=$SERVE_USER SERVE_PASSWORD=$SERVE_PASSWORD && serve --auth"
  },
  "dependencies": {
    "serve": "latest"
  }
}
```

     $ now -e SERVE_USER=user -e SERVE_PASSWORD=password
     > Using Node.js 8.2.1 (default)
     > Ready! https://performance-kfwaideqkf.now.sh [3s]
     > Synced 1 file (15.32kB) [2s]
     > Initializing…
     > Building
     > ▲ npm install
     > ⧗ Installing 1 main dependency…
     > ✓ Installed 164 modules [5s]
     > ▲ npm start
     > > @ start /home/nowuser/src
     > > echo SERVE_USER=$SERVE_USER SERVE_PASSWORD=$SERVE_PASSWORD && serve --auth
     > SERVE_USER= SERVE_PASSWORD=
     > serve: Running on port 5000
     > Deployment complete!


When running, I get a 502 and serve fails because of not having the correct env vars. This worked just a couple days ago.

**Comment by jamo** [comment]
Earlier today fixed a regression with secrets in new deployments.

**Comment by kshmir** [comment]
Thanks, will check it out!

**Comment by kshmir** [comment]
It seems to be working now, thank you!
