### ISSUE TITLE
`now --static` should not ignore files

### ISSUE THREAD

**Issue by mathiasbynens** [vercel/vercel#742]
`now` aggressively ignores files, which is a known issue: https://github.com/zeit/now-cli/issues/157

However, for static deployments, it doesn’t make sense to ignore `node_modules` directories etc. Consider not ignoring files for static deployments made through `now --static`.

**Comment by jacobmischka** [comment]
Getting hit with this right now too, only workaround I can find is renaming `node_modules` to something else and referencing that instead (ie `$ mv node_modules/ deps/ && ln -s deps node_modules`). Doesn't seem possible to trick now into uploading `node_modules` no matter what you do.
