### ISSUE TITLE
Trouble aliasing Squarespace domain.

### ISSUE THREAD

**Issue by mrwillis** [vercel/vercel#746]
Hi all,

I am following the steps [here](https://zeit.co/docs/features/aliases) and  [here](https://zeit.co/docs/features/zero-downtime-migration) using a Squarespace domain but I am having some issues running

`now alias deployment [domain]` :(

Here is everything that I've done and has worked:

1. `now domains add --external tokenfort.com`
2. Added the `TXT` record in Squarespace with the key from above
3. `now domains add --external tokenfort.com` (success!)
4. `now alias my-deployment-eyhxcwtevc.now.sh tokenfort.com` fails provisioning the certificate. 

```
now alias nextjs-oabaobunyc.now.sh tokenfort.com
> tokenfort.com is a custom domain.
> Verifying the DNS settings for tokenfort.com (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for tokenfort.com
> Error! Unknown error: Error: Invalid challenge response for tokenfort.com. Make sure the DNS rec
ords are correct.
Error: Invalid challenge response for tokenfort.com. Make sure the DNS records are correct.
    at module.exports.EventEmitter.createCert.domain.retry (C:\snapshot\now-cli\lib\index.js:787:1
7)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

As per another issue I read, I ran `now create cert tokenfort.com` but got a similar error:

```
now cert create tokenfort.com
> Error! Unexpected error. Please try again later. (Invalid challenge response for tokenfort.com.
Make sure the DNS records are correct.)
```

So maybe I figured I should try changing the nameservers, which I did:

![image](https://user-images.githubusercontent.com/2652683/29675306-c7f119a8-88c2-11e7-8e7e-442280896378.png)

But I get the same error running `now alias`. Not sure what I've done wrong :(

Thanks for the help.

**Comment by bntzio** [comment]
You need to add your domain without the `--external` flag so that it points to the `zeit.world` nameservers.

1. Remove your domain `now domain rm your-domain`
2. Re-add your domain `now domain add your-domain`
3. Alias your deployment again `now alias deployment-url your-domain`

And just wait for DNS to propagate 🙂

**Comment by mrwillis** [comment]
Thanks @bntzio. You were a great help. Much appreciated!
