### ISSUE TITLE
Deploy Grav to Now?

### ISSUE THREAD

**Issue by itsdillon** [vercel/vercel#748]
I'm pretty new to Docker, so I'm pretty lost here.

I'm trying to deploy a flat file CMS project named Grav. I found this docker container online https://github.com/andreaschiona/grav-dokerized and was able to deploy without any errors. But once I goto the url https://andreaschiona-grav-dokerized-echaqoadgr.now.sh/ I get an error.

How should I go about this, and still have the ability to upload custom themes and plugins etc...

**Comment by Qix-** [comment]
Hi @dillonraphael - sorry for the delay here.

Are you still seeing this problem? I'm not entirely sure this is a Now problem or if it's a problem with your Docker configuration.

I'm going to optimistically close this, but please don't hesitate to respond if you feel it should be re-opened.

Alternatively, there is a crowd of people (including us!) that would be willing to help in Slack over at https://zeit.chat.
