### ISSUE TITLE
Command to show deployment logs

### ISSUE THREAD

**Issue by vjpr** [vercel/vercel#751]
I ran `now`, and then `ctrl+c`d, and was surprised to find my build still running, but no command to view the deployment logs (upload/sync status etc.).

**Comment by leo** [comment]
You can use `now logs -h`. ☺️

**Comment by vjpr** [comment]
It doesn't seem to show sync/deployment status. And I could not actually get it to work...

```
➜  vwp git:(master) ✗ now
> Deploying ~/dev-live/vwp under xxx
> Using Node.js 8.2.1 (default)
> Ready! https://vwp-zzz.now.sh (copied to clipboard) [6s]
> Synced 1 file (33.53kB) [3s]
> Initializing…
^C
➜  vwp git:(master) ✗ now logs

  𝚫 now logs <deploymentId|url>

  Options:

    -h, --help              output usage information
    -a, --all               include access logs
    -c FILE, --config=FILE  config file
    -d, --debug             debug mode [off]
    -f                      wait for additional data [off]
    -n NUMBER               number of logs [1000]
    -q QUERY, --query=QUERY search query
    -t TOKEN, --token=TOKEN login token
    --since=SINCE           only return logs after date (ISO 8601)
    --until=UNTIL           only return logs before date (ISO 8601), ignored if the f option is enbled.

  Examples:

  – Print logs for the deployment `deploymentId`

    $ now logs deploymentId

➜  vwp git:(master) ✗ now ls
> 6 deployments found under quantitec [935ms]

vwp (5 of 5 total)
 url                                inst #    state                 age
 vwp-zzz1.now.sh                   0    BUILDING              12s
 vwp-zzz2.now.sh                   0    FROZEN                19h
 vwp-zzz3.now.sh                   1    READY                 19h
 vwp-zzz4.now.sh                   0    FROZEN                19h
 vwp-zzz5.now.sh                   0    BUILD_ERROR           19h

now-test (1 of 1 total)
 url                                inst #    state                 age
 now-test-emrysbpsyt.now.sh              ✖    READY                 59m

➜  vwp git:(master) ✗ now logs  vwp-zzz1.now.sh
➜  vwp git:(master) ✗ now logs vwp-zzz1.now.sh
➜  vwp git:(master) ✗ now logs -a vwp-zzz1.now.sh
➜  vwp git:(master) ✗ now logs -f vwp-zzz1.now.sh
^C
➜  vwp git:(master) ✗
```

**Comment by vjpr** [comment]
Also, might be useful to make `now logs` detect the most recent deployment for the project in the `cwd` and print the logs.

**Comment by leo** [comment]
@vjpr Are you using a beta of Now CLI? Check `now -v`. If so, switch to the normal CLI:

`npm install -g now`

As you can see, `now ls` shows the uploading/sync status as "DEPLOYING".

**Comment by vjpr** [comment]
```
now -v
7.4.0
```

> As you can see, now ls shows the uploading/sync status as "DEPLOYING".

But if the upload/sync stage is taking a long time there is no way to see that. If you `ctrl+c` you cannot get back to the logging that was showing in the console during the deploy.

E.g. I want to see this status again:

![screen shot 2017-08-29 at 11 06 34 am](https://user-images.githubusercontent.com/281413/29917540-8fd3b546-8e42-11e7-84cb-ee8dd6b54e38.png)

**Comment by leo** [comment]
I don't think there should be a way to get back to that if you intentionally exited the process by hitting `ctrl` and `c` on your keyboard.

@TooTallNate @matheuss Thoughts?

**Comment by vjpr** [comment]
But if the upload hangs or is super slow, there is no way to check progress anymore (even on the web) after `ctrl-c`.

I don't expect to be able to get back to that view necessarily, but there should be a way to `tail` the deployment / syncing logging output after you `ctrl-c`.
