### ISSUE TITLE
Add support for now <file>

### ISSUE THREAD

**Issue by leo** [vercel/vercel#756]
_From @rauchg on July 7, 2017 6:16_

Support for `now <file>`, with support for:

- Binaries as a first-class deployment type
- Static deployments as a fallback

_Copied from original issue: zeit/now#2_

**Comment by Qix-** [comment]
@rauchg is this still 'in the works' or is it done?

**Comment by leo** [comment]
@Qix- not working yet! Now Desktop supports it though 😇

**Comment by Qix-** [comment]
@leo aha, that's what I was thinking about :)

**Comment by leo** [comment]
Landed! https://github.com/zeit/now-cli/pull/1139
