### ISSUE TITLE
GCP deploy on next@beta throws TypeError

### ISSUE THREAD

**Issue by leo** [vercel/vercel#757]
_From @danoc on August 30, 2017 3:21_

Hello! When running `now` for a GCP deployment I'm running into:

```
⠋ Building and bundling your app…> Error! An unexpected error occurred!
  TypeError: builders[desc.type] is not a function
    at build (/snapshot/now/dist/now.js:1590:29)
    at deploy (/snapshot/now/dist/now.js:5960:25) TypeError: builders[desc.type] is not a function
    at build (/snapshot/now/dist/now.js:1590:29)
    at deploy (/snapshot/now/dist/now.js:5960:25)
```

Has anyone else seen this issue? I'm using `8.0.0-beta.8`.

_Copied from original issue: zeit/now#64_

**Comment by divyenduz** [comment]
I am getting the same error for aws deploy with now 8.3.10.

**Comment by alamont** [comment]
I have the same issue on 8.5.4 with gcp.

**Comment by idanwe** [comment]
I have the same issue with now@9.0.1 and aws running `now aws`

**Comment by luisherranz** [comment]
Same here on now@9.2.7

**Comment by boyum** [comment]
I am experiencing this on now@11.4.6. I have tried reinstalling `now` on my current computer, as it works perfectly on another pc with the same project ([https://github.com/boyum/how-to-emoji](https://github.com/boyum/how-to-emoji)) and the same user logged in to `now`.

The error happens every time I try deploying, but prints out different messages. Apart from the one @leo is experiencing, a few others appear:

> Error! Got unexpected status code from Google: 400
> Error! Couldn't find "gcp" property in now.json
> Error! An unexpected error occurred in deploy: TypeError: Cannot read property 'id' of undefined
    at fnCheckExistsRes (C:\snapshot\repo\dist\now.js:22179:106)
    at Object.deploy (C:\snapshot\repo\dist\now.js:22186:32)
    at <anonymous>

and:
> Error! Got unexpected status code from Google: 400
> Error! An unexpected error occurred in deploy: TypeError: Cannot read property 'region' of undefined
    at Object.deploy (C:\snapshot\repo\dist\now.js:22156:28)
    at <anonymous>

The gcp-one appears even though I don't have a `now.json` file (nor a `now` section in `package.json`).

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
