### ISSUE TITLE
Command options not visible in cmder

### ISSUE THREAD

**Issue by leo** [vercel/vercel#759]
_From @darahak on August 27, 2017 21:32_

I use Cmder on Windows and when I use `--help` for any command, I cannot see the options unless I highlight them. Some descriptions are also hard to read because of the low contrast between their background and font color.

I'm not sure if the problem is about Now or Cmder.
Screenshots below.

<details>
<summary>Current display</summary>

![now-default](https://user-images.githubusercontent.com/11488612/29754059-58208276-8b7e-11e7-9070-cc9f4c88cba5.png)
</details>

<details>
<summary>Highlighting hidden text</summary>

![now-hl](https://user-images.githubusercontent.com/11488612/29754078-884b445e-8b7e-11e7-9334-12f0d528f69f.png)
</details>

_Copied from original issue: zeit/now#60_

**Comment by Qix-** [comment]
This is a problem that's been well discussed over at https://github.com/chalk/chalk/issues/161 :) I encourage you to check that out.

Unfortunately there's nothing we can do in now-cli to remedy this.
