### ISSUE TITLE
Deployment on AWS Lambda gives Code 500 Internal Server Error

### ISSUE THREAD

**Issue by leo** [vercel/vercel#761]
_From @darknoon on August 24, 2017 22:41_

I tried deploying a really basic app just to make sure it wasn't my server misbehaving:

```
$ cat server.js
require('http')
	.createServer((req, res) => {
		res.end('Hello World!');
	})
	.listen(process.env.PORT);
```

I ran this command (my now beta is installed locally)

```
$ ../node_modules/.bin/now aws
> Deploying "~/Code/Lobe/lobe/src/frontend/test-deploy" (aws) (us-west-1)
✔ Build generated a 1.69kB zip [148ms]
✔ API resources created (id: "now-test-deploy-4eCnyDRqXH") [2s]
> Success! https://k4atst0laf.execute-api.us-west-1.amazonaws.com/now (in clipboard) [2s]

```

shows:

```{"message": "Internal server error"}```

_Copied from original issue: zeit/now#57_

**Comment by leo** [comment]
_From @darknoon on August 24, 2017 22:43_

My now version is `8.0.0-beta.8`

I'm not sure how to check the logs from AWS; it doesn't seem to be showing up in cloudwatch.

**Comment by blakek** [comment]
I am seeing the same issue.  I had to adjust the permissions for the now-default role for CloudWatch logs (not sure if that's specific to our account—if not, I'd be glad to contribute documentation).

The logs are saying "Could not establish a connection to the http server".

**Comment by cangoektas** [comment]
@leo I looked into this and found a couple of issues:

1. [The `PATH` environment variable](https://github.com/zeit/now-cli/blob/canary/src/serverless/handler.js#L37) is missing some directories which makes the child process exit with code 127 command not found.
    - `sh` is located in `bin`
    - I don't know why but there's a `node 0.10.48`  binary located in `/usr/bin` which is used but node 6 is in `/var/lang/bin`

<img width="1280" alt="node_versions" src="https://user-images.githubusercontent.com/1178516/31464305-76e747c8-aed1-11e7-9cad-396cf7cff7c0.png">

2. There's an issue with how the proxy functions are injected into `__how_handler.js`, which is not obvious at first. After `now` is build, everything is bundled into one file, except `handler.js`. When creating `__now_handler.js`, the [`handler.js` file is read from the filesystem](https://github.com/zeit/now-cli/blob/canary/src/serverless/get-handler.js#L8) *but* the proxy function code comes from _within the bundle itself_ and it's injected with [´.replace(REQ_HANDLER_SYMBOL, fn.toString())´](https://github.com/zeit/now-cli/blob/canary/src/serverless/get-handler.js#L34)

<img width="1280" alt="webpack_require" src="https://user-images.githubusercontent.com/1178516/31464188-fe6daf3a-aed0-11e7-91e3-12d2dc90a8ae.png">

I worked on it and got Lambda deployments working now but I feel like my implementation is a bit hacky. :/ I mean the first problem is very straight-forward to fix but the webpack stuff is a bit tricky. I fixed it by also copying the proxy functions (just like `handler.js`) and then injecting the _unbundled_ code into `__now_handler.js`. But I feel like there should be a separate webpack build for the serverless handlers.

But anyway, maybe we can still get it in as a quick fix :) Would you like a PR and have a look?

**Comment by leo** [comment]
We have concluded that we are not going to maintain any of the third party platforms (Google Cloud Platform or Amazon Web Services) and are therefore removing them from Now CLI.

Since the third-party providers were not functioning properly anyways, we are hard-deprecating them as of now (there will not be a replacement).

They are removed in https://github.com/zeit/now-cli/pull/1601.
