### ISSUE TITLE
Feedback on v1 release of now.json @beta

### ISSUE THREAD

**Issue by leo** [vercel/vercel#766]
_From @babakness on August 3, 2017 23:16_

Feature request:

Being able to launch a service into a VPC so that it can access services (like a database) would be awesome. Perhaps there could be a key for "vpc" in now.json accompanied by the matching function. 

I have noted that there "regions" key which is an array. If launch simultaneously to multiple region, I suppose the idea here is to load balance between them? Perhaps, then, vpc is an object which provides a region-to-vpc map. In which case it seems that the "regions" option could be unnecessary since the regions are the VPC keys.

```
"regions": {
  "us-west-1": '192.168.0.0/16,
  "us-west-2": '192.168.0.0/16
}
```

implies values for "regions" of "us-west-1" and "us-west-2"

_Copied from original issue: zeit/now#42_

**Comment by Qix-** [comment]
FWIW this is definitely planned functionality.
