### ISSUE TITLE
Add kubernetes backend

### ISSUE THREAD

**Issue by leo** [vercel/vercel#767]
_From @rauchg on July 7, 2017 6:16_

_Copied from original issue: zeit/now#3_

**Comment by leo** [comment]
_From @rosskukulinski on July 13, 2017 16:1_

@rauchg let me know if you have questions regarding the Kubernetes ecosystem and/or APIs.  I'm loving the progress you're making with the Now Universal announcement today.

**Comment by leo** [comment]
_From @raphaelkross on July 25, 2017 17:11_

@rauchg any specific place where Kubernetes support is being planned? Would love to contribute w/ that, in fact, I was working in something like that - but would love put my effort on this project instead.

**Comment by Qix-** [comment]
@raphaelkross - Kubernetes is planned for sure, but help is always welcome :) Feel free to take a whack at it!

**Comment by netspencer** [comment]
considering building this out! anyone been able to make it work?
