### ISSUE TITLE
Discover custom providers based on presence of `now-*` binaries in $PATH

### ISSUE THREAD

**Issue by leo** [vercel/vercel#769]
_From @rauchg on July 7, 2017 21:35_

_Copied from original issue: zeit/now#6_

**Comment by Qix-** [comment]
@rauchg still want to pursue this?

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
