### ISSUE TITLE
Create a `minimist` wrapper that validates a schema

### ISSUE THREAD

**Issue by leo** [vercel/vercel#770]
_From @matheuss on July 7, 2017 8:13_

It'd, upon a `false` by default `throwOnUnexpectedFlag`, throw if you define `{boolean: ['version']}` and the program is called with `--testing`

_Copied from original issue: zeit/now#5_

**Comment by Qix-** [comment]
Closing in favor of [zeit/arg](/zeit/arg) 🎉
