### ISSUE TITLE
Figure a way to enable providers to return something to us (aka `now.js`)

### ISSUE THREAD

**Issue by leo** [vercel/vercel#773]
_From @matheuss on July 9, 2017 8:42_

We could, for example, let providers use `return 1` to indicate that the they want `process.exit(1)`.

Would be nice here: https://github.com/zeit/now/commit/a1dd06290a784311b05f3e486d609b832a1444de#diff-cec70a08c11a260d44b518126d174623R119

_Copied from original issue: zeit/now#9_

**Comment by Qix-** [comment]
Closing as invalidated - the ref is gone and not enough information. This is also superseded by future universal client plans.

Feel free to re-open if necessary.
