### ISSUE TITLE
Better optimize the bridge for nodejs serverless deployments

### ISSUE THREAD

**Issue by leo** [vercel/vercel#774]
_From @rauchg on July 10, 2017 5:55_

Right now, we spawn a new child where we invoke the user-supplied http server.
However, since our shim is in Node.js, we can simply `require` and avoid extra I/O, copy, parsing time, etc.

_Copied from original issue: zeit/now#13_

**Comment by Qix-** [comment]
@rauchg going to close this as invalid given our future plans for Node.js deployments. Feel free to re-open this.
