### ISSUE TITLE
Look into more efficient proxy solutions to the target processes from the cloud functions

### ISSUE THREAD

**Issue by leo** [vercel/vercel#775]
_From @rauchg on July 10, 2017 5:17_

For example:
https://github.com/GoogleCloudPlatform/cloud-functions-go/blob/master/local_modules/execer/execer.cc

_Copied from original issue: zeit/now#12_

**Comment by Qix-** [comment]
@rauchg could you expand a bit more on this?

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
