### ISSUE TITLE
Make creation of serverless bundles dependent on code changes

### ISSUE THREAD

**Issue by leo** [vercel/vercel#776]
_From @rauchg on July 10, 2017 12:13_

Right now we're appending a timestamp as a workaround.

Some possibilities:
- Piggybacking on `.git` if present
- Hashing contents of staged files

_Copied from original issue: zeit/now#14_

**Comment by Qix-** [comment]
Is this still valid @rauchg?

**Comment by leo** [comment]
No response – closing.
