### ISSUE TITLE
Failed webpack build step of a universal redux react app

### ISSUE THREAD

**Issue by okjulian** [vercel/vercel#78]
I am not sure if this is the place to report issues with now, but here I go anyway.

I keep getting an error in my now deployments.

First of all a little context. I am deploying a server rendered rect app with redux bootstraped using [universal kyt](https://github.com/NYTimes/kyt-starter-universal), and I have a build step that compiles the app using webpack. 

The problem is that the build step fails on now, but works perfectly on my machine. The error I am getting is `Module not found: Error: Can't resolve 'lodash/isPlainObject' in '/home/nowuser/src/node_modules/e3d8a6548416ea90c89022179a97a8ef8f8428d0/lib/components'` I think that this error comes from the `react-redux` package (I cannot tell for sure because now shows a hash instead of the package name)

 I reproduced the error locally using the same node version and starting from an empty node_modules folder. With this configuration everything works perfectly on my machine, but fails on now.

I hacked a solution by forking react-redux, and changing lodash dependency to lodash.isplainobject because that is the only function that react-redux needs. Using my fork of react-redux everything works fine, so the problem has something to do with now and react-redux lodash dependency.

Anyone came across this kind of error before? Any idea of how to solve this without my ugly fork?

**Comment by okjulian** [comment]
Any help regarding this situation? Here is my [now deployment](https://full-stack-blog-app-gyryhbhrva.now.sh/), if it helps.

**Comment by leo** [comment]
@TooTallNate

**Comment by jamo** [comment]
I tried rerunning build for a clone of your deployment; seems that the build is executed properly now. Please reopen if the issue still occurs

**Comment by okjulian** [comment]
Thanks @jamo
