### ISSUE TITLE
[Question] Server bandwidth metric

### ISSUE THREAD

**Issue by leo** [vercel/vercel#785]
_From @AngelKyriako on August 3, 2017 14:50_

- Question 1:
The bandwidth stated in the pricing section is accumulated based on both the inbound & inbound requests ?

I have a setup as follows:
- A node instance which communicates with a client only via REST HTTP.
- The node instance communicates with another mongolab instace to store or retrieve data.

I am in the process where I want to measure and get an average byte size for the bandwidth each request is using. That way I can calculate the request per month the server can handled for a particular plan by doing:
```
ServerRequestPerMonthLimit = ServerBandwidthLimitBytes / (AverageRequestInboundBandwidthBytes + AverageRequestOutboundBandwidthBytes)
```

I am using the [request-stats](https://github.com/watson/request-stats) npm module [like this](https://zeit.co/cqIe6OT3kFkTqqLkIDyLtQzb/thelumeesmayhemserver/pkydlhncnx/source?redirect=1&f=stats.js) to calculate each request inbound size.

And I expose those via the [/_stats](https://dev-thelumeesmayhem.now.sh/_stats) route.

- Question 2:
Do you think a /_stats route would make sense to be enabled by default(Based on an env Param or Plan) from all zeit.now served instances to receive those metrics ?

However, if the pricing bandwidth limitation takes into account outbound traffic as well I am not sure how to measure the outbound requests byte size towards the mongolab server.

- Question 3:
Any ideas on how I could achive that ? 

Finally, since I cannot measure the outbound traffic, I am currently assuming that it is going to be as large as the inbound size in the worst case scenario(Although, I am not sure I should make this assumption).
Which gets me to:
```
ServerRequestPerMonthLimit = ServerBandwidthLimitBytes / (2*AverageRequestInboundBandwidthBytes)
```

By calculating that number and assuming an average number for client requests per month for one user, I am able to make an assumption of how many users the plan can handle per month. 

- Question 4: Does this logic seem to be valid to anyone reading this  ?

PS. I was not sure where to post these stuff, sorry for the spam on the github issues.
PS2. zeit.now is just awesome, thank you.

_Copied from original issue: zeit/now#41_

**Comment by jacsamg** [comment]
Hello. Did you get the answer to the first question? I'm in the same situation.

**Comment by AngelKyriako** [comment]
No idea, but I would bet it is accumulated based on both.

**Comment by leo** [comment]
Indeed, they are summed up! 🙏
