### ISSUE TITLE
Is there any release scheduled supporting Azure (az) ?

### ISSUE THREAD

**Issue by leo** [vercel/vercel#787]
_From @lipp on August 9, 2017 9:43_

_Copied from original issue: zeit/now#46_

**Comment by simontegg** [comment]
I'd also love to see azure

**Comment by matheuss** [comment]
Yeap, Azure is planned 👍

**Comment by jonatansberg** [comment]
@matheuss Roughly when is planned? Are we talking days, months, years? And are there any ways to contribute in order make that time window smaller? :)

**Comment by matheuss** [comment]
@mrlundis we'll share a more precise schedule as soon as possible 🙌

**Comment by petertiedemann** [comment]
@matheuss https://github.com/zeit/now-cli/tree/8.3.10#microsoft-azure-az indicates that `now az login` should be valid command in 8.3.10, but i get `> Error! The specified directory "az" doesn't exist.` . Is it correctly understood that the documentation is incorrect?

**Comment by matheuss** [comment]
@petertiedemann yeah, the docs are incorrect as of now. We'll fix them ASAP!

**Comment by leo** [comment]
Docs just got fixed! https://github.com/zeit/now-cli/pull/1138

**Comment by szul** [comment]
Is there any update on Azure login support? Still doesn't seem to be a valid login.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
