### ISSUE TITLE
COPY folder with Docker issues with .gitignore file

### ISSUE THREAD

**Issue by arashsa** [vercel/vercel#790]
Copying a folder with Docker

`COPY ./dist /dist`

does not work when this folder is included in the .gitignore file.

**Comment by arashsa** [comment]
I figured out that now ignores files and folders inside .gitignore. 

To still upload files that you want to ignore for git (such as build files), you can add them to a now.json file.

An example would be:

```
{
    "name": "name",
    "type": "docker",
    "files": [
        "dist"
    ]
}
```

**Comment by arashsa** [comment]
However, there seems to be issues with this, as the dist folder is still not included and I am getting an error when building the Dockerfile:

`lstat dist: no such file or directory`

**Comment by pekkah** [comment]
Having same issue. Using now.json to include a gitignored folder. Getting same error from docker build.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
