### ISSUE TITLE
Continuous Deployment with Now

### ISSUE THREAD

**Issue by Theo-** [vercel/vercel#791]
Hi,

I was wondering if there is a way to do authentification with `now` during Continuous Deployment.
Looking for something like `now login -t ${DEPLOYMENT_TOKEN}`

I searched the previous issues but I couldn't find anything.
Thanks!

**Comment by evenchange4** [comment]
I have the same question here. What is the best practice of authentification for CD with now-cli?
For my projects, I append `--token [TOKEN]` for all the commands:

```
$ now switch [TEAM] --token [TOKEN]
$ now ls --token [TOKEN]
$ now deploy --public --token [TOKEN]
```

It is just a little inconvenient but works great.

ref: https://github.com/evenchange4/micro-github-latest/blob/master/tasks/deploy.sh#L20

**Comment by leo** [comment]
With the latest version, you can pass `-t` or `--token` to any sub command... 😊
