### ISSUE TITLE
Why not host on NPM instead of downloading in a postinstall script?

### ISSUE THREAD

**Issue by trusktr** [vercel/vercel#792]
The reason I ask is because it seems dubious to have someone run `npm i -g now` to install essentially nothing, and then postinstall downloads the actual tool. It seems like abuse of the NPM registry, using it in a way that wasn't intended.

I'm not saying that Now is dubious, just that the install process might seem dubious to some.

---

But anyways, all the Zeit stuff is simply awesome, and it's a great product!!

**Comment by leo** [comment]
Having npm host our binaries would mean having binaries for all supported platforms in the npm package. In turn, the time it takes to download would be about 4x the current one... 😊 

> But anyways, all the Zeit stuff is simply awesome, and it's a great product!!

Thanks a lot!
