### ISSUE TITLE
Unexpected Prompt for Login when given token.

### ISSUE THREAD

**Issue by evenchange4** [vercel/vercel#796]
## Issue

There is an unexpected **Prompt for Login** when I use now-cli in CI:

```
+now switch [TEAM] --token [secure]

> No existing credentials found. Please log in:
> Enter your email: 

😭  pending ...
```

## Version

✅ ^7.3.0 => ❌  v8.0.0

I think it is related to the new `Prompt for login if no credentials defined: #795` patch.

## Reference

travis log: https://travis-ci.org/evenchange4/micro-github-latest/builds/271540119

## PR

#797

**Comment by nulltask** [comment]
Me too :(

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now-cli/pull/797
