### ISSUE TITLE
Specify scope in now.json

### ISSUE THREAD

**Issue by gunar** [vercel/vercel#799]
Let me specify which team owns the project by setting the key `package.json.now.team`,
as I might forget to `now switch` before deploying.

Thank you.

**Comment by Qix-** [comment]
@rauchg thoughts?

**Comment by revolunet** [comment]
handy feature that prevents many useless deploys :)

**Comment by thomaslindstrom** [comment]
You can do this on the `now` command by doing `now —team=my-team`, so I don’t see why we shouldn’t also be able to configure it in, eg., `now.json`, too. 😉

**Comment by timneutkens** [comment]
I run into this when deploying nextjs.org too. This would be very nice if you're managing multiple teams and don't want to switch context every time you want to deploy.

**Comment by leo** [comment]
You can now set `scope` in `now.json` for this (details [here](https://zeit.co/docs/v2/deployments/configuration/#scope)).
