### ISSUE TITLE
Secret values with leading dashes are parsed as the incorrect number of args

### ISSUE THREAD

**Issue by evansolomon** [vercel/vercel#80]
```
$ now secrets add thing "-wtf"
> Error! Invalid number of arguments. Usage: `now secret add <name> <value>`
```

**Comment by maxbeatty** [comment]
I _think_ you need to base64 encode secrets like that for now

```
now secrets add --base64 thing $(echo "-wtf" | base64)
```

**Comment by leo** [comment]
Exactly! We'll probably also keep it like that.

**Comment by cdock1029** [comment]
How do you get the original string back out? 

I'm getting `"[object Object]"` when debugging / logging the string

**Comment by pcambra** [comment]
I am not sure that the --base64 parameter is actually doing anything in the `now secrets add` command, I did this instead:

```
now secrets add thing $(echo "-wtf" | base64)
```

Otherwise I'd get `[object Object]` as @cdock1029 says.

**Comment by Fuzzyma** [comment]
I really would like to know how to fix this... all solutions here do not work:

```sh
$ now secret add --base64 channel_id $(echo "-12345" | base64)
> Error! Invalid number of arguments. Usage: `now secret add <name> <value>`

now secrets add thing $(echo "-123" | base64)
> Well works but in the program I have something like "ABCDE" insead the actual parameter
```

So its abolutely not possible to use parameters starting with a dash.

**Comment by jamo** [comment]
One solution would be to base64 decode the secret in the app
also you might want to omit the newline coming from echo so that decoding the secret would work as expected:
`now secrets add thing $(echo -n "-123" | base64)`

The api will be eventually improved

**Comment by Fuzzyma** [comment]
>The api will be eventually improved

That would be nice. `now.sh` should not in any way come into the way of programming issues. And having to decode an env variable which is normally set perfectly fine is such an issue.

**Comment by hleumas** [comment]
There actually is perfectly working solution, see https://github.com/zeit/now-cli/issues/749#issuecomment-487322395
