### ISSUE TITLE
`now dns add` should return error feedback in case of an error

### ISSUE THREAD

**Issue by bukinoshita** [vercel/vercel#801]
Running:
```
$ now dns add <DOMAIN> TXT <VALUE>
```
on `v7.4.0` it returns me `> Error! Invalid number of arguments. See: now dns --help for usage.` but on `v8.0.1` it does not return anything.

cc @sergiodxa

**Comment by Qix-** [comment]
Hi @bukinoshita - sorry for the delay here.

We fixed a number of these a while back, and I haven't seen any more reports of them since. I'm going to optimistically close this issue - please respond here if you are still seeing this issue!

Thanks for the issue :)
