### ISSUE TITLE
`now alias` should return error feedback in case of an error

### ISSUE THREAD

**Issue by bukinoshita** [vercel/vercel#802]
Running:
```
$ now alias
```

When it's unable to verify that they've propagated, on `v7.4.0` it returns me this error message `> Error! > We configured the DNS settings for your alias, but we were unable to verify that they've propagated. Please try the alias again later.` but on `v8.0.1` it does not return anything.

**Comment by bukinoshita** [comment]
might be related to https://github.com/zeit/now-cli/issues/801 since it's not returning an error as well

**Comment by Qix-** [comment]
Hi @bukinoshita - sorry for the delay here.

We fixed a number of these a while back, and I haven't seen any more reports of them since. I'm going to optimistically close this issue - please respond here if you are still seeing this issue!

Thanks for the issue :)

**Comment by tugkan** [comment]
+1

**Comment by tugkan** [comment]
@Qix- +1
