### ISSUE TITLE
Token-based authentication broken for some commands

### ISSUE THREAD

**Issue by AndreyNikiforov** [vercel/vercel#804]
My CI worked on 7.4.0 now-cli, but started to fail after 8.0.1 upgrade.

cmd line: `now deploy --npm --token="${NOW_TOKEN}"`
and `now alias --token="${NOW_TOKEN}"`

Trying locally (Mac) with --debug flag gives the following (some lines are removed):

> [debug] /now/create: 2009.898ms
> [debug] error: Error: Not authorized
Error: Not authorized
   at module.exports.EventEmitter.create.deployment.retry (/snapshot/now-cli/dist/now.js:396:21)
   at process._tickCallback (internal/process/next_tick.js:109:7)

Deploying with logged in credentials works.

Any ideas what may be causing this?

**Comment by leo** [comment]
Checking this today!

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now-cli/pull/805
