### ISSUE TITLE
`> Ready! https://xxx.now.sh (copied to clipboard)` should not say `Ready!`

### ISSUE THREAD

**Issue by vjpr** [vercel/vercel#806]
```
> Deploying xxx under yyy
> Using Node.js 8.4.0 (default)
> Ready! https://xxx.now.sh (copied to clipboard) [24s]
> Initializing…
> Building
> ▲ npm install
> ✓ Using "yarn.lock"
> ⧗ Installing 67 main dependencies…
> ✓ Installed 911 modules [29s]
> ▲ npm run build
> > xxx@1.0.0 build /home/nowuser/src
> > next build
> > Using external babel configuration
> > Location: "/home/nowuser/src/.babelrc"
> > Using "webpack" config function defined in next.config.js.
```

I think `Ready!` is confusing here, especially with the use of an exclamation mark.

- It is not clear what is actually "ready".
- Every new user with think that there deploy is already finished, then find a 503 or something when its not.

I suggest being more clear about what is "ready", and removing the color and the exclamation point.

**Comment by melvin0008** [comment]
Would "Your deployment is ready!" be more apt?

**Comment by Qix-** [comment]
Would `Depoying to $url (copied to clipboard)` work instead?

**Comment by gtsiolis** [comment]
It should be safe to close this, since this is not relevant anymore (see https://github.com/zeit/now-cli/pull/1002#issuecomment-363619695). `deploy.js` has moved and the output changed to:

```sh
> Deploying ~/app under {username}
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
> https://app-{abc}.now.sh [in clipboard] [3s]
> Deployment complete!
```

**Comment by markozxuu** [comment]
@sergiodxa @pranaygp  it's time to close this issue
