### ISSUE TITLE
now throws exception when bootstrapping login

### ISSUE THREAD

**Issue by jesseditson** [vercel/vercel#812]
Logged in with a fresh install on a new machine, got these results:

```
$ now
> No existing credentials found. Please log in:
> We sent an email to jesse.ditson@gmail.com. Please follow the steps provided
  inside it and make sure the security code matches <redacted>.
✔ Email confirmed
TypeError: Cannot convert undefined or null to object
    at getUser (/snapshot/now-cli/dist/now.js:7160:10)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Worked fine on the second run, would guess that it's assuming `~/.now` exists when it doesn't, or something along those lines!

**Comment by Qix-** [comment]
Hi there - apologies for the delay.

It looks like this has since been fixed. I'm going to close this issue, but please reply here if you're still seeing this problem.

Thanks!
