### ISSUE TITLE
Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by codeofsumit** [vercel/vercel#814]
I got an SPA that I try to deploy, build and serve like in this guide https://zeit.co/blog/now-static.
Whenever `npm run build` is executed I get this error though:

```
 > node build/build.js
> Segmentation fault (core dumped)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 139
> npm ERR! medaku@1.0.0 build: `node build/build.js`
> npm ERR! Exit status 139
> npm ERR! 
> npm ERR! Failed at the medaku@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2017-09-06T11_09_31_927Z-debug.log
> Error! The build step of your project failed. To retry, run `now --force`.
```

the build is working fine locally. Any ideas what might be wrong?

**Comment by codeofsumit** [comment]
will ask via slack support

**Comment by alexananiev** [comment]
Hey @codeofsumit! Have you resolved the issue? Can you share the solution?

**Comment by infiman** [comment]
@codeofsumit have you fixed that? Have similar issue here :(

**Comment by arivatibm** [comment]
Same here - any clue on solution?

**Comment by codeofsumit** [comment]
Yes, use a node 7 alpine image. Node-sass and the node 8 alpine image do not get along. 
Put this in your package.json:
```
"now": {
  "engines": {
    "node": "7.x.x"
   }
}
```
