### ISSUE TITLE
Drop old deploy under alias after deploy of new version

### ISSUE THREAD

**Issue by imevro** [vercel/vercel#827]
Hi, thanks for your work, I'm in love with it!

Case: I have alias `X.now.sh` and I'm deploy as `now --public && now alias` new version (`Y-1q2w3e4r5y.now.sh`) of app under that alias, but when I do `now ls`, I see old version (`Z-0z9x8c7v.now.sh`) too under that alias.

```
X (2 of 2 total)
 url                           inst #    state                 age
 Y-1q2w3e4r5y.now.sh                1    READY                  2m
 Z-0z9x8c7v.now.sh                  1    READY                  7h
```

How can I auto remove old version? It's little verbose run `now ls` and `now rm [deployId]` after each deploy.

Thanks!

**Comment by leo** [comment]
Which command did you run exactly? The list you just showed doesn't contain aliases, but rather groups per app name (`now ls`). The app name is **not** the alias.

So if your deployments have the same deployment name (specified as the `name` property in `package.json`, for example), they will be grouped together.

**Comment by imevro** [comment]
Ah, I see, don’t know that. 

But question is still actual: how to prune old deploy automatically after release of new version?

**Comment by leo** [comment]
@evgenyrodionov That's not necessary. 😊 The Now platform is built so that you can just leave your old deployments laying around if you want to access them later.

But you can run `now rm -h` to learn how to remove them.

**Comment by imevro** [comment]
Ok, thanks
