### ISSUE TITLE
`now domain` doesn't handle auth errors

### ISSUE THREAD

**Issue by leo** [vercel/vercel#84]
<img width="799" alt="screen shot 2016-07-19 at 4 19 35 pm" src="https://cloud.githubusercontent.com/assets/775227/16941728/e8601a18-4dcc-11e6-8719-ee9499934faf.png">

**Comment by leo** [comment]
✔️

**Comment by OlliV** [comment]
Was it fixed somewhere?

**Comment by leo** [comment]
Just checked it locally and it wants to you to sign in.
