### ISSUE TITLE
`URL=$(now)` process exits before deployment is completed

### ISSUE THREAD

**Issue by mattfysh** [vercel/vercel#847]
Works:

```bash
now
now alias $(pbpaste) mydomain.com
```

Doesn't work:

```bash
URL=$(now)
now alias $URL mydomain.com
```

**Comment by mattfysh** [comment]
Note: the goal is to avoid running the alias command while the container is still building and the node.js server process has yet to start

**Comment by TooTallNate** [comment]
In my opinion `now alias` should _just work_ with deployments that are still building.

However that said, there's plenty of use cases where you might want to interact with the deployment in other ways than `now alias` (think a simple `curl` request to validate the HTTP response), so we should probably add a flag to wait for the deployment to be complete (`now --wait`?)

Another option is to make `now | some-pipe` (any time now is invoked with non-TTY), but that's probably a bit too magical IMO.

**Comment by jamo** [comment]
We should fix the regression; from the beginning, the default behaviour has been to wait for the ready/build error and only then exit with appropriate exit code.

@matheuss @leo can you look into fixing this regression

**Comment by justafish** [comment]
The current behaviour is also preventing me from being able to see deploy logs in my CI

<img width="1571" alt="screen shot 2017-10-03 at 13 38 16" src="https://user-images.githubusercontent.com/345613/31125423-2935d2fc-a840-11e7-8770-85c99e72d150.png">

**Comment by rtsao** [comment]
I've created a PR that resolves this: https://github.com/zeit/now-cli/pull/934

**Comment by kirillgroshkov** [comment]
So is there a `--wait` flag, or how do I make sure deployment is completed (or errorred) after `now` command exited?

E.g I want to do: `now deploy && now alias` and now I'm having an error that deployment hasn't completed yet to alias it.

**Comment by jamo** [comment]
`now` should block until the deployment has transitioned to READY i.e binds a port and we start forwarding traffic to it.

If something else is happening it's a regression.

Are you using the latest `now` client?

**Comment by kirillgroshkov** [comment]
Here' my log:
```
now --version
9.3.0

now --public --npm && now alias
> Deploying ~/Idea/kg-backend under kirill
> Using Node.js 8.9.4 (requested: `8.9.4`)
> Ready! https://kg-backend-delmazmjml.now.sh (copied to clipboard) [7s]
> Synced 15 files (197.6KB) [0ms] 
> Initializing…
> Assigning alias kg-backend to deployment...
> Error! Unknown error: Error: The deployment is not ready yet
Error: The deployment is not ready yet
    at module.exports.Now.createAlias.alias.retry (/snapshot/now-cli/dist/now.js:3991:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by moul** [comment]
Same here with latest version

```console
$ now --version
9.3.2

$ now --npm -T $NOW_TOKEN && now alias -T $NOW_TOKEN
> Deploying ~/dashboard under xxx
> Upload [] 100% 0.0s (4.45KB) [1 file]> Using Node.js 8.9.4 (default)
> Ready! https://xxx-xxx.now.sh [7s]
> Synced 1 file (4.45KB) [0ms] 
> Initializing…
> Building
> ▲ npm install
> ✓ Using "yarn.lock"
> ⧗ Installing 38 main dependencies…
> ✓ Installed 1206 modules [31s]
> ▲ npm run build
> > dashboard@1.0.0 build /home/nowuser/src
> > next build
> > Using external babel configuration
> > Location: "/home/nowuser/src/.babelrc"
> Total precache size is about 0 B for 0 resources.
> Total precache size is about 0 B for 0 resources.
> ▲ npm start
> > dashboard@1.0.0 start /home/nowuser/src
> > next start -H 0.0.0.0
> Deployment complete!
> Assigning alias xxx.xxx to deployment...
> xxx.xxx is a custom domain.
> Verifying the DNS settings for xxx.xxx (see https://zeit.world for help)
> Verification OK!
> Error! Unknown error: Error: The deployment is not ready yet
Error: The deployment is not ready yet
    at module.exports.Now.createAlias.alias.retry (/snapshot/now-cli/dist/now.js:4000:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by matheuss** [comment]
https://github.com/zeit/now-cli/issues/1115#issuecomment-366635489
