### ISSUE TITLE
Incorrectly interpreting negations in .npmignore

### ISSUE THREAD

**Issue by lukechilds** [vercel/vercel#848]
I have the following npmignore:

```
*
!src/**/*
```

e.g ignore everything apart from anything in `src`. This works with npm, however now only uploads  package.json and ignores the src directory so my app fails to start.

If I remove .npmignore now works as expected.

**Comment by lukechilds** [comment]
Just to update, adding:

```json
"now": {
  "files:": ["src"]
},
```

to package.json still only results in package.json being uploaded.

**Comment by lukechilds** [comment]
I also tried updating .npmignore to:

```
*
!src/**
```

And specifically adding the file:

```
"files:": ["src/index.js"]
```

However that also didn't work. This seems to contradict the docs: https://zeit.co/docs/features/configuration#"files"-(array)

**Comment by sholladay** [comment]
Did you try using package.json `files` property _instead of_ `.npmignore`? Sounds like you tried _in addition to_.

This works for me without any dotfiles:

```json
{
    "name": "my-package",
    "files": [
        "src"
    ]
}
```

That should deploy everything inside `src`.

**Comment by lukechilds** [comment]
I was on npm@4 due to issues with npm@5 which doesn't work properly with `files`. Just upgraded to npm@5 as I've heard it's much better now and updated to use `files`, although now has just failed on me (https://github.com/zeit/now-cli/issues/857) so I can't actually deploy to test.

**Comment by lukechilds** [comment]
Same issue on fresh Ubuntu VM with latest now :/

**Comment by lukechilds** [comment]
@sholladay I got `now` working again, can confirm just using `files` works. However this is still a bug.

Just `.npmignore` with:

```
*
!src/**
```

means `now` correctly interprets the `*` but doesn't apply the `!src/**`.

**Comment by Qix-** [comment]
@lukechilds Apologies for the delay - are you still seeing this problem?

**Comment by lukechilds** [comment]
Yep, still occurs.

**Comment by leo** [comment]
Thank you so much for the effort you have put into this issue! 😊 

However, since we completely re-worked the entire codebase of Now CLI and this issue does not apply to the new code anymore, I'm closing it now.

You can read more about our biggest release yet here: https://zeit.co/blog/now-2
