### ISSUE TITLE
now switch no longer accepts token

### ISSUE THREAD

**Issue by sholladay** [vercel/vercel#853]
Since Now 8,  it seems I cannot `now switch` to a team from a script, because `--token` is no longer respected.

I love the fact that `--team` was introduced 💕 but it is annoying and less maintainable to have to specify `--team` with every single command in the script (e.g. if our team name changes, more chance for mistakes). As far as I can tell, this shouldn't be necessary. I consider this a regression, personally, unless I am missing something. Let's keep it DRY.

## Before

Now 7.4.0:
```console
$ now switch my-team --token=$ZEIT_TOKEN
> Success! The team My Team is now active!
```

## After

Now 8.3.0:
```console
$ now switch my-team --token=$ZEIT_TOKEN;
> Error! This command doesn't work with "--token". Please use "--team".
```

**Comment by leo** [comment]
This is expected. We introduced `--team` because it's much more explicit. In terms of CI, you shouldn't use `now switch` - it's only meant to be used manually.

Also great to hear that you like the new flag! 😍
