### ISSUE TITLE
Tokens for teams

### ISSUE THREAD

**Issue by sholladay** [vercel/vercel#856]
This is a feature request to have API tokens that are scoped to a team rather than a user.

There are two main reasons:

1. This could eliminate the need for `--team` in some cases, which would be nice for CI (see #853). My deployment scripts are decidedly non-DRY and this would help.
    > In terms of CI, you shouldn't use now switch - it's only meant to be used manually

2. More importantly, if someone should get a hold of my token, I would prefer for damage to be limited to a given team, rather than all resources I have access to across every team.

I would suggest a format like `<my-team>_<rest-of-token>`.

**Comment by jhalborg** [comment]
Is there still no way of doing this?! :O Just upgraded my team account to a paid plan, only to discover there was no way of getting a token for the team as far as I can tell 😢

**Comment by rauchg** [comment]
We are going to prioritize this @jhalborg. Sorry for the delay.

**Comment by jamo** [comment]
@jhalborg you can still use the `-t` for token and `-T` for team name, for all CI etc setups. Or if you are using our API, you may provide team_id or team_slug query parameters to authenticate as team.

**Comment by leo** [comment]
I think implementing this makes a lot of sense!

**Comment by sigo** [comment]
@leo have we any progress? 🙏

**Comment by revskill10** [comment]
Without this feature, it seems impossible to integrate now with github actions to auto deploy on push.

**Comment by dmi3y** [comment]
Hi guys, is it still in progress? Any timelines?

**Comment by CalinaCristian** [comment]
Hey guys, maybe it helps, they added a --scope to now and now you can use --scope <team_name> https://zeit.co/blog/introducing-scope

**Comment by sholladay** [comment]
`--scope` is the same as `--team`, it just allows you to specify your own account instead of a team, if you want to. The token is not itself scoped, so if your token is compromised, all accounts and teams you have access to are also compromised.

**Comment by CalinaCristian** [comment]
Nevermind, just re-read the topic, yea. It would be great to just have team scope tokens . Sorry

**Comment by thebuilder** [comment]
Just leaving a vote for this. Working at an agency, it would be be nice to not have the token tied to a specific user.

- Each deploy is associated with the owner of the token. If a build was triggered by the CI, it would make much more sense to have the team listed as the one who triggered a deploy.
- Likewise each deploy creates a alias mapped the to owners username
- You'd need to replace tokens if the token owner resigns from the company

I guess the best solution for this right now is to create a dummy bot account, but i wouldn't consider that a longterm viable solution.

**Comment by leo** [comment]
Thank you for creating this issue!

Please note that – in order for us to be able to handle each feature request with care – we have to consume all of them through a unified pipeline that makes it easier for us to prioritize, track and progress on the features our user base is interested in.

In turn, the [Issues tab](https://github.com/zeit/now/issues) on this repository is best only be used for reporting bugs, which we can immediately act on.

For well-explained feature requests (like the one you just posted), please contact us at [support@zeit.co](mailto:support@zeit.co), so that we can consider adding it to our roadmap.

**Comment by 59023g** [comment]
Any updates here?

**Comment by sholladay** [comment]
They never added it to the roadmap. I gave up on using Now anyway. If you care about this, you'll have to email them.

**Comment by will-holley** [comment]
+1 to prioritize this.  Using a Vercel Team to manage environment variables and I need to sync them into a Github Actions CI environment.  Exposing a token which gives admin access to my personal Vercel projects is a non-starter.

**Comment by PaulRBerg** [comment]
Why has this been closed?

**Comment by swarnava** [comment]
For anyone looking for an update, we have released this: https://vercel.com/changelog/access-tokens-can-now-be-scoped-to-teams

**Comment by frdwhite24** [comment]
> Just leaving a vote for this. Working at an agency, it would be be nice to not have the token tied to a specific user.
> 
> * Each deploy is associated with the owner of the token. If a build was triggered by the CI, it would make much more sense to have the team listed as the one who triggered a deploy.
> * Likewise each deploy creates a alias mapped the to owners username
> * You'd need to replace tokens if the token owner resigns from the company
> 
> I guess the best solution for this right now is to create a dummy bot account, but i wouldn't consider that a longterm viable solution.

@thebuilder Did you ever find a solution to this? This issue is closed because they've added team scoping but we're experiencing the issues you're explaining in this comment, and would really love to find a good way to fix this! thanks in advance

**Comment by divmgl** [comment]
> Did you ever find a solution to this? This issue is closed because they've added team scoping but we're experiencing the issues you're explaining in this comment, and would really love to find a good way to fix this! thanks in advance

+1 on this. We're currently having to switch from building using Vercel Deploy Hooks to the Vercel CLI to avoid cases where merging pull requests rapidly to production causes the latest commit to be deployed, rather than the one that is currently being built.

However we can't switch to the Vercel CLI without providing a `VERCEL_TOKEN`, which means that it will now look like I am the one who is deploying every single time to Vercel. Not a huge issue, but I'd rather have team tokens for our organization.

**Comment by danLDev** [comment]
Any update on this? Similar to others above I'd like to be able to trigger deploys via GH Actions on GH Tags/Releases, however with the current setup it seems like all deploys are going to appear to have been triggered by me, which is not ideal for obvious reasons.

**Comment by jamo** [comment]
Why not create a service account/bot user for your Vercel team and run the CI deployments as that user?

**Comment by jonworek** [comment]
> Why not create a service account/bot user for your Vercel team and run the CI deployments as that user?

I haven't tried it yet, but I had a similar thought and suspect that might work. Though I'm assuming that with at least the pricing plan that I'm on, that would require an extra $20/mo. But if the extra cost is not a concern, I'm guessing it should work.

**Comment by michaelhays** [comment]
This should really be re-opened, since you still cannot create an API Token on behalf of a team, and it's a pretty necessary feature for many workflows.

**Comment by nvegater** [comment]
I am the owner/creator of a team and own the account that created the team, I need a token to automate with GH Actions. I cant find how to generate a token that has access to team resources (env vars specifically, vercel pull not working). Anyone knows how to do that? I think is not possible.

Its crazy that I have less features in the team paid mode than in the personal free mode.
