### ISSUE TITLE
Unexpected error. Please try again later. (search_.map is not a function)

### ISSUE THREAD

**Issue by lukechilds** [vercel/vercel#857]
Keep getting this error:

```
$ now --version
8.3.1
$ now
> Deploying ~/Dev/oss/test under lukechilds
> Error! Unexpected error. Please try again later. (search_.map is not a function)
```

**Comment by lukechilds** [comment]
Possibly caused by this: https://github.com/zeit/now-cli/blob/1134f65cdaae19a62f9656c17af981a4f37e91c6/src/providers/sh/util/get-files.js#L92

**Comment by lukechilds** [comment]
Oh, also:

```
$ now --version
8.3.1
```

**Comment by lukechilds** [comment]
I've tried rebooting, installing multiple different `now versions` (back to 7) and even nuked `~/now.json` and `~/.now`. Still getting the same error.

**Comment by lukechilds** [comment]
Same issue on fresh Ubuntu VM with latest now :/

**Comment by lukechilds** [comment]
Fixed, I was using `files` as a string instead of an array in package.json. This seems to work with npm but is undocumented, it was killing `now` as it expects an array.

I've updated my package.json to use an array but submitted a PR so now can handle this edge case without dying.

**Comment by leo** [comment]
Fixed in https://github.com/zeit/now-cli/pull/858
