### ISSUE TITLE
Google's Puppeteer doesn't work in now.sh

### ISSUE THREAD

**Issue by cazala** [vercel/vercel#861]
When trying to run [Google's Puppeteer](https://github.com/GoogleChrome/puppeteer) on now it throws the following error

```
> (node:185) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Failed to launch chrome!
> /home/nowuser/src/node_modules/puppeteer/.local-chromium/linux-497674/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
> TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md
> (node:185) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

**Comment by TooTallNate** [comment]
Hey @cazala, can you share with me the code you are trying to deploy or a Now deployment URL?

**Comment by cazala** [comment]
**package.json**

```json
{
  "name": "test-puppeteer",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "node ."
  },
  "dependencies": {
    "express": "^4.15.4",
    "puppeteer": "^0.10.2"
  },
  "engines": {
    "node": "8.1.2"
  }
}
```

**index.js**

```js
var Express = require('express');
var puppeteer = require('puppeteer');
var app = new Express();

var isWorking = 'nope';

app.get('/', (req, res) => res.send('<div id="test">yes</div>'));
app.get('/test', (req, res) => res.send(isWorking));

app.listen(3000, async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('http://localhost:3000');
  isWorking = await page.evaluate(() => document.getElementById('test').innerHTML);
  await browser.close();
});
```

`npm start` and go to `http://localhost:3000/test` you should see `yes` (that string comes from accessing `http://localhost:3000` and extracting it from the content of the page)

here is the deployment: https://test-puppeteer-rslpmwquck.now.sh/

as you can see if you go to https://test-puppeteer-rslpmwquck.now.sh/test it says `nope`, because it is failing to launch puppeteer.

**Comment by TooTallNate** [comment]
So I looked into this a bit. Currently it doesn't seem like Puppeteer works on Alpine Linux (see https://github.com/GoogleChrome/puppeteer/issues/379), so you'll have to use a Dockerfile with a debian-based image for now.

**Comment by leo** [comment]
👍 Please use a Docker deployment... 😊

**Comment by revolunet** [comment]
hi, anyone has a working Dockerfile for pupetteer on now.sh please ?

**Comment by revolunet** [comment]
Found one : https://github.com/cheeaun/puppetron/blob/master/Dockerfile

**Comment by styfle** [comment]
Please see this blog post for Now 2.0: https://zeit.co/blog/serverless-chrome
