### ISSUE TITLE
Desktop app keeps asking for permission on a daily basis (macOS High Sierra)

### ISSUE THREAD

**Issue by Dids** [vercel/vercel#870]
I'm running the latest now desktop app on macOS High Sierra (GM) and seeing daily permission prompts from the app, most likely due to new CLI releases.

I'm not sure if this is an issue or a feature, but each update triggers two permission prompts (which require a password), and I'm definitely not seeing this on my other Mac, which is running macOS Sierra.

**Comment by leo** [comment]
Can you try `chmod +x /usr/local/bin`? :blush: If it doesn't work, please report [here](https://github.com/zeit/now-desktop).

**Comment by modermo** [comment]
Was this fixed? I'm getting the same thing.

**Comment by leo** [comment]
@modermo Did you fix your directory permissions?

**Comment by leo** [comment]
Actually, this is the wrong repo if you want to re-open it. => zeit/now-desktop

**Comment by Dids** [comment]
Also to update that chmod didn't fix it for me. I eventually reinstalled High Sierra, after which it worked properly.
