### ISSUE TITLE
now logs --follow doesn't follow

### ISSUE THREAD

**Issue by yodertv** [vercel/vercel#871]
I'm no longer getting the _tail -f_ behavior with _now logs -f_. This occurred when I upgraded to now 2.5.5 mac binary, and now 8.3.4 on the command line. I was using this successfully in past versions. zeit deployed app is running just fine, too. thanks,

**Comment by yodertv** [comment]
I've learned that this behavior is limited to the alias. Seems to be working on the instance name directly.

**Comment by tamagokun** [comment]
same, if I use `-f` I get nothing back, if I leave it off, it seems to work. Using 8.3.5

**Comment by yodertv** [comment]
Follow this issue at [https://github.com/zeit/now-cli/issues/892](url)

**Comment by Qix-** [comment]
![image](https://user-images.githubusercontent.com/885648/32667371-635731a2-c5ef-11e7-95e4-2a94271ed4ca.png)

Apologies for the delay - this appears to have been fixed.

Please comment back here if that's not the case :) Thanks for bringing it up!
