### ISSUE TITLE
Unable to deploy - Error - No open port found. Make sure 'npm start' creates an HTTP server on a port (any).

### ISSUE THREAD

**Issue by ghost** [vercel/vercel#873]
URGENT - No open port found. Make sure 'npm start' creates an HTTP server on a port (any).
This string is repeated over and over, is there anyway to stop and remove the deploy ?

**Comment by leo** [comment]
`now rm <deployment>` 😊

**Comment by ghost** [comment]
The deployment is stuck at "BUILDING" and won't let me remove that way :(

It's been like this for an hour, no timeout


[image: LearnUpon]
David Bryant
Account Manager

Email:
david@learnupon.com

Phone:

+61 283 111 209 <+61283111209>

Web:
www.learnupon.com

Twitter:

@learnupon <https://twitter.com/learnupon>

Discover why customers love LearnUpon <https://www.learnupon.com/customers/>
.

**Comment by ghost** [comment]
NVM Got it :) Thank you for your help!


[image: LearnUpon]
David Bryant
Account Manager

Email:
david@learnupon.com

Phone:

+61 283 111 209 <+61283111209>

Web:
www.learnupon.com

Twitter:

@learnupon <https://twitter.com/learnupon>

Discover why customers love LearnUpon <https://www.learnupon.com/customers/>
.
