### ISSUE TITLE
Friendly error message for aliasing to nested subdomains

### ISSUE THREAD

**Issue by nkzawa** [vercel/vercel#875]
```
> Error! Unknown error: Error: The supplied alias "foo.bar.now.sh" is not a valid hostname. Make sure it excludes http:// and slashes
```

The error happens when you add aliases by `now alias` with settings in `now.json`.
I think we should display a more friendly message ~~if we don't support nested subdomains~~ (we don't support it).

**Comment by ppatel221** [comment]
Hey, im a student in an open source class looking to contribute to an open source project. Is it okay if i work on this?

**Comment by leo** [comment]
@ppatel221 Sure! Would be awesome 😊

**Comment by ppatel221** [comment]
Any tips on how to get started with this?
