### ISSUE TITLE
External domain with MX records

### ISSUE THREAD

**Issue by jsantell** [vercel/vercel#878]
I currently have a domain hosted configured to point to a VPS for hosting via A record, and also used with an external email provider via an MX record. I'd like to switch over fully to zeit hosting, but have concerns on the best way to do this. All this considering minimizing downtime for email.

I could keep my provider's name server and add a CNAME to zeit.world, or an A record pointing to a zeit world IP address, but [CNAME and MX records for email cannot coexist](http://email-museum.com/2008/09/08/why-you-shouldnt-mix-cname-and-mx/), and adding an A record still requires the addition of a CNAME/ALIAS record (my provider doesn't have ALIAS records, and I'm unsure if ALIAS conflicts with MX records the same way as CNAME).

I could use zeit.world name servers, and attempting to configure them as an external domain (now listed in my `now domains ls`), but even after adding the TXT record, it still requires updating the name servers to point to zeit.world before modifying the DNS records, so I'd have email downtime when the name servers resolve to zeit, and before I can add the appropriate MX records, and unclear as well whether or not this requires a CNAME, and no notification when this change occurred to add the new records.

Having read the [alias](https://zeit.co/docs/features/aliases) and [DNS](https://zeit.co/docs/features/dns) docs, it's unclear how to achieve this without downtime, any guidance?

**Comment by jsantell** [comment]
Ended up solving this with some help from Tim in chat, and ultimately using the ALIAS record alongside the MX record, thanks!

**Comment by shanedroid32** [comment]
I realize this is closed, but I am having the same problem and getting it resolved on my own isn't happening as quickly as I'd like. Is there any chance you could elaborate how you resolved this issue? Thanks.

**Comment by OlliV** [comment]
I'm not sure whether this is what you want to do?

```
$ now dns add zeit.rocks mail MX mail.zeit.rocks 10
$ now dns add zeit.rocks mail ALIAS alias.zeit.co
```

**Comment by jsantell** [comment]
I ended up pointing my domain to zeit's nameservers and having an MX record for my email hosting and using an ALIAS record (on the root, very similar to https://github.com/zeit/now-cli/issues/878#issuecomment-333835616 except `now dns add zeit.rocks @ ALIAS alias.zeit.co`)
