### ISSUE TITLE
cant write to file EACESS permission denied

### ISSUE THREAD

**Issue by nati-alvarez** [vercel/vercel#879]
I made a chat app that stores users chat history in .json files, but my app can't write to the .json files. I get this error: 

```
{                Error: EACCES: permission denied, open 'chatlogs/chatlogce62ca62-6c22-44d5-9220-
                  ac1438824ec4.json'
                  errno: -13,
                  code: 'EACCES',
                  syscall: 'open',
                  path: 'chatlogs/chatlogce62ca62-6c22-44d5-9220-ac1438824ec4.json'
 }
```

Is there any way to let my app write to the chatlogs directory? Thanks in advance.

**Comment by TooTallNate** [comment]
Hey @nati-alvarez. The filesystem is only writable from the `/tmp` directory after the deployment has started. Please see: https://zeit.co/docs/deployment-types/node#file-system-specifications

You might want to consider writing the logs to an external database of some kind.

**Comment by nati-alvarez** [comment]
@TooTallNate  Ok, I guess I'll have too. Thanks.
