### ISSUE TITLE
now alias is quite inconsistent in error messaging

### ISSUE THREAD

**Issue by koresar** [vercel/vercel#881]
Please take a look at this picture.

1) I have a Free plan, but also I was able to buy a domain 4 months ago. Your [pricing page](https://zeit.co/pricing) is saying - NO DOMAINS. How come I bought a custom domain on a Free plan?

2) First `now alias` attempt results in `DNS Configured! Verifying propagation…` and then `Error!`
3) Second attempt - `Error! Please make sure that your nameservers point to zeit.world.`. However, they do point.
4) Third attempt - `Error! Custom domains are only enabled for premium accounts.`. Why you are telling me that information so late?

Looks like I have to buy "Premium".

It would be good if you could check plan before aliasing a custom domain. Thank you.

<img width="565" alt="zeit alias" src="https://user-images.githubusercontent.com/1622575/30779464-e83a2c9c-a134-11e7-819c-fa15b57fa6a5.png">

**Comment by leo** [comment]
Agreed. Any help is welcome!

**Comment by TooTallNate** [comment]
Closing due to age, and the fact that custom domains are no longer a premium feature. Please open a new issue if there are still inconsistencies!
