### ISSUE TITLE
now logs -n seems to be ignored 

### ISSUE THREAD

**Issue by Obiwarn** [vercel/vercel#884]
now logs -n 5000 my-api.now.sh

gives me only 1000 lines of logs.

**Comment by leo** [comment]
I think we're moving old logs away, @Qix-?

**Comment by Qix-** [comment]
@rauchg can you please comment the goals here?

**Comment by nkzawa** [comment]
This is because the number of logs are limited on the API endpoint for now. We should describe it on help message. We can support steaming logs and make the limit higher but would need a limit anyway IMO.

**Comment by leo** [comment]
This probably isn't true for Now 2.0 anymore, is it? @nkzawa

**Comment by nkzawa** [comment]
Closing since there are only 1000 logs per deployment/path on Now 2.0.
