### ISSUE TITLE
Missing support for custom domains in `now logs -f`

### ISSUE THREAD

**Issue by ahadjeres** [vercel/vercel#892]
I am able to use the `now log` to print the logs in my terminal but it does not work when I use the `-f` follow option. When I activate the `-d` debug option this is the output:

CMD: `now log -d -f mydomaine.com`.
result : `> [debug] Socket connected 
              > [debug] Socket disconnect`

**Comment by leo** [comment]
Just verified that this is only the case for custom domains!

**Comment by yodertv** [comment]
@leo Here's a duplicate issue [https://github.com/zeit/now-cli/issues/871](871)

**Comment by leo** [comment]
Closed as a duplicate of #871
