### ISSUE TITLE
Pointing nameserver: Denic: [ERROR: 116 SOA record response must be authoritative (resolver\, answer)

### ISSUE THREAD

**Issue by Kiechlus** [vercel/vercel#90]
Trying to follow https://zeit.co/world and pointing my domain _fkmt.de_ to the [...].zeit.world nameservers I get the following errors from my registrar:

`ERROR: 53300102912 Nameserver error [ERROR: 116 SOA record response must be authoritative (resolver\, answer) (frankfurt.zeit.world./91.109.245.139:53 (UDP\, Timeout: 3s\, Retry: 1 x 0s\, NO DNSSEC\, ignore TC\, via local interface \[IPv4: nast-17-out.prod.denic.de/10.121.46.35|IPv6: /2a02:568:101:214:0:0:1:14\])\, frankfurt.zeit.world./91.109.245.139:53 (UDP\, Timeout: 3s\, Retry: 1 x 0s\, NO DNSSEC\, ignore TC\, via local interface \[IPv4: nast-17-out.prod.denic.de/10.121.46.35|IPv6: /2a02:568:101:214:0:0:1:14\]): <No records>)]`

Found two similar cases [1] [2]: 

> Worked it out. It's a "catch 22".
> Our hosts won't let us add a domain to our account, until the domain is pointing to it's name servers - for security mostly.
> But denic won't let you point a domain to your account, until it's setup to accept it.

This means I cannot use the zeit.world DNS service for _.de_ domains?

[1] http://www.devnetwork.net/viewtopic.php?f=31&t=137755#p685423
[2] https://www.df.eu/forum/threads/61601-Externe-Domain-kann-nicht-konfiguriert-werden?s=ffd8e04a734b93fa5db5c684fd79af48&p=400985&viewfull=1#post400985

**Comment by OlliV** [comment]
Currently it's possible by using [now-client](https://github.com/zeit/now-client) but we should probably add some way to force it on the command line client as well.

If you don't want to use now-client, another possibility is to use just plain curl in the same way as now-client is accessing the API:

``` bash
curl -H "Authorization: Bearer [TOKEN]"  -d '{"name":"yourdomain.co"}' "https://api.zeit.co/now/domains"
```

Where `[TOKEN]` is the token from `~/.now.json`

**Comment by Kiechlus** [comment]
Ok. I'm currently playing with it but that seems to be a paid feature.

Curl output:

`{"error":{"code":"custom_domain_needs_upgrade","message":"Domain name creation requires a premium account."}}`

**Comment by OlliV** [comment]
Yes, in fact. https://zeit.co/now#pricing
