### ISSUE TITLE
Error when trying to purchase a custom domain

### ISSUE THREAD

**Issue by rawgroundbeef** [vercel/vercel#902]
I'm experiencing the following:

```
now alias https://x.now.sh xyz.lol
Purchase? [y/N]
Error! `name` is not defined
```

Node version v8.4.0

**Comment by oliverbytes** [comment]
I'm getting the same error.... Any solution to this?

**Comment by Qix-** [comment]
Hi - can you update to the latest client and test again? I feel like we've fixed this :)

**Comment by oliverbytes** [comment]
I was able to purchase already. It seems fixed. thanks a lot!

**Comment by hsavit1** [comment]
still happens for me @Qix- @leo
