### ISSUE TITLE
Typo in logging output while deploying

### ISSUE THREAD

**Issue by pqvst** [vercel/vercel#903]
I just noticed that my CLI showed this line while deploying:
> Sending build context to Docker daemon 2.266 **MBkB**

I'm guessing **MBkB** is a typo/bug, unless that's some new unit I've never heard of before?

But I think this is an issue in the API/backend since I can't find that log line in *this* repo. Could someone confirm?

**Comment by matheuss** [comment]
Interesting – that comes Directly from Docker. Could you share a deployment that produced such logs so I can take a look? I just want to make sure we're not messing up with something.

**Comment by pqvst** [comment]
I've PMed you my deployment on Slack. I did a quick Google search (docker + "mbkb") and found some other references to MBkB in log outputs.

**Comment by Qix-** [comment]
Going to close this as it's a bug in docker 🐳 

Feel free to open an issue over there and link back to this for visibility :)
