### ISSUE TITLE
Verifying nameservers…

### ISSUE THREAD

**Issue by alexverdaguer** [vercel/vercel#905]
After more than 24h still seeing Error! Please make sure that your nameservers point to zeit.world.

https://www.whatsmydns.net/#NS/manguerasytubos.es is ok !

I have this issue with 2 domains.

Cheers !

**Comment by OlliV** [comment]
Hi,

.es domains currently require manual verification from our side. Add the domains with `now domain -f <domain.tld>` and let me know either here, sending an email to our support, or in slack.

**Comment by alexverdaguer** [comment]
Hi OlliV,

Worked like a charm. Best place to host our Apps !
Thank you !

**Comment by amio** [comment]
@OlliV Does `.im` domain need manual verification too?

**Comment by OlliV** [comment]
Not to my knowledge but if you have any issues with that TLD don't hesitate to contact either our support or me directly by email.
