### ISSUE TITLE
Unable to add mx records ("invalid MX priority")

### ISSUE THREAD

**Issue by trotzig** [vercel/vercel#907]
I'm trying to set up mx records for my domain `happo.io`, pointing to google servers. On using the `now dns add` command, I'm getting this error: 

```
now dns add happo.io @ MX ASPMX.L.GOOGLE.COM 1
> Error! Unexpected error. Please try again later. (Invalid priority given for an MX record)
```

I've tried other priorities as well (0, 10, 20, etc) and they all result in the same error. I've [reached out to folks in the zeit-community slack channel](https://zeit-community.slack.com/archives/C1TMPLCKS/p1507150386000010) but I haven't had any responses.

**Comment by trotzig** [comment]
I noticed a recent commit by @timneutkens (13fd546f8bd9) changing the example for `dns now add` to include quotes around the `@`. I've tried that too, same result:

```
⨠ now dns add happo.io '@' MX ASPMX.L.GOOGLE.COM 1
> Error! Unexpected error. Please try again later. (Invalid priority given for an MX record)
```

**Comment by matheuss** [comment]
What version of the CLI you are running? I recently fixed this here: https://github.com/zeit/now-cli/commit/86deb0a1c6140d5a73d5ff61ddc147bdf98f08cc

![image](https://user-images.githubusercontent.com/4721750/31216468-0b264240-a9b4-11e7-8009-b4abda40a810.png)

**Comment by trotzig** [comment]
Ah, embarrassing. I was on 8.2.2. I was assuming the Now desktop app would keep me up-to-date, but it turns out I had manually installed `now` a while back using `npm install -g now`. Using the latest version works just fine, thanks for the quick response. 👍

**Comment by matheuss** [comment]
Hmmm that's not expected – Now Desktop should keep you updated! cc @leo could you take a look please

**Comment by trotzig** [comment]
I'm using `nodenv` which might be relevant to this discussion.
