### ISSUE TITLE
now alias fails for AWS Route 53

### ISSUE THREAD

**Issue by rhlsthrm** [vercel/vercel#912]
```
> test.<MY_DOMAIN>.com is a custom domain.
> Verifying the DNS settings for test.<MY_DOMAIN>.com (see https://zeit.world for help)
> Error! Unknown error: Error: Verification required: Please add the following TXT record on the external DNS server: _now.<MY_DOMAIN>.com: eddcd0.................a153d9dda9fd92482150
```

The error message is clear, but how exactly do I configure the text record? Do I add it for the top-level domain or subdomain? Is the _now.<MY_DOMAIN>.com included in the text record?

**Comment by OlliV** [comment]
The top-level domain and only the token in the record.

**Comment by marko999** [comment]
this doesn't work for me... 
I have added TXT record for a top domain <mydomain>.ai and in value I have put the token from that error message but still cannot verify

**Comment by jamo** [comment]
Can you correctly see the the value with e.g `dig`: `dig _now.yourdomain.ai TXT +short`


E.g. with my personal domain:
```
$ dig _now.jarmoisotalo.com TXT +short
"fb4bac214f44487a21b80d5b1a72cf2a0e0fca63df902021c8d09a42ad0a04a1"
```

**Comment by marko999** [comment]
Yes, I can see the token when I run the command
