### ISSUE TITLE
"Now" server not passing all the headers from the express server

### ISSUE THREAD

**Issue by praneshr** [vercel/vercel#916]
I've a `express` server which streams html files. But, the `Transfer-Encoding:chunked` header is not passed to the client.

**Comment by jamo** [comment]
I'll look more into it, the initial understanding is that we are acting per [rfc 2616](https://tools.ietf.org/html/rfc2616#section-13.5.1) as `transfer-enconding` is a hop-by-hop header as per so dropping it should be safe.

**Comment by Qix-** [comment]
@praneshr Could you expand a bit on your particular use-case?

**Comment by jamo** [comment]
As per [PFC2616](https://tools.ietf.org/html/rfc2616#page-92) we don't forward hop-by-hop headers

**Comment by praneshr** [comment]
Fixed this issue. thanks @jamo @Qix-
