### ISSUE TITLE
It does not delete a group of deployments with quotation marks in the name.

### ISSUE THREAD

**Issue by aranajhonny** [vercel/vercel#917]
![screenshot_4](https://user-images.githubusercontent.com/9091881/31309480-3772f46a-ab5d-11e7-9eef-6b05af803718.jpg)

**Comment by Qix-** [comment]
Hi there :wave:

We don't recommend putting quotations in the name, to start. It usually ends up causing confusion, like what you're seeing. :)

Can you try `now rm '"piuma"'`? Note that that is `"piuma"` wrapped inside single-quotes -- `'"piuma"'`.

**Comment by aranajhonny** [comment]
ok.
