### ISSUE TITLE
Make XO happy

### ISSUE THREAD

**Issue by leo** [vercel/vercel#92]
Let's make the project comply to [these rules](https://github.com/zeit/now/blob/master/package.json#L44) (so that we can stop overriding them):

- [ ] import/no-unassigned-import
- [ ] import/no-dynamic-require
- [ ] max-depth
- [ ] no-use-before-define
- [ ] complexity
- [ ] no-control-regex

When opening a PR for one of these, please call it:

> "Comply to rule "max-depth"

**Comment by sindresorhus** [comment]
Tip: `$ xo --fix` might able to auto-fix some of these issues.

**Comment by leo** [comment]
@sindresorhus Already did that! 😊

**Comment by leo** [comment]
✔️
