### ISSUE TITLE
now alias ls gives "Could not match path alias for"

### ISSUE THREAD

**Issue by AndreyNikiforov** [vercel/vercel#922]
`now --version`
> 8.3.10

`now alias ls my-app-obfuscated.now.sh`

**Gives:**

> Error! Could not match path alias for: my-app-obfuscated.now.sh

**Expected:**

List rules for alias

**Notes:**

`now alias ls`
lists my-app-obfuscated.now.sh as an alias for one of the deployments

Any help would be appreciated

**Comment by Qix-** [comment]
Hi there - could you upgrade to the latest `now` and try again?

**Comment by leo** [comment]
Closing, since no response in a year.
