### ISSUE TITLE
`Error! Unexpected error` when the error is in the message

### ISSUE THREAD

**Issue by jamo** [vercel/vercel#923]
›$ now certs create domain.com
> Error! Unexpected error. Please try again later. (You don't have access to "domain.com")

**Comment by jamo** [comment]
I guess this falls to the same category: `> Error! Unknown error: Error:`
```
> Error! Unknown error: Error: Verification required: Please add the following TXT record on the external DNS server: _now.myfancydomain.com: xxxxxxxxxxxx
```

**Comment by OlliV** [comment]
This was discussed a while back and the current error message format we have now in place was IIRC decided to be ok.
