### ISSUE TITLE
Order get's mixed up when now-rm multiple instances 

### ISSUE THREAD

**Issue by jamo** [vercel/vercel#927]
If I run `now rm url1 url2 ... urln` with deployment urls that are sorted by date (copied from `now list output)

The verification question changes the order deployments:
<img width="664" alt="" src="https://user-images.githubusercontent.com/1354151/31510259-dec94dd0-af8c-11e7-836e-4db9afc312ba.png">

And then the output of deleted apps list IDs instead of urls.
<img width="321" alt="" src="https://user-images.githubusercontent.com/1354151/31510307-faa06610-af8c-11e7-8537-2aff99641e2d.png">

**Comment by leo** [comment]
@jamo Just btw, you can do `now rm <app-name>`

**Comment by Qix-** [comment]
Is this a platform issue, or a client issue?

**Comment by OlliV** [comment]
Seems like a client bug.

**Comment by leo** [comment]
Yep, we should definitely order them correctly.

**Comment by leo** [comment]
Closing this, as we're focusing on becoming better at hosting websites now!
