### ISSUE TITLE
Cannot get external domain aliased

### ISSUE THREAD

**Issue by sbstnmsch-zz** [vercel/vercel#930]
I have problems getting my external domain `ilike.to` to work with Now and Zeit.World.

What I've done so far:
- Followed all steps in https://zeit.co/docs/features/aliases
- Added and verified my domain using the TXT record
```
$ now domains ls
> 1 domains found under sbstnmsch [840ms]

  domain       dns       verified  created
  ilike.to     external  true      3d ago
```
- Pointed my domain (former hosted on checkdomain.de) to Zeit.World London, Frankfurt, California AND Singapore:
```
$ dig ns ilike.to

; <<>> DiG 9.8.3-P1 <<>> ns ilike.to
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 171
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 4

;; QUESTION SECTION:
;ilike.to.                      IN      NS

;; ANSWER SECTION:
ilike.to.               6071    IN      NS      london.zeit.world.
ilike.to.               6071    IN      NS      frankfurt.zeit.world.
ilike.to.               6071    IN      NS      california.zeit.world.

;; ADDITIONAL SECTION:
california.zeit.world.  2055    IN      A       173.255.215.107
frankfurt.zeit.world.   2471    IN      A       91.109.245.139
london.zeit.world.      59516   IN      A       178.62.47.76
london.zeit.world.      59516   IN      AAAA    2a03:b0c0:1:d0::db:e001

;; Query time: 329 msec
;; SERVER: 10.144.0.1#53(10.144.0.1)
;; WHEN: Fri Oct 13 11:14:49 2017
;; MSG SIZE  rcvd: 182
```
- Here I see `Singapore.zeit.world` is missing completely?!
- No authorities in `dig` answer
- I did that 3 days ago and the domain has still not propagated globally
- No A-Records https://www.whatsmydns.net/#A/ilike.to
- Only ~50% NS-Records https://www.whatsmydns.net/#NS/ilike.to pointing to Zeit.World servers, others unknown
- Asked the support of my former domain hoster and they said something seems misconfigured with Zeit.World
- I tried aliasing my deployment to my external domain and get certificate errors:
```
$ now alias iliketo-cnzqtnxxjf.now.sh ilike.to
> ilike.to is a custom domain.
> Verifying the DNS settings for ilike.to (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for ilike.to
> Error! Unknown error: Error: Invalid challenge response for ilike.to. Make sure the DNS records are correct.
Error: Invalid challenge response for ilike.to. Make sure the DNS records are correct.
    at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:906:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

I googled around, found others with similar problems (#459 #566), though some of them resolved it by just waiting. I asked in the Slack-Channel #now - but no resolution so far.

I think there is something wrong here.

**Comment by sbstnmsch-zz** [comment]
Additionally when I try to manually create certificates:
```
$ now certs create ilike.to
> Error! Unexpected error. Please try again later. (Invalid challenge response for ilike.to. Make sure the DNS records are correct.)
```
I'm no DNS expert - but as `now alias` says DNS settings are OK, which one of `now alias` and `now certs create` is lying ;-)

**Comment by OlliV** [comment]
This is happening if http traffic is not getting to our proxies.

https://zeit.co/docs/features/dns#adding-a-domain-using-external-nameservers

**Comment by alexpriceco** [comment]
> "This is happening if http traffic is not getting to our proxies."

@OlliV, what does that mean? I didn't understand that doc's relation to the issue. 😕
(I'm also having this issue)

**Comment by OlliV** [comment]
@alexpriceco are you using zeit.world or an external namerserver?

**Comment by alexpriceco** [comment]
Hey @OlliV, after my third try (started with zeit.world, then gave external a shot, then back to zeit.world), running `now dns ls` actually returned some records. Previously I'd just get errors after the "Verifying the DNS settings" step.

Not sure what changed that made things work out, but it looked like that previous times I tried, dns records weren't being created for the domain I was trying to alias to. ¯\_(ツ)_/¯
