### ISSUE TITLE
Cannot deploy ES6 index.js with now

### ISSUE THREAD

**Issue by StrikoMirko** [vercel/vercel#937]
Hi,

I am having difficulties trying to deploy a next.js app with now.
My main file is index.js which is written using ES6 and I get error message:
`Unexpected token import`
How can I deploy my next.js app?

thank you.

**Comment by leo** [comment]
The ES2015 module syntax is not yet supported by the latest version of Node.js - this is not related to our platform. Please make sure to transpile the code to make it work 😊

**Comment by leo** [comment]
Next.js should do that by default, but maybe the configuration is wrong.

**Comment by StrikoMirko** [comment]
Sorry I just saw this response.

My error was that I was using micro for the start script instead of the next start.
Documentation for now confused me a little bit.

Thanks anyway.
