### ISSUE TITLE
Now desktop app does not open

### ISSUE THREAD

**Issue by alansouzati** [vercel/vercel#943]
I'm new to Zeit and I'm currently evaluating it.

I'm trying to deploy this [simple branch](https://github.com/grommet/grommet-site/tree/zeit) but I get this error:

> Error! Unexpected error. Please try again later. (Unexpected response)

Also, I'm trying to install the Now desktop app for Mac and there is nothing I can do to open it. I've moved it to Applications and I click on it and no feedback at all.

**Comment by leo** [comment]
We're experiencing problems on our platform right now. More details [here](https://twitter.com/zeit_status).

Sorry for the inconvenience caused!
