### ISSUE TITLE
auth.json is world readable 

### ISSUE THREAD

**Issue by chids** [vercel/vercel#949]
👋,

1. Installed `now` via `npm install -g now`
2. Ran `now login` and verified via the received e-mail
3. `ls -lart ~`
   * `drwxr-xr-x    2 my-user  staff        136 Oct 26 01:44 .now`
3. `ls -lart ~/.now`
   * `-rw-r--r--   1 my-user  staff   189 Oct 26 01:46 auth.json`

_(I'm on macOS if that matters)_

**Comment by rauchg** [comment]
@chids great find. We'll have this corrected ASAP
