### ISSUE TITLE
Trying to a secret with the same name as an existing secret fails

### ISSUE THREAD

**Issue by vjpr** [vercel/vercel#950]
```
now secrets add site-password "blah blah"
> Error! Unexpected error. Please try again later. (An unexpected internal error occurred)
```

**Comment by leo** [comment]
It should fail, that's expected. You can only have one secret with the same name, because they're global in your team/user account... :blush: 

What we can do is improve the error message!

**Comment by sloria** [comment]
Just ran into this when trying to update the value of a secret. Is there a way to update a secret without having to `rm` then `add` again?

**Comment by pedrolucasp** [comment]
@leo Was this issue fixed? 
As today (10/07/2018), the console outputs `Error! The secret name "my-secret" already exists for this user`.

**Comment by reaktivo** [comment]
Just came here with the same issue: having a way to update a secret value without removing it would be kindly appreciated.

**Comment by leo** [comment]
Closing in favor of https://github.com/zeit/now-cli/issues/1058
