### ISSUE TITLE
Age is displayed incorrectly in now ls

### ISSUE THREAD

**Issue by AndyBitz** [vercel/vercel#951]
While executing `now ls` I noticed that the age of a deployment I just made was displayed wrong.
I guess that the time gap between deploying and executing `now ls` was too small, therefore the age value was too small for the cli to handle it.

![6e1005ce-12b5-431f-bfb0-ff6a9902e9f7](https://user-images.githubusercontent.com/16088670/32147466-f0b25dee-bce7-11e7-8050-98a52f0fbe86.jpg)

**Comment by Qix-** [comment]
@leo is this a platform bug or CLI bug?

**Comment by OlliV** [comment]
This is due to the local clock drifting or perhaps the other way around. Anyway either the client's clock is in the past or the server's clock is in the future. Timekeeping sucks.
