### ISSUE TITLE
now domains rm fails to delete resources

### ISSUE THREAD

**Issue by rgbkrk** [vercel/vercel#952]
I'm attempting to migrate a domain from my personal account to a team account. Since I was told that zeit could not transfer the domain and resources for me, I've had to go the `now domains rm` route.

```
$ now domains rm nteract.io
> The following domain will be removed permanently
  https://nteract.io      400d ago
> Warning! This domain's 2 aliases will be removed. Run `now alias ls` to list them.
> Warning! This domain's 2 certificates will be removed. Run `now cert ls` to list them.
> Are you sure? [y/N] y
> Error! The following certificates must be removed before removing the domain: slack.nteract.io, nteract.io
> More details: https://err.sh/now-cli/undefined
```

`now` gives the impression that it's going to delete the aliases and the certificates, then fails. I previously went through support / chat last time this happened, and was told the issue was fixed after some time. I had even tried manually deleting some resources.

**Comment by rgbkrk** [comment]
It appears that it takes some amount of time to do the alias and cert deletion, at least, longer than `now domains rm` waits for.

**Comment by rauchg** [comment]
We noticed this issue earlier today and it's in the process of being fixed. Thanks for the report @rgbkrk

**Comment by rgbkrk** [comment]
Ok, cool. I'm documenting some of it as I go in https://github.com/nteract/nteract.io/issues/34, since I'm running into other issues (which I can only assume is waiting on DNS propagation).

**Comment by rgbkrk** [comment]
I've been able to switch the owner of the domain, I can't do aliasing or create certs though:

```
$ now alias https://nteractio-fqzdqjnvmd.now.sh https://nteract.io
> nteract.io is a custom domain.
> Verifying the DNS settings for nteract.io (see https://zeit.world for help)
> Verification OK!
> Provisioning certificate for nteract.io
> Error! Unknown error: Error: Invalid challenge response for nteract.io. Make sure the DNS records are correct.
Error: Invalid challenge response for nteract.io. Make sure the DNS records are correct.
    at module.exports.EventEmitter.createCert.domain.retry (/snapshot/now-cli/dist/now.js:906:15)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

Is there any way to get insight into this?

**Comment by rgbkrk** [comment]
~~We're currently in outage mode for this, since now the domain is transferred but we can't provision certificates. Since I realize this is likely DNS related, I'm going to let this sit for an hour. If there's any amount of transparency from zeit that I could glean, it would help ease my concerns and wait for DNS to resolve. If I haven't heard back and it doesn't work in an hour to do a `now alias`, I'm going to run a script to try every minute to alias `https://nteractio-fqzdqjnvmd.now.sh` to `https://nteract.io`. Same will apply for our slack inviter and eventually other services...~~

We were able to alias just now, so we're all set. Thanks for `now`!

**Comment by rgbkrk** [comment]
It seems that the core issue around this may have been addressed (though I think the `undefined` error should probably be rooted out). Closing for now. Thanks all!
