### ISSUE TITLE
Prettier codebase?

### ISSUE THREAD

**Issue by pranaygp** [vercel/vercel#955]
Any thoughts on using [Prettier](https://github.com/prettier/prettier)

I ask because it was easy for me to accidentally add semicolons when writing code, but then remembering that the style for this repo is to not use semicolons.

Since we already have eslint setup, I could spin up a quick PR that adds [prettier as an eslint plugin](https://github.com/prettier/prettier#eslint)

**Comment by rauchg** [comment]
I'm strongly +1.

**Comment by leo** [comment]
We're already using prettier here?

**Comment by pranaygp** [comment]
Hmm, interesting. There's a script (in package.json) called "precommit" that should call prettier?

However, I was able to (completely accidentally) sneak in a line of code that used a semicolon. The prettier thing never got triggered.

https://github.com/zeit/now-cli/pull/953/files#diff-3a55845f63e7f7f9d9237b79de0d0ca1R134

I'll have a look

**Comment by rauchg** [comment]
Maybe `pre-commit` didn't get installed or needs to be upgraded:

https://github.com/zeit/now-cli/blob/canary/package.json#L138

**Comment by leo** [comment]
Exactly. You most likely skipped the commit hook (maybe you have `--no-verify` set by default)?

**Comment by pranaygp** [comment]
I think `pre-commit` doesn't actually get installed correclty when you use `yarn` instad of `npm install`
