### ISSUE TITLE
now: command not found

### ISSUE THREAD

**Issue by thinkwalnut** [vercel/vercel#958]
I did `$ npm install -g now` I am on Ubuntu 16.04
I Got this Code:
```
`/home/parjanya/.npm-global/bin/now -> /home/parjanya/.npm-global/lib/node_modules/now/download/dist/now

> now@8.3.11 postinstall /home/parjanya/.npm-global/lib/node_modules/now
> node download/install.js

> For the source code, check out: https://github.com/zeit/now-cli

> Downloading Now CLI 8.3.11 [====================] 100%

/home/parjanya/.npm-global/lib
`-- now@8.3.11 
`
```

now I did  `$ls`
I got: `index.js  node_modules  package.json`

then i did: `$ now`

**But it doesnt work**, gives me this:
```
No command 'now' found, did you mean:
 Command 'nw' from package 'netrw' (universe)
 Command 'new' from package 'nmh' (universe)
 Command 'sow' from package 'ruby-hoe' (universe)
 Command 'nop' from package 'graphviz' (main)
 Command 'cow' from package 'fl-cow' (universe)
now: command not found
```

**Comment by leo** [comment]
Can you please check if other globally installed npm packages are accessible?

E.g. - try installing `serve`: `npm install -g serve`

If this doesn't work, npm's binary directory is not included in your path or the binaries aren't being linked to your binary directory correctly. In both cases, you need to adjust your npm config.

**Comment by thinkwalnut** [comment]
Oh! i tried the command you said, I got this:
```
No command 'serve:' found, did you mean:
 Command 'server' from package 'rsplib-legacy-wrappers' (universe)
serve:: command not found

```

I have no idea how to config npm to run now
Can you point me to help please @leo

**Comment by leo** [comment]
@thinkwalnut Firstly, try installing Node.js again - it will set up the right paths. Try clicking the right green button [here](https://nodejs.org/en/). Once the installation is completed, try installing serve or now again.

**Comment by wenwuwu** [comment]
I am having the same problem. Pretty suck since the first step got stuck.
