### ISSUE TITLE
Support yarn package aliases

### ISSUE THREAD

**Issue by slorber** [vercel/vercel#960]
Hi,

I need yarn for my project because of a feature unsupported in npm which permits me to run the same library in 2 distinct versions, due to dependencies requiring different versions:

```
    "babel-core": "^6",
    "babel-core-5": "npm:babel-core@^5",
```

This works on `yarn install`, but it fails when trying to publish on `now`

**Comment by mxstbr** [comment]
This works perfectly fine for me: (note though that I'm not installing the same module twice, I only alias it once)

```JS
"draft-js": "npm:my-fork"
```

You just have to make sure to push the `yarn.lock` to `now` so that it uses `yarn` and not `npm`. (I'd love an option to force it to use yarn though)

**Comment by leo** [comment]
Now that we're using out-of-the-box Yarn and NPM (as per [Now 2.0](https://zeit.co/blog/now-2)), this is supported anyways.
