### ISSUE TITLE
Now-CLI Docker MultiStage Builds Error

### ISSUE THREAD

**Issue by idkjs** [vercel/vercel#962]
macOS Sierra
Node.js 8.9.0
Now-CLI 8.3.11

I have this project, https://github.com/idkjs/lafrenchtech-demo, deployed [here](http://lafrenchtech.azurewebsites.net/) on Azure via webhook to this [Docker Hub Image](https://hub.docker.com/r/idkjs/lafrenchtech-client/). I figured try it with Now-CLI to see what happens. I ran `now` in the directory with this docker file in it and go the below error. I then tried `now --force` Obviously, the Dockerfile builds and runs as shown in the links. Does deploying via now require a different structure? Does now not support multi-stage build? Thank you.

```
shingdev at cosmos in ~/code/lafrenchtech-demo/lafrenchtech-client on master
$ now
> Deploying ~/code/lafrenchtech-demo/lafrenchtech-client under idkjs
> Two manifests found. Press [n] to deploy or re-run with --flag
> [1] package.json         --npm
> [2] Dockerfile        --docker
> Warning! Skipping file /Users/shingdev/code/lafrenchtech-demo/lafrenchtech-client/build/static/js/main.08b5bcea.js.map (size exceeded 1MB)
> Warning! 1 of the files exceeded the limit for your plan.
> Please run `now upgrade` to upgrade.
> Ready! https://lafrenchtech-client-cpjtihmdca.now.sh (copied to clipboard) [1m]
> You (idkjs) are on the OSS plan. Your code and logs will be made public.
> NOTE: You can use `now --public` to skip this prompt
> Synced 35 files (1.07MB) [60s]
> Initializing…
> Building
> ▲ docker build
Sending build context to Docker daemon 1.175 MBkB
> Step 1 : FROM alpine:latest as build
> Error parsing reference: "alpine:latest as build" is not a valid repository/tag
> Error! The build step of your project failed. To retry, run `now --force`.
```

**Comment by rauchg** [comment]
This is a priority. We'll add support very soon.

**Comment by mbitch** [comment]
Hey guys, any news on Docker multi-stage build support?

**Comment by matheuss** [comment]
@teqhire almost there! News coming shortly 🙂

**Comment by Tabrizian** [comment]
Any new news on this topic?

**Comment by byCedric** [comment]
Just casually stalking this issue to see if there's news, is it implemented _now_? 😬

**Comment by Qix-** [comment]
Yes - multi-stage should be working in OSS (let me know here if that isn't the case).

Multi-stage for paid plans is coming soon. :)
