### ISSUE TITLE
Add an --overwrite flag to overwrite a project instance

### ISSUE THREAD

**Issue by ramadis** [vercel/vercel#972]
I understand why `now` favors  _idempotency_ on instance deployments as explained in several other issues. 

However I feel there are plenty of use cases where a developer would want a new deployment to use the same instance and share the same url (As seen by the amount of issues raised). I was wondering if maybe adding an `--overwrite` flag to deploy the application to the same instance would be the best solution.

Just want to bring the idea and open a discussion for the community.

**Comment by Qix-** [comment]
So the _idempotency_ is an optimization that can be overridden using `now -f`.

As for _immutability_, a subsequent deployment having the same nonced URL (e.g. `my-deployment-sdf9af8a.now.sh`) is pretty set in stone - what you're asking about is what `now alias` is for, and we're not really interested in changing that workflow or paradigm.

Hopefully this helps a bit :)
