### ISSUE TITLE
Community questions on stackoverflow.com

### ISSUE THREAD

**Issue by styfle** [vercel/vercel#977]
I noticed there is no tag on stackoverflow.com so I thought it might be good to have a place for the community to ask and answer questions.

https://meta.stackoverflow.com/questions/359174/creating-a-tag-for-zeit-now-a-cli-for-deployment

**Comment by Qix-** [comment]
I'll leave the community of SO.meta to decide :)

**Comment by styfle** [comment]
Does the zeit team prefer questions to be asked on SO or on GitHub issues (or maybe another place)?

**Comment by Qix-** [comment]
Well we haven't really seen much ZEIT-related activity over at SO, so it's kind of hard to answer that in a single breath.

Ultimately, we'd prefer that bugs and other issues are brought up here so we can address them. As well, we have quite the active community chat over at https://zeit.chat (on Slack) that most people seem to prefer :)

We're definitely not against or opposed to having questions pop up on StackOverflow, though :)

**Comment by leo** [comment]
Closing this now, following the comment above.
