### ISSUE TITLE
Underlying infrastructure questions and documentation clarification

### ISSUE THREAD

**Issue by jthegedus** [vercel/vercel#985]
Hey all, I've been looking at using Now (for SSR and compute - I've used if for static) for a while and was hoping to get some clarification and docs updated to reflect any answers (unless I've missed some crucial docs page or something).

The Installation section of the docs references [AWS Lambda](https://github.com/zeit/now-cli#aws-lambda-aws) followed by GCP and Azure. Does this mean that all Now deployments are run on ephemeral compute and thus are Google Cloud Functions and Azure Functions used for each respective providers? Since Dockerfiles are also handled by Now, what underlying tech of each platform is used since no ephemeral compute option allows for natively hosting docker containers? Are services like AWS ECS used here instead?

I appreciate the simplicity of simply logging into a provider and running `now` and flexibility of being multi-cloud with a simple list of deployment regions, but more transparency about the underlying infrastructure used with each provider would greatly reduce the amount of investigation required before Now is considered a viable deployment method for an individual or business.

Not only this, but the underlying tech obviously has some implications on the cost (Lambda vs ECS), so which tech aligns with which tier on the [pricing page](https://zeit.co/pricing)? I'd like to know before using the service if I will fall into the Premium tier or On-Demand tier. Is On-Demand purely for ephemeral compute deployed services?

**Crux of the question**
What configuration would I need to target my app for a particular type of deployment over another (Lambda vs Containers, instances vs on-demand)?

Apologies for the long question, I wish to learn more about Now and answer questions from curious friends without having to use every combination of deployment and application type myself.

**Comment by leo** [comment]
The underlying infrastructure completely changed with Now 2.0 – take a look here: https://zeit.co/blog/now-2
