### ISSUE TITLE
now-cli hangs when aliasing to custom domain

### ISSUE THREAD

**Issue by vladejs** [vercel/vercel#989]
I bought my domain on Bluehost, in order to alias my custom domain to my now deployment, I went to the CPANEL and changed the `A @` record to point to the ip address of `d.zeit.world`:
```
Host Record | Points to  | TTL 
@           | 96.45.81.1 |  14400
```

I also changed the `www CNAME` to `alias.zeit.co`.

After doing this I waited and tried to `ping mydomain.com`. It successfully replied with `d.zeit.world` IP.

Then I tried to alias my domain with the deployment:
```
now alias deployment.now.sh mydomain.com
```

And it just hung:
```
> mydomain.com is a custom domain.
> Verifying the DNS settings for mydomain.com (see https://zeit.world for help)
```

Any help would be appreciated.

> Edit.
After a while I got this error:
```
> Error! Unknown error: Error: Failed to fetch "http://mydomain.com"
Error: Failed to fetch "http://mydomain.com"
    at module.exports.Now.verifyDomain.domain.retry (/snapshot/now-cli/dist/now.js:4161:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

```

**Comment by vladejs** [comment]
Ok I got it all wrong. I just had to configure nameservers for the domain.
I did it and the alias was set successfully.

But still can't see the updated app on the domain.
When it says success on "Checking DNS propagation", do thatmeans it's working already?
Why it's nowt working?

**Comment by vladejs** [comment]
Also, I don't know why it didn't asked me to add a TXT record like is said in the documentation

**Comment by philmillman** [comment]
@vladejs try doing `now add domain yourdomain.com --force` once you've added the name servers, I've had to do this in the past

**Comment by goldensunliu** [comment]
I am experiencing hanging as well on 
```
Verifying the DNS settings for $MY_CUSTOM_DOMAIN (see https://zeit.world for help)
```
I have verified the Nameservers are pointed correctly to zeit's hosts.
tried with version 8.4.0 and 9.2.7

**Comment by goldensunliu** [comment]
After checking around, I am pretty sure now alias is supposed to fail for free tier deployments.
However, the now-cli just hangs and never returns anything useful. From the source code, there seems to be logic handling these error down the line:
``` javascript
if (code === 'custom_domain_needs_upgrade') {
          const err = new Error(
            `Custom domains are only enabled for premium accounts. Please upgrade by running ${chalk.gray(
              '`'
            )}${chalk.cyan('now upgrade')}${chalk.gray('`')}.`
          )
          err.userError = true
          return bail(err)
        }
```
https://github.com/zeit/now-cli/blob/57943d0f0a9c9659990bbc3888e4e5ae193e5577/src/providers/sh/util/alias.js#L153
but it seems like the code never got there or some error got swallowed in `maybeSetUpDomain` in file `src/providers/sh/util/alias.js`

**Comment by TooTallNate** [comment]
Closing since aliasing to a custom domain is now allowed on the free tier.
