### ISSUE TITLE
`now-macos` took up all my disk space overnight

### ISSUE THREAD

**Issue by vjpr** [vercel/vercel#996]
In `/private/var/folders/kp/06ys69nn6hq9k23cv0xxn19m0000gn/T` (~250GB) there are 1000s of directories named `tmp-7778xxxxxxxxx` (x's are random chars), each containing `now-macos` of size 59.9MB.

I think this might be an issue with the update mechanism.

Can you confirm that this is where now downloads its updates to?

**Comment by Qix-** [comment]
Thanks for the report - this is alarming indeed. I'll get someone right on it.

Needless to say, feel free to `rm -rf` that temp directory :)

**Comment by leo** [comment]
Closing in favour of https://github.com/zeit/now-desktop/issues/417 - this is an issue with Now Desktop, not Now CLI. Thanks for reporting!
